### ISSUE TITLE
Allow CanvasItems to inherit parent's visibility layer

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot-proposals#10014]
### Describe the project you are working on

I'm making an FAQ for the community of commonly asked questions and problems users have with working with parallax in Godot.

### Describe the problem or limitation you are having in your project

When I started making a demo to show how to use parallax within a split screen game. I realized there's no reasonable way to have a canvas item show in one viewport but not another.

The current steps to achieve this is:
1. share the same `World2D` between the two viewports.
2. set the first Viewport's canvas cull mask to layer 1.
3. set the second Viewport's canvas cull mask to layer 2.
4. set the visibility layer of every canvas item and every descendant's that you want to appear only in the first viewport to layer 1.
5. set the visibility layer of every canvas item and every descendant's that you want to appear only in the second viewport to layer 2.
6. set the visibility layer of every canvas item and every descendant's that you want to appear only in both viewports to 1 and 2.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an `inherit_visibility_layer` property to canvas items. `false` will use the current visibility layer and `true` will use its parent's visibility layer. This means instead of having to set each canvas item and all its descendants, you just set a common parent to `false` and set the visibility_layer there.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Creating a draft PR we can discuss. Feel free to give input. It seems like the ideal behavior would be to have `true` as the default, but that would be a compatibility breakage. We could start by having it `false` by default and add a project setting that could be removed when we're okay introducing the compatibility breakage.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's absolutely doable right now, but requires explicitly setting the visibility_layer of almost every canvas item in a game, which is a rough ask.

### Is there a reason why this should be core and not an add-on in the asset library?

CanvasItem is part of core.

EDIT: Updated to match PR

**Comment by kleonc** [comment]
> ### Describe the feature / enhancement and how it helps to overcome the problem or limitation
> 
> Add a `visibility_layer_mode` to canvas items, with two options: `Explicit` and `Inherit`. `Explicit` will use the current visibility layer and `Inherit` will use its parent's visibility layer. This means instead of having to set each canvas item and all its descendants, you just set a common parent to `Explicit` and set the visibility_layer there.
> ### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
> 
> Creating a draft PR we can discuss. I'm not set on the name or the enum labels, so feel free to give input. It seems like the ideal behavior would be to have `Inherit` as the default, but that would be a compatibility breakage. We could start by having it `Explicit` by default and add a project setting that could be removed when we're okay introducing the compatibility breakage.

Without compat breaking indeed `Explicit` would need to be the default and hence setting things to `Inherit` could be quite a nightmare usability-wise (without e.g. a custom plugin). Better than copying layers from the parent manually like currently but still cumbersome. So the question is whether compat breaking is ok here, otherwise it will be not too user friendly.

Alternatively, maybe it could be done similarily to e.g. `CanvasItem.texture_filter`, so `INHERIT` would be for inheriting the visibility layer mode instead of inheriting the visibility layer itself. Such mode-inheritance would be implemented only in the CanvasItem node (not within the RenderingServer), such `INHERIT` could be the default value, and there would be a project setting (with the default value set to preserve compatibility) used by the root Viewport for propagation (meaning a property like `Viewport.canvas_item_default_visibility_layer_mode` would need to be added).

This would allow both:
- preserving compatibility,
- changing the behavior for all CanvasItem nodes (within the root Viewport) to the new mode by changing a single project setting.

So `enum CanvasItem.VisibilityLayerMode` would have values like (example naming; intuitive names is definitely a problematic part here):
- `INHERIT` (default) - uses the same **mode** as the parent (CanvasItem/Viewport, taking into account `CanvasItem.top_level`).
- `OWN` - uses item's own `visibility_layer` (same as yours `Explicit`).
- `PARENT` - uses the visibility layer used by the parent (same as yours `Inherit`).

Also potentially other modes like `OWN_{AND|OR}_PARENT` doing bitwise and/or on relevant layers could be added on request (not sure if they'd be useful).

Both `enum RenderingServer.CanvasItemVisibilityLayerMode` and `enum Viewport.DefaultCanvasItemVisibilityLayerMode` would have the same values as `enum CanvasItem.VisibilityLayerMode` but without `INHERIT`.

(Not convinced about this, just throwing another idea. :upside_down_face:)

**Comment by markdibarry** [comment]
There is a workaround to this in the closing comment for [#95952.](https://github.com/godotengine/godot/pull/95952) This would be down the road, but I'm planning on making a new proposal and PR to align visibility layer systems and make them more approachable for users. I'll link this when the time comes.
