### ISSUE TITLE
ItemList add_item and add_icon_item indices

### ISSUE THREAD

**Issue by Ternvein** [godotengine/godot-proposals#101]
**Describe how this feature / enhancement will help your project:**
Makes work with `ItemList` more obvious by returning added item index.

**Describe implementation detail for your proposal (in code), if possible:**
`var index = $ItemList.add_item(...)`
`$ItemList.set_item_tooltip(index, ...)`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
`var index = $ItemList.get_item_count()`
`$ItemList.add_item(...)`
`$ItemList.set_item_tooltip(index, ...)`

**Is there a reason why this should be core and not an add-on in the asset library?:** 
It's too basic feature.

Currently both `add_item` and `add_icon_item` functions return `void`. It won't break compatibility much, but will make setting up `ItemList` more obvious. Every item-related function in `ItemList` works with indices, except for `add_item` and `add_icon_item`.

I can make a pull request when I'll have some time.

**Comment by Zylann** [comment]
Every single time I add an item to an `ItemList`, the code ends like this:
```gdscript
var index = item_list.get_item_count()
item_list.add_item(...)
item_list.set_item_metadata(index, ...)
...
```
Unless the list is not interactive or we use the *displayed text* as identifier, the first line is always required.

If we do a parallel with `Array.append()`, this one doesn't return the index, which is fine, it's just a simple container after all. So why `ItemList` would? Because `ItemList.add_item` *constructs* items, it's not adding an item you had in a variable already. So the only way to modify it is by index, using API functions for various of its properties.

In that regard, returning the index would be helpful. It has only one design downside: it hides the fact items are accessed by index (and not by "some unique ID").

**Comment by YuriSizov** [comment]
Since there doesn't seem to be much traction and the workaround provided by both OP and Zylann is perfectly fine and costs only a line of code, I think it's safe to close it.

**Comment by Jaland** [comment]
I would like to re-examine this proposal. I think it could also be more easily fixed if I could just add an `Item` object that included the tooltip, metadata, etc... Having to hunt down the index really makes the ItemList object hard to use and the code associated with it messy.

**Comment by YuriSizov** [comment]
It's usually not desirable to have methods that take too many arguments.

**Comment by Jaland** [comment]
Sure but why bother including metadata within a list item, but then making it such a pain to include that metadata?

I have not done C++ in a while, but couldn't we allow a second add_item method that takes a paired-down version of an object that includes Metadat/Icon/Tooltip information?
