### ISSUE TITLE
Don't autocomplete on name declaration

### ISSUE THREAD

**Issue by Foxomat** [godotengine/godot-proposals#10382]
### Describe the project you are working on

a point and click adventure

### Describe the problem or limitation you are having in your project

autocomplete popping up when it doesn't make sense:
when declaring a var, signal or const or something like that, autocomplete pops up, but in that case you want to define something with a new name, not reference something else.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

choose more carefully when autocomplete appears - for example not when declaring a var, signal or const

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

when declaring a var, signal, const or anything new, don't let autocomplete pop up

### If this enhancement will not be used often, can it be worked around with a few lines of script?

one can always ignore bothersome things of course, but still...

### Is there a reason why this should be core and not an add-on in the asset library?

it's about core usability

**Comment by Calinou** [comment]
This seems to be how VS Code's autocompletion works:

https://github.com/user-attachments/assets/2392f134-d5da-4a04-9552-32e63e652594

**Comment by HolonProduction** [comment]
I can't talk for VSCode but I assume this is about the builtin editor. In that case this was a bug which is fixed in 4.3:
https://github.com/user-attachments/assets/d1f49af8-7cd3-4d47-9602-4902cc5417de

An additional API isn't needed, the completion window should just not be visible if no options were added. This was done in 4.2 and earlier were it would keep open with the last non empty list of options.

**Comment by HolonProduction** [comment]
Closing this as completed in 4.3 as per my above comment
