### ISSUE TITLE
Implement drag-and-drop for NodePaths

### ISSUE THREAD

**Issue by MartinHaeusler** [godotengine/godot-proposals#1042]
**Describe the project you are working on:**
3D puzzle adventure

**Describe the problem or limitation you are having in your project:**
When you have a `[Export] public NodeType myPath` field in your script, then the editor brings up a popup dialog when you click on it, allowing you to pick a node. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be much more convenient if I could simply drag a node from the scene tree over to the inspector field and drop it there (the way it works in Unity).

This would require that the editor can be "locked", i.e. it must not immediately switch to the selected node, otherwise nodes cannot be dragged into inspector fields. Unity supports both locking the inspector to a certain scene element, and also only displays the editor for an element if you *click* on it, not if you click-and-drag it.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/16356998/84440437-48f02600-ac3a-11ea-8e1f-50bed7180d2d.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, because it concerns only the editor. The "workaround" is to use the popup dialog, which is distracting for the user due to the context switch. They may have their eyes on the node in the scene tree already, click on the "assign" button and get an entire new tree to browser through, just to find the same item again.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Again, entirely editor-related and definitely a core feature.

**Comment by KoBeWi** [comment]
> Unity supports both locking the inspector to a certain scene element, and also only displays the editor for an element if you click on it, not if you click-and-drag it.

Solving this would also fix https://github.com/godotengine/godot/issues/33704

**Comment by MartinHaeusler** [comment]
For me, this issue is really highly critical - a term I don't use lightly. The reason is simple: productivity. If there's one feature I use literally all the time in the Unity editor, it's this one (granted: I mostly do coding, ymmv). Godots current solution unfortunately is very clunky and inefficient (in terms of time spent per action).

**Comment by avencherus** [comment]
At one point I thought that brush icon was something like:  "Click it, then click the node you want to generate a link."  After a closer look I realized it just clears the assignment.

This is definitely a sore spot for us too, we try to avoid things with NodePath requirements as much as possible, because it could lead to a lot of time spent going through these windows, and it becomes very error prone when doing dozens or more of them.

I would add to this, that they're also very brittle in the sense that they don't update when the node they reference is moved or renamed.  A simple edit, means going back through the process again.

If you have many, and a parent is changed, they can potentially all break and to be tediously relinked.

They're a nice idea, but it really needs some reworking to be practical to use in large projects.

**Comment by barefists** [comment]
+1 to this. Would really save a lot of time.

**Comment by Calinou** [comment]
@barefists Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by robbertzzz** [comment]
I've got a love-hate relationship with locking the editor in unity, it's easy to forget that it's locked. I'm not sure whether that would be the best solution, I haven't missed that specific feature in Godot. Just not changing the inspector until a mouse up event (so only trigger it after a full click) is much better in my opinion.

**Comment by idchlife** [comment]
I'm making custom waypoint system and I need to link multiple waypoints to multiple waypoints (e.g. like in cs 1.6 PodBot waypoints).

It's not possible to keep system flexible if I have to manually assign nodes from the hierarchy and not drag-dropping them, unfortunately. Maybe I'm missing different approach? 

Right now I'm basically forced to check before assignment - which nodes I should use and I don't write custom names for them (e.g. Path1 Path2 Path3) since there can be like TONS of nodes.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/4563032/140943782-02f4086c-79f2-4086-984b-d5aa5e044261.png">


<img width="250" alt="image" src="https://user-images.githubusercontent.com/4563032/140943859-a27dc13c-61ab-4992-aeac-4841bcaeb36b.png">

**Comment by Domigome** [comment]
> w I'm basically forced to check before assignment - which nodes I should use and I don't write custom

I think would be better solution that the inspector only changes after mouse is released. Thus, no need to lock the inspector.

If I just click on a object that I'm willing to drag, as far as I keep the mouse pressed, the inspector keeps the same. 

Even Unity does not have this feature, but I really think this way is really simple and useful.
