### ISSUE TITLE
Ability to export Node types instead of just NodePaths

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1048]
**Header/Notice**: This is a revival of the [old issue here](https://github.com/godotengine/godot/issues/7821). Mentioning @Zylann as they are the creator of the old issue.

**Describe the project you are working on:**
This is useful for all project types, but it is particularly useful with things like UI with lots of containers and hierarchy.

**Describe the problem or limitation you are having in your project:**
If someone would like to export a reference to a node that can be edited from the editor, there is a lot of boilerplate script code for each variable and the editor-side is not necessarily intuitive. (Clicking the `NodePath` variable and selecting a node rather than just dragging the node into the space).

Previous code example:
```py
@export var my_label_path: NodePath
@onready var my_label: Label = get_node(my_label_path)
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The feature enhancement I (and others) propose is to have a shorter syntax that handles the `NodePath`s. Basically, a simpler code format that behaves the same as the previous code.

New code proposal:
```py
@export var my_label: Label
```

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See the code proposal above.
![dragging a label node into the export property](https://user-images.githubusercontent.com/14253836/84548560-7fc24c80-accb-11ea-8693-59ea98208844.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This can be worked around in only two lines, but those lines are very redundant, especially in cases where several nodes are exported. Also, this is an extremely common use-case that has come up several times in most (if not all) of my projects.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is core in the script and not sure if it is possible to work around with an add-on.

**Comment by creikey** [comment]
I think I am against having the exported property function the same as an exported resource, where there is a dropdown for new etc. , would be better for it to functionally act the same as a NodePath export

**Comment by creikey** [comment]
I will look into drafting a PR for this soon

**Comment by creikey** [comment]
I have completed the basic functionality, however I think it's a little bit wonky, and have not implemented the setgets originally mentioned by @Zylann

**Comment by creikey** [comment]
I think the biggest issue with being able to update the exported nodepath in real time is that there would need to be some sort of generic templated setgets for every single export of a type, where the setter would:
 - only accept nodepaths
 - if I'm not in the tree return
 - if I am in the tree, fetch the node, ensure it's not null, and check its type, and if all is good cache it in a temporary variable
and the getter:
 - if the temporary variable is null, return the nodepath
 - if it's not null, return the temporary variable

All of this could possibly be encapsulated in either a new variant type or object maybe

**Comment by creikey** [comment]
The really hairy part about the setter only taking a NodePath is that then the variable cannot be reassigned with a new instance of its Node. Maybe the setter needs to be able to take a NodePath, then it will run get_node, or another instance of its script, then it will simply assign.

**Comment by TheDuriel** [comment]
After some discussion with creikey:

Goal: Allow exporting of NodePath properties which automatically resolve to a reference to the Node. Condensing the acquisition of the path, and storage of its return value to one line.

How, part 1:

`export(NodeRef, <Type>) var foo: <Type>`

This creates a NodePath dialogue in the Inspector.

When the User selects a Path, get_node() is called, and the returned value is set to foo.

How, part 2:

When a Scene is saved, since Object References can not be serialized. The relative path to the node is gotten and stored instead. Using Node.get_path_to()

When a Scene is loaded, and a properties type or export hint is not of type NodePath, but a NodePath is found in the file. This path is resolved upon onready.

How, part 3:

To preserve RemoteTree functionality, like when loading a Scene: When a Node Reference would be remotely set. Instead set the NodePath, then resolve it in the running Game.

---

The Second half of Part 2, and Part 3, can also be described thus:

When setting a value to a property. If that value is a NodePath, and the Type hint is not. Resolve the path, then set the result instead.

**Comment by Shadowblitz16** [comment]
one of the issues with nodepaths is that they are relative to the node the script is on.
this makes it hard to actually implement swapping logic in which a node's parent changes since the node path could no longer be pointing to the right node of even one that exists.

passing a reference to a node would be much better as it would no longer be tied to the node the script is on and you would directly be able to access its properties and methods as well

however I disagree with this..
I don't think `export(NodeRef, <Type>) var foo: <Type>`
I think it would be like so..
`export(<Type that inherits from node>) var foo`

**Comment by TheDuriel** [comment]
export(<type>) will export a field for Script Resource extending that type. This is wrong.

var foo: <type> this is required as otherwise the value is not typed at all from the IDEs perspective.

Ultimately

export(NodePath) var foo: <type> would be preferred.

**Comment by nathanfranke** [comment]
Yes, we know that you can't export a reference. That's why this issue exists...

**Comment by Zylann** [comment]
This original issue existed because the use case of connecting up an existing node directly to a *node* script property isn't as straightforward as it could be. It works in a certain way because it's only about setting a reference to a node that already exists and can be referred to in `tscn`.

I see "reference" mentionned but we need to be careful about what we mean by that, so to clarify just in case:
Types inheriting `Reference` but *not* `Resource` are a bit different: wanting to export `Reference` types assumes you can *create* an instance of it *on-site* (cuz where else would you grab it from if it's neither a node nor a `Resource` file?), and that they would be serialized together with the scene or resource owning the property. Which is, basically what an embedded `Resource` does.

> however I disagree with this..
`export(NodeRef, <Type>) var foo: <Type>`
I think it would be like so..
`export(<Type that inherits from node>) var foo`

I tend to agree to that. Why would the user be required to type `NodeRef` explicitely? Can't the engine figure this out from the specified type? If it's `Node`, do the node behavior. If it's `Resource`, do the resource behavior. Else, error.
If the reason is because serialization is different, I'd say this is implementation detail. The same happens in Unity, yet there is no difference in scripts. So the question here would rather be if we want to force the user to be explicit or not.

**Comment by name-here** [comment]
At present, as far as I know, there's also no way to make the editor only let you set the exported NodePath to a certain Node type.  Built-in Node types seem able to do this (see Node A and B properties on Joint2D that only accept RigidBodies, for example), but, as far as I know, there's no way to do it through script.

**Comment by jordo** [comment]
It seems a bunch of users doing these one-liners:

`export(NodePath) onready var _dependent_node = get_node(_dependent_node) as Node2D`

It's nice to represent a dependency in one line like this, but also this is way too much code to express this.   It also works (_dependent_node is either a valid Node2D or not).  It would maybe be nice to perhaps syntactic sugar this in 4.0, if this is the easiest solution to expressing an external reference dependency, but only being able to serialize a NodePath.  

But ya, I agree, something better would be a NodePath + Type.  Maybe type information could somehow be added to path syntax (prefix or suffix or something).    example:   'res://::Node2D::./../nodes/someNode2D'.

**Comment by Zylann** [comment]
Unfortunately that code seems to exploit a flaw in GDScript. If you do this in a `tool` script it will break because `_dependent_node` will no longer contain a nodepath after being assigned. And similarly, assigning it will cause a typing error because `NodePath` is not a `Node2D`.

**Comment by jordo** [comment]
This works fine for static typing.  And any script or tool script will break if _dependent_node isn't valid.  Exploit or not, it seems a lot of users are using that code to setup a dependent reference in a single declaration.  

And ya I agree, such a feature doesn't need.  I'm just more or less commenting on whats being done in the wild right now.

**Comment by Zylann** [comment]
> any script or tool script will break if _dependent_node isn't valid

It will break if the tool script requires the node to be set. That's precisely why I mention tool scripts. Sure just adding `tool` works, but it will only have set `_dependent_node` to a `NodePath`, while the internal code expects it  to be a `Node2D`, that's what I meant.

> This works fine for static typing

In your scenario yes, but *theoretically*, not in editor. If you add a static type `_dependent_node : Node2D` while exporting as `NodePath`, the editor will try to set `_dependent_node` (which is `Node2D`) with a `NodePath`. That's obviously a type mismatch. If that doesn't fail then it's just another exploited bug where static typing has been forgotten to be checked.

**Comment by jordo** [comment]
> In your scenario yes, but _theoretically_, not in editor. If you add a static type `_dependent_node : Node2D` while exporting as `NodePath`, the editor will try to set `_dependent_node` (which is `Node2D`) with a value of type `NodePath`. That's obviously a type mismatch. If that doesn't fail then it's just another exploited bug where static typing has been forgotten to be checked.

Ya, again, like I mentioned this is more commenting on what users are doing.  Whether that's in theory or not, in practice it's obvious that people want to express this dependency as a single declaration.  And this is what's currently being used as a workaround as opposed to declaring & maintaining multiple variables to express a single dependency.    

I'm not sure if you'll be able to get rid of NodePath entirely in this proposal.  Important to be able to serialize the dependency in a way that will fail at runtime if the serialized path can't resolve to an actual node.  Also consider copy and paste working now with nodes, (I think copy & paste in the editor is purely in-memory, but I could be wrong).

**Comment by jordo** [comment]
Mostly users just want to export+assign and use the dependency immediately as a node reference in code.  They don't really care that under the hood it's serialized as a NodePath or whatever.  

But consider this:   If I export a NodeRef or is proposed and assign it to some sibling node, and the copy pasta this node into an entirely different scene what happens?  Which is why I'd argue NodePath or some underlying resource type is still what we want to use to implement this functionality.  Which then brings this full-circle to still doing something that is more syntactic sugar to accomplish what users actually want  (less boilerplate to express this type of dependency).

**Comment by Zylann** [comment]
> Important to be able to serialize the dependency in a way that will fail at runtime if the serialized path can't resolve to an actual node

There still has to be a nodepath in `tscn` and `PackedScene` because this is what identifies the node when it is not built in memory. Just like resources are represented as file paths, it doesn't mean they have to also be file paths in properties referencing them. A system like this usually won't have bad node paths because the editor simply won't let you do that. But if it it's not valid for any reason, same as resources: can't load it. Either fail to load the scene, print an error, or leave the property null.

> f I export a NodeRef or whatever type is proposed here and assign it to some sibling node, and then copy pasta this node into an entirely different scene what happens?

You can serialize the copied scene (so it becomes a nodepath, no longer an object in memory) and then deserialize into the destination scene. If what you copied had a path to a sibling that's not part of your selection, then deserialization won't assign the property and it will come up as null.
You could try looking up nodes in the scene as well and assign them if they happen to have the same path but I'm not sure it would be a good idea.

> Which is why I'd argue NodePath or some underlying resource type is still what we want to use to implement this functionality. Which then brings this full-circle to still doing something that is more syntactic sugar to accomplish what users actually want (less boilerplate to express this type of dependency).

Then that's a different feature: typing nodepaths. If you want this then the property will be a nodepath.

**Comment by TheDuriel** [comment]
My proposed approach already solves all this.

**Comment by jordo** [comment]
> You can serialize the copied scene (so it becomes a nodepath, no longer an object in memory) and then deserialize into the destination scene. If what you copied had a path to a sibling that's not part of your selection, then deserialization won't assign the property because it won't be within the data you copied, and it will come up as null.

You COULD do this, but last I checked this is not how copy/paste, undo/redo is done in the engine right now, and would be a very large undertaking to change this.  imo probably very unlikely to be implemented like this.  

TheDurial, I'm in agreement with your approach syntax wise, but I disagree that the path should be resolved/written at scene save/load time.  I think it should be resolved at assignment time.

**Comment by Zylann** [comment]
> You COULD do this, but last I checked this is not how copy/paste, undo/redo is done in the engine right now

Yeah... I don't like this tbh, that's one of the reasons. I had to deal with that stuff already in the past and that's how I solved it (it even worked across two editors)

**Comment by jordo** [comment]
> Then that's a different feature: typing nodepaths. If you want this then the property will be a nodepath.



It's not really a different feature as the tho functionalities in this proposal are pretty tightly coupled.  Export a Node and it's type, with automagic assignment in ready / onready. 


> Yeah... I don't like this tbh, that's one of the reasons. I had to deal with that stuff already in the past and that's how I solved it (it even worked across two editors)

I'm in 100% agreement with you on this one.  Command pattern for undo/redo should do 'serialize' based saving & copy memory.  But that's not how they did it (which is unfortunate).  But I know changing that stack will be pretty difficult at this point.

**Comment by Zylann** [comment]
> Export a Node and it's type, with automagic assignment in ready / onready.

How though? 

Looking back at Duriel's idea:

> When a Scene is loaded, and a properties type or export hint is not of type NodePath, but a NodePath is found in the file. This path is resolved upon onready.

By the time `onready` is called, the context that sets all the properties(`PackedScene.instance`) has already finished, and the property won't be valid until it gets added to the tree. Resolving in ready means the nodepath info has to outlive `instance()` somehow up to that point.

**Comment by TheDuriel** [comment]
Resolving the NodePath should be done by the node itself.

**Comment by aki-cat** [comment]
I don't know how nodes are serialized, but from what I gather from this discussion is that they're serialized by their path in the scene??? that sounds... not good?

Regardless of syntax, wouldn't it be better to have a reference to it that is independent of its path? Like imagine a scene's serialization first and foremost lists its nodes in a dictionary of unique IDs. Then ideally it could just represent the tree as a tree of those IDs. Then there could be a type/syntax sugar/something (idk what) that uses _that_ ID as a way to reference the Node. This is what Unity does, afaik.

I think it's important for types of node references be checked at editor-time, otherwise half of the usefulness of this proposal is kinda dead. I don't want to have to run the game to see that a reference to a node has broken. Static typing should do that for me.

**Comment by TheDuriel** [comment]
> I don't know how nodes are serialized, but from what I gather from this discussion is that they're serialized by their path in the scene??? that sounds... not good?

It is the only possible way. Given that it is a Tree Strucutre, read linked list, that is being stored here. Please everyone actually open up a .tscn file in a text editor and view how things are handled there.

There is no change required to how saving and loading nodes functions. The only thing that needs to be done, is to automatically resolve NodePaths when they are assigned to a variable. NodePath should be an entirely internal Resource invisible to the end user.

**Comment by Servail** [comment]
It's clear as day that NodePaths are useless and even bad for the dev. Only serialization can benefit (sort of) from them. So we must deal directly with (UIDed) node instances/locators and editor/scene system must handle serialization on save/load. I don't see any reason why this sturdy approach still exists tbh, maybe it's the situation where something that appears primitively simple is actually against the KISS principle, but then how is this unclear for smart people doing Godot's editor? 
P.S.: Also, I don't get why we still can't write a fine custom node in GDS/C#, without attaching script. Not speaking of attaching multiple scripts lol. All these criss-cross nodepath.getnode.getscripts... meh. Nuff said. Functionality that must be in editor years ago.

**Comment by Ansraer** [comment]
I was bored and reading through gdscript_editor.cpp when I came across `@export_node_path`. Based on my understanding of the source code it should implement what is requested here, shouldn't it? If not, what else would be required to fulfill this proposal?

**Comment by fire540** [comment]
So basically it's the same as a NodePath export but it automatically sets it to `get_node()` of it? That would be useful.

Right now I do this, which is messy and adds an extra variable and line:
```gdscript
export var node_: NodePath
onready var node: = get_node(node_) as Node
```

**Comment by Ansraer** [comment]
For the record: on the 22.2.2022 there was some discussion regarding this on rocketchat in #gdscript. The consensus was that this is a desired feature, but the implementation details are still a bit unclear.

https://chat.godotengine.org/channel/gdscript?msg=dMaetkhmJxXGGaR73

**Comment by TheDuriel** [comment]
```
User Facing:

export(Sprite) var my_sprite: Sprite

Or if we wish to be explicit:

export(NodePath, Sprite) var my_sprite: Sprite

This would expose a NodePath picker in the inspector, limited to the specified type.

export(NodePath, <Any>) may be neccecary for flexibility?

Implementation Concept:

There are two places in which behavior must be added.

When Serializing Scenes (in the Editor).

When Instancing a PackedScene.

Serialization:

In packed_scene.cpp

If SceneState::_parse_node

In the loop below 

List<PropertyInfo> plist;
p_node->get_property_list(&plist);

Check if an Exported property is a NodePath. Save the NodePath to the Node that the property currently contains.

This may actually be done in Node.cpp instead?

Instancing:

In node.cpp

In Node::_notification

At NOTIFICATION_READY

Check if an Exported property is a NodePath, get_node() that path and set the new value.
```

**Comment by Zylann** [comment]
I wonder again why node resolution has to wait all the way to ready at all... since the scene loader `instance()` already knows everything it needs to know to assign the instance to the property. No need to cache the path in the node, no need to re-resolve it for each instance.

**Comment by TheDuriel** [comment]
For this example I put it in ready, simply because it seems like a big hassle to do so in PackedScene and I couldn't find the place to put it.

**Comment by sairam4123** [comment]
I think this is all about exposing already present feature in Godot. You can always filter nodes by Type in the Node Selector panel.

**Comment by creikey** [comment]
Is this happening in 4.0 or not yet? I'd like to add it to 4.0 if it's not currently in the codebase and the gdscript source is settling down somewhat

**Comment by TheDuriel** [comment]
@creikey See https://github.com/godotengine/godot/pull/62185

**Comment by MartinHaeusler** [comment]
@akien-mga Yes please, we need this on the C# side too. The inability to type node paths properly is a big deal, and I'm very happy to see it's being addressed in Godot 4.

**Comment by Shadowblitz16** [comment]
wait what about exporting custom node types?
I tested it and it doesn't work.

**Comment by nathanfranke** [comment]
> Wait what about exporting custom node types defined with class_name? I tested it and it doesn't work.

Proposed here: https://github.com/godotengine/godot-proposals/issues/4785

**Comment by tjp1205** [comment]
I am currently on Godot 4.0 stable, where nodes can be exported and used in a running. However, when paired with the [Tool] attribute, the exported nodes would return null while the script is running in the editor. Is this intended, or is this feature not supported yet?
