### ISSUE TITLE
Ability to drag a tab into a new window.

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [godotengine/godot-proposals#10480]
### Describe the project you are working on

No actual project, just a general feature request to make working on games on multiple monitors easier.

### Describe the problem or limitation you are having in your project

Stuck in one window on a single screen.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Grab and drag a tab outside the main Godot window to create a new window of that single tab.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is a request for the Godot IDE itself.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think a library could do this.

**Comment by Calinou** [comment]
You can already split docks into their own window (click the three vertical dots next to each dock), along with the script/shader editor (click the "two windows" icon in their top-right corner). Note that you can't do this if **Single Window Mode** is enabled in the Editor Settings, or on Linux if using the native Wayland backend due to feature limitations.

Either way, more complete multi-window support is already being tracked in https://github.com/godotengine/godot-proposals/issues/1508, https://github.com/godotengine/godot-proposals/issues/7233, https://github.com/godotengine/godot-proposals/issues/7984 and others.
