### ISSUE TITLE
Implement a new `invalidated` signal for tweens

### ISSUE THREAD

**Issue by FabriceCastel** [godotengine/godot-proposals#10575]
### Describe the project you are working on

A Balatro-like

### Describe the problem or limitation you are having in your project

I've got a global animation queue system that queues tweens and triggers the next one when the `finished` signal is emitted for the last played tween. If a node the current tween is targeting gets `queue_free()`ed then the tween gets into a state where `is_valid()` returns `false` and `is_running()` returns `true`. The `finished` signal is never emitted (and that is supposedly *by design*, ie. not subject to change.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a new signal `invalidated` that is emitted if the tween changes from being valid to invalid would allow us to handle these edge cases without breaking backwards compatibility, and should be a fairly straightforward change to make(?)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

n/a, the feature ask is self-explanatory

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, the workaround I've had to resort to is to add a check against the currently running tween within a `func _process(delta)` defined on my animation queue singleton. It's... *fine* but I really shouldn't have to check that every frame, reacting to a signal would be much cleaner.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a change to a core class, `Tween`

**Comment by Alzurana** [comment]
Hello there. FabriceCastel and I already talked about this on reddit and I devised a test script for devs to analyze the issue. I think it goes deeper than just a missing signal. The very way how await and tweens are supposed to be used to form coroutines has some serious implications. Lets lead with the example script:

```
extends Node


@onready var _coroutines_open: int = 0


func _process(_delta: float) -> void:
	# normal instantiation
	var object := Node2D.new()
	add_child(object)
	# we create a coroutine that will create and await a tween on the passed object
	tween_coroutine(object)
	print("Coroutines currently open: ", _coroutines_open)
	# we free the object before the tween could finish
	object.queue_free()


func tween_coroutine(object: Node2D) -> void:
	# simple counter for how many coroutines are open
	_coroutines_open += 1
	await get_tree().create_tween().tween_property(object, "global_position", Vector2(1.0, 1.0), 1.0).finished
	_coroutines_open -= 1

```

In order to test this: Make an empty scene, attach this script to the root and run it.

So, basically, we create a node, tween it's position in a coroutine and await completion. We then immediately free the node on the same frame.

This results in the warning "Target object freed before starting, aborting Tweener." which I only get if I delete on the same frame. No warning occurs when I delete the object on the next frame, however. The tween also does not notify me that it's target object has been deleted. However the coroutine is forever stuck (finished never emits) and uses memory indefinately. I had this run for 2 minutes at 144 FPS and godot allocated 100-200 MB more RAM during that time.

I want to put emphesis that it is normal workflow in godot to just await multiple tweens for all kinds of reasons. If, in any case, the tweens target gets deleted, whatever awaits said tween enters limbo and is forever stuck. I feel like this is oversight. It does not cause an error messages to appear, it's basically a silent memory and frankly "logic" leak since said methods are getting stuck.

I would argue that "finished" should always trigger when the tweens time runs out to prevent this. Alternatively, a tween could also be considered "finished" when it's target got deleted. It has nothing to do anymore, it's clearly done. This would also apply for the case of deletion on the same frame, which causes the warning.

I'm pretty sure godot devs and vertarans might even come up with a better solution to this. I do have to disagree with the "invalidated" signal proposal as the only solution. It is interesting to have that functionality and would be useful in general but it makes using tweens safely simply too complicated in day to day use. I'd propose to just fire the finished signal and make the documentation reflect this.

**Comment by FabriceCastel** [comment]
I would personally +1 having `finished` get emitted in this case instead of adding a new dedicated signal (that is the behaviour I expected to see originally), assuming there's no strong opposition to the idea. It's technically not backwards compatible, but I'm not sure what code genuinely relies on tweens *not* finishing when they get into this bad state..

**Comment by Alzurana** [comment]
blackshift on discord was very helpful with this. I'll document the approach to fix this here, and create a PR for it later.

They pointed out that calling _finished() before this line would resolve the issue.
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/scene/animation/tween.cpp#L582


This causes the Tweener to finish before it's timeout, however, that is not a problem because it already returns false at this point, signaling to the caller that it indeed finished.


The call to the Tweeners can be found here:
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/scene/animation/tween.cpp#L344


This fix should probably also affect MethodTweener and CallbackTweener here:
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/scene/animation/tween.cpp#L709
and here:
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/scene/animation/tween.cpp#L773

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/96216.
