### ISSUE TITLE
Add a option for SkeletonIK3D can calculate IK after set_bone_pose

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#10584]
### Describe the project you are working on

A Third Person Game can custom character.

### Describe the problem or limitation you are having in your project

For my project, i want custom my character, like arm an leg length.
I found a way was set_bone_pose, it work very nice.
code:
```gdscript
@tool
extends Skeleton3D

@export_range(0.0, 1.0, 0.01) var value := 0.0:
	set(val):
		value = val
		if is_node_ready():
			update_bone()


func update_bone():
	var p_idx = find_bone("Bone.001")
	var s_idx = get_bone_children(p_idx)[0]
	
	var p_t = get_bone_rest(p_idx)
	var t = get_bone_rest(s_idx)
	
	set_bone_pose(s_idx, t.translated(Vector3(0,1,0)*value))

```

![GIF 2024-8-29 11-03-31](https://github.com/user-attachments/assets/bc65aba3-23f6-406a-bad0-2abd8bae58cf)

but after set_bone_pose, I found the IK was not correct.
not set_bone_pose:
![GIF 2024-8-29 11-06-38](https://github.com/user-attachments/assets/d12126cc-afbe-42c1-8975-1075d5b45163)
after set_bone_pose:
![GIF 2024-8-29 11-07-48](https://github.com/user-attachments/assets/d6999c26-517b-43fa-98c8-8b7c470e13fc)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I guess, the IK calculate always use bone's reset pose.
IMO, can add a option, let IK calculate can be after set_bone_pose.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

none

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no, i can't a way to impliment this.

### Is there a reason why this should be core and not an add-on in the asset library?

It shoud be core.

Test Project: [IkTest.zip](https://github.com/user-attachments/files/16794975/IkTest.zip)

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
Already exist in 4.3, see https://godotengine.org/article/design-of-the-skeleton-modifier-3d/.

**Comment by CsloudX** [comment]
@TokageItLab Thanks.
Sorry my english was  not good.
is it mean I should change the order between SkeletonIK and AnimationPlayer?
if it is, for my project, the scene was extend from LengthTest.glb. it was exported by blender.
so i can't change the Skeleton and AnimationPlayer order. and the SkeletonIK must be a child of Skeleton.
Maybe it can be change order in runtime. but I can't priview in Editor.
Or I can make local, but it will broken my extends relationship.

**Comment by TokageItLab** [comment]
> I guess, the IK calculate always use bone's reset pose.

If you are using the built-in SkeletonIK3D, this is incorrect in Godot 4.3. Also 4.2 does not really have that problem either, since the Process Order of the Node is set to 1 by default.

If you are developing your own IK, you must extend SkeletonModifier3D and do get/set_bone_pose in the virtual method as shown below in the article there.

**Comment by CsloudX** [comment]
I'm test it use 4.3. and use built-in SkeletonIK3D. the default behavior was like I'm report.

**Comment by TokageItLab** [comment]
Since IK is definitely calculated after set_bone_pose, s0 I think the IK solver is simply not resolving the result in the way you want. You should be able to confirm that changing bone_rest does not change the behavior.

**Comment by CsloudX** [comment]
All code was here:
```
@tool
extends Skeleton3D

@export_range(0.0, 1.0, 0.01) var value := 0.0:
	set(val):
		value = val
		if is_node_ready():
			update_bone()


func update_bone():
	var p_idx = find_bone(\"Bone.001\")
	var s_idx = get_bone_children(p_idx)[0]
	
	var p_t = get_bone_rest(p_idx)
	var t = get_bone_rest(s_idx)
	
	set_bone_pose(s_idx, t.translated(Vector3(0,1,0)*value))
```
I'm not set_bone_rest.
I'm uploaded the test_project, maybe there was a error config in my project.

**Comment by TokageItLab** [comment]
The proposal "to allow IK computation after set_bone_pose" is definitely complete by 4.3, and IK computation can definitely be done after set_bone_pose.

I have confirmed that closing the scene and reopening it changes the result, so this is probably a bug with the odd timing of the caching of IK3D poses, and this should be sent to https://github.com/godotengine/godot/issues as a simple bug report, not a proposal.

However, since we plan to remake IK, we do not plan to fix the existing SkeletonIK3D; current SkeletonIK3D is deprecated and unmaintained, and the problem remains in its old behavior.
