### ISSUE TITLE
Expose support for packing/unpacking ZIP archives to the scripting API

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot-proposals#1069]
**Describe the project you are working on:**
Node based image and material editor.

**Describe the problem or limitation you are having in your project:**
I would like to be able to pack and unpack user configuration to a single zip file. I will for sure find another usage for it later.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I will be able to do what I cannot do now.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Inspiration can be taken from gdunzip (link below). Zip functionality can be a method in File class (which could zip files and directories).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It cannot be done with a few lines of script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The plugin in GDScript was made but it's only unzip, it doesn't do CRC checks and it's not very fast. The engine already uses some C library (still minizip?) so it shouldn't be hard to expose it to GDScript to get native performance.

Related links [3701](https://github.com/godotengine/godot/issues/3701), [22440](https://github.com/godotengine/godot/issues/22440) and [gdunzip](https://github.com/jellehermsen/gdunzip).

*Bugsquad edit (keywords for easier searching): extract, create*

**Comment by Calinou** [comment]
There's a pull request implementing this feature: https://github.com/godotengine/godot/pull/34444

**Comment by goatchurchprime** [comment]
bzip (brotli zip) might be a more up to date standard to aim for that is quite widely used and is good for compressing small snippets because it uses a common dictionary.  I've encountered its in pointclouds files from [potree](https://github.com/potree/potree)

There is a Javascript implementation of the decompress function here: 
https://github.com/potree/potree/blob/37dc46a25ca56683e216c973dd117bc68b75ab0f/libs/brotli/decode.js

It looks like this may have been created by porting the C-code to Haxe and then converting from that into Javascript:
https://github.com/dominikhlbg/BrotliHaxe  There's then a Haxe converter that outputs Godot/C#.

(Or I could just work out how to compile C++ asset add-on modules into Godot)

**Comment by ssokolow** [comment]
@goatchurchprime That would be useless for various plans I have for this.

1. When I use Zip as a container for something like a custom level and all its assets, compression *is* desirable, but my number one goal is accessibility to players without special tools.
2. If I want to write support tooling in Godot, Zip is the popular choice for various existing formats to use as containers, not brotli.

Heck, some minimum level of Zip support comes standard in OSes these days. while 7zip only supports brotli in any form via a [fork](https://github.com/mcmilk/7-Zip-zstd).
