### ISSUE TITLE
Add a setting to change the script editor autocomplete shortcut (tab, enter, tab or enter)

### ISSUE THREAD

**Issue by StormFalcon32** [godotengine/godot-proposals#1084]
**Describe the project you are working on:**

This applies to all projects

**Describe the problem or limitation you are having in your project:**

Often times I will try to make a newline, and accidentally accept an autocomplete suggestion

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Allowing the user to change the shortcut to accept autcomplete can let them avoid this issue by setting it to tab only, or whatever other shortcut they are comfortable with, instead of enter or tab.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Adding an option for "autocomplete accept" to the shortcuts menu

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, it's built into the editor

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's a core part of the editor

**Comment by Calinou** [comment]
Definitely, I'd prefer using only <kbd>Tab</kbd> to accept autocomplete suggestions myself.

**Comment by Calinou** [comment]
For the record, this is currently hardcoded here: https://github.com/godotengine/godot/blob/e773664f26ced3587a5a5d9caa494b96df00e3f4/scene/gui/text_edit.cpp#L2638

Since this isn't editor-specific code, [we should avoid adding yet more editor-specific code to it](https://github.com/godotengine/godot/issues/29730). Therefore, this change will probably have to wait for the [TextEdit refactor](https://github.com/godotengine/godot/issues/31739).

**Comment by Paulb23** [comment]
Implemented by godotengine/godot/pull/43663 and godotengine/godot/pull/44181
