### ISSUE TITLE
Allow to send body_entered type signals to Raycast nodes

### ISSUE THREAD

**Issue by xavierocampos** [godotengine/godot-proposals#1085]
I don't know how simple it is to do this, but I think it makes a lot of sense why Area nodes allow you to send area_entered or body_entered signals to detect collisions, and in some cases this is the best way to resolve an action, but in other cases it is not necessary to add an Area node, which in turn must have a CollisionShape node to detect collisions, but the Raycast node is more than enough. The Raycast node has its own collision detection features, yes, perfect and much appreciated, but how many times have we missed the classic error of not detecting if the collision is different to null first? This could be solved as simply as adding these signals to the node to make it work in the same way as an Area node and I think that would be a good addition in my view.

**Comment by Xrayez** [comment]
Do you think #710 could solve this for your use case?

**Comment by xavierocampos** [comment]
> Do you think #710 could solve this for your use case?

I think that's a feature of versions in development that I haven't had the pleasure of trying out, if I'm not mistaken would it be like a CircleCast? which is not bad but does not solve this case, because what I mention is specifically a feature that could improve the RayCast nodes, not because it can not be done now with other methods, but because I think it would facilitate the use, that and the possibility of modifying its height and width in addition to the length as currently allowed in the stable versions in the case of working in 3D, as now the RayCast is very thin, although this could be overlooked of course...

**Comment by Xrayez** [comment]
> I think that's a feature of versions in development that I haven't had the pleasure of trying out

Yeah I'm just linking my own proposal and I wondered if this can relate.

> if I'm not mistaken would it be like a CircleCast?

Yeah, you could set any shape (ideally the circle shape would be instantiated by default, godotengine/godot#39479).

I think it wouldn't be trivial to allow optional width of a raycast, because internally that likely as simple as intersecting the segments geometrically (which have no notion of width math-wise).

The closest implementation of "raycast with width" in regards to #710 is setting up a `ShapeCast` with a thin `RectangleShape` instantiated.

Regarding the addition of the signal callback whenever collision occurs, I think it's more or less easy to add, needs an additional check of entering/exiting condition.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
