### ISSUE TITLE
Have class_name classes properly show in the inspector

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot-proposals#109]
**Describe the project you are working on:**
This isn't necessarily relevant to my particular project, but I'm working on a 3D FPS

**Describe how this feature / enhancement will help your project:**
It will provide a more cohesive flow in the inspector when using **class_name** and then extending from that newly created class.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
My base **Weapon** class. Take note of the exported variables.
![image](https://user-images.githubusercontent.com/16636969/65810296-c3dde300-e176-11e9-9d78-e574b79eb474.png)

Example class that extends my custom class
![image](https://user-images.githubusercontent.com/16636969/65810332-4666a280-e177-11e9-93cb-1e87602cc9ec.png)

Notice how this exported variable gets shoved in to the inspector with the class that it inherits from.

**Describe implementation detail for your proposal (in code), if possible:**
![image](https://user-images.githubusercontent.com/16636969/65810364-7e6de580-e177-11e9-8636-174fd96e0c81.png)

I propose that it should follow the built in inspector hierarchy. So, if I put my **Weapon** class on this standard KinematicBody node, above the KinematicBody node, should be the **Weapon** class. Then, when I create a new class that extends from the **Weapon** class and put it on this same node, this new class should be on top of the **Weapon** class in the inspector. This would mean that the inspector for custom classes wouldn't just read the class as "Script Variables"

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This enhancement will be used all the time as it affects a keyword for GDScript and the way the engine would handle it in the inspector

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because **class_name** and the inspector are core.

**Comment by willnationsdev** [comment]
For the community's reference, I at one point attempted an implementation of this in [this PR](https://github.com/godotengine/godot/pull/13116), but it was, at the time, closed because the design of the implementation wasn't very good. It directly changed Object in the core rather than changing the EditorInspector code like it should. The implementation could probably be greatly simplified too.

There was, at the time, no concept of script classes, so the editor simply went off the file name to decide on a name. Now, however, there is an editor-aware "name" that can be assigned to scripts. And when C# gets script class support (#22), then it will just work out-of-the-box for C# (and other languages).

Some people wanted script annotations to be a thing and for them to allow you to associate properties with a particular category or group. I still think that's a great idea, but we should do it *on top* of doing this since this makes the script system more consistent with the engine side anyway.

**Comment by willnationsdev** [comment]
Something that needs to be accounted for is what to do about properties that belong to intermediate scripts. For example:

- derived_c.gd (`class_name DerivedC`)
- derived_b.gd (unnamed) <- where do these properties go?
- derived_a.gd (`class_name DerivedA`)
- Node

**Comment by Duroxxigar** [comment]
@willnationsdev I didn't necessarily have a good idea about that one, but using the file name should work in my opinion. One of the purposes of that hierarchy is to show the inheritance tree, so, we should be consistent.

I'm not sure why you think it wouldn't indicate the order of inheritance though. I believe it would. Using your example...

- DerivedC
- derived_b.gd
- DerivedA
- Node

It will be a bit jarring to see an class on the hierarchy, but I think it is important to see the file name with the appended .gd so one could tell that it isn't a named class and should be able to tell exactly which .gd file it is. (Though, without the file type, one may still be able to tell)

**Comment by willnationsdev** [comment]
@Duroxxigar 

> I'm not sure why you think it wouldn't indicate the order of inheritance though.

I was thinking of a scenario where the script class properties displayed in their own categories and then any property that didn't directly belong to a script class would be shuffled up to the top under the "Script Variables" header.

> It will be a bit jarring to see an class on the hierarchy, but I think it is important to see the file name with the appended .gd so one could tell that it isn't a named class and should be able to tell exactly which .gd file it is.

This is what I decided to go with, after your and groud's feedback. The PR is ready to be merged I believe, barring any more recommended changes / CI issues.
