### ISSUE TITLE
Make the `or` operator between yields do something

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1092]
**Describe the project you are working on:**
Reaction game

**Describe the problem or limitation you are having in your project:**
I can't pause a function with multiple yields at the same time.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I want to pause a function in one line until signal1 or signal2 is emitted.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`yield(get_tree().create_timer(2), "timeout") or yield($Button, "pressed")` You can already write this without having an error but there's a warning: _Standalone expression (the line has no effect)._

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it's very useful.

**Comment by pycbouh** [comment]
`yield` is only useful for something extremely simplistic. You should do this race using proper signal connections and callbacks.

```gdscript
var condition_reached := false

func _my_func():
  get_tree().create_timer(2).connect("timeout", self, "_do_something")
  $Button.connect("pressed", self, "_do_something")

func _do_something():
  if condition_reached:
    return
  condition_reached  = true
  
  # Do the thing
```

**Comment by MaaaxiKing** [comment]
I'm already doing it like this but I thought it would be better with my suggestion and the first time I was thinking about how it could work was me joking "Oh maybe it works like this, haha." and then I wondered why it didn't make en error. In this regard I thought it would work because if not it would give me an error but as it turned out I was thinking wrong.

**Comment by pycbouh** [comment]
You weren't getting an error because syntactically this is still correct GDScript. You just logically add two function calls (`yield or yield`). This statement returns a boolean value, but you are not using it in any meaningful way, and thus the warning is issued to inform you about this.

Implementing your suggestion would be hard to impossible, because it would be ambiguous (meaning here not possible to parse in a predictable way). I am also not aware of any language that allows to do races between two `await`ed results like that. JavaScript, at best, provides a static interface on Promise class for this. Maybe some global helper like that can be introduced if there is any interest in it. But only after GDScript refactoring for 4.0 and assuming that new syntax.

**Comment by MaaaxiKing** [comment]
I think this would be great.

**Comment by me2beats** [comment]
I would like to have something like
```gdscript
yield((self, "a") or (self, "b"))
```
that would wait for `a` or `b`.
I know I could just use `connect()`+`emit_signal()`, but that requires more code.
Imagine that you need to do that with 5 signals, this would look messy when using `connect()`

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP), and because `yield` was removed in favor of `await` in 4.0.
