### ISSUE TITLE
Expose EditorToaster interface

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot-proposals#11051]
### Describe the project you are working on

Plugins could greatly benefit from this API to show info messages, warnings and errors as toast notifications. The API itself is already there, it just needs to be exposed to GDScript.

Example toast:
![image](https://github.com/user-attachments/assets/2d6d5a97-a7f5-4612-b72d-13fd8a50e5aa)

### Describe the problem or limitation you are having in your project

Unsable to show messages in the existing toast system.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose the API to GDScript so plugins can use it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's possible to build your own toast notification system but that results in bad user experience.

### Is there a reason why this should be core and not an add-on in the asset library?

It's already there :slight

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/77890, which made all `push_error()` and `push_warning()` uses in tool scripts create toasts. However, it seems a separate API would be preferred so that you can print errors/warnings without creating toasts. This would also let you create informational toasts which can't be created using `push_error()`/`push_warning()`.
