### ISSUE TITLE
Autocreate same instance with other name when instancing the same scene multiple times in code

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1129]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I want to instance a scene everytime something was hit and I have to write plenty lines just because it can't automatically create more than 1 instance.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Exactly like with Tabs. If you have a Tab named "Tab1" and create a new Tab named "Tab1", it will have @ in its name.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, would be many lines.
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it's core.

**Comment by pycbouh** [comment]
Packed scenes can be created in any number of instances. If a new instance has a name that would conflict with an existing node in the tree, the name would be adjusted. You probably have an issue in your code.

**Comment by MaaaxiKing** [comment]
This is my DiamondOre script:
```
extends "res://Minerals/Stone/Stone.gd"

var diamond = preload("res://Items/Diamond/Diamond.tscn").instance(PackedScene.GEN_EDIT_STATE_INSTANCE)

func _on_hit(damage):
	get_node("/root/Game").add_child(diamond)#only adds once
	diamond.position = position+Vector2(0,64)
	._on_hit(damage)
```

**Comment by pycbouh** [comment]
Yes, you explicitly create a single instance, instead of storing the `PackedScene` resource and reusing it to create instances as you need them. You need to study docs a bit more, as you seem to be missing some basic concepts of instancing scenes. You can also ask around community channels for help with your code.

Please make sure you understand the situation fully before opening a proposal. Quality proposals are detailed and thorough, and there is a reason for each section in the template. If you think that there is a problem with the engine that can be solved by a new feature, try answering each of the questions in the issue template with as much detail as possible. I believe you would see the problem in your code yourself, if you were to explain your case step by step.

**Comment by KoBeWi** [comment]
```
func _on_hit(damage):
    for i in 10:
        var diamond = preload("res://Items/Diamond/Diamond.tscn").instance()
        get_node("/root/Game").add_child()
        diamond.position = position+Vector2(0,64) 
    ._on_hit(damage)
```

**Comment by MaaaxiKing** [comment]
This would create 10 diamonds when hit once, but I want to instance one diamond everytime it is hit but I found the problem: I have to instance in the function, not before.
