### ISSUE TITLE
Add support for FLAC decoding

### ISSUE THREAD

**Issue by DJKero** [godotengine/godot-proposals#1190]
**Describe the project you are working on:**
Rhythm Game for Desktop

**Describe the problem or limitation you are having in your project:**
The game uses sound tracks to store the audio, and slices everything into keysounds (Samples that are played only when the buttons are pressed), even sounds that won't be displayed as notes (BGM Notes, which are longer), as needed when loading the song.
This is important because the content creators can produce content in a way, that they can intentionally choose to merge sounds that'll play at the same time in one track or not.
For example: Layered Synths, Background Sounds. If they're not merged, it'll be possible for anyone to create harder difficulties in the future. This is to encourage/discourage the creation of new difficulties, remixes and the ability for other people to reuse those sounds for their own creations.

Before this new format it was just a TON of small samples and a BGM file, the flexibility of this new format to organize keysounds in a longer format and the removal of the limit imposed by the nature of the previous format allows for the creators to decide if they want to work the same way as before, export the tracks as is sacrificing flexibility and storage for a faster workflow or to be smart and allow for easier creation of remixes and new content down the line.
Collections can reach hundreds of GBs, this is because of the huge amount of lossless content that is created by the communities through time.
So, with this added flexibility the amount of storage space used per song can be a lot higher than before.
Because of this I think it is really important to use FLAC instead of WAV files to optimize the storage usage from the start.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Decoding of FLAC files through the Engine would fix this issue for this and other games in the genre, allowing to optimize their storage use without the tradeoff of using lossy formats.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A function that accepts a PoolByteArray as a parameter and returns a decoded PoolByteArray or an instance of AudioStreamSample.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know, it depends on the developer, I'd use it on every project.
And yes, it could be solved with GDNative or Modules but I think there are merits to it being in core.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I honestly think this should be in core because it could benefit not only projects similar to this, but other projects with a sizable Soundtrack to optimize their storage use without sacrificing quality.
It's certainly a handy tool to add to core, and a nod to audiophiles, too.

**Comment by Calinou** [comment]
> And yes, it could be solved with GDNative or Modules but I think there are merits to it being in core.

Lossless audio doesn't seem to be widely used in games, and I doubt this will change anytime soon. Most games seem to be fine with using high-quality lossy algorithms such as Vorbis or Opus (when supported).

**Comment by DJKero** [comment]
I'd like to add this:

I'd be willing to do it myself if needed, I don't have any experience with the Engine itself or Modules but I can learn. 
My project needs it badly, since the storage will add up for sure if modders from the game my project is based of share their stuff which they don't currently do because it's bootlegging old cracked versions of it, and if creators from other communities start to create for it, too.
Granted, it took some years to get to the point, but one BMS Event which is done every year, uses around 10+ GB since 2010/11 and recent events use more than 20 GB
It's the most known Event, but there are multiple more every year, so even if the community is smaller the content will add up to the point of using FLAC doing some real work.
And keep in mind these events use the old format which forces a BGM track with a large part of the song merged together.

**Comment by DJKero** [comment]
> > And yes, it could be solved with GDNative or Modules but I think there are merits to it being in core.
> 
> Due to the storage requirements, lossless audio doesn't seem to be widely used in games. I doubt this will change anytime soon. Most games seem to be fine with using high-quality lossy algorithms such as Vorbis or [Opus (when supported)](https://github.com/godotengine/godot/issues/7496). This is especially true when you account that most games have many different sounds playing at the same time, which would make the advantages of lossless audio even less noticeable.

For this kinds of games, WAV was the only choice and support for OGG is kinda recent, since they're MUSIC games I'd like to see how the Decoding affects loading performance with HDDs if it does much at all, since I'

**Comment by Zylann** [comment]
> Due to the storage requirements, lossless audio doesn't seem to be widely used in games.

I'd like to add a point about my use case of FLAC:
While I understand that shipped games have little reason to use FLAC to play sounds, my audio workflow *while making sounds, music and games* revolves around using FLAC instead of WAV, for simple disk space reasons.
I would apreciate if Godot was able to at least import FLAC (my working format) as OGG (Godot's playback format).

**Comment by DJKero** [comment]
I honestly don't agree that its not useful for games or shipped games.
Rhythm Games and Soundtracks would benefit largely from this, those 2 are clear use cases for the feature.

**Comment by Calinou** [comment]
@Zylann This means we'd have to integrate an OGG encoder as well, which is even more work.

**Comment by DJKero** [comment]
> @Zylann This means we'd have to integrate an OGG encoder as well, which is even more work.

I'd say that the decoding of FLAC to PCM would be the solution to his workflow too.
He wants to be able to import them like me.

**Comment by Zylann** [comment]
@Calinou so we support plenty of image formats which we encode into ours, but nothing for sound? Yeah, it's work... doesn't mean it wouldnt be useful.

**Comment by DJKero** [comment]
@Zylann As stated in [here](https://github.com/godotengine/godot/issues/7496) it doesn't make sense anymore to stream the music from storage anymore so you don't need anything more than FLAC to PCM capabilities.

**Comment by Zylann** [comment]
You know that beging able to use OGG allows to make the game even lighter, right? ^^

**Comment by DJKero** [comment]
> You know that beging able to use OGG allows to make the game even lighter, right? ^^

@Zylann yeah, but you are working from FLAC, and you can convert to OGG for distribution, it just doesn't make sense to store them in FLAC if you are going to compress them in the engine.

**Comment by Zylann** [comment]
They are in FLAC originally because that's what my sound library is made of. They have to be full quality for all possible uses they can have, not just games.
But when I make a game with them, I dont necessarily want to keep that quality, due to the distribution format.

**Comment by DJKero** [comment]
@Zylann you'd need to convert them for distribution as I said before, if you don’t you aren't saving anything, just lowering RAM usage while using more Processing power to decode when needed.

**Comment by Zylann** [comment]
I guess? I dunno what problem we are talking about here. All I've been saying is for Godot to be able to import sounds when they are in FLAC, even if they get converted anyways. That's only for convenience.

**Comment by DJKero** [comment]
Yup, you don't need to encode the FLAC to OGG in engine, it achieves nothing for storage use and you lose audio quality.
For convenience you'd use FLAC and decode it to use with AudioStreamSample.
If you want to make your game use less storage for distribution you can always convert everything to OGG and replace every sound in the project then.

**Comment by DJKero** [comment]
I think FLAC playback would require more work, FLAC decoding works just fine for almost any use case and avoids decoding in real time which could introduce issues.

**Comment by Zylann** [comment]
> you don't need to encode the FLAC to OGG in engine, it achieves nothing for storage use and you lose audio quality.

Uh... yes, but I'm repeating myself here: I could want to. And I mean at *import time*, not at runtime.

> If you want to make your game use less storage for distribution you can always convert everything to OGG and replace every sound in the project then.

And doing that manually is exhausting, which is why since the start I've been proposing a way for this to be configurable in *import settings*. You can also find this in Unity (i.e you can drop an OGG, MP3, FLAC, WAV etc and the engine will play them all fine in an exported game because they get converted to the engine's internal format, based on import settings). You could even decide to have presets per platforms.
But since it's not entirely related to this proposal (which assumes everything is imported as-is) I'll just leave it there.

**Comment by DJKero** [comment]
@Zylann Oh I think I misundertood what you wanted to say, you are talking about importing FLAC and Godot storing it as OGG?

Yes that can be a separate issue that I would support too.

**Comment by DJKero** [comment]
To really clarify my use case, most of the content is loaded from a list of configurable paths, and the idea is to load the content in FLAC and decode before gameplay.
This is done the same way with WAV files.
It also would allow for a retry option with almost no loading time after the result screen.

**Comment by aaronfranke** [comment]
This would be a good candidate for a GDNative plugin. This doesn't need to be core.

**Comment by DeleteSystem32** [comment]
@DJKero Not sure if you're still interested in this/have found your own solution, but I've implemented flac import/decoding support in a [module](https://github.com/DeleteSystem32/gd-flac) a while back, and just updated it for Godot 4. If there's interest I'd be open to port it to GDNative, but I agree that it might be too niche for core.

**Comment by DJKero** [comment]
@DeleteSystem32 That's really cool! Thanks you!
For my current project I may need to learn and use modules anyways to optimize performance and audio latency eventually so a module it's fine in MY case. You should probably check the waters if there's people interested in it being a GDNative plugin.

**Comment by DeleteSystem32** [comment]
So I've just tried implementing it in GDNative, but now I'm not sure if it's even possible. The necessary methods don't seem to be exposed, which means adding new audio formats can probably only be done through modules, unless I'm missing something.

**Comment by aaronfranke** [comment]
@DeleteSystem32 Exposing more methods would be generally welcome if you'd be willing to submit a PR for it.

**Comment by benjarmstrong** [comment]
I'm working on a music/rhythm game and would like support for FLAC decoding, but I think it should be a plugin because the overwhelming majority of games use lossy compression for their audio and we probably shouldn't have fringe features like this in core. 

I might look into making this at some point, it's probably not terribly difficult to implement.

**Comment by me2beats** [comment]
The feature would be useful for making an audioplayer or audio sequencer app.
On the other hand, ogg+mp3+wav is enough for some basic needs

**Comment by me2beats** [comment]
But maybe it depends on how many lines of code could this take and could this require some additional dependencies.

**Comment by DeeJayLSP** [comment]
Considering godotengine/godot#80160 was rejected and there are custom FLAC implementations out there, I think this proposal can already be considered rejected.

**Comment by Calinou** [comment]
Closing per the above comment.

**Comment by lawnjelly** [comment]
I'm surprised no one has mentioned another option is to have the editor able to import FLAC and convert it to e.g. WAV for the final export, even if you don't want FLAC player in the non TOOLS build.

This means everyone's game projects in development can be smaller due to using lossless FLAC.

**Comment by DeeJayLSP** [comment]
> I'm surprised no one has mentioned another option is to have the editor able to import FLAC and convert it to e.g. WAV for the final export, even if you don't want FLAC player in the non TOOLS build.

I did experiment it when I was making https://github.com/godotengine/godot/pull/96545, but AIFF was my priority.

Moreover, the import code was moved entirely from `ResourceImporterWAV` into `AudioStreamWAV` to allow loading files at runtime. This means that even if you don't have the player, `dr_flac` will still be compiled in a template build. I don't think can be redone without breaking compatibility.

**Comment by DeeJayLSP** [comment]
@lawnjelly I *kinda* managed to make a working FLAC importer that's editor-only: https://github.com/DeeJayLSP/godot/tree/flac-importer

**Comment by Joy-less** [comment]
Even though this was closed, I think it would be very good for Godot to be able to import FLAC audio, whether it is converted to WAV or not. FLAC should generally be preferred over WAV, for the same reason that PNG is preferred over BMP. Bandcamp offers FLAC downloads, and there are many audios on OpenGameArt.org that offer FLAC.

> Due to the storage requirements, lossless audio doesn't seem to be widely used in games. I doubt this will change anytime soon. Most games seem to be fine with using high-quality lossy algorithms such as Vorbis or https://github.com/godotengine/godot/issues/7496. This is especially true when you account that most games have many different sounds playing at the same time, which would make the advantages of lossless audio even less noticeable.

While that's true, I disagree with this criticism, because WAV is already importable into Godot, presumably for the same reasons I gave above.

**Comment by DeeJayLSP** [comment]
@Joy-less if https://github.com/godotengine/godot/pull/96545 gets accepted, I think the chances of an eventual FLAC to AudioStreamWAV importer being accepted are considerable.

**Comment by phosxd** [comment]
Waiting for this (or for someone to make a GDExt that works for 4.6) so I don't have to bundle ffmpeg  🙏

**Comment by C-Corpze** [comment]
I would like to have runtime FLAC decoding in Godot.

Using tools like [LossyWAV](https://wiki.hydrogenaudio.org/index.php?title=LossyWAV) can greatly reduce its file size, decoding speed should be a bit faster than OGG Vorbis and it generally should have better sound quality that QOA.

Why else use LossyWAV + FLAC instead of OGG for soundtracks?
While I'm fully aware that high bitrates are virtually indistinguishable from lossless, there's one other downside to MP3 and OGG Vorbis.

Because a lot of lossy codecs work in frequency domain and use a lot of filtering, things like phase shifting and changing decibel levels can occur.

Picture you have a soundtrack that's mastered and everything, you highpassed out all the frequencies below 20 - 30hz for perfect clean and punchy bass, you carefully pushed all your peaks against the 0db limit.

Now you convert that to MP3 or Vorbis, it might still sound the same to the human ears but now all your phases are shifted, low frequency noise has been added to your sub-bass and all that carefull high-pass filtering and limiting gets undone.

In majority of games this probably won't be that big of a deal admittedly and you're likely going to have lots of sound effects playing that mix and cause phase cancellation anyways.
But I still think these are valid points to consider and having support for a relatively light-weight lossless, compressed file format is honestly amazing.

I love formats like Wavpack and FLAC along with LossyWAV because it essentially gives the benefits of lossy file size reduction while also letting you keep all the frequencies in the spectrum and preserves frequency phase and peaks a lot better.

I also think quantization noise has a more natural and less bothersome quality compared to the swirling or transient smearing that you might get from other lossy codecs.
I know QOA also does quantization compression but QOA was designed for maximum speed, it's constant bitrate and it's generally lower quality compared to Wavpack's hybrid mode or FLAC + LossyWAV.

I've tried looking for extensions that allow me to use FLAC or Wavpack in Godot.
Wavpack extensions are pretty much non-existent and FLAC often requires me to recompile the entire engine from source which seems like a very intimidating and complicated process to me and requires me to set up an entire C++ toolchain.

Imo, I think FLAC + LossyWAV is worth it, I think the flexibility of having more audio formats to choose could benefit many.
