### ISSUE TITLE
Adding Corner Radius on StyleBoxTexture and StyleBoxFlat

### ISSUE THREAD

**Issue by JUNZ1** [godotengine/godot-proposals#1214]
**Describe the project you are working on:**
Working on a Mobile Touch Based Game

**Describe the problem or limitation you are having in your project:**
StyleBoxTexture and StyleBoxFlat classes should have corner radius property

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It will give stronger feature to the developers who uses them in their game for native drawing, For the moment these objects corners are 90 degrees and not changable

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just adding these properties like added in StyleBoxFlat

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As far as i know no.. You can not draw these elements natively with some rounded corners

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe most of the developers want to use native godot classes when they need maximum control in the game..

**Comment by Calinou** [comment]
StyleBoxFlat already has a corner radius property since Godot 3.0.

StyleBoxTexture could technically have one (as a mask), but I don't think it makes sense. With StyleBoxTexture, you typically use corners that are baked into the texture to improve performance and have greater creative freedom.

Also, keep in mind rounded corners will cause Godot to use a polygon drawing path instead of a rect draw ing path, which is [much slower](https://github.com/godotengine/godot/issues/19943).

**Comment by JUNZ1** [comment]
Thank you for return, then i think its much better to make it during asset creation, instead of using godot..
