### ISSUE TITLE
Add a custom sorting method to ItemList

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot-proposals#1290]
**Describe the project you are working on:** A Selection Menu for RTS Game's Unit Selection

**Describe the problem or limitation you are having in your project:** Currently I'm using an ItemList to manage the listing of units, I desire to have my saved list of units in sync with the ItemList. The only way I can guarantee this is either by manually moving, removing, and adding items to the ItemList or by clearing and setting it all at once, I've resorted to clearing and setting everything. This does not sit well with me.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** If I had a capability to sort the items in the list in a manner I can define, I wouldn't run the risk of possible bugs introduced by manually managing the list, and I wouldn't need to start the list from zero every time something is added or removed.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** I wonder if perhaps Array's sort_custom capability could be implemented for ItemList as well, it already supports sorting by the default comparer, but I don't know the complexity of getting it to use other comparers.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Not exactly, but its not hard to workaround, but I think this case I am forced to write inefficiently. While its not a large priority in any respect, I do think its better to give the capability to the developer on controling how the ItemList looks after its been created. (without resorting to manipulating the individual items bit by bit)

**Is there a reason why this should be core and not an add-on in the asset library?:** I'd either have to rewrite the ItemList object to achieve this, or manually handle the list with a separate function, there is currently no manner to get ItemList to sort in any way other then based on the text itself.

**Comment by Zylann** [comment]
So far I then considered `ItemList` as litterally a view, with no special features beyond displaying a list of items. I had to integrate custom-sorted item lists (same with `Tree`!) in several projects I worked on. It wasn't actually difficult, all I did was to put the items in an array, use `sort_custom`, clear the list and re-insert the items from the array, pretty straightforward. 
It became a bit more complicated when I wanted to preserve previously selected items, though not that much.

A similar case I encountered often was to *also* filter the list. Which again, I did in a similar way: clearing the list, and inserting items from an array by testing them against the filter predicate.
In both cases, I ended up with a view-model design: my ItemList is just a view, my model is an array or some other collection data structure which contains the true data from the game. So I doubt you'd have to rewrite the entire `ItemList` to get what you need, but for sure you need to design your code around it so that it works with those extra behaviours.

Adding custom sorting to `ItemList` could be done in several ways. You described adding `sort_custom` like `Array`, so basically users would have to provide a `funcref` with 2 parameters, which returns `true` if `a < b` or `false` if `a < b`. Such a solution is the simplest like the existing `sort_items_by_text`, and stateless, i.e it won't remember to sort again if you insert more items, unless you call the function a second time. If it's what you need, it sounds pretty simple to add.

However there is something to solve: from the point of view of `ItemList`, the comparator can only either use the item's text, its index, or its metadata (because again, ItemList is a GUI view, it only knows what it needs to know to display stuff). I'm not sure what would be the actual arguments of the comparator because of this. It can't be the text because it doesn't allow to access metadata. It can't be the metadata because it's optional. And it can't be the index because it will change as we sort the list... so the comparator would have to receive both text and metadata:
```gdscript
item_list.sort_custom(funcref(self, "compare"))

func compare(item1_name: String, item1_metadata, item2_name: String, item2_metadata) -> int:
    ...
```
Alternatively, two functions can be provided, `sort_custom_by_text` and `sort_custom_by_metadata`, which would sort based on either text or metadata.

**Comment by akien-mga** [comment]
Closing as https://github.com/godotengine/godot/pull/63349 was rejected due to lack of demand from the community in this proposal.
