### ISSUE TITLE
Add "universal" anti-aliasing in 2D (MSAA and/or SSAA)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1297]
Old Issue: https://github.com/godotengine/godot/issues/12840 \
See above issue for previous discussion

**Describe the project you are working on:**
Any project

**Describe the problem or limitation you are having in your project:**
In some instances aliasing is very clear to see. It would be optimal to make AntiAliasing work in 2D.

For example, background stars in a space game that are the size of only a few pixels.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
AntiAliasing settings should work in both 2D and 3D. (Even if eventually we add FXAA, SSAA, etc.)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Ideally, this would work with the already existing `rendering/quality/filters/msaa` project setting.
![image](https://user-images.githubusercontent.com/14253836/89138171-4d311500-d500-11ea-8ce1-a25aa20e8537.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This setting will be used often, but it also cannot be worked around easily.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a core renderer problem so unlikely to be solved in an add-on.

**Comment by Zylann** [comment]
You mention stars in a background, however it's important to know what rendering technique you refer to. I'm not sure if MSAA works with pixels of textures, only polygon edges (quads that make up sprites, lines etc), doesn't it?
Although it's true that if that feature works in 3D there is no reason to not have it in 2D.

**Comment by Calinou** [comment]
> 'm not sure if MSAA works with pixels of textures, only polygon edges (quads that make up sprites, lines etc), doesn't it?

At the end of the day, individual rects are considered polygons, but a single texture with stars inside will be a single polygon.

**Comment by fire** [comment]
I discussed some approaches for implementing here. https://github.com/godotengine/godot/pull/40866

**Comment by nathanfranke** [comment]
Eventually it will be nice to support SSAA which would fix the texture issue. But for now we should set the precedent of anti aliasing settings to be both 2D and 3D

**Comment by Calinou** [comment]
@nathanfranke SSAA is already supported. See the [3D viewport scaling demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling) (which can also apply to 2D the same way).

**Comment by kCenk** [comment]
> @nathanfranke SSAA is already supported. See the [3D viewport scaling demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling) (which can also apply to 2D the same way).
> 
> Keep in mind it has a significant performance cost though, making it less than ideal for 2D rendering. There are usually better ways to solve aliasing compared to a brute-force approach (except for offline rendering where quality is your primary goal).

I couldn't figure out a way to use this on a 2D project, the image outputted was only 1/2 my resolution.

**Comment by nathanfranke** [comment]
@kCenk I got it to work. Did you enable filtering in Viewport texture -> resource?

**Comment by kCenk** [comment]
TextureRect Flags? I did set it to 4, texture_rect.texture.flags = 4

**Comment by golddotasksquestions** [comment]
Rotated Sprites and TextureRects will always have staircase edges, regardless of any project or import settings: 
![rotated_sprite](https://user-images.githubusercontent.com/47016402/90766377-b334df00-e2eb-11ea-9cd1-7ac9bcf32319.png)

This is especially problematic for cardgames. Exampe: 
https://www.reddit.com/r/godot/comments/id17lf/how_do_i_smoothen_these_edges/

Only workaround I found was to use Polygon2D, enable the "antialiased" property and assign it the texture.

**Comment by Calinou** [comment]
@golddotasksquestions There are two other ways to solve it:

- Use a supersampled viewport with Filter enabled. That is, use a TextureRect to display a filtered ViewportTexture whose resolution is greater than the window size. See [3D Viewport Scaling demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling) for an example of this (it applies to 2D as well). This is slow, but it works for literally anything that will be rendered.
- Add a transparent 1-pixel border on each side of the sprites and make sure filtering is enabled. This has no noticeable performance cost and still provides good smoothing.

**Comment by nathanfranke** [comment]
For rotated sprites, there should definitely be a MSAA option for 2D (Or just making the current option work for 2D).

As for anti-aliasing within textures of sprites, this can only be solved with SSAA ([MSAA doesn't help with textures anyways](https://en.wikipedia.org/wiki/Multisample_anti-aliasing#Aliasing)). I propose an option next to MSAA for SSAA. I think this is a bit nicer than the viewport workaround.

**Comment by endlesstravel** [comment]
I have a very simple way to achieve this anti-aliased line:
One line (```this``` is a CanvasItem(Node2D) ) for C# version,  just copy Smooity.cs to your project
(here https://gist.github.com/endlesstravel/ae1b2adba9bebd872329d6118c0d87b2)
then :
```C#
// in overrid _Draw() , don't forget call Update() in _Process()
Smooity.DrawLine(this, new Vector2[] { Vector2.Zero, GetLocalMousePosition() }, Colors.White, 0.5f);
```
![image](https://user-images.githubusercontent.com/10757838/91781091-097b1980-ec2c-11ea-8862-a79ddb1ea296.png)
just checkout here: 
![2020年8月16日-10点29分-2](https://user-images.githubusercontent.com/10757838/91781267-77bfdc00-ec2c-11ea-9afd-12308909bbfe.gif)

-------
Is the problem over here? Unfortunately not：
🤕 
------------
I have already implemented it, but I did not send it out because of the following points:
1. Performance issues: 
I tried to optimize performance with `Mesh` and `DrawPolygon batch` instead of calling a single DrawPolygon every time, but I failed: 
* for dynamic build mesh each time, I encountered an unknown issue, Godot will draw the last line many times.
* for `DrawPolygon ` at one time for mutiply line, it just can't handle closed poly, if it draw a circle , it will show error but draw noting.
2. Because of bugs, there are also problems with the processing of discounted edges.
-----
Sincerely hope that bug(s) did not ruin godot 😢

**Comment by nathanfranke** [comment]
@endlesstravel `Control.draw_line` already has `antialiased`

**Comment by Calinou** [comment]
In `master`, [antialiasing is restored for line drawing using triangle strips](https://github.com/godotengine/godot/pull/43828) but 2D MSAA still needs to be implemented.

**Comment by hazarek** [comment]
No way to draw a 1px pixel perfect antialiased line in godot similar to HTML5 canvas. All workarounds are bold blurry lines.

**Comment by Calinou** [comment]
@hazarek Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by hazarek** [comment]
> @hazarek Please don't bump issues without contributing significant new information. Use the 👍 reaction button on the first post instead.

OK. Keep censoring me and stalling everyone with workarounds.

**Comment by nathanfranke** [comment]
@hazarek The vast majority of contributors to this project are doing so out of their own spare time for free. It is impossible to fix every issue in a small amount of time. The only way to speed up this issue is either solving it yourself, hiring someone who can, or donating to the project so the maintainers can hire someone themselves.

**Comment by hazarek** [comment]
> It is impossible to fix every issue in a small amount of time.

This problem has existed for at least 6-7 years as far as I know. It's really pathetic to blame the community instead of apologizing to users.

**Comment by Calinou** [comment]
I released an [add-on for better 2D line antialiasing](https://github.com/godot-extended-libraries/godot-antialiased-line2d) in Godot 3.x. Check it out :slightly_smiling_face:

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/63003.

**Comment by Giwayume** [comment]
Can we get this backported to 3.x, should I open a different proposal for that?

**Comment by Calinou** [comment]
> Can we get this backported to 3.x, should I open a different proposal for that?

https://github.com/godotengine/godot/pull/63003 doesn't include the GLES3 part anymore (as per https://github.com/godotengine/godot/pull/63003#issuecomment-1201594946), so @Geometror would have to make it available again somehow so this can be backported for `3.x`.

I don't think you need to open a separate proposal – backports of fully backwards-compatible functionality are something anyone can work on.

**Comment by jordanlis** [comment]
Hi, sorry to comment again this closed issue, but I have two things to say : 
- If if could be backported to 3.x, it could be great yeah !
- Does this apply to canvasLayer ? Because I think 2D graphics on viewports are smoother (not sure why), but on canvaslayer there are no options to improve 2D graphics. 

I made an HD layer with a canvaslayer for my game, but the graphics are not so great because of this issue with MSAA

Not sure this is the good place to ask, but if anyone can tell me it could be great.

**Comment by Calinou** [comment]
> Because I think 2D graphics on viewports are smoother (not sure why)

If graphics appear smoother on a viewport, it's because you're downsampling it somehow (e.g. because you're using the `2d` stretch mode and reduced the window size below the default). This has a significant performance cost.

**Comment by jordanlis** [comment]
> It's technically possible to reimplement this in 3.x, but it's a lot of work – you can't just copy-paste code and expect it to work, even for GLES3. Also, nobody among the core contributors is available to do this work.

Understood. Well nevermind, I must be one of the only that wanted to stay on godot 3. I'm trying to port my game to godot 4.0 and I saw from the poll results that a vast majority of people are using version 4. 

> If graphics appear smoother on a viewport, it's because you're downsampling it somehow (e.g. because you're using the `2d` stretch mode and reduced the window size below the default). This has a significant performance cost.
> Are you sure the visual issue is because you don't have access to MSAA in 2D? Can you post a screenshot here? What's your project's base window size, and which stretch mode are you using?

Well, first of all I'm not sure no, but how can I ? I just realized since I started this HD layer for my menu / inventory that HD graphics are downsampled whereas they are on an HD canvas. 

Here's a screenshot of my game menu 
![image](https://github.com/godotengine/godot-proposals/assets/68544949/c0c8602c-cda8-4506-9833-5adca15f1921)

This is acceptable, but not perfect. If you zoom, you see that this is different than in figma for example, and this is only because I'm using a huge size. I noticed that when using big texture images, it decreases the aliasing effect. 
For example, the gunshot icon is 1200 x 600, so I had to apply a reducing factor to all of my icons (not a problem, but anyway I did what I could). 

My base resolution is 1920 x 1080
Here's my window configuration
![image](https://github.com/godotengine/godot-proposals/assets/68544949/fa1f634d-4ccc-4130-a87d-ab2be43b1f1f)

Here's the arborescence
![image](https://github.com/godotengine/godot-proposals/assets/68544949/04a9df54-2e04-44c2-92bc-e1e54545d2b9)

Viewport node size
![image](https://github.com/godotengine/godot-proposals/assets/68544949/f52fb834-f093-4ad1-901c-8ab9906bcc9f)

I should have given you a screenshot with the base size of my icons, I mean the real size before I use them with the big size. You can see better the issue.
