### ISSUE TITLE
Add a way to get the editor's Camera2D/Camera3D nodes

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot-proposals#1302]
**Describe the project you are working on:**

I write a tool where I need to use the use the camera method: `unproject_position` in a 2D node, in the process method.

**Describe the problem or limitation you are having in your project:**

I don't find a way to get the editor's camera, so I can't add extra info in my tool. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's a core feature.

**Comment by aaronfranke** [comment]
Here is some work-around code (designed for Godot 3.2, [original](https://godotengine.org/qa/1028/how-can-locate-the-viewport-node-of-the-2d-editor-on-the-engine) by @neikeq).

```gdscript
func _ready():
	var editor_viewport_2d = find_viewport_2d(get_node("/root/EditorNode"), 0)
	var editor_viewport_3d = find_viewport_3d(get_node("/root/EditorNode"), 0)
	var editor_camera_3d = editor_viewport_3d.get_child(0)


func find_viewport_2d(node: Node, recursive_level):
	if node.get_class() == "CanvasItemEditor":
		return node.get_child(1).get_child(0).get_child(0).get_child(0).get_child(0)
	else:
		recursive_level += 1
		if recursive_level > 15:
			return null
		for child in node.get_children():
			var result = find_viewport_2d(child, recursive_level)
			if result != null:
				return result


func find_viewport_3d(node: Node, recursive_level):
	if node.get_class() == "SpatialEditor":
		return node.get_child(1).get_child(0).get_child(0).get_child(0).get_child(0).get_child(0)
	else:
		recursive_level += 1
		if recursive_level > 15:
			return null
		for child in node.get_children():
			var result = find_viewport_3d(child, recursive_level)
			if result != null:
				return result
```

**Comment by Zylann** [comment]
Note: the 3D editor has more than one camera. This is because there are split view modes with 2, 3 or 4 viewports at once. Hence why the camera is provided in input callbacks since it is paired with interactions done in that viewport.

**Comment by QbieShay** [comment]
Just stumbled on this, perhaps cameras could be exposed with a `get_spatial_cameras(index)` ?

**Comment by fbcosentino** [comment]
Expanded the one posted by @aaronfranke to include all viewports (if the user is splitting viewports). All 4 viewports are always there, just optionally hidden

The code gives you `ViewportContainer`, `Viewport` and `Camera`, for maximum convenience

```gdscript

func _ready():
	var editor_viewport_container_2d = find_viewport_2d(get_node("/root/EditorNode"), 0)
	
	var spatialeditor_viewport_container = find_SpatialEditorViewportContainer(get_node("/root/EditorNode"), 0)
	var viewports_3d = find_viewports_3d(spatialeditor_viewport_container)
	
	# viewports_3d[ <viewport index 0-3> ] = {
	#     "viewport_container": ViewportContainer,
	#     "viewport": Viewport,
	#     "camera": Camera
	# }
	#      Indices:
	# 1 viewport: index 0
	# 2 viewports (both ways): indices 0 and 2
	# 3 viewports: indices 0, 2 and 3
	# 4 viewports: indices 0, 1, 2, 3
	
	print( viewports_3d[0]["camera"].fov ) # Prints 70 (if you haven't changed)




func find_viewport_2d(node: Node, recursive_level):
	if node.get_class() == "CanvasItemEditor":
		return node.get_child(1).get_child(0).get_child(0).get_child(0).get_child(0)
	else:
		recursive_level += 1
		if recursive_level > 15:
			return null
		for child in node.get_children():
			var result = find_viewport_2d(child, recursive_level)
			if result != null:
				return result

func find_viewports_3d(spatial_editor_viewport_container) -> Array:
	var result = []
	for spatial_editor_viewport in spatial_editor_viewport_container.get_children():
		var viewport_container = spatial_editor_viewport.get_child(0)
		var viewport = viewport_container.get_child(0)
		var camera = viewport.get_child(0)
		result.append( {
			"viewport_container": viewport_container,
			"viewport": viewport,
			"camera": camera
		} )
	return result

func find_SpatialEditorViewportContainer(node: Node, recursive_level):
	if node.get_class() == "SpatialEditor":
		return node.get_child(1).get_child(0).get_child(0).get_child(0)
	else:
		recursive_level += 1
		if recursive_level > 15:
			return null
		for child in node.get_children():
			var result = find_SpatialEditorViewportContainer(child, recursive_level)
			if result != null:
				return result
```

**Comment by snektailmeat** [comment]
> Note that the 3D editor keeps track of the camera transform on its own. This means that if you set the rotation manually, it will be overridden as soon as you pan the camera or use freelook again.
> 
> We should add a proper interface for setting the editor Camera3D transform as well.

so whats the status on this or the whole not being able to get the editors camera ?

**Comment by Calinou** [comment]
> so whats the status on this or the whole not being able to get the editors camera ?

This isn't implemented yet. Pull requests are welcome :slightly_smiling_face:

**Comment by petterthowsen** [comment]
Anyone know any hack for this for godot 4? In my case I need the 2D editor camera.

**Comment by QbieShay** [comment]
After looking into the camera code, i firmly believe that instead of making the camera available, we should instead offer functionalities on the relevant editor class to control the camera. 
The editor camera is actually way more complex than it looks like and handing the control over to the plugin maker breaks a lot of things. Simply exposing the camera node doesn't work.

**Comment by snektailmeat** [comment]
i dont know how it works in 2d but the information checkbox already displays, it exposing that in gd script shouldn't be that hard,  shaders also have acces to it so i really dont know why this hasnt been implemented yet while the request go way back to 2016...

**Comment by parubini** [comment]
I too would like the option to access and set the editor camera transform.origin. I am building a 360VR tour editor/player as a plugin and would like to be able to set the editor camera transform. origin to be (0.0,0.0,0.0).

In 3.5 I managed to work around by finding the editor camera, and then in my EditorPlugin, reset the origin inside _process

```
tool
extends EditorPlugin

func _ready():	
	var viewport = editor_interface.get_editor_viewport()
	var cameras = find_camera(viewport, [])
	if cameras.size() > 0:
		editor_camera = cameras[0]

# From https://github.com/cybereality/godot-space-mouse
func find_camera(node, list) :
	if node is Viewport:
		var camera = node.get_camera()
		if is_instance_valid(camera) and camera is Camera and "@" in camera.name:
			list.append(camera)
			return list
	for child in node.get_children():
		find_camera(child, list)
	return list

func _process(delta):
	if is_instance_valid(editor_camera):
		editor_camera.transform.origin = Vector3.ZERO
```

The above works, but is clearly a hack, continuously overriding the editor origin

**Comment by QbieShay** [comment]
> i dont know how it works in 2d but the information checkbox already displays, it exposing that in gd script shouldn't be that hard, shaders also have acces to it so i really dont know why this hasnt been implemented yet while the request go way back to 2016...

@snektailmeat that's just how open source is, people donate time so they implement what they feel like implementing. Plus there's been attempts, but the camera code is more complex than it looks like.

I think we should talk about how/which parts of the camera API to expose, but in the end someone has to pick up the work.

**Comment by snektailmeat** [comment]
@QbieShay i get that this is all free time based but im basically stuck with my game because of it 🙂 and all the older hack workarounds dont work in 4.0 🙂 and getting passivaggressively told by @Calinou (who is afaik paid to work on gd) to basically write my own proposal feels really insulting🙂 because if i could write one i already would have done so 🙂

so hers my proposal; jsut expose the Information box in code :🙂
![smilley](https://user-images.githubusercontent.com/112773729/200178246-256e9c0f-87a0-4ed4-bcdf-859b3b95a386.PNG)
something like get_viewport().get_information().get_position()

**Comment by YuriSizov** [comment]
@snektailmeat I think you took it the wrong way, but the comment left by Calinou in September is a typical way we encourage people to participate if they feel strongly about a feature. This is an open-source project after all. It lives with the contributions made by our community members, and the vast majority of contributors is not sponsored by anyone. Note that the process of contributing is democratic and nobody is forced to work on anything specific. Paid contributors are also extremely busy as is, so we can't cover all the requests, unfortunately.

Now, regarding the workarounds mentioned in this thread, they should still work more or less. Do note that `SpatialEditor` is now called `Node3DEditor`, so the checks in the provided code should be adjusted. Similar other changes may be required as well, but the overall principle should remain the same.

**Comment by snektailmeat** [comment]
@YuriSizov still cant get it to work maybe you got some better luck ? got any example code working 4.0, i also couldnt get the workarounds form the other threads to work

**Comment by tinmanjuggernaut** [comment]
`EditorInterface` should be able to return an array with all viewports, and viewports should be able to return the active camera. Seems like basic functionality to me. The editor should only update the camera position on input, which means a plugin could potentially override it when not updating.

This code works fine to get all 4 editor Camera3Ds in Godot 4 in the meantime, and could be modified for 2D cameras. The four cameras track the 4 viewports, in order. Note the instancing of EditorPlugin. See https://github.com/godotengine/godot/issues/68685. If written inside an EditorPlugin derived class, you can call `get_editor_interface()` directly.

```

func _ready():
	if Engine.is_editor_hint():
		var editor_cameras: Array[Camera3D]
		editor_cameras = get_editor_cameras()

func get_editor_cameras() -> Array[Camera3D]:
	var ei: EditorInterface = EditorPlugin.new().get_editor_interface()
	var cameras: Array[Camera3D]
	find_editor_cameras(ei.get_editor_main_screen().get_children(), cameras)
	return cameras
	
func find_editor_cameras(nodes: Array, cameras: Array) -> void:	
	for child in nodes:
		find_editor_cameras(child.get_children(), cameras)
		if child is Camera3D:
			cameras.push_back(child)
```


@snektailmeat Not cool. He wasn't passive aggressive. Even if they are paid, which most aren't, are you paying them so you can direct their efforts? You'll get a lot more help in proportion to the amount of effort you put in through troubleshooting, looking through code, and experimenting. Zero effort, mischaracterization of other's words, and an entitled attitude will turn off anyone from helping you.

**Comment by tinmanjuggernaut** [comment]
I've created a draft PR that provides access to the (4) 3D editor viewports, which give access to the (4) 3D editor cameras. It works perfectly.

However, I can't find the 2D camera. Does the editor use a 2D camera? I can get the 2D viewport, but it has a null camera. Please review it here and help me find the camera.
https://github.com/godotengine/godot/pull/68696

**Comment by tinmanjuggernaut** [comment]
The PR is ready for review. The 2D editor does not have a camera. View transforms are applied directly. The PR exposes the 2D and 3D viewports, and shows how to access the 2D canvas transform and 3D cameras as the 2D and 3D viewports are moved around.

https://github.com/godotengine/godot/pull/68696

**Comment by xiongyaohua** [comment]
Hi I just stumble this problem recently, in the process of writing of 2D plugin. I am not familiar with 3D part, but for 2D plugin writer I think it is not enough to only expose the viewport, there are other functionality from the `CanvasItemEditor` are needed. Maybe it is better to just expose the whole `CanvasItemEditor` to script plugin writer?

I am not sure this is the best way, but made an PR anyway. Hope developers who are more familiar with the architecture could shed some light.
https://github.com/godotengine/godot/pull/68706

**Comment by YuriSizov** [comment]
@xiongyaohua We prefer not to expose parts of the editor absent-mindedly. If something like this needs to be exposed, its API needs to be cleaned up and discussed. Opening parts of the editor, or any presently internal API really, to the end user means the exposed contract has to be maintained and any changes to it need to be considered in terms of breaking compatibility. At this time we don't have a plan to expose the canvas item editor control.

**Comment by QbieShay** [comment]
I think it would be useful if the people that encountered this issue could detail what they were trying to do and what they'd need the camera for.
If it's things like unproject position, for example, we don't need to expose viewports and camera, we can expose a function that returns the position instead.
Exposing the camera opens the door for people to try and do stuff that, for how the editor camera works, **will not work**. The editor camera **cannot** be controlled by just grabbing the node, it breaks a lot of different things.

**Comment by snektailmeat** [comment]
@QbieShay in my case i would like to have my terrain function in the editor, since clipmap terrrain needs to follow the camera, right now im using a dummy node that i need to constantly move across my world, i also have a realtime reflection probe at my camera that i would like to also work in the editor, you know for art direction and stuff.
like i mentioned before i would be happy with the stuff the information box already displays.
but since this issue goes back to 2016 and all the prs have been shutdown, i guess ill have to stick to my dummy node system :)

**Comment by QbieShay** [comment]
@snektailmeat what I'm reading here in your usecase, correct me if I'm wrong, it's two things:
1. reading data from the camera
2. in editor reflection probe that follows the camera

I think those are two separate features and should be discussed as such ^^

**Comment by tinmanjuggernaut** [comment]
For me it's the camera transform. However I could see a plugin polling all sorts of information from the viewports or camera including the viewport size, debug draw mode, anti aliasing, mouse position, render info, screen transform, viewport texture, RID, signals, all of the camera properties, and more. I see no good reason to limit access to the viewports or camera. We can find it in the tree anyway as previously shown. If they can't change the editor camera transform, they'll find out. Warnings in help are sufficient. 

e.g. EditorInterface
`Warning: Removing and freeing this node will render the editor useless and may cause a crash.`

**Comment by tinmanjuggernaut** [comment]
I think the most common use case is reading information from the editor viewport/camera, rather than changing it. eg. Where the camera is and what it's looking at. https://github.com/Schroedi/EditorFlyCam for instance is essential for making cutscenes. Shaders can already grab and respond to the camera, but tool scripts cannot without the hacks above. We had a level design problem on our custom terrain because looking at locations far from the origin showed us blocky, low levels of detail. Objects could not be placed accurately. Terrain editors need to update based on camera position. Everything I listed previously could be useful to read off of. No one is going to change the RID, the viewport texture is only useful as read, etc.

**Comment by QbieShay** [comment]
I was mostly talking about changing the transform of the camera. The problem with exposing the node is that it's an invitation to modify it: we will get a lot of people reporting bugs about not being able to change the camera. I think for now the best way would be to expose the data one by one, where camera transform is by far the most common, i think.

> We can find it in the tree anyway as previously shown.

The hacks required makes it very clear that it's a workaround on something that is not supposed to work, which makes a big difference in terms of maintaining it

Either way, I'm not against exposing information, and I think already a super safe PR would be to get camera data instead of camera node, same for the viewport

**Comment by xiongyaohua** [comment]
> I think it would be useful if the people that encountered this issue could detail what they were trying to do and what they'd need the camera for.

In my case I am writing a customize 2D object editing plugin, quite similar with `Path2DEditorPlugin`. I find there are several things that are straitforward in C++, but not so in GDScript:
1. Get the the transform of the 2D editor viewport, for projecting mouse events. (`CanvasItemEditor::get_canvas_transform()`)
2. Update **both** the 2D editor viewport and the sliders after change underlying 2D object (`CanvasItemEditor::update_viewport()`)
3. Reusing the snapping behavior of `CanvasItemEditor` (`CanvasItemEditor::snap_point(Point2 p_target,`)

There are two things stand out:
1. Expose viewport along is not enough. For example beside the viewport, sliders around it also need to be updated.
2. Mostly we need only query the state, not change the state of the editor. 


> We prefer not to expose parts of the editor absent-mindedly. If something like this needs to be exposed, its API needs to be cleaned up and discussed. Opening parts of the editor, or any presently internal API really, to the end user means the exposed contract has to be maintained and any changes to it need to be considered in terms of breaking compatibility.

@YuriSizov I spent more time going through the code, and I think you are right. From the code, it seems the current convention is to expose all editor related things through `EditorInterface`. I saw some functionalities of the `CanvasItemEditor` are already exposed on `EditorInterface`, for example

https://github.com/godotengine/godot/blob/cca9f780252f48beb9a7a39826b40bcb3a4ade54/editor/editor_plugin.cpp#L464-L475

> Either way, I'm not against exposing information, and I think already a safe PR would be to get camera data instead of camera node, same for the viewport

I also agree with the general idea of expose data instead of node. 

Combining these two, I am going to update [this PR ](https://github.com/godotengine/godot/pull/68706), exposing the functionalities of `CanvasItemEditor` through `CanvasInterface`, instead of exposing `CanvasItemEditor` directly.

**Comment by snektailmeat** [comment]
@QbieShay lick the other already mentioned i would like to get the Position of the main editor camera for a tool srcipt. wich https://github.com/godotengine/godot/pull/68696 seems to do perfectly. while i would not need it i, can see setting for example the postion of the editor camera also useful, for quick traversal in a big world.
i wouldn't worry about unintended behavior since you can have enough of that with toolscripts already, maybe just add a red warning box in the docs if it gets added

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/68696.
