### ISSUE TITLE
R Lang

### ISSUE THREAD

**Issue by ranalytica** [godotengine/godot-proposals#1304]
**Describe the project you are working on:**
I would like to be able to use R language for analytics. Is it possible?
**Describe the problem or limitation you are having in your project:**

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by clayjohn** [comment]
This is a repository for Godot users to propose and discuss improvements to the Godot engine. If you would like to make a proposal, you need to properly fill out the template so that others can discuss the proposal with you. 

If you just want to ask a question please consider asking it on one of the [community channels](https://docs.godotengine.org/en/stable/community/channels.html) instead.

**Comment by Calinou** [comment]
Also, please note there are currently no plans to support more programming languages in Godot. That said, it's likely possible for a third party to create a GDNative binding that would let you use R with Godot.
