### ISSUE TITLE
Switch from current debugger protocol to DAP

### ISSUE THREAD

**Issue by ofrank123** [godotengine/godot-proposals#1308]
**Describe the project you are working on:**
Getting a debugger for Godot working in Emacs.

**Describe the problem or limitation you are having in your project:**
Godot does not currently follow the [DAP](https://microsoft.github.io/debug-adapter-protocol/) protocol, and as such for each text editor a standalone client must be written, instead of the existing DAP client that almost all modern text editors have available.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would like to switch the debugger to the follow the DAP protocol.  In addition I can try to switch the current VSCode debugger to DAP.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It will work very similarly to the current debugger, it will just be standarized.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is changing core godot functionality, not an add on.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-vscode-plugin/issues/72.

**Comment by neikeq** [comment]
What's done for most languages is to just write an app that acts as a middleman between both protocols. This is what the GDScript plugin for VSCode does (see Calinou's link).

**Comment by ofrank123** [comment]
Does this not defeat the whole purpose of the DAP, as you lose the whole "universal protocol" deal if you're writing a new middleman for each language.  I could totally be missing something, and if what you're saying is that a DAP server for GDScript already exists, then great, but the VSCode plugin doesn't look like that.  It seems like the best solution is to just rewrite the debugger server going forward so that it conforms to the DAP.

**Comment by neikeq** [comment]
Not necessarily. AFAIK much as the LSP the DAP is intended for writing an extension once and re-using it in multiple editors, for example:

>Godot does not currently follow the DAP protocol, and as such for each text editor a standalone client must be written

You wouldn't need to write a standalone client for each editor. You would need to write it once and then you can use it for all of them.

Of course if the language VM itself used the DAP protocol as you suggest, you wouldn't need to even write a standalone client yourself.

**Comment by NathanLovato** [comment]
> Of course if the language VM itself used the DAP protocol as you suggest, you wouldn't need to even write a standalone client yourself.

That would be the idea.

It's my teammate @Razoric480 who wrote the debugger support for VSCode, and it's custom code for VSCode only.

Having the debugger and language server follow the DAP and LSP specs in Godot would be great, this gives you almost full language support in any editor. The LSP already gave us gdscript autocompletion support in Emacs, Vim, and many others, although there are some issues left in the GDScript language server (notifications that don't follow the spec).

If it's possible, I'd second following DAP too.

**Comment by Faless** [comment]
I had a look at the DAP protocol, I really like the idea of supporting it.

But we don't want to "switch" the debugger protocol to DAP, because as far as I understand it, that's not what it's for.

**The editor will be the `debug adapter`**, a `DAPServer` class, optionally enabled like the LSPServer.

![with-DAP](https://user-images.githubusercontent.com/1687918/112020893-0a748980-8b31-11eb-91e6-e239b6032ca8.png)

(image from [here](https://microsoft.github.io/debug-adapter-protocol/overview))

The `debug adapter` will implement at least:
- Initialize
- Breakpoints initialization (hooking up `EditorDebuggerNode`/`ScriptEditorDebugger` `set_breakpoints`)
- Breakpoints break (hooking up `EditorDebuggerNode`/`ScriptEditorDebugger` `breaked` signal)
- Usual start/pause/continue/stop.

From there, we can iterate and add more domain-specific capabilities if we want (live-view, inspector, etc), some of them have probably standardized equivalents (surely for stack traces / inspecting), some of them will probably have to be extensions.

Most of this can already be done as a GDScript plugin via the new [`EditorDebuggerPlugin`](https://github.com/godotengine/godot/pull/39440). But I'm all in favour of having it as a `module` like the LSP server.

**Comment by Faless** [comment]
Closing as superseded by #2494
