### ISSUE TITLE
Add an `import` keyword

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot-proposals#1332]
**Describe the project you are working on:**
A program to do 3D design

**Describe the problem or limitation you are having in your project:**
I have some classes, I would like to cut and paste a class into an external .gd file and include it.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

![image](https://user-images.githubusercontent.com/17924807/89691745-a08cd400-d901-11ea-82c8-bbd9854291f4.png)

I decide to refactor my code and move the classes into external .gd files:

![image](https://user-images.githubusercontent.com/17924807/89691813-d2059f80-d901-11ea-9e51-44fa58c3da63.png)

Test2.gd:
![image](https://user-images.githubusercontent.com/17924807/89691825-d9c54400-d901-11ea-95d9-c7eb304eeaa5.png)

This does not work. The code now fails silently.

Changing Test2.gd to this:

![image](https://user-images.githubusercontent.com/17924807/89691859-f82b3f80-d901-11ea-9605-3ba2c638b971.png)

1. Remove the class name
2. Re-indent my code

Fixes the issue.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Create an 'import' keyword that would mimic the Python include keyword. It just pulls the file in.

[edit] I forgot the Python keyword is "import", I mistakenly remembered it as "include"

**Comment by monk-e-boy** [comment]
Oh poop. I forgot to mention that **preload** causes more errors in other code - namespace issues? Not sure, it's hard to tell:

![image](https://user-images.githubusercontent.com/17924807/89692833-a9cb7000-d904-11ea-9cfa-b0c1b93b4765.png)

ERROR: Test2 is not a valid type

Not sure how to fix this issue. I don't think it should be an issue and that using an '**import**' keyword to import my script should remove this error.

**Comment by Calinou** [comment]
I don't think providing a 1:1 match with Python behavior makes sense in Godot's context, which is primarily targeted at game development. Dropping the subclass makes it possible to decrease the whole script's indentation by one level, which is always welcome when viewing/editing the code on a narrow display.

**Comment by monk-e-boy** [comment]
I'm not asking for 1:1 match with Python.

But adding a way to import scripts is pretty standard in all languages. PHP, C#, c++, Python, js etc.

Regard 'custom types' .... can you see why moving my code around causes issues? I don't care about type / custome type (Test1 / Test2). I just want my code to work. This distinction seems unnecessary because no other language imposes it on me.

**Comment by EricEzaM** [comment]
Uhhh unless I'm mistaken wouldn't using `class_name` fix this issue? I don't really see what problem adding an 'import' would solve.

**Comment by dalexeev** [comment]
> > ERROR: Test2 is not a valid type
> 
> Custom types aren't valid as type hints yet. You can use the generic `Object` type hint instead.

Strange, it works for me:

![изображение](https://user-images.githubusercontent.com/47700418/89707294-6c52fb00-d975-11ea-861a-054c1f1e624a.png)

**Comment by TheDuriel** [comment]
Yes this is supported. Though it _can_ mess up.

I'm against adding Import as I don't see much value in it. Godots Scene module encourages Component structures, rather than deep/wide inheritances.

Interfaces on the other hand I'd love.

**Comment by Kequc** [comment]
Your preload would work for `test2.gd` if you remove the `class` declaration. Gdscript just treats every file as a class. So de-indent your `_init` and that should work fine.

You can also specify `Test2` as a type. It's just a mess that's all, better to use `object` or `resource` as others have suggested for that.

**Comment by ShivamMukherjee** [comment]
Or you could use the `Script` type hint. Works most of the time for me.

**Comment by aaronfranke** [comment]
To me this sounds more like an argument in favor of removing inner classes (the `class` keyword in 3.2). I think it's much better to always have each class in its own file anyway.

**Comment by Vivraan** [comment]
GDScript loses its script like nature then.

**Comment by dalexeev** [comment]
> If I need to depend on separate scripts, I go for
> 
> ```gap
> const T: Script = preload("res://...")
> 
> func f(t: T) -> void:
>     # ...
> ```

> Also using Script is a hack

You don't need to use `Script`, then the type system will work correctly. You can do this and it will work:

```
var config := preload('config.gd').new()
```

![](https://user-images.githubusercontent.com/47700418/90983999-dde89700-e57a-11ea-8291-db1676bd65d6.png)

**Comment by Spartan322** [comment]
> You don't need to use Script, then the type system will work correctly. You can do this and it will work:

So far I've had to deliberately avoid using preload and the type hints anyway because of the cyclical dependency stuff, but that aside calling Script a hack is incidental, and that fails if you can't use preload, which I've run into enough times.

**Comment by dalexeev** [comment]
Thank you, now I understand. I try to avoid cyclical dependencies. And I get the error quite rarely. Anyway, this will be fixed in 4.0.

**Comment by Vivraan** [comment]
> > If I need to depend on separate scripts, I go for
> > ```gap
> > const T: Script = preload("res://...")
> > 
> > func f(t: T) -> void:
> >     # ...
> > ```
> 
> > Also using Script is a hack
> 
> You don't need to use `Script`, then the type system will work correctly. You can do this and it will work:
> 
> ![](https://user-images.githubusercontent.com/47700418/90983999-dde89700-e57a-11ea-8291-db1676bd65d6.png)

I prefer putting it in a `const` to treat like a type, which in most contexts should remain immutable in my opinion.

**Comment by Vivraan** [comment]
> the language is too basic to be able to write simple or streamlined code

It'd be nice to know about a place where GDScript doesn't make the cut. Could you provide an example where this is the case?

> And there's plenty of unintuitive behaviors in GDScript simply because of this comparison.

Some examples here would be illuminating as well. There's no doubt that GDScript is more stripped down, so somewhere where it becomes unbearable should be examined in this thread or another.

> Singletons make that worse, I understand lack of namespace, but any moderate project will definitely have multiple global scoped named objects that will conflict that without some type of file include or something we can't fix

Yes, this is a peeve as well. Can't deny that it'd be suitable to have namespaces. That said, `preload` can disambiguate by path.

> Also using Script is a hack from what I can see and I really wouldn't trust it

Static typing isn't a hack, but as you contend the whole language is a hack, I won't deny that it isn't if that is the case.

> Biggest issue currently with that has always been the cyclical dependencies that would always happen

Please correct me if I'm wrong but in most OOP (and not Functional) programs, I've always seen cyclical dependencies as a problem best resolved using Observers or injecting dependencies (here, using `load` instead of `preload` say, or simply using dynamic typing), although I'll not say that they're not a peeve if I encounter a plugin which does something similar. Duck typing doesn't usually care about type, while in a static context, it must be necessary to avoid patterns which introduce cycles. Of course, I believe GDScript not being able to handle something simple which isn't a problem with other OOP or Functional languages is a major spot it has called for improvements in.

> As I've said too, relying on bindings to account this is also a crutch

The whole point of computer languages is that they act as crutches, abstractions, over some kind of thing. In your moderately sized projects, it might actually help you if you ditch GDScript in favour of another language: whether or not Godot doesn't know what a class is, it usually can group your code like a class does, and until they do something about namespaces, that is the way to go here, I have come to think. Maybe it's problematic, but I haven't encountered a contrary use case on my own yet.

**Comment by Vivraan** [comment]
There is a limitation to the `preload` thing as well:
1. Preloaded consts are inherited, so somewhere you're expecting to have a new const to tell the script about another which is used in its parent, it already has it - this may not be suitable.

2. I use it for passing around type information of more derived types, which may not be suitable for something which can be done dynamically, or by using a group, or a signal (connecting is a feature of Nodes, which don't need preloading).

3. (I'm forgetting this one, it was related to polymorphism)

A better pattern must come to replace this, but it's useful otherwise.

**Comment by dalexeev** [comment]
> > Singletons make that worse, I understand lack of namespace, but any moderate project will definitely have multiple global scoped named objects that will conflict that without some type of file include or something we can't fix
> 
> Yes, this is a peeve as well. Can't deny that it'd be suitable to have namespaces. That said, `preload` can disambiguate by path.

Singleton (autoload) is not the same as `class_name` and singleton should never be used for the same purpose. Singleton is essentially a global object. The number of singletons should be kept to a minimum, and each should only be used for a truly global purpose.

I don't see much need for namespaces. Possibly for `class_name`, but not likely. In GDScript, every object is its own namespace. In the global namespace only built-in singletons, constants and GDScript functions, autoloads and `class_name`s. Namespaces can only be useful for third party addons and Asset Library.

**Comment by TheDuriel** [comment]
Namespaces and Interfaces are two things I will advocate for any day. They're useful in any project, especially as complexity grows. (Namespaces CAN be faked currently by loading the classes as Const in a named dummy class.)

**Comment by dalexeev** [comment]
@TheDuriel Also inner classes are much like namespaces (you can use `MyGlobalClass.InnerClass` and even deeper). In this context, adding the `import`/`include` keyword might make sense (to keep the file from growing due to inner classes).

**Comment by TheDuriel** [comment]
I'd rather inner classes be removed. They're quite awkward.

**Comment by dalexeev** [comment]
I agree, I avoid them too. But I meant that they work the same way as `const`+`preload`: add a type constant as a member of the class. In general, all 3 systems (namespaces, `const`+`preload` and `import`/`include`) are equivalent.

**Comment by Spartan322** [comment]
> It'd be nice to know about a place where GDScript doesn't make the cut. Could you provide an example where this is the case?

Function overloads is a massive problem especially with type hints, that aside you can't separate functions with the same name that perform slightly different behavior dependent on the arguments which is a very useful feature. The implementations of loops currently suck, there's no do...while, (yeah I get its not in python, its not fun to be missing that functionality especially when its simple and removes boilerplate with little defect) match is very strange (also there is no C# equivalent of goto case for match afaik) lack of static variables, (instead you've gotta write to some global scope class which is just insane) and the optional type hinting needs to be more robust (preferably at least supporting generic-esque capability) then python because its essential to interacting with the editor. There's also secondary things like polluting the global scope (Singleton Globals and class_name both do this and make it a chore to read any moderate size project written in GDScript, which everybody doing anything for Godot does over using a better more capable language, this is one of the reasons I say using a binding is an excuse) which is especially frustrating because either you pollute the global scope or pollute the file scope. (which also requires a filepath which is the ugliest sin in a script language) I'd much rather create reusable code that I don't have to boilerplate or manage as a class. I'd love it even more if it didn't default every file to being a class since that infects every aspect of how Godot handles scripts which breaks in every other language. I could go on but I've gone offtopic enough as it is.

> Static typing isn't a hack

Not really static typing since there isn't technically anything static about how its been doing it (so far) and the type hinting is kinda a hack anyway, also that aside it does make me question why we're cool with optional typing and optimizing it and making it a core of the VM but we have a problem with full organization control over projects.

> Please correct me if I'm wrong but in most OOP (and not Functional) programs...

Depends on the build system, most compiled languages tend to solve it by separating the dependency loading and initialization, and now even C++ is attempting something like it with modules.

> The whole point of computer languages is that they act as crutches, abstractions, over some kind of thing.

Abstraction sure, (there are some which don't really do this, least not unless you define abstraction to a degree that makes the term useless) but calling it a crutch is wrong. While it is true you should look for a language that does what you need it to in the way it should be done, all languages should at least be capable of minimizing the headache and work especially for its specific field of design. GDScript has in many aspects tended to fail on this front because of its hacky implementation and stripped down nature, while to a certain degree being stripped down allows it some nice affordances, it is undermined by its verbosity and half-assed act of appearing like a any other language arbitrarily, and then missing the mark when it comes to even that.

> In your moderately sized projects, it might actually help you if you ditch GDScript in favour of another language

If this was encouraged and actually believed by anybody using Godot, sure, but nobody does this nor is it encouraged to abandon GDScript for a better language, (and the only easily usable one is C# which has enough auxiliary problems in Godot to make even that a rather moot point) like every addon suffers from becoming bloated by Godot using GDScript as its de facto everything language, (even if it sucks at any specific thing you need) and almost nobody is willing to ditch it, I wouldn't really have a problem with this if GDScript was actually ditchable as a developer on Godot, and while the basic design of something in GDScript can generally (and literally) translate into other languages, because of the limitations of scripting by forcing particular behaviors onto other languages, and the fact those languages have deeper capability, the design is left shallow and flat. Also anything regarding translating something from GDScript is not ever scalability even if its modular.

**Comment by Vivraan** [comment]
> A community-maintained listing of languages with bindings for making scripts in Godot Engine.

If I understood you correctly, [switch expressions](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions) is the feature you're looking for.

> I'd rather inner classes be removed. They're quite awkward.

If the import system is more refined, inner classes would make much more sense since currently they are public by default. They're also extremely useful - [the FakeoDB plugin makes a query syntax for lazily executed queries] using them.

**Comment by Xrayez** [comment]
> I don't think providing a 1:1 match with Python behavior makes sense in Godot's context, which is primarily targeted at game development.

I've stumbled upon this proposal by accident, but I proposed the same `import()` keyword to be added for dynamically importing assets in Godot, see  #1632, so having both names could be confusing.

So, even if we add this feature as described in *this* proposal, it's better to have `include` keyword, in my opinion.

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments and reactions on OP).
