### ISSUE TITLE
Option for Controlling the apk Size for Gradle Build Export

### ISSUE THREAD

**Issue by titangamingglt** [godotengine/godot-proposals#1345]
**Describe the project you are working on:** An Endless Runner Shooting Android Game

**Describe the problem or limitation you are having in your project:** As The project is for android we are using monetization for it and also using Firebase for saving data. For this we are using Custom Plugins. By using Custom Plugins we must use Gradle Build option for the Android Export. Beacuse of this we have no control over the app size of our game as it becomes very large about 90 mb for a simple game.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** I think there should a Inbuilt options for controlling the app size if one is using Gradle Build. Like similar to android size analyzer or similar to this. Or there should be a feature to disable modules like we can in case of normal build system.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** I really dont know about engine development . But maybe there should be an in built option in the export android settings.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** I think this can not be workaround with scripts.

**Is there a reason why this should be core and not an add-on in the asset library?:** Because this relate to the core android export  of the engine.

**Comment by Calinou** [comment]
See also #342, #726 and #1001.

**Comment by m4gr3d** [comment]
@titangamingglt What you're describing is more of an issue with gradle rather than Godot, and for that task, there are [several documentation and articles](https://www.google.com/search?q=android+apk+shrinking&oq=android+apk+shrinking) for how to shrink an apk when building via gradle.

Unfortunately, this is an entire field in itself, so it's out of scope for engine to provide such functionality.
What I recommend would be to take apart the apk ([Android Studio can be used for this](https://developer.android.com/studio/build/apk-analyzer)) and identify the components that contribute the most to the apk size.
