### ISSUE TITLE
Division by zero should return +INF

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#1368]
**Describe the project you are working on:**
I've been building a trading system in Godot, and my code has many mathematical transformations.

**Describe the problem or limitation you are having in your project:**
I'm getting a bit tired of crashes whenever I accidentally don't check if I divide by zero or not.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I notice that in JS `1/0` is `Infinity`, and I'd suggest this is a good solution.

In python `1/0` is a runtime error, but since most stats systems use `numpy` or `pandas` anyway, they usually take care of this to be `+INF`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

```gdscript
# Calculate % change from one candle to the next
y_change = (next_candle.c - curr_candle.c) / curr_candle.c
```

and the following will commonly fail, with an error (Division by zero):

```
curr_candle.c / y_change
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

`y_change` is quite commonly `zero`, and so I have to always add an extra check:

```gdscript
y_change = (next_candle.c - curr_candle.c) / curr_candle.c
if y_change == 0:
    y_change = 0.000000001
````

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a bit frustrating and leads to many errors when I accidentally forget to check this.

I'd be interested in hearing other contributors thoughts, as this lies outside the realm of normal game dev stuff, and perhaps returning `+INF` when we divide by zero is not a great solution for some?

**Additional**
Submitted as [bug report](https://github.com/godotengine/godot/issues/41252), redirected to proposal

**Comment by Calinou** [comment]
Thanks for reopening it here. Can you edit the proposal to follow the [template](https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhancement-proposal.md)?

**Comment by tavurth** [comment]
@Calinou I've updated to match the template, thanks for the reminder!

**Comment by aaronfranke** [comment]
`1 / 0` is supposed to be an error. The input types are `int` and `int`, so the output should be `int`. Infinity only exists in the context of floats; there is no way to represent infinity with integers.

`1.0 / 0.0` is supposed to be infinity, but I just tested in 3.2 and it seems to be an error instead.

**Comment by tavurth** [comment]
<img width="430" alt="Screenshot 2020-08-14 at 22 15 34" src="https://user-images.githubusercontent.com/100964/90271701-f02c4c00-de7b-11ea-8da4-e948bffc0a8a.png">

<img width="575" alt="Screenshot 2020-08-14 at 22 16 11" src="https://user-images.githubusercontent.com/100964/90271637-d854c800-de7b-11ea-9e8c-d8c58d25df54.png">

<img width="601" alt="Screenshot 2020-08-14 at 22 16 30" src="https://user-images.githubusercontent.com/100964/90271643-dbe84f00-de7b-11ea-811a-c4bb2b592f47.png">

Noted, thanks for your input @aaronfranke! It does make sense that integer division should not produce infinity, as it's an error case. Only for real numbers should `1/0` approach infinity.

@Calinou perhaps you know better if this should be then marked again as a bug?

**Comment by Calinou** [comment]
@tavurth I think this is still feature proposal territory, as getting an error may be desired in many cases. I'd expect the physics engine to go awry if you feed it infinite coordinates for velocity, for instance.

**Comment by tavurth** [comment]
At the same time, we'd not be taking `0` as `+INF`, as `0` is `0`. Instead we'd be taking division by `0` as `+INF`, which is mathematically correct.

Let's take the example of `1 / velocity` (v):

`v = 1; 1 / v = 1`

It's more likely a bug from my perspective, but I don't know what happens in C# (unity) or other game focused languages when a division by zero occurs.

**Comment by KoBeWi** [comment]
Doesn't INF break the code anyways? E.g. you move something and accidentally divide velocity by 0, so the object moves to infinity. Or you divide damage by 0 and insta-kill everything. Or in the code you provided you suddenly get INF% change, which might break other calculations (e.g. when you try to subtract from infinity etc.). In what case it wouldn't be unexpected (i.e. INF checks wouldn't be needed)?

**Comment by tavurth** [comment]
<img width="400" alt="Screenshot 2020-08-14 at 23 05 12" src="https://user-images.githubusercontent.com/100964/90275819-9f6c2180-de82-11ea-838d-965ad6e9c1af.png">

@KoBeWi division by `+INF` gives correct results and causes no errors.

**Comment by qarmin** [comment]
If you want to use dividing by float 0, you can compile Godot with removed lines from 217 to 220 in
https://github.com/godotengine/godot/blob/aded76cb84fd1081279d2ed11fd73b553c6e6b4e/core/variant_op.cpp#L216-L222

I don't think that is good idea to allow dividing by float 0 to produce INF, because in most cases this isn't intentionally.

**Comment by tavurth** [comment]
I feel like asking scientists to comment out a few lines and recompile the engine is a bit much if we want to allow adoption by other types of consumer than game developers? 

From my perspective `1 / 0` should never result in a weird case for game development, but perhaps adding it as a warning in the same area as we currently have (project settings) would be a more dev-friendly idea?

**Comment by KoBeWi** [comment]
Changing it to warning instead of error isn't a bad idea actually.

**Comment by aaronfranke** [comment]
`1 / 0` should be an error, but `1.0 / 0.0` could give a warning maybe.

@tavurth In the last screenshot you posted, you print `1 / INF` but the math is `INF / 1.0`.

Also, in the example you posted, you have `v = 0.000000000001; 1 / v = 1000000000000`, but you should also consider that `v = -0.000000000001; 1 / v = -1000000000000`, which is another reason why float operands are required (floats have signed zero, so we can have `1.0 / 0.0` giving infinity and `1.0 / -0.0` giving negative infinity.

**Comment by tavurth** [comment]
Yep, you're correct about screenshot will correct...

**Comment by jonbonazza** [comment]
What value does having an INF number provide?

**Comment by tavurth** [comment]
**Uses for INF**

There are many uses for `INF` in programming, much more in data science and statistics however. 
A simple example of an everyday use is to find the min-max of a range of values:

```gdscript
var max_val = -INF
var min_val = +INF

for value in values:
    max_val = max(max_val, value)
    min_val = min(min_val, value)
```

We can be sure that `min_val` and `max_val` will always show us the true extents, and is cross platform. In other cases we might use `INT_MAX`, but `INF` is more understandable for stats.
Infinity is useful for many other areas of coding though, and I won't go into them here.

**This proposal**
This proposal is primarily about reducing an error case when we `divide by zero`, which should in my opinion give infinity, but currently throws an error.

It's annoying as it leads to bugs in my production code, and every time I end up with a value which could be zero, I have to check it and set to `0.00000000001` if it is so. (prevent this error).

**Comment by tavurth** [comment]
I just tested, and running `print(1 / 0.0)` returns `INF` while the game is in production mode (exported).

There's no way this could break any games that are not already broken, as this already works like this in all production exports.

This is a editor only (debug only) change, and would result in one less error while developing stats projects in Godot.

**Comment by shayneoneill** [comment]
1.0 / 0.0 is NOT suposed to be infinity. If you add an infinite number of zeros together you dont get one.

Say you take y = 1/x and graph it. On one side it converges to INF and on the other side to negative INF. So which one is it? Well its neither because 1 can not be divided by 0. The IEEE 754 for floating point math standard specifies that  there should be an Undefined Number exception raised (or just crash). 

There *IS* a Complex Infinite that can be returned for maths in the complex number realm, but for your standard float or integer math, returning INF is fault and should be changed.

**Comment by tavurth** [comment]
Hi @shayneoneill,

If you take a quick look at [this notebook](https://gist.github.com/tavurth/dea2dfbd448e265cb97e3123305a2132) you'll see that common stats libraries treat `1.0 / 0.0` as `+INF` and `-1.0 / 0.0` as `-INF`.

<img width="400" alt="Screenshot 2020-08-15 at 13 32 38" src="https://user-images.githubusercontent.com/100964/90308044-cc104f80-defb-11ea-8725-b142f83bc42a.png">

Godot treats these numbers the same way in production. (Silently returns `+INF` or `-INF`)

This proposal is about removing the editor warning when we have a float division by zero, as it's inconsistent with the production code usage.

**Comment by groud** [comment]
No, a division by zero is simply undefined. Changing math rules for the sake of avoiding a simple `if` check would be the worst idea ever, being both false and confusing.

In some libraries the division by zero may lead to +INF, but usually this is because for big dataframes, you usually prefer not having a single row making the whole processing fail (other libs may fill the value with NaN). If you try dividing by zero in core python, you will get an error.

**Comment by tavurth** [comment]
Hi @groud!

This proposal is about the removal of a crash when in debug mode.

After @shayneoneill made reference to the IEEE Std 754, and now your assumption that we would be changing math by taking this proposal, I would like to set the record straight..

[The IEEE-754 standard is quite clear](https://irem.univ-reunion.fr/IMG/pdf/ieee-754-2008.pdf) on page 37.

> The default result of divideByZero shall be an ∞ correctly signed according to the operation

So the global standard is that division by zero, should return `±∞` or `±INF`. 
**Please note that Godot currently already does this**

**Relevant passage**

<img width="800" alt="Screenshot 2020-08-15 at 15 20 04" src="https://user-images.githubusercontent.com/100964/90309733-ce2dda80-df0a-11ea-80a5-e8429d1243ba.png">

**More information**

[Stack Overflow](https://stackoverflow.com/a/14684474)

**Comment by groud** [comment]
Yes, it make sense to avoid crashes in production at any cost. But in debug mode, the program should crash when you do such operation. A division by zero is always something the user should handle themselves, and do not rely on arithmetic with INF. It's a lot better to have your program crash so that you can fix the problem, instead of having weird behaviors you don't understand why.

**Comment by Zireael07** [comment]
Given the IEEE above, I would think that INF is a better choice than outright crashing, BUT it would need to be well-documented so that people do not > rely on arithmetic with INF

Also, this likely would break compat?

**Comment by tavurth** [comment]
Perhaps we can simply rely on `INF` result, but give a toggleable warning in the dev console, in the same fashion as `unused_signal` or other warning.

To me I see the reason behind wanting to avoid accidental `/0` but forcing stats users to restart the app every time they forget a check is overbearing.

Thoughts on moving to warning rather than crash?

**Comment by KoBeWi** [comment]
> but forcing stats users to restart the app every time they forget a check is overbearing

You don't need to restart, there's a resume button next to Stop.

**Comment by tavurth** [comment]
> > but forcing stats users to restart the app every time they forget a check is overbearing
> 
> You don't need to restart, there's a resume button next to Stop.

Unfortunately due to https://github.com/godotengine/godot/issues/24684 this doesn't work for most stats cases.

**Comment by dam-git** [comment]
Although I see the usefulness of warning about the division by zero during debug, it may also be an annoyance for those that want to work with `INF` numbers and know what they are doing.
A configuration setting allowing to change the behavior in debug mode seems appropriate.

**Comment by Calinou** [comment]
> A configuration setting allowing to change the behavior in debug mode seems appropriate.

I think language behavior should not depend on project settings. This causes difficult to diagnose issues when people post code samples online.

**Comment by aaronfranke** [comment]
@Calinou It would make sense if it's a warning and not an error. We already have project settings for GDScript warnings.

![warnings](https://user-images.githubusercontent.com/1646875/131548139-e464a4a0-58c2-4da9-b5e6-9d19a58a240b.png)

**Comment by dam-git** [comment]
> > A configuration setting allowing to change the behavior in debug mode seems appropriate.
> 
> I don't think language behavior should depend on project settings. This causes difficult-to-diagnose issues when people post code samples online.

Fair point.
In that case, I would argue that we should not raise an error when dividing by zero because:
- Infinite is already defined in INF constant (we may as well use it);
- It is possible to detect infinite numbers with `is_inf()` (so it is possible to deal/work with them);
- Other functions already return INF without raising an error, for example `log(0.0)`;
- Several functions work consistently with INF numbers, e.g.: `min()`, `max()`, `abs()`;
- It's the behavior described by IEEE 754 (as far as I could check; see [wikipedia](https://en.wikipedia.org/wiki/IEEE_754) and [doc in ieee.org](https://grouper.ieee.org/groups/msc/ANSI_IEEE-Std-754-2019/background/nan-propagation.pdf#%5B%7B%22num%22%3A10%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C78.3%2C493.5%2C0%5D)).

Another argument is that, as we are right now, if I want to replicate in debug the behavior of release, I'll need to replace all the floating point divisions with something like below, which is a bit unpractical to say the least (not looking for the best implementation, it's just for the sake of the argument):
```
func division(a: float, b: float) -> float:
   if b != 0.0:
      return a / b
   else:
      if a == 0.0:
         return NAN
      else:
         return sign(a) * INF
```

**Comment by theraot** [comment]
I can confirm this is debug only. With this code (which the editor marks as error):

```
extends Node

func _ready() -> void:
	OS.set_window_title(str(1.0/0.0))

```

If exported with debug does not change the title of the window, and writes this to the console:

```
SCRIPT ERROR: _ready: Division By Zero in operator '/'.
          At: res://a.gdc:5
```

However, if exported without debug, it changes the title of the window to:

```
1.#INF
```

@tavurth I suggest you update the proposal to explain that.

---

> I don't know what happens in C# (unity) or other game focused languages when a division by zero occurs. Perhaps others can weigh in on this?

You can try in [SharpLab](EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBfsQJwAUxAdAAwD0zLAlANxW10c2gnkA). `0.0/0.0` is `NaN` and `1.0/0.0` is positive infinity.

---

By the way, I see nothing wrong with division by zero being a warning. If I type division by zero, I probably didn't mean it. And if I did, I could write `INF` or `NAN` instead.

However, be aware that this would be a warning of little value, because this code would trigger it:

```
print(1.0/0.0)
```

But this code would not:

```
var x := 0.0
print(1.0/x)
```

In fact, currently only the former is a parse error, but not the second. However the debug halts at runtime, because it is a division by zero error (only on the debugger).

---

What if we don't want `NAN`, `INF`, or `-INF` to creep into our code?

I suggest an annotation. Similar to suppressing a warning. But keep it an error. The error would happen at runtime. The beauty of the error is that you don't have to know you have a problem to find it. And you would get the error closer to the source of the problem than you would otherwise. Without it, in the situation where you don't want `NAN`, `INF`, or `-INF` you could be in for an epic debugging adventure.

With the annotation, what if I know what I'm doing and I want `NAN`, `INF`, or `-INF`?

1. The code without the annotation would behave as it currently does, no breaking change.
2. The default be the more restrictive case. We would be opting in the "unsafe mode", not out.
3. If we know what you are doing, we put the annotation preemptively.
4. Otherwise, the error would tell us where we need the annotation.

*Other things I considered are: 1. A "finite float" type, and 2. better debugging tools that would tell us where a variable got its value. I think the annotation is the simpler solution.*

**Comment by filipworksdev** [comment]
Since we're dealing with computer based abstraction of reality some languages to handle a/0 as infinity.  But 0/0 would still remain indeterminate and cannot be inf.

JavaScript V8 does this see <https://github.com/v8/v8/blob/bd8c70f5fc9c57eeee478ed36f933d3139ee221a/src/hydrogen-instructions.cc#L4063>.

In GDScript I think INF is just a really big number handled specially so this divide by zero would end up passing silently if you made it INF. You could make a special rule to turn division by zero into a warning and return INF instead.

**Comment by YuriSizov** [comment]
> `1 / 0` is supposed to be an error. The input types are `int` and `int`, so the output should be `int`. Infinity only exists in the context of floats; there is no way to represent infinity with integers.
> 
> `1.0 / 0.0` is supposed to be infinity, but I just tested in 3.2 and it seems to be an error instead.

We've discussed this in the proposal review meeting, and this is the desired behavior. If this is how it happens in 3.x, it can probably be filed as a bug and fixed. And this should also be tested in GDScript 2.0, maybe it's already fixed there.

**Comment by tavurth** [comment]
@YuriSizov I just tested this in `Godot.4.beta.1` and the output is as you say it should be.

<img width="293" alt="Screenshot 2022-09-25 at 15 40 35" src="https://user-images.githubusercontent.com/100964/192141523-820d0416-49c8-4cd3-ad8c-0eb847455ee6.png">

I will close this issue as it's not possible to implement in Godot 3.x without breaking compat.
