### ISSUE TITLE
[3D WORKFLOW / UX] General issue with inherited scenes not compensating for when source assets are updated

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot-proposals#1398]
**Describe the project you are working on:**
We have a lot of scenes and we updated the asset importers, we are working on a large game in Godot

**Describe the problem or limitation you are having in your project:**

- Inherited scenes can break and not gracefully compensate for: 
    - importer updates
    - source asset updates
    - collider scaling differences
    - script assignments lost when moving or renaming nodes
    - scaling fixes (changes in export settings, or units)
- When you modify an .fbx .dae .obj. If you save it as a new tscn / inherited scene and make edits, in the future when we make changes to importers or fix behavior it is broken by node path changes or by scaling changes, which can be user modifications to the original source asset, ideally, Godot can handle the desynced state because currently the .tscn. Will always be behind the imported / non inherited scene since you re-import the .fbx and then opening the tscn will mean that if the scaling is fixed in the .dae importer any user-added or edited objects will be broken including lights, colliders, cameras, scripts (if node is renamed/moved script attachment will be orphaned), or scaling values which are manually tweaked by the user in the engine
- User intervention is required each time this happens and it’s not clear why some problems arise, without any notification just an ERR_FAIL_COND or something in the console which doesn’t clearly let the user know ‘hey your scene was reimported and these things were lost, etc.’
- Some users are not as technical when making assets
- You don't know *where* the problems are when it happens, it's hidden from the user currently mostly.

**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**
### Fixing scaling problems
- We can compensate for this by storing user changes to inherited scenes, and notify the user we can correct the scaling, then later expand on this to other elements so it’s not just for collision shapes, the core focus here is collision shapes, we can, in theory, apply the same solution to other nodes but requires forethought.
- When the modification to the tscn is done we store the relative offset applied, then we apply this again when the scene is reimported, this prevents massive scaling differences ever breaking things.
- Each scene knows its user changes this way, and compares them against importer changes and can correct changes made gracefully, like a ```git diff`` but for the user edits vs generated edits from importers.
- This can then be applied to each 'problem' too, and compensation can be added to make this more graceful and better UX for the user with a lot of changed assets or through an engine upgrade :)
### Fixing elements when you remove a node from the importer**
- TSCN Orphan detection - to notify of a node which no longer has a parent in an inherited scene
- User is notified, nodes can be saved or reassigned using UI, or dropped completely. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Define orphan:
- a node without parent which is lost and still in the .tscn file even on resave.

Define collision problems:
- a collider which is not scaled on reimport of the inherited imported file (fbx, dae, gltf,etc)

Define loss of script:
- script lost due to original node path not existing in the inherited scene

Define importer updates:
- importer changes which fix or improve behavior to make more compatible with the format 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
- no

**Is there a reason why this should be core and not an add-on in the asset library?:**

- its a general TSCN/Importer fix we can uniformly fix for all formats.

**Comment by fire** [comment]
The main goal is for these extensions to be gdscript-able. Can you review the generic idea, it should also work for Orphan detection and TSCN validation.

There's an array of extensions.

The original problem: I wanted to move the glTF2 camera and light extensions to a "Extension class of a gltf document".

Import:
read from disk -> extension point 0 -> parse into gltf/fbx document -> extension part 1 -> packed scene -> extension part 2

Export:
packed scene -> extension part 3 -> convert to gltf/fbx document -> extension part 4 -> write to disk -> extension point 5

# Example workflows:

## Workflow extra root node:

There is a root node that is at the top.

Extension point 0 and 1 are ignored.

Extension point 2 takes the existing scene that is imported and modifies the root to be dissolved keeping children. The nodepath and string references need to be rewritten. Animations too.

## Workflow diff tool:

A diff tool can be one of the default extensions and can be subclassed.

We can make an extension 2 point gui for gdscript fixes that has shows a popup dialog for all the relevant changed locations for review.

## Workflow orphan detection:

Extension point 0 reads from the raw tscn and directly searches for orphans and deletes it since the orphans don't appear in the scene.

## Workflow gdscript is in correct:

This is a diff tool that shows every node that is invalid. The tool asks the developer for input.

## Workflow tool wizard:

Extension points 0 is a wizard.

## Workflow tool post process move to directory :

Extension point 5 is a post process option.

**Comment by RevoluPowered** [comment]
To clarify:

**Import:**
read from disk -> on_pre_import_diff -> parse into gltf/fbx document -> on_current_import_diff -> packed scene -> on_post_import_diff

**Export:**
packed scene -> on_pre_import_diff -> convert to gltf/fbx document -> on_current_import_diff -> write to disk -> on_post_import_diff

**Comment by RevoluPowered** [comment]
This is already fixed by @reduz in 4.0 with a much simpler solution.
