### ISSUE TITLE
Change editor view panel UI

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot-proposals#14]
I visit the IRC at times and the last time I was there I noticed an interesting discussion about the UI and UX, and how it's not always clear to the user that the extra icons are related to the tool. I was just working on a project and looked at the UI and thought "hm... let me give this a go."

I love UI and UX and so...

## ...you know this guy?
![original-highlighted](https://user-images.githubusercontent.com/38346332/64234434-9fd00e80-cef6-11e9-9093-cf7ec9b839aa.jpg)
*Nasty little fella right? I lived a year without ever noticing this button.*

## What if we made it longer?

**awesome**, **collapsible** and **put all the options from the top panel there instead**? Moved the **view** button next to the "distraction-free" toggle away from the top panel? *Kinda makes sense to have the two buttons together.*

### But one panel's not enough, let's make it into two!
 1. options that persist 
 2. tool related options (curve tools in the example below)

### Properties of the panels
- panel one combines the view options with camera settings
- panel two makes tool options consistent with the style of panel one (great for making users understand how to use it)
- they are transparent (0.66?) and go full opacity on mouse over
- only visible in the view last visited by the mouse

## The idea
![Panels01](https://user-images.githubusercontent.com/38346332/64234611-fe958800-cef6-11e9-98e9-505d0ca1677a.jpg)

## Collapsed
![Panels02](https://user-images.githubusercontent.com/38346332/64234614-01907880-cef7-11e9-9f33-ad45dd692347.jpg)

## Close up
![CloseUpCOncept](https://user-images.githubusercontent.com/38346332/64237444-abbecf00-cefc-11e9-8e5f-aa408ad7caf3.jpg)

## The good stuff
- noticing tool related options becomes more intuitive 
- more screen estate for the view
- can be collapsed(hidden)
- tool options get their own panel, that's **awesome**.

## The not-so-good stuff
- Godot doesn't have anything of the sort at the moment
- If someone accidentally closes it, might not be instantly evident that the options were there
- changes a something that's been the same for a long time now.

## Questions
**Q: Doesn't it waste space and make the minimum width larger than before?**
A: Actually this would mean that the two panels can be placed on top of each other, **saving space instead**:
_notice how the the view options button is right next to distraction-free toggle_
![PanelsShort](https://user-images.githubusercontent.com/38346332/64234889-8aa7af80-cef7-11e9-8e6a-5835aa58087c.jpg)

**Q: Won't it be distracting to see it on all four views in splitview mode?**
A: Not if we made it only visible in the view most recently 'mouse-overed'

## Conclusion
You know this is not something I need for a project I'm working on, it would however feel like a great UX improvement. Especially the ability to hide it when not needed.

I wouldn't be able to make a pull-request nor code it myself. This is a proposal where I hope to discuss whether this would be a welcome change and if so hopefully someone capable picks it up.

Thanks for checking this out! Turned out longer than I had thought it would.

**Comment by mrwanashraf** [comment]
would be awesome to see that beautiful UI in godot! :clap: :clap: :clap:

**Comment by ilyafuu** [comment]
it is very convenient it is necessary to improve the UI editor for 4.0 will be very beautiful :+1:

**Comment by nezvers** [comment]
It really looks slick! I'm for it.

**Comment by tomglenn** [comment]
I really like this proposal. Would love to see this in Godot.

**Comment by Altair1234** [comment]
Yeah and maybe double the size of each icon as well. They look pretty small imo.

**Comment by lentsius-bark** [comment]
@Altair1234 Defo! If any change is done to the panel it'll be the best time to double check everything is the right size. These were taken directly form a screenshot so they're the same size you are used when working with the editor. I did notice however that the "select mode" icon seems to be positioned differently from the rest of them.

 @tomglenn @nezvers @ilyafuu @mrwanashraf glad to see you like it everyone!

**Comment by stolencatkarma** [comment]
This is that extra spark that is gonna make 4.0 really special. So slick and professional.

**Comment by girng** [comment]
That toolbar menu is in the same place when you are editing a 2d scene, so when switching between 3d and 2d (unless the 2d toolbar is updated for this suggestion as well), it will not look right when switching.  I  like as much screen real estate I can get in my editor window. Just my 2 cents

**Comment by eon-s** [comment]
The main problem with this is that these tools are node-dependant and may be hard to keep track of them unless an universal floating bar is added.

**Comment by reduz** [comment]
This seems good in theory, and was discussed before, but the 3D editor can split the view into many viewports, and there would be no room to put this:

![image](https://user-images.githubusercontent.com/6265307/64252974-a2c90000-cef2-11e9-92f9-16a039ec359f.png)

So, the top bar, being unique, continues making more sense.

**Comment by girng** [comment]
@reduz That's a good point, lol you'd have 4 of those  menus!

**Comment by groud** [comment]
Despite being very nice looking, what is the most important here stays usability, and providing an efficient workflow. A few comments:
- Collapsing the bar is useless, tools should always be visible.
- The select, move, rotate, etc... tools should be mutually exclusive (it is not implemented yet, but both of those tools should not be pressed at the same time), so putting additional tools in another toolbar might confuse users. Those tools should all stick together so that you understand those tools are "linked", as they cannot be used both at the same time. 
- The problem pointed out by reduz is valid, but if the toolbar appears always on the top-left corner that might be ok. But in that case, the toolbar makes as much sense as this "floating" toolbar.

**Comment by Xenoamor** [comment]
In the office at the moment so can't check but I recall that Blender 2.8 does something very similar. It might be worth checking how they handle this across multiple viewports

**Comment by coppolaemilio** [comment]
@reduz we can make it like the floating bar when there is only one viewport and make it fixed when there are 4?

**Comment by reduz** [comment]
@coppolaemilio I think that would be very inconsistent, and so far the way it works now is not a problem.

**Comment by groud** [comment]
![2019-09-04-150307_1411x855_scrot](https://user-images.githubusercontent.com/6093119/64257116-0f5cf280-cf25-11e9-8481-bf5ee9b1666d.png)
Blender does something like that, which kind of makes sense. We could likely got inspiration from this design I believe.

**Comment by reduz** [comment]
@groud The per viewport options in Blender are viewport dependant, it's not our case.

I also really dislike icons, as they make usability worse (you just have no idea what they are, and discoverability is terrible).

We were coincidentially discussing this yesterday with @groud and the main problem we have is that new options added to the toolbar are confusing because it's not very clear that they are there.

What I suggested was to simply add a small highlight to the toolbar to show that a tool is node dependent.

As an example, something like this when you select a 2D polygon:

![image](https://user-images.githubusercontent.com/6265307/64258869-5d123480-cefe-11e9-9e13-5be01bbd4dc5.png)

**Comment by VicentGJ** [comment]
I agree with this, the way blender does it seems like a good reference, looks very nice and its very usable. I will like to see this implemented.
Besides I have always seen that toolbar like one of the weakest points of the current UI

**Comment by groud** [comment]
> I also really dislike icons, as they make usability worse (you just have no idea what they are, and discoverability is terrible).

I am not sure what you are talking about. I was talking about the vertical toolbar on the left. The icons we have could be kept the same.

> @groud The per viewport options in Blender are viewport dependant, it's not our case.

Blender has global menus too on the top. That's where we could put our own menus (like snapping, view or transform). The vertical left toolbar could only be kept for editing tools, that must be used on the viewport.

**Comment by reduz** [comment]
@groud I agree that toolbar is confusing (too much stuff) but I am not super convinced about alternatives being better. I suppose we could try doing some mock-ups to see which ones may work best.

**Comment by groud** [comment]
> I suppose we could try doing some mock-ups to see which ones may work best.

Yeah, I agree :)

**Comment by lentsius-bark** [comment]
Fantastic feedback! I was certain there were points I hadn't thought of or rather point I had thought of but didn't think them problematic enough to stop the idea from realizing.
Reading through these I am excited to see if I can come up with a different approach.
@reduz and @groud, thanks for taking time to respond to the proposal!

Also to people thinking there would be 4 of those menus, the idea was to only have it in one view at a time, for example the last window visited by the mouse, but as pointed out by Reduz this would mean that on a small screen with 4 views, this would likely provide too little space. :)

**Comment by VicentGJ** [comment]
@reduz is true usability is the most have, but that does not means fancy design does not contribute to the usability.
I think than if an UI manage to look good to the eye then it makes simpler to understand. 
Blender 2.7 UI does not have usability problems, however, besides 2.8 UI relies more on icons it is more attractive for the beginner.

**Comment by reduz** [comment]
@VicentGJ Well, to be honest, Godot is a lot more praised than Blender in the discoverability/usability department, so trying to get influences from it is probably not a good idea. If anything, I think we should stay on our current path rather than trying to copy the fourth attempt (that was not proven yet) of an application that was always criticized to be very difficult for beginners.

**Comment by groud** [comment]
> I personally think our current approach is very difficult to improve, and putting transparent things and moving things all around the place is likely not going to do a lot for usability.

Ah yeah, I agree on that. For me, the transparency hurt the readability, and moving things around is useless and confusing. So indeed, I don't think this should be there.

**Comment by TheFlamyy** [comment]
One issue I have with the current UI is that it's not possible to multiple "main views" (2D, 3D, Script, AssetLib) open at the same time.
In some cases it would be beneficial to have the 2D and 3D viewport open simultaneously (when editing viewport textures) - or 2D viewport and script editor for changing custom `tool` nodes.

Another possible change would be to make - all - dockers floating/detachable (like Gimp). You could move your docks around however it pleases you. Currently they are - a bit - limited by eight possible.

**Comment by reduz** [comment]
@TheFlanny this is planned for 4.0 already.

**Comment by Two-Tone** [comment]
@reduz Which part? The floating docks, the ability to have multiple main views open at the same time, or both?

@groud The transparency really isn't an issue if the design because it's not essential to it.  It can be adjusted for readability and even have it go fully opaque when hovered over.

I feel like there is a solution that would solve the multi view port issue. Maybe have it float over the view ports?  That might hurt readability or look bad. Could make it scrollable like what Blender does, but it can't stand that.

**Comment by Xenoamor** [comment]
I'd just like to add that in Blender 2.8 you have the option for icons or text by dragging out the toolbox:
![image](https://user-images.githubusercontent.com/7109951/64284707-1bab7480-cf52-11e9-9f9d-b9fa18e63b17.png) ![image](https://user-images.githubusercontent.com/7109951/64284717-2239ec00-cf52-11e9-9bb3-b8775378353c.png)

**Comment by alvarlagerlof** [comment]
> @VicentGJ Well, to be honest, Godot is a lot more praised than Blender in the discoverability/usability department, so trying to get influences from it is probably not a good idea. If anything, I think we should stay on our current path rather than trying to copy the fourth attempt (that was not proven yet) of an application that was always criticized to be very difficult for beginners.
> 

Blender may have been very bad ux-wise. But 2.8 really is a monumental improvement in many ways. They have also recently got support in from Ubisoft and Epic games, with Ubisoft mentionioning UX improvements as a contributing factor (There's a blog post). I wanted to learn Belder for a long time, but have always given up. WIth 2.8, I was able to get started FAST, and actually complete stuff, same with my friend. This may be wrong, but I have also gotten the impression that the Blender community has grown a lot since the release of 2.8. Criticizing it for bad UX now does not really work.

> I think we have a very specific problem here, which is that it's difficult for users to tell when a tool has added an item to a menu. As I mentioned before, the solution does not need to be that extreme.
>

![image](https://user-images.githubusercontent.com/14835120/64284646-5dd8b400-cf5a-11e9-91d4-ae8f2baa824f.png)
Please tell me if I'm wrong, but doesn't this menu support more options added by plugins, isnt't that kind of the same. Please also note how they handled making icons more clear by allowing the user to expand the menu to see text too. 
 
> I personally think our current approach is very difficult to improve, and putting transparent things and moving things all around the place is likely not going to do a lot for usability. But as always, if a good proposal comes up it can always be discussed, I just don't think this happened yet.

Transparency kind of makes the viewport feel bigger though, even though you cannot fully see what is under the bar, it does not fill the whole screen width regardless and it can therefore be resizable. Also putting it vertically could help in some cases instead of stacking horizontal bars like seen in the mockups. Putting two columns beside each other is also an option. 
![image](https://user-images.githubusercontent.com/14835120/64285146-6f6e8b80-cf5b-11e9-9a06-ec1fb7c0ecde.png)

While I'm at it there are some other things that could be improved (not really knowing what's already changing in future versions here). 

- ![image](https://user-images.githubusercontent.com/14835120/64285212-9c22a300-cf5b-11e9-8514-53fabb86fa64.png)
The file system is divided in files and folders, I think it would be clearer (and frankly more standard) to show file in the tree too.
- 
![image](https://user-images.githubusercontent.com/14835120/64285325-d8ee9a00-cf5b-11e9-8ff4-904d04fe1708.png)
Clicking on Theme.tres here opens a new inspector, but it isn't really clear that you have actually opened something new. I just kind of jumps to new content. Might be clearer to expand from the button instead of replacing the entire view. For me, it quickly gets very confusing once you are a few levels deep.

- 
![image](https://user-images.githubusercontent.com/14835120/64285672-413d7b80-cf5c-11e9-840c-cfd8364d87b6.png)
2d and can bee in the same scene, but then when you press on script you get a whole new file list of scrips, which seem to be independent from the scene files. So bascially there are both modes at the top and tabs. Confusing. 
![image](https://user-images.githubusercontent.com/14835120/64285791-895c9e00-cf5c-11e9-919e-49caa9458f5b.png)

- 
![image](https://user-images.githubusercontent.com/14835120/64285849-a85b3000-cf5c-11e9-97f9-6bbc6a3ce1e4.png)
![image](https://user-images.githubusercontent.com/14835120/64285887-bb6e0000-cf5c-11e9-9618-8aa994f897c2.png)
Open in editor and a script button, but a folder icon and a <> or {} would be much clearer I think.

- 
![image](https://user-images.githubusercontent.com/14835120/64285988-eb1d0800-cf5c-11e9-833c-747a312f4bce.png)
I can change the top left one to the right or left one without any effect. Maybe drag and drop fits better?

- 
![image](https://user-images.githubusercontent.com/14835120/64286090-199ae300-cf5d-11e9-8e39-6fc57d588c09.png)
Just created a "empty", but what is it, and why is my previous scripts showing? This should be obvious.

- ![image](https://user-images.githubusercontent.com/14835120/64286254-68487d00-cf5d-11e9-915a-6319774f707c.png)
When i clink on a menu item here, I expect the currently showing menu to change when hovering over other menus, like other programs.

- ![image](https://user-images.githubusercontent.com/14835120/64286377-a3e34700-cf5d-11e9-9731-b20ed6556ec8.png)
Previews don't show up on all tabs.

- ![image](https://user-images.githubusercontent.com/14835120/64286460-ce350480-cf5d-11e9-8ce8-42b5e9780d19.png)
The debugger seems to be a lot more than a debugger.

- ![image](https://user-images.githubusercontent.com/14835120/64286508-ec026980-cf5d-11e9-955f-7e91d59acff2.png)

- ![image](https://user-images.githubusercontent.com/14835120/64286599-1fdd8f00-cf5e-11e9-8365-bdd2036179e6.png)
Isn't the inspector about the node too? I think the title could be improved here.

- ![image](https://user-images.githubusercontent.com/14835120/64286664-44396b80-cf5e-11e9-9cb3-4a909600630a.png)
Title this with "Outline" or something similar.

- ![image](https://user-images.githubusercontent.com/14835120/64286726-616e3a00-cf5e-11e9-9375-9ada96b6f0a8.png)
Barely noticable find menu here. VSCode has a good implementation I think.
![image](https://user-images.githubusercontent.com/14835120/64286799-7b0f8180-cf5e-11e9-9244-68685bf5f86a.png)

- ![image](https://user-images.githubusercontent.com/14835120/64286866-95495f80-cf5e-11e9-8d70-dc3702332b01.png)
Not fitting in the "File" menu in the script editor.

While I am proposing a lot of change here, I just want to say that this is only because I think this is what's best for the editor, and I do not what to burn it. There are a lot of good things that I really like with Godot, but not mentioning them here makes me sound really negative.

**Comment by Calinou** [comment]
@alvarlagerlof The screenshots you posted seem to be from Godot 3.0.x (judging by the checkbox icon appearance). Many of the issues have been fixed in 3.1 and in the `master` branch (which will become 3.2 in the future).

**Comment by MCrafterzz** [comment]
Even if the toolbar isn't changed to the suggested look at least make tool icons right aligned. This way they are clearly separated.

**Comment by kkmzero** [comment]
The UI makes me feel claustrophobic every time I use Godot, which is quite often. It would need complete overhaul. I think we can learn something from Blender 2.8. Unfortunately, I'm not UI designer, so I can't point on exact issues and tell you "yes, this is what's wrong with Godot's UI" but I'm sure there are talented people who can make game development in Godot feel less like being locked in tiny box.

+ The viewport is completely unintuitive. It's very hard to navigate in your own scene and precisely put objects where they should be unless you manually enter coordinates to object's properties, which is also a horrible task since Inspector window is so clustered.

**Comment by asheraryam** [comment]
@kkmzero I usually use the editor on a 23" screen and it's fine but when I switch to the 15" laptop it's impossible to use, so I can see how it can be quite bad.

**Comment by kkmzero** [comment]
> @kkmzero I usually use the editor on a 23" screen and it's fine but when I switch to the 15" laptop it's impossible to use, so I can see how it can be quite bad.

I can't imagine working in Godot on 15" screen but this shouldn't be issue on 17"+ screens. In other words, "buy a huge screen" is not an argument for me since UI definitely can be improved. I changed font size settings to smaller values and it immediately felt better but still it's far from optimal. Here is example:
![meshinstance](https://user-images.githubusercontent.com/32756443/64861474-54250f80-d630-11e9-98d9-aa331559ec02.png)
I would love to see numbers with at least 1 decimal place, which is not possible if your value is negative. And I don't really want to resize windows every time I want to change some value, and then again, change them back if I want to work in viewport or write a script. I know it sounds kind of nitpicky but I see it as obstacle in my workflow and this is just one issue from the list. And to be honest, I'd be more than happy to hear what other Godot users think. It's always better to have more views on some problem.

**Comment by seppoday** [comment]
I like the idea, but I think it's better to think about the whole UI redesign. If we will jump from one spot to another it will be mess.

**Comment by pycbouh** [comment]
> I think it's better to think about the whole UI redesign

@seppoday It is much more practical to reduce big tasks to smaller, more maintainable tasks. For example, imagine if we changed the whole editor UI. It would be impossible to agree on it as a whole, everyone would like some parts and hate other parts. The discussion would be cluttered and all over the place. But smaller changes can be discussed in detail instead, each change and idea given its time to be polished and appreciated.

**Comment by silverkorn** [comment]
@seppoday , https://github.com/Calinou/godot/commits/improve-editor-theme ?
It's an "official-_ish_" WIP that had not been updated since around a month and a half.

**Comment by lentsius-bark** [comment]
@pycbouh considering your latest work i think we can close this issue as it supersedes this idea and implements the same and extended functionality in a "godot" way.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/3550.
