### ISSUE TITLE
Theme Editor User Experience - gathering feedback, request for ideas.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-proposals#1438]
**Describe the project you are working on:**
Hopefully I will be able to rework the theme editor. After a brief discussion with @groud, it seems like another part of the editor that may need some work - but slightly smaller in scope than the tileset/tilemap editor 😉.

**Describe the problem or limitation you are having in your project:**
The theme editor user experience is not optimal. Hopefully I will be able to make some improvements, but want to gather feedback and ideas first, and have a think about how it will all be laid out.

There are a few tickets floating about related to the theme editor, but it would be good to have as much as possible in one place.

Cheers!

Related tickets:
https://github.com/godotengine/godot/issues/40827
https://github.com/godotengine/godot/issues/39138
https://github.com/godotengine/godot/issues/29038
https://github.com/godotengine/godot/issues/22252 (more related to Scrollbar theming options than the editor itself)
https://github.com/godotengine/godot/issues/29063

**Comment by EricEzaM** [comment]
One thing I have found is that the workflow is pretty slow and clunky.

![image](https://user-images.githubusercontent.com/41730826/91722374-7dda9c00-ebdd-11ea-8f37-9eecb30532a7.png)

It would be nice to have something like:
1. Right click on element in preview
2. "Edit This" to take you straight to what you want to edit in the inspector (or wherever)

**Comment by EricEzaM** [comment]
Also there are a bunch of ui elements that are not included in the preview window. Not sure for the reason, would have to investigate why and if they can be added.

**Comment by BenMcLean** [comment]
I'd like to make some retro pixelly themes for the Godot GUI at some point. Maybe port over the [text mode style skin I made for libGDX](https://github.com/BenMcLean/libgdx-dos-skin)

**Comment by EricEzaM** [comment]
@BenMcLean I think maybe you misunderstood; this issue about the Theme Editor (as in, the thing you use to edit UI themes), not the editor theme.

**Comment by TicklesTheBrain** [comment]
The biggest hurdle with Theme Editor is that what you are not really editing a theme, you are editing a collection of styles, which are not associated with each other. For this editor to be useful, it should let you set some theme-wide values (like primary colour, primary font, margin-size-A, etc. should all be user-defined) and then let you use those values in the styles. Without something like this, I'm afraid any UI changes to the Theme Editor would just be superficial as they would not remove the vast number of clicking you have to do every time you want to change something substantial about in a theme.

**Comment by EricEzaM** [comment]
> The biggest hurdle with Theme Editor is that what you are not really editing a theme, you are editing a collection of styles, which are not associated with each other. For this editor to be useful, it should let you set some theme-wide values (like primary colour, primary font, margin-size-A, etc. should all be user-defined) and then let you use those values in the styles. Without something like this, I'm afraid any UI changes to the Theme Editor would just be superficial as they would not remove the vast number of clicking you have to do every time you want to change something substantial in a theme.

@TicklesTheBrain have you seen #850? I have experienced the same frustration  and that is one solution.

**Comment by TicklesTheBrain** [comment]
@EricEzaM No, i hadn't seen that. thanks. Yeah, having CSS-style property cascading/override would probably be the quickest way to improve usability, but I am talking more about CSS-style variables. Like different types of nodes using the same colour property variable in some way that is customizable by user.

**Comment by EricEzaM** [comment]
Yeah I also made an editor plugin for colour management but it doesn't replace colours across your styles in the editor.

I agree having a system like you describe would be of great value though.

**Comment by univeous** [comment]
I think the theme editor is ~~nearly can't use~~ a little hard to use for now.
- If I create a StyleBoxTexture in the theme inspector and click it, the theme in the bottom panel will be replaced by TextureRegion:
![image](https://user-images.githubusercontent.com/40604180/105574400-4690a580-5d9f-11eb-9ed5-7211fc259234.png)
and after I set up my texture, I need to click to fold my StyleBoxTexture(otherwise the theme panel will not show up), then find my theme in the FileSystem and click to open it again to preview my style:
![image](https://user-images.githubusercontent.com/40604180/105574405-527c6780-5d9f-11eb-8c1e-d08fcde64bb9.png)
 for every style in the theme, I need to repeat this process; This is pretty annoying.

- I think it's common to have multiple styles for a single class item, such as Button. Maybe I need a round button, a rectangle button, etc. If I want to create these styles, I need to click "Edit Theme" - "Add Item", and then find Button type, and then input name like "Round Button Disabled":
![image](https://user-images.githubusercontent.com/40604180/105574552-64123f00-5da0-11eb-8689-5ae3bfe0c35a.png)
then add texture for my style. (Remember every time I create and edit a style I need to find my theme in FileSystem and click it again after edit)
And then repeat it for focus and hover and normal and pressed style...
For the rectangle and other button styles, repeat it (5*style number) times again(And re-click theme!). It's pretty super annoying.

- After I finally managed to create my button styles, I want them to apply to my buttons.
So I need to find my style in theme - right click and copy - find the button(s) I want to apply my style - scroll to the Custom Styles and click to unfold it - right click on the style and paste.
It's very error prone because the stylebox is just named StyleBoxTexture. And It's just one style for normal texture; I still need the others(hover, focus, etc.) so I need to open my theme again and repeat it. It's...oh...

My suggestions:
- Make theme panel and TextureRegion can exist at the same time.
- Make it easier to create the styles for a Class Item.
- Make it easier to apply styles to Control node, For example, For button, There can be a drop-down menu to select styles from the theme, like round or rectangle or something, and it will apply all 5 styles to the button.

**Comment by Calinou** [comment]
> Make theme panel and TextureRegion can exist at the same time.

This is implemented by https://github.com/godotengine/godot/pull/45085.

**Comment by univeous** [comment]
> After creating a base StyleBox, you can copy and paste it to various theme styles to save time. Once you need to modify one of them separately from the others, use **Make Unique** in the resource dropdown.
> 

That's what I do for now. But for a button I have to copy and paste 5 styleboxes, it's kind of annoying. What I expected is that after I create these 5 styleboxes in my theme, it's easier to apply them to buttons.

> I think you can already specify a resource name in the Resource section of the StyleBox subresource, but it won't be displayed in the inspector preview. While this could be changed, it could also confuse people about which resources are saved as external resources and which ones are built-in.

If it won't be displayed in the inspector preview it's a little pointless. I don't think people will confuse because saved resources will always have an extension name.

**Comment by tlitookilakin** [comment]
Ideally, some way to define theme parameters when registering a custom class inheriting Control. As of now, plugins can add custom classes, but there's no way to integrate them directly with the theme editor, the best you can do is copy styles from built-in classes.

**Comment by barbaros83** [comment]
this #1791 proposal sounds very intuitive to me, have all the ui elements be selectable from the example UI sheet, and then display all the editable parts of that UI element in the inspector, this combined with a global override for all the UI theme settings should improve the theme editor alot

**Comment by pycbouh** [comment]
I'm currently reworking the Theme Editor, mostly prompted from my own experience and frustration, but I also took the time to collect all the problems described here or in linked issues/proposals. The lists seems as follows:

* Hardcoded preview is limiting, doesn't represent all possible controls, their states.
* Editing theme properties is hard and unintuitive in the Inspector dock. It provides low abstraction which can be a pain to navigate and keep a sense of.
* Editor lacks usability that can be gained by allowing users to select previewed controls and be able to instantly edit them specifically.
* When working on a theme its important to be able to quickly add predefined theme items from the default theme, so that you can configure them.
* Editing subresources, such as Styleboxes, can be hard and painful, involve many steps and jumping between contexts.
* Edited theme properties lack description, even though you can see them when overriding individual properties of controls.
* Themes lack the ability to override default values.
* Themes lack the ability to easily assign values from predefined sets/to custom controls.

In my rework I've already addressed a lot of it, or am in process of doing it. Some things are already simplified by an early PR (https://github.com/godotengine/godot/pull/46593), but my current work went much further than that and quickly makes that PR obsolete. I will probably close this proposal and open my own, with the proposed *implementation* to solve the problems mentioned, but I need a bit more time to finalize the demo. In the meantime, I sometimes share my progress on RC with other contributors.

**Comment by ray90514** [comment]
Hi, I would like to take part in GSOC 2021 and be interesting in the idea of reimplement Godot's theme editor.
I have a preliminary conception about this, the new theme editor has a list or a tree to display item which is in the theme, 
after selecting a item or a class of items on the left side, it will be available in Inspector dock and be previewed on the right side .
![image](https://user-images.githubusercontent.com/56381255/111643282-cdab4880-8839-11eb-8100-b0610716652c.png)
Is it a practical conception?

**Comment by pycbouh** [comment]
> Hi, I would like to take part in GSOC 2021 and be interesting in the idea of reimplement Godot's theme editor.

Hello! As you may read in the message above yours, I'm already working on the new Theme Editor. This leaves the opportunity for the student project regarding the matter up in the air, currently. Your idea is insteresting. Though implementing it would mean hardcoding a lot of scenes for different controls and their states. In my current development I already allow loading arbitrary scenes, plus I want to make a preview configurator as an alternative. I guess this can be useful for the latter.

**Comment by Shadowblitz16** [comment]
I really want to get rid of using icons for widgets like numeric up/down buttons and scrollbar arrows
which also has missing styles for alot of icons

I also want to see support for progress bar scrolling like what windows 95 had and two focus styles, one for overlay and one for what the actual control looks like.

**Comment by pycbouh** [comment]
@Shadowblitz16 This doesn't sound like something that requires any changes in the Theme Editor or in the Theme resources. Those proposed changes are about how specific controls use theming, and some can even be solved by creating custom controls that act the way you want.

**Comment by pycbouh** [comment]
I'll close this one, as ideas and problems were successfully gathered and are addressed in #2505.
