### ISSUE TITLE
Rename the `.import/` folder to a different name

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#1521]
**Describe the project you are working on:**
Many different projects and helping many people getting started with Godot

**Describe the problem or limitation you are having in your project:**
Very often I find myself communicating the difference between the .import files and the .import folder. I think part of the confusion it's because they share the name, but they behave in a completely opposite way: the folder can be ignored because it's generated, while the .import files are very important to properly import textures, meshes etc.
I've seen people assuming that the .import files are not important.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Rename the .import folder to .cache

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Rename the .import folder to .cache

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is editor's internal functionality and it can't be changed from script

**Is there a reason why this should be core and not an add-on in the asset library?:**
Same as previous, can't be done with scripting

**Comment by aaronfranke** [comment]
As discussed in https://github.com/godotengine/godot/issues/23368 and https://github.com/godotengine/godot/pull/38607, a better option would be making a `.godot/` folder and putting things like `.import/` and `.mono/` inside of it.

**Comment by QbieShay** [comment]
I'd still prefer to have it be .godot/cache

**Comment by aaronfranke** [comment]
I think `.godot/cache` would be redundant since `.godot/mono` is also cache and `.translation` files are also cache. `.godot/imported` is more specific and gives a hint to its purpose of storing imported assets.

**Comment by QbieShay** [comment]
Ok, fair point

**Comment by vnen** [comment]
I will argue again that this isn't a cache. It might look like it in the editor since it can reimport everything, but if you want it to run directly it won't work without this folder being created by the editor first. So I prefer `imported` to, or maybe `generated`.

**Comment by Zireael07** [comment]
Imported vs .import still has the problem that newcomers will confuse them - maybe generated is a better name?

**Comment by aaronfranke** [comment]
@Zireael07 Well, the idea is that beginners would never have to know about `.godot/imported`. If they are having issues with their project, they can just delete the `.godot` folder. If they are making a gitignore, they just add the `.godot` folder.

**Comment by akien-mga** [comment]
We discussed this with core developers today and we agreed that renaming the `.import/` folder could be good. Incidentally, it will also be useful for Godot 4.0 as the format of imported files is incompatible with 3.2, so currently you run into issues if you try to open a 3.2 project in 4.0 without deleting the `.import` folder first.

What's left to define is the actual name that we should use. Based on the above discussion, we talked about:

- `.godot/imported/`: The top-level `.godot/` folder can then also be used for other kind of "safe to remove" files, such as `.godot/mono/`, and possibly in the future some project-specific metadata if we think that some of it needs to be stored in the project folder. One drawback mentioned was that the `.godot/` folder might be confused with the `project.godot` file, thus recreating the same issue that motivates this proposal. But I think it might be clear enough to users that `.godot/` and their `project.godot` files are different things, and less confusing that `.import/` and hundreds of generated `*.import` files.

  * This is implemented by #38607. If @neikeq approves, then the same can be done for `.mono/` with #38704.

- `.internal/imported/`: Same as above, but avoids the potential `project.godot` confusion. But `.internal` for some that is relevant for and included in exports might also be confusing.

- `.cache/` is rejected as per https://github.com/godotengine/godot-proposals/issues/1521#issuecomment-694235256, since this is not cached data. There's also already a cache folder in the user home.

**Comment by akien-mga** [comment]
We talked about making a poll to choose the name, but to be fair, I think that `.godot/imported/` is just fine and I'd be inclined to just go with it.

Upvote (:+1:) if you agree, downvote (:-1:) if you disagree (and make a counterproposal/justify).

**Comment by neikeq** [comment]
>  If @neikeq approves, then the same can be done for `.mono/` with https://github.com/godotengine/godot/pull/38704.

I requested some changes to that PR. Other than that I approve the change.

**Comment by jonbonazza** [comment]
@akien-mga i think the genrrated android project build files should also go in the .godot folder
