### ISSUE TITLE
Add reparenting method

### ISSUE THREAD

**Issue by lmerriam** [godotengine/godot-proposals#153]
**Describe the project you are working on:**
A Diablo-style 2D action RPG.

**Describe the problem or limitation you are having in your project:**
Any time I pass around nodes (for example, I have status effects which are transferred from an attack object to it's victim) reparenting them requires that I first get the existing parent, remove the child, and then add them to their new parent. This causes what feels like unnecessary code and scene tree traversal:
```
node.get_parent().remove_child(node)
new_parent.add_child(node)
```

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
A reparenting function built in to the engine would be faster than my GDScript and would save me from repeating most of the code in the example above every time I need to reparent.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Implement a new `node.set_parent(new_parent)` method or change the existing `add_child(node)` method to remove any existing parents by default

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is a common use case that would be faster if implemented in the engine.

**Comment by clayjohn** [comment]
Why not just define your own function?

```
func reparent(node, new_parent):
    node.get_parent().remove_child(node)
    new_parent.add_child(node)
```

Also related: https://github.com/godotengine/godot/pull/23816 (PR implementing this that was closed after failed to find consensus; https://github.com/godotengine/godot/issues/21781 (related feature proposal)

**Comment by lmerriam** [comment]
> Why not just define your own function?
I think this is a common enough use case that it shouldn't have to be re-implemented in every project.

**Comment by Janders1800** [comment]
Yeah, it could also have the option to not trigger areas wen reparented, currently every time you reparent something on runtime triggers all the areas is in (since technically it leaves the scene and enters again). And to reparent on site (keeping global transforms).

**Comment by Eoin-ONeill-Yokai** [comment]
I think the need for this would really go away if there were some kind of Extension Method type of feature so that functions can be added to Object classes dynamically.

**Comment by Calinou** [comment]
@Eoin-ONeill-Yokai There was a [pull request](https://github.com/godotengine/godot/pull/15639) for this a while ago, but it was closed.

**Comment by akien-mga** [comment]
See discussion on godotengine/godot#36301.

Basically, adding a `Node::reparent` method should be fine, which should strict take care of `remove_child()` and `add_child()`, without trying to keep the global transform for nodes which can support it.

Keeping global transform as described in godotengine/godot#21781, if still wanted, should be done via specific methods in `Node2D` and `Spatial` (i.e. not overloads of `reparent`, but new methods like `reparent_with_transform`).

**Comment by Xrayez** [comment]
This might be a crazy idea but here's an alternative to proposed `Node::reparent` method. Technically I should've just probably write a new proposal but I think it's unlikely that the following idea is accepted, and because I already share a similar problem as this proposal describes.

Compare:

### `Node::reparent`

```gdscript
old_parent.get_child(0).reparent(new_parent)
```

**vs.**

### `Node::adopt_child`

```gdscript
new_parent.adopt_child(old_parent.get_child(0))
```

When comparing on the level of code snippets:

```gdscript
# Current way:
node.get_parent().remove_child(node)
new_parent.add_child(node)

# Proposed solution in this proposal:
node.reparent(new_parent)

# My proposal:
new_parent.adopt_child(node)
```

This is the reverse of `reparent` and closer to `add_child` behavior. Currently, if you attempt to add a node which already has a parent you'll receive an error:

![godot_add_child_existing_parent](https://user-images.githubusercontent.com/17108460/98820024-476b9980-2436-11eb-8740-5ff63ff1368c.png)

A method like `adopt_child` would do the necessary reparenting under the hood. Similar to how we have `get_node_or_null()` to circumvent the limitation of `get_node()` for when there's no node found.

The upside is that this potentially encourages better practices by discouraging the usage of `get_parent()` for traversing the tree for everything (only on the level of naming).

Both `add_child()` and `adopt_child()` start with "ad", which improves auto-completion naturally.

Also, `adopt_child()` already better suggests that the node has another parent compared to `reparent()`, IMO.

This can be renamed to `add_child_reparent` but the downside is that it would become verbose and would be even more verbose with `add_child_reparent_with_transform()`...

I know the name may seem weird but it describes the behavior quite accurately. Think `master`/`puppet` keywords for networking, where `slave` was renamed to `puppet`. In fact, what I propose actually promotes better social values, don't you agree? If we want to completely eliminate the life aspect, then even existing "child" should not be there...

I personally have no problem with either type of wording, I think we should take emotional responsibility in this regard, those are just words unless you supply meaning to them.

I'm also totally fine with `Node::reparent` as long as it's added to the engine in any form. 🙂

In theory, both methods can be added and ***complement*** each other.
