### ISSUE TITLE
Godot on Steam - add remote play together ability

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot-proposals#1541]
Godot is now on Steam
https://store.steampowered.com/app/404790/Godot_Engine/
But it doesnt support any of the features - just two features actually.

If you look at another engine 
https://store.steampowered.com/app/248170/Clickteam_Fusion_25/
It has Remote play together. 

This allows for two player to share a godot screen remotely and interact with it.  It is especially useful when one of the two users has a problem and is asking for assistance. It can also be used as a teaching tool

**Comment by Calinou** [comment]
Can Remote Play Together be integrated without linking to the proprietary Steam library? If so, we'll have an hard time finding a contributor to do it.

**Comment by KoBeWi** [comment]
I think there's nothing to enable. Remote Play already works in any game, without any Steam libraries (you just need to lanunch the game via Steam). Remote Play Together is the same, but you can connect to another user instead of the same account. If this needs to be enabled, it's probably one toggle in the game/app admin page.
