### ISSUE TITLE
Add a signal emitted on every frame played to AnimationPlayer

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot-proposals#1594]
**Describe the project you are working on:**

An alphabet learning game. The player flies a dragon through scenery looking for specific letters and avoiding obstacles.

**Describe the problem or limitation you are having in your project:**

A donkey kicks a barrel into the player's path. I have an AnimationPlayer playing the kick+return to neutral position animation, but I don't know when the animation reaches the frame where the donkey's feet visually touch the barrel in order to start the barrel flying.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

If AnimationPlayer reported its current frame, I could then detect when the donkey's feet visually touch the barrel, and then start the barrel's flight path.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It would be a simple signal, "frame_changed(frame)", where the frame parameter is the current frame being played.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This should be a core feature of AnimationPlayer, as it would be useful under many circumstances. Probably the best workaround at this point is to use a timer that fires off at the approximate contact time within the animation. However, this is clumsy and prone to timing errors.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Reporting the current animation frame being played is a fundamental responsibility of an animation player.

**Comment by Calinou** [comment]
Signals emitted on every frame are generally considered an antipattern, as they negate any potential performance improvements provided by the use of signals (compared to polling). See https://github.com/godotengine/godot/pull/24208 where a similar feature was rejected.

**Comment by UnwarySage** [comment]
For this specific use, consider perhaps a call function track with the barrel kicking function called at the right moment would be the way to go.

**Comment by SoapSpangledGames** [comment]
I solved it by using a timer to synchronize the two actions.

**Comment by qaptoR** [comment]
Bumping instead of creating a new proposal.

I was about to begin working on a feature for the `AnimationPlayer` to add a new 'key signal` track that would function like so

1. add `key signal` track
2. add keys to track with optional name per key
3. in any script connect a function to `AnimationPlayer.key_signal(animation :String, key_index :int, key_name: String, time :float)`

I don't think there's really any need for more than 1 signal track per animation since the keys are for specific moments in the animation.

Inverts the dependency relationship between a script and the 'call method' track essentially, so instead of the animation subscribing to particular functions, the functions subscribe to the animation.

The project I'm working on is a generic action rpg. I want to connect a 'deal_damage' function to multiple animations. but I also want other functionality to happen beyond dealing damage. So instead of adding a track and keyframe for every possible function for every animation, It would mean adding 1 signal key to the hit frame for each animation and then subscribing those functions to the animation player signal.

**Comment by Calinou** [comment]
Closing per the above comments.
