### ISSUE TITLE
Add a normalmap property to Polygon2D

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#1651]
**Describe the project you are working on:**
2D game

**Describe the problem or limitation you are having in your project:**
Sprites support normalmaps, and canvas item shaders have already the property `NORMAL_TEXTURE` built-in.
It is possible to create a very simple shader that does normal maps for polygons, but the workflow isn't great, because one has to go and make the material unique for every polygon2D

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This is a UX enhancement for when using polygon2D and normal maps

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add a property normal map to both animated sprite and polygon2D

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be worked around by making a custom shader, but the UX is pretty bad.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Godot already supports built-in normal map in the canvas item shader, and it is very odd that there is no property to make use of this for some of the 2D rendering nodes, while others have it (mesh2d and sprite).

**Comment by Calinou** [comment]
> Add a property normal map to both animated sprite

For the record, this can already be done by suffixing an animation with `_normal` but it's undocumented: https://github.com/godotengine/godot/pull/40269

**Comment by insomniacUNDERSCORElemon** [comment]
For polygons it'd be interesting if features like this could be done via vertex colors as well. Also with the ability to save/load vertex color maps (I could see multiple layers, use in code, or use in shaders as a potential useful options).

Though there's currently a small issue with vertex colors and the color interpolation non-square quad-faces (that are automatically triangulated). That would likely be an annoyance at least when those non-square faces are also supposed to be rounded faces (normal map) or with a gradual falloff for specularity. Shouldn't be visible when a quad's verts only has 2 sets of colors and they are adjacent (horizontal or vertical gradient) as the edge will propagate color the same no matter which way is is oriented.

Note: some of my perspective here is altered by the ability to use a vertex color trick of adding more geometry to get fake face colors, an old technique (used for vertex color Skyboxes in the originals of Spyro and Homeworld 2). Example: ![left is solid colors, middle is gradients, right is the mesh](https://i.imgur.com/LKOjjrc.png)

You can see the color interpolation issue in the middle example (zoom in). And the mesh on the right, this is certainly something that isn't really viable until there's a proper vertex painting editor (and even then, a color palette/index system would help in cases where the same exact colors were used on many vertices... like possibly normal maps). 

Sidenote related to palettes, allowing multiple layers of vertex color (for albedo at least) would allow for less color usage and easier editing later (if you had a balloon with color on one layer and realistic shading on another layer, you can change the color of the balloon by changing 1 value rather than changing every vertex manually).

**Comment by Calinou** [comment]
This should be addressed by CanvasTexture in 4.0, since it can contain normal and specular maps. In 4.0, any 2D texture is now defined using CanvasTexture (even Controls).
