### ISSUE TITLE
Remove the political/rebelious statements from the encryption documentation

### ISSUE THREAD

**Issue by basdp** [godotengine/godot-proposals#170]
I'm going to ignore the basic template because this is not really a 'bug' or a technical feature. It's more clear to explain it like this.

We have this documentation about why encryption might be interesting:
https://docs.godotengine.org/en/3.1/tutorials/io/encrypting_save_games.html#why

Although I think it's funny and I kind of enjoyed to read that section, I really feel that it takes away from the professional image and flow of the rest of the documentation. I think we should refrain from any political, or existential criticism on society in the documentation. Besides, there are of course a lot more reasons to use encryption that this example alone.

Again, I really think it's a funny passage. But I feel that the Godot docs is not the place for that. Also, the Documentation guidelines require the docs to
> "be clear and objective."
https://docs.godotengine.org/en/stable/community/contributing/documentation_guidelines.html#what-makes-good-documentation

I propose to remove or rewrite this section into an objective explanation of applications of this type of encryption.

**Comment by Xrayez** [comment]
If there could be a single acceptable place in the software development field for such humor/sarcasm/bitter truth in documentation, it would certainly be the game development field. 🙂

Just look at the Python's spam, ham, and eggs.

**Comment by groud** [comment]
Honestly, I don't think a single funny paragraph in a big documentation in an open source project makes it less professional. I would even say it make the community a little bit more welcoming :)

**Comment by golddotasksquestions** [comment]
https://www.reddit.com/r/godot/comments/d6wqb1/official_docs_shouldnt_be_political_even_in_satire/

**Comment by basdp** [comment]
Couldn’t find that PR, sorry. (Githubs search is shit..)
I agree that humor is really appreciated in game development! But this is sarcasm against most likely the developers that want to use this tutorial, which is really out of place.

**Comment by clayjohn** [comment]
This is a very contentious issue within the Godot community. 

In my opinion, the only viable solution is to replace the content of the joke with another joke that is less likely to offend people.

@basdp At the same time, many users are attached to this doc as it is funny and it is at no ones expense. However, I think it should be changed just because this topic comes up every month like clockwork and its just not worth it to keep the tutorial. Most of us devs like the idea of being able to have humour in the docs. It makes it a little easier to provide thousands of hours free work when there is a little humour to spice things up. But so many users complain about the tutorial, and many seem triggered by the phrase "capitalist oligarchy", that it isnt really worth defending at this point IMO.

**Comment by clayjohn** [comment]
Actually I'm going to close this for a few reasons
1.  Not using template -> violates rule 1 
2. This topic is highly contentious and often leads to unnecessary flame wars
3. Documentation proposals don't require a proposal issue, they can proceed directly to PRs

With that being said. @basdp you clearly have a good idea for improving the tutorial. Please write up your proposed improvement and PR it to the ``godot-docs`` repo. The discussion can continue over there. And then we have the benefit of discusses a specific change rather than discussing changes in general.
