### ISSUE TITLE
Add more tutorials on how to make editor and inspector plugins

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1712]
**Describe the project you are working on:**
Rougelike

**Describe the problem or limitation you are having in your project:**
I want to learn how to make custom language plugins for the built in script editor and inspector layout plugins
however there aren't many tutorials on plugins

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest a whole section in the docs be dedicated to something like this ranging from very easy plugins to advanced ones.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
NA

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
yes,
NA

**Is there a reason why this should be core and not an add-on in the asset library?:**
there needs to be more tutorials on advanced topics such as these so that people can help improve godot

**Comment by Calinou** [comment]
There are already tutorials about this here: https://docs.godotengine.org/en/latest/tutorials/plugins/editor/making_plugins.html

That said, [keep in mind we're moving away from step-by-step tutorials in favor of a reference manual](https://github.com/godotengine/godot-docs/issues/3390).

Anyway, I'm closing this since documentation requests are off-topic for the Godot proposals repository.
