### ISSUE TITLE
Add a vignette effect to Environment or CameraEffects

### ISSUE THREAD

**Issue by Darkinggq** [godotengine/godot-proposals#1806]
**Describe the project you are working on:**
testing demo 3D for Godot 4.0

**Describe the problem or limitation you are having in your project:**
I see textures on my desktop it's too inconvenient to insert godot and I don’t want independent shaders, because you need ready-made ones inside the World Environment to completely full so that users can make post process effects faster prototype

![image](https://user-images.githubusercontent.com/17591539/98856003-fc6d7880-246d-11eb-9796-7f6ba6591577.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
here GLSL code for vignette [link youtube](https://www.youtube.com/watch?v=caQZKeAYgD8) it's just not difficult
![image](https://user-images.githubusercontent.com/17591539/98858748-30e33380-2472-11eb-9a0c-f5256f0b4428.png)

customize any vignette suitable game style desire

**Is there a reason why this should be core and not an add-on in the asset library?:**
yes inside the core of godot

**Comment by Calinou** [comment]
> I see textures on my desktop it's too inconvenient to insert godot and I don’t want independent shaders, because you need ready-made ones inside the World Environment to completely full so that users can make post process effects faster prototype

I don't think you absolutely need to have a vignetting effect in a *prototype*.

**Comment by alexfreyre** [comment]
I don't agree with this PR. Godot weights is so little because not everything gets implemented only the most important features and that has a beauty inside. 

I think that there are things that are missing in the Environment node for example, advanced color grading, lens flares, god rays.

A filter like vignette, lens distortion or chromatic aberration could be important for some users and not for others and that is simple to find and to write, that is why this kind of shader isn't implemented and SDFGI for example is implemented.  

I agree with the idea of keep Godot simple and very small!

**Comment by Jummit** [comment]
> I don't agree with this PR. Godot weights is so little because not everything gets implemented only the most important features and that has a beauty inside.

This shader would only be a few lines of code. It wouldn't make Godot any larger.
 
> I think that there are things that are missing in the Environment node for example advanced color grading

Godot 4.0 has LUT

> lens flares, god rays.

These would be significantly larger and all your other points (Godot should stay simple) say they shouldn't be included.

> A filter like vignette, lens distortion or chromatic aberration could be important for some users and not for others and that is simple to find and to write, that is why this kind of shader isn't implemented and SDFGI for example is implemented.

In my opinion these fit perfectly in WorldEnvironment alongside DOF blur, bloom, SSAO and all the other post processing shaders.
 
> I agree with the idea of keep Godot simple and very small!

Adding vignette would be a simple and small addition.

**Comment by Calinou** [comment]
I started working on a vignette option in CameraEffects: https://github.com/Calinou/godot/tree/cameraeffects-add-vignette

**Comment by arkology** [comment]
Is there actually any need for this feature to be in core?
This is quite specific and really easy to implement using shaders.

**Comment by jcostello** [comment]
@arkology vignette is so common used that make sense to have it on core IMO

**Comment by Calinou** [comment]
To add to the above comment, using a built-in shader also runs *slightly* faster compared to a TextureRect that spans the whole viewport:

```
Vignette mode is now: 0 (texture)
Project FPS: 1327 (0.7 mspf)
Project FPS: 1314 (0.7 mspf)
Project FPS: 1311 (0.7 mspf)
Project FPS: 1312 (0.7 mspf)
Project FPS: 1311 (0.7 mspf)
Vignette mode is now: 1 (shader)
Project FPS: 1325 (0.7 mspf)
Project FPS: 1345 (0.7 mspf)
Project FPS: 1347 (0.7 mspf)
Project FPS: 1347 (0.7 mspf)
Project FPS: 1344 (0.7 mspf)
Vignette mode is now: 2 (none)
Project FPS: 1346 (0.7 mspf)
Project FPS: 1354 (0.7 mspf)
Project FPS: 1353 (0.7 mspf)
Project FPS: 1354 (0.7 mspf)
Project FPS: 1348 (0.7 mspf)
```

**Comment by Calinou** [comment]
Closing, as https://github.com/godotengine/godot/pull/54482 was rejected due to concerns over adding bloat to the tonemapping shader (which is performance-sensitive).

As mentioned above, vignetting can easily be implemented using a TextureRect that spans the whole viewport. This is *slightly* slower, but it's also much more flexible (since you can use any texture or shader you wish).
