### ISSUE TITLE
Allow creating `.gitignore` and `.gitattributes` files when creating a new project

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1813]
**Describe the project you are working on:**

This is relevant for any project that uses Git for version control. It would be nice for myself to have these automatically created, however I am also concerned about other people's projects (see next point).

**Describe the problem or limitation you are having in your project:**

`.gitignore` files are (practically but not technically) necessary for Git repositories if you want to prevent Git from tracking and committing generated files. Also, `.gitattributes` is nice to have since we can tell Git to handle line endings properly. I always remember to add these files in my own projects, but it would be nice if it wasn't necessary.

I am a maintainer on the Godot Asset Library. I often see people forgetting to put proper gitignore files in their projects when posting their projects on GitHub and accidentally committing files they shouldn't like the `.import/` folder. Also, I occasionally see people accidentally having carriage returns in their projects, which is a mistake caused by having Git configured incorrectly.

There was also [some concern about possible confusion](https://github.com/godotengine/godot-proposals/issues/1521#issuecomment-697575796) with the `.godot/` folder.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

We can solve all of the above issues by having Godot automatically create these files when creating new projects. It will be easier for users who know about these files since Godot will handle it for you and you don't need to copy anything manually, it will make it harder for users who don't know about these files to forget them since (again) Godot will handle it for you, and it will avoid confusion of what should and shouldn't be ignored because (yet again) Godot will handle it for you.

For people who aren't using Git, these files are useless, but also they are harmless and extremely small (total 116 bytes) and of course it's super easy to delete them. We can also allow disabling their creation (as the below PR does).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Branch: https://github.com/aaronfranke/godot/tree/gitignore-create

PR: https://github.com/godotengine/godot/pull/42447

3.2 backport (may or may not actually end up in 3.2): https://github.com/aaronfranke/godot/tree/3.2-gitignore-create

The PR makes the creation of these files be optional in the project creation dialog. You can also create them from inside an existing project using the new "Create Version Control Metadata" button.

I also threw in the ability to disabling the creation of the default environment, since it was in mostly the same part of the code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This can be easily worked around by copying the appropriate files into your project.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Since this ideally would happen in every project when creating new projects, it would be best to do in core. Of course, it can be worked around easily for each individual project, but some users will forget to do this.

**Comment by jonbonazza** [comment]
Can we make it optional instead? In my case, i usuallly habe Github (or Gitlab) create .gitignore for me when I create the project. I prefer this approach since it's an artifact of git, not godot. I'd be okay if it's an option, but I don't believe it makes sense to have godot itself require every project to include them.

**Comment by aaronfranke** [comment]
@jonbonazza Yes, the idea is to make it optional. The main thing up for debate is whether it should be on or off by default.

**Comment by pycbouh** [comment]
> The main thing up for debate is whether it should be on or off by default.

In my opinion, the main thing in the air currently is **usability**. I guess we have to bring our arguments from the linked PR here so that people know about them, because nobody is going to read two threads.

So, yes, this should be optional, as it already is in your implementation but in the most convoluted way. Instead of several checkboxes it should be **a single option** "Create Git files" (which can be later upgraded to "Initialize Git repository") and that option should be available **on the project creation form**, either visible right away or under a fold. That way people can configure this one-time-per-project thing quickly. And no, going into the full editor settings from the project manager is not a good way to handle this.

![image](https://user-images.githubusercontent.com/11782833/98923970-5f4e2680-24e5-11eb-94bb-573a461fc69a.png)
*Sorry for a very crude mockup*

This shouldn't be a discriminatory feature either. We can support a number of VCSs that people use and make no assumptions about current trends or popularity within a biased medium of GitHub and open source software. But it is okay for the initial implementation to provide only one VCS in the form of Git. It's just that it should be designed in a way that would allow us to implement more further down the line. When more VCSs are introduced, the single option on the project creation form should receive a dropdown list of options for [VCS] in "Create [VCS] files".

We can still utilize the editor settings to store the default values for the checkbox and the dropdown list, and specific options for each VCS. Say, if you really need to create only one of the two files proposed here, then this can be ticked off in the editor settings, but the action itself should enabled or disabled when we create a project.

Further improving usability, this action should also be made into a top editor menu option. This would allow for existing projects to have their VCS initialized at any time. We already have a subsection dedicated to VCSs, we can use it:

![image](https://user-images.githubusercontent.com/11782833/98923321-907a2700-24e4-11eb-9060-88e518930210.png)

**Comment by aaronfranke** [comment]
@pycbouh Alright, you've convinced me, I'll see if I can change the PR to make these available in a dropdown or popup of some kind in the project creation menu in the next few days. And I guess it could make sense to allow creating these files later in that menu, but I'm curious how we would do this in an agnostic way. IMO the ability to create a `.gitignore` should not be tied to having Git integration with the Godot editor. Would it be something like Project -> Version Control -> Create Version Control Metadata -> Select "Git" and then you can choose `.gitignore` and `.gitattributes`... or something?

**Comment by pycbouh** [comment]
> Alright, you've convinced me

❤️ 

> be like Project -> Version Control -> Create Version Control Metadata -> Select "Git"

I think this would suffice. Like I've mentioned in the PR, I personally don't see much reason in such granularity and would just create both. If you think the files are easy to delete when you don't want them at all, deleting them if you need only one of them should be a non-problem 🙃 Cheekiness aside, if we do need granularity, I guess your idea works: after you select "Git" there a small popup can come up with a bunch of settings.

**Comment by aaronfranke** [comment]
@pycbouh I updated the PR, and I also made a 3.2 version for testing purposes. Links in the OP, let me know what you think :)

**Comment by pycbouh** [comment]
@aaronfranke Thank you, that's about something that I've had in my mind. Took 3.2 branch for a spin, seems to work as expected.

![image](https://user-images.githubusercontent.com/11782833/99070048-97766780-25c0-11eb-9e0a-7cd6a0425908.png)
![image](https://user-images.githubusercontent.com/11782833/99070226-e2907a80-25c0-11eb-9f1d-39eb5f56fa12.png)

Maybe an explicit "Cancel" here wouldn't hurt:

![image](https://user-images.githubusercontent.com/11782833/99070340-11a6ec00-25c1-11eb-9fa3-b7d527ecb73d.png)

**Comment by likeich** [comment]
I would also support this for subdirectories such as custom android builds. Custom Android builds contain many files that are unnecessary and require manually adding an Android-specific gitignore to the android/build/ folder. Being able to create this automatically would be nice.

One like this has been working for me: https://github.com/github/gitignore/blob/master/Android.gitignore

**Comment by Calinou** [comment]
> Custom Android builds contain many files that are unnecessary and require manually adding an Android-specific gitignore to the android/build/ folder. Being able to create this automatically would be nice.

Shouldn't the Android source ZIP contain that `.gitignore` file?

**Comment by likeich** [comment]
> Shouldn't the Android source ZIP be made to contain that `.gitignore` file? This way, the `.gitignore` would be created automatically when you use the **Install Android Source ZIP** functionality.

Yeah that's what I'm talking about. Earlier it was talked about making it optional though. So maybe the same setting is also checked when installing the android source ZIP.

**Comment by aaronfranke** [comment]
@likeich I'm not very familiar with Android, but I can work on this after my PR is merged. We could code it so that if there is already a .gitignore at the project level, it will make one in the Android folder.
