### ISSUE TITLE
Use more pythonic syntax with enums

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1878]
**Describe the project you are working on:**
NetworkingTest

**Describe the problem or limitation you are having in your project:**
~~Enums and Consts are basicly the same thing but they use a odd syntax for gdscript and enums and const are written diffrently~~
Realized const enums are actually dictionaries Xd

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Change enums ~~and consts~~ so they use this syntax

```gdscript

#valid
enum MyEnum:
    ValueA = someConstValue,  #valid
    ValueB = someNonConstValue,   #valid
    ValueC : someConstValue, #invalid
    ValueD : someNonConstValue,   #invalid

#invalid
enum MyEnum {
}

#invalid
enum MyEnum = {
}
```

It would not only be a cleaner look

## EDIT 
I want to mention the reason I suggest '=' or `:` is to be easier to understand `:` is more of a scope or inheritance thing and `=` is more of a assignment thing

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Above

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This would not only be more pythonic but its more consistent.
 
**Is there a reason why this should be core and not an add-on in the asset library?:**
enums ~~and consts~~ already are this would just make syntax more consistent

**Comment by Calinou** [comment]
Python has neither enums nor constants in the core language :slightly_smiling_face:

**Comment by Shadowblitz16** [comment]
@Calinou yes i know but I think the ':' syntax for blocks is more pythonic

**Comment by Shadowblitz16** [comment]
https://github.com/godotengine/godot-proposals/issues/1882

**Comment by Shadowblitz16** [comment]
@aaronfranke 
@dalexeev

I just realized const enums are actually const dictionaries

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and the lack of activity here).

**Comment by dalexeev** [comment]
In fact, the proposal is not very clear, this is its main problem. The main point of this proposal is

```gdscript
enum MyEnum:
    MY_VALUE_1,
    MY_VALUE_2,
    MY_VALUE_3,
```

instead of

```gdscript
enum MyEnum {
    MY_VALUE_1,
    MY_VALUE_2,
    MY_VALUE_3,
}
```

This is a cosmetic change and I am not against it. I admit, in this case, I got excited.

Saving one line is not that important, but it really looks more consistent. An enumeration, unlike an array/dictionary, is a definition, not a value literal, so it is ok that the syntax is different. Moreover, in 4.0-dev named enums are no longer dictionaries.

@Calinou, I suggest reopen it. The lack of support in this case is not so obvious. At least, it should be given a second chance.
@Shadowblitz16, please correct the OP to be clearer.

**Comment by Calinou** [comment]
@dalexeev Feel free to open a new proposal for this :slightly_smiling_face:
