### ISSUE TITLE
Add a project setting to flush standard output on every printed line

### ISSUE THREAD

**Issue by icolwell** [godotengine/godot-proposals#1912]
### Describe the project you are working on

A server that connects to clients for multiplayer purposes. The server version of godot is used while headless. 

### Describe the problem or limitation you are having in your project

Since the project is a server, it is useful to control multiple instances of them via systemd.
stdout from the godot project is not captured by journalctl, however stderr is. This is undesirable since information is missing from the server logs.
[See here for related Q&A question](https://godotengine.org/qa/74351/godot-server-no-stdout-when-run-non-interactively?show=88665#c88665).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

According to @Calinou in above linked question:

> In the interest of performance, Godot will only flush the buffer when it exits.
> This should probably be changed for server builds at least, as this is problematic for logging using systemd.

I propose that there be a project setting or export config (not sure which one would be best) that toggles between flushing on every print or flushing on exit. The default would be current behaviour of flushing on exit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A project setting or export config (not sure which one would be best) that toggles between flushing on every print or flushing on exit.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can kinda work around this by always using `printerr` for the server code. Not a real solution at all though.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a pretty core feature when trying to use godot server version in production.

**Comment by icolwell** [comment]
Thank you @Calinou !

**Comment by PoisnFang** [comment]
what's the short term work around for this? @Calinou

**Comment by icolwell** [comment]
@PoisnFang 

> You can kinda work around this by always using printerr for the server code. Not a real solution at all though.

**Comment by PoisnFang** [comment]
yeah.... I still get the error even with all my print function as `printerr` I should also mention I use the mono version

**Comment by BCD-qed** [comment]
At least since 4.1 (I have not checked prior versions) there has been a project setting for this behavior that defaults to false. 
[bool] application/run/flush_stdout_on_print = false

There is also a setting to change the behavior of printing to debug that defaults to true.
[bool] application/run/flush_stdout_on_print.debug = true

Navigate: Project > Project Settings > Application > Run
If you do not see either setting, you can search for "flush" and the settings will be displayed.
To have it always visible turn on "Advance Settings" 

You can find both settings in the documentation [here](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#property-descriptions)
