### ISSUE TITLE
we need enable etc2 in GLES2 mode !

### ISSUE THREAD

**Issue by denghe** [godotengine/godot-proposals#1937]
so many 5 years+ old android devices support etc2 texture but use gles2 mode, and i have been used it in cocos2dx for 3 years without problem. 
gles3 mode does not support batch is bad, i have test draw Label control 3000+, gles2 60 fps, gles3 10 fps.  i have tested redmi1/2,  gles3 mode have so many bug and lag, but gles2 mode no problem.
my custom shader code for etc1 is so diffucult for me!
please remove Vram compression's Import Etc 2 's GLES3 limit !

**Comment by clayjohn** [comment]
Thanks for making a proposal!

We ask that all users read and follow [The Rules](https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal) when making a proposal. Specifically, please use the provided template instead of deleting it. The template is there to help you organize your proposal appropriately, and to help other users review your ideas.

**Comment by denghe** [comment]
thank u very much ! i'll try 3.24.... but how to set a compressed picture ( like etc2 <ktx 20> or pkm 20 ) or import to Sprite ?
