### ISSUE TITLE
Navigation bake on gridmap with parsed geometry type set up as static collisions

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot-proposals#1948]
### Describe the project you are working on
3d game with gridmap

### Describe the problem or limitation you are having in your project
NavigationMeshInstance ParsedGeometryType->StaticCollisions ignores gridmap
(Video preview)
https://imgur.com/a/7Bv5DX0

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make navigation baking be able to bake navmesh onto gridmap collisions (now it can only bake geometry)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Even editor viewport cant see gridmap's collisions, probably same thing with navigationmesh (white bush collision and nothing on gridmap)
![image](https://user-images.githubusercontent.com/46406204/101348755-3da24e00-389d-11eb-9cdb-543f4a965285.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Hopefully there is workaround would be suggested because I have no idea how to do it now

### Is there a reason why this should be core and not an add-on in the asset library?
Because gridmap has collisions and it is child of navigationmesh, I see no reason why it shouldnt bake navmesh on it

**Comment by Calinou** [comment]
I believe this is because like TileMaps, the GridMap collision shapes are only instanced when the project is running, not in the editor.

**Comment by JohnTator** [comment]
> I believe this is because the GridMap collision shapes are only instanced when the project is running, not in the editor. TileMaps also have this quirk.

I'm not familiar with how the baking works, but is it possible to make the baking temporarily instance the collision shapes of GridMap objects for the purpose of baking and remove them upon completion, or something else that achieves similar results?

Not being able to bake a GridMap's navigation based on collisions makes it nearly unusable in the vast majority of cases where you would use a GridMap. 

The only work arounds currently are to either manually model the NavMesh in modeling software (which negates the benefits of using a GridMap and requrires a great amount of time and effort), or to manually add the NavMesh to each mesh within the MeshLibrary (since each NavMesh needs to touch adjacent NavMeshes, you cannot respect the Agent's height/radius this way, effectively treating the radius as 0)

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/56855.
