### ISSUE TITLE
Improve Navigation with multiple agents

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1966]
### Describe the project you are working on
Prototyping an RTS game in Godot 4.0

### Describe the problem or limitation you are having in your project

- Agents can exit the navigation mesh. This can lead to invalid states such as hanging off the edge of a cliff and phasing inside walls.
![image](https://user-images.githubusercontent.com/14253836/101770327-ede6a100-3aad-11eb-8272-e5ca2a32ad2a.png)
![image](https://user-images.githubusercontent.com/14253836/101770382-00f97100-3aae-11eb-8123-fefd31913af1.png)

- Groups of >5 are inefficient navigating corners. They all navigate "single-file" instead of around each other.
![image](https://user-images.githubusercontent.com/14253836/101770531-300fe280-3aae-11eb-825c-265e4278a9e1.png)

- Similar to as seen above, all agents try to reach the exact same point which leads to "mushing" and inefficient motions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Add an option to `NavigationAgent` to disallow exiting the navigation mesh.
- Improve collision avoidance. If this is not possible to do performant, allow crowd simulation add-ons for the asset library.
- This should be fixable by increasing `path_max_distance`, but the value `10` still hosts the same issue.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Stay on mesh flag:
![image](https://user-images.githubusercontent.com/14253836/101771303-55e9b700-3aaf-11eb-9628-dc65dadbe39d.png)
![image](https://user-images.githubusercontent.com/14253836/101771778-140d4080-3ab0-11eb-9d97-b8359ef22a2a.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Most of these issues cannot be worked around easily. The only alternative would be to make a new pathfinding system from scratch, or use a custom module.

### Is there a reason why this should be core and not an add-on in the asset library?
NavigationServer is already part of core.

**Comment by barbaros83** [comment]
yes this is something im struggling with because the astar and navigation node in 3.2 doesnt provide support for calculating multiple paths at once.
and i played around with the navigation agent in 4.0 and that also doesnt seem to work with multiple units, maybe its possible to code around that limitation but it would be very nice to have support build in for an rts like scenario where you need to move lots of units around at the same time.

**Comment by Killfrra** [comment]
The problem is that the avoidance library doesn't know what's going on with the navigation mesh, it works separately from building the path in its own little world. But while browsing the net, I came across [this demo](https://guidogarcia.net/demos/rvo2-js/) (turn on the obstacle checkbox). That is, it is theoretically possible to inform lib about the boundaries of the NavMesh, saying that these are obstacles and yes it will probably affect performance. And as for multiple paths... I don’t know (yet)
