### ISSUE TITLE
Add an icon indicating that the sub-resource tree is clickable in the Inspector

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot-proposals#2047]
### Describe the project you are working on
Any
### Describe the problem or limitation you are having in your project
Consistency/usability of hidden drop-drown submenu tree list with no visual hint

![image](https://user-images.githubusercontent.com/23405122/103290793-a25b4f00-49ea-11eb-81ab-05419cda5c24.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add same icon

![image](https://user-images.githubusercontent.com/23405122/103290832-b69f4c00-49ea-11eb-8302-74c037106a2d.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add icon anchored to right side of title of dropdown menu, like down for other ui element. Since other drop down lists have it, it might just be a boolean to toggle, I don't know.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
This is inspector itself

**Comment by zachthemystic** [comment]
This might be my issue too, so I'm making my comment here.
![Screen Shot 2021-05-14 at 5 07 21 PM](https://user-images.githubusercontent.com/1402196/118331768-0af92300-b4d7-11eb-9ec8-c749558b907e.png)
As a newcomer, given the Font (and also, FontData) resource in the inspector (see picture), I did not know I could click on the Font/FontData icons (the 'Tt' and the grey square 'Abg'). I knew I could click on the checkbox on the left, and on the downward carat on the far right.

Little did I know it was really important to click on the graphic itself! That would have saved some time if I had known that. It was double reveal when I realized it was true with FontData also.

My request is to make those icons appear more clickable, such as having their own downward carat. It would have saved me some time as a newbie, and I thought to raise the issue here before I forgot. Thanks!
