### ISSUE TITLE
Allow ScrollContainer's ScrollBar to always claim space

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2121]
### Describe the project you are working on
Attempting to use a ScrollContainer, to show it's limitations, in my opinion. As I said I would do in (#2119)

### Describe the problem or limitation you are having in your project
The pop-in of the scrollbar, which rescales/moves content inside the scrollbar can be quite jarring. (This mostly happens whenever a scrollbar is used on a piece of UI that can be resized). I want to reserve a place for the scrollbar, so it doesn't need to adjust the content whenever it spawns. If the scrollbar isn't currently necessary, it will leave a blank space.

![scrollcontainerpopin](https://user-images.githubusercontent.com/10502115/104601426-86a6a880-567a-11eb-9f03-94ffa444729e.gif)

_The issue: Whenever the scrollbar pops in, the content is moved/rescaled. I show this in editor, because I was too lazy to make the panelcontainer resizable in-game, but it works the same._

Essentially, allow me to give the `Scrollbar` inside a `ScrollContainer` a `rect_min_size`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
An additional setting for ScrollContainers, which allows the space required for the scrollbar to be shown is always claimed for the scrollbar.
This can either be a manual `x,y` input, or a boolean which automatically takes the minimum size that the scrollbar can be, and claims that.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Doing this with a custom built Scrollbar/ScrollContainer is very easy, as you can just set a `rect_min_size` and make the scrollbar invisible.

![scrollcontainerpopincustom](https://user-images.githubusercontent.com/10502115/104602315-94a8f900-567b-11eb-972b-e2c0cb93de84.gif)
_The scrollbar on the right doesn't move the content of the "ScrollContainer". It is assigned its own space, which isn't taken by the content when the scrollbar becomes invisible_

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not that I know of.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: Addition to functionality of ScrollContainers

**Comment by AndersonDeMatos** [comment]
That's the enhancement that I need in ScrollbarContainer for my project.
<a href="https://imgur.com/zUZVeb2"><img src="https://i.imgur.com/zUZVeb2.png" title="source: imgur.com" /></a>
The Itens name area will have vertical scrolling enabled (but the VScrollbar will be always hidden), the numbers area will have horizontal scrolling enabled (but the HScrollbar will be always hidden), and the area where the itens are (bottom right) will have both vertical and horizontal scrolling enabled.
When I scroll any VScrollbar it will send a signal to scroll the other VScrollbar, and when I scroll any HScrollbar it will send a signal to scroll the other HScrollbar. The Idea is that the lines of itens stay always aligned with the itens names and the rows are always aligned with the numbers. When I press any Item Name button all the itens of that line are select and when I press any number button all the itens of that row are selected.
The problem is that when I reach the end of any scrollbar they are not aligned anymore because the contents of the bottom right area are moved a little more to compensate the space used by the scrollbars, but the contents of the top right and bottom left areas don't have that extra space, so they can't keep the alignment with the bottom right area.
<a href="https://imgur.com/ffQKckh"><img src="https://i.imgur.com/ffQKckh.png" title="source: imgur.com" /></a>
With this enhancement I could do what I want to keep the itens always aligned with the names ans numbers.

**Comment by AndersonDeMatos** [comment]
That's the enhancement that I need in ScrollbarContainer for my project.
<a href="https://imgur.com/zUZVeb2"><img src="https://i.imgur.com/zUZVeb2.png" title="source: imgur.com" /></a>
The Itens name area will have vertical scrolling enabled (but the VScrollbar will be always hidden), the numbers area will have horizontal scrolling enabled (but the HScrollbar will be always hidden), and the area where the itens are (bottom right) will have both vertical and horizontal scrolling enabled.
When I scroll any VScrollbar it will send a signal to scroll the other VScrollbar, and when I scroll any HScrollbar it will send a signal to scroll the other HScrollbar. The Idea is that the lines of itens stay always aligned with the itens names and the rows are always aligned with the numbers. When I press any Item Name button all the itens of that line are select and when I press any number button all the itens of that row are selected.
The problem is that when I reach the end of any scrollbar they are not aligned anymore because the contents of the bottom right area are moved a little more to compensate the space used by the scrollbars, but the contents of the top right and bottom left areas don't have that extra space, so they can't keep the alignment with the bottom right area.
<a href="https://imgur.com/ffQKckh"><img src="https://i.imgur.com/ffQKckh.png" title="source: imgur.com" /></a>
With this enhancement I could do what I want to keep the itens always aligned with the names ans numbers.

**Comment by L4Vo5** [comment]
After https://github.com/godotengine/godot/pull/48008 and https://github.com/godotengine/godot/pull/55694, setting `vertical_scroll_mode` or `horizontal_scroll_mode` to `ScrollContainer.SCROLL_MODE_SHOW_ALWAYS` achieves the desired effect.
I actually wish the old behaviour was available too 😅

**Comment by KoBeWi** [comment]
> ScrollContainer.SCROLL_MODE_AUTO achieves the desired effect.

It doesn't

https://github.com/godotengine/godot-proposals/assets/2223172/aae9452f-e299-465a-941c-a949eea1dcc2

SHOW_ALWAYS is probably the closest to the requested feature.
Actually, it's better than having an empty space in place of the scrollbar, so I think this proposal is resolved?

**Comment by KoBeWi** [comment]
I think we could add SCROLL_MODE_RESERVED, which is like SCROLL_MODE_ALWAYS, but hides ScrollBar when it can't be scrolled.
