### ISSUE TITLE
Allow Selecting frames in AnimatedSprite - `select frames by spritesheet` by clicking & dragging

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2252]
### Describe the project you are working on
Game Project

### Describe the problem or limitation you are having in your project
I was importing a spritesheet into an AnimatedSprite, but I only needed half the frames. I instinctively clicked and dragged over all the frames I wanted to select. Sadly this only selects the one that was initially clicked on.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow selecting multiple frames by hovering over them, while holding the `Left Mouse Button` down.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![HoldSelectFrames2](https://user-images.githubusercontent.com/10502115/107081146-89686980-67f2-11eb-8bcf-55a1e0b2dde8.gif)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Can be worked around by selecting them individually.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: UX improvement on Core functionality

**Comment by RoniPerson** [comment]
I just wanted to point out a question which should be answered before implementing this. How should this draging behave when draging to a new line? At the moment i can think of three options.

A rect selection:
![grafik](https://user-images.githubusercontent.com/67514656/114308090-efb78400-9ae2-11eb-85cc-b9fc6922a11d.png)
Only select hovered frames:
![grafik](https://user-images.githubusercontent.com/67514656/114308119-01992700-9ae3-11eb-987f-c4ef2a5ed45d.png)
Like a text selection:
![grafik](https://user-images.githubusercontent.com/67514656/114308282-8e43e500-9ae3-11eb-8b14-f4a48a0d5bfb.png)

All of this options could have a usecase because the best salution depends on how the sprite sheet is set up. But I dont know which would be the most used salution.

**Comment by Calinou** [comment]
You can hold <kbd>Shift</kbd> to perform a multiple selection, similar to selections in the OS file manager.
