### ISSUE TITLE
New UV Channel imports into a scene file

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#2266]
### Describe the project you are working on
3d project

### Describe the problem or limitation you are having in your project

We wanted to import more UV channels for use in Godot games.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The GLTF2 importer will use the all-new extended mesh format to store UVs.

The GLTF2 exporter will store the UV channels from the mesh into the gltf2 file.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Discussed at the rendering meeting. https://gist.github.com/fire/878b71a2b69fcb47c1c685e96163e05d

New glTF importer will have a dropdown to select the lightmap channel:

We default to texcoord1.

* None
* texcoord0
* texcoord1 
* .. 
* texcoord7

This vec2 is to be stored into custom3 (vec4) and aligned to XY because it would waste two floats if not aligned.

The layout for UV:

The glTF importer will write 

* texcoord0->uv,
* texcoord1->uv2
* texcoord2,3->custom0
* texcoord4,5->custom1
* texcoord6,7->custom2

The PackedScene to glTF2 exporter will write:

* uv->texcoord0
* uv2->texcoord1
* custom0->texcoord2,3
* custom1->texcoord4,5
* custom2->texcoord6,7

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Adding new UV channels is not a script change. It is a gltf2 importer change.

### Is there a reason why this should be core and not an add-on in the asset library?

Importing UV channels is a core change. It is unable to be integrated with the scene importer/exporters and still be a script.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/2192.

**Comment by Lexpartizan** [comment]
I need this functionality right now, as I'm going to use additional UV channels in shaders. Since one channel (UV2 is reserved for lightmaps) is not enough for me. I want to store more information in the bag to greatly reduce the amount of materials.

I need this functionality right now, as I'm going to use additional UV channels in shaders. Since one channel (UV2 is reserved for lightmaps) is not enough for me. I want to store more information in the bag to greatly reduce the amount of materials.

I just wanted to remind you that this functionality is needed not only when importing and in the editor, you need to provide easy access to these UV layers in the Godot shader language. UV3, UV4, etc.

I also liked the idea expressed here that the last UV layer should be used for lighting. But I understand that this may cause some problems in other parts of the engine.

I am currently working on a texture atlas (more precisely, a texture array) and would like to transmit the tile number using UV3, for example. This would solve a lot of problems for me, since I would be able to provide several other materials (from 16 to 64) on one material without unnecessary drawcalls. At the same time, without sacrificing mipmapping or repeating textures, that is, without overestimating the number of polygons.

**Comment by Lexpartizan** [comment]
https://www.youtube.com/watch?v=Rw8UL2q6VYI
i trying make texture atlas with tiling and need two UVs channel.

**Comment by fire** [comment]
Updated https://github.com/godotengine/godot/pull/52504#issuecomment-915792241 with a video.

https://user-images.githubusercontent.com/32321/132633244-a8a9838e-afd2-471a-84c0-0df9bc32e641.mp4

**Comment by Lexpartizan** [comment]
@fire You are a real hero! I've already given up all hope of seeing this! Thanks! Thanks! Thanks!
