### ISSUE TITLE
Add `ScriptEditor` `get_current_text_editor()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2278]
### Describe the project you are working on
I plan to make plugins which should work with active script `TextEdit` (like detecting some changes, maybe even change current `ScriptEditor` code.

### Describe the problem or limitation you are having in your project
One thing I miss is getting current script `TextEdit`.
I feel hacky each time using the tree to get nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding `ScriptEditor` `get_current_text_editor()` could solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
get_editor_interface().get_script_editor().get_current_text_editor()
```
returns `TextEdit`
I believe it should be in `ScriptEditor`, just not exposed yet.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Only using the editor tree (that is always ugly).

### Is there a reason why this should be core and not an add-on in the asset library?

This will be used for other plugins

**Comment by Xrayez** [comment]
I confirm the potential usefulness of this feature.

I've previously tried to add various controls to the script editor's menus and this required typical `get_child(0).get_child(2)` mess while trying to fetch needed elements.

The use case I have is an editor plugin which takes a script and compiles it into another language, and this would work best if the "Convert to XXX" could be added directly to the script editor, and not via `Project` → `Tools` menu item, because I'm actually interested in processing the currently edited script.

See for example [GDScript transpiler frond-end plugin](https://github.com/Xrayez/godot-editor-plugin-tools/blob/master/addons/script_editor/script_editor_plugin.gd) I've made for [Goost's GDScript transpiler](https://github.com/goostengine/goost/tree/gd3/modules/gdscript_transpiler).

See also people writing some sort of script compilers as seen in this bug report: godotengine/godot#45802.

**Comment by rainlizard** [comment]
Definitely looking forward to this being implemented officially, there's so much we can do if we have this.
Until then, here's a workaround for anyone who comes across this thread:
```
tool
extends EditorPlugin

var scriptEditor = get_editor_interface().get_script_editor()
var recursiveSearch

func _process(delta):
	var currentTextEditor = get_current_text_editor()
	print(currentTextEditor)

func get_current_text_editor():
	recursiveSearch = null
	recursive_get_editors(scriptEditor)
	return recursiveSearch

func recursive_get_editors(parent):
	for i in parent.get_children():
		if i.get_child_count():
			recursive_get_editors(i)
		if i is TextEdit and i.has_focus():
			recursiveSearch = i
```
We all know this is the hacky slow way of doing things and it might have a chance of eventually losing the reference if you only call it once. However I'm pretty sure it will always be successful as long as it's always called in the same block of code where you do things with it. It's usable, it takes 2ms on my CPU to perform.

With this, we can do anything in the [TextEdit class](https://docs.godotengine.org/en/stable/classes/class_textedit.html) (and [Control](https://docs.godotengine.org/en/stable/classes/class_control.html) too of course).
So, ``currentTextEditor.get_line()`` will return the current line of code as a string, ``currentTextEditor.insert_text_at_cursor(string)`` allows us to input code into the script editor, etc.

I had trouble figuring out how to get the line of code that's directly underneath the Mouse cursor (all TextEdit functions only relate to the Caret cursor not the Mouse cursor), the next best thing we can do is simulate a mouse left click which will move the caret cursor, then use ``get_line()`` afterwards:
```
func click_the_left_mouse_button():
	var evt = InputEventMouseButton.new()
	evt.button_index = BUTTON_LEFT
	evt.position = get_viewport().get_mouse_position()
	evt.pressed = true
	get_tree().input_event(evt)
	evt.pressed = false
	get_tree().input_event(evt)
```
I hope this is useful to someone.

**Comment by atursams** [comment]
Hi,
I came here looking for answers on another matter. Can someone elaborate on the use case and this functionality? Is this for adding IDE functionality in Godot's script editor?
