### ISSUE TITLE
Switch MarginContainer node name and properties to Padding rather than Margin

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot-proposals#2334]
### Describe the project you are working on
Not so much a project as something that I've been having to explain to a lot of people due to confusion with more modern UI framework naming conventions. If you check the Godot forums, and various Discord servers, there's a *ton* of confusion over why it's called MarginContainer, when the other containers also contain Margin properties.

### Describe the problem or limitation you are having in your project
Basically, MarginContainer does not truly represent Margins when you update its Custom Constants, but rather Padding, in more modern UI framework terminology. Some older frameworks refer to it as "inner margins" vs "outer margins", but padding vs margins (respectively) is far more common these days, and the container itself is meant to implement padding.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think renaming the node to PaddingContainer and changing the properties to Padding Left, Padding Right, etc., would make it a lot clearer that the values you set in Custom Constants set the distance on the inside of the control. Having talked with several beginners about this (I help answer questions all over Discord), they also think Padding would have helped them to understand why you'd want to use a MarginContainer (or, as per my proposal, PaddingContainer).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
This is just a rename of the control node and some of its properties. It would be good if we can utilize something that gives us backward compatibility, such as what's coming in Godot 4.0 with the big node name refactor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You'd have to make your own node scene and export new properties that map onto the old ones, I believe, and that would be copy/pasted among many, many projects.

### Is there a reason why this should be core and not an add-on in the asset library?
It's changing a core node, I'd expect it to remain there and not require people to setup an addon every single new project.

**Comment by pycbouh** [comment]
I guess it does make sense to better differentiate between inherited `Control`'s margin properties and `MarginContainer`'s own margin constant.
![image](https://user-images.githubusercontent.com/11782833/108827072-2fc7b380-75d6-11eb-8718-03894c1e916e.png)

We do need to be careful here with the terminology though, because the word `margin` is used for all types of margins throughout Godot. Like, another potential case for a similar rename is in StyleBoxes. Some of them have `content margin` and `expand margin`, both of which are actually internal and not external.
![image](https://user-images.githubusercontent.com/11782833/108827343-8cc36980-75d6-11eb-9da2-13ccf9c9ed1d.png)

"Content margin" is basically just padding, though "expand margin" is harder to name.

**Comment by WolfgangSenff** [comment]
Yes, agreed - and also that margin (for content margin) is the incorrect name. Virtually all modern UI frameworks refer to anything like that as padding. Even the actual box model itself refers to paddings this way: https://www.w3schools.com/css/css_boxmodel.asp

**Comment by Calinou** [comment]
Control's Margin properties were renamed to Offset in the `master` branch. Should we do the same with MarginContainer?

**Comment by pycbouh** [comment]
We should definitely **not** rename MarginContainer to OffsetContainer. Those are unrelated properties. I am still in favor of PaddingContainer, but current master is already disambiguated.

**Comment by aaronfranke** [comment]
The concept of this PR was rejected in https://github.com/godotengine/godot/pull/64667, so I'm closing this proposal. 

The problem of being ambiguous with Control node margins is resolved by the Control node properties being renamed to offset. The meaning of MarginContainer makes sense because it is a container that gives a margin to its children, even though it creates padding in itself. The primary concern of containers is what they do to their children - for example, VBoxContainer arranges its children into boxes stacked vertically. Margin is also a more friendly name that people think about outside the context of CSS.

If the rename is still desired in a decade or so, we could rename for Godot 5.0 in a decade or so. But I think it's good.

**Comment by Leonardo-Ma** [comment]
>The control `margin` properties were already renamed to `offset` in 4.0 for the same reason - to remove confusion between Control margins and MarginContainer.

_@fire-forge in https://github.com/godotengine/godot/issues/64667#issuecomment-1221407258_
            
The 'margin' property in Controls may have been renamed to offset, **but the actual proposed issue here, MarginContainer rename was not implemented nor refused in the PR mentioned.** (The refusal was due to offset rename). 
'content margins' references also remain 'margin' while it's also a padding.

I understand 'margin' is clearly more friendly, but it's impossible to not associate this to CSS or modern standards. But the same name having the exact opposite expected effect (margins are paddings in Godot) causes the same confusion that resulted in partially renaming to offset, that is also not friendly. 
This hardly should be the accepted reason for Godot to reinvent accessibility and common knowledge.

This specific issue may have not gained popularity, but 

- [Add margins and padding to Control nodes](https://github.com/godotengine/godot-proposals/issues/812) (32 thumbs up) 
[Closed in favor of [Redesign how user interface (Controls) scaling is presented to the user](https://github.com/godotengine/godot-proposals/issues/2841) that didn't implement it];

- [Replace MarginContainer with Padding properties for theme](https://github.com/godotengine/godot-proposals/issues/12068) (4 thumbs) 
[[As commented](https://github.com/godotengine/godot-proposals/issues/12068#issuecomment-2751746640), some variation of [Remove the anchors and margin workflow from Control nodes, and move the feature to containers](https://github.com/godotengine/godot-proposals/issues/4994) **that would require actual padding AND margin** could also fix this confusion].

Fixing the ambiguity could also potentially close:

- [StyleBox's expand_margin and content_margin should allow negative values](https://github.com/godotengine/godot-proposals/issues/2233) (26 thumbs) 
[That has many comments also mistaking lack of margins with Godot's padding called 'margins'. Whereas the renamed 'offset' can be negative even]

Though I do agree that in maybe 4 or more years, in Godot 5, Godot will reduce the amount of reinvented common knowledge and gain more space in professional areas.
