### ISSUE TITLE
method: get topmost node's name of an instanced scene no matter to the instance-node name

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2338]
### Describe the project you are working on
Reaction game
### Describe the problem or limitation you are having in your project
I cannot get the name of a node no matter to its instance name.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
You could get the name of a node without that is has to do something with the name in the current scene tree.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`get_<some>name()`
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it's GDScript.

**Comment by LightningAA** [comment]
I mean... you can get the filename like `my_node.filename`. If you want the name of root node of that scene, you could probably do something like `load(my_node.filename).instance().name`. What do you need to get the node's name for?

**Comment by MaaaxiKing** [comment]
I need it for saving the amount of a specific gem type you have. `load(my_node.filename).instance().name` works. Thanks! Nevertheless, I find that such a built-in method would be great.

**Comment by pycbouh** [comment]
I honestly do not understand what is proposed here. Can you explain in more detail what exactly is your limitation and what exactly is your proposed solution?

**Comment by MaaaxiKing** [comment]
You have a scene whose topmost node's name is "Bullet". A child of it is CPUParticles2D. You have another scene whose topmost node's name is "Ball". Everytime you shoot with a gun, a Bullet or a Ball is instanced and added as a child. Now, if you want to save how many bullets you shot, it's good if the key of this inside the saving dictionary is "total shot bullets" or so. You want the same with Balls, so how many Balls you shot ("total shot balls"). Now, Ball and Bullet have the same script. If a Ball is instanced, it's name is possibly @Ball@@12. But you want only "Ball" because the name of the topmost node of the non-instance scene is "Ball". Maybe a bad example, I'm sorry, it's a bit tricky to explain. Of course, you could just make a script and define class "projectile" and then make two scripts: ball and bullet and then write in ball `"total shot balls"` instead of `"total shot %ss"%load(my_node.filename).instance().name.to_lower()`.

**Comment by pycbouh** [comment]
In that case you should not rely on node names and should likely track those stats as you spawn your child scenes. Additionaly, if they do indeed share a script, you can add a `projectile_type` property which you'd assign a enum/const value to. This way you'd be able to figure out which type the scene is after the fact.

```gdscript
var ball_child = ball_scene.instance()
ball_child.projectile_type = ProjectileType.Ball

var bullet_child = bullet_scene.instance()
bullet_child.projectile_type = ProjectileType.Bullet
```

It can even be an exported property in your shared script and you'd be able to store its value with the scene instead of assigning it in code.

Relying on node names to determine some underlying "type" of a scene is a bad practice in general. As for the proposal, I think it is fair to close it since the example provided doesn't support the need for a way to track PackedScene's root node name within an instanced branch.
