### ISSUE TITLE
Add or document a way to pass images between C# and GDScript

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot-proposals#2345]
### Describe the project you are working on
I am making a game in which I want to load and save custom level data using a QR code. I am planning to use ZXing.Net for C# in order to generate images and extract data from QR codes.

### Describe the problem or limitation you are having in your project
[cf. this post in the Q&A forums](https://godotengine.org/qa/96196/using-zxing-net-to-read-or-create-qr-codes-in-a-godot-project)

I'm hitting a roadblock where VSCode is telling me that it can't recognize the `Bitmap` class.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Maybe there should be a way to convert Godot's Image resources into something that ZXing.Net for C# can read, and back.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
There could be another data type in Godot that can be converted from or into an Image or a Texture.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think that may be possible, since I suppose at most 2 other people are interested in using QR codes in Godot, but I'm not sure what that script would use.

### Is there a reason why this should be core and not an add-on in the asset library?
I don't know. Probably not, but if a method exists already, I would like to see it documented.

**Comment by pycbouh** [comment]
> Add or document a way to pass images between C# and GDScript

I assume what you mean here is "a way to convert a .Net `Bitmap` into an `Image` resource. While I am not intimately familiar with image formats and how they map to one another, `Image`s [can be created from byte arrays](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-create-from-data) in Godot. We also have a [bunch of `load_X_from_buffer` methods](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-bmp-from-buffer) for various image formats.

Quick Google search shows that something like this may work
```c#
Bitmap sourceImg = new Bitmap(width, height);
Godot.Image godotImg = new Godot.Image();

using (MemoryStream ms = new MemoryStream()){
   sourceImg.Save(ms, ImageFormat.Png);
   ms.Position = 0;
   godotImg.LoadPngFromBuffer(ms.ToArray());
}
```

However, you say that your problem lies before you even interact with Godot (`Bitmap` not being recognized), so this is out of scope of our project. If you still think that there is something that requires additional documentation, feel free to open an issue in [godotengine/godot-docs](https://github.com/godotengine/godot-docs).

If you just need help getting things to work with your project, please join one of our [community channels](https://godotengine.org/community). For example, we have a dedicated C# room on our Discord where people may be able to help you setting up VSCode and make that `Bitmap` be recognized.
