### ISSUE TITLE
Dragged sprites and scenes parented by default to the root node

### ISSUE THREAD

**Issue by luislodosm** [godotengine/godot-proposals#2381]
### Describe the project you are working on.
Teaching high school kids to develop with Godot.

### Describe the problem or constraint you have in your project
When kids drag a sprite from the file system into the main Godot viewer, it gets parented to the selected node in the scene tab, often producing **unwanted parentings**.

### Describe the function/improvement and how it helps to overcome the problem or constraint
Create an option to **always parent the dragged sprite to the root node of the scene**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups and/or diagrams
<img width="2672" alt="Captura de pantalla 2021-02-28 a las 17 56 44" src="https://user-images.githubusercontent.com/63356898/109428498-3d72a400-79ef-11eb-9cab-29ad256dd72a.png">

### If this enhancement will not be used often, can it be solved with a few lines of script?
I don't know.

### Is there any reason why this should be basic and not an add-on in the asset library?
I think it would be very useful and more secure.

Dragging sprites now has 2 steps: 
1 - Select the parent node
2 - Drag the sprite.

In the new way, this would be 1 or 2 steps:
1 - Drag the sprite from the file system to the viewer.
2 - Drag the sprite to the desired parent, if necessary.

This also applies to dragging packed scenes from the filesystem.

I hope this input will be useful. If it has already been discussed, I apologise.

**Comment by Calinou** [comment]
> Create an option to **always parent the dragged sprite to the root node of the scene**.

How would this be determined? I think the <kbd>Shift</kbd> modifier is already used.

**Comment by luislodosm** [comment]
Indeed.

- Drag and drop: add to selected node.
- Drag and drop + shift: add as a sibling node.
- Drag and drop + alt: change node type.

Does anyone use these modifiers?

There is no option to add to root node. It would be nice to have an option in the editor preferences to do this by default. I think it produces fewer errors.

**Comment by Zireael07** [comment]
I didn't even know alt did that, and I don't think anyone would miss it (change node type is easily accessible from the right click menu). Similarly, adding as sibling is as easy as dragging things around in the scene tree... 

I agree that a more sensible default would be to parent to root node. So root node for drag and drop w/o modifiers, and shift for adding to selected node?

**Comment by Calinou** [comment]
We can make it like this:

- Drag and drop: Add as child of root node.
- Drag and drop + <kbd>Shift</kbd>: Add as child of selected node.
- Drag and drop + <kbd>Ctrl</kbd> + <kbd>Shift</kbd>: Add as sibling of selected node.
- <kbd>Alt</kbd> with any of the above combinations: Ask to change type.

**Comment by golddotasksquestions** [comment]
To me the primary modifier key is Ctrl (⌘Command on Mac), then Shift, then Alt. Two modifier keys diminish usability by a lot, and three is like a guarantee this shortcut won't be used or remembered. If there are single modifier keys available, I would avoid using multiple modifier key combinations at all costs.

Therefore I would think it would make even more sense to lay it out like this:

-     Drag and drop: Add as child of root node.
-     Drag and drop + `Ctrl`: Add as child of selected node.
-     Drag and drop + `Shift`: Add as sibling of selected node.
-     `Alt` with any of the above combinations: Add at the respective place + Ask to change type.

Also, what I think would really help usability in this regard is to allow to directly drag a file to into the SceneTree:
https://github.com/godotengine/godot-proposals/issues/128
Before solving this by using any modifier keys, directly dragging it to the place in the scene tree where I want the node imho would be even a much more intuitive way to use drag and drop functionality. Having both options would really bring Godot a good step forward to faster, more intuitive usability.

**Comment by xix-xeaon** [comment]
@foxydevloper I saw your PR but I'll comment on the proposal instead.

It's tough, but I do think dropping in root by default is less bad than dropping in selected by default - since root doesn't change all the time. I think this should be changed both in 2D and 3D. I'm not against the modifiers but I don't think they're a great solution either. Again, selection changes all the time so keeping track of which modifier to use in relation to your selection makes it a more advanced workflow.

I had an idea though, what if you could mark nodes as "drop in"-able, just like marking a node as locked. Drop would now start at the selected node and search up the tree (including selected) for a "drop in"-able node (or root if none found) and add as a child of the first found. Both 2D and 3D should work the same. Most of the time you'll have some container node and it's to that node you want to add all the things you're dropping while designing a level or similar. If you "drop in"-able that container then if you have it selected, or one of the things in it (because you're moving them around etc), then your next addition will end up in the container where you want it.

The proposed modifiers could still also be implemented if desired.

**Comment by foxydevloper** [comment]
> It's tough, but I do think dropping in root by default is less bad than dropping in selected by default - since root doesn't change all the time. I think this should be changed both in 2D and 3D. I'm not against the modifiers but I don't think they're a great solution either. Again, selection changes all the time so keeping track of which modifier to use in relation to your selection makes it a more advanced workflow.

I've since made the change to 3D as well in my PR. As for the modifiers, you can change the node's location in the scene manually, but for users who remember them, modifiers can make adding nodes using drag and drop in the right location a lot easier. Selection changing all the time is a great reason why it should be added to the root node by default. Having modifiers result in the current selection being used is easier, since someone who doesn't know the modifiers exist in the first place may be confused as to how to avoid nodes getting nested every time they drag one in.

As for your idea, I think that's a confusing and complicated system that would take up space as an option in the editor, since it would only help in niche circumstances. If you have a container node that you store certain nodes inside of, then the ctrl key can be used.

**Comment by angstyloop** [comment]
https://gist.github.com/angstyloop/08200c6d816347c82ea1aed56c219f17
