### ISSUE TITLE
Let proposals be discussed for at least 1-2 days before implementing or closing them immediately

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#2462]
### Describe the project you are working on
Godot Engine.
This is the opposite of #154. 

### Describe the problem or limitation you are having in your project
We know that there are proposals which are *difficult* to implement, and proposals which are *trivial* to implement (literally within minutes). The former case may/usually involves a lot of discussion, both from the core developers and community. But some proposals (like involving usability), are oftentimes easy to implement so it's too tempting to make a PR for it in a matter of minutes/a few hours.

The problem is that this kind of approach may lead to premature decisions and implementations that might not represent the potential/real consensus within the community.

For instance, see #2460 which got implemented literally within 8 hours from the moment it was created, yet I don't see enough discussion around this proposal, and it seems like I'm the only one who expresses disagreement. Unfortunately, the proposal is closed so most people won't even notice the proposal for it to be properly discussed (unless someone stumbles upon the proposal via search engines).

At the same time, it's OK to open a PR for a proposal as stated in the rules.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Let new proposals be discussed before implementing them immediately. Let new proposals be opened for at least **2 days** before closing them, unless they clearly violate GIP rules or don't meet the scope of Godot as a project. This minimum time for discussion is ***needed*** to achieve good quality results, both for the proposal process and implementation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It's impossible to make a *collective* decision just within a few hours, so we should aim for at least 24-48 hours, at least for the sake of that people at the opposite side of the globe are still sleeping. We should aim for *community-driven* development. Core developers can make any decision at the end of the day, but a discussion must happen, unless nobody cares about a proposal or are neutral about it.

Again, time will tell. 🙂

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This is meta proposal: #1669.

### Is there a reason why this should be core and not an add-on in the asset library?
This is meta proposal: #1669.

**Comment by pycbouh** [comment]
> For instance, see #2460 which got implemented literally within 8 hours from the moment it was created, yet I don't see enough discussion around this proposal, and it seems like I'm the only one who expresses disagreement.

You were expressing disagreement with something that wasn't a part of the proposal. You were expressing disagreement with the previous decision, which was the cause for this proposal to happen. And this "proposal" was a small UX enhancement, so there was no point discussing it at all. It wouldn't even demand a discussion if it was a direct PR instead.

We don't usually close proposals even if they are too vague, too unrealistic or fail to comply with the spirit of the rules and the questions of the template. We only immediately close proposals that are dupes or have failed to fill out the template completely (and in that case they are closed temporarily, if the author decides to correct it). Other than that, proposals are never closed in a hurry. So the problem that you are trying to solve here doesn't exist.

**Comment by KoBeWi** [comment]
btw if you are unhappy with #2460 you can open a counter-proposal.

**Comment by LikeLakers2** [comment]
@pycbouh I think you're misunderstanding what Xrayez is asking. Because of how #2460 was handled (being implemented within hours of being opened), he's concerned that other proposals may get implemented/closed before users have a chance to discuss them. Thus, Xrayez is proposing a timeframe of at least 2 days before any decision is made (even if a proposal is as small or insignificant as #2460 and thus might not warrent discussion) so there can be a fair chance for some disagreement to be made *before* it's implemented.

**Comment by Xrayez** [comment]
> So the problem that you are trying to solve here doesn't exist.

@pycbouh saying that there's no problem means that you don't want to understand the problem. In order to understand the problem, you'll need to convert the above statement to a question.

Some people can interpret this as an insult. I know I personally have a problem with this, otherwise I wouldn't bring this up, don't you think? 😛 

At the very least, I'd like to see *at least some rationale* behind any change. The "Move to Trash" name applied to *all platforms*, and now we have *per-platform* change, it's not just a "small UX enhancement" anymore, as this sort of consistency is not always applicable for each platform, and these kind of changes require some feedback from users.

LikeLakers2 summed it up nicely!

> btw if you are unhappy with #2460 you can open a counter-proposal.

Thanks, done! #2463 🙂

Also, lets keep the discussion closer to topic now. #2460 is just an example. I think what I propose here makes perfect sense, regardless of whether you think the problem exists or not (at the very least, this kind of approach will minimize the amount of frustration of people proposing and discussing changes for Godot development).

This "proposal" is not actionable either, it's just an open-ended discussion and a call for action regarding GIP workflow, and I hope people who read this will be inspired to make reasonable decisions (I'm not saying that they're unreasonable, but oftentimes I feel like there's a lack of understanding, and little attempt to reach common ground, and some degree of inattentiveness).

**Comment by Zireael07** [comment]
In general, I agree that acting on a proposal too quickly might prevent properly discussing them. 2 days seems like a good length of time to allow contributors (from all over the world) to chip in.

**Comment by pycbouh** [comment]
> I think you're misunderstanding what Xrayez is asking

@LikeLakers2 Then you've misunderstood my answer. What I'm saying is that what Xrayez proposes here is already what we do in practice, and always have been. We already let proposals be open for days and weeks before acting on them or considering their implementation for merge. There is no hard limit in writing, like Xrayez wants, but we do this already.

This issue was created solely because of #2460, which was a small UI/UX enhancement on top of another, earlier change (https://github.com/godotengine/godot/pull/41263). Contributors considered this as such and the fix was easy, so it was quickly implemented. As I've said, if it was a direct PR and not an issue in this repository, nobody would've batted the eye. Xrayez was against the earlier change (from "Delete" to "Move to"), so he wanted to take this opportunity to argue his case once more. Well, as mentioned before, if he wants to see that earlier change reverted, he needs to open his own proposal specifically for that, which he did with #2463. 👍 But being sore that you couldn't piggyback off of another, related proposal, is not a good reason for this meta issue.

So, to reiterate. When I say that there is no issue, I say it because 1) We already do keep valid proposals open for at least a few days/weeks, and 2) The issue that provoked Xrayez to open this is not indicative of us breaking that practice. And even if we were to reinforce this existing practice with a wording in readme or something, it wouldn't be an improvement, IMO. As always, we go off of our better judgement, so that we can consider such intricacies on the case by case basis. And having a strict rule like that would prohibit us from handling small issues which were reported here instead of somewhere else in a timely manner.

**Comment by Xrayez** [comment]
> Contributors considered this as such and the fix was easy, so it was quickly implemented. As I've said, if it was a direct PR and not an issue in this repository, nobody would've batted the eye. Xrayez was against the earlier change (from "Delete" to "Move to"), so he wanted to take this opportunity to argue his case once more.

I was actually silent about the initial change (under impression that my suggestion will be rejected in any case), but I took the courage and I decided to take opportunity to discuss the change in the recent proposal at least. The problem is that people somehow assume that there's an absolute consensus if something was merged before. In fact, I might not be even aware of previous decisions. That's why I ask core developers to at least provide some feedback and guidance if situations like #2460 do occur. And godotengine/godot#41263 didn't receive much 👍s anyways at the moment of writing, so wouldn't say we've got consensus there either:

![image](https://user-images.githubusercontent.com/17108460/111138948-361fce80-8589-11eb-960b-7164e4b3c678.png)

Again, the problem is that users may also be silent about those changes, due to similar reasons, and here you go...

> But being sore that you couldn't piggyback off of another, related proposal, is not a good reason for this meta issue.

I could as well propose improvements to the workflow without a real-life use case. It's just something which makes sense. I don't believe that #2460 to be the *only* case.

> And even if we were to reinforce this existing practice with a wording in readme or something, it wouldn't be an improvement, IMO.

Again, I'm not suggesting to do anything. This is just about being a little bit more conscious. But in theory, this could be put somewhere in **How core developers evaluate proposals** section in the README. 😛

In fact, I'd blame @akien-mga for this, but I don't want to blame anyone... Just keep those PRs opened for at least 24 hours before considering merging, unless a change is clearly obvious, of course.

**Comment by akien-mga** [comment]
So you want me to needlessly wait 48 hours before merging a PR that does `s/Trash/Recycle Bin/`? With 15 PRs per day, I *have* to merge things fast when they're consensual, I don't see why anyone would have rejected a `s/Trash/Recycle Bin/` change when the name of the trash on Windows is "Recycle Bin".

We can always revert changes which are not considered good after the fact, but there's no reason to introduce an artificial delay for such tiny cosmetic changes.

For bigger changes, we already wait a lot more than 48 hours to get proper code review, discussion on the feature, etc.
I don't see a need to add some extra bureaucracy here.

**Comment by pycbouh** [comment]
> The problem is that people somehow assume that there's an absolute consensus if something was merged before.

Well, no, it's still an authoritarian decision by Akien and advisors as to merge something or not. It doesn't need an *absolute* consensus, and doesn't imply it.

> That's why I ask core developers to at least provide some feedback and guidance if situations like #2460 do occur.

I still don't get why you see a quick resolution of #2460 as some drastic event. It was a sensible enhancement of an already approved and merged PR. Does this type of OS-specific terminology have a lot of precedence in our code base? Probably not. We still have `Show in File Manager` instead of `File Explorer`/`Finder`. But it makes sense to use it, and gotta start somewhere.

**Comment by Xrayez** [comment]
> With 15 PRs per day, I _have to_ merge things fast when they're consensual, otherwise they risk ending up in limbo and not being merged for 12 months, instead of 48 hours...

I don't quite see a problem here. It's just a delay. You can merge PRs as effectively as before, the merge process just happens to be on the next day rather than immediately. Unless we have a clear code owner, or something which most users won't care about. But editor stuff affects a lot more than just an internal change (which is fine to merge immediately in contrast).

> I don't see why anyone would have rejected a `s/Trash/Recycle Bin/` change when the name of the trash on Windows is "Recycle Bin", so I merged it.

> I still don't get why you see a quick resolution of #2460 as some drastic event.

I don't understand why you don't understand why I think that godotengine/godot#47004 is not obvious, I've already told you why.

I mean, it's obvious on the surface level I guess, but it seems like nobody cared from the core developers whether the new name matches the one on Windows.

> Well, no, it's still an authoritarian decision by Akien and advisors as to merge something or not. It doesn't need an _absolute_ consensus, and doesn't imply it.

I simply didn't get the opportunity to influence that decision, it seems.

Ok, now it's clear.

**Comment by akien-mga** [comment]
> You can merge PRs as effectively as before, the merge process just happens to be on the next day rather than immediately. Unless we have a clear code owner, or something which most users won't care about. But editor stuff affects a lot more than just an internal change (which is fine to merge immediately in contrast).

Well the "Unless" sentence here invalidates this proposal. It doesn't make sense to add a formal 48 hours delay to merge anything but then not respect it based on judgement calls. Merging the fix for #2460 was a judgement call on something that *I* considered simple enough and not warranting discussion.

> I don't understand why you don't understand why I think that godotengine/godot#47004 is not obvious, I've already told you why.

But that's the point @pycbouh raised above. This PR has been merged ages ago and is not the topipc of #2460. Resolving #2460 does not necessarily imply reverting godotengine/godot#47004 - they're related but different issues (and godotengine/godot#47004 should likely have gone through the proposal process, which would have likely taken more than 48 hours to be considered consensual).

> I simply didn't get the opportunity to influence that decision, it seems, because I did not receive any feedback for my concerns before the PR got merged, that's all.

Well I'll admit that I was on my phone when I merged the PR which seemed straightforward to me, and did not check the proposal itself. If I had, I would have seen your comments and likely waited for further discussion. In this case I'd suggest you can put a comment on the implementation PR to relay the fact that the proposal being implemented may not be consensual (or in this case, that you'd prefer the earlier godotengine/godot#47004 to be reconsidered instead of being iterated upon).

**Comment by akien-mga** [comment]
All that being said, if we want to document some kind of minimal discussion time for proposals, I don't really mind. But it hardly ever happens that a proposal is implemented and merged within less than 48 hours anyway unless it's a simple string change, so I don't think it will matter much, and I see this here proposal mostly as a reaction to #2463, not a general workflow issue that needs to be addressed.

**Comment by Xrayez** [comment]
This is what I'm asking for, 48 or at least 24 hours is enough.

And don't tempt me go into the process of making an elaborate research on this topic in GIP, I surely find a bunch of cases which this proposal covers, because it's not what I aim for.

**Comment by mrjustaguy** [comment]
I really don't see a point to 1-2 days of proposal discussion minimum.

1. Most proposals are open for days anyway
2. Under a Day proposals are 90% of the time tiny cosmetic tweaks, that don't take a ton of effort and people will complain if they don't like it, or if there's something wrong, which will lead to a discussion
3. If it is agreed that a PR doesn't actually make sense in said discussion, it can easily be reverted

All It'd do was add complexity to adding simple tweaks & additions that can be filtered out by the person approving the merger, based on common sense. I mean imagine how many #2205 style minor additions that everyone could benefit from might be out there that no contributor has noticed lacking that could be implemented within an hour even?

All in all, don't think there's a point in even attempting adding a rule for a 1-2 day proposal time minimum for implementation, as in the end it'd affect maybe 1-2 proposals a ~~week~~ month, and that's being optimistic about the number of such proposals.

**Comment by Xrayez** [comment]
I think the real issue for me was that:
1. A proposal was opened (#2460) for an enhancement of the existing feature. It doesn't matter if it's small or big, it's a fact. The user has no option but to make a formal proposal for not-a-bug issues:
   
   ![image](https://user-images.githubusercontent.com/17108460/111482935-06b1c300-873d-11eb-8dcf-b87b8608cc28.png)

2. A PR was created immediately to solve the proposal.
3. **Discussion happened directly in the pull request rather than proposal**.
4. The PR was merged **without taking into account other opinions at GIP**.

GIP says that general implementation should be discussed in GIP first, not pull requests (see rule 5 at README):

> 5. You can make a PR implementing the feature in the main repository before making a proposal. However, if it is a large change, a core developer may require that you make a proposal before your PR can be merged. **It is always better to make and discuss a proposal before spending your time implementing a new feature.** [emphasis mine]

(**large change** *is also a change which would impact most users, not necessarily the amount of additions and deletions in the PR)*

So, I'd say that perhaps the real issue is exactly the poor organization between the proposal and PR workflow. I decided *not* to comment in the PR because there was already a proposal for it. The issue is that it's difficult to tell where should I discuss things. GIP was created specifically for that, discussing and agreeing upon implementation before making a PR.

So, extending the time it takes to discuss proposals would certainly help to reach consensus in general, because it increases the chances of someone looking at the proposal, reading it, internalizing it, and making suggestions, simple as that. 🙂

Now, again, I don't ask to introduce some formal time frame, I'm just asking to pay more attention to both PRs *and* GIP proposals (before merging anything, at least). That's why I said that this meta "proposal" is *not* actionable. Feel free to close this if you simply agree with this approach. 😛

**Comment by Xrayez** [comment]
However, if you do like to formalize it, adding something like this to the rules may be enough:

> Don't submit a pull request immediately after a proposal was created. Let people discuss and agree upon a change directly in GIP for at least 12-24 hours to achieve consensus among developers worldwide.

Note that you *can* work on something immediately, but creating a PR right after a proposal divides the discussion between GIP and the main repository (that's also an issue I've seen with PR discussions).

**Comment by Jummit** [comment]
Note: The proposal that started this discussion had no reactions, and the first comment was against the change. I don't think time was the issue, the proposal shouldn't have been implemented even if it were older than 2 days.

I think Calinou was a little too eager to implement it, as it's a pretty simple PR 😉. That's just an assumption though.

**Comment by mrjustaguy** [comment]
#2460 is not by ANY means a large change, and even by your definition, most people probably wouldn't even notice such a thing.

**Comment by Xrayez** [comment]
> #2460 is not by ANY means a large change, and even by your definition, most people probably wouldn't even notice such a thing.

When "Delete" was first renamed to "Move to Trash", I noticed it immediately and wasn't happy with that change. But as I said before, I simply accepted this fact 3 months ago. So, I suspect that people simply choose not to provide feedback for things like this, but again those people would likely prefer to retain the original name (on Windows).

There's already some support for #2463.

**Comment by mrjustaguy** [comment]
That argument is like saying something like: 

1)"GDScript was renamed to GodotScript (or what not), I noticed it, and wasn't happy because scripting is an inherent part of project development, so I suspect that people simply choose not to provide feedback for things like this, but they'd still prefer the original name"

or

2)"Icon1.png was changed to Icon2.png, I noticed it, and wasn't happy because I have to see Icon2.png every time I start the engine, but people would likely prefer to retain original icon"

In both cases it would be very likely reverted even if the new one is actually better, because of familiarity bias which would cause a sizable portion to choose the one they're used to.. How does this relate to Move to Trash vs Delete? MtT is clearer on what it's doing, Delete isn't, yet people prefer Delete because it's what has been there for quite a while.

Note: This is kind of getting out of hand, as the Delete/Move to Trash is the only thing being discussed at this point.

**Comment by Xrayez** [comment]
Your substitution examples pertain to Godot itself. Renaming GDScript to GodotScript would not really change the meaning, nor "Icon1.png" "Icon2.png" etc. We are talking about cross-usability on the level of OS and software here.

> Note: This is kind of getting out of hand, as the Delete/Move to Trash is the only thing being discussed at this point.

Yeah, I think I better close this, Akien and others are already aware of this and I respect that the issue is recognized on some level at least, I hope this had some influence on decision making. 🙂

Lets move the discussion to #2463, if you like.

Cheers!
