### ISSUE TITLE
Regarding the governance model and community-driven development

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#2531]
## Problem

We know that Godot development is based on the community effort of people which contribute bug fixes, documentation changes, improving existing and developing new features etc. We also know that Godot is an open-source project with participants from all around the globe.

Given above, we naturally have several major questions pertaining to development government:
1. How people agree upon a change?
2. Who makes the final decision about any change?
3. Who can influence the decision making?

I think you'll agree that we have a variety of projects with largely different government models out there. Some open source project just provide the source code to be available to everyone, some go a bit further and allow interested people to influence the decision making directly (in any form), or allow to modify the project in a community-driven way via consensus alone, like Wikipedia.

The question is: what is the government model in Godot? The documentation states that it's community-driven, but we can see a bunch of instances where people express resentment regarding the development process in Godot (even within the Godot's member community), see issues like godotengine/godot#47498 or #486.

We know that Godot's development philosophy is based on purely solving problems which stem from the need of the community. But again, what's the actual community in relation to Godot, and what part of community has a major influence regarding the direction of the project.

I'm raising this question because I think that we do have a problem which needs to be resolved on some level.

### Decision making

Here's Wikipedia's definition of "community-driven development":

> Community-driven development (CDD) is a development initiative that provides control of the development process, resources and decision making authority directly to groups in the community.

In relation to Godot, we can translate this as "Godot gives control to groups in the community called maintainers". As you know, maintainers are the ones responsible for making the final decision when it comes to merging anything. But to become a maintainer, you have to earn it in some way, possibly by improving the existing functionality, or even creating new functionality. This is where so called meritocracy comes into action.

But lets look at opened pull requests in the main repository (those that don't actually require making a formal proposal beforehand) and GIP proposals. Godot has over 1k opened pull requests and over 1.5k proposals, and I think that each individual who make those think that their changes are important, and a lot of contributors would definitely be willing discussing and making further changes if necessary.

The lack of desire is evident by looking at people who choose to close their own pull requests and proposals just because they didn't receive any feedback for their proposed changes, like godotengine/godot#43947.

So, I don't quite see how someone can even acquire those decision making superpowers if their changes are not even looked at. The way I see it, if there are no maintainers who are willing to review those changes, then the decision making should actually shift towards people who currently actively work on the engine, and not because someone worked on something years ago.

This tells me that Godot is not fully community-driven since active maintainers are not willing to review those changes, even if they solve the community needs. Note that whether those changes should be solved by the engine or third-parties is not relevant in this discussion, see #575 for that.

## Solution

Lets not fixate on the proper definition of what is seen as "community-driven development" as seen in dictionaries. Most people assume community-driven means exactly that: a development *controlled* by the community. I think that's the major source of conflicts and misunderstanding, especially when we take into account that a lot of contributors don't possess fluent English skills.

So, I think it may be enough to present Godot's governance model more realistically to users and especially new contributors.

- Clarify that Godot is community-*based*, or community-*maintained* project, but not necessarily community-*driven*.
- Provide frequent pull request and proposal *meetings* openly available to people of interest. I don't see any public meetings currently.
- Start delegating the decision making to people interested in improving a particular part of the engine in the way Godot community sees it (again, governed by solving real-world problems most people stumble upon using the engine).

But again, after thinking about this a bit more, I think the major problem is not the actual governance model used by Godot nor the problem of changing it, but making the existing model crystal clear to users and contributors, because based on my own observations, Godot attracts a lot of inexperienced people who might not even been contributing to other open-source projects before.

**Comment by pycbouh** [comment]
Saying "Lets not fixate on the proper definition" and then making your preferred definition something that "most people assume" is in bad faith. Please, don't do that.

> The lack of desire is evident

> active maintainers are not willing to review those changes

I think this is disengenious and even offensive towards people who work on Godot. The implication that the PRs are stagnating simply because maintainers are lazy or not interested is awful. In an open source project that has seen any amount of success there is always going to be way more ideas (proposals), issues and PRs than any number of contributors would be able to handle. Even paid contributors have very specific tasks that they need to handle before making an effort to clean up the backlog. It will come to that.

> Clarify that Godot is community-based, or community-maintained project, but not necessarily community-driven.

Community doesn't maintain Godot, maintainers do. Community does drive the decision making process, but it doesn't rule it. Misinterpretation of the definition is the core of the problem here, when you put it like that. Definition of Godot as "community-driven" doesn't put community in charge. It puts community interests in front, but it doesn't mean that there is democracy or design-by-committee process. In fact, I am strictly against it and in favor of opinionated decision making process with few decision makers.

> Provide frequent pull request and proposal meetings openly available to people of interest. I don't see any public meetings currently.

That's a fair thought and a practice that existed before. I think the aim is to restore it after 4.0, when big refactorings will end and more of an evolution will begin.

> Start delegating the decision making to people interested in improving a particular part of the engine in the way Godot community sees it (again, governed by solving real-world problems most people stumble upon using the engine).

That is unrealistic. If there is no consensus or trust between maintainers then there is no future. And trust is the core factor at appointing core maintainers and code owners. So if there is trust between the core team and a contributor, they can be made a code owner of a particular part of Godot already. If there is no trust, it doesn't matter if the area is lacking a maintainer. Nobody would put a part of the codebase into the hands of someone they don't trust.

**Comment by reduz** [comment]
My opinion on it.

> Clarify that Godot is community-based, or community-maintained project, but not necessarily community-driven.

1) Definition does not matter, our processes are already open and anyone can see them, and anyone can ask.
2) I only see that we should clarify approval process (who has final say).

> Provide frequent pull request and proposal meetings openly available to people of interest. I don't see any public meetings currently.

Its the plan to eventually do more, but not all proposals or pull requests will be reviewed. The main problem is, when we did PR meetings, most of the time feature PRs are things we as contributors have no idea whether community needs or not, specially because they are just things that come out of the blue that no one else asked about. This is why we created the proposal system, so before opening PRs users would need to file a proposal and we could gauge if there was any kind of community interest on this. Still, feature PRs out of the blue are allowed as part of a proposal and this results on them also remaining around forever because despite technical merit, if there is no interest no one will review it because we still dont know whether its useful/wanted. My view here is that we should just either disallow them altogether, or agree that they will sit there forever without a review just like an ignored proposal. I also think proposals should be closed automatically after a while if there is no interest but then again, this is something other contributors should agree to.

> Start delegating the decision making to people interested in improving a particular part of the engine in the way Godot community sees it (again, governed by solving real-world problems most people stumble upon using the engine).

**Comment by clayjohn** [comment]
> 2. Provide frequent pull request and proposal meetings openly available to people of interest. I don't see any public meetings currently.

> 3. Start delegating the decision making to people interested in improving a particular part of the engine in the way Godot community sees it (again, governed by solving real-world problems most people stumble upon using the engine).

This is actually very similar to our end goal with the concept of "teams" and "team ownership" You'll notice on PRs a given "team" will be assigned to review. The long term plan is to allow interested contributors to get pinged when a PR needs a given team's review so they can contribute to the process. See the CODEOWNERS file on the main repo https://github.com/godotengine/godot/blob/master/.github/CODEOWNERS.  

We are slowly building the infrastructure to get more interested contributors with less experience involved in the PR review process. Another piece of this was moving to rocketchat which has a chat room dedicated to each team. 

For example, if someone wants to get involved with the rendering team, they can follow the rendering team and (hopefully) receive notifications when the rendering team is pinged on an issue or PR. They can then participate in discussion on the issue/PR or on rocketchat and contribute to the bugfix/implementation/review. 

This allows more contributors to take a larger part in the development process and frees up maintainer's time so they can hopefully review and approve more PRs. In a perfect world, interested contributors would discuss and review PRs and the maintainer would just need to be involved to merge the PR once consensus is reached by the interested contributors. 

Of course, when merging PRs, someone has to actually press the button and merge/close the PR. This authority will always have to remain in the hands of a trusted maintainer. But the rest of the process can be and should be shared.

**Comment by Xrayez** [comment]
> I think this is disengenious and even offensive towards people who work on Godot. The implication that the PRs are stagnating simply because maintainers are lazy or not interested is awful.

Sorry, I didn't mean to imply that Godot maintainers are lazy. I wanted to say that we possibly have a problem of prioritization and organization within the community.

> Community doesn't maintain Godot, maintainers do.

Aren't maintainers part of community? 🤔

Also, it's not always the case that maintainers are the ones who do most of the work. Yes, they're able to review and press that merge button, but it's totally possible that most of the maintainance work is still done by the rest of the community that do not have decision making powers. reduz will also agree that he delegates bug fixes and smaller enhancements to the rest of community, because he cannot allow himself to focus on improving only one thing to perfection as it would take him months of work (I can quote on that if required). It's likely the reason why Godot got open-sourced, so that the rest of the community can pick up the work. The only difference is that only bug fixes are generally accepted, but not new features, obviously.

That's what I mean by Godot being community-maintained rather than community-driven: bug fixes for the "lower class", feature development for the "upper class", so to speak. 😛

> > Start delegating the decision making to people interested in improving a particular part of the engine in the way Godot community sees it (again, governed by solving real-world problems most people stumble upon using the engine).
> 
> That is unrealistic. If there is no consensus or trust between maintainers then there is no future. And trust is the core factor at appointing core maintainers and code owners. So if there is trust between the core team and a contributor, they can be made a code owner of a particular part of Godot already. If there is no trust, it doesn't matter if the area is lacking a maintainer. Nobody would put a part of the codebase into the hands of someone they don't trust.

> Decision making is already fully delegated to maintainers and core contributors, but we can't go beyond that because this is something entirely based on trust. We will never delegate to someone who we don't fully trust, that doesn't have a proven track record, that has not proven to be technically capable, or that did not have an flawless attitude towards the project at all times.

I think we already have some competent contributors in particular areas, perhaps we simply have a trust issue here (some of them are already on par with those contributors who are currently hired), but hopefully it's just a matter of time once this delegation happens.

---

Again, if you read the OP carefully, I'm not even proposing to change anything in relation to the governance model. I fully understand the concerns raised above and do not attempt to play on the opposite side. I simply ask to act in accordance to what documentation says, and the simplest solution to this is to amend the documentation to clarify this.

Feel free to close this once this is done.

**Comment by hilfazer** [comment]
Given the definition of Data Driven Programming i can understand why the community may think they're in charge.
[From "The Art of Unix Programming"](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch09s01.html):

> One is that in data-driven programming, the data is not merely the state of some object, but actually **defines the control flow** of the program

[From an answer on Stack Overflow](https://stackoverflow.com/questions/1065584/what-is-data-driven-programming):

> Data driven progamming is a programming model where the data itself **controls** the flow of the program and not the program logic

But let's have a look at [Profile-Guided Optimization](https://en.wikipedia.org/wiki/Profile-guided_optimization):

> Profile-guided optimization (PGO, sometimes pronounced as pogo[1]), also known as profile-directed feedback (PDF),[2] and feedback-directed optimization (FDO)[3] is a compiler optimization technique in computer programming that uses profiling to improve program runtime performance. 

So the profiler isn't making decisions, compiler does based on the feedback it got from the profiler.

So perhaps _community-guided_ would be better?

**Comment by Xananax** [comment]
As someone who has no stake in this conversation, or in the development of Godot, and is a bit external to all of this, I can allow myself to be blunt. So I will.

This premise (and the resulting conversation) is absurd and a waste of everybody's time (I am not, here, referring to Pybouh, Reduz's, and Clayjohn answers, but the repeated controversy that I've seen on Discord, Twitter, and Rocketchat).

I'm infuriated by the lack of logic of it all, it breaks my brain. This makes no sense because of two reasons:

1. The reasoning for defining the term is flawed
2. The goal of a completely "community drvien" project is lofty and childish

I'll expand on those two points below.

-----

There is often, in emotional debates, an attempt by the hurt people to try to redefine terms in an effort to make the debate seem rational. This shifts the discussion to semantic analysis (while always pretending it's not about semantics, yet always pulling the debate there again).

This is always pointless, because words are defined by usage, not etymology: If I insisted that you cannot call an elected official "representative" because "aha! but they don't represent _everyone_, do they?" or that you can't call a box "empty" because "aha! it contains air though!", I wouldn't be accomplishing anything.

The way Godot uses "community driven" _is_ how the term is used. Wikipedia definition notwithstanding (that Xrayez quoted correctly: "decision making authority directly to groups in the community"), countless projects use the term, and none of those projects are more "community driven" than Godot is. In truth, Godot is one of the most community driven projects I've ever seen. 

-----

<details>
<summary>(Open for more thoughts on other projects)</summary>
I'd be interested to see an example of a project that is more "community driven" than Godot (with a similar scope). In 20 years of involvement with open source and all sorts of community driven projects, digital and IRL, I've never seen it. Maybe it exists; if it does, I bet it'd be an outlier, and would probably be found in a specific circumstance that allows this to happen. 


The Wikipedia example is not a good example, because Wikipedia has a set of superadmins who overview the contributions of everyone else. It's also not software, doesn't require long term strategy or runtime efficiency, the cost of additions isn't exponential, and it's all around not comparable in any sort of way with Godot; but it's telling this is the example of "extreme openness" that was found. 
</details>

-------

In short, either:

- You want to redefine the term "community driven" for _the whole world_, and it's unrelated to Godot. Go make a blog about it. Create a petition for this term to be removed from language. 
- Or
- You say that Godot is community driven, just like every other Community Driven project.

It can't be both.

---------

Second point: 

A project's guidance requires more than "adding features". It requires to have long term vision, plans for how things will be maintained, and crucially, _decide what to leave out_. A feature is **never** only a feature. It's **always** a trade off. When taking something in, you leave something out. It's important that someone who understands the trade off makes the decision.

This might be a less deeply understood reality for people who haven't managed long-term projects, which might be some source of confusion. To be clear: software engineering experience doesn't mean you can make those decisions. They require people with experience in _managing software development_, which is a different set of skills altogether.

People who have somewhat contributed don't have the knowledge necessary to take such decisions (They might have the capacity to participate meaningfully by providing their point of view, which they're invited to do).

-----

<details>
<summary>(Open for examples of things maintainers can do that passerbys can't)</summary>

The project's maintainers can see:
- the complexity cost (which is, let's make a point here, exponential)
- the maintenance cost (also exponential)

They can ask:
- Who will maintain this? Can we trust this person to always maintain it?
- How much of a Bus Factor is it? Can another maintainer understand it?
- Does it fit with other features that we have in the pipeline? Would it prevent a future feature? What's the opportunity cost of putting this in?
- Do we have someone we trust, that has the time and knowledge necessary to audit this piece of code?
- ... and so many other questions that someone who's not doing this day in day out _cannot ask_, and _shouldn't ask_.
</details>

-----

Of course there are sometimes false negatives, with certain PRs rejected even though they shouldn't have. No governance is perfect. But what is certain is that there needs to be a vetting process for features anyway, and this vetting needs to be done by people who have been in the project for long, and will remain with the project for long.

----

<details>
<summary>(Open for a note about voting)</summary>
Voting for features is way worse, as it opens this thoughtful and strategic process to large groups, which will not put in the necessary time to understand trade offs. Groups are also very easily swayed by hype or visuals.  
Additionally, we have no way to guarantee the people that vote most are the people who use the engine most. At large amount of users just dip in and out of Godot, have never completed even a gamejam with the engine, will probably go on to use something else, have no real interest and investment in the engine... but will have _extremely strong opinions_ on what the engine should do.
</details>

----

Projects cannot happen in a completely "community driven" way simply because they'd implode on themselves in a matter of weeks. It has been tried by kids everywhere, and even by some medium sized projects (that died).

In short:

The type of community driven that's advocated _doesn't work_. It is not realistic, and cannot be done (at least, for most projects). 

--------

If the idea is that newcomers are confused, then let them be! Just like people come to understand "representative" doesn't mean the person represents everyone, they'll come to understand "community driven" means 

> for the benefit and with the participation of the community

and not

> a sad confused chaos where everyone puts in everything until the project becomes a black hole of nothingness that no one can use

And if people insist on the latter definition, and feel resentment, it's simple enough to tell them to go play somewhere else. Fork the engine and build your own leadership process, no one will stop you. Test this completely community driven idea, show us how it works. I'd be delighted to see how this could work.

If anyone's actually interested by doing that, there is a ton of thesis, PHDs, and literature on how it could work in theory. Yes, because it's a hard, unsolved problem as of yet. Make sure to do your homework by finding and reading those before trying 
(honest offer: I can help a bit with that, it's one of my fields of interest).

-----

<details>
<summary>(open for a last note on why I think this is happening)</summary>

With all of this in mind, I personally think Godot should thrive to be _less_ community driven. In other open source projects, which also bear the "community driven" moniker, but give less leeway to people, ridiculous situations such as this one don't happen nearly as often.

It seems to me like the openness of Godot drives entitlement up and leads to weird expectations. It is my wish that Godot has _less_ community drive. Which would still, just to be clear, make it one of the most community driven projects out there, but wouldn't have the maintainers waste precious time in meaningless squabbles such as this one.
</details>

**Comment by mrjustaguy** [comment]
Maintainers are a Part of the community, they're just the part of the community that has proven themselves worthy of the control (and if the funds allow for it) a pay check.. 

This makes total sense, you want to have a Wall between unending random contributors and a Project or else the Project would totally go out of control, and as such wouldn't be able to cater to the majority because of waaaay too much poorly maintained bloat.

It is the job of the Maintainers to figure out what the community at large wants, and to implement it as best as they can (or assist other contributors with implementing it, or just giving a green light to a contribution that passed a Quality standard)

A Community-Driven project without some sort of a filter (The Maintainers in this case) would be like having a ton of totally random people pushing the project in random directions, instead of a coordinated push in one general direction. You can easily determine which will go further.


As far as the Wikipedia definition goes, it fits with what Godot is, I don't see a problem.
1. Community controls the Development Process, we have a say on what we want and don't want, the discussions for such things are open to all. If the Community wants better 3D rendering, Work is done on getting it better 3D rendering.
2. Community is funding Godot, and is as such in Control of the resources
3. Proposals are opened, Decision is based on how doable it is, and how desired/undesired it is, so the Community is making the calls, and the Core Devs ARE a part of the community, with a bit more weight in the decision making process, as they can better estimate how doable something is, and constantly get feedback from the smaller fish in the Community, thus being able to use that feedback to point the project in a given direction.

**Comment by Xananax** [comment]
It should thrive in acts. 

For example, closing this issue without answering and wasting precious contributor time.

The moniker "community driven" is beyond discussion and it would be wrong to change it.

**Comment by Xrayez** [comment]
@Xananax thanks for your opinion, but I think that you're wrong.

> The moniker "community driven" is beyond discussion and it would be wrong to change it.

Changing the "moniker" of "community-driven", or editing it is allowed by someone who governs the Godot project. It won't be a wrong thing to do if that's something which the lead developer wants, even from the contributor's initiative.

In fact, @reduz asked me to express my opinion regarding this topic, so I did. This information wasn't targeted for non-contributors.

**Comment by Xananax** [comment]
> This information wasn't targeted for non-contributors.

Ah I see, sorry. I didn't realize the community's take was not wanted on that particular topic

**Comment by pycbouh** [comment]
@Xrayez You've opened a public proposal, so please don't dismiss public opinions shared on it. You could've posted on RC if you wanted to keep it more private.

**Comment by Xrayez** [comment]
Now I hope you understand what people feel when someone exclude particular groups of community from discussion. I did this on purpose to demonstrate that your rationale may not hold truth, but please don't interpret my words as authoritarian. I'm for expressing opinion openly. What you feel now is unpleasant, yes or no?

**Comment by pycbouh** [comment]
This is inflammatory and extremely unprofessional. Nobody excludes any groups from discussion, and this has nothing to do with the decision making process. This is just inappropriate.

**Comment by Xananax** [comment]
Not unpleasant, simply felt it was dishonest. I'm happy that it wasn't the case. 

But no one's argued that the community should be walled off away from any contribution. And as a result, had I been annoyed or not, it wouldn't answer a single one of the points I or other have made.

The points are;

1. "community driven" means what it means, it applies to Godot, and there's no point arguing the meaning of it
2. there's no alternative to a governance by a small group that knows the software inside and out

**Comment by Xrayez** [comment]
> This is inflammatory and extremely unprofessional. Nobody excludes any groups from discussion, and this has nothing to do with the decision making process. This is just inappropriate.

@pycbouh please express your professionalism and read my previous post entirely to internalize it:

> Now I hope you understand what people feel when someone exclude particular groups of community from discussion. I did this on purpose to demonstrate that your rationale may not hold truth, **but please don't interpret my words as authoritarian. I'm for expressing opinion openly** [emphasis mine]. What you feel now is unpleasant, yes or no?

Nothing what I've previously said in this discussion was offending or demeaningful.

Your accusations are groundless. 😕

**Comment by QbieShay** [comment]
> Now I hope you understand what people feel when someone exclude particular groups of community from discussion. I did this on purpose to demonstrate that your rationale may not hold truth, but please don't interpret my words as authoritarian. I'm for expressing opinion openly [emphasis mine]. What you feel now is unpleasant, yes or no?

Who has been excluded, from what discussion?

**Comment by mrjustaguy** [comment]
Actually it's not a groundless accusation, as He's got a Point.. The attempted demonstration (and the follow up to it) does appear inappropriate and unprofessional (as in slightly childish) and could have been worded a bit better and clearer in a more professional manner...

Now I know this'll end up feeling like suppressing the topic, but I think this proposal should be closed/changed a bit to actually go more indepth with the actual issue at hand and propose some more concrete solutions to it.. the last 2 points specifically could possibly be looked at more, however the 1st point under the solution is just nonsense as the differences are near-non-existent between proposed and current and very prone to subjective understanding and really just nitpicking on a non-important detail (I mean 99% of people wouldn't even think there's much of a difference between community-based/maintained and community-driven).

**Comment by QbieShay** [comment]
@Zireael07 there is a difference between being excluded from a discussion and not being the person that has the final word on the discussion.

Again, please provide practical examples, with suggestion on what should have been done differently

**Comment by Xrayez** [comment]
> Given the definition of Data Driven Programming i can understand why the community may think they're in charge.
> [From "The Art of Unix Programming"](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch09s01.html):
> 
> > One is that in data-driven programming, the data is not merely the state of some object, but actually **defines the control flow** of the program
> 
> [From an answer on Stack Overflow](https://stackoverflow.com/questions/1065584/what-is-data-driven-programming):
> 
> > Data driven progamming is a programming model where the data itself **controls** the flow of the program and not the program logic
> 
> But let's have a look at [Profile-Guided Optimization](https://en.wikipedia.org/wiki/Profile-guided_optimization):
> 
> > Profile-guided optimization (PGO, sometimes pronounced as pogo[1]), also known as profile-directed feedback (PDF),[2] and feedback-directed optimization (FDO)[3] is a compiler optimization technique in computer programming that uses profiling to improve program runtime performance.
> 
> So the profiler isn't making decisions, compiler does based on the feedback it got from the profiler.
> 
> So perhaps _community-guided_ would be better?

I'm sorry I haven't replied earlier, but yes, I think this better reflects the existing model.

When I search for "open source community driven" in Google, the first result I get is this:

https://thenewstack.io/why-the-best-open-source-is-community-led-open-source/

The "lead" may also be an appropriate word to describe the true meaning in the context of Godot development specifically, because:

* Development and direction of the project completely relies on community needs of the majority.
* Therefore, the community actually has a direct influence where the project may end up in the future.

It's not just semantics, different community-based models are described in various scientific sources. This kind of information is crucial to understanding the existing model for any new contributor, in my opinion. Especially as big as Godot.

I'd like to remind you that I'm dedicating my lifetime to Godot development *for free* at times. This is why I'm asking to be crystal clear regarding this topic, because I'd like that future contributors won't stumble upon those pitfalls and illusion that their feature requests are going to be accepted without hassle.

I just recall the time when Godot community was quite small and we didn't have Godot proposals in the separate repository. It was much easier to add something to the engine if community expressed general positive feedback merely based on a few 👍s.

I understand that Godot grows at a fast pace, that's why it's super important to keep development principles and governance model up-to-date.

**Comment by Xrayez** [comment]
@Xananax

> For example, closing this issue without answering and wasting precious contributor time. That would be my personal opinion, and how I would act. But that's not the subject.

I agree with you.
