### ISSUE TITLE
Mark and/or hide renamed properties

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#2686]
Godot 3.3 has renamed use_pixel_snap, but both properties remain in the project list and the description text has been completely removed. I guess this is for backwards compatibility but it's confusing, especially the push to make the project list simpler? I expect the same goes for other node properties renamed in the node inspector too....

1. For renamed properties add a DEPRECATED tag (popup help) so when presented in the gui it can be easily seen it has been renamed and what to, rather than just a blank entry, confusing everyone that is not a Godot developer
2. I believe there is a PR to add an 'advanced/basic' toggle for properties. Given this will hide things, why not add an extension to always hide renamed items?

![image](https://user-images.githubusercontent.com/12863685/116971280-3b5be880-acb1-11eb-8251-dc16a0642696.png)

![image](https://user-images.githubusercontent.com/12863685/116971254-326b1700-acb1-11eb-97d0-1e94686eb1a7.png)

**Comment by pycbouh** [comment]
This is not for backwards compatibility, the old property won't work. It is displayed on the list because it is saved in your settings file. At this point it's the same as if you had a custom setting, from a plugin for example. In this case this can indeed feel confusing, maybe an option to remove custom properties can be introduced to clean it on demand.

You need to follow the proposal template, however, before we can consider anything. The issue will be reopened when you update your proposal.

**Comment by Calinou** [comment]
For the record, this was already reported here: https://github.com/godotengine/godot/issues/22099

**Comment by chucklepie** [comment]
On, I'll rephrase to match template.

But to answer your question, surely there's a distinction to be made
between custom properties and those properties that are not custom but are
changed within godot...

As it happens not deleting them is a good thing because it means you have
backwards compatibility.

**Comment by pycbouh** [comment]
> As it happens not deleting them is a good thing because it means you have backwards compatibility.

There is no such correlation. Those settings are not recognized by the engine anymore. You only see them because you have them saved in your settings file. Newer versions of the engine don't have a database of the property names used by previous versions, so no, there is no distinction between those and custom properties.

**Comment by Zireael07** [comment]
Cleaning those up or marking them somehow is a good suggestion.

**Comment by chucklepie** [comment]
I know, I was just saying maybe there should be a distinction between
custom properties that you can create yourself and those that are
deprecated.
