### ISSUE TITLE
Better github actions flow

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2703]
### Describe the project you are working on
A PR for the Godot engine

### Describe the problem or limitation you are having in your project
User story: "As a new contributor, I found it hard to get my commit ready to be merged"

I had several issues with my build pipeline, lint issues, code issues (platform specific) and docs issues.

As it was I waiting for at least three build cycles to complete before understanding all of my issues.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would have found it easier if the the fastest github actions were run first (Static code check, docs check)

In this way the PR would have been easier to deliver because I could respond more promptly to requests by the build process.

Perhaps the steps could also be auto-linted, and docs generated automatically. This would prevent a failed build for an extra " " or missing newline, as these can be handled by the build step itself. Probably the same for docs?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Github actions flow could be changed to only trigger later builds after fast build steps are completed first.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I guess this is used for every PR

### Is there a reason why this should be core and not an add-on in the asset library?
This is github specific

**Comment by pycbouh** [comment]
Static errors can be caught before you even commit any changes by pre-commit hooks that we provide:
https://github.com/godotengine/godot/tree/master/misc/hooks

Docs cannot be auto-generated, because it's the responsibility of the author of the PR to document their changes. A machine cannot do it, and the check is now enforced on GH to remind the author if they forget to do that.

As for platform specific issues, yes, this is a known problem. Yet for you to see the problems you don't have to wait for all of the tasks to fail or finish. They are ready as they are processed and you can see issues immediately. So I'm not sure how chaining build steps would help you.

**Comment by tavurth** [comment]
> Static errors can be caught before you even commit any changes by pre-commit hooks that we provide:

Ah I see, I was not aware of this. I guess it's difficult to build a cross platform hooks system?

> Docs cannot be auto-generated, because it's the responsibility of the author of the PR to document their changes. 

I ran `./bin/godot.osx.tools.x86_64 --doctool` and it generated the docs for me. Is this not the correct flow?

> So I'm not sure how chaining build steps would help you.

In my case the build steps only ran 2 at a time, and they took about an hour to get to the final error `file_format`, then I fixed the issues and the build failed at the very last step `linux:generate_docs`.

Perhaps it would be good to move the `generate_docs` stage to one of the faster build cycles? Linux always seems to take the longest. (Now running for 30 minutes or so)

In general I would love to see some more docs on the build flow as well as for a first contribute it was a little tricky. The [build steps docs](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html) were good and very helpful, but I didn't see these issues until the Github actions informed me of them hours after my commit 😞

**Comment by tavurth** [comment]
Another example of this would be the docs check:

```patch
-		<constant name="KEY_MASK_CMD" value="134217728" enum="KeyModifierMask">
+		<constant name="KEY_MASK_CMD" value="268435456" enum="KeyModifierMask">
```

Above it seems that somehow the value of `KEY_MASK_CMD` has changed while running `--doctool` however, why I'm not sure, it seems to be a platform specific issue (because I'm building the PR on a MAC)

Or this one:

```patch
-		<member name="audio/driver" type="String" setter="" getter="" default="&quot;CoreAudio&quot;">
+		<member name="audio/driver" type="String" setter="" getter="" default="&quot;PulseAudio&quot;">
```

Which also seems to be platform specific (Last time it was built on Linux, now it's built on a mac)

**Comment by pycbouh** [comment]
> I guess it's difficult to build a cross platform hooks system because of platform specific dependencies? 
More like, toolchains and environments differ. You can only really check platform specific stuff that CI checks for by using the same containers and building it multiple times yourself. That's a bit too much for most PRs though.

> and it generated the docs for me. Is this not the correct flow?

No, this is exactly what you need to do. But what exactly did you mean in the OP then? I understood your proposal as "generate docs on CI automatically".

> Perhaps it would be good to move the generate_docs stage to one of the faster build cycles? Linux always seems to take the longest. (Now running for 30 minutes or so)

Ah well, I don't think we have much control over it. We are at the mercy of the GitHub cloud services. Though lately builds became pretty fast and take less than 15 minutes to complete, with most tasks usually done in 6-7 minutes.

> I guess hooks would also fix this?

Hmm, no, doctool should "fix" that. In fact, it shouldn't provide any platform dependent results. If this happens, it's an issue that we need to address.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/pull/46235. If that PR is merged, all you need to set up pre-commit hooks would be to run `pip install pre-commit && pre-commit install`.

**Comment by tavurth** [comment]
>  I understood your proposal as "generate docs on CI automatically".
Yep sorry that was my miscommunication, I was talking about the `--doctool` part of the flow.

Rather, why should the build fail if the user would run `--doctool` anyway. If the CI is running that anyway, perhaps we could create an extra commit on the branch if there are changes needing to be made?

Users could then squash at their discretion.

**Comment by pycbouh** [comment]
> Rather, why should the build fail

Because we want contributors to act responsibly regarding documenting features they add. Also, when contributors forget to run the doctool, other contributors who don't — get a lot of changes that they were not responsible for. We don't enforce filling out the docs, but at least running the tool is required so that others don't run into this issue.

> If the CI is running that as part of it's test, perhaps we could create an extra commit on the branch if there are changes needing to be made?
> Users could then squash at their discretion.

I don't see this saving anyone any time, as we already require commits to be squashed on the main repo. So contributors always have to do it, not just at their discretion. And at this point, they can just as well run the command. If they can build from source, running this command is trivial and takes almost no time. And running it themselves hopefully would push them to actually write the docs for the code they want to commit. Because, well, who's better to do this? 🙂

**Comment by Xrayez** [comment]
See also godotengine/godot#46224.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/46224.
