### ISSUE TITLE
Add a "virtual" Folder node for editor-only scene tree organization

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#2717]
### Describe the project you are working on
This suggestion is not related to my project in particular, but to the organization of nodes in the editor.
### Describe the problem or limitation you are having in your project
The organization of the nodes in the tree is something that could be improved by adding a node of type "Folder".
A node of type "Folder" is only used in the editor to organize the nodes, this node is destroyed when execution occurs and during execution it is as if it never existed and has no effect on the tree, this node is only to group and organize the nodes in the editor and does not interfere with the tree.
The node of type "Folder" only exists at edit time for organizational purposes.

At the moment a node of type "Node" is added thus complicating the tree and occupying more memory than necessary and only to be able to organize the tree.
Furthermore, this node does not remain collapsed and expands when you select a node in the editor (not in the tree) so it is useless to put the nodes in another node as a container because it does not save any space.

I do not understand what problem there is in adding it, whoever wants to use the folder node has full rights and whoever does not want to use the folder node is also fully entitled.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The "Folder" node can contain other nodes that are located at the same level of the tree, it is exactly like a windows folder with the difference that you can only place nodes that are at the same level as the "Folder" node, that is to say , you will not be able to put the parent of the "Folder" node inside the "Folder" node because it is impossible.

![Captura2](https://user-images.githubusercontent.com/19652075/118140033-44af2880-b408-11eb-90cb-8239b47065a7.PNG)

Folder node in action
![Captura](https://user-images.githubusercontent.com/19652075/118140459-aa031980-b408-11eb-8aa8-2a3ef2918939.PNG)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
I do not know if it is possible to do it with an addon.

**Comment by pycbouh** [comment]
I feel like this was already proposed, but can't find the issue at the moment.

At any rate, this is unlikely to happen. First of all, a folder can't be a node, as nodes have a place in the tree and cannot be "virtual". Secondly, if we were to add fake nodes into the scene tree we would only confuse users when they try to assess the node path for a node in a folder.

You can just use plain `Node`, `Node2D`, `Node3D`/`Spatial` or `Control` nodes for grouping. They won't magically disappear when you run the project, but I see no problem with that. And if you want them to disappear this definitely can be done with several lines of scripts.

**Comment by Torguen** [comment]
But that's a strange solution, adding a "Node" just for organizational purposes and then destroying it through code, that's what the folder node would try to avoid.
Anyway, it seems to me that it could help the organization.

**Comment by pycbouh** [comment]
> But that's a strange solution, adding a "Node" just for organizational purposes and then destroying it through code, that's what the folder node would try to avoid.

It's only strange because you've put a requirement to destroy it in code for some reason. You can keep organizational nodes at runtime, there is really no reason to remove them. Thus any node can function like a folder.

**Comment by Torguen** [comment]
It is strange because the purpose of a node is not to serve only to contain other nodes without providing any utility beyond that and occupying memory and resources uselessly.
I understand that it is not possible to add the hint for some reason but it is obvious that using a node only to contain other nodes ... that is not the purpose of these.

**Comment by pycbouh** [comment]
> it is obvious that using a node only to contain other nodes ... that is not the purpose of these.

That is not true, you're inventing this limitation yourself. It is completely within Godot's approach to use nodes for grouping. Also memory spent on such nodes would not be among your first concerns when optimizing your game. Use nodes freely, use a lot of them. That's what they are there for.

**Comment by Torguen** [comment]
> That is not true, you're inventing this limitation yourself.

That is not true, you are trying to camouflage that lack... and so we could spend the day.

> It is completely within Godot's approach to use nodes for grouping.

Yes, I know that, that's why I make the suggestion, because it seems to me that nodes uselessly occupy memory, resources and complicate the tree, because now you will have to navigate one more level and it is the level that adds that node that only serves to group .

One thing is that it is not possible to add the suggestion, which I understand and another thing is that you deny the usefulness of a type of node that does the function of a kind of folder, you yourself said that the suggestion has already been made.

**Comment by pycbouh** [comment]
Not only I deny usefulness of this suggestion (because this can already be achieved in Godot), I see harm in introducing nodes that do not affect the path. It would only bring confusion to users, as what they see is no longer what they actually get. And since you seem to want this to be the case on purpose, I am completely against such approach.

> That is not true, you are trying to camouflage that lack... and so we could spend the day.

I'm not sure what you want to prove with this. You argue that something cannot be done in Godot because of a limitation that you've yourself put in place, a limitation that does not actually exist in Godot. I'm only trying to correct your misconception, in case you've misunderstood something about Godot. It'd be hard for you to argue a case for your idea if you invent limitations in Godot just to solve them with your idea. In fact, this goes against [our methodology for contributing](https://docs.godotengine.org/en/stable/community/contributing/best_practices_for_engine_contributors.html), where a solution must be a result of an existing problem, and not the other way around.

**Comment by trollodel** [comment]
> I feel like this was already proposed, but can't find the issue at the moment.

It's part of #791

**Comment by Torguen** [comment]
It is the opinion of each one, I would like to be able to organize them better without using a node in the way I said before.

On the other hand.
Well, if that limitation doesn't exist, then can you tell me how I can group nodes in a way other than by creating a node that interferes with the tree?

That is, how can I get what I suggest without a node like the one I am suggesting?
I think its imposible.

**Comment by Torguen** [comment]
> I'm not sure what you want to prove with this. You argue that something cannot be done in Godot because of a limitation that you've yourself put in place, a limitation that does not actually exist in Godot. I'm only trying to correct your misconception, in case you've misunderstood something about Godot. It'd be hard for you to argue a case for your idea if you invent limitations in Godot just to solve them with your idea. In fact, this goes against [our methodology for contributing](https://docs.godotengine.org/en/stable/community/contributing/best_practices_for_engine_contributors.html), where a solution must be a result of an existing problem, and not the other way around.

What I'm trying to show by this is that you simply don't see (or don't want to see) what for some users may be a lack. You do not accept that this could mean a lack for anyone.
But I'm not going to argue about that any more.

**Comment by Zireael07** [comment]
IMHO adding a folder that is essentially a visual-only helper to collapse things is a needless complication to Godot's clear node tree structure. There is nothing preventing you from using a Node or a Control or a Spatial to organize things, and if the "organizer" node has no script/visuals, it doesn't affect performance (I have quite a lot of those "organizers", empty nodes in my project :P )

Alternately we could maybe implement collapsing node x + arbitrary siblings in the editor scene tree, for visual-only purposes, but as I said - why?

**Comment by dalexeev** [comment]
> I feel like this was already proposed, but can't find the issue at the moment.

I think I found it. godotengine/godot#31786

At that time, I even supported this, although now I believe that the existing approach does not need to be improved.

It's funny that you supported that too. :rofl: 

![](https://user-images.githubusercontent.com/47700418/118151069-e5f3aa00-b41b-11eb-8e27-a32b354e6456.png)

**Comment by pycbouh** [comment]
> It's funny that you supported that too. 🤣

@dalexeev Oh, but I didn't support folders per se in your comment (you may notice I've also liked Akien's comment saying the same there as I do here). What I liked about your comment is the idea for collapsing a chain of intermediate nodes into one. I did have the need for that quite a bit at the time. Interestingly, I don't need it that much these days. But still, intermediate nodes collapsed into one is a good idea (given that the paths respect it one way or another).

But no, I wasn't remembering that issue, I was remembering #791, as mentioned above.

**Comment by dalexeev** [comment]
The idea of collapsing paths is as bad as the idea of folders because it only confuses the user. And the problem I mentioned is solved in other ways: [improved $ operator](https://github.com/godotengine/godot-proposals/issues/1776) and [export of nodes](https://github.com/godotengine/godot-proposals/issues/1048).

**Comment by pycbouh** [comment]
@dalexeev Like I've said, paths must be somehow respected, precisely to avoid confusion. But this is unrelated anyway, and doesn't bother me anymore regardless.

**Comment by Error7Studios** [comment]
> It is strange because the purpose of a node is not to serve only to contain other nodes without providing any utility beyond that and occupying memory and resources _**uselessly**_ in addition to complicating the tree.

You can use the parent node to do some operation on all its children at once, without every needing to use `add_to_group()` / `get_nodes_in_group()`, so it's not useless.

![Enemies Node](https://user-images.githubusercontent.com/60025044/118158021-e1f66680-b3e0-11eb-88a7-82d18f807d16.png)

**Comment by KoBeWi** [comment]
This can be achieved with a simple script:
```
func _ready():
    remove_and_skip()
```
Just attach it to a "folder" node and it will disappear on startup.

**Comment by josefkaragoli** [comment]
I dont think theres any reason for this to be core, especially considering there already is an addon for it and as @KoBeWi mentioned, it's pretty easy to do through a custom class.

**Comment by me2beats** [comment]
I can see cases where it could be useful

1. Nodes as folders change scene hierarchy. This may be not convenient or even unacceptable.

For example there are tools or plugins that work only with direct children (not with grandchildren etc).
For example gridmap works only with direct meshinstance children.
Fixing gridmap by making it work recursively is a limited solution because there could be some third party plugins which you can't "fix" (they may be closed and the developer could be unavailable or he may not accept proposals).

2. Having many Spatials-folders and deep node hierarchy is not good for performance (of course not critical, but nonetheless)
so one would have to remove them manually, for example then the scene instance enters the three. this is a boilerplate code which could be not so small, depending on the project architecture/design.

3. Node/spatial-as-a-folder approach just violates "SRP" (I don't mean OOP tho).
Folders should be folders, not Spatials, not even Nodes imo.
Why do folders need to have signals or an ability to set a script on them?

On the other hand I understand that implementing folders as just SceneTreeEditor tree items is not a simple thing.

**Comment by Jummit** [comment]
Seeing the ratio of up/downvotes on this post I think it's very unlikely that the proposed change will be implemented. I suggest closing this proposal and letting the author decide if he wants to create another proposal which he thinks will get more approval.

**Comment by Torguen** [comment]
There are several threads (I think 3 in total, including this one) suggesting this.
I don't think a new one needs to be opened.
https://github.com/godotengine/godot/issues/31786

**Comment by me2beats** [comment]
I forgot to say some other points:

— A problem with node-as-a-folder approach is that it  can cause inconvenience when refactoring.

    By refactoring I mean for example moving a node to some another "folder" or "subfolder".
Then if you had node paths relative to the node parent defined in the script, you might have errors, because paths changed.
Imo folders should be designed keeping in mind that the user may rename them often or create new subfolders and move nodes there

— Inconvenience when you should choose what type of a folder node should be: Node, Node2D, Spatial or even Control, and then watch it fits it's children

— Finally folders could have their own unique features

Folders as TreeItems (SceneTreeEditor is a Tree) instead of Nodes could better solve these and  the above (listed in me previous comment) problems than nodes as folders imo.

**Comment by Torguen** [comment]
I don't know, it makes me hell to be navigating the tree without being able to group the nodes in some way.
In this gif I use a container node called "ItemsRespideros" to have some nodes there collapsed without taking up space but this does not work because when you select a node, the node expands automatically so I'm not sure if it has any use to make the advice that the companions more above suggest.
There is no way to keep that "ItemsRespideros" node collapsed until I decide to open it?

![GIF](https://user-images.githubusercontent.com/19652075/121334365-e0558b00-c919-11eb-8343-b0a79c67834c.gif)

**Comment by Torguen** [comment]
> > it is obvious that using a node only to contain other nodes ... that is not the purpose of these.
> 
> That is not true, you're inventing this limitation yourself. It is completely within Godot's approach to use nodes for grouping. Also memory spent on such nodes would not be among your first concerns when optimizing your game. Use nodes freely, use a lot of them. That's what they are there for.
> 
> > in addition to complicating the tree.
> 
> It's not complicating the tree, it's organizing it.

**Comment by Torguen** [comment]
Oh, I accidentally closed it.

**Comment by me2beats** [comment]
> There is no way to keep that "ItemsRespiraderos" node collapsed until I decide to open it?

I think you could use "Make sure the object children are not selectable"

**Comment by Torguen** [comment]
> > There is no way to keep that "ItemsRespiraderos" node collapsed until I decide to open it?
> 
> I think you could use "Make sure the object children are not selectable"

Thanks but it didn't work, now I can't select them in the editor (they are all selected at once).
![GIF](https://user-images.githubusercontent.com/19652075/121339100-6f64a200-c91e-11eb-9b2f-a9cbde0998d2.gif)

**Comment by KoBeWi** [comment]
I think that automatic unfolding is another problem, unrelated to this proposal.

**Comment by me2beats** [comment]
> Thanks but it didn't work, now I can't select them in the editor (they are all selected at once).

hmm yea, that won't work

I also don't think this should be solved only with using folders or so.
There should be an option like "`auto unfold nodes when selecting in editor`", this would solve this problem.

Also I believe this could be workarounded with a plugin (a bit hacky tho, since SceneTreeEditor lacks plugin support/API currently).

**Comment by Torguen** [comment]
> > Gracias pero no funcionó, ahora no puedo seleccionarlos en el editor (se seleccionan todos a la vez).
> 
> hmm sí, eso no funcionará
> 
> Tampoco creo que esto deba resolverse solo con el uso de carpetas o algo así.
> Debería haber una opción como " `auto unfold nodes when selecting in editor`", esto resolvería este problema.
> 
> También creo que esto podría solucionarse con un complemento (aunque un poco hacky, ya que SceneTreeEditor carece de compatibilidad con complementos / API actualmente).

I agree, that option could solve the problem in principle.

**Comment by Torguen** [comment]
What is the status of this?
Should we open an addition proposition or what?

**Comment by timothyqiu** [comment]
@Torguen In case only the instanced scenes' position matters, as a workaround:

1. Add a special tile for your item (name it `item_tile` for example)
2. Instead of instancing individual items in the editor, draw the tile in your TileMap
3. Use the following snippet to instance `Item.tscn` from `item_tile` tiles:
    ```gdscript
    func instance_tiles(tile_name, scene):
    	var id = $Tilemap.tile_set.find_tile_by_name(tile_name)
    	assert(id != -1)
    	
    	for pos in tilemap.get_used_cells_by_id(id):
    		var node = scene.instance()
    		tilemap.add_child(node)
    		node.position = tilemap.map_to_world(pos)
    		tilemap.set_cellv(pos, -1)
    
    # Call instance_tiles("item_tile", preload("res://path/to/Item.tscn")) in _ready()
    ```

**Comment by pycbouh** [comment]
> I don't understand how people can work with the current tree, I don't see many people making requests for this.

Honestly, your scene tree looks sensible, organized and easy to work with. But yes, to disable the auto-unfolding on selection you need to open a new proposal so that it can be discussed separately.

**Comment by Torguen** [comment]
Ok, I have already proposed.

**Comment by Calinou** [comment]
For future reference, @Torguen's proposal is here: https://github.com/godotengine/godot-proposals/issues/3095

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on the first post).

**Comment by Nodragem** [comment]
@Calinou I actually felt the same need as PabloDevGit recently, and the obvious missing point to your argument is the performance cost of having a Node3D parented to N Node3Ds. It would be useful that the documentation explains the performance cost and why it is not worth worrying about. Maybe by showing a benchmark, or telling us about the various optimisations done by Godot behind the scene.

As much as some would like *early optimisation* to be a sin, good practices and awareness about performance will prevent huge refactors down the line when the game has to run on real life machines.
