### ISSUE TITLE
Add speed modifier key when dragging mouse inspector to adjust property

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#2760]
### Describe the project you are working on

2D runner game

### Describe the problem or limitation you are having in your project

When you adjust properties in inspector you can drag your mouse and hold ctrl and left mouse button to adjust properties by ful integral. It's painfully slow at the moment. In order to just change value by 3 I need to drag a mouse across whole desk

here is example of how slowly value changes
https://streamable.com/1ripux

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add ability to hold crt + alt for example to speed the process so value adjusts much faster

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No idea

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There isn't really apart of manually typing a value

### Is there a reason why this should be core and not an add-on in the asset library?

Part of a core editor

**Comment by Calinou** [comment]
The logic is here: https://github.com/godotengine/godot/blob/f096a586d51ebcca467e608d62058047fd505e96/editor/editor_spin_slider.cpp#L49-L143

I was pretty sure we had Shift and Alt modifiers already, but it seems we don't…

**Comment by winston-yallow** [comment]
It seems we already have shift. It's in master and in 3.x both: https://github.com/godotengine/godot/blob/f096a586d51ebcca467e608d62058047fd505e96/editor/editor_spin_slider.cpp#L99-L101

It just is the other way round than what the proposal suggests: Shift slows it further down. Which for me feels like expected behavior and is in line with other applications like blender.

I suggest to keep this behavior, and instead increase the default speed. Usually the flow is to first get the value roughly and quickly into the desired target range, then pressing shift to fine tune the value. It's just that the base speed is way too slow for this workflow.

**Comment by akien-mga** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/3017.
