### ISSUE TITLE
Add a default `main.tscn` to a new project

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#2792]
### Describe the project you are working on
A block building builder for the GoGodot game jam.

### Describe the problem or limitation you are having in your project
Every time a new project is started a "interrupting" popup appears that says to define a main scene. Not a big deal, but it breaks the flow a bit and I feel like there could be a more elegant solution, that also communicates better what "main" means, as I did not know this for some time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
https://github.com/godotengine/godot/issues/1134, this is a previous issue about this, which talks about this popup: "The pop up will solve the issue of a new user having to search for "Project Settings" and the main_scene setting.". 

Proposal: Add a default Main.tscn to the project, which the ProjectSettings automatically sets as the main_scene, just like icon.png. Then you can add your scenes/nodes under main and run it with F5 immediately .

This does not communicate however that the option to change the main scene exist. Therefore, you could add a Node with editor description to Main.tscn explaining what main stands for and that you can change it in ProjectSettings, but I am not really sure about this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![afbeelding](https://user-images.githubusercontent.com/49942484/119825017-d2a20d80-bef6-11eb-8542-6fb62af6f85b.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
no, it happens at startup.

### Is there a reason why this should be core and not an add-on in the asset library?
no, it happens at startup.

**Comment by pycbouh** [comment]
I don't think it's a good idea. Current behavior highlights a configuration problem that each developer needs to solve as they see fit. Your solution would hide that there is a problem, yet doesn't help inexperienced developers when they create their own scenes, hit "Play" and don't see them, because the empty and untouched default "main" scene was launched.

There is also a question of what that scene would be, what type of node would it have as its root and why.

**Comment by boukew99** [comment]
Okay thanks, I see now. Will close this now. BTW tried the highlighting of Tree and it was really nice

**Comment by pycbouh** [comment]
Generally there is no need to close your proposals after one disagreeing comment. This is just my opinion 🙂 But if you don't feel like it's worth it anymore, then it's fine to close it.

**Comment by boukew99** [comment]
Mmm okay. Felt like I did not really know the size of what I was proposing anymore. But will leave it open a bit longer then. 

To clarify:
In my understanding main scene was just the entry point. But a tree only has one entry point and that is its root, thus that is what Main.tscn represented for me.
However the actual root is the root viewport though, so that is the actual entry point, however that can't be customized. 
So that's why there is your own main scene. I did not take into account that it might be configured in different ways. 

Furthermore, a possible main scene could be the root viewport. It will be more transparent about what happens when you run a scene (as can be seen with remote Scenetree).

**Comment by Calinou** [comment]
> Furthermore, a possible main scene could be the root viewport. It will be more transparent about what happens when you run a scene (as can be seen with remote Scenetree).

This would require the scene to be added as an autoload for it to work as expected when you use <kbd>F6</kbd> to run a custom scene.

**Comment by Xrayez** [comment]
I have a script which creates a project from a template containing `main.tscn` with `Node2D` as root (because I make 2D projects most of the time), so yeah I highly support the idea behind this proposal, see godot-extended-libraries/godot-ideas#12 which describes the hurdles of creating new projects similarly.

See also related proposals in **Speeding up creation of new projects or development workflows** section in godot-extended-libraries/godot-ideas#15 (quite a bunch of them so far).

**Comment by seocwen** [comment]
I always liked having the default main file in XNA, with all its excessive comments, but Godot, is less in need of that sort of mini-tutorial because nodes handle so much functionality. I think the equivalent would be an empty default main.tscn with an attached default main.gd with useful comments, but I struggle to think of what this would be. I wrote down my thoughts from the first time I used Godot:

> 	When I opened Godot for the first time it asked if I wanted to explore available templates, which sounded amazing. I didn’t know I wanted my game engine to introduce itself by showing off its features and offering a foundation to work from, but apparently I did. Then again, GUI Drag and Drop Demo didn’t exactly deliver on those expectations. Was it unreasonable of me to yearn for a template that might serve as a broad tutorial for how the engine worked? Perhaps even a game where the goal was to learn how the game engine itself worked? I’ve never seen such a thing, but opening Godot made me want it.
> 	So, I found the engine’s documentation—the website navigation hides it under the learn tag, which for all knew might have been a page marketing Godot to schools—which I liked. It’s because of the FAQ I decided to write this.

**Comment by rainlizard** [comment]
I would like this because it speeds things up. I agree a little with pycbouh, it's good for the new-user to get a grasp on the filesystem and where they're saving their scene. I think that's really user-friendly stuff for new users. The issue here is that while it's good for new users it's rather tedious for the rest of us.

I think project templates need to be better implemented. **Local** project templates, not these internet templates that take 10 seconds to load, I've never used someone else's template because working with someone else's code in your project is just a huge chore. But I would ALWAYS use small local templates that I made, if I could. For test projects, for new projects, etc. To bring this back to the topic - such a template would allow you to create a simple project with a Main.tscn (in a sub directory if necessary).

You can't just tell me to use templates because this topic is about relieving some tedium and the current implementation of templates is no faster.

**Comment by dalexeev** [comment]
We can add `main.tscn` with one "Hello world" label. Just so that you can press Play and the project will start.

**Comment by pycbouh** [comment]
I think that just a better way to make personal project templates is the solution here, like @rainlizard mentioned. We can even include an example of such template that would add some default `main.tscn`. But I still don't think we should change the default behavior.

**Comment by Calinou** [comment]
I also have a `godot-init` script for command line users: https://gist.github.com/Calinou/cd4c67e2a44377c9fb772500daa467f5

**Comment by dalexeev** [comment]
It seems to me that we are talking about inexperienced users who have just opened Godot. I remember how a few years ago I could not figure out what was needed for 5 minutes:

1. add a root node (there was a problem here);
2. save the scene;
3. press the Play button and select the main scene.

Now point 1 is almost eliminated, thanks to the Root Selection in the Scene panel, but still, the process is not so obvious when you first see it. Yes, this is just a minute delay, but a little help to the user is important at the start.

> I think that just a better way to make personal project templates

> I also have a `godot-init` script for command line users

When we talk about newbies, command line and personal project templates won't help. This should be in the default template, and the user can replace the template with the one they want.

**Comment by pycbouh** [comment]
@dalexeev To simplify your step 1 further I've proposed https://github.com/godotengine/godot-proposals/issues/679 some time ago.

**Comment by Xrayez** [comment]
They way I see this, it could be an option in the project manager:

![godot_project_manager_2d_3d](https://user-images.githubusercontent.com/17108460/120028331-39115380-bffd-11eb-873d-1ca72138e3b9.png)

- `Empty`: will do nothing (current behavior).
- `2D`: will instantiate `Node2D` scene and assign it as main one.
- `3D`: will instantiate `Spatial/Node3D` scene and assign it as main one.

2D projects don't need to instantiate `default_environment.tscn`, so we can skip generating this resource, which also speeds up project initialization (due to procedural sky which needs to be generated every time).

Depending on the project type, default project settings could also be adjusted.

Don't know about you, but I would see this as a major workflow improvement.

**Comment by pycbouh** [comment]
Make it a dropdown (like with the script templates) and a way to define your own templates in the editor data folder, and that's it.

**Comment by Calinou** [comment]
@pycbouh Sounds like a good idea to me (on top of being easy to implement), but we'll have to rename the "Templates" tab in the project manager to something like "Online Templates" since it will not list local templates.

**Comment by pycbouh** [comment]
@Calinou We do have a PR to rename tabs in the PM: https://github.com/godotengine/godot/pull/47871

Speaking of which, this is conflicting a bit with https://github.com/godotengine/godot-proposals/issues/1813 / https://github.com/godotengine/godot/pull/42447

**Comment by aaronfranke** [comment]
@Xrayez @pycbouh We could take what is in https://github.com/godotengine/godot/pull/42447 and swap out the default environment checkbox for another dropdown which has options for creating default scenery for 2D, 3D, UI, or Empty. Picture for reference:

![Screenshot from 2021-05-28 17-14-20](https://user-images.githubusercontent.com/1646875/120042735-ad85cb80-bfd8-11eb-8416-495efe88b547.png)

**Comment by boukew99** [comment]
> but a little help to the user is important at the start
> that we do provide a newbie-friendly template out of the box
Yes, it would be nice to have a supportive starting foundation that sends you on the right path

**Comment by Error7Studios** [comment]
If you're going to add a default `main.tscn`, please give it a `main.gd` with:

```
func _input(event):
	if event.is_action_pressed("ui_cancel"):
		get_tree().quit()
```
I feel like I've written that function a thousand times.

**Comment by Xrayez** [comment]
Note that you can stop the Godot debug process with F8 key (which works while the game window is focused and while in the editor). Unless you'd also like to let the scene tree to trigger other deinitialization callbacks.

**Comment by Error7Studios** [comment]
> Note that you can stop the Godot debug process with F8 key

Thanks, I always forget about this.
`Escape` is the universal close/exit window key, so it feels natural to have that also stop the `main` scene by default.

**Comment by Calinou** [comment]
> Escape is the universal close/exit window key, so it feels natural to have that also stop the main scene by default.

This means you wouldn't be able to use <kbd>Escape</kbd> to open an in-game menu anymore, since the process would be killed.

**Comment by Error7Studios** [comment]
> This means you wouldn't be able to use Escape to open an in-game menu anymore

Hm, good point. Guess I'll just get used to using <kbd>F8</kbd>, then.
(P.S. Thanks for the <kbd>any</kbd> key tag)

**Comment by rainlizard** [comment]
That's why you do:
```
if Input.is_action_just_pressed('ui_cancel'):
	if OS.has_feature("standalone") == true:
		oConfirmQuit.popup_centered()
	else:
		get_tree().quit()
```
lol, old habits die hard.

But this conversation doesn't matter because it's absolutely necessary that templates be custom and defined by user.

**Comment by MaaaxiKing** [comment]
Such a basic but wonderful idea! I wonder that no one else came up with this yet. However, wouldn't `game.tscn` be more sensible owing to the fact that Godot is a **Game Engine**, regardless of the opportunity to produce some other-kind program‽

**Comment by pycbouh** [comment]
> Such a basic but wonderful idea! I wonder that no one else came up with this yet. However, wouldn't `game.tscn` be more sensible owing to the fact that Godot is a **Game Engine**, regardless of the opportunity to produce some other-kind program‽

It doesn't really matter what we would call it, especially since we are talking about some default template. If you want it to be anything else, you can always customize it after your vision.

**Comment by Xrayez** [comment]
The way I see it, it's more about the program's execution/entry point. Many (if not all) statically built apps are invoked via `main()` function as requested by operating system. Even though GDScript is interpreted language, this conveys an appropriate message that this `main` scene could be considered as the main entry point in the context of Godot's scene tree system. Especially when the "main scene" concept is already familiar to existing Godot users.

**Comment by me2beats** [comment]
local templates could solve the problem as well
https://github.com/godotengine/godot-proposals/issues/1481

**Comment by boukew99** [comment]
Okay, however this proposal has lost its need for me, since I mostly work on 1 project now and have a pretty fixed main scene (switched sometimes for iterating). I think my proposal originally came from a confusion of how to apply structure, partially due to inexperience, and thus I ended up making more new projects. I am fine now with how it is.

**Comment by KoBeWi** [comment]
btw in 3.5 when you try to run a project without main scene, you get an option to set the current one as main (which is also auto-selected by default, so you can just press Enter).
![image](https://user-images.githubusercontent.com/2223172/150653599-1208beeb-bd3b-4cc2-8fc3-e30c0f7ff512.png)
