### ISSUE TITLE
Don't ignore mouse input when the window is just being focused

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#2827]
### Describe the project you are working on
A virtual lighting program with multiple windows for many different options. (sorted into multiple windows so you can use multiple screens)

### Describe the problem or limitation you are having in your project
If you unfocus the window you have to double click a button (one for the window focus and one for the button) and the button hover dosen't work. It is a bit annoying if you have to double click a button every time you change the window.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Firefox has this feature, so I hope Godot can have it too.  (gray text = unfocused; you have only to click one time to change the tab)

https://user-images.githubusercontent.com/71942164/120844688-0ec91400-c570-11eb-94c9-6275617652b2.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.

### Is there a reason why this should be core and not an add-on in the asset library?
I think window managment is part of the core.

**Comment by RabbitB** [comment]
I've run into this issue as well; seeing as I make a lot of small utility apps in Godot, a common use case is to jump back and forth between the utility program and whatever I'm working on that the utility is intended to help with. It can be frustrating if you're working quickly, go to click a button, only to realize a minute later you didn't actually click the button because the window wasn't in focus.

That said, I've also been frustrated by being unable to click into applications before, without clicking UI elements, either because they're too densely packed, or because the entire window is taken up by a control, so it would be nice to have it available as a project setting that can be turned on or off.

**Comment by Gamemap** [comment]
@RabbitB I think this problem is solved with Godot 4.0. (I was using Beta 1)
If you could confirm this I will close this issue.
