### ISSUE TITLE
int, float, bool, string keywords as shorthand to var : type syntax used by GDScript

### ISSUE THREAD

**Issue by filipworksdev** [godotengine/godot-proposals#2830]
### Describe the project you are working on

No project but potentially useful feature.

### Describe the problem or limitation you are having in your project

Convenience  keywords that would make GDScript slightly easier to write and read. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a number of commonly used type keywords that get converted by the interpreter in the the appropriate typing only when declaring variables. 

`int` shorthand for `var : int`
`float` shorthand for `var : float`
`bool` shorthand for `var : bool`
`string` shorthand for `var : String`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`int a = 1` will be interpreted as `var a : int = 1`  
`float f = 5.4` will be interpreted as `var f : float = 5.4`
`bool b = true` will be interpreted as `var b : bool = true`
`string s = "hello"` interpreted as `var s : String = "hello"`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around simply by using current typing GDScript typing syntax. 

### Is there a reason why this should be core and not an add-on in the asset library?

This appears a small change with potentially major impact on readability, usability and I believe it could get a lot of use. The docs will correctly explain that `int`, `float`, `bool` and `string` are simply there for convenience as a shorthand way of writing the full typing syntax `var : type` and only these 4 types get a shorthand. GDScript only.

**Comment by zinnschlag** [comment]
A new syntax and a new keyword (string), that almost certainly would break existing code. Also, extending the new syntax to just four types is arbitrary and unintuitive. The amount of convenience provided by this new feature is rather small compared to that.

I would like to reference two lines of the Zen of Python (PEP 20). While GDScript isn't Python, I feel PEP 20 is generally a good guideline when it comes to language and software design.

- Special cases aren't special enough to break the rules.
- There should be one-- and preferably only one --obvious way to do it.

**Comment by filipworksdev** [comment]
While GDScript started from Python it has certainly moved past it and is now a unique and mature language in it's own right. It seems to me like your comment says you disapprove of my suggestion because is Python-like enough. I think maybe is time to stop holding GDScript to Python standards and instead think outside the box to bring more functionality to Godot's users. In fact I would argue that typing implementation in GDScript goes against both your points yet very useful for users.  And perhaps yes my suggestion is not useful enough but this was my primary motivation. I will be honest and say I never considered nor cared for PEP or Python when I made this suggestion but rather considered various discussions throughout the years since 2018 when I started using Godot Engine more regularly and it seemed to me like it was a feature many people wanted but was not suggested yet.

**Comment by pycbouh** [comment]
> While GDScript started from Python

It did not.

> It seems to me like your comment says you disapprove of my suggestion because is not Python-like enough

No, their comment is about having a stricter syntax rather than looser syntax with various way to achieve the same thing. It is generally more useful to not allow the latter because it produces unnecessary tensions between language users. For an example of that look into things like Tabs vs Spaces, Yay or Nay for trailing commas, Single or Double quotes, etc. @zinnschlag referred to the specific rule within the PEP20 doc regarding that, and there is nothing Pythonic about this rule:

> There should be one-- and preferably only one --obvious way to do it.

Their other point was that it doesn't make sense to only allow this for some types but not other types. This is also a correct assumption that has nothing to do with Python, but with language design in general. Users would expect things to work universally and arbitrary application of your proposed syntax would only create confusion. The relevant part of PEP20 is once again not Pythonic in its sentiment:

> Special cases aren't special enough to break the rules.

**Comment by filipworksdev** [comment]
Okay but he didn't say that. He literally said "I would like to reference two lines of the Zen of Python (PEP 20)." So there is a direct reference to PEP and Python. You elaborated what he said but that's not what he said that's what you said. And no there's no need to reference any PEP. I actually don't even agree that GDScript should follow both of those lines or that those lines define GDScript. GDScript is writing it's own standard as we speak. The question is whether my suggestion has any benefit to Godot users or not.

**Comment by zinnschlag** [comment]
Please don't quote me out of context:

> While GDScript isn't Python, I feel PEP 20 is generally a good guideline when it comes to language and software design.

That should make it reasonably clear, that this advices originated within the development of Python but is not related to Python.

**Comment by Calinou** [comment]
If you wish to save some typing, use type inference:

```gdscript
var a := 1
var f := 5.4
var b := true
var s := "hello"
```

**Comment by LightningAA** [comment]
If something like this was implemented, I think it should replace the existing `var: type` syntax , which I personally probably wouldn't mind since it's more familiar to me. `var` would be for dynamic variables and maybe a new keyword like `auto` could be used for implicit typing. Probably not worth it, but just throwing around some ideas.

**Comment by aaronfranke** [comment]
Only doing this for 4 types is a bad idea and I'm against it. Doing it for every type would be a neat discussion, and if it existed then I would use it, but realistically I doubt this will be implemented. You would have to convince reduz and vnen.

On the topic of "There should be one-- and preferably only one --obvious way to do it"... if I was designing GDScript from scratch, I would have made `int x = 1` the only way to declare a statically typed integer. We don't have the luxury of designing something from scratch, so if we added `int x = 1`, we would either have to allow both it and `var x: int = 5` (which would annoy people because it breaks the above principle), or break compatibility (which would annoy people because it breaks compatibility and some people prefer the colon stuff... for some reason). The latter seems like the better option, but again, it would annoy lots of people.

> > While GDScript started from Python
> 
> It did not.

One upside of adding `int x = 1` would be that hopefully people stop mistaking GDScript as "started from Python" or whatever. :stuck_out_tongue:

**Comment by LightningAA** [comment]
> or break compatibility
4.0 would be a logical time to make a change like this as GDScript is being rewritten

**Comment by dalexeev** [comment]
> hopefully people stop mistaking GDScript as "started from Python"

Maybe we need to stop comparing GDScript to Python before asking newbies?

![](https://user-images.githubusercontent.com/47700418/120913596-d07f4200-c6a0-11eb-84c4-7bce9ebff1b6.png)

Or admit that in some respects GDScript is indeed very similar to Python, despite the fact that in other respects it is very different from Python?

With regard to this proposal. I agree with the arguments above and in addition I want to say that for GDScript the `var name: type = value` syntax, adopted in Pascal, Python, TypeScript, and some other languages, is more suitable than the C syntax, which is designed to save characters at the cost of clarity. Combining multiple syntax variations and trying to be like all languages at once is a bad goal.

**Comment by LightningAA** [comment]
That's a fair argument, most modern languages (Rust, TypeScript, Kotlin, Nim) seem to use the colons for types. I guess I don't really care too much either way

**Comment by LightningAA** [comment]
See also https://softwareengineering.stackexchange.com/questions/316217/why-does-the-type-go-after-the-variable-name-in-modern-programming-languages#

**Comment by pycbouh** [comment]
> Maybe **we** need to stop comparing GDScript to Python before asking newbies?

We tried: https://github.com/godotengine/godot-docs/pull/4388 Maybe some of those changes weren't ported to 3.x docs, and maybe they weren't enough. Feel free to open a PR.

**Comment by filipworksdev** [comment]
I made this suggestion in good faith but I wasn't prepared for a meta discussion about GDScript and it's Python origins. I want apologize if my comments seemed very defensive. 

For me personally C syntax of declaring variables `int a = 1` is actually more readable to me than `var a : int = 1` or `var a := 1`. In fact  `:=` shorthand is most difficult to read as it requires having to look at the variable name and the value to deduce type. 

We should not be afraid to look for concepts from any language that can potentially make a GDScript a much better language for scripting games. C syntax of declaring variables could be an alternative way in addition to the current syntax. For example Nim is Python like but allows for multiple ways of doing same thing making it more comfortable to programmers from different backgrounds used to different ways of coding. 

I would say this comment perfectly sums up my position.
> 4.0 would be a logical time to make a change like this as GDScript is being rewritten and there are already several breaking changes

Also would like to thank you for your posts and discussions. Re-reading I found a lot of concerns valid such as why only 4? Why add another syntax? Why break compatibility?

**Comment by Calinou** [comment]
> For example Nim is Python like but allows for multiple ways of doing same thing making it more comfortable to programmers from different backgrounds used to different ways of coding.

Nim's style insensitivity is definitely one of the most controversial points of that language, and many people see it as a "billion dollar mistake" (myself included) :slightly_smiling_face:

**Comment by me2beats** [comment]
`int a = 1` instead of  `var a : int = 1`
`float f = 5.4` instead of `var f : float = 5.4`
looks beginner unfriendly.
When you see `var` keyword, it's a variable and nothing else. Very simple.
Otherwise reading the code would be harder imo.

This saves a few chars but it makes syntax and parsing more complicated and doesn't add new functionality like typed arrays for example

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
