### ISSUE TITLE
Redesign how user interface (Controls) scaling  is presented to the user

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-proposals#2841]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Users often complain that sizing controls (user interfaces) in Godot is complex and very confusing. Too many properties and it's not obvious what each of them does. Among the properties there is a lot of redundancy so it can take a while to correctly understand what is going on.

That said, the user interface system is extremely powerful once you understand how it works, so the goal is not so much to change it but to change how information is presented to the user to make it less confusing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are currently 3 separate modes for user interface sizing and placement in Godot:

* Anchors
* Rect position and size, including rotation, scale, etc.
* Containers

![image](https://user-images.githubusercontent.com/6265307/121179541-423cc480-c836-11eb-9b50-8f45c9ee9d7f.png)

Each serves a different purpose and use case, but all are presented at the same time to users. That said, using all of them at the same time is generally not needed:

* When _containers_ are used (control is inside a container), _anchors_ and _pos/size_ are ignored.
* When using _anchors_, _position and size_ are ignored
* Even when using containers, the size flags exposed as well as the stretch ratio vary on their availability depending on the parent container.

The idea of this proposal is to hide what is not needed, and to also allow the user to specify better the kind of workflow desired.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The first step would be to move everything position related to the top of the list, so the properties are not mixed up with other, unrelated ones.

##### Containers

The following changes will take place in the inspector:

* "Size Flags" section will be renamed to "Container Sizing"
*  In this section, the parent container will be asked for which flags are supported (not all support expand, not always in both vertical and horizontal direction, and not all support stretch ratios).
*  If the parent to a node being edited is a container, the "Positioning" (anchors/position/size/transform properties) will be hidden, as they are unused in this workflow. Only "Container Sizing" will be visible and shown on top.
* "Minimum Size" will be moved to its own section, as its useful for both operation modes (container and regular position) and will appear as second section below "Container Sizing" or "Positioning".

![image](https://user-images.githubusercontent.com/6265307/121184079-1b34c180-c83b-11eb-837b-8d4627bf5d62.png)

##### Positioning

All positioning related properties will be put in a larger section "Positioning". Also moved to the top. When containers are used this section goes hidden, so on top of the inspector either this or containers will be there.

_Positioning_ will have the following properties and subsections:

* *use_anchors*: Anchoring will be enabled only if this property is on. If enabled, the following sub-sections of "Positioning" will be visible:
   * Anchors
   * Margins
   Likewise, the "Rectangle" subsection (showing position and size) will be hidden if anchors are active. 
   By default, anchors will not be enabled. To use anchors, you will need to toggle them on.
   
![image](https://user-images.githubusercontent.com/6265307/121184825-d8bfb480-c83b-11eb-9a42-f854f369a821.png)

* If *use_anchors* is disabled, then the "Rectangle" subsection of "Positioning" will be shown. This displays position and size.
   
![image](https://user-images.githubusercontent.com/6265307/121185285-47047700-c83c-11eb-8597-7ff4eba8cdfc.png)

* a "Transform" subsection of "Positioning" will be always visible (And below either "Anchoring or Rectangle"), this will contain rotation, scale, pivot, etc.
* The Clip Content property will be moved to visibility because it does not belong here. Likely renamed to "Clip to Rect"

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible to do with script, should be core.

**Comment by groud** [comment]
I like the idea, I definitely think the positioning properties should be hidden if children of a container. As said on IRC, my main concern is about the Layout menu (which is used often), made dependent on something in the inspector. We can either activate the "use_anchors" bool automatically (but it's making the menu doing something behind your back), or disable the Layout menu is "use_anchors" is not activated, which is not great for discoverability and ease of use.

Instead, I propose to change the use_anchor bool to an enum with 3 modes, and move the layout options to one of those modes:
![better_control_inspector](https://user-images.githubusercontent.com/6093119/121189021-fb68c200-c869-11eb-80db-d0f809a42f13.png)
This would make things a more discoverable (as everything is in the same place), while not making things a lot more complex IMO.

**Comment by reduz** [comment]
@groud as mentioned on RC, I like the idea of making anchors an enum, but I would just have a single one that shows: Anchors: [Disabled,Custom,Preset1,Preset2,Preset3,etc]. If custom is selected you edit them (properties visible), otherwise the preset is used and the settings to edit them invisible.

**Comment by SilencedPerson** [comment]
I feel like the Anchor could be completely removed from the Control Nodes as value and made into separate Node by itself, usually you just need to set it up on only ONE node anyway.

While we are discussing the controls, could we please change rect_position, rect_size and similar values to just position,size ? I don't see the point of the current distinction, quite frankly it just messes up my code when tweening the UI.

**Comment by YeldhamDev** [comment]
As someone who does heavy UI work on my game, I dislike this idea. That are multiple times that I need to modify anchors, position, and size of `Control` nodes for some more complex UI.

**Comment by reduz** [comment]
@YeldhamDev Anchors and position/size are redundant so, while I understand that some very rare case you may need to do something strange, this change simplifies workflow for the vast majority of users, so the benefits outweight the cons. 

That said, feel free to explain how are you using it currently, and we can see if there is another way to do it (other than probably having to use a script, worst case).

**Comment by RandomShaper** [comment]
For those that want or somehow need to see all the properties, there can just be an editor setting (something like `always_show_all_layout_properties`, off by default).

**Comment by reduz** [comment]
@RandomShaper It could work, but first I think I need to convinced that the concern exposed by @YeldhamDev can't be solved in a different way, for which it would be useful to have an example of what he needs.

**Comment by reduz** [comment]
@RandomShaper @YeldhamDev I was thinking about it, and I think it will be easier to have a Custom + Rect setting in the anchor mode for the rare cases you need both. IMO that should solve the problem.

**Comment by groud** [comment]
> @RandomShaper @YeldhamDev I was thinking about it, and I think it will be easier to have a Custom + Rect setting in the anchor mode for the rare cases you need both. IMO that should solve the problem.

IMO, the "Custom" mode is likely going to be used so rarely that we could simply display position and size too in that mode. it would be kind of a "power user" mode.

**Comment by YeldhamDev** [comment]
@reduz This is a response for the use cases that you asked previously:

---

### Specific Margins for Specific Elements

Complex UI can have a lot of controls that need to be in certain places along the screen, while still following certain corner sides. Of course, margins still need to be applied for those.

> Just use `MarginContainer` then?

That can be used, but it creates other problems:
- As elements can have different margins and be in different layers, you will end up having to place various `MarginContainer` nodes, resulting in a quick pollution of the scene tree.
- If said control elements need to be animated (e.g. entering the screen), those containers start to become a hustle and another thing to keep attention when animating.

### Visuals and Animations

Place take a look at the GIF below:

![Peek 2021-06-08 12-31](https://user-images.githubusercontent.com/30739239/121217416-5baf3200-c871-11eb-8a0c-5e059cf7d8d2.gif)

Besides having some of the elements that I discussed above, the main focus here are the gates that animated during the transition. While their vertical position is animated, their horizontal size is anchored to hug both ends. Having the position and size being available while still anchored made the process much more easier.

Could it also be done without it? Probably, but it would've required much more work to achieve the same results. Keep in mind that animation wasn't even as complex as you can see in some game UIs.

**Comment by theraot** [comment]
I'll remind people that while you should not use position to place controls in a container, position can be still useful for animation purposes. Thus, for people trying to use AnimationPlayer to animate controls having position related properties hidden (or uneditable) in the inspector panel could be hurdle.

Perhaps that's good? Straight up using an AnimationPlayer to animate a control in a container is rarely what to do, because the control should leave the control where the container wants it to be. Instead:

- Add another container between the control and the its container, so the AnimationPlayer can move the control relative to the inner container, which would be relative to the position the outer container wants it to be.
- Edit the coordinates of the AnimationPlayer from a script to make sure it ends where the containers wants the control to be.
- Use a Tween from script so you can make sure the animation ends where the container wants the control to be.
- Just move from script, and again, make sure the control ends up where the container wants the control to be.

*Personally, I prefer to use Tweens for this purpose. Thus, this is not a problem for me.  As far as I'm concerned pushing people into not using AnimationPlayer to move controls is a good thing, but that is only my opinion. I'm aware that the motion that Tweens provide is limited in comparison to what you can do with an AnimationPlayer, thus there can be legitimate cases for using AnimationPlayer to move controls.*

**Comment by YeldhamDev** [comment]
@theraot The problem of doing such things with a `Tween` instead with the `AnimationPlayer` is the lack of direct preview. With the latter, you can see the results on the spot, while former you will need to open the game, navigate to the specific spot that the animation plays, and then you will be able to see it.

**Comment by reduz** [comment]
@YeldhamDev yeah I see, i guess in some situations you want to animate just from the position. I think as @groud says, the custom mode can probably include position + size too, it wont hurt.

**Comment by pycbouh** [comment]
@YeldhamDev @reduz If the use case here is animation, does it matter what "mode" is selected in the Inspector? All properties are still accessible for the animation, and if they can be edited in code, they can be animated. Now if this proposal would affect what properties you can select in the animation editor, then it would present a problem. But otherwise... Or do you use keying from the inspector, @YeldhamDev?

**Comment by YeldhamDev** [comment]
@pycbouh Being able to modify the position/size directly from the 2D editor is an immense time saver when making UI animations. As I said before, it would still be possible to do it without that, but it would be much more difficult.

**Comment by eon-s** [comment]
Maybe when the animation player is shown with keys enabled on the inspector, the full view can be active by default (I think that this type of _views_ can be useful on other types of nodes too).

**Comment by ArjunNair** [comment]
> @markopolojorgensen Disabled properties add clutter and are still confusing. I prefer to think of workflows where users need something and go look for it, and you try to make it as easy as possible to find it.

I too think completely hiding it can cause confusion for new users. Especially, if changing a seemingly harmless property causes a large swatch of options to appear or disappear out of the blue. What about disabling and collapsing said properties with an alert indicator (such as that is used in nodes in the scene window to call attention) next to the label. Hovering over the alert indicator would pop up an info box (just like it does for, say, an Area2D with no Collider2D node) telling the user why the property is disabled. Eg: "Positioning is determined by the parent container and cannot be modified". 

That way the user cannot edit properties which have no effect anyway, but at the same time they also know why a particular property is showing up that way. The proposal for collating and renaming some of the properties still applies though.

**Comment by aaronfranke** [comment]
@reduz What do you think about this kinda-related proposal? In addition to only showing the relevant properties in the inspector, it would be nice if SizeFlags was more intuitive and fewer combinations were invalid. #299

**Comment by golddotasksquestions** [comment]
This Proposal is a vital improvement, one I have been desperately waiting for ever since I've discovered Godot years ago! The new structure proposed here makes a lot more sense compared to what we have right now.

However I agree with others, removing properties completely without indication can be just as disorienting and confusing for beginners and intermediate users. Blender does this too and it is horrible. There are so many situations when you know what to look for, you know where to look for it, but you can't find it, just because it is removed without notice and you would have to click some other thing first to make it appear.

Unfortunately Godot has it's fair share of these already (bottom panel and toolbar for example). If this expands onto the Inspector, I can already see the community channels filled with "where is property X?" questions.

It hurts discoverability and the learning process. Maybe there is a way to compromise by automatically collapsing but keeping the greyed out property category. Then if a user tries to expand the collapsed property category, they see the properties greyed out as well (but can still see them - which is important for designing UI). A single line warning underneath explaining what's going on, with a slightly more in depth explanation in the tool tip when hovering above the greyed out properties or warning ⚠️:

![image](https://user-images.githubusercontent.com/47016402/121748902-12c5da80-cb0a-11eb-97ac-0f714f77e34d.png)

There is one more thing that has caused me countless sleepless nights, which is the rect Pivot Offset property. I can't find any info in this proposal what would happen with this property. The way this property currently works really absurdly backwards and extremely counter intuitive. It would be nice if there would be a more intuitive option. Personally I would prefer to be able to position the origin directly, see https://github.com/godotengine/godot-proposals/issues/129

**Comment by vybr** [comment]
I just don't see why there is a choice between using anchors and position/size in the first place as they aren't mutually exclusive properties. I have never used a UI prototyping tool that made users choose between positions/size and anchors. If I have a button anchored to the bottom of a panel I should be able to move it either in the editor or with an animation without needing to enable another option.
I can see people suggesting an "Advanced" option but if we're discussing UX:
- Will users know what "Advanced" means? 
- For users who use these options together a lot already, why add an extra step? 
- Are we sure users are even being confused by anchors and position/size specifically?

**Comment by Killfrra** [comment]
- I like the idea of turning off fields non-supported by container from the "size flags" / "container flags" section.
- I'm not sure if we need the flags separately for vertical and horizontal, but if we do, I think it would be logical to have two "stretch ratio" fields immediately under the corresponding "expand" flag, to visually emphasize that without the flag enabled, they do not affect the size of the element.
- It also probably makes sense to replace two flags "shrink to center" and "shrink to end" with one drop-down menu, similar to "align" with the initial value "start" / "left" / "top", because I have not yet seen a container that would be affected by both of these flags set at the same time

This is how I imagine an inspector view for a node inside a container that supports all size flags:
![Screenshot_20210613_205301_edited](https://user-images.githubusercontent.com/15277964/121818235-715b9780-cc75-11eb-887d-829de15d3b68.png)

**Comment by pycbouh** [comment]
> It also probably makes sense to replace two flags "shrink to center" and "shrink to end" with one drop-down menu, similar to "align" with the initial value "start" / "left" / "top", because I have not yet seen a container that would be affected by both of these flags set at the same time

The problem is, they don't mix with Fill and Expand or Fill+Expand. Aaron's #299 is much better in that regard. As for two stretch ratios, it makes sense. I think that we only have one because it only affects BoxContainers and SplitContainers which can only go in one direction. So it does cover all the cases for the built-in containers, but it may be useful to have two of them for custom containers, I guess.

**Comment by Zireael07** [comment]
>  which is the rect Pivot Offset property. I can't find any info in this proposal what would happen with this property, even though it affects positioning greatly

Seconded - I use pivot offset in my projects because rotating from the top left corner is usually NOT what I want. 

Since the most common rotation people want is from the center, maybe instead of (indeed often confusing) pivot offset we could get an enum (each of the corners + center)?

**Comment by pycbouh** [comment]
Just letting everyone know that I'm working on implementing this proposal. 🙃

**Comment by Feniks-Gaming** [comment]
Do you hope this will make it to 4.0 or are we looking past that 4.1

**Comment by pycbouh** [comment]
> Do you hope this will make it to 4.0 or are we looking past that 4.1

This is not going me to take a year, so yeah, safe to assume it's a part of 4.0. It may even get to 3.x in some way, because a lot can be done just from the organizational standpoint, without breaking compat whatsoever.

**Comment by SoloByte** [comment]
As an example when rect properties are useful to see even though the node itself is a child of a container would be the rect_scale. I regularly animate the rect_scale property even though the general layout is dictated by containers to make certain things "pop" when selected/hovered over etc.


https://user-images.githubusercontent.com/34277803/141155970-cd05ee37-e1ab-43a0-bc89-667fd9c064ca.mp4

The buttons are in a VBoxContainer, the class panel is in VBoxContainer with the prev/next input panels and the items are in a grid container, and all of them use an animated rect_scale.


As a side note because of animating the rect_scale regularly AND using containers the current implementation of the **rect_pivot_offset** is pretty much useless for me. Using containers makes everything very flexible and therefore I never really know the rect_size of my UI nodes in advance. Because of all of this, it is hard to put the origin where I need it for my animations with the current system. 
For instance, animating the stretch_ratio of a node inside a container changes the size of all other nodes dynamically (as it should) but that also means I can not really use the rect_pivot_offset for all the affected nodes, rendering rotation/scaling useless.

Making the rect_pivot_offset relative instead of absolute (between 0 - 1 for instance) would make it much easier to work with. Maybe the absolute value is still better in some situations but as far as I can remember I never needed it.

I hope this helps somewhat ;)

**Comment by pycbouh** [comment]
@SoloByte That's a nice example. I think you wouldn't be able to do that same thing in `master` already, because we disable scale for children of containers (because containers reset the scale to (1, 1). I works for you because container is not aware of the changes you make during an animation and doesn't correct its children. I think you would need to use an intermediate control to achieve that effect without breaking the container logic, even for a split second animation.

**Comment by Calinou** [comment]
> because we disable scale for children of containers (because containers reset the scale to (1, 1) rendering the property useless by default).

Setting the scale at run-time should still work, it's just no longer exposed in the editor IIRC.

**Comment by pycbouh** [comment]
> Setting the Control scale at run-time should still work, it's just no longer exposed in the editor IIRC.

Yes, you can of course change it with code. But you may want to set up animations using the editor GUI 😉

**Comment by pycbouh** [comment]
I've submitted my work as https://github.com/godotengine/godot/pull/55157. Please give it a try if you can. Whether you like what it looks like on clips or not, an actual hands-on test is very very valuable!

I've tried to explain the rationale regarding particular implementation details in the OP there as well, in case it doesn't meet the user experience you were looking for.
