### ISSUE TITLE
Implement exporting Snaps from the editor

### ISSUE THREAD

**Issue by JUNZ1** [godotengine/godot-proposals#2842]
### Describe the project you are working on
Developing action game for Ubuntu Snap Store
### Describe the problem or limitation you are having in your project
I can not export project with snap format
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Ubuntu created a new software market called Snap Store, which is a growing market. That market is targeted as a main software  store for the future. For the moment Godot Engine has no capability for this export type.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Snap can be developed by using C++
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I dont think so.
### Is there a reason why this should be core and not an add-on in the asset library?
Exporting is a core functionality, i dont think that this can be add-on

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-docs/issues/2993.

I think this is better left to documentation, since relatively few people wish to export Flatpaks/Snaps directly from Godot. Generally, people want to be able to distribute their projects on itch.io, Steam, etc, and that means using a "direct" Linux export.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and overall lack of comments).

If you feel that creating Snaps for Godot projects should be documented, open an issue on the [godot-docs](https://github.com/godotengine/godot-docs) repository. However, this may be considered a [tutorial that isn't a good fit for the official documentation](https://github.com/godotengine/godot-docs/issues/3390) now.
