### ISSUE TITLE
Automatically select rename when creating a new node

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot-proposals#2850]
Alternative proposal to https://github.com/godotengine/godot-proposals/issues/1686
### Describe the project you are working on
A game with nodes
### Describe the problem or limitation you are having in your project
Most of the time after I create a node I want to rename it. 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I just barely found out you can press <kbd>Enter</kbd> to do this (I knew you could use <kbd>F2</kbd>, but that's less convenient), but I think it'd make sense if the rename lineedit showed up as soon created a new node (and if the user just wants to keep the default name they just click away). <kbd>Enter</kbd>/<kbd>F2</kbd> also doesn't work after creating a new scene because the `Scene` dock isn't selected (if you `2D Scene`/`3D Scene`/`User Interface` buttons).
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://user-images.githubusercontent.com/50304111/121568339-d779bd80-c9dc-11eb-8e93-b5bec5ef79e5.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think it could probably be implemented as a plugin with a few lines of script, but it's not convenient
### Is there a reason why this should be core and not an add-on in the asset library?
I think it'd be useful for all kinds of projects

**Comment by mrjustaguy** [comment]
Add as Editor Setting please

**Comment by Calinou** [comment]
My only issue with doing this is that pressing <kbd>Ctrl + A</kbd> will no longer cause the Create New Node dialog to appear just after creating a node. Instead, all the node's text will be selected.

**Comment by SilencedPerson** [comment]
@Calinou We could change it to Shift+A to have it work like in Blender. That would solve that problem and fix muscle memory of users that use both softwares.

**Comment by Calinou** [comment]
> @Calinou We could change it to Shift+A to have it work like in Blender. That would solve that problem and fix muscle memory of users that use both softwares.

But <kbd>Shift + A</kbd> is how you write an uppercase "A" character in the first place…

**Comment by dsnopek** [comment]
I currently use the Ctrl-A then Enter method to rename. I guess this proposal would reverse that? It would mean that Ctrl-A would add and rename, then I'd have to do Ctrl-A then Enter to _not_ rename.

I'm not sure which of the two operations is more common, but it'd be very annoying re-adjusting my brain to flip this around.

**Comment by LightningAA** [comment]
> I currently use the Ctrl-A then Enter method to rename. I guess this proposal would reverse that? It would mean that Ctrl-A would add and rename, then I'd have to do Ctrl-A then Enter to _not_ rename.
> 
> I'm not sure which of the two operations is more common, but it'd be very annoying re-adjusting my brain to flip this around.

Yes that is correct, I guess we should either try and figure out which situation is more common, or add an editor setting for this (I'm not sure it's worth an editor setting though). To me it makes sense to name a node before adding more nodes, but maybe some people like to go through and name their nodes after they've added them, or just leave them with the default names

**Comment by me2beats** [comment]
This would be useful, but could it be optional?
When making fast prototypes I wouldn't like to press `Esc` every time to leave the node name as is.

**Comment by LightningAA** [comment]
> I wouldn't like to press `Esc` every time to leave the node name as is.

You can press <kbd>Enter</kbd> instead

**Comment by dsnopek** [comment]
> To me it makes sense to name a node before adding more nodes, but maybe some people like to go through and name their nodes after they've added them, or just leave them with the default names

I frequently add and then duplicate a bunch of times, then rename the resulting nodes. So, like Ctrl-A Ctrl-D Ctrl-D Ctrl-D and then arrow keys and enter to rename them. Or, the same but with Ctrl-I (instance a scene) then some duplicating and renaming. Is the proposal also going to affect Ctrl-I? For me, Ctrl-A and Ctrl-I fit in the same slot in my brain, so it'd be super weird if they behaved differently.

**Comment by LightningAA** [comment]
> Or, the same but with Ctrl-I (instance a scene)

[I thought it was <kbd>Ctrl+Shift+A</kbd>](https://github.com/godotengine/godot/pull/47530)?

**Comment by MaaaxiKing** [comment]
> My only issue with doing this is that pressing Ctrl + A will no longer cause the Create New Node dialog to appear just after creating a node. Instead, all the node's text will be selected. Unless we override the shortcut to work even if the node name is currently being edited, but I'd consider that to be bad UX as I expect Ctrl + A to always select all text in a text field.

Why not just <key>Ctrl</key>+<key>N</key> for "New"? I'd find it good, regardless whether this proposal will be implemented,

**Comment by golddotasksquestions** [comment]
I don't think I would like this, if it would be the default. In most cases I only need to give a few nodes in a scene a custom name. More often than not, I only give the top most node has a custom name.

Even if this would mean I would just have to press Enter, it's yet an additional step every time. Calinou also has a valid point. Without the rename prompt it is right now is also more beginner friendly I think. It's not necessary to specify a name to make a working scene. 

For experienced users who like to rename every node, I think as an **opt-in** Editor Setting it would be a great thing to have though.

**Comment by LightningAA** [comment]
@golddotasksquestions Those are some really good points. I like the idea of automatically doing it for just the first node of a new scene (a lot of times I don't rename colliders etc.), and also I think the editor shortcut should maybe say <kbd>Enter</kbd> instead of <kbd>F2/<kbd>, because the former is more convenient (and I wish I'd known about it sooner 😄).

**Comment by golddotasksquestions** [comment]
I'd rather not have Enter being used for anything other then confirmation of a choice (after you typed in a value) or line break in a script. 

If you want to change the name of a node now, you can already simply double click it. This seems a lot more convenient than Enter as you will in most cases move your mouse and click once to select the node you want to rename anyway.

This way you also don't accidentally "write" into a node name field because you overlooked the Scene Panel still being active window.

**Comment by LightningAA** [comment]
1. You already can use enter to rename a node, that's not what I was proposing
2. I disagree with the removing the <kbd>Enter</kbd> shortcut in favor of double clicking. To create a new node, I usually use <kbd>Ctrl + A</kbd>, search for the node I want, hit enter to add it. I would much rather just hit <kbd>Enter</kbd> again and start typing the node's new name, rather than having to move my right hand to mouse, move the mouse over to the node I've just created, left click twice, move my right hand back to the keyboard and type the node's new name.

**Comment by Sosasees** [comment]
What if, instead of Godot automatically pressing the "Rename" button for you,
there would be a second LineEdit in the "Create New Node" window
for giving the node an optional custom name?

This way, you could press Tab right after having typed the Node Type
to give the node a custom name if you want.

This would be good reguardless of how often you give nodes a custom name:
Whenever you want to have a custom-named node, you could use this function to work faster,
and whenever you don't, you can just ignore this LineEdit and add the node "the old way".

**Comment by LightningAA** [comment]
@Sosasees that's exactly what https://github.com/godotengine/godot-proposals/issues/1686 proposes. In my opinion I think that's overcomplicating things, I think pressing <kbd>F2</kbd> or <kbd>Enter</kbd> is just as effective.

**Comment by golddotasksquestions** [comment]
@LightningAA 

> I would much rather just hit Enter again and start typing the node's new name,

But apparently you already can do exactly that.

**Comment by LightningAA** [comment]
@golddotasksquestions yes you can. After your comment and the discussion in this proposal I'm no longer in favor of automatically selecting rename after creating any node, just when creating a new scene. You were saying you wished <kbd>Enter</kbd> was not an option for renaming nodes, and I was explaining why I disagreed with that.

**Comment by Sosasees** [comment]
@LightningAA Yes, how things are right now
is much more elegant.

**Comment by dsnopek** [comment]
>> Or, the same but with Ctrl-I (instance a scene)
>
> I thought it was Ctrl+Shift+A?

Oops, sorry, I must have customized that at some point. :-)

**Comment by AaronRecord** [comment]
Closing, I think https://github.com/godotengine/godot/pull/49521 + the fact that you can use <kbd>Enter</kbd> key to rename nodes, is a better solution, hitting the enter key takes almost no time, and there are often times where I think it's fine to leave node names as their default. I also feel https://github.com/godotengine/godot-proposals/issues/1686 could be closed, but maybe someone else feels otherwise ¯\\_(ツ)_/¯
