### ISSUE TITLE
Rename `class_name` to `class` and `class` to `inner class`

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2865]
### Describe the project you are working on
Games
### Describe the problem or limitation you are having in your project
In Godot 3, the way you declare classes isn't as intuitive as it probably could be (at least in my opinion, coming from other languages). If I asked a programmer who wasn't familiar with GDScript what the difference between `class` and `class_name` was, they probably wouldn't be able to guess. Of course these things can be taught, but we should still strive to name things as intuitively as possible.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
```
class_name -> class
class -> inner class
# or if an annotation would make more sense
class -> @inner class
```
Inner classes would probably no longer be indented, like normal classes.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```gdscript
# path_finder.gd
class Pathfinder extends Node

static func pathfind() -> Array[Segment]:
    # do all the pathfinding


inner class Segment extends Reference
var position: Vector2i
var travel_cost := 1.0
```
Usage of inner classes from other scripts is the same:
```gdscript
# other_script.gd
var path: Array[Pathfinder.Segment] = Pathfinder.pathfind()
```
Every `.gd` would be required to have one class, and inner classes would be scoped to whatever class they share a file with.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.
### Is there a reason why this should be core and not an add-on in the asset library?
GDScript is core.

**Comment by Calinou** [comment]
> I suggest removing inner classes, as having 2 implementations of classes is unnecessary, confusing and more bug prone.

Inner classes are useful to create internal data types without relying on non-type-safe Dictionaries.

**Comment by LightningAA** [comment]
> Also, what would happen if you define multiple classes that extend a Node class? Which node's _ready() would be executed?

Fair point... Maybe only one class that extends `Node` should be allowed per file?

**Comment by LightningAA** [comment]
> Inner classes are useful to create data types scoped to a script without relying on non-type-safe Dictionaries. Unlike Dictionaries, you get autocompletion and compile-time errors by using custom subclasses as data types.

What about a syntax like
```gdscript
inner class PathfindNode
...
```

**Comment by dalexeev** [comment]
> I don't see why `preload(*.gd)` is useful anymore since `class_name` was added, although if it's still useful to you please let me know why.

This can be useful if you don't want to register a global class. For example:

```gdscript
var config := preload("config.gd").new()
```

**Comment by dalexeev** [comment]
#209
#1208
#1842
#2612
#2865

**Comment by Xrayez** [comment]
> I don't see why `preload(*.gd)` is useful anymore since `class_name` was added, although if it's still useful to you please let me know why.

Classes that have `class_name` are registered in `project.godot` as well. If you have hundreds of them, it will bloat `project.godot` (if you don't always use UI to edit project settings). There are also known performance issues with having global classes: godotengine/godot#39841 (which *can* be fixed, but this already shows that this kind of approach is prone to negatively affect other aspects of development).

**Comment by LightningAA** [comment]
> Classes that have `class_name` are registered in `project.godot` as well. If you have hundreds of them, it will bloat `project.godot` (if you don't always use UI to edit project settings). There are also known performance issues with having global classes: [godotengine/godot#39841](https://github.com/godotengine/godot/issues/39841) (which _can_ be fixed, but this already shows that this kind of approach is prone to negatively affect other aspects of development).

While that is a valid point for why `preload(*.gd)` might currently be used, I don't think that's a good reason for why is should stick around. No language I've used has required me to manually enter in the path to a script file to access it's class because it's inconvenient. Maybe the implementation details of `class_name` needs to be reconsidered, but `class_name` is more intuitive and convenient (at least in my opinion).

**Comment by pycbouh** [comment]
@LightningAA `preload()` is unrelated to scripts. It's a generic mechanism for all resources. It will stay a part of the API regardless of the type system in GDScript.

**Comment by LightningAA** [comment]
@pycbouh yes I know :), I was suggesting removing preloading `.gd` files as I didn't see why it was necessary anymore. I don't really care if preloading `.gd` files stays, it was just a suggestion.

**Comment by dsnopek** [comment]
> While that is a valid point for why preload(*.gd) might currently be used, I don't think that's a good reason for why is should stick around. No language I've used has required me to manually enter in the path to a script file to access it's class, because it's inconvenient. Maybe the implementation details of class_name needs to be reconsidered, but class_name is more intuitive and convenient than preload(*.gd) (at least in my opinion).

I avoid using `class_name` except when absolutely necessary because we don't have namespaces in GDScript. If I use `class_name` too liberally, I end up wasting a ton of time (like, hours in total over the life of a project) naming and renaming things as conflicts arise. I like using `preload()` because I can sort my scripts into folders and the path allows me to have a kind of nested namespace.

So, as things are, I definitely don't want `preload()` to go away. But if GDScript had nested namespaces, then I'd be _almost_ entirely on-board.

I say "almost" because I also sometimes make custom `Resource` sub-classes that have 1 or more scripts as exported variables. And, if I want to have a default value for those variables (let's say for a default behavior that is only overridden rarely), then `preload()` is needed to set the default value.

**Comment by pycbouh** [comment]
> I was suggesting removing preloading `.gd` files as I didn't see why it was necessary anymore. I don't really care if preloading `.gd` files stays though, it was just a suggestion.

Well, I just don't see how this can be implemented? We just disable preloading of a particular type of resource in core? That would introduce weird and unexpected behavior as all other resources could still be preloaded, an unnecessary edge-case. Would we throw? Should `load()` still work? I'm just confused as to what exactly are you suggesting we "remove" as there is nothing added specifically for scripts. 🙃 

All we can do is recommend not using it with scripts in our guidelines, but even then there are actual use-cases for it (namely, not polluting the global namespace or replacing `load`s with a more strict dependency).

**Comment by LightningAA** [comment]
@pycbouh I was assuming specific logic had been added to load GDScripts, as this is not the case then yes I agree, preload should stay even after namespaces/more optimized `class_name`.

**Comment by aaronfranke** [comment]
@LightningAA Many people use inner classes, so they shouldn't be removed. I assume that most of the :-1: are from when you originally posted that suggestion. If the proposal is just about renaming the keywords, I am 100% in favor, it would be much better than what we currently have in 3.x where the more-used option has the awkward `_name` suffix.

**Comment by LightningAA** [comment]
> If the proposal is just about renaming the keywords, I am 100% in favor, it would be much better than what we currently have in 3.x where the more-used option has the awkward `_name` suffix.

Yes that is exactly what this proposal is, although if I remember correctly most of the 👎 and 😕 were from after I'd already edited it to remove the part about removing inner classes, although not after I removed the part about removing preload.

**Comment by timothyqiu** [comment]
I think `class_name` makes sense because unlike other languages, every GDScript is implicitly an unnamed class.

* So we use `class_name Widget` to give that class a name.
* So a `class` inside a GDScript is a inner class.

I think the suggested `class` and `inner class` rename is a bit awkward becasue it gives user a false sense of being able to create a script without any class in it.

Also, if indentations are removed at that level, then it does not comply with the overall syntax rules about scope.

**Comment by dalexeev** [comment]
Please note that if we do not come to a consensus, then everything will remain as it is. Even if the current version is not perfect, people are at least used to it. The previous proposals are very similar, but they have not received unequivocal support either.

A few thoughts:

1. `class_name` occurs at most once in a script, `class` can appear many times. Therefore, it makes sense that the proposal to rename `class` to `inner class` does not get support.
2. We cannot remove the inner classes, because that will annoy those who use them.
3. We could rename `class_name` to `global class`, but what does that do? I remember someone saying that underscores in a keyword are ugly, but is that a significant argument?
4. There are important differences between these keywords. `class_name` gives the global name to the current script, which itself is an unnamed class. `class` declares a class. Therefore, we shouldn't use the same keyword for these two cases or confusing syntax like the `@inner` annotation.
5. GDScript is somewhat different from other languages in that you can put multiple classes in a single file (although this is generally not recommended). There can be only one main class in a `.gd` file.

**Comment by hilfazer** [comment]
> the way you declare classes isn't as intuitive as it probably could be (at least in my opinion, coming from other languages)


If coming from other languages is important then we could use the opportunity to rethink naming of "inner" classes. There are inner classes in Java and Kotlin but... they are different than what GDScript has. If i'm not mistaken Java's static nested classes are what GDScript's inner classes are.

What languages have inner classes that work like GDScript's inner classes?

**Comment by dalexeev** [comment]
I would venture to suggest this option:

```gdscript
class InnerClass1 extends Reference:
    pass

@global("MyGlobalClass1")
class InnerClass2 extends Reference:
    pass

@global("MyGlobalClass2")
@icon("my_global_class_2.png")
extends Node

var a = 42

func _ready():
    print(a)
```

**Comment by timothyqiu** [comment]
> What languages have inner classes that work like GDScript's inner classes?

C++ and Python, for example. I think the "inner class" of JVM languages is kind of a special case, most other languages use "inner class" interchangeably with "nested class".

**Comment by Shadowblitz16** [comment]
What we should do is treat remove class_name because it represents two different functionalities.
- It registers the node as a global type
- It registers the node in the node creation dialog

1 could be achieved with a option `:` at the end or allowing multiple node's in one file
2 could be achieved with a keyword in 3.0 and a annotation in 4.0

This is how most other oop languages would do it.
It also gets rid of ambiguity.

```
@register_node
class MyNode extends Node
...

class MyClass:
    ...

``` 

or...

```
@register_node
class MyNodeA extends Node:
    ...

@register_node
class MyNodeB extends Node:
    ...

class MyClass:
    ...
...
```

I personally find the latter easier to understand the problem is some people don't like the extra indent and we need to figure out what class you use for logic.

**Comment by pycbouh** [comment]
> I don't have to even extend anything because it automatically extends Object

@filipworksdev It extends Reference. 🙃
