### ISSUE TITLE
Add increment and decrement operators to GDScript (`++`/`--`)

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2869]
### Describe the project you are working on
Any
### Describe the problem or limitation you are having in your project
I need more characters to increment a number by 1 than in other languages
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
You could in-/decrement a number (that means also floats, which is unfortunately not supported in Java or C# and I'm sure many others) more easily
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just like in Java or C# or whatever language: `++`/`--`
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it's just a super tiny thing to implement

**Comment by pycbouh** [comment]
> Yes, it's just a super tiny thing to implement

Not really. This syntax creates a lot of ambiguity for the parser, which was the stated reason by @vnen why it doesn't exist in GDScript. You can already do the same with `x += 1`, which is not that more complex.

**Comment by Calinou** [comment]
This was discussed a long time ago in https://github.com/godotengine/godot/issues/1107 and was rejected.

**Comment by MaaaxiKing** [comment]
I'd neever use "`i+=1`" xD; a lack of whitespaces is a no-go! I'm a bit disappointed about the rejection but not really having a problem with it since I'm starting to switch to C# anyways—do you recommend this when having good experience in both languages?—just wanted to improve the language a bit. A difficulty with implementing is unforeseen for me, but OK, I can't change that.
I feel the linter to be grumping too much, they're about equally good.

**Comment by dalexeev** [comment]
`i++` is like `goto` in the expression world, only much worse. 

1. Unlike other operators, increment and decrement work not on values, but on variables.
2. Increment and decrement violate the order in which the expression is evaluated.

![](https://user-images.githubusercontent.com/47700418/122164595-b6ebb080-ce7f-11eb-8317-54d681f07f63.png)

We should not blindly copy such "convenient" shortcuts. It is better to type 2 clear lines than 1 confusing one.

`i += 1` is

1. short enough (no duplication of information as in case `i = i + 1`);
2. clear enough (increase `i` by `1`);
3. versatile enough (you can write `i += 2` or `i += x`).

**Comment by MaaaxiKing** [comment]
Normally, it is not `y = i++ + 1;` but `y = ++i + 1;`!

**Comment by pycbouh** [comment]
Those two variants do different things and also demonstrate perfectly ambiguity for the parser.

What's the order of `a + + + b`?

**Comment by MaaaxiKing** [comment]
I thought, `+ +`—and therefore also `+ + + `—doesn't even work, does it?

**Comment by pycbouh** [comment]
That was not the point, I've added spaces for demonstration purposes. You can write it as `a+++b` if you want.

**Comment by MaaaxiKing** [comment]
With `a = 1`, `b = 6` and `c = a+++b`, `c` should be `(a)+(++b)` and that's (1) + (1 + 6), which is 8. `a` and also `b` should stay the same.
In C# and Java however, `c` is 7 (bad), `a` is 2 (bad), b stays the same (fine), which is in total absolutely terrible because in **an** assignment, not two things should happen!

**Comment by pycbouh** [comment]
And so you've seen why it is a terrible operator 🙃 

The results are expected though, it is treated as `a++ + b`, which means "use a as it is with b, then increment a". So `c = 7, a = 2` is definitely correct. But it's not obvious from the written code, is it?

**Comment by MaaaxiKing** [comment]
I don't find it is a bad operator, it's just horribly implemented. I can now comprehend the rejection. I know that the result is expected but logically, it's the worst thing I've ever seen in programming because a two-in-one assignment is downright silly!
I'll close this now, but can I get an opinion about switching to C#? I'd never use `int c = a+++b` anyways.

**Comment by Xrayez** [comment]
Well, I code in C++ as much as in GDScript, and I treat GDScript as a lightweight version of C++ (however weird that may sound). As a C++ developer, I'd find increment/decrement operators to be natural in GDScript.

**Comment by Xrayez** [comment]
I'm reopening this proposal because #2894 popped up as well. @vnen is the only one in authority who can formally close this proposal to reflect his final decision, not moderators, sorry.

**Comment by Joakker** [comment]
Why not just have it be a statement? Go does increment like that

```gdscript

var e = 0

func incE1():
    e++ # Valid

func incE2():
    print(e++) # Invalid, expect expression
```

You could make it a prefix so it's easier to distinguish

```gdscript
func incE3():
    ++e # Same as incE1
```

**Comment by pycbouh** [comment]
@Joakker That may solve the ambiguity for the reader, yes. Not sure if it's easier to implement or not.

That said, people coming from other languages would expect your second example to work as well, so we may still have unsatisfied users asking for this to be possible. This also limits this syntax a lot, making it even less useful when you can already do the `+=1` thing.

**Comment by dalexeev** [comment]
Seriously? Complicate the GDScript parser just to save 1-3 characters? In the next step there will be people who will ask to make the increment/decrement behavior complete, the same as in C, C++, JavaScript, PHP, etc.

**Comment by vnen** [comment]
> Why not just have it be a statement? Go does increment like that

The main point of it is to use in an expression. If you only use in a statement, there's not much difference from `x += 1`.

Also, the main point of this operator in the C-family languages is to use in a `for` loop (and similar constructs). In GDScript you do a `for`  loop without having to increment it manually so it's not as important (the same happens in Python). I know GDScript is very C-like because its dependency in Godot, but I don't see this as enough reason to add everything that C has.

I would like to hear other arguments besides "it saves me a few characters" and "I'm used to this in other languages", since I don't think those are enough reasons to add one more complication to the language (not to mention it open the precedent for more complex additions for the same reasons). I think it hurts readability and add confusion. When someone says "people already know this from C-family languages", I feel they forget this trips a lot of beginners in those languages. So for all this I'm still against adding this.

**Comment by Xrayez** [comment]
> Also, the main point of this operator in the C-family languages is to use in a `for` loop (and similar constructs). In GDScript you do a `for` loop without having to increment it manually so it's not as important (the same happens in Python).

This may be connected to use case in #2727 (see my comment below).

I would much appreciate the ability to use `for` loop just like in C-family languages, because it avoids the need to use `while` constructs and needlessly initializing temporary local variables for that which pollute the scope. I find it quite unintuitive to use `range` for inverse loops (where `i--` would work better in my opinion), it's also quite costly because it would allocate an array of temporary values (the reason why `for i in x` construct was added).

Here's a real-life use case (code taken from my project):

```gdscript
	var chunks_generated = 0
	var dy = 0
	var dx = 0
	while dy < src_height:
		while dx < src_width:
			# Match source rect
			var chunk_rect = Rect2(dx, dy, chunk_width, chunk_height)
			chunk_rect = chunk_rect.clip(src_rect)

			# Copy chunk from source image
			var chunk = Image.new()
			chunk.create(chunk_width, chunk_height, false, terrain.get_format())
			chunk.blit_rect(terrain, chunk_rect, Vector2(0, 0))

			# ... same for mask, if specified
			var chunk_mask = null
			if using_mask:
				chunk_mask = Image.new()
				chunk_mask.create(chunk_width, chunk_height, false, mask.get_format())
				chunk_mask.blit_rect(mask, chunk_rect, Vector2(0, 0))

			# Make source chunk
			var shaper = Shaper.new()
			shaper.make_models_from_image(chunk, p_eps)

			# ... same for mask, if specified
			var shaper_mask = null
			if using_mask:
				shaper_mask = Shaper.new()
				shaper_mask.make_models_from_image(chunk_mask, p_eps)

			var offset = Vector2(dx, dy)

			for idx in shaper.get_model_count():

				var body = Scene.TerrainBody.instance()
				var model = shaper.get_model(idx)

				if using_mask:
					# Have to create an actual exception shapes
					var masker = Shaper.new()
					model.type = ShaperModel.ptSubject
					# by intersecting this source model:
					masker.add_model(model)
					# ... with mask model(s)
					for i in shaper_mask.get_model_count():
						var mask_model = shaper_mask.get_model(i)
						mask_model.type = ShaperModel.ptClip
						masker.add_model(mask_model)

					masker.make_models(Shaper.ctIntersection)

					# Finally, apply as exceptions
					var mask_models = []
					for i in masker.get_model_count():
						var mask_model = masker.get_model(i)
						mask_model.transform(Transform2D(0, offset))
						mask_models.push_back(mask_model)

					body.mask_models = mask_models

				# Apply source model
				model.transform(Transform2D(0, offset))
				body.model = model

				# Set other initial properties
				body.offset = offset
				body.size = map.cell_size
				body.texture = map.get_texture()
				body.normalmap = map.get_normalmap() if map.depth_enabled else null
				body.background_texture = map.get_texture()

				map.add_body(body)
				chunks_generated += 1

			dx += chunk_width

		dy += chunk_height
		dx = 0
	dy = 0
```

The problem here is that the initialization takes before loop, and I have to iterate `dx`, `dy` variables way below the loop body, and that lead me to errors in the past because of incorrectly indented statements. I also have to make sure to reset `dy = 0` on each row.

I cannot use `range()` here because the step is not based on integers, but actual chunk size. I *could* compute the number of x/y chunks and iterate over that, but that really makes C++ and GDScript even more inconsistent, and performance is quite important in my case.

That said, how about restricting `i++`/`i--` operators to `for` loops? Would that make it difficult to implement? Having `i += 1` and `i -= 1` work inside loops would also be sufficient if you insist on not adding `i++`/`i--` operators:

```gdscript
for i = 10; i > 0; i -= 1:
	for j = 0; j < 10; j += 1:
		print(i, j)
```

As far as I know, GDScript allows to use `;` to separate expressions like that.

I understand that this won't change anything but it would be wrong from my part not to mention this...

**Comment by MaaaxiKing** [comment]
Restrictions is not a good idea, in my view 😐.

**Comment by Xrayez** [comment]
> Restrictions is not a good idea, in my view 😐.

Restrictions are already part of GDScript btw. If you try to use `if x = something` (where `==` operator is usually expected), this will throw an error, unlike in C-family languages. I'm not saying that we should allow that, of course, but restriction are made specifically so that you can avoid those common human errors, and GDScript does apply those restrictions.

**Comment by Xrayez** [comment]
> I know GDScript is very C-like because its dependency in Godot, but I don't see this as enough reason to add everything that C has.

This could be a very strong reason if the initial design of GDScript was made to be compatible with the language Godot was written in (C++), and perhaps that was reduz philosophy as well. But obviously, the design decisions change with the maintainer (AFAIK, reduz no longer works on GDScript anymore). 🙂

**Comment by vnen** [comment]
> it's also quite costly because it would allocate an array of temporary values (the reason why `for i in <number>` construct was added), but it doesn't work inverse, nor allows to initialize variables to values other than `0`, so it's not a complete solution.

`range()` does not allocate an array when used in a `for` loop, as long as the values are constant. You can initialize to a value other than 0 since the function has three uses: `range(N)` for 0 to N-1, `range(initial, final)` for `initial` to `final-1` or `range(initial, final, increment)`. So you can set something other than `0` as the initial value.

But it seems this discussion has shifted from increment operator to a C-style `for` loop. The example code wouldn't benefit of the operators themselves since it's not incrementing by 1. This would need a different proposal. And I would argue the C-style loop wouldn't add a lot to readability, if anything.

For instance, this:

```gdscript
for i = 10; i > 0; i -= 1:
	for j = 0; j < 10; j += 1:
		print(i, j)
```

Looks to me like a lot of noise. Compare to the current way of doing this:

```gdscript
for i in range(10, 0, -1):
	for j in range(0, 10):
		print(i, j)
```

Which is much more straightforward to decode the loop information.

**Comment by MaaaxiKing** [comment]
I also find the easyness of the current for loops super.

**Comment by Xrayez** [comment]
> `range()` does not allocate an array when used in a `for` loop, as long as the values are constant

In most cases that I had to deal with, `for` loop values are not constant, unless I misinterpret the meaning of a constant value in GDScript.

> But it seems this discussion has shifted from increment operator to a C-style `for` loop.

As far as I know, we treat problems as first-class citizen when considering implementing something in Godot, so to speak. You said that:

> Also, the main point of this operator in the C-family languages is to use in a `for` loop (and similar constructs).

If the main point of increment/decrement operators is to solve those use cases in C-family languages, this *could* also be the case for GDScript. But since GDScript seems to solve this particular problem another way, and other syntaxes are not up for discussion, then yeah it does not make sense to have increment/decrement operators in GDScript, as you said. So what I've said is also on topic.

**Comment by Teashrock** [comment]
i = ++i + ++i

**Comment by akien-mga** [comment]
There seems to still be no consensus on this proposal and no compelling use case to sway the opinion towards implementing this.

As GDScript maintainer @vnen made it clear that it didn't support the feature (at least with the current arguments given), I'm personally also not in favor of this proposal which has been rejected several times in the past, and other maintainers who voiced their opinion don't seem to support it either. So closing, we do no plan to implement these operators.
