### ISSUE TITLE
Add more editor shortcuts

### ISSUE THREAD

**Issue by rudrrayan** [godotengine/godot-proposals#293]
**Describe the project you are working on:**
I am working on a 2d platformer featuring lighting and building mechanics.

**Describe the problem or limitation you are having in your project:**
certain shortcuts that do exist in most software such as a rename shortcut or to "change type" etc. do not exist on the Godot engine. When working on a project, such annoyances tend to build up and for speed programmers and users working against a deadline this is also an issue.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Introducing more shortcuts in different aspects of Godot greatly increases the flexibility and ease for beginners and professionals working on a certain project. It also opens new possibilities for people wanting to submit or create projects for game jams.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
<img width="960" alt="Godot Engine - Infeinermium (_) 09_12_2019 18_00_27" src="https://user-images.githubusercontent.com/47331292/70460409-283dec80-1aae-11ea-9a30-573d36b4b70b.png">

**Describe implementation detail for your proposal (in code), if possible:**
I do not have much experience with github or contributing to code, but i can say that this is quite an easy feature to implement. If other shortcuts could be implemented, performing an action when a certain combination of keys are pressed, surely adding a few more should not be difficult?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this enhancement could be altered or even removed in a settings tab

**Is there a reason why this should be core and not an add-on in the asset library?:**
having a few extra shortcuts SHOULD NOT be an addon. Firstly, it is such a principle mechanic, that it should not require the user to download. Alongside this, for people who are switching engines to Godot or wanting to rate and compare the engine with others, they should not have to go through the effort to download a mechanic like this.

**Comment by Calinou** [comment]
I'm not sure if <kbd>Ctrl + R</kbd> would be a good fit for renaming. <kbd>F2</kbd> is already used to switch to the 2D editor, so we can't use that either.

Any suggestions for the **Change Type** and **Make Scene Root** shortcuts?

**Comment by KoBeWi** [comment]
You can already rename nodes by pressing Enter.

btw, you can already add shortcuts for these actions in Editor Settings, no? They just don't have defaults.

**Comment by golddotasksquestions** [comment]
@Calinou 
> Any suggestions for the Change Type and Make Scene Root shortcuts?

Why not let OP set their own? I suppose OP did not know they could do so by go to Editor > Editor Settings > Shortcuts then type the command into the search field.
Neither did I know I could do this until another user told me so (possibly you Calinou or KoBeWi), I always just clicked RMB and saw some had shortcuts and other had not, and that was it. The Shortcut panel in the Editor settings is also really easy to miss. It also needed someone to point me there exactly for me to find it. Is this the case for you as well @rudrrayan ?

Personally I think it's actually a good thing that those less common things don't have predefined shortcuts but allow the user to set their preferred shortcut any time. 

I clearly remember when I started learning Maya and everything already had a predefined shortcut. Often I found those not intuitive or practical and tried to change them. But since pretty much every key combination was already taken, you were always confronted with a prompt asking: "This shortcut is already taken. Do you really want to set this shortcut and remove this other one?"
If you did, then of course the other functionality suddenly had no shortcut at all anymore. This meant I would have to "replace" those as well, which lead to a never ending cascade of shortcut changing. 
Even if you don't fall into this pit, the question "should I really change this shortcut and with it destroy another?" can be quite irritating. At least for me it was, because I was afraid I would have a harder time to follow tutorials, if I change too much. Yes there is the ability to reset to default shortcuts (not Godot), and yes some editors have the ability to export and import shortcuts settings (not Godot), but even if I had those options I became more apprehensive to improve my work environment to my needs because the Editor was filled to the brim with predefined shortcuts and I as a beginner did not know which are the important ones and which are not.

**Comment by Calinou** [comment]
This was implemented a while ago, closing. As of Godot 3.2.1, Rename, Change Type and Make Scene Root can all have shortcuts configured in the Editor Settings:

![image](https://user-images.githubusercontent.com/180032/85212761-46867e00-b356-11ea-915e-4dd1fa8e06f9.png)

![image](https://user-images.githubusercontent.com/180032/85212763-4e462280-b356-11ea-8c5a-25bb6b358c21.png)
