### ISSUE TITLE
Implement seeking in VideoPlayer

### ISSUE THREAD

**Issue by OpusManning** [godotengine/godot-proposals#2945]
### Describe the project you are working on
I'm working on an educational application that has various "panels" that contain mixed content.  Text, videos, graphics.  Students read these items, and often need to study them in great detail.

### Describe the problem or limitation you are having in your project
The VideoPlayer lacks a means to "scrub" the video with a slider.  It looks like you can start and stop the stream, but not much else.  

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I'd like to have a video player in Godot that essentially replicates the one included in the Chromium browser or even Firefox.  Perhaps a themeable video player?  I like the formats that the VideoPlayer currently supports.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
What I'd like is to be able to assign a video file to the player, give the dimensions of the video file, and it kind of "just works" by playing in a nice video interface.  I realize that it's reasonable that I put the interface together with the existing nodes, which would be absolutely fine with me because they are nice and work very well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
My understanding is that it can't be addressed with GD Script, as it is a C-level issue of the current code.  I believe that the attempt is to work with FFMPEG, and VP9, and the programming is low-level audio and video stream management.

### Is there a reason why this should be core and not an add-on in the asset library?
I honestly think it might be better in the asset library, although currently it is in the core.

**Comment by Calinou** [comment]
Video playback will eventually be moved out of core and into a [FFmpeg-based GDNative add-on](https://github.com/kidrigger/godot-videodecoder).

**Comment by hungrymonkey** [comment]
Yea, I manage to get a implementation working here below for ogg theora but upstream kinda broke their own play code. I would need to fix upstream code in order to make mine work.

If anyone wants an idea on how to implement ogg theora, I wrote a blog about it. I should had compare timestamps as 64 bit int instead of floats.

https://hungrymonkey.github.io/seeking-three-moving-windows-ogg-theora/

https://github.com/hungrymonkey/godot/tree/seek_theora

**Comment by OpusManning** [comment]
One thing I didn't realize is that [this repo](https://github.com/kidrigger/godot-videodecoder) is a GDNative add-on - I thought it was THE VideoPlayer class in Godot core.  Unfortunately, I'm too stupid to compile it.  I was thinking about this though: is there someone I can pay to complete the implementation?  Might be a delicate issue, but I'd be willing to throw some dirty cash at the problem...

**Comment by Calinou** [comment]
> I was thinking about this though: is there someone I can pay to complete the implementation? Might be a delicate issue, but I'd be willing to throw some dirty cash at the problem...

Implementing seeking in the core VideoPlayer isn't something that can be done quickly, and I doubt anyone has the skills required to do it anyway (*and* is available to do it).

**Comment by OpusManning** [comment]
I agree if you're talking about the core component (VideoPlayer class), but I'm referring to [this plugin](https://github.com/kidrigger/godot-videodecoder).  If we could get a quality plugin, I'd be willing to put down real cash for that, essentially completing the TODO list on the bottom of the project page...

**Comment by Calinou** [comment]
> I agree if you're talking about the core component (VideoPlayer class), but I'm referring to [this plugin](https://github.com/kidrigger/godot-videodecoder). If we could get a quality plugin, I'd be willing to put down real cash for that, essentially completing the TODO list on the bottom of the project page...

The videodecoder plugin seems to not be in a working state currently. As far as I know, it doesn't really have any active users.

**Comment by golddotasksquestions** [comment]
Can we have this proposal or https://github.com/godotengine/godot-proposals/issues/2602 reopend reopened?

I think it's vital to have seek for basic VideoPlayer functionality in my projects. This is also something that comes up regularly on community channels. I understand there is no one working on it and it might not be likely someone will because it's complicated or involves a lot of dependencies which the core team would rather want to see in an GDextension, but I still think it's important to have an open issue about it where people can express their need.

Having people making new proposals/issues every time and then closing them so a new issue is opened again later just spreads the discussion to multiple pages and demand is harder to keep track of.

Currently all other issues have been closed and lead here, like 
https://github.com/godotengine/godot/pull/47838, 
https://github.com/godotengine/godot/issues/14430
https://github.com/godotengine/godot-proposals/issues/2602

**Comment by Calinou** [comment]
Someone is working on support for seeking WebM videos in `3.x`: https://github.com/godotengine/godot/pull/57690

**Comment by golddotasksquestions** [comment]
@Calinou 

I strongly believe we should be allowed to discuss official addons on the official Godot Github pages. Getting people to sign up and participate in these discussions is difficult enough. Getting them signed up and participate on an explicitly unsuported private repo with almost no traffic to discuss someones unsupported private ideas, has almost no incentive.

If you think proposals is not the place for this, maybe we should have a separate godot/GDextensions repo going forward?
I think cutting out more and more core functionality to separate GDextensions is highly problematic if they are only officially supported in name, but can't be discussed on official channels.

**Comment by golddotasksquestions** [comment]
For those interested, there is a PR for webm seek() support: https://github.com/godotengine/godot/pull/57744
