### ISSUE TITLE
Hire a full time marketing representative

### ISSUE THREAD

**Issue by Pilvinen** [godotengine/godot-proposals#2956]
**Hire a full time marketing representative for the Godot organization.**

This person would call up and contact companies, organizations, advertisers, funds, etc. and **apply for grants and sponsorships** for the Godot project.

Getting some money from Patreon is a nice bonus and definitely helps the project, but it's nothing compared to ad/grant/sponsor money.

Right now Godot has a lot of traction and potential, and to keep that momentum going I feel it's important take some calculated risks such as hiring a marketing person - which to many might not feel like the right intuitive move and best use for the money - but:

"You have to spend some money to make some money."

Having a full time professional marketing rep on the team would help the Godot project to grow in long term and stay relevant and vital in a highly competitive market. As a consequence the project would have more financial stability, and could potentially employ more developers in the future.

Godot has currently strong enough presence in the market, and viable product and previous history with big grants that this is a realistic plan.

I also strongly feel this type of work is not something that one of current the team members should be doing part time. It should be delegated to a **_trained professional_** who can focus on it **full time** without having to worry about other organizational issues or burdens.

**Comment by Calinou** [comment]
In a perfect world, it would be possible to hire someone that:

- Has connections with the industry, which means having the right address book *and* being able to regularly meet up with people in real life. This tends to imply lots of traveling, or living in a large, tech-oriented city (with high cost of living). This means the salary required will be very high.
- Understands the open source ethos and avoids the typical pitfalls (remember Muse Group's acquisition of Audacity?).
- Is trustworthy enough to be handed this task of representing Godot to companies. See the [Governance](https://godotengine.org/governance) page on the Godot website for more information.

However, I am not convinced such a person exists. We cannot hire someone who has no experience dealing with Godot or open source software in general. Does Blender even have a person dedicated to finding grants?

**Comment by mrjustaguy** [comment]
There are only 2 People I've found when Looking at the Blender Foundation that MIGHT be filling that role. The Finance Manager is the most likely, and the other is the CEO.
See https://www.blender.org/about/people/

Personally I don't think that it makes too much sense for having a dedicated Marketing Rep, especially when a project much larger & older doesn't seem to have a clear one, and this is a job that can be done part time, especially on this fairly small scale, as most Sponsors are only interested in things that benefit them directly in some way like:
1) by getting tons of eyes on their brand (your Product Placements, and Brand Logos), for Which Godot isn't really good, it simply doesn't have enough eyes on it for that to be worth it yet
2) by pouring money into a project they are using themselves (or might otherwise potentially benefit from the fruits of the project, such as Epic)
3) similar to 2, they don't see much use of the project at the moment, but have money to throw at projects, just in case a project might yield some breakthroughs in unexpected areas that might one day benefit them (so in this case, they don't have any use of what's currently in the project and it's current technologies, but see it as fertile ground for brand new technologies to be created, and by this I don't mean like new Rendering Technique that's just a different way of doing something that we already do, but instead doing something totally new)

Really, This would only make sense when Godot's the size of Blender, at which point again it doesn't make sense as it'll just be a magnet for sponsors at that point anyway, like Blender is unless by some miracle it gets to it's size and doesn't get noticed in the eyes of the people sponsoring this sort of stuff, which is just unlikely at that size and could again be done part time, every now and then by someone who is on the team already...

**Comment by Xrayez** [comment]
***Disclaimer**: What comes next is my personal opinion based on my own experience working with Godot and talking with Godot core developers. But I can provide quotes to backup my opinion upon request, if necessary, so that I'm not accused of quoting out of context.*

*Also, I'm just an ordinary contributor in Godot, so please take this with a grain of salt, but I've been contributing to Godot's development for more than 4 years now.*

---

Interestingly, I've noticed that Godot has a good number of users, but not necessarily developers. You could say that Godot does have a good number of developers as well, but look at the sheer number of opened pull requests at the main repository. We do have many first-time/one-time contributors compared to other projects, but only a few do the actual regular maintenance work (perhaps the numbers are the same here when it comes to maintainers, but what I'm really trying to say is that Godot attracts a lot of beginners, I'd say). Unfortunately, I've even witnessed professional developers leaving Godot just because their pull request got in the Limbo.

Having said that, I'd say that Godot already does a really good job marketing the features, and does attract a decent number of users already. But in order to attract professional developers and companies (who do the actual work), it's more about:

* *Proving that* contributions they make for Godot (in the form of pull requests, creating feature proposals) are not left unprocessed. Even if you're not ready to give a formal reply, at least comment on the matter and say that you're going to reply in more detail later, but do not provide superficial opinions, of course. Ignoring, intentional or not, is catastrophic to the prosperity of any project.
* *Proving that* Godot has potential to solve specific use cases when needed, without going into major workarounds of having to maintain a custom version of the engine. Nobody wants to maintain stuff, companies want to save money it would take to maintain a custom engine (which already requires at least a single full-time developer working on this). Building upon **mrjustaguy**'s response, innovations/breakthroughs tend to start off as being specific, but the fact is that Godot does not solve specific use cases out of the box.
* *Proving that* Godot is safe to use in production.
* *Proving that* Godot is not just a prototyping tool. Again, unless easy prototyping is the main goal of Godot's development.

Also, when asking for money, you really have to understand what to ask for. To build upon **Calinou**'s response, it's not only about knowing the ethos of open-source, it's also about knowing what kind of audience Godot aims to target. If Godot hires a marketing person who will go and say: "Yeah, Godot is more like Unreal Engine but open-source", it's more asking for trouble rather than money, in my opinion. That's how Godot's initial development philosophy may be ruined by a salesman person. 😢

**Comment by Calinou** [comment]
Closing, as reduz is likely in the best position to perform this kind of networking already. This is especially the case as he'll better focus on guiding other contributors to work on various areas such as rendering and physics after 4.0 is released.
