### ISSUE TITLE
Autoload and scene tree should be combined into a unified system

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-proposals#2977]
### Describe the project you are working on

My game features a lot of components that are permanent for example `GameMenu`, `AudioSfx` , `AudioMusic`,  `GameData` and many other are permanently loaded as singletons in autoload.  I have more Nodes in Autoload than I have in the Scene tree panel. 

### Describe the problem or limitation you are having in your project

All the nodes in autoload are not easily accessible like the nodes in the Scene tree panel and requires me to look for them in the FileSystem panel. Additionally `/root/main/...` path is somewhat confusing as I'd expect root to be `main` but the actual root is `root` and is hidden from the tree. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose the merging Scene panel and Autoload panel in a new combined and unified system. 

- Main scene built in and will start at `root` which will be grayed out and cannot be renamed and have the appropriate Viewport icon. 
- This main root scene will be stored inside `project.godot` at the end of the file following a tag called `[main]`.
- This main root scene is accessible via a new button that switches between "local" scene tree and this new "global" built in main root scene described above.  If no scene open then the button is grayed out and only this main root scene is displayed.  
- You will no longer require to pick a main scene anymore and game project will immediately start. 
- Creating a singleton will simply require a script to be tagged as such using `@singleton name` or similar system. This method of creating singletons is more organic. Another option would be to simply have a button to flip a node into a singleton. This would also show up on the right click context menu.

I am not sure if this is a good idea but perhaps it can lead to a better ui system that's more unified and functional. Not to say that the current one is not but there is always room for improvement. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/36826319/125181289-79095000-e1d1-11eb-9dfa-60602eb818e6.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with the current system.

### Is there a reason why this should be core and not an add-on in the asset library?

It could be an optional addon instead of core.

**Comment by timothyqiu** [comment]
> All the nodes in autoload are not easily accessible like the nodes in the Scene tree panel and requires me to look for them in the FileSystem panel.

AutoLoads are scenes. You can't access nodes in other scenes from the Scene panel either.

Both scenes and AutoLoads will be nodes/branches on the runtime scene tree.

> Additionally `/root/main/...` path is somewhat confusing as I'd expect root to be `main` but the actual root is root and is hidden from the tree.

You can access AutoLoads by its singleton name instead of absolute path. For example, use `SingletonNode.foo()` instead of `get_node("/root/SingletonNode").foo()`.

**Comment by filipworksdev** [comment]
> AutoLoads are scenes. You can't access nodes in other scenes from the Scene panel either.

> Both scenes and AutoLoads will be nodes/branches on the runtime scene tree.

This Autoload singleton pattern is somewhat confusing. A scene is just a structure of nodes. The entire game is created using a tree structure of different Nodes. 

You can in fact `get_node()` on an Autoload like any other Node because there's nothing special about those nodes. Anything you can do on a regular node you can also do on an autoload singleton node.

Based on my understanding the only special thing about autoload singletons is how they are defined . Thy get associated with a singleton object. This can be in theory done on any node that is top level right under the root. 

![image](https://user-images.githubusercontent.com/36826319/125184905-761d5800-e1ef-11eb-9657-0bbf417cbec5.png)

What I am proposing can be seen when you run the game inside the editor. Your Scene panel turns into a `Remote` and `Local` . I am suggesting making this feature permanent `Global` and `Local` so you can always see the full scene structure any time you choose. See pic above. This singleton pattern can be unified and incorporated into a global Scene tree that shows all nodes regular and singletons together and singletons can be switched on/off via a button or right click context menu.

> You can access AutoLoads by its singleton name instead of absolute path. For example, use `SingletonNode.foo()` instead of `get_node("/root/SingletonNode").foo()`.

I was thinking in the context of normal scene nodes. Say your main scene is called `main` then you would expect to get_node("main/mynode") but in fact is get_node("/root/main/mynode").  This is an issue that comes up ocasionally  new users don't understand where "/root" came from.

**Comment by timothyqiu** [comment]
> I was thinking in the context of normal scene nodes. Say your main scene is called main then you would expect to get_node("main/mynode") but in fact is get_node("/root/main/mynode"). This is an issue that comes up ocasionally new users don't understand where "/root" came from.

The parameter of `get_node` is either relative to the current node or absolute. You can use `get_node("mynode")` if you're calling on the main node. NodePath is like normal paths, if your current directory is `/etc/main` and want to go to `/etc/main/myfolder`, you use `cd myfolder` instead of `cd main/myfolder`.

If you want to get parent or sibling nodes, I think it's better to use `export(NodePath) var path`, select the node in the inspector, and `get_node(path)`.

**Comment by Calinou** [comment]
I like  the idea of showing an icon in the Remote inspector for singletons, but I'd keep the rest as-is.

**Comment by KoBeWi** [comment]
The proposal gained 0 support and the OP deleted their account, so closing.
