### ISSUE TITLE
Add properties to CharacterBody for more move_and_slide options

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot-proposals#2982]
### Describe the project you are working on

A 2D platformer.

### Describe the problem or limitation you are having in your project

They are weird behaviour with the current logic,`move_and_slide` is defined as such:

> move_and_slide is intended to simplify the collision response **in the common case** where you want one body to slide along the other. It is especially useful in **platformers or top-down games**

This method allows beginners to build games that require "common" physics very easily, more than many engines, that's a gem. However I was not satisfied by the current behaviour and I tried to experiment to see what can be improved.

1. Moving platform

They are many issues with moving platform, as fixing those issues is useful in the current version, I will not describe what and why as I did a PR for that [#50314](https://github.com/godotengine/godot/pull/50314)

2. Move and slide logic

`move and slide` makes a projection into the collision normal, so it moves and slide :) however it will change the velocity according to the projection and that will lead to bad behaviours.

- when you project and change the velocity you lose the original direction
- when you project and change the velocity you change the length

 I have a lot of examples but here are few to illustrate the idea:

a) 

If you walk into a slope the body will slowdown, however, to understand well, it's not the method that slowdown the body but the developer because we usually set the `x` component of the velocity.

However if the slope is too steep, `move_and_slide` will increase the `y` a lot, and so, as the length of the velocity returned by the method will be bigger, the body will accelerate and will start to fly and the end of the slope

![steep](https://user-images.githubusercontent.com/6397893/125196496-83236100-e25a-11eb-867a-dea2a971178f.gif)

b)

The body accelerates on the ceiling which is not physically correct (this can also stop the motion as in the following gif):

![acceleration 1](https://user-images.githubusercontent.com/6397893/125196767-502d9d00-e25b-11eb-80ae-cb1173fa0121.gif)

As the velocity slide, this will block the motion sometime:

![JUMP current](https://user-images.githubusercontent.com/6397893/125196871-ccc07b80-e25b-11eb-98c1-ae6eba88ad63.gif)

3. Don't cover some basic behaviour

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. For the logic, the idea is to no more change the velocity by the projection (see code for details)

2. I tried to list (and asked for feedbacks in few platforms) to see what **options** can cover the majority of the needs, here are the ideas I find relevant:

- **Constant speed on the floor**: as requested from a long time, this force the body to move in a constant speed in slope
- **Move on floor only**: currently you can move on walls, same most of the time you don't want that
- **Exclude layer for moving platforms**: currently you have to follow when you are in a moving body
- **Slide on the ceiling**: if you want the ceiling stop the body, or not (current behaviour).

notes:
- they are options, you can turn them on or not
- in 4.0 there is no more parameter in `move_and_slide`, they are properties

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I made of POC of this proposal in **GDScript**:

- https://github.com/fabriceci/move_and_slide
- https://github.com/fabriceci/move_and_slide_4.0

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not in few lines and not easy.

### Is there a reason why this should be core and not an add-on in the asset library?

it's core

### GIF after this proposal ###

![acceleration now](https://user-images.githubusercontent.com/6397893/125199164-2bd6be00-e265-11eb-9d48-f89235ef8531.gif)
![Jump now](https://user-images.githubusercontent.com/6397893/125199168-3002db80-e265-11eb-9d56-183be01759f7.gif)
![demo](https://user-images.githubusercontent.com/6397893/125199711-ca641e80-e267-11eb-9117-ef71f0e47405.gif)

**Comment by pouleyKetchoupp** [comment]
I agree with the concept and the proposed options.

It's in phase with the plan for 4.0, and it's the reason why physics nodes have been reorganized to have a specialized node for characters (proposal #2184).

Detailed comments about specific options:

> **Constant speed on the floor**: as requested from a long time, this force the body to move in a constant speed in slope

Yes, this is a recurring demand and it was already on my radar. Probably disabled by default, but I'm not completely sure about that.

> **Move on floor only**: currently you can move on walls, same most of the time you don't want that

Sounds like a good idea. The current behavior does lead to situations that look buggy when climbing up slopes, so this should probably be the default behavior.

> **Exclude layer for moving platforms**: currently you have to follow when you are in a moving body

Seems useful as well, since there's currently no option to disable the effect of moving platforms (which also includes other characters) and that seems the most flexible way.

> **Slide on the ceiling**: if you want that the ceiling stop the body, or not.

It is a known issue (https://github.com/godotengine/godot/issues/20593). As commented in that issue, it could be done in user script, but with the new design an option would be great since it does seem like a common case. I would probably make it slide by default.

Also as an alternative, it could be a threshold to allow for more flexibility (as proposed in https://github.com/godotengine/godot/issues/20593#issuecomment-408889467), so it would be allowed to slide past a certain angle and bump if the ceiling is flat enough.

**Comment by Janders1800** [comment]
Same for 3D.

**Comment by AttackButton** [comment]
About the:

> Move on floor only: currently you can move on walls, same most of the time you don't want that

This already exists with the old `floor_max_angle` move_and_slide paramenter. I like the idea of the floor max angle because games that use a lot of slopes and loops like Sonic can be made so much easy with this.

One question, the `snap` vector of the `move_and_slide_with_snape` function will stay in the new version?

**Comment by fabriceci** [comment]
> This already exists with the floor_max_angle

The parameter `floor_max_angle` is only used to determine if you are on a floor, a wall or a ceiling. If you set the floor max angle to 1° you you still be able to walk on "wall". `move on floor only` will prevent you to be able to move on wall (if enabled).

 > the snap vector of the move_and_slide_with_snap function will stay in the new version?

This proposal in only about adding/fixing things, all the current options remain. 

But FYI, as everyone doesn't know that, `move_and_slide_with_snap` and `move_and_slide` are merged in one method in 4.0. Snap becomes a property, as well as all the other argument. You will simply call the function like this `move_and_slide()` and set the property in code or in the editor (see screen of my work in progress)

![Screenshot 2021-07-26 at 10 16 23](https://user-images.githubusercontent.com/6397893/126956447-ef06860c-b63e-4723-a180-dcf13da41d11.png)

**Comment by AttackButton** [comment]
Cool! Nice work, man.
