### ISSUE TITLE
Refactor the SizeFlags enum of Control nodes

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#299]
### Describe the project you are working on:

Any game with a UI

### Describe the problem or limitation you are having in your project:

The problem that I am having is that, either I do not understand the SizeFlags enum of Control nodes, or the enum is designed in a confusing way that allows invalid configurations.

According to the [Control node documentation](https://docs.godotengine.org/en/latest/classes/class_control.html#enumerations):

>enum **SizeFlags**:
>  * **SIZE_FILL** = **1** — Tells the parent Container to expand the bounds of this node to fill all the available space without pushing any other node. Use with size_flags_horizontal and size_flags_vertical.
>  * **SIZE_EXPAND** = **2** — Tells the parent Container to let this node take all the available space on the axis you flag. If multiple neighboring nodes are set to expand, they’ll share the space based on their stretch ratio. See size_flags_stretch_ratio. Use with size_flags_horizontal and size_flags_vertical.
>  * **SIZE_EXPAND_FILL** = **3** — Sets the node’s size flags to both fill and expand. See the 2 constants above for more information.
>  * **SIZE_SHRINK_CENTER** = **4** — Tells the parent Container to center the node in itself. It centers the control based on its bounding box, so it doesn’t work with the fill or expand size flags. Use with size_flags_horizontal and size_flags_vertical.
>  * **SIZE_SHRINK_END** = **8** — Tells the parent Container to align the node with its end, either the bottom or the right edge. It doesn’t work with the fill or expand size flags. Use with size_flags_horizontal and size_flags_vertical.

"Fill" says it "fills all the available space without pushing any other node", but this is false in testing. This sentence implies that the last item in an HBoxContainer would grow to the right, it doesn't. The actual behavior is that it fills up the reserved space.

Both "Shrink Center" and "Shrink End" say "It doesn’t work with the fill or expand size flags", and I don't think they work with each other either. Shrink Center is mutually exclusive with everything else, and Shrink End is also mutually exclusive with everything else.

I don't think there is a use case for "Expand" without "Fill", but I could be wrong. So, from what I can gather, there are only **5** valid configurations out of the 16 possible combinations:

* No size flags
* Fill only
* Fill with Expand (ExpandFill)
* Shrink Center only
* Shrink End only

Furthermore, having none of the size flags enabled basically functions as a "Shrink Begin", if I'm understanding this correctly (because it's not filling or being moved to center/end).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think that it would make more sense to refactor this into a "dropdown"-style contiguous enum (0,1,2,3,4) instead of a "checkbox"-style bitwise enum (0,1,2,4,8), and rename some of the options. I was thinking something like this:

* Normal (same as Fill currently, and called this way because this is the default and most common)
* Expand (same as ExpandFill currently)
* Shrink Begin (same as everything unchecked currently)
* Shrink Center (same)
* Shrink End (same)

It would require a very heavy amount of refactoring which would break compatibility. For example, code that checks for Fill would need to be changed from `& SizeFlags.Fill` to `< 2` or `< SizeFlags.ShrinkBegin` or similar. Code that checks for Expand would need to be changed from `& SizeFlags.Expand` to `== SizeFlags.Expand` and code that checks for ShrinkCenter/ShrinkEnd must be `== SizeFlags.ShrinkCenter` etc.

### Describe how this feature / enhancement will help you overcome this problem or limitation:

If the SizeFlags enum was less confusing, it would help people understand Control nodes more easily.

### If this enhancement will not be used often, can it be worked around with a few lines of script?:

I think Control nodes are used very often, so making them less confusing is good.

### Is there a reason why this should be core and not an add-on in the asset library?:

SizeFlags is a core feature.

**Comment by groud** [comment]
In fact that is not how I would refactor this. Not all of the size flags are used by all containers, their use depends on the type of the Container.

So instead of having all of them available all the time, I thing we should find a way to dynamically add/remove properties to children nodes depending on their parent Container type, so that only properties that make sense would be displayed. This requires designing a dedicated API, but it's not a simple task I guess.

**Comment by CodeDarigan** [comment]
"expand the bounds" should probably be changed to something like "expand to the total minimum size" as size_fill typically means that (I don't know of any issue where it doesn't?)

**Comment by aaronfranke** [comment]
@groud How would you refactor this? You are right that not all containers work the same. I tested all Container-derived nodes:

* The proposal I made works well for `HBoxContainer`, `VBoxContainer`, `GridContainer`, `HSplitContainer`, `VSplitContainer`, `MarginContainer`, and `PanelContainer`.
  * Many of the above don't use all combinations of size flags, but my proposal isn't any worse in this regard.
* It doesn't work well for `ScrollContainer` because "Shrink Center" and "Shrink End" do not work without "Expand" enabled.
  * However, the same behavior can be achieved without size flags by setting the Anchor point to 0.5 or 1 on the child.
  * Additionally, we can change the behavior of `ScrollContainer` so that it always has the current "Expand" behavior.
* The `CenterContainer` and `TabContainer` nodes do not seem to use size flags at all.
* The `ViewportContainer` node does not care about `Control` nodes as children, since it contains a `Viewport`.
* I'm not familiar with `GraphNode` but this proposal should be fine there too.

I think that this proposal is a big improvement, and I don't see any downsides. It makes things a lot less confusing because it doesn't allow setting invalid states.

**Comment by groud** [comment]
Oh I did not say the proposal was bad. The rework I proposed will likely make it obsolete, but yeah, it looks like a good improvement otherwise.

**Comment by pycbouh** [comment]
I'm going to include this as a part of https://github.com/godotengine/godot-proposals/issues/2841. I think the implementation will avoid breaking compatibility and instead would redesign the Inspector control instead to provide a list of options instead of checkboxes. Not sure if we're going to rename them, but the list would be pretty much as described in the OP:

> Normal (same as Fill currently, and called this way because this is the default and most common)
Expand (same as ExpandFill currently)
Shrink Begin (same as everything unchecked currently)
Shrink Center (same)
Shrink End (same)

I would also try to include the part where we may filter out the incompatible options depending on the parent container type.

**Comment by dugramen** [comment]
This isn't very friendly to the GridContainer, which has more scenarios with unique flag combinations. I actually think the current scenario is needed, but better wording/naming would help. Example Below:

Blue background is the area of the GridContainer.
All buttons have no flags:
![image](https://user-images.githubusercontent.com/54819319/141002012-b5eee2bc-a379-4075-9a35-03eb81277f4f.png)

3rd button with FILL flag:
![image](https://user-images.githubusercontent.com/54819319/141002293-0de9cee3-8bde-4980-aa6c-624806a9c846.png)

3rd button with EXPAND flag:
![image](https://user-images.githubusercontent.com/54819319/141002504-732acf98-fd0a-4c5c-bc48-053724bc0696.png)

3rd button with SHRINK_CENTER flag:
![image](https://user-images.githubusercontent.com/54819319/141002655-7eda51c8-4b9c-46f2-b3a3-bddd5ced5475.png)

3rd button with SHRINK_END flag:
![image](https://user-images.githubusercontent.com/54819319/141002762-4ceef5f1-fa0e-417c-a9d3-a7e6c1513e11.png)

3rd button with SHRINK_CENTER + EXPAND:
![image](https://user-images.githubusercontent.com/54819319/141003178-8d12e378-34f6-4653-a719-a7a9932e044e.png)

3rd button with SHRINK_END + EXPAND:
![image](https://user-images.githubusercontent.com/54819319/141003309-d3a94718-94b1-4721-b603-2b474d1fb14b.png)

3rd button with FILL + EXPAND:
![image](https://user-images.githubusercontent.com/54819319/141004935-ae211736-b486-4783-b940-c3023da9ca0c.png)

That's at least 8 unique scenarios, and this proposal wouldn't support all of them anymore. And I can see a possible use case for all of them.

A possible solution could be to have just those 8, but I don't know if there would be more scenarios. But if there isn't, then I think the names should be more literal:
"None", "Center", "End", "Fill",
"Expand", "Expand & Center", "Expand & End", "Expand & Fill"

Or maybe just "None", "Center", "End", "Fill" with an "Expand" checkbox.

**Comment by pycbouh** [comment]
@dugramen This may actually be a problem that needs to be solved in `GridContainer`. Flags are well defined and their purpose is such that Expand + Shrink Anything doesn't make sense. At any rate, the idea is to also allow customizing these flags as you wish for custom containers, because custom containers may ignore flags' meanings, same as `GridContainer` does. For the majority of use cases the list would be preferable as it doesn't create invalid combinations.

**Comment by dugramen** [comment]
Oh ok, so specific containers would have more flags. But I'm curious, will you still keeping the bit flags internally or just manually defining enums or something?

**Comment by pycbouh** [comment]
@dugramen Yes, I don't plan to remove the flags or replace them, this is only a question of giving users clearer options when working with the inspector with the intent to remove those that aren't supposed to be used together. But in cases where it might be useful I think a context menu can exist with an option to pick the flags individually. Or something like that.

**Comment by pycbouh** [comment]
This should be sufficient to both give better indication to new users and allow advanced users to do whatever magic they want to do with their custom containers. Still need to add filtering for options based on container type.

https://user-images.githubusercontent.com/11782833/141524970-e6c38829-5669-49e9-b6ea-f7ab1119e554.mp4

**Comment by pycbouh** [comment]
After looking more into it and testing every available container, I think that I've made a wrong assumption. It turns out, quite a few containers accept `Expand + Shrink ...` combination, not just some odd ones. As such, I went for 

> Or maybe just "None", "Center", "End", "Fill" with an "Expand" checkbox.

kind of approach. I decided to still keep the "Custom" option in case some custom container needs "Fill + Shrink ..." or something like that. And to preserve backwards compatibility with current possible values, even if they are invalid.

Here's an HBoxContainer and its options in action. For a brief moment at the start of the clip I also select GridContainer for comparison:

https://user-images.githubusercontent.com/11782833/142639401-8d3a128d-e205-4347-ac5d-ad357cc9ce93.mp4

And here's what it looks like when container ignores size flags and does its own thing:

![godot windows tools 64_2021-11-19_17-28-17](https://user-images.githubusercontent.com/11782833/142639504-54433fdf-28c0-4369-8f54-3cab4cb56a19.png)

**Comment by aaronfranke** [comment]
@pycbouh Having Expand be a checkbox makes a lot of sense. Although, if the only options in the dropdown are Fill and the three Shrink options, then I guess there isn't much use for the "Custom" option, since they are mutually exclusive.

**Comment by pycbouh** [comment]
@aaronfranke Yes, for built-in controls this is true. But I've decided to keep the custom option for custom containers which can do some funky stuff, and to preserve compatibility with current values which can be in invalid combinations. Latter is mostly important for the `3.x` version, but former may be useful in 4.0+ still.

**Comment by pycbouh** [comment]
PR submitted, please give it a test: https://github.com/godotengine/godot/pull/55157. I've also provided a clip with all container types and their corresponding sizing flags.
