### ISSUE TITLE
Improve "Contiguous" option in the new tile editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#3022]
### Describe the project you are working on

2D platformer using tiles.

### Describe the problem or limitation you are having in your project

The Bucket fill tool in the new tile editor in 4.0 has 2 modes: mode that does what you'd expect from a normal fill tool and a second one that replaces all tiles of the same type. The main problem is that the latter is default. Paired with the fact that Bucket tool doesn't currently support undo, it results in me sometimes destroying my map, because I forget to switch it.

In literally every software I used, bucket fill tool will floodfill the area you use it in. This is what most users expect. Meantime the second fill mode, which is the default one, is something I never seen anywhere else. And I doubt that the users expect the fill tool to replace all tiles. It's handy feature, but shouldn't be default.

Another problem is the name. "Contiguous"? When trying the editor it was my first time seeing this word. Well, maybe it's not really relevant with Godot being localizable, but even then, this name doesn't clearly tell what the option does. That's because the floodfill behavior is the expected one and the name doesn't really point to it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The "Contiguous" mode should be the default one. Also the option should be renamed and the name should be reversed to describe the other behavior. Something like "Replace All" or "Same Type" or "All Same".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just rename the "Contiguous" option and make the floodfill behavior default one.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Wellllll technically it *is* possible to make a plugin that switches this option on start, but really? xd

### Is there a reason why this should be core and not an add-on in the asset library?

It's about editor usability.

**Comment by groud** [comment]
I agree it makes sense to use the "Contiguous" mode as the default.

I think I took the UX from the photoshop's, as it basically does a similar thing. See https://www.youtube.com/watch?v=pHzzRcTduW0. Also in gimp they use "Fill whole selection" and "Fill similar colors" for respectively the "Not Contiguous" and "Contiguous" modes. I think the name "Contiguous" is explicit enough, and clearer than other options IMO (though that might be because we have a similar word in French).

Another solution might be to create another tool. Some software have the "Replace all of same type/color" tool as separated (though it seems more common to separate things for the selection tool than the bucket fill one). My examples:
- Gimp: "Magic Wand" for contiguous and "Select By Color" for not contiguous.
- Tiled: "Magic Wand" for contiguous and "Select Same Type" for not contiguous.
(if you have other software that do that please tell me ^^ )

**Comment by 95camarones** [comment]
I think separate tools as @groud suggests would be easier to understand than a "contiguous" mode (which I think is likely to confuse English speakers who haven't used Photoshop - it's a more common term in French and Spanish). I think naming should be as descriptive as possible: paint bucket or flood fill is ubiquitous, but I would prefer "replace all of same type" to "magic wand".

Alternatively, how about a tool "preview" effect that highlights/inverts all of the affected tiles? This would make it clear which tool you were using.

**Comment by KoBeWi** [comment]
Actually a "Magic Wand" tool to *select* tiles of the same type would be useful. I sometimes have an area that I want to fill with background tiles, but I want to fill it on another layer than the front tiles and I also don't want the 2 layers to overlap. With wand tool I could first fill the empty space with "dummy tiles" and then use the wand to copy them to another layer and then fill with the actual pattern. Not sure if that's common use case though.

**Comment by KoBeWi** [comment]
Seems like this was partially addressed by https://github.com/godotengine/godot/pull/54396
The option is now enabled by default. Personally I don't have issue with its name (as I know what it does lol), so if this isn't going to be changed, the proposal may be closed.
