### ISSUE TITLE
Add Project Chrono as a physics engine

### ISSUE THREAD

**Issue by gregcsokas** [godotengine/godot-proposals#3023]
### Describe the project you are working on

A 3D air, land, sea vehicle simulation game

### Describe the problem or limitation you are having in your project

  Already known limitations of the Godot Physics and Bullet physics engines.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It seems to me this project can be a proper alternative to the current physics implementation.

https://projectchrono.org/

-It's opensource with BSD license
-It's modular
-It's cross-platform

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like the current physical engines. You could choose from the settings, and the engine can work with it.
Because of the modularity of the project Chrono, in the settings maybe you should be able to on/off different modules.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's too heavy stuff for few lines of code.

### Is there a reason why this should be core and not an add-on in the asset library?

Based on the fact it's a physics engine, I think the core will be a better place for this, and I don't know it is possible to write a module for this thing.

**Comment by pycbouh** [comment]
> Already known limitations of the Godot Physics

Those are being addressed as we speak by a hired contractor. And there is a big incentive not to use a box solution as integration and further maintenance can be a bigger undertaking than making your own physics system. As well as having such an integral part of the engine as a third-party dependency with its own goals and purposes can often prove to be a problem.

**Comment by Xrayez** [comment]
> As well as having such an integral part of the engine as a third-party dependency with its own goals and purposes can often prove to be a problem.

That's why one shouldn't rely on Godot's physics either if the core component of a game is centered around physics itself, like real-life simulations, and especially for things that require a bit more determinism.

Chrono looks like an interesting project at first glance. You may already know, but Bullet in Godot is implemented as a built-in module, therefore it's totally possible to integrate this kind of physics backend as a custom module. I'm working on a general-purpose extension for Godot called [Goost](https://github.com/goostengine/goost) which is also a module, and features like this likely make sense to integrate there, the only thing missing is willing and passionate people who'd like to maintain such a physics backend...

**Comment by gregcsokas** [comment]
More or less I can agree with @pycbouh, using a third-party module can be hard, from the maintenance perspective.
Yes maybe this engine is a little bit overkill in a lot of cases, but it's still opensource so you don't have to reinvent the wheel, forking is still an option and any maintainer can use any amount of code from it, I know it can be still really hard to work with because you have to understand a lot of unfamiliar code.

My personal opinion is that, if we mix the Godot's user-friendly mentality with a badass physics engine it could be a win win situation.

**Comment by Calinou** [comment]
> My personal opinion is that, if we mix the Godot's user-friendly mentality with a badass physics engine it could be a win win situation.

This is what was attempted with Bullet, and it turned out to be a bad idea in the end :slightly_smiling_face: 

Bullet is barely maintained anymore and has shifted its focus from game development to robotics and simulation.

**Comment by gregcsokas** [comment]
> > As well as having such an integral part of the engine as a third-party dependency with its own goals and purposes can often prove to be a problem.
> 
> That's why one shouldn't rely on Godot's physics either if the core component of a game is centered around physics itself, like real-life simulations, and especially for things that require a bit more determinism, at least locally.
> 
> Chrono looks like an interesting project at first glance. You may already know, but Bullet in Godot is implemented as a built-in module, therefore it's totally possible to integrate this kind of physics backend as a custom module. I'm working on a general-purpose extension for Godot called [Goost](https://github.com/goostengine/goost) which is also a module, and features like this likely make sense to integrate there, the only thing missing is willing and passionate people who'd like to maintain such a physics backend...

It looks really promising for me, but unfortunately, I don't speak C/C++ 
Otherwise, I would have been maintaining something for a long time :D

**Comment by gregcsokas** [comment]
> > My personal opinion is that, if we mix the Godot's user-friendly mentality with a badass physics engine it could be a win win situation.
> 
> [This is what was attempted with Bullet](https://godotengine.org/article/godot-30-switches-bullet-3-physics), and it turned out to be a bad idea in the end slightly_frowning_face
> 
> Bullet is barely maintained anymore. Moreover, its developers have shifted its focus from game development to robotics and simulation.
> 
> Also, according to the Project Chrono homepage, none of the selected applications for Project Chrono feature "game development":
> 
> ![image](https://user-images.githubusercontent.com/180032/126608921-e2f52253-ad77-461f-94ef-2f2b645c6c10.png)
> 
> I'm afraid that doesn't bode well for a potential integration in Godot…

Yes maybe you are right about it, but on youtube, you can find some videos about Unity + Project Chrono like this
https://www.youtube.com/watch?v=v74fKqgqW14

I don't know anything about this integration, I'm just explaining why I thought it can be a good/valid choice.
Can you guys check it somehow?

**Comment by Xrayez** [comment]
> I'm afraid that doesn't bode well for a potential integration in Godot…

It depends I guess. Godot is even capable of creating GUI-only applications. With virtual reality advent, we may expect non-games applications in Godot as well, who knows.

> I don't know anything about this integration, I'm just explaining why I thought it can be a good/valid choice.

It may not be a good choice to integrate as a built-in physics backend because the feature set may be largely different, so it may be difficult to integrate on this level since you'd have to match Godot's own physics API with Chrono. However, I think it's still possible to implement as a set of nodes which will reflect Chrono features, but the downside is that built-in classes like `RigidBody` will still use Godot's physics. More like [Box2D](https://github.com/briansemrau/godot_box2d) integration which provides its own set of specific classes, since Godot's physics in 2D is fairly limited compared to Box2D.

**Comment by logzero** [comment]
I've looked into chrono myself and it seems to be a bit too heavyweight for games.

To quote one of the devs:
> Chrono does not guarantee real-time simulation. However, certain models (including some vehicle models) can run in real-time on commodity hardware.

**Comment by Calinou** [comment]
Closing per @logzero's comment.

It's still possible for a third party to integrate any physics engine they wish by creating a module
, but this won't be pursued officially.
