### ISSUE TITLE
All confusion from Collision Layer eradicated via a simple label rename.

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot-proposals#3032]
![aaaaaaa](https://user-images.githubusercontent.com/46036208/126702796-a236a38b-f272-4833-850f-a1494c0aa044.png)

**Comment by pycbouh** [comment]
Please follow the proposal template, your issue will be reopened when you do. I understand that you think you suggest something extremely simple and not worthy of a formal proposal, but we have to keep standards and you still have some message added to describe your proposal in there albeit in the picture. So please move it from the picture to the proper text and fill out the sections provided. An image is a good aid though.

Keep in mind that sections in the inspector are named after the properties, and changing a name like that may dissociate it from the property it is setting and make it harder to work with.

**Comment by golddotasksquestions** [comment]
The problem already starts with this being called a "Layer". There is nothing layer like to it. You can't stack it, there is no vertical or horizontal relationship in a "collision layer". It's just a group.

The concept of layers and masks make a lot of sense in digital imaging software, like Photoshop. Like in a painting, you lay on layer on top of another.

Collision Layers in Godot however are not laid on top of each other. They don't have any vertical relationship. 

"Masks" is also incredibly unfortunate naming as a mask in a system of layers is the area that is blacked out - the area that does not count to the end result. It's in the name "Mask" - Like something you put in front of your face. Only where there is no mask, you can see through. Only the area that is not masked counts. Same goes for "masking tape". You tape off with masking tape whatever should not be taken into account. This is how it works in photography, in construction, in film, in painting, in costume design, in figurative speech ... everywhere, except in Godot.

In Godot does the opposite: Whatever you check as "masked" is there. Is counted. Is the relevant part.

The most mind boggling part here is that what collision masks do has nothing to do with masking anyway.

Instead of "Collision Layer", it should be called "Collision Groups", 
Instead of "Collision Mask", it should just say something along "Checks collision with:"

![collision_layers_naming](https://user-images.githubusercontent.com/47016402/126722552-c441cda8-108c-4d79-b8d5-a9112821ddb8.png)

**Comment by insomniacUNDERSCORElemon** [comment]
@golddotasksquestions what about collision set and collision get? 

Maybe even collider would be a bit more logical as well.

**Comment by golddotasksquestions** [comment]
@insomniacUNDERSCORElemon I think almost anything would be better than "collision layer and masks". But "Collision set" and "collision get" is not really explicit either. It also sounds like methods (we actually already have get and set methods). 

I think it needs to be very clear how the upper grid is for assigning this very object to Collision Group(s), while the lower grid is for telling the Object which Collision Groups it should checks for collisions.

**Comment by BracerJack** [comment]
I Love @golddotasksquestions "checks for collisions with", it just makes so much sense.
Thank you all for your support in the matter !

**Comment by pycbouh** [comment]
@golddotasksquestions We can't just rename the label, the property itself needs to be renamed (if that's even a problem). And "check collisions with" it probably not the best property name.

Either way, your analysis and further discussion here is a very good basis for a proposal, so feel free to open one, since this one doesn't seem to be getting fixed.

**Comment by Dwapook** [comment]
collision write and collision read has been clear to me in the past.. and write/read are simple names..

**Comment by LightningAA** [comment]
This change would probably only be relevant to 3.x btw as this behavior is being reworked in 4.0 https://github.com/godotengine/godot-proposals/issues/2775

**Comment by AttackButton** [comment]
Other problem is the wrong representation of the two way collision (like 3.x) in the editor, layers and masks create just a link between the two objects, but the editor incorrectly just shows one side, even though the engine makes the collision correctly.

The confusion starts when the user set in an object the mask to collide with another object, both will collide correctly, but visually on the editor the last one not necessary will need the first checked in it masks as well.

The solution for this could be the editor to automatically check the mask of the second object with the layer of the first one.

Every time the mask of one is checked, the editor could check on the mask of the other as well. 

That's what the **unity layers collision** matrix do somehow. It's ugly, but very effective to show the link between the objects:

![image](https://user-images.githubusercontent.com/25422687/153506204-771302d8-c301-40e2-a91b-3d9779908223.png)


* The exception would be the Areas (depending on each situation) and raycasts.

**Comment by Zireael07** [comment]
@AttackButton: Your idea would've made sense some time ago. Now it doesn't, as in 4.0 A can collide/detect B without the reverse being true, so it doesn't make sense to tick the other's mask too.
