### ISSUE TITLE
Implement `is_inside_solid_geometry()` in `CharacterBody`

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#3066]
### Describe the project you are working on

3D Character Game

### Describe the problem or limitation you are having in your project

It is not possible to determine whether a `CharacterBody` is buried in objects or not. This means that it is not possible to get the object in which the `CharacterBody` is buried.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If a `CharacterBody` is buried in an object, you can disable the collision of the object by checking `is_inside_solid_geometry()` to prevent it from getting stuck.

See also #3065.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a method to `CharacterBody`. I think it can be considered buried if the collision cannot be resolved after a user-set number of slides.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It needs to be included within the GodotPhysics

**Comment by Calinou** [comment]
The `is_buried()` naming seems strange to me. Why not `is_stuck()` or `is_inside_solid_geometry()`?

**Comment by TokageItLab** [comment]
Since I am not a native English speaker, I consider the ones you mentioned to be better. For now, I'll change it to `is_inside_solid_geometry()` in the overview, which could explain the function.

**Comment by pouleyKetchoupp** [comment]
That could be useful, but I would rather do it in a more generic way.

Instead of a specific function, it should be possible to get the depth from any collision that occurred in your last character motion, by adding an extra function to `KinematicCollision3D`.

The information is already there, just not exposed to script. I can make a PR next week, but if you'd like to try it yourself, it should be easy to do.

You just need to add a new method `get_depth()` here that returns `result.collision_depth`, and add it to the script bindings too:
https://github.com/godotengine/godot/blob/20d46c5b9ede7bfb9001d341ac20d8a30f49cba5/scene/3d/physics_body_3d.cpp#L1446-L1460

That would allow your script to check if the depth is over a threshold and detect that your character is stuck.

**Comment by TokageItLab** [comment]
I confirmed that this can be solved with the API already in place.
```gdscript
move_and_slide()
is_inside_solid_geometry = test_move(self.transform, Vector3.ZERO)
```
However, if there is get_depth(), it can be used for post-penetration test resolution, so I will send a PR later.
