### ISSUE TITLE
Show popup message when selecting custom class with `Add Child Node`

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-proposals#3101]
### Describe the project you are working on

Applies to any project with scripts using `class_name`

### Describe the problem or limitation you are having in your project
`Edit: see explanation video:`
https://user-images.githubusercontent.com/60025044/129176160-bc525cec-3235-491a-bed5-1c473d0400c1.mp4

When trying to instance a custom scene which has a script that uses `class_name`, it's easy to accidentally use `Add Child Node` instead of `Instance Child Scene`.

Now you have a built-in node instance instead of the custom scene instance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When the user selects a custom class in the `Add Child Node` dialog, a popup message can ask them if they meant to do that.
`Edit: This should only happen when the script is attached to the root node of a scene.`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
You are about to create a built-in node which is extended by <Class Name>.
You may have intended to instantiate a custom scene using 'Instance Child Scene' instead.
[ OK ]       [ Cancel ]
```
This could be the default behavior, but toggleable in `Editor Settings`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure how common of a problem it is, but it's gotten me more than once.
If `class_name` didn't automatically add the class to the `Add Child Node` dialog, this would be less of an issue.
If that were the case, an `@in_editor` annotation could be added before `class_name` to make it appear under `Add Child Node`.

Related: https://github.com/godotengine/godot-proposals/issues/1047

**Comment by willnationsdev** [comment]
I'm a little confused. Aren't there separate dedicated buttons for adding a child scene (chain link icon) and adding a child node (plus icon)? I don't see how a popup on the CreateDialog (the one for adding nodes) would help with that. Instead, you'd have the popup appearing much more frequently in scenarios where users just want to add one of their globally-defined nodes and not just a scene (since that's what that dialog is specifically for).

Is there any scenario where a scene could end up in the CreateDialog? Is this for plugin-based "custom classes" (thought those were only for scripts and not scenes iirc)?

**Comment by timothyqiu** [comment]
FYI: Adding a script with class name into a scene is a valid use case for utility nodes and simple custom controls.

**Comment by Error7Studios** [comment]
> FYI: Adding a script with class name into a scene is a valid use case for utility nodes and simple custom controls.

Sure, and in that case, there should be no popup window shown, as I said in the above reply:

> the proposed popup window should only appear when the script using class_name is attached to the root node of a scene.

That way, you would only see the popup when you _**most likely**_ used `Add Child Node` by **_accident_**.
If you already have a custom scene with the script attached to the root node, I think it would be a pretty rare case where you'd want to instantiate the script instead of the scene.

**Comment by willnationsdev** [comment]
Oh, I see what the problem is now, okay. Well, although I understand the problem, I don't believe this proposal is the best solution for it since it directly interferes with the intention of the UI (by assuming the user might have wanted to create a scene when the user explicitly clicked on - and presumably intended to - create a node).

I would suggest that #1935 could be a better solution where scene-bound scripts would appear in both dialogs and would consequently instantiate the same way in either case.

**Comment by Error7Studios** [comment]
> I would suggest that #1935 could be a better solution where scene-bound scripts would appear in both dialogs and would consequently instantiate the same way in either case.

Perfect. That proposal would also fix the issue of `Class.new()` and `PackedScene.instance()` doing different things, when a particular class is supposed to always be "bound" to the root node of a particular scene.

A custom script icon should probably be used for any scripts that are bound to a scene like this.
