### ISSUE TITLE
Move Loop from an import option to a property in the AudioStreamPlayer nodes

### ISSUE THREAD

**Issue by MichaelShaulskiy** [godotengine/godot-proposals#3120]
### Describe the project you are working on

Applies to anything

### Describe the problem or limitation you are having in your project

While participating in a game jam, I had voice lines in ogg format which I wanted to use in game.

After putting them in an AudioStreamPlayer/2D node and setting looping to off in the AudioStreamPlayer, my voicelines kept looping.

I didn't know why, even the finished() signal from the AudioStreamPlayer was never emitted.
Perplexed, I googled my problem and found a fix for my Problem: by default, looping is turned on in the import tab of my ogg audio asset.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It doesn't make sense to have a looping option in the import tab of all things. There already is a looping option in the AudioStreamPlayer Node, which will have no effect, if looping is turned on in the import options. 

Looping isn't an inherent property of audio files. They should be just that: audio files, containing sound data.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a User imports an audio file, there will be either no option called looping or the looping option will still be present, but not enabled by default as it is now.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No because the AudioStreamPlayer looping option has no effect on audio assets imported with looping turned on in the import settings

### Is there a reason why this should be core and not an add-on in the asset library?

It is a source of confusion and not logical, looping should be an option in the AudioStreamPlayer only

**Comment by golddotasksquestions** [comment]
It maybe would make more sense to have ogg looping disabled by default, but not all games have voice overs (given how Godot is used predominantly by hobbyists still, it's fair to assume most games don't have voice overs).

For games that don't have voice overs, having an import option enable the oggs loop property by default would make a lot of sense as ogg is meant to be used for game music, not sound effects. 

I would think for voice acting ogg is fine. These sound sniplets are usually substantially longer than your average sound effect and a tiny delay is also not completely immersion breaking.

For any short repeated sound effects however like impact sounds, swooshes, shooting sounds, footsteps, menu and ui sounds and the like, use wav. Especially those that are important gameplay indicators in fast paced games since decoding the ogg can take more time and processing power.

**Comment by dalexeev** [comment]
`Resource`s should manage data, not behavior. Therefore, this is a very good proposal.

Moreover, we have already introduced such a change:
![](https://user-images.githubusercontent.com/47700418/130362564-93580253-c883-4cf9-a53b-6952b0941fc7.png)

**Comment by me2beats** [comment]
Loop should be turned off imo.
![turn it off](https://user-images.githubusercontent.com/16458555/146652393-ada3e323-bb3f-4b8c-8261-357e9bd65e0e.JPG)

Now I have to disable this extremely often, this is annoing.
I keep Loop on for background music etc but the number of such files is much less.
I believe loop should be off for all audio formats.

**Comment by YuriSizov** [comment]
This may already be addressed by https://github.com/godotengine/godot/pull/62896.

**Comment by mieldepoche** [comment]
I have WAV files that have loop regions.
Without a per-AudioStreamPlayer loop mode, it is impossible (without an ugly workaround) to play both the "short" sample and the looped one as it will always loop no matter what.

My current workaround is:
```gdscript
var asp := $AudioStreamPlayer
asp.play()
get_tree().create_timer( asp.stream.get_length() ).timeout.connect( asp.stop )
```

> This may already be addressed by https://github.com/godotengine/godot/pull/62896.

This does not seem to adress the issue I'm having, which would be solved by this proposal, so I'd say no.

**Comment by Landeplage** [comment]
I've worked with audio in a Godot project lately, and I agree that having a checkbox for looping in the import stage is confusing, and a bit irritating. Additionally, the AudioStream resource itself has settings like LoopMode and loop start/end. This means looping is configured in two places.

To me, it makes more sense to move loop settings to the AudioStreamPlayer node, because it is linked more to the _behaviour_ of the audio, as opposed to _content_. This is also how Unity handles it.

One advantage of keeping this setting at the import stage would be to be able to check the filename of the audio, and look for "loop". If it has "loop" in the name, we more than likely want to loop the sound. The importer could automatically check the "Loop" box for us. This would be great as an optional project setting, or even a setting right in the import options.

**Comment by Mickeon** [comment]
I am working on keeping both the Import setting and allowing AudioStreamPlayers to override the playback looping behaviour. So far so good. 

In my personal projects this feature would be beneficial, as it does make sense to me for Godot to keep the original audio's looping settings in mind (otherwise sounds that have been set up to loop with `loop_begin` and `loop_end` may not behave consistently), while still allowing it to be overridden by whatever Node is playing the source.

**Comment by fguillen** [comment]
Any advance on this?

**Comment by Calinou** [comment]
> Any advance on this?

See https://github.com/godotengine/godot/pull/65797#issuecomment-1573413035. Please don't cross-post, as it makes the discussion harder to follow 🙂

**Comment by akien-mga** [comment]
The need for this was replaced by https://github.com/godotengine/godot/pull/86473.

**Comment by norrbru** [comment]
Am I missing something, or is this issue still absolutely present in 4.6? To set the looping of audio files you still have to enable the looping on a per-file-basis.

This is incredibly unintuitive, and goes against most audio software conventions. As @MichaelShaulskiy noted in the original proposal, *looping is not an inherent feature of audio files.* This logic should absolutely be kept only within AudioStreamPlayers, and I'm having a hard time figuring out why this was closed as completed. 

The issue #86473 is either affecting something else, or has been removed at some point. This should be reopened.

**Comment by Nichgon** [comment]
It seems the loop override parameter from https://github.com/godotengine/godot/pull/86473 only works for .ogg and .mp3, but not for .wav which we still have to enable the looping on a per-file-basis.
