### ISSUE TITLE
Make `Vector2/3` nullable in C#

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#3203]
### Describe the project you are working on

chaotic 2D game

### Describe the problem or limitation you are having in your project

My orginial problem is described [here](https://github.com/godotengine/godot-proposals/issues/3202), now I wanted to workaround that with a default argument that is `null`, then check if it is `null` and if so, set it to `Vector2.Zero`, but Vectors aren't nullable (yet).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Vectors could be `null`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know, maybe [this](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=net-5.0) helps.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it cannot be changed with an add-on.

**Comment by raulsntos** [comment]
You can already use [Nullable<T>](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=netframework-4.7.2) like this:

```csharp
public void MyMethod(int a, int b, Nullable<Vector2> v = null)
{
	if (v == null)
	{
		v = Vector2.Zero;
	}

	// Access the value of v with the Value property
	GD.Print("Vector is (", v.Value.x, ", ", v.Value.y, ")");
}
```

You may also want to take a look at the [Nullable value types documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types).

**Comment by MaaaxiKing** [comment]
Ah, now I understand, what I've linked to, thanks a lot. But is my proposal theoretically realizable?

**Comment by raulsntos** [comment]
Vectors can't be `null` because they are structs, not classes. While we could change `Vector2` to be a `class` instead of a `struct`, I don't think that'd be useful since we can already use `Nullable<T>` for your use case (as explained above) so it brings no benefit.

Also, there is a reason why types like `Vector2` are defined as `struct` instead of `class`. You might want to look into [Choosing Between Class and Struct](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct) which will explain it better than me, but basically `structs` are cheaper to allocate.
