### ISSUE TITLE
Improve auto complete in IDE

### ISSUE THREAD

**Issue by XLIVE99** [godotengine/godot-proposals#336]
**Describe the project you are working on:**
I'm remaking my basic space game (Maded with Unity) on the Godot engine for learning. Some asteroids come thru random and player trying to avoid them as long as possible. Player controls a space ship. There will be 8-9 space ships.

**Describe the problem or limitation you are having in your project:**
>I googled it but i couldn't find anything like that, so if there's already something like that, sorry for that. Also sorry for my bad english.

In Unity, Visual Studio can suggest functions and other things with `GetComponent<>`. But in Godot when i instanced `PackedScene` even i have GDScript on that, IDE doesn't show any suggestion. Also `get_node(NodePath)` just show `Node` functions (It's probably because returning Node class) but i have `export Array NodePath` and path shows particle2D node, there will be 8-9 space ships has different particle node names and different count of particles. For example my first ship has 4 particles but second ship has 2 particles.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It will make easier to coding. For now, i need to check node's properties. Better IDE lesser error.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![InstanceProblem](https://user-images.githubusercontent.com/30470295/71450618-19c22700-2776-11ea-8e79-f683cb696fe9.png)

![GetNodeProblem](https://user-images.githubusercontent.com/30470295/71450623-234b8f00-2776-11ea-9068-a0046bf0a1af.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think it can work with a few lines of script, IDE is one of the hearts of game engine so it will be used often.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Godot has own IDE, it is already inside of core.

**Comment by KoBeWi** [comment]
> But in Godot when i instanced PackedScene even i have GDScript on that, IDE doesn't show any suggestion.

That's because it doesn't know what script it has. IIRC it should work when you use `preload`, but the Godot's autocompletion is both unreliable and amazing sometimes.

As a workaround, you can use `as` keyword to explicitly cast variable to desired type. It works with Godot classes and custom ones (created with `class_name`).

**Comment by XLIVE99** [comment]
> > But in Godot when i instanced PackedScene even i have GDScript on that, IDE doesn't show any suggestion.
> 
> That's because it doesn't know what script it has. IIRC it should work when you use `preload`, but the Godot's autocompletion is both unreliable and amazing sometimes. (also keep in mind that sometimes it's impossible to infer type and Godot still lacks typing for e.g. arrays and dictionaries).
> 
> As a workaround, you can use `as` keyword to explicitly cast variable to desired type. It works with Godot classes and custom ones (created with `class_name`).

Thank you, i didn't know that. Do i need to set `class_name` everytime i need suggestions?

**Comment by willnationsdev** [comment]
@XLIVE99 

> Thank you, i didn't know that. Do i need to set class_name everytime i need suggestions?

No, `class_name` just generates a global variable that loads your Script. You can also not create a global variable, and instead create a local constant.

    # GlobalNode.gd
    extends Node
    class_name GlobalNode
    var global_num := 0

    # MyNode.gd
    extends Node
    var local_num := 0
    func _ready():
        # Access name globally.
        # Notice the colon which infers the type and assigns it as a static type.
        var child := GlobalNode.new()
        # can get autocompletion because using static typing
        child.global_num += 1
        add_child(child)

    # SomeOtherNode.gd
    extends Node
    const MyNode := preload("res://MyNode.gd") as Script
    func _ready():
        var child := MyNode.new()
        # can get autocompletion because colon grants static type inference
        child.local_num += 1
        add_child(child)

In this case, the 'child' properties are specifically "typed" as a certain of Script that extends Node. The same goes for these:

    var child1: GlobalNode = null
    var child2: MyNode = null

But if you haven't created a local constant with the loaded Script value, or if you haven't created a "script class" (a global script variable/name) using the `class_name` keyword, then you won't be able to use static typing to refer to the Script-based class by name. So, this would produce an error:

    var child3: SomeOtherNode = null

...because we've only created a script file with that name (SomeOtherNode.gd), but haven't actually loaded it into a constant in the current script or declared it as a global script class.

Please see the relevant [documentation on static typing](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/static_typing.html) for more information.

**Comment by willnationsdev** [comment]
If you notice particular problems with the static typing in GDScript (which is the way we provide better autocompletion), then that should *probably* be reported as a bug in godotengine/godot. Otherwise, I'm thinking that this proposal is too vague to be actionable. Let us know if you continue to have problems.

**Comment by XLIVE99** [comment]
> @XLIVE99
> 
> > Thank you, i didn't know that. Do i need to set class_name everytime i need suggestions?
> 
> No, `class_name` just generates a global variable that loads your Script. You can also not create a global variable, and instead create a local constant.
> 
> ```
> # GlobalNode.gd
> extends Node
> class_name GlobalNode
> var global_num := 0
> 
> # MyNode.gd
> extends Node
> var local_num := 0
> func _ready():
>     # Access name globally.
>     # Notice the colon which infers the type and assigns it as a static type.
>     var child := GlobalNode.new()
>     # can get autocompletion because using static typing
>     child.global_num += 1
>     add_child(child)
> 
> # SomeOtherNode.gd
> extends Node
> const MyNode := preload("res://MyNode.gd") as Script
> func _ready():
>     var child := MyNode.new()
>     # can get autocompletion because colon grants static type inference
>     child.local_num += 1
>     add_child(child)
> ```
> 
> In this case, the 'child' properties are specifically "typed" as a certain kind of Script that extends Node. The same goes for these:
> 
> ```
> var child1: GlobalNode = null
> var child2: MyNode = null
> ```
> 
> But if you haven't created a local constant with the loaded Script value, or if you haven't created a "script class" (a global script variable/name) using the `class_name` keyword, then you won't be able to use static typing to refer to the Script-based class by name. So, this would produce an error:
> 
> ```
> var child3: SomeOtherNode = null
> ```
> 
> ...because we've only created a script file with that name (SomeOtherNode.gd), but haven't actually loaded it into a constant in the current script or declared it as a global script class.
> 
> Please see the relevant [documentation on static typing](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/static_typing.html) for more information.

Thank you, problem solved.
