### ISSUE TITLE
Add a Save Node for easy scene state saving

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#3364]
### Describe the project you are working on

Drawing editor, where I would like to save the editor configuration and turn based dialogue, were I would like to save the character stats.

### Describe the problem or limitation you are having in your project

Saving the scene state across sessions is only doable from script and I prefer to use the visual user interface, as that is what I am comfortable with.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a Save Node you can add to a Scene, which you can use to select the properties you would like to save. Then this node handles saving and loading automagically for that particular scene. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Select Save Node.
![afbeelding](https://user-images.githubusercontent.com/49942484/135242641-2630f5dc-a9f3-48d6-848e-f62e893ee5f2.png)
And then you can select properties you want to save (in the dock, like ResourcePreloader).

Then you can call the load and save function at the time you want.

And (possibly) a autoload and autosave property, which automatically loads the scene state when added to the scene tree and saves when removed from the SceneTree. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I presume a lot of people are interested in it as there a lot of implementations of save systems in the asset store. But thus also yes, it can be done via script, but it won't necessarily be very specific to the scene.

### Is there a reason why this should be core and not an add-on in the asset library?

It seems like something that is positioned better in core.

**Comment by pycbouh** [comment]
> Saving the scene state across sessions is only doable from script and I prefer to use the visual user interface, as that is what I am comfortable with.

I appreciate that there are people who aren't comfortable with writing code, maybe even not with using Visual Script. But we cannot add nodes to the core for every occasion just because of that. This is perfectly doable with a custom node that you, or someone willing to help you, can create for your project. You can then you just plug & play it into the scene you want to save and use the inspector.

**Comment by boukew99** [comment]
I am sorry I was not clear on this. I have done it before in code a couple of times with ConfigFile, but with comfortable I meant that it is not flexible for change and that it has to be somewhat custom to each scene, which makes it a bit of a pain and makes me skip it most of the time. I would have made a custom node, but there is no way to select properties in the scene from any node, right? Next to that it is more of a configuration of the scene thus PackedScene and ResourceSaver seemed a bit of overkill?

My intention is not to bloat the engine, but I envisioned it is a easy and versatile way to save parts of your game, through the scene system, and make saving more accessible to more people besides me as saving is used in almost any game.

**Comment by pycbouh** [comment]
> I meant that it is not flexible for change and that it has to be somewhat custom to each scene

Indeed it isn't. Because there is no single solution for saving the state of your game that fits everyone's needs. It will always be a bespoke system that you make that makes sense for your architecture and design, and we cannot introduce a broad solution to the core that would be for everyone and no one at the same time.

> I would have made a custom node, but there is no way to select properties in the scene from any node, right?

You can do anything you want. You can make a system that selects properties of specific nodes and stores those values. In fact, that's pretty much what PackedScene is. It's a list of nodes and their respective properties with their respective values.

> Next to that it is more of a configuration of the scene

That calls for a deterministic approach where you use a custom resource (or a ConfigFile, but it's less versatile when it comes to data structure). And only you can decide how the state of the nodes can be serialized and deserialized in a way that makes sense for your setup. Like I've said, core already provides you with tools to do the bespoke system. And it provides tools for the most blunt approach possible as well (just serializing the whole scene with PackedScene) if you can't decide on how to build it properly.

**Comment by boukew99** [comment]
Okay, thank you very much, i will make this and try to discover its limitations
