### ISSUE TITLE
C# template: add "using static Godot.GD" to top, for improved GDScript similarity

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot-proposals#350]
**Describe the project you are working on:**

Just started learning GoDot, but using C# not GDScript.

**Describe the problem or limitation you are having in your project:**

Translating GDScript tutorials into C# is pretty straight forward, but adding a few ```using static``` lines at the top of the C# template would make it even easier to translate from GDScript to C#

for example, the top of the C# template could be
```c#
using Godot;
using System;
using static Godot.Mathf;
using static Godot.GD;
```

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

doing this would let people use the static methods of Godot.Mathf and Godot.GD directly, such as ```Print("hi");``` instead of ```GD.Print("hi")```  

which lowers the delta between GDScript and C# a lot.    C# users who dislike this don't need to use it.   This feature is already available in Mono.  It's a C# 6.0 feature, as per:  https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#using-static

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

```c#
using Godot;
using System;
using static Godot.Mathf;
using static Godot.GD;

public class Test: KinematicBody
{
	public override void _Ready()
	{
		Print("Hello Godot");
	}
}
```

**Describe implementation detail for your proposal (in code), if possible:**

just add ```using static [Namespace].[StaticClass]``` lines to the top of the C# template, for each static class you want exposed to make the C# experience closer to GDScript

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

just don't use it, or delete the ```using static``` lines from the ```.cs``` file

**Is there a reason why this should be core and not an add-on in the asset library?:**

super easy to do and helps GDScript users be less intimidated by C#, a good "first user experience", as novice C# users won't know how these "fancy" features

**Comment by aaronfranke** [comment]
I have considered this before, we could certainly do this, but it might promote bad coding practices, as `using` directives should be used sparingly to avoid including many things in the namespace.

There is also the question of whether this should be done just for `GD` or also for `Mathf`, having both would be most similar to GDScript, but some things in `Mathf` might be inappropriate to include by default, such as `MoveToward` and `Log` which are ambiguous without `Mathf.` (`MoveToward` might be a user function for moving the player, and `Log` could be mistaken for `Print`. Imagine if someone had a `Log` method that accepted strings, then they passed in a number expecting it to be auto-converted, but instead it just calls `Mathf.Log`. This latter problem doesn't exist in GDScript because there is no overloading so IINW you can't create a method called `log`).

**Comment by jasonswearingen** [comment]
having suggested this, I don't think I would actually ever use ```using static godot.GD'``` or for ```Mathf```.  

However as I just started with godot I should share my own anicdote:

> As there are not any C# based tutorials (as far as I can tell)  I am following some GDScript tutorial series, but writing the code in C# though the tutorial presents GDScript.    The tutorial showed using deg2rad()  and I had no idea where this came from, and so it took me about 30 min of searching around to figure out it's from Godot.Mathf.


So perhaps the better "solution" would be some doc improvements to the C# getting started guide (or tutorial for it).     As I just submitted my first godot doc pull request, perhaps this is something I can attempt to contribute to once I am more familiar/comfortable with godot.

@aaronfranke  I will go ahead and close this proposal.   Please feel free to reopen if you desire.

**Comment by Joy-less** [comment]
This is an older proposal, but I would like to add that this could be done by default in the `.csproj` file:
```csproj
<ItemGroup>
  <Using Include="Godot.GD" Static="True" />
</ItemGroup>
```

Alternatively, in a `.cs` file: (C# 10+)
```cs
global using static Godot.GD;
```
