### ISSUE TITLE
Add Option for Environment's Reflected Light Soruce to be a Different Sky from the Background

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3593]
### Describe the project you are working on

Game with Metalic Surfaces and a Dynamic Sun

### Describe the problem or limitation you are having in your project

Ambient Light and Reflections Need to be constant, which can be done for Ambient Light by using Color instead of Background/Sky, however Reflected lighting cannot be specified in a way that is decoupled from the Skybox.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding an ability to specify a new separate Sky Resource for Reflected (and Ambient could use it too) Light would allow for a Dynamic Skybox, while keeping Constant Background Lighting when desired.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an option for Specifying Skies to the Environment Lighting, If none set, use the one the Background uses.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No way to Workaround atm.

### Is there a reason why this should be core and not an add-on in the asset library?

Environment is Core.

**Comment by Calinou** [comment]
In `master`, the reflected light is dissociated from the ambient light in Environment. However, there is no option to use a different sky for reflected light.

**Comment by Calinou** [comment]
> The Only workaround I can think of is to use GI, however that has the problem of Performance being too costly, not to mention it isn't a part of the Forward Mobile Renderer.

Look into using ReflectionProbes, which are supported in the Vulkan Mobile backend :slightly_smiling_face:

**Comment by mrjustaguy** [comment]
that only somewhat gets the desired result, while not being global, and also not really working great with Little lighting in the scene. I mean it is a significant improvement over Nothing, but not as good as Sky Reflected Lighting is for what i'm looking for.

**Comment by clayjohn** [comment]
@mrjustaguy Do you have any ideas how this should be exposed in the UI?

Right now the environment can only support one Sky. The Sky is exposed if either the background, reflections, or ambient, use MODE_SKY.

**Comment by Zireael07** [comment]
@mrjustaguy: Your use case would be solved if my proposal would be implemented: https://github.com/godotengine/godot-proposals/issues/148

**Comment by mrjustaguy** [comment]
I'd add a Checkbox in Sky, that determines if one Sky is used or two are, and if two are, the 2nd would affect AL & RL if they are set to "Sky" (not background, that should use Sky 1)

I'd Call it something like
"Use Second Sky for Lighting" (Off by default, when On, add another set of Sky options)

**Comment by Calinou** [comment]
I've found a workaround:

- Add a PanoramaSky to the environment as usual.
- Add a MeshInstance with a SphereMesh. Create a SpatialMaterial for it, enable **Flags > Unshaded** and set **Parameters > Cull Mode** to **Front**. Load your reflection panorama into the **Albedo** texture slot.
  - Set the MeshInstance's visibility layers to be only present on **Layer 20** (click the dropdown arrow and uncheck all other layers).
- Add a ReflectionProbe as a *sibling* of the SphereMesh. Do not place the ReflectionProbe as a child, or the node will be hidden when you hide the SphereMesh that acts as a reflection panorama.
  - Make the ReflectionProbe's extents cover the whole scene (with about 10% of padding on each side). This makes sure that ReflectionProbe blending does not get in the way.
  - Set the ReflectionProbe's cull mask to only contain **Layer 20** (uncheck all other layers).
- The texture will likely appear too dark due to sRGB conversion. To fix this, select the reflection panorama in the FileSystem dock, go to the import dock, set the compression to **Lossless** and click **Reimport**. You may have to play with other settings in the Import dock, but this is what fixed it for me.
- Configure your Camera node to not render **Layer 20** in the visibility section.

![image](https://user-images.githubusercontent.com/180032/146078732-dc923ca0-08e7-488a-9c67-c0bd1f565b86.png)

In the running project:

![2021-12-14_22 01 46](https://user-images.githubusercontent.com/180032/146078775-bc1f0349-df6a-47be-8437-229e90913d97.png)

Example project (`3.x`): [different_reflections.zip](https://github.com/godotengine/godot-proposals/files/7714721/different_reflections.zip)

**Comment by Calinou** [comment]
@mrjustaguy Would you consider this workaround sufficient? Since I doubt this is a very frequent use case, I'm not sure if it's worth the effort implementing this in core.

**Comment by mrjustaguy** [comment]
Yeah, I've been testing it a bit, and seems to work fine for the use case needed so I think this can be closed, albeit Forward Clustered Renderer might have issues until culling is fixed. Haven't tested how the issue affects this as I am not using that renderer for the project.

**Comment by Calinou** [comment]
For further reference, there is a second way to use different reflections and sky if you don't want to use a ReflectionProbe:

- Add a PanoramaSky *reflection map* to the environment. This is the opposite workflow as the one described above.
- Add a MeshInstance with a SphereMesh (not parented to the Camera). Create a SpatialMaterial for it, enable **Flags > Unshaded** and set **Parameters > Cull Mode** to **Front**. Load your reflection panorama into the **Albedo** texture slot.
  - Set the SphereMesh's radius to be roughly equal to the Camera's **Far** property (and double that value for the height to keep proportions).
- Add a RemoteTransform node as a child of the Camera. Set its **Path** property to point to the MeshInstance node and uncheck **Rotation** (so that the background sky does not rotate with the camera).
- The sky texture will likely appear too dark due to sRGB conversion. To fix this, select the reflection panorama in the FileSystem dock, go to the import dock, set the compression to **Lossless** and click **Reimport**. You may have to play with other settings in the Import dock, but this is what fixed it for me.
