### ISSUE TITLE
Google play in app rating

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#3600]
### Describe the project you are working on

2d and 3d

### Describe the problem or limitation you are having in your project

As Google play system are updating there should be a system to use in app rating

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Using a node called Google play in app rating

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By using a node and few lines of code

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yeah. As this system is a Google services the system should be implement on core. And there are too many android developer using godot for creating there apps
.sovto save and help the android developer godot must have to contain this feature as a core.

**Comment by pycbouh** [comment]
This is the territory for Android plugins, not the core. In fact, there are a couple of plugins for that purpose already:
https://github.com/pschw/InAppReview
https://github.com/i-bardinov/Godot-GooglePlay-InApp-Review

One can make an argument for including one of them under the organization on GitHub, of course. But the problem with this is that we need to have an active and dedicated maintainer for it that we trust, otherwise it will be just dead weight with the official status which benefits nobody.
