### ISSUE TITLE
Rename the ZIP extension used for exported project data back to PCZ

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3619]
*See also https://github.com/godotengine/godot/issues/5492.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

[Godot supports exporting pack data in two formats: a custom PCK format, and the ZIP file format.](https://docs.godotengine.org/en/latest/tutorials/export/exporting_projects.html#pck-versus-zip-pack-file-formats) PCK is recommended for most use cases, but ZIP compresses better (at the cost of lower read performance) and is easier to modify. This easier modification can be useful to provide primitive modding support in a game (by allowing players to replace various assets more easily).

Since ZIP main pack support is unlikely to be removed for 4.0, I would suggest renaming its file extension to something different than ZIP. The reason for doing so is that it avoids confusion. Otherwise, players might think they have to extract the ZIP archive located besides the executable to run the project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename the ZIP file extension back to PCZ (or something else, but PCZ is the extension used in Godot 2.1 and prior).

If we deem that the risk of confusion between PCK and PCZ is too high, then we could go with a different extension entirely.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Replace all `.zip` references with `.pcz` in the editor code and documentation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is core engine functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by KoBeWi** [comment]
> players might think they have to extract the ZIP archive located besides the executable to run the project.

This sounds a bit far-fetched. Did anyone ever had this issue?

**Comment by Zekiah-A** [comment]
> > players might think they have to extract the ZIP archive located besides the executable to run the project.
> 
> This sounds a bit far-fetched. Did anyone ever had this issue?

I can see this happening, as most games and files, especially on platforms like itch.io are uploaded as .zip, as there is usualy more than one file, so it is highly likely that someone would just unzip it once they have it downloded

**Comment by mrjustaguy** [comment]
I really, Really don't think it's a great idea, as with zip everyone just knows that they can open it up and see what's inside, which another format would remove as an advantage, and or would bring back the same issue that zip has, that people would expect to extract it.

However, as stated above, as a Gamer, and someone who has played a very large variety of games, and done tweaking for some games, I never, EVER did anything like extracting the zip archive when an exe was provided outside of the archive in the same package, unless explicitly told to do in a readme, and My first instinct was always to first try running the exe, unless there is a readme stating otherwise or the exe itself is in a zip.

As a novice Modder & Tweaker I love when I see standardized extensions in games, such as zip, png, gltf, and a whole list of others, because I know I'm likely to have a much easier time doing what I want with it. I mean I'm ok with less common formats if they are clearly stated by the game Dev which tools to use for them, if the tools are freely available or have such alternatives ofc, but that would be on every game dev to state with custom formats like pcz, which maybe not every dev will remember to do, due to the surprisingly common fallacy that "the user will know what to do because I know what to do"

The only argument that would hold water here is that the exe is provided within the same zip that has the game files, but if you for example make a zip and put the exe in the zip and also the game files zip, people will only extract the first zip, the 2nd zip will be fairly obvious it's intended to stay that way.

The only problem is I have Never been able to get a project to run from a zip, and I've tried on multiple occasions as it'd shrink my games considerably without many issues.

**Comment by Calinou** [comment]
We decided against changing the extension in last week's proposal meeting, but I forgot to close this proposal until now.
