### ISSUE TITLE
Enable "Allow Hidpi" by default to fix window management issues across platforms on hiDPI monitors

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3681]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Godot projects[^1] [suffer from](https://github.com/godotengine/godot/issues/24922) [various issues](https://github.com/godotengine/godot/issues/13017) when run on hiDPI monitors (such as Windows scaling set above 100%). This is most noticeable on Windows, but some problems can also pop up on macOS as a result of relying on a lowDPI fallback provided by the OS. (Linux has no concept of DPI-awareness for applications, at least on X11.)

The lowDPI fallback, as its name implies, is designed to be a *fallback*. While it provides better performance on integrated graphics, it is not meant to be used as a daily driver. We're effectively at the mercy of whatever the lowDPI fallback wants to do (including a lack of control over *how* the scaling is performed, which can result in poor scaling quality). Microsoft and Apple both encourage application developers to fix their applications to be resolution-independent, then mark their applications as DPI-aware.

This is not exclusive to modern applications/games. Some old games have received additional patches to be marked as DPI-aware by default. For games that are no longer maintained, [one of the most common resolutions on PC Gaming Wiki is to disable OS-provided display scaling (aka. *enabling* DPI awareness)](https://www.pcgamingwiki.com/wiki/Diablo_III#:~:text=by%20default%2C%20it%20appears%20as%20if%20diablo%20iii%20has%20a%20number%20of%20issues%20with%20high%20or%20custom%20dpi%20settings%20in%20windows.%20). This shows that this issue is not exclusive to Godot, and that we should not try to fight the operating system's lowDPI fallback.

[^1]: The Godot editor is always marked as DPI-aware, and is therefore not affected by this. Any project run from the editor will however be affected by this until **Allow Hidpi** is enabled in the Project Settings.

See https://github.com/godotengine/godot/pull/29553 where this change was previously proposed. Since the original issues haven't been fixed on the OS level, I feel this is worth discussing again in 2021.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enable the **Allow Hidpi** project setting by default.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

One concern about enabling **Allow Hidpi** by default is that performance will suffer on integrated graphics, especially in 3D games. This can be alleviated in the `master` branch by [detecting the use of integrated graphics](https://github.com/godotengine/godot/pull/55790) then [defaulting to lower 3D resolution scaling](https://github.com/godotengine/godot/pull/51870) (probably 50%).
If performance still proves to be an issue in 2D games, 2D resolution scaling could be implemented.

Changing a project setting's default value is a compatibility-breaking change, so a decision needs to be taken before 4.0 is released.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, since the **Allow Hidpi** project setting already exists. However, the current default provides a bad experience not only for game developers, but also for their players who just want to play fullscreen games in peace :slightly_smiling_face: 

### Is there a reason why this should be core and not an add-on in the asset library?

This proposal is about changing a default project setting.

**Comment by pycbouh** [comment]
I don't quite understand why it's an option at all. It should just be always on, because if it's not on, then the window of a Godot project is incorrectly scaled, looks blurry and blown out. Keeping it off only makes the experience worse for a part of users, and I doubt anyone is looking to purposefully provide worse experience.

**Comment by Calinou** [comment]
> I don't quite understand why it's an option at all.

It was left as an option because [it _does_ provide the fastest scaling (it's faster than using a scaled Viewport)](https://github.com/godotengine/godot/issues/36507). Nonetheless, I don't think the added complications are worth it, especially when playing in fullscreen.

**Comment by rainlizard** [comment]
The reason I don't enable ``Allow Hidpi`` is because I want my UI size to look the same regardless of resolution, taking up the same percentage screen space on every person's monitor. Even if it's blurry - because being consistently the same size is preferable to being sharp and tiny. This is a downside of high resolutions like 4k, programs can often have unscaled, tiny UIs that are very difficult to see with poor eyesight. [AOE2 example](https://steamcommunity.com/sharedfiles/filedetails/?id=862524297)
I think if it could be set by the player in-game, based what works best for them personally then that might be a good solution. It looks like currently the only way to set it in-game is by creating an ``override.cfg`` with:
```
[display]
window/dpi/allow_hidpi=true
```
and then prompt the user to restart the game.

**Comment by pycbouh** [comment]
> The reason I don't enable Allow Hidpi is because I want my UI size to look the same regardless of resolution, taking up the same percentage screen space on every person's monitor.

In my experience, if you don't enable it, it does the exact opposite of looking the same. It just looks scaled up, because it doesn't account for system-wide scaling, which is normally set on higher density/higher resolution screens. Enabling hiDPI actually makes it look like it physically has the same size on every display.

**Comment by Calinou** [comment]
> I think if it could be set by the player in-game, based what works best for them personally then that might be a good solution. It looks like currently the only way to set it in-game is by creating an override.cfg with:

Windows already allows you to force DPI awareness on and off for specific executables. We don't need to provide our own layer of customization over that – "use the platform" :slightly_smiling_face:

**Comment by BigZaphod** [comment]
As a macOS/iOS user and developer and (very) part-time Godot hobbyist, I've been a bit confused by this option and wondered why it wasn't enabled by default. On iOS nearly everything has been high-DPI (retina branding) for a decade (seriously - the retina display was first introduced in 2010). The vast majority of macOS machines are laptops which have been retina for years (2012 or so) and iMacs started getting retina screens in 2014, I think. I'm not very familiar with the PC world, but I get the impression this sort of thing isn't quite as common there? As an Apple user, though, it is unbelievably jarring when something doesn't support this properly out of the box - and currently, by default, Godot projects do not.
