### ISSUE TITLE
GDScript - Allow for defined types to avoid "var name : Type" situations

### ISSUE THREAD

**Issue by Mortecha** [godotengine/godot-proposals#3685]
### Describe the project you are working on

I'm currently following Age of Asparagus's tutorial on building a top down shooter in order to get familiar with Godot since I'm migrating all of my projects from Unity. https://www.youtube.com/watch?v=HX6qpYjwN3M

### Describe the problem or limitation you are having in your project

I've run into this situation where in order to get GDScript to predict what methods are available to a variable, you tell it what type of variable it could be when you initially create the variable. 

eg:
var equipped_weapon : Spacial
var hand : Position3D

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose instead of declaring the type afterwards with : , why not instead have the option to declare the Type as you create the variable, this will result in less typing to achieve the same thing. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

instead of :

var equipped_weapon : Spacial
var hand : Position3D

you could instead do:

Spacial equipped_weapon
Position3D hand

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will get used very frequently, in fact it will change the way GDScript works for the better as it allows the ability for common coding practices regarding declaring variables in C, C++ and C# to be used in GDScript. 

### Is there a reason why this should be core and not an add-on in the asset library?

As stated above, It changes how GDScript works for the better as it allows the ability for common coding practices regarding declaring variables in C, C++ and C# to be used in GDScript. I'm also not advising changing how it currently works, but instead allow for the ability to declare a variable type that you know it will be at the time it's created.

**Comment by pycbouh** [comment]
This was already discussed as part of https://github.com/godotengine/godot-proposals/issues/2830, and the decision was that it would not benefit users.

**Comment by Mortecha** [comment]
How would it not benefit users though? I would love to hear you're thoughts? 

Luckily I suppose, the option to just use C# instead already exists.

**Comment by pycbouh** [comment]
> How would it not benefit users though? I would love to hear your thoughts.

You can refer to the discussion in the linked issue. But in short, there is no support for it from users, and I think our main GDScript maintainer wasn't a fan of the idea either.

**Comment by Mortecha** [comment]
So there are two things that stand out here. Firstly you've assumed that I didn't read through the linked issue, and secondly you are grouping the point that I've raised regarding allowing the user to define a type instead of var with another issue raised that specifies allowing one of 4 types to be defined in a similar way.  

It's something that's so intuitive and simple that it boggles the mind to think that it's viewed so negatively. It instead raises questions about why you's want to use GDScript in the first place. 

Thank you for your time pycbouh. I'll use C# instead.

**Comment by Calinou** [comment]
> It's something that's so intuitive and simple that it boggles the mind to think that it's viewed so negatively. It instead raises questions about why you'd want to use GDScript in the first place.

In modern software design, providing several ways to achieve the same thing tends to be frowned upon (with rare exceptions). It introduces confusion for users and choice paralysis that's better avoided.

**Comment by pycbouh** [comment]
> So there are two things that stand out here. Firstly you've assumed that I didn't read through the linked issue

You asked for my thoughts, but they are expressed in the linked thread. I didn't claim it wouldn't benefit users now, as my opinion, I just reiterated the decision that was reached. Which is why I referred you to the previous discussion, if you want to learn the rationale.

> secondly you are grouping the point that I've raised regarding allowing the user to define a type instead of var with another issue raised that specifies allowing one of 4 types to be defined in a similar way.

It is the same issue, though. You want to change the syntax of the language to remove the `var` keyword with a type definition. The other proposal focused on built-in types, and yours is about user-defined types, but the change is the same (and in fact the other discussion, if the memory serves me right, mentioned that we should either do it for all types, or no types, because otherwise it would break user expectations).

> It's something that's so intuitive and simple that it boggles the mind to think that it's viewed so negatively. It instead raises questions about why you'd want to use GDScript in the first place.

Your proposed change is superficial. Different programming languages have different syntax, and GDScript uses a `var` and a colon. Functionally, it's completely the same now as in your proposal, or in fact that older proposal. No new functionality is unlocked by this, so there is only a point of saving keystrokes, but that's not really an important metric, code is autocompleted most of the time.

**Comment by Mortecha** [comment]
Ok so I was originally just going to drop this because there are better alternatives to GDScript already, but seriously what you guys are saying is borderline stupid. 

Now you're telling me that you prefer to do this:
onready var nav = $"../Navigation" as Navigation
onready var player = $"../Player" as KinematicBody

where as Type is required to get auto complete working where instead you could do this instead:
onready Navigation nav = $"../Navigation" 
onready KinematicBody player = $"../Player"

you can save key strokes and get auto complete without having to use "as Type"

secondly, you would prefer to use this:
var direction : Vector3 = path[0] - global_transform.origin

instead of this:
Vector3 direction  = path[0] - global_transform.origin

Now my tone might put you off at the start, but you know that what I'm suggesting is logical and not seeing that is I hate to say it stupid. I'm suggesting that you allow for the programmer to make the choice of being explicit where it's appropriate, it will allow for autocomplete to work without having to resort to "as Type" or ": Type". You both are gate keeping a dumb idea and one that could be vastly improved.

**Comment by pycbouh** [comment]
> Now you're telling me that you prefer to do this:
onready var nav = $"../Navigation" as Navigation
onready var player = $"../Player" as KinematicBody

Not that it's important what I prefer, but no, I don't like casting here as that makes errors only apparent on property access. I prefer using type hints, as they allow for explicit typing and would throw on assignment.
```
onready var nav : Navigation = $"../Navigation"
onready var player : KinematicBody = $"../Player"
```

> I'm suggesting that you allow for the programmer to make the choice of being explicit where it's appropriate, it will allow for autocomplete to work without having to resort to "as Type" or ": Type".

You are complaining about GDScript having an unfamiliar syntax, but functionally what you suggest doesn't change how it would work. `var name : Type` is the correct way to give a variable an explicit type. It's not a hack or trick that you resort to, it's what the syntax is in that language, whereas in another language it could've been `Type name`.

Now, there are also bugs with typing in GDScript as it was added at a later date on top of existing language. This is partially addressed in Godot 4, with a parser rewrite. Maybe some fixes can also be made in 3.x releases, but that's a pretty hard job to do due to the architecture of the language backend. However, none of these problems are because of the syntax chosen. There would be no difference from how we arrange words here. (Well, it would complicate the parser a bit, since a member or a variable declaration would no longer have an explicit keyword at the start. But not the point.)

-----

Now, I'm keeping this open in case you want to calm down, stop disrespecting other engine users and contributors, and stop breaking the Code of Conduct.

**Comment by Mortecha** [comment]
I am not politically correct and I don't care about feelings, I also am happy to break things in order for them to improve so apologies for not fitting in the mold of you're ideal contributor. However I mean well and my only interest is improving GDScript as it has alot of potential and I like that it just works out of the box. 

Yes this is a complaint about syntax as familiarity is also a benefit. What if I'm right though? Godot will naturally be picking up users from Unity like myself and Unreal, the conventions I've brought up are from these perspectives and future users will also find the syntax odd. GDScript is also open source, it should be allowed to be critiqued in this way with the benefit of improving because of it.  

Complaints can also signal and underlying issue as well. And the underlying issue is that GDScript is trying not to be C# when there's no problem if it does in some aspects, like explicit variable type declaration. I'm not suggesting that you remove the var : paradigm that already exists, just allow for explicit variable declaration as well to keep me and who knows how many other people who feel the same way happy with it too.

**Comment by pycbouh** [comment]
> just allow for explicit variable declaration as well to keep me and who knows how many other people who feel the same way happy with it too.

There is already an explicit variable declaration syntax, it's `var name : Type`.
