### ISSUE TITLE
Add `Input.get_vector()` for Vector3

### ISSUE THREAD

**Issue by weirdybeardyman** [godotengine/godot-proposals#3702]
### Describe the project you are working on

A 3d modelling app made in Godot.

### Describe the problem or limitation you are having in your project

To create a 3d flying camera that moves in three axis (up-down, left-right, back-forth) I need to get two of the axis with Input.get_vector() and then the third with Input.get_axis and then combine them together.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an Input.get_vector() equivalent that takes three axis and returns a Vector3.
It is admittedly not the worst missing feature in the world, but it makes sense to me that if there is an Input.get_axis() and Input.get_vector() then there should also be a 3 axis function. 
This could be useful for flying cameras and vehicle controllers that require 3 axis of control such as planes, submarines, ect.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Of course a more suitable name would be needed but would it be as simple as copying the current Input.get_vector() function and changing it to this?
```cpp
Vector3 Input::get_vector_3(const StringName &p_negative_x, const StringName &p_positive_x, const StringName &p_negative_y, const StringName &p_positive_y, const StringName &p_positive_z, const StringName &p_negative_z, float p_deadzone) const {
	Vector3 vector = Vector3(
			get_action_raw_strength(p_positive_x) - get_action_raw_strength(p_negative_x),
			get_action_raw_strength(p_positive_y) - get_action_raw_strength(p_negative_y),
            get_action_raw_strength(p_positive_z) - get_action_raw_strength(p_negative_z));

	if (p_deadzone < 0.0f) {
		// If the deadzone isn't specified, get it from the average of the actions.
		p_deadzone = 0.25 *
				(InputMap::get_singleton()->action_get_deadzone(p_positive_x) +
						InputMap::get_singleton()->action_get_deadzone(p_negative_x) +
						InputMap::get_singleton()->action_get_deadzone(p_positive_y) +
						InputMap::get_singleton()->action_get_deadzone(p_negative_y) +
						InputMap::get_singleton()->action_get_deadzone(p_positive_z) +
						InputMap::get_singleton()->action_get_deadzone(p_negative_z));
	}

	// Circular length limiting and deadzone.
	float length = vector.length();
	if (length <= p_deadzone) {
		return Vector3();
	} else if (length > 1.0f) {
		return vector / length;
	} else {
		// Inverse lerp length to map (p_deadzone, 1) to (0, 1).
		return vector * (Math::inverse_lerp(p_deadzone, 1.0f, length) / length);
	}
	return vector;
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently you can either Input.get_axis() 3 times or Input.get_vector() and Input.get_axis() for the third axis.
```gdscript
var horizontal_input : Vector2 = Input.get_vector("fly_left","fly_right","fly_forward","fly_back")
var vertical_input : float = Input.get_axis("fly_down","fly_up")
var combined_input = Vector3(horizontal_input.x, vertical_input, horizontal_input.y)
transform.origin += combined_input 
```

### Is there a reason why this should be core and not an add-on in the asset library?

This would be an added function in the Input singleton.

**Comment by Calinou** [comment]
cc @aaronfranke 

`Input.get_vector` would likely have to be renamed to `Input.get_vector_2()` to avoid ambiguity.

**Comment by groud** [comment]
I don't think the feature is needed.

We added the `get_vector` function partially because it was needed to handle circular deadzones (those circular deadzones are often preferred with thumbsticks). Such type of deadzones was complex to implement using two `get_axis` calls or four `get_action_strength`, as each axis deadzone was dependent on the other axis value. That's why we made `get_vector` built-in, and why it supports circular deadzone by default.

On the other end, I don't think there are any 3D input device that would require use of a "spherical" deadzone: the third axis there is usually independent from the others, maybe with two buttons or a wheel. So there's not a lot of reasons to make it built-in IMO.

A `get_vector3` would be quite confusing with circular deazones too btw, as it would mean we would need a way to precise which two axes are supposed to form a circular deadzone out of the three axes. Consequently, I think requiring the users to be explicit here, using `get_vector` and `get_axis`, makes more sense.

**Comment by weirdybeardyman** [comment]
> 

Fair enough, that makes a lot of sense!

**Comment by aaronfranke** [comment]
For the reasons @groud mentions, `Input.get_vector()` is for 2D inputs like a joystick. If you need to control a flight system with a joystick and another axis, then you should use `Input.get_vector()` and `Input.get_axis()` for those inputs respectively.

**Comment by weirdybeardyman** [comment]
Should this proposal be closed then? If so should I close it or will @Calinou do that?
