### ISSUE TITLE
Remove `&&`/`||` keywords in favor of `and`/`or` in GDScript

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3763]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

`&&` and `||` have been supported as alternative syntax for `and` and `or` since the dawn of GDScript. These operators had the same precedence and behaved exactly the same. There are languages such as Ruby where `&&` and `||` have greater precedence, but I consider this to be a can of worms that can easily bite newer programmers. Instead, it's better to rely on parentheses even if it's slightly more verbose.

However, since there is no practical benefit to using those operators, it's better to stick to a single operator for consistency.
For comparison, Python does not support `&&` and `||` – it only supports `and` and `or`.

`&&` and `||` will remain in the shader language as there are no `and` and `or` keywords there.

I remember the deprecation of `&&`/`||` being hinted by @vnen (to the point of a warning being added to the GDScript compiler), but I oddly can't find this warning now.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Remove support for the `&&` and `||` keywords in GDScript.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See pull request:

This is a compatibility-breaking change, so a decision needs to be taken before Godot 4.0 is released.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core GDScript functionality.

**Comment by pycbouh** [comment]
I am absolutely against this change. This will greatly reduce comfort coding with GDScript and reading scripts written in GDScript to me. It's much harder to identify logical statements when they are written similar to plain English, but not quite readable as natural text. Plus, there are still a lot of operators left that don't have counterparts, so it's going to be less consistent overall as a result.

**Comment by Mickeon** [comment]
I believe both should coexist. I can see the exclusion of `&&` and `||` when working with binary numbers to be off-putting for some, especially since their bit-wise versions `&` and `|` would remain unchanged.

Being very common operators across multiple languages, I see little reasons to _outright_ remove them, but I suppose it does make sense to optionally discourage their use through a warning, so that people in a team may write more consistently.

**Comment by Xananax** [comment]
I'm not really clear on why this would be useful. 

`&&` and `||` are used widely enough across languages that even if they are freed, they still shouldn't be allowed as regular identifier characters. So we wouldn't really free them for other uses, we'd simply make them forbidden characters. The reasons will be hard to explain to newbies: "`|` is not allowed in identifiers because it's used to mean something in other languages". 

I understand wanting consistency, but while there's something to be said for having everyone's code look the same (something I'm very much a partisan of), we know from the attempt of Python and others that:

1. it's mostly a theoretical benefit, because unless you make the language prohibitively restrictive, code will still end up differing quite a lot
2. GDScript already isn't consistent enough to offer that benefit (typed/untyped code, cast code, `onready`, ...)

It could be equally said that this change is _more inconsistent_ with:

1. shaders
2. bitwise operators

Lastly, while this PR wouldn't really achieve the desired homogeneity, people who are used to programming in other languages would have to overcome deeply ingrained reflexes. I am myself a big proponent of `and` and `or`, and prefer using them. Yet, even after years of GDScript, I still write `&&` and `||` a lot of times, specially when I'm in flow.

**Comment by PolyVector** [comment]
I personally find keywords like "and/or" awkward and difficult to read when used as logical/math operators and have never used them in my years with Godot. Symbols visually stand out as they make invalid characters for variable/method names.

A silly extreme example of what I mean might be "if motor and band or not noted" but this is how I feel when reading/writing code this way. It's a reason I find GDScript more readable than python.

The logical operators also maintain their similarity with the bitwise versions of and/or.

This feels like a change for the sake of it where the headaches will outweigh any minute benefit from eliminating redundancy.

_Reposting this in the correct place, oops! 😬_

**Comment by Mickeon** [comment]
If anything, I would suggest putting `&&` and `||` on par with their more readable equivalents, and have them be syntax highlighted the same way. 

Currently
![image](https://user-images.githubusercontent.com/66727710/148289906-71d5a626-b8bb-43a6-92a7-4ed07c7ee18c.png)
What I mean:
![image](https://user-images.githubusercontent.com/66727710/148289929-62a688a5-5afd-41a6-acc0-d8f2eee7d078.png)

Although, during the writing of this suggestion, I realised that this would be nonsensical and inconsistent, as their colour is specifically tied to the fact that they're symbols. But, perhaps my comment can be food for thought.

**Comment by AttackButton** [comment]
I know it is closed, but I need to say `&&` and `||` are so easy to read and there are a lot of other examples that exist in the same way. Like the boolean not:

![image](https://user-images.githubusercontent.com/25422687/148334274-8f09f8b8-13c3-46ca-b107-8b1206e47235.png)

I think `if !var_test:` can be read faster than `if not var_test:`.

**Comment by pycbouh** [comment]
For anyone interested, the upcoming built-in code formatter for GDScript will be capable of forcing one style or the other (in fact, it will be required to unify the style, because those variants are tokenized the same internally).
