### ISSUE TITLE
Change the default editor font to look better on small displays

### ISSUE THREAD

**Issue by SoyoTamo** [godotengine/godot-proposals#3764]
### Describe the project you are working on

Nothing important.

### Describe the problem or limitation you are having in your project

For low resolutions the new font for 4.0 can be quite unreadable compared to 3.x, and downloading fonts to test it and adding it can be quite cumbersome.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have at least 3 or 4 font options (which may have already been considered before but ended up being discarded [including 3.x]) from which to choose at ease, just as with themes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It could be, but it's not the best at all.

**Comment by Calinou** [comment]
The default editor font in `master` is exactly the same as in `3.x`. It also uses the same default size.

**Comment by SoyoTamo** [comment]
Ok I give you the saving of space, but the blur is a real thing for me.

4.0:

![IMG_20220105_221146](https://user-images.githubusercontent.com/95949771/148317168-2384ae3f-236d-494e-9ae3-17a6a3fbb188.png)

3.4.2:

![IMG_20220105_220647](https://user-images.githubusercontent.com/95949771/148317199-472410e0-34be-4611-be38-6d5482dbbeb4.png)


Same configuration, really my resolution is not the best, but in 4.0 I have to work a bit to read, something that does not happen in 3.x at all.

**Comment by pycbouh** [comment]
Is that your native resolution? It's very hard to tell the difference at this scale, both seem to be equally blurry and unreadable. But my guess is that bold font makes it look more noticeably blurry in your case. I'm not sure there is much we can do here, there is just not a lot of pixels to work with. You may benefit from a special font there.

**Comment by SoyoTamo** [comment]
Yes :(, and no, both are not equally blurry and illegible, the font in 4.0 is thicker

**Comment by SilencedPerson** [comment]
While there is discussion going on about the font, the boldness made it less legible for me too.

**Comment by SoyoTamo** [comment]
Well, good that I'm not the only one. It should be noted that I am in 1024x600 and I think it should also be a problem for 720p (something more normal). And I really think it looks less professional as well as less readable.

**Comment by SoyoTamo** [comment]
I also do not see fair that for a certain number of users going from 3.x to 4.0 is a decline compared to reading.

**Comment by pycbouh** [comment]
You can always use editor UI scaling to make it more legible. If those screenshots are at one to one scale, that's practically unusable in either version of the engine, compression or not. If you don't want to change the scale, then using a font that is designed for small resolutions is your only other option. You may also want to disable font antialiasing in the settings, and play around with hinting.

**Comment by SoyoTamo** [comment]
That is not a real solution, simply enlarging the font only makes the editor go off the screen in some cases.

**Comment by pycbouh** [comment]
At no point did I say that the font in 4.0 is not bold. I know that it is bold. In fact I stated that it is bold in my first reply here, and suggested that that's the likely cause of your problem in 4.0. My point is, that in your screenshots the text is blurry even in 3.4, even with a normal font. Bold font only increases the effect that is already present on your setup.

To counter it you can disable the font antialiasing. Your GPU drivers can also have a feature to increase sharpening that may help. You have options.

There is nothing there to prove, I can already see your problem in both 3.4 and 4.0. We are definitely not going to revert the bold fonts as they make user experience better for most. And there is a strong incentive to not include multiple fonts packaged with the editor, namely because you can set any font you want yourself. I don't use the default fonts for example, I prefer IBM Plex for the main editor font. And so I suggest ways in which you can mitigate the problem for yourself. It's up to you to take the advise or not. 🤷

**Comment by Calinou** [comment]
This is likely because Godot 4.0 renders DynamicFonts with filtering enabled by default, whereas Godot 3.x rendered them with filtering disabled by default. In situations where they don't line up on the pixel grid perfectly, this will cause them to look more blurry.

Solutions would be to disable filtering on DynamicFonts by default, or enable 2D vertex and transform snapping in the editor.

**Comment by SoyoTamo** [comment]
> En ningún momento dije que la fuente en 4.0 no está en negrita. Sé que es audaz. De hecho, dije que es audaz en mi primera respuesta aquí, y sugerí que esa es la causa probable de su problema en 4.0. Mi punto es que en sus capturas de pantalla el texto es borroso incluso en 3.4, incluso con una fuente normal. La fuente en negrita solo aumenta el efecto que ya está presente en la configuración.
> 
> Para contrarrestarlo, puede deshabilitar el antialiasing de fuentes. Los controladores de la GPU también pueden tener una función para aumentar el afilado que puede ayudar. Tienes opciones.
> 
> No hay nada que probar, ya puedo ver su problema tanto en 3.4 como en 4.0. Definitivamente no vamos a revertir las fuentes en negrita, ya que hacen que la experiencia del usuario sea mejor para la mayoría. Y hay un fuerte incentivo para no incluir múltiples fuentes empaquetadas con el editor, es decir, porque puede configurar cualquier fuente que desee usted mismo. No uso las fuentes predeterminadas, por ejemplo, prefiero IBM Plex para la fuente del editor principal. Y por eso sugiero formas en las que puedes mitigar el problema por ti mismo. Depende de ti tomar el consejo o no. 🤷

Deactivating it does not solve anything, it looks even worse, if it were not something annoying I would not comment on it

**Comment by SoyoTamo** [comment]
> Esto es probable porque Godot 4.0 representa DynamicFonts con el filtrado habilitado de forma predeterminada, mientras que Godot 3.x los representa con el filtrado deshabilitado de forma predeterminada. En situaciones en las que no se alinean perfectamente en la cuadrícula de píxeles, esto hará que se vean más borrosos.
> 
> Las soluciones serían deshabilitar el filtrado en DynamicFonts de forma predeterminada, o habilitar el vértice 2D y transformar el ajuste en el editor.
> 
> PD: En pantallas pequeñas (1366×768 y más pequeñas), el editor usará automáticamente la escala del editor del 75% en lugar del 100% para seguir siendo utilizable.

I know that this configuration helps, but even so in some moments it can be left, I do not expect them to fix that, I know it is difficult

**Comment by SoyoTamo** [comment]
If you say Godot can detect resolution and do something about scaling, maybe they should also make DynamicFonts turn off at low resolutions, in case that's the issue

**Comment by Calinou** [comment]
> maybe they should also make DynamicFonts turn off at low resolutions, in case that's the issue

This is not about disabling DynamicFonts. The issue you're reporting here seems to be a consequence of the Vulkan renderer using linear filtering by default (which affects things like https://github.com/godotengine/godot/issues/45081). I would say it's more of a bug than a feature request, so it may be better to report this on the main Godot repository instead of here.

**Comment by SoyoTamo** [comment]
Well I'll end up doing it eventually at https://github.com/godotengine/godot-demo-projects

**Comment by Calinou** [comment]
> Well, I'll end up doing it at [godotengine/godot-demo-projects](https://github.com/godotengine/godot-demo-projects)

The demo projects repository is unrelated to the [main Godot repository](https://github.com/godotengine/godot).

**Comment by SoyoTamo** [comment]
oh, my fault, i thought its a problem not related to some current version

**Comment by Calinou** [comment]
When the editor scale is set below 100% and the font hinting mode is Auto, it might be worth using Normal hinting instead of Light hinting (or None on macOS). This usually makes for sharper font rendering.

**Comment by Calinou** [comment]
I think the new [spacing presets](https://github.com/godotengine/godot/pull/87085) works well for now, although it doesn't automatically change the font size (as this may be undesired on laptops, where the default font size can already be quite small).
