### ISSUE TITLE
Add a new 'is_finite' method for checking built-in types

### ISSUE THREAD

**Issue by AncRad** [godotengine/godot-proposals#3790]
### Describe the project you are working on

I am working on tools for the editor, 3D and 2D games. Of the programming languages I use only GDScript. I plan to host the tools in AssetLib, and it's important to me that my addons always handle exceptions. My addons have many Float-based properties open to the user, such as Vector2, Vector3, Transform and others.

### Describe the problem or limitation you are having in your project

As strange as it may sound, but Real numbers are not always really Real.
The problem lies in the lack of a universal way to check most of the built-in types using Real, such as Float, Transform (2D, 3D), Vector (2, 3), Rect2, Basis, AABB and others.
Yes, in @GDScript there are methods `is_inf(float)` and `is_nan(float)`, and in this case the record I need gets the following form: `not is_nan(value) and not is_inf(value)` - this takes up a lot of space. The entry for the other types looks a little longer, for example, `not is_nan(vector2.x + vector2.y) and not is_inf(vector2.x + vector2.y)`, for Vector3 it is not much longer, and for Transform it looks like this: `not is_nan((transform * Vector3()).length()) and not is_inf((transform * Vector3()).length())`
It's all very cumbersome. Prescribing the same method in different classes is not very convenient and contradicts the principles of OOP. The use of Singletons hinders decentralization and is often not considered by some programmers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The solution to the problem is to add a new method to all the built-in types from the following list: Vector2, Vector3, Plane, Color, Rect2, Quat, AABB, Basis, Transform2D, Transform. And by adding a method to @GDScript for float. These methods will return true if all components of the built-in type fulfill the condition `not is_nan(component) and not is_inf(component)` and false in the opposite case.
This method can have the form as in many common programming languages: `bool is_finite(value: float)` and `bool type.is_finite()`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
print(is_finite(1.0)) # prints true
print(is_finite(NAN)) # prints false
print(is_finite(INF)) # prints false
print(Vector3(0.0, 0.0, INF).is_finite()) # prints false
var transform := Transform.IDENTITY
print(transform.is_finite()) # prints true
transform.origin.x = NAN
print(transform.is_finite()) # prints false
```
![is_finite](https://user-images.githubusercontent.com/16743532/149069345-4edb782a-8ccd-4f9d-9111-6d30f2f92e2b.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If this is not used often, then it can be implemented in a few lines of script. But checking this exception may be required anywhere in any project.

### Is there a reason why this should be core and not an add-on in the asset library?

There is a reason, everything is the same as with the `is_inf` and `is_nan` methods. After all, they can be replaced with entries `value != INF and value != -INF` and `value != NAN`

**Comment by AncRad** [comment]
In addition, methods may be required to check the arrays PoolRealArray, PoolVector2Array, PoolVector3Array, PoolColorArray. After all, GDScript code iterating over a large array can be a bottleneck, and a low-level implementation can solve this problem.

**Comment by aaronfranke** [comment]
> and `value != NAN`

NaN is not equal to itself, so `value == NaN` is always false and `value != NaN` is always true. If you wanted to replace `is_nan` then the function you would need is `value != value`.

> The solution to the problem is to add a new method to all the built-in types from the following list: Vector2, Vector3, Plane, Color, Rect2, Quat, AABB, Basis, Transform2D, Transform.

If added everywhere, that's a lot of methods to add. Arguably it wouldn't be used often in many of those structures, since checking if those values are valid is more complex than just checking if it's infinity or NaN. For example, with a Basis you want the vectors to be linearly independent, and for Quaternion you want the values to form a valid rotation. If you're validating a Basis or transform it would make sense to just validate the determinant.

**Comment by dalexeev** [comment]
I support this proposal because this method is available in other programming languages such as JavaScript and PHP. Also note that both `is_inf(NAN)` and `is_finite(NAN)` must return `false`, so `is_finite(x)` is not equivalent to `not is_inf(x)`.

If we add the `is_finite` method, then it makes sense to rename `is_inf` to `is_infinite` in 4.0.

> If added everywhere, that's a lot of methods to add. Arguably it wouldn't be used often in many of those structures, since checking if those values are valid is more complex than just checking if it's infinity or NaN.

This is an analogue of the `is_equal_approx` method, which many base types also have.

<details>
<summary>Screenshot</summary>

![](https://user-images.githubusercontent.com/47700418/149455147-c04ebf68-3570-4d22-a622-8ac10b715ad3.png)

</details>
