### ISSUE TITLE
Change the default Toggle Comment shortcut from Ctrl + K to Ctrl + #

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot-proposals#3822]
### Describe the project you are working on

This regards all source code written in the editor, by everyone who uses it.

My apologies if this is not the place to post a suggestions for the editor,
but two pages directed me to github for proposals.

### Describe the problem or limitation you are having in your project

As a heavy user of Sublime, CTRL+K screws with my muscle memory and now I am repeatedly using the wrong shortcut.
In both editors. It's a horribly distracting, accumulative waste of life-time. It's not just the second I'm losing to this,
but the "being ripped out of my flow" causing frustration.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose this shortcut for being added as a default, because I am used to it in Sublime. It's incredibly intuitive being able to comment out a line at the press *of the key that's actually used for commenting*. I can understand that I could just get used to using CTRL+K, but I have reasons why I believe it should be CTRL+# instead of CTRL+K.

1. Sublime has a userbase of 17 million people (according to careerkarma.com), who are used to using CTRL+[Un-/Comment Character].
2. It makes a lot of sense to have the shortcut be CTRL+[Un-/Comment Character] and there is no obvious connection between comments and the letter K, not counting german's word "Kommentar".
3. All of those who also use Sublime don't have to change the shortcuts or screw with their muscle memory.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Uh ...

[Grand Vision of Sublime's Users' workflow becoming a tiny bit more optimized/less disrupted]

### If this enhancement will not be used often, can it be worked around with a few lines of script?

My proposal is related to the editor.
My apologies if this is not the correct place.
If so, please point me to where it belongs.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a convenience issue, which, I believe, should be in the editor by default.

In my admittedly worthless opinion this short-cut should be default across all text editors ever,
simply because it makes intuitive sense to have CTRL+[Comment Character] as the hotkey for un-/commenting a line.

Thank you for your scaringly valuable time.

**Comment by pycbouh** [comment]
> As a heavy user of Sublime, CTRL+K screws with my muscle memory and now I am repeatedly using the wrong shortcut.

> I propose this shortcut for being added as a default, because I am used to it in Sublime.

Well, I thank you for being so candid 🙃 However, we cannot change defaults based on some user's personal preference. You can, however, rebind the shortcut however you want using the editor settings.

> All of those who also use Sublime don't have to change the shortcuts or screw with their muscle memory.

You can always keep using Sublime with Godot by connecting to Godot editor's LSP for GDScript.

> I have reasons why I believe it should be CTRL+# instead of CTRL+K

I have one for the opposite: there is no `Ctrl + #` in my keyboard layout. It would be `Ctrl + Shift + 3` for me. Not useful at all.

**Comment by Mickeon** [comment]
For me, the **CTRL + K** shortcut is pretty far away. Furthermore, in my keyboard layout, **#** is not an easily accessible character, either. I mapped the shortcut to **CTRL + Q** and I have been quite comfortable with it, and I look forward to do something similar in future IDEs I'm going to use.

That's to say, that shortcuts can be highly personal. It varies as a result of personal taste, coding style, habits, past experience, and of course, keyboard layout.
But fortunately, keyboard shortcuts can be personalized from the default, without impacting any other user's preferences.

**Comment by AhmedElTabarani** [comment]
In Vscode and most IDE, we use `Ctrl` + `\` so we can use the same short cut ?

**Comment by Mickeon** [comment]
When I was first beginning with Godot, something about the **CTRL + K** hit well.
Shortcuts are always really overwhelming to learn and master. **CTRL + D** makes sense to me because the "D" stands for "Duplicate". Likewise, "O" stands for "Open...", and further modifier keys change its subject _("Quick Open Scene, Open Script"...)_.
I personally associate the "K" in the shortcut to "**K**omment". It's not quite right, but like the aforementioned shortcuts, I don't find it ambiguous, it makes them easier to remember.
Unfortunately, unlike most characters, "#" is not very consistent across all keyboards. On some, **CTRL + #** may even be inaccessible.

> In Vscode and most IDE, we use `Ctrl` + `/` so we can use the same shortcut ?

`Ctrl` + `/` in **GDScript** specifically wouldn't make much sense. [There have been proposals to use "//"](https://github.com/godotengine/godot-proposals/issues/3794), but comments in GDScript can only be done with "#" as it is. In a way, the original proposal seems more reasonable.

**Comment by Xrayez** [comment]
> `Ctrl` + `/` in **GDScript** specifically wouldn't make much sense. [There have been proposals to use "//"](https://github.com/godotengine/godot-proposals/issues/3794), but comments in GDScript can only be done with "#" as it is. In a way, the original proposal seems more reasonable.

I'm for <kbd>Ctrl + /</kbd>. I think it's not tied to specific style comment, because it works correctly depending on a language you're editing in IDE (at least that's the way in VS Code).

**Comment by jcostello** [comment]
`Ctrl + /` is more common in other IDEs. I would use it

**Comment by SolsticeProjekt** [comment]
Well, I guess that predictably got shot down.

`Ctrl + /` would be horribly cumbersome for anyone using a german keyboard layout.

**Comment by Xrayez** [comment]
> Am I supposed to be the one who closes this, or should I keep it open?

There's no need to close it yourself, it's the maintainers in Godot who should decide (based on [general consensus](https://godotengine.org/governance)). But I think we have useful insights here anyways. 🙂

**Comment by Gurigraphics** [comment]
I think this should be customizable by default as in any IDE.

Because it's like language translation content. This is not something that should be embedded in a compiled file.
It should be in a separate file to be easily edited manually, whereas a visual editor doesn't handle this.

As I already commented in the other topic:
Everything that there is no evidence that it is the best option, becomes the best option when it can be customizable.

In my case, Ctrl + / is the best option. 
Ctl + k is tolerable. 
And Ctrl + #, it's the worst option. I would never use.

**Comment by SolsticeProjekt** [comment]
Hm. So much depends on the keyboard's language layout.

I can see now why K makes sense.
Symbols can vary, letters (besides cyrillic, mandarin, etc.) don't.

I guess using letters also means there's no need for different shortcuts depending on a keyboard's layout.

**Comment by SolsticeProjekt** [comment]
Related to shortcuts: https://www.youtube.com/watch?v=qKLkkqOl7sY

This is about the Add-On Jam. AT 0:12, the first one, he introduces an add-on
which sets the shortcuts for Blender for Rotation, Scaling and Movement in the editor.

I post this, because apparently there *is* some need for care regarding shortcuts.

I can understand that it makes no sense to support shortcuts for *all* the tools,
and of course, "where do you draw the line?" applies, but it's still interesting to note.

There's demand for common shortcuts amongst the tool chain.
In this case, people who use Godot also often use Blender.

It's a massive hassle needing to "muscle-memory" *both* sets of shortcuts,
because it's super easy to constantly get it wrong. This adds to what I've predicted
about my own behaviour above:

I've started using CTRL+K in Sublime and it's REALLY annoying! lol

Yes, I know I can solve this problem myself, but my point is that "helping myself"
kind of stops being a good solution when it's scaled up,
which is why there's demand for an Add-On which sets the Blender shortcuts in Godot's 3D editor.

I'm sorry for all the words.

**Comment by pycbouh** [comment]
Blender shortcuts are not just about having familiar shortcuts, they come with behavior. Their usefulness is not in having G specifically being bound to translation, but in the tricks you can do with locking axes and switching local and global transformation coordinates on the fly.

It can be any other key instead of GRS.

**Comment by SolsticeProjekt** [comment]
I don't understand why you mention the obvious.

Of course it makes no difference *which* key it is,
as long as *it's the same keys* in both programs.

**Comment by pycbouh** [comment]
You've missed my point. I'm saying that "Blender shortcuts" are useful regardless of which keys we assign to them in Godot. Mechanical memory is good, but those actions are useful because of their functionality, not because of the familiarity of the keys assigned to them. They can in fact differ from Blender and be useful.

Regardless, Sublime is nowhere near an equivalent in that regard.

**Comment by SolsticeProjekt** [comment]
> You've missed my point. I'm saying that "Blender shortcuts" are useful regardless of which keys we assign to them in Godot. Mechanical memory is good, but those actions are useful because of their functionality, not because of the familiarity of the keys assigned to them. They can in fact differ from Blender and be useful.

Ah, I see your point now. You're right as long as we ignore muscle  memory.

Which we can't.

The familiarity to keys matters a lot,
because muscle memory matters a lot for using computers, especially in a mostly non-annoying way.

Imagine needing to switch muscle memory for copy/paste every time you switch from Windows to Linux or Mac.
Worse, imagine all three of them having a separate set of hotkeys for this.
There's a reason why they're the same everywhere and it's a damn good one.

Muscle memory is slow to adapt and
it's incredibly annoying getting used to another movement pattern for a task already memorized.

The brain sends the signal, the muscles just move. That's how we type.
Besides wanting to do the task, there's no conscious action involved once it's learned.

When you change the environment the brain will still fire the same signal causing the same movement,
ending in frustration, because the movement is wrong.

That's why that add-on implemented the blender shortcuts with the actual blender shortcuts.

It *matters* that it's the same keys.
Just how it matters that copy/pasting has the same hotkeys across all platforms.

**Comment by Gurigraphics** [comment]
> I think this should be customizable by default as in any IDE.

In fact, this is already customizable.  

Go to Editor -> Configurations -> Shortcut tab -> Script Text Editor -> Toggle comment -> click edit -> and press combinations keys

You can choose what I think is best:
```
Control+BackSlash
Control+Slash
Control+Period
Control+Hastag
```
I choose Ctrl+"/" and it was like this
```
Control+Unknown
```
But, this works.

**Comment by aaronfranke** [comment]
Even if Ctrl+# doesn't exist on many people's keyboard layouts (it's Ctrl+Shift+3 for me too), I think it's still fine since I just wouldn't use it.

On macOS, Cmd+Shift+3 takes a screenshot of the screen, so I guess code would be commented if you tried to take screenshot with this shortcut while focused in the script editor? But it's not a big deal, you can just unbind the shortcut, or unfocus the script editor, or take a screenshot another way.

If it's a usability improvement for many users then I think it's worth it.

**Comment by SolsticeProjekt** [comment]
Wow, this is still active!

**Comment by AThousandShips** [comment]
@SolsticeProjekt Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

Remember, you ping a lot of people by adding comments like this
