### ISSUE TITLE
Clarify ambiguous terminology in new TileMap editor prompt

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot-proposals#3874]
### Describe the project you are working on

Generic TileMap workflow

### Describe the problem or limitation you are having in your project

As discussed in #1769, there's a risk that first-time users will have a difficult time with setting up a TileMap. In particular, this prompt is shown once a TileSet has been added, before the TileSet has been edited:

![image](https://user-images.githubusercontent.com/61291296/151259826-8445dae3-31c9-4297-9546-f49a2fbdf61a.png)

Right clicking the TileSet resource in the inspector and choosing "edit" seems like a reasonable response to this prompt, but instead the user needs to click on "TileSet" in the bottom panel (which more experienced users might know will take them to the TileSet **editor**).

While prompts in the editor can't be expected to guide users through the whole process of setting up a TileMap, this one in particular feels like it's pointing people in the wrong direction.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Reword this prompt, maybe to `This TileMap's TileSet has no source configured. Open the TileSet editor to add one.` (though this still doesn't make clear what the TileSet editor is).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a basic editor prompt.

### Is there a reason why this should be core and not an add-on in the asset library?

Improves first-time user experience for anyone setting up a TileMap.

**Comment by groud** [comment]
If it makes things clearer, I am ok with the idea. I am open to suggestions on how to phrase it exactly.

**Comment by Oryss** [comment]
First time user here, I found this topic when searching for this message because I had no idea what I was supposed to do :-)

**Comment by Calinou** [comment]
As of 4.3.dev3, the description is now:

> This TileMap's TileSet has no source configured. Go to the TileSet bottom tab to add one.

Is this considered sufficient? It seems clear to me at least.

**Comment by s4m2d** [comment]
I came here too by searching for, what this means, since it is really not straight forward at all. If you look from an UX perspective, there should be a clear indication - or better - a button to directly fix the issue (add a set).

- Also the bottom "tabs" are in the part where you log and debug -> This is the wrong context from an UX perspective
- Normally you search in the editor (right window pane) -> there is also no option to add it, it breaks with the UI conventions Godot uses.

**Comment by KaijuKoder2** [comment]
Agree the workflow/messages here is very confusing, even if you get there in the end, takes a while to figure out:  

The "This TileMap's TileSet has no source configured. Go to the TileSet bottom panel to add one" message is confusing, because there's nothing explicitly labelled 'source'. Then you look at the side panel also labelled TileSet. (Pic 01) The initial message is clear enough: "The edited TileMap or TileMapLayer has no TileSet resource. Create or load a TileSet resource property in the Inspector."  But the second message "This TileMap's TileSet has no source configured. Go to the TileSet bottom panel to add one" is confusing, because you're now looking for a control labelled "source" which doesn't exist. If you go into the TileSet bottom panel tab the 'Tiles' (next to 'Patterns') box does talk about sources at the side, but the 'Tiles' area isn't labelled 'Tiles Sources' from which comes the confusion. Everything in these nodes is 'Tiles something' so when something is actually 'Tiles Sources' but labelled as 'Tiles' it's confusing.

Once you figure it out (took me a couple of hours) it's quite good but it's a long journey to find your way.

This exact sequence works:
1. Create TileMapLayer
2. In Right-hand Inspector Panel "TimeMapLayer" TileSet <empty> New Tileset (Expand that 'TileSet' and configure grid type size etc)
3. In Bottom Panel choose Tileset, then drag in your PNG to big Tiles box  
4. But If you choose to TileMap bottom panel tab and try and paint in the main window nothing happens(!!!)
5. But if you go back to TileSet bottom panel tab and seemingly click on any of the base tiles (not necessarily the one you want to paint!) (note the Setup|Paint|Select buttons don't seem to do anything to the TileMap painting node), now if you go back to TileMap bottom panel tab and now click on any of the base tiles you can paint those. 

**Some Suggestions:** 

**(1) Consistency in the labelling.** That tab should be labelled and referred to as 'Tile Sources' (upper case 'S') both on panel and in the message "This TileMap's TileSet has no Tile Sources configured. Go to the TileSet bottom panel Tile Source to add one." Because there are many things labelled 'Tile' in these nodes so it'd help if that was clearer that the 'Tile' box is in fact the 'Tile Sources' box. 

**(2) Just activate it!** One difficulty with Godot is there are so many controls in so many panels, many sharing the same or similar names. e.g. 'Tiles" It's easy to get lost, so perhaps the easiest thing that could be done here is just to activate and open the TileSet tab for the user, and tell them 'drag your images into the Tile Sources box' (so labelled). I think that'd help. Perhaps more messages should be handled like this so they just active the control the user is required to complete (when possible) instead of requiring them to search for some obscure control.

(3) Step 4 in the procedure might perhaps be resolved by telling the user they must first click on a base tile in the TileMap tab (because the tile they selected in the TileSet tab has no effect). 

Also note people get confused painting with the TileSet  and TileMap tabs open. If you look at these youtube videos you'll see them frequently getting confused: 
https://www.youtube.com/watch?v=zCocC_x8URE
https://www.youtube.com/watch?v=HYnKrIM2s8s
