### ISSUE TITLE
Rename `BaseButton`'s properties to remove name conflicts and confusion

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-proposals#3877]
### Describe the project you are working on

Godot ✊ 

### Describe the problem or limitation you are having in your project

In Godot 3 `BaseButton`/`Button` had both a property and a signal called `pressed`. This was fine as long as signals were their own thing. This changed in Godot 4, where signals became first-class citizens and their identifiers have entered the common namespace. Which led to a [few conflicts](https://github.com/godotengine/godot/issues/38937), among which was button's `pressed` signal and property.

We [briefly renamed](https://github.com/godotengine/godot/pull/57101) the property to `button_pressed` before alpha to avoid this very annoying conflict in the first public outing, but we did this with a goal to eventually properly re-evaluate and rename it, or a signal, or a few related properties as well.

There is an open PR, but it is debated: https://github.com/godotengine/godot/pull/48193. As such, we need this proposal to first decide on what the new name/names should be.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Thanks to @KoBeWi we have a comprehensive list of various names for the `pressed` property in various frameworks and engines:

> * PyGame uses `pressed`, same as us
> * Roblox uses `activated`, this name was mentioned here before
> * Unity seems to have no event. You do `GUI.Button(Rect) some_action;`. Weird, but ok
> * nuklear does the same as Unity
> * Avalonia uses `Command` property, like `Command = something`
> * Tk does the same as Avalonia, but with `command`
> * remi uses `onclick` event
> * Haxe also uses `onClick`
> * Kivy uses `on_press`
> * quasar uses `@clik` event
> * nanogui uses `setCallback()` method instead of event
> * agar has a `button-pushed` event
> * Flutter uses `onPressed`
> 
> On the other hand, here's some random article that says "pressed" button state is actually "active": https://uxdesign.cc/button-design-user-interface-components-series-85243b6736c7

While `click` variations seem to be pretty common, there is also a strong argument in the aforementioned PR that buttons are not activated by clicking alone, so a more generic name should be more appropriate. Here are my takes:

* I am partial to calling the signal `activated` which maps to how we call signals for triggering items in `Tree` and `ItemList`. It's also a pretty good generic name, which should be obvious to everyone.
* I don't think that we need to rename the `pressed` property per se. But we can rename it to `active` for consistency.
* The virtual method `_pressed` should follow the name of the signal and be renamed appropriately.
* I would not follow the PRs approach and rename the `button_up/button_down` signals to `button_pressed/button_released`. I'm slightly in favor of the new naming, but I think that the new name `button_pressed` would be confused with the old name `pressed`, which used to mean a different event.
* Additionally I'm in favor of changing the boolean `toggle_mode` into an enum of options (`active_mode` perhaps?). I think it will make it clearer what this property does if we provide a list of possible settings, e.g. a choice between "Press" and "Toggle", or "Click" and "Hold".

However, there are other opinions for each option. So let us argue and discuss what would be beneficial for the most users and solve the name conflict the best.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is a mostly a rename change, no functionality is changed with it. If `toggle_mode` is replaced with an enum, we would have to adjust a few assignments and checks wherever we rely on it in the engine.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is an engine change to remove a naming conflict (and possibly improve the default user experience).

**Comment by TheDuriel** [comment]
My view:

Signal names should ideally relate to the action they represent. Pressed is intuitively clear in the context of a button. What does activating a button mean? Has it been Selected? Pressed? Focused? Enabled? Paused?

Pressing a button is the act of depressing it. Both visually, but at least physically. No matter keyboard, mouse, or controller input. You press a button to, well, press a button.

For the pressed property: Active can work here, depressed could too. Down is another option. But since this property relates to the ability for a button to be toggled, and is generally only used there, On, Active, or IsPressed, appear to be the more likely candidates. (is_ is usually reserved for functions that return booleans though.)

Random musings:

A button that is not toggleable, can not stay pressed. So the current pressed property is only ever set if the button is a toggle button, or while the user holds but does not release the button press. The latter is an arguably pointless use case that could justify making the exposed property only be about the toggle state. But I supposed there are some less common use cases where you might wish to poll the state of a button. Like for a press and hold scenario, directly and without using the signals. (I wouldn't. But hey, it's thinkable.)

**Comment by KoBeWi** [comment]
The temporary `button_pressed` name is actually consistent with `button_down` and `button_up` signals, so maybe it could left like that...

**Comment by pycbouh** [comment]
> The temporary `button_pressed` name is actually consistent with `button_down` and `button_up` signals, so maybe it could left like that...
> 
> EDIT: Ah, the property was renamed not signal. It should be the opposite.

We could do that as a safe option, but isn't it redundant? Both for the existing signals and for the proposed one.

**Comment by KoBeWi** [comment]
It is, but would we even consider renaming these signals if not the conflict? Current names are probably fine. But if the `pressed` were to be renamed to something else than `button_pressed`, we should likely rename the other `button_` signals too, so they are consistent.

**Comment by YuriSizov** [comment]
During the bikeshedding meeting we have arrived to an agreement. We want to rename the property, not the signal or anything else which is used more often. For the property we have agreed on the name `down` (so setget is `set_down`/`is_down`).

It was the least controversial option which everyone was fine with. We didn't find a perfect option, but this one did win the popular vote. So let's go with that.

**Comment by uberflut** [comment]
What about `is_pressed`? it matches the boolean "grammar" and it's continuist with the `pressed` signal naming. I think its the simplest way out of the problem.

**Comment by YuriSizov** [comment]
@uberflut It doesn't fit into our naming convention, because `is_pressed` is the name of the getter for the property. This is why we never call boolean properties with `is_*` as a prefix.

**Comment by uberflut** [comment]
I just read that in the other thread. Well what about changing the verbal time then? I think the signal should keep the pressed so we can keep calling `_On_Button_pressed()`, maybe the property could go 'pressing' but i find it less apealing than the 'down' option you already mentioned.

**Comment by aaronfranke** [comment]
Since it only works with `toggle_mode` set to true, maybe it should be `toggled` or `checked`?

**Comment by jordo** [comment]
I think `signals` / `events` that reflect a property state change, (ex:  pressed, focused, etc), which ultimately boil down to a property changing value ( example:  changing 'pressed' property from false to true), should be renamed to reflect the state of the property with the same nomenclature.  If I understand correctly it seems that the preference is to not break backwards compatibility on signals names, but I think that's the wrong call here.  At a major engine upgrade i think the priority should be for a clean API at the cost of compatibility across a major engine update (3.X -> 4.X).

My preference would be to keep state and properties as the named property.  

Example.  A property change of an object's 'pressed' property from false to true should trigger a 'onPressed' signal.  A property change of 'focused' from false to true should trigger the signal 'onFocused'.  

I think the priority shouldn't be for backwards compatibility here, and instead be focused on a clean and easy to understand API.

**Comment by jordo** [comment]
The signals in these situations are a direct result of a named property's state being changed, and are thus implicitly correlated.  So the naming convention between the signal and property should also be correlated.

**Comment by YuriSizov** [comment]
@jordo The signal here is not directly related to the property. The property is not used for buttons which are not in the toggle mode. So that wouldn't work.

**Comment by jordo** [comment]
Toggle mode is the same, the transition just happens transparently & immediately.   i.e. that particular mode doesn't allow for the button's property to stay 'pressed' as true.

**Comment by nsrosenqvist** [comment]
Just going to leave my 2 cents here, which I voiced in reply to @YuriSizov's question [on Twitter](https://twitter.com/nsrosenqvist/status/1567583022664372228?t=aCopJrQ3C4dUsNzmuqu2Ug&s=19):

> Maybe rename it to "active", to reflect the states available in CSS: "hover", "active", "focus", etc. "Activated" (past tense) doesn't accurately reflect a current state

**Comment by YuriSizov** [comment]
@jordo It's the other way around, actually. Toggle mode is the mode where the property is used. In the regular mode the property is not used. You can't even set it in the regular mode.

**Comment by jordo** [comment]
`signals` or in other naming conventions, `events` are a reflection of something changing `state`.  They are the change of one state to another, in some form or another.

If there is an object property that correlated with a signal (a change of state) in some way shape or form, the naming of the property and signal should be clear.   

It makes no sense to me to have a `down` or `activated` property, but then emit a signal called `pressed`, especially when they are correlated.  Then I have to remember what change of properties are related to which signals, and which signals result in which property changes, etc.

My preference would be to rename signals (even if it's just a few) to start with, and to start to migrate the signal<->property relation in the engine's API to be more intuitive and consistent.

**Comment by YuriSizov** [comment]
> It makes no sense to me to have a `down` or `activated` property, but then emit a signal called `pressed`, especially when they are correlated. Then I have to remember what change of properties are related to which signals, and which signals result in which property changes, etc.

I agree with you on that part. All these alternatives are poor, because they don't provide any meaningful distinction. Pressed, pushed, clicked, activated are all the same term with a different flair and mostly add to the confusion.

I'm just pointing out that there is no direct connection to the property, so naming the signal as if there were is probably not a good idea either. I think this is why we're probably going to end on leaving the property as `button_pressed` or at worse renaming it to `pressed_state` or something.

Personally, I'd prefer to slightly rename the signal, but there was a strong opposition to that. So we can't go that route.

**Comment by Jose-Moreno** [comment]
@YuriSizov So I came here from the poll on twitter... instead of `pressed`, call it `depressed` then?
- It is officially a synonym of "pressed", means the same thing
- It's grammatically, semantically & visually similar so it will be easy to accept for existing and new users.
- No name collision with `pressed`
- You won't need a snake case property that could lower consistency with other properties.
- https://english.stackexchange.com/questions/21067/why-is-the-term-depressed-often-used-to-describe-a-button-which-is-pressed
- https://www.merriam-webster.com/dictionary/depress
- Also @TheDuriel had already mentioned this [on a previous comment ](https://github.com/godotengine/godot-proposals/issues/3877#issuecomment-1024864275)but it was glossed over apparently.

**Comment by dalexeev** [comment]
> It makes no sense to me to have a `down` or `activated` property, but then emit a signal called `pressed`, especially when they are correlated.

As aaronfranke wrote above, and as we discussed in one of the previous proposals, there is some difference between the property and the signal: the property only refers to `toggle_mode = true` (button is pressed and continues to be pressed down), and the signal is not related to `toggle_mode` and button state, it's just the fact that the button is clicked, whether it stays pressed after that or not. So, _in this case_, I don't see the problem that the property and the signal are different, they are indeed slightly different things.

Possible property names that I personally consider more or less acceptable:

* `toggled` (plus: similar to `toggle_mode`, minus: same as signal);
* `checked` (ideal for `CheckBox`, but inaccurate otherwise);
* `active`/`activated` (very abstract, but suitable for both `Button` and `CheckBox`);
* `down` (fine for `Button`, but not fine for `CheckBox`).

**Comment by YuriSizov** [comment]
> down (fine for Button, but not fine for CheckBox).

This is in fact why I stopped in the middle of implementing the agreed upon solution and went for a twitter poll. This name doesn't make sense for a checkbox.

**Comment by bodamat** [comment]
I completely agree with @TheDuriel. Pressed is more easily to understand than activate, because what does it mean. 
But also I can’t understand why Button and Checkbox is the same and should have the same events name. We never find the best option for both, because they are doing completely different things.

**Comment by YuriSizov** [comment]
Given the feedback we've received from the comments and the Twitter poll, it seems that the best option is not to introduce any new terms here to avoid unnecessary disconnection between the states of the button and the property. While personally I would prefer we swapped the name of the signal (`pressed`) and the name of the property (`button_pressed`), there wasn't a consensus on this, both internally and in the public discussion. As such, we've decided to keep the current status quo, however accidental its beginning was.

We can revisit this during the beta if there appears to be a serious issue for users, but otherwise this is just another quirk we'd have to live with for the foreseeable future.
