### ISSUE TITLE
Rename `@export` annotation to be less confusing

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot-proposals#3906]
### Describe the project you are working on

Any project that makes use of the `@export` annotation with the intention to expose a variable to the editor inspector.

### Describe the problem or limitation you are having in your project

I think there's a couple of downsides in terms of ambiguity to the export keyword.
It has a strong meaning elsewhere in game development and editors in general, such as exporting the project, exporting an asset, etc.

As a consequence, looking up documentation and past help threads can be cumbersome. I've often found myself on the wrong docs page or having to sift through search results. it can also be confusing when asking questions about it. for instance, which kind of export is being referred to occasionally needs to be clarified in Discord help channels.

Some proof of the poor searchability:
[exported property](https://docs.godotengine.org/en/stable/search.html?q=exported%20property&check_keywords=yes&area=default) - doesn't show up at all
[export](https://docs.godotengine.org/en/stable/search.html?q=export&check_keywords=yes&area=default) - shows up as the 22nd item
[GDScript export](https://docs.godotengine.org/en/stable/search.html?q=exportsGDScript+export&check_keywords=yes&area=default#) - 22nd item again
[exporting](https://docs.godotengine.org/en/stable/search.html?q=exporting&check_keywords=yes&area=default#) - 17th item

you pretty much need to remember the exact title of the article - GDScript exports - do find it quickly.
although to be fair that is also to some extent and issue of the readthedocs search. Google does a better job. 

Furthermore, I think it's not even a particularly good word for describing the feature. Quoting @aaronfranke here:

> In terms of English words, exporting something does not necessarily imply storing it, in fact a good/product exported overseas typically means the opposite of storing it, it's shipped away.

[Other users](https://github.com/godotengine/godot/issues/54161#issuecomment-1027200488) have also expressed confusion about it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The first term that shoots to mind as an alternative is `@expose`.
Although it's a minuscule difference, I feel like it describes what users generally expect from this feature - exposing a variable to the inspector - much better. It's also a short and concise keyword similar to export, but without the ambiguity issue.

There has been some critique to that idea brought up by @pycbouh: [1](https://github.com/godotengine/godot-proposals/issues/828#issuecomment-1022171179), [2](https://github.com/godotengine/godot/issues/54161#issuecomment-1026923288), [3](https://github.com/godotengine/godot/issues/54161#issuecomment-1027014366)
they explain that `@export` does more than just exposing to the inspector, such as serialization and storing on disc, but personally I don't see how `export` does encapsulate that any better than expose. Once again, I think @aaronfranke put it best:

> if we can say "exported variables are stored by default", why can't we say "exposed variables are stored by default"?

On the other hand, if the current `@export` keyword has two distinct use-cases, then perhaps it should be split up into different annotations as [mentioned by pycbouh](https://github.com/godotengine/godot/issues/54161#issuecomment-1027212147).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A simple replacement of `@export` for `@expose`, including the variations such as `@export_range()` becoming `@expose_range()`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

n/a

### Is there a reason why this should be core and not an add-on in the asset library?

n/a

**Comment by pycbouh** [comment]
> they explain that `@export` does more than just exposing to the inspector, such as serialization and storing on disc, but personally I don't see how `export` does encapsulate that any better than expose.

My opinion is not that it encapsulates it significantly better than your proposal per se, just that your proposed term doesn't make it better in principle. IMO, of course. The old keyword still has the benefit of familiarity for many existing Godot users, even if it comes at a price of confusion for newcomers. We do need to improve the docs, though, that is certain.

I'd like this to not become an argument about whether `export` or `expose` is better. We should not trivialize the choice here, we can still look for a better term that does actually reflect the functionality of the keyword. Especially since the proposal comes from the place of not realizing there exists any additional functionality. I think this a great argument in itself to keep looking.

**Comment by golddotasksquestions** [comment]
While I think what @pycbouh says is very valid, we should always look for the term which explains and infers as much of the functionality of a keyword of property or method or class as possible. However in some cases like this one where there are some lesser known expert uses it might make sense to choose a term which focuses on the primary wider know use in order to arrive to a solution rather than keeping the old even worse naming.

**Comment by Mickeon** [comment]
I would outright exclude `serialise`. It sounds like an annotation that would save the property on disk, but not necessarily expose it in the editor.

**Comment by h0lley** [comment]
if I try to put myself in the shoes of someone who just booted up Godot for the first time, then I am fairly certain I'd never expect `serialize` to be the name of the feature that makes properties appear within the inspector, and upon learning about it I would raise at least one brow as far as humanly possible. `expose` on the other hand seems very intuitive to me; it's exactly what I want to happen, and it's an expressive, concise word on the level of `export` on top of that. not to mention, I think many users  don't even understand `serialize` as "making an object storable", but associate it purely with the sequential publication of works such as books or magazines...

The line "exposed variables are stored by default" in the opening paragraph of the corresponding documentation article would then take care of pointing out more advanced use-cases.

sure, we shouldn't be restrictive in the spectrum of choices - someone may have a better idea - but frankly I doubt that there's a single concise word in existence that encompasses all applications of this feature. `@edit`, `@store`, `@inspect` ... it's like either or, never both.

**Comment by Zireael07** [comment]
Voting for "expose" - the change from export to expose is minimal and also it doesn't run the risk of people confusing exported properties for exporting projects when searching the docs.

**Comment by sairam4123** [comment]
I'm voting for "expose" too. It would be a little bit difficult to fix my muscle memory to type in expose instead of export 😄

**Comment by fire-forge** [comment]
When I first started using Godot I remember having trouble finding docs pages relating to export variables, because they were buried in pages about project exporting. I'd support changing `export` to `expose`, since it would make searching the docs easier.

**Comment by dalexeev** [comment]
The word "export" reflects that the values ​​of the variables are taken from the scene/resource file. If we are going to rename this annotation, then I would prefer `@store` or something similar, but definitely not `@expose`. I think `@expose` is no more understandable to beginners than `@export`, and even more confusing.

The "easier to find online" argument doesn't seem like a compelling reason for this renaming. No one will search for "godot expose variables". Beginners may search for something like "godot how to add variables in editor". From this point of view, `@editor` is also a good option, although it distorts what is happening.

Please note that the new option must be clearly better than `@export`, otherwise it is not worth changing to another one that is the same but less familiar.

**Comment by Zireael07** [comment]
`@store` has the problem that deserialize has, it sounds like it'll be stored to some file...

**Comment by pycbouh** [comment]
> `@store` has the problem that deserialize has, it sounds like it'll be stored to some file...

Which is true?..

**Comment by Mickeon** [comment]
> `@store` has the problem that deserialize has, it sounds like it'll be stored to some file...

Which is technically what `@export` also does, as well!

It'd be nice, though, to find a word that fits with every variation of the export annotation: 
- `@export_range`;
- `@export_multiline`; 
- `@export_flags`... 

For this, I would still favour `@expose` as I personally really find it to be the closest verb describing what the annotation actually does:
 ```
@expose_range(10, 50) var jump_height := 0.0
@expose_flags("Fire", "Water", "Earth", "Wind") var elements := 0
@expose(Array, PackedScenes) var stages := [] 
@expose_file var file
@expose_dir var directory
```

For example, the annotation `@store_range` or `@store_file` may sound too misleading to whoever is trying to understand the code. 
The same goes for `@serialize_range`.

**Comment by Xrayez** [comment]
Be aware that all of this is backed up by property usage flags in C++:

![image](https://user-images.githubusercontent.com/17108460/152539575-0e0839d2-3cff-468a-819b-50c9f85f0a48.png)

There's another value `PROPERTY_USAGE_DEFAULT`, which combines both, and `PROPERTY_USAGE_NOEDITOR`, which excludes `PROPERTY_USAGE_STORAGE`.

Due to this, the "storage" and "editor" are treated separately in core, it's possible to expose properties to editor but not to store them, for instance.

Because of this, I see that `export` keyword combines both storage and editor flags. Regardless of whether we end up renaming `export` to `expose`, we still have different concepts to distinguish:
- `export` or `expose`: expose to the editor, store to scene/resource.
- `store`: store to scene/resource, do not expose to the editor
- `editor`: expose to the editor, do not store in the scene/editor

So I think that we cannot just rename `export` to `store`. I honestly think that `store` and `editor` should be introduced as new annotations to GDScript (I don't imply removing `export`).

**Comment by pycbouh** [comment]
> I honestly think that `store` and `editor` should be introduced as new annotations to GDScript (I don't imply removing `export`).

While it is one of the suggested changes in OP, this creates a lot of additional complexity to a feature that should be simple to use. For example, if we both keep the unified annotation and add individual annotations for each `store` and `editor`, this means that every export hint needs to be defined twice (`export/expose` + `editor`), or even thrice (if `store` also validates it).

This leads me to suggest we split actual "exposure" and "storage" declaration from the hinting. It would be more verbose, but at least we can then keep `export/expose` and add `store`, `editor` without making them individually more complex. This would also be quite similar to our shader language hints:

```
@export @hint_range(10, 50) var jump_height := 0.0
@expose @hint_flags("Fire", "Water", "Earth", "Wind") var elements := 0
@store @hint(Array, PackedScenes) var stages := [] 
@editor @hint_file var file
@expose @hint_dir var directory
```

**Comment by Mickeon** [comment]
That makes me think, couldn't `@hint` alone be a good word for it? It's short, concise, doesn't step on another concept's toes and matches the shader language to an extent. The Global Constants already refer to them as `PROPERTY_HINT_*`, and `Engine.editor_hint` is a fairly useful property when writing code interfacing within the editor itself.

**Comment by pycbouh** [comment]
> That makes me think, couldn't `@hint` by itself be a good word for the rename?
> The Global Constants already refer to them as `PROPERTY_HINT_*`

Well, yes, the hint part is the same, but hints by themselves don't imply any behavior. Usage does (e.g. STORAGE or EDITOR, or others). So using just `hint` would conflict with the rest of the system and create wrong assumptions when you start to learn the engine more. If we do this, the reasonable question from the user would be "Why does setting `PROPERTY_HINT_*` not expose my property, when the annotation of the same name does expose it?"

Since these are not internal systems, hidden from user, but instead just the next level of the same feature, we must ensure logical and syntactic parity.

**Comment by SilencedPerson** [comment]
I really do not see point of having the name reflect that it is being stored. It is not the main use case, it's main use it's to expose stuff to the inspector. Anything else is additional functionality and should be easily accessible from the documentation.

1) `export` is confusing, gets buried under actual exporting stuff in the docs.
2) `serialize` is pretty hard to write and does not convey that it exposes stuff to the inspector any better than export
3) `hint` is something i wish would be gone from the shaders too as it makes it feel more like tooltip
4) `store` is something that makes me think of steam or itch.io than storage but it's still better than every other option so far.
5) `expose` in my opinion vastly superior to all the the other choices.

I will throw in few other possible words:
1) reveal
2) disclose
3) exhibit

**Comment by SilencedPerson** [comment]
> The "easier to find online" argument doesn't seem like a compelling reason for this renaming. No one will search for "godot expose variables". Beginners may search for something like "godot how to add variables in editor".

Not how it works these days. Beginner will watch a tutorial on Youtube where the tutor explains to them that the `export` keyword exposes the variable to the inspector. Subsequently, the beginner will try it in the game engine. Then sometime later they will go directly to the documentation after being sent there by community many times before after asking in other places like reddit/discord/youtube comments on different issues when they eventually begin to wonder what else they can do with the keyword (what i encountered the most is how to export multiline string) and type in "export" and hit the wall. Only so very few people without prior experience in other engines would ever think about adding variable to inspector, it's not something obvious.

People are focusing on the documentation part because this is how it happens. I have experienced it, I have seen it other people go through and I made other people experience it by sending them to documentation.

If they had easier access to the documentation, they would immediately learn it immediately.
![image](https://user-images.githubusercontent.com/82024211/152579332-0c1d9397-4ed5-4ac3-beea-0f16a24a3a01.png)

**Comment by dalexeev** [comment]
Clarification for those who did not know or did not pay attention to this fact: you can create a script that extends `Node`/`Resource`, and different instances of your class can have different values of export variables.

![](https://user-images.githubusercontent.com/47700418/152579300-f2be9d16-00c6-4909-b150-b2f0a10999e8.png)

You don't just make it possible to edit the value of a variable in the editor for the script as a whole, you make it possible to set different values for different instances of the class. This is an essential detail, which is highly desirable to be reflected in the name. That is why `@expose` is worse than `@export`.

**Comment by golddotasksquestions** [comment]
@dalexeev I'm 100% sure everyone here knows this. It's really hard to miss once you start instancing a scene with export variables.

`export` still sucks infinitely more because it's other much more prominent meanings in game dev and editors in general and the fact that the name makes it impossible to even find information about this and more behaviour/functionality the keyword has. Which is also why `store`, `serialize` are equally really bad choices.

`expose` or `reveal` are used nowhere I can think of, and therefore allow all these additional functionality and behaviour you and @pycbouh are talking about to be found much easier.

**Comment by aaronfranke** [comment]
> @dalexeev: No one will search for "godot expose variables".

Yes they would...?

> You don't just make it possible to edit the value of a variable in the editor for the script as a whole, you make it possible to set different values for different instances of the class. This is an essential detail, which is highly desirable to be reflected in the name. 

That's... completely expected regardless of the keyword. It's basic object oriented programming that instances of a class can have different values, nobody would expect that the inspector treats these variables as static or anything.

Again, though, if we can say "exported variables do [thing]", why can't we say "exposed variables do [thing]"?

**Comment by dalexeev** [comment]
> I'm 100% sure everyone here knows this. It's really hard to miss once you start instancing a scene with export variables.

1\. I don't think 100% of all users know this. 2\. I'm worried that with the renaming we will lose some of this meaning and this problem will become bigger.

I don't think "export" is the ideal name, but I'm still not sure if the suggested alternatives are better enough than the existing name to justify this renaming. This is one of the two main reasons why I am skeptical about this proposal.

I expressed my concerns. The decision must be made by the maintainers. At this point, the discussion has become somewhat tense, so I'd better keep quiet.

**Comment by aaronfranke** [comment]
The rename itself is not a big obstacle considering that users will already have to rename to change `export` to `@export`.

**Comment by Xrayez** [comment]
I think it's not enough to just rename the annotation, to be honest.

If there's some resistance to renaming, perhaps #2979 could also be incorporated with `@expose` somehow... A property which is exposed is likely meant to be used outside of the scene/script as well. This is not to say that we should treat private/public access modifiers as something mandatory, but the way I see it, GDScript could potentially warn you about using properties on an instance which does not `@expose` them (given that the warning system is optional and can be disabled, this is not intrusive at all).

This is just an idea of course, but I think that this kind of feature would certainly make it intuitive and more complete.

**Comment by pycbouh** [comment]
> The rename itself is not a big obstacle considering that users will already have to rename to change `export` to `@export`.

Yes, users will have to do changes to their scripts anyway. Then why not rename it proper? Changing a core term comes at a cost of years of accumulated knowledge and help resources. We can pay that price, but wouldn't it be better to make it actually worth it big time? We won't have a chance to do that again until Godot 5.

Seeing that the only vocal opposition so far is me and @dalexeev I think I can say for all of us that we are not against fixing the problem, we just want to fix it all. I really don't understand why there is so much reluctance to investigate other options to help solve a big misconception. No matter how many times it is stressed that serialization and editor exposure are two equal parts of one functionality, some still call the serialization part "additional functionality and behaviour". It's not, it's the core of it. One of two parts. And we need to make sure people stop missing it. So we want a better option. Don't you?

**Comment by h0lley** [comment]
> is an amazing example that we need a better convention than what we have. Not just a flavor change, an actual better convention.

such as? :)


> I really don't understand why there is so much reluctance to investigate other options to help solve a big misconception.

I think that's just due to that people can't really get behind something that's not concrete.

I mean there's no comment in here that goes actively against an alternative to a simple renaming, i.e. a new convention, right?


>  an essential tool for creating custom resources (the preferred way in Godot to deal with data)

I've been using export in conjunction with custom Resource classes extensively throughout my current project. so have I already been using this feature in the way you say is not reflected by "expose"? because exposing the custom resource properties to the inspector (and therefore storing them with the corresponding scene file when changed from the default) is still the main point in my mind.

you make it sound like there is a situation where you want to export your resource and the fact that it then appears in the inspector is just dead weight to your use-case. is that right?

I know there's resources like TileSet which you plug into a TileMap, and that does not have any exported properties of its own - but this is an exception because it got its on editor interface. or there's this awkward resource called ButtonGroup which doesn't hold any data of its own but is used to link buttons that reference it - but that, too, seems like an outlier.

I can't think of a common use-case for exporting a custom resource that doesn't export any properties of its own for editing in the inspector, so I would like to understand.

**Comment by pycbouh** [comment]
> you make it sound like there is a situation where you want to export your resource and the fact that it then appears in the inspector is just dead weight to your use-case. is that right?

Yes, that is pretty normal for an average project. You would likely have your own data editor/tools for your custom resources (made with an editor plugin, for example), or would use some resources programmatically.

**Comment by h0lley** [comment]
> Yes, that is pretty normal for an average project. You would likely have your own data editor/tools for your custom resources (made with an editor plugin, for example), or would use some resources programmatically.

I feel like adding your own UI to the editor for your custom resources is a rather advanced use-case and users on that level are extremely unlikely to get hung up on basic keywords. but please do not take this as me saying there's no merit in looking for better solutions.

> This has nothing to do with exporting custom resources. Resources are used without exporting them in scenes all the time. But a custom resource without any exported fields is not going to save anything. People run into this all the time, not realizing they need to mark properties for export for them to save. (Partly because they think it's only for inspector).

unfortunately I keep struggling here.
in what scenario would someone expect or need a not exported property of resource to be serialized & stored?
anything that isn't prefixed with `export` is given a default value and meant for run-time use only.
how could someone expect that a variable that isn't overwritten via export to have any other initial value than the one it is declared with in the script?

> I suggested some options,

the thing with splitting into separate annotations? yea I recognize that, which is why I also mentioned it in the opening post, but it needs be fleshed out. sorry if I missed anything else.

> but I don't think that I am solely responsible in finding the answer, am I?

sorry, I did not mean to imply that at all.

**Comment by pycbouh** [comment]
> I feel like adding your own UI to the editor for your custom resources is a rather advanced use-case and users on that level are extremely unlikely to get hung up on basic keywords.

Sure, but Godot is not a toy engine either. It tries to be user-friendly, but it doesn't try to be overly simplistic for the sake of it. This is to say that "advanced users will figure it out anyway" is not a good argument in any proposal. I mean sure, I for one don't care that it's called `export` anymore, just some Godot-specific term, it can mean whatever, I've learnt it, I use it, I don't think about it. But it's better to teach new users proper lingo than to hope that more experienced developers would just roll with it.

We should strive to be correct, regardless of skill level.

> unfortunately I keep struggling here.
in what scenario would someone expect or need a not exported property of resource to be serialized & stored?
anything that isn't prefixed with export is given a default value and meant for run-time use only.
how could someone expect that a variable that isn't overwritten via export to have any other initial value than the one it is declared with in the script?

I can't know for sure how people get confused, I just have experience that they do get confused sometimes. They probably expect that it's enough that the member is public for it to be stored with a custom resource. That is a somewhat reasonable guess if you don't know about exporting properties. And it's not like you would look up "godot export" to figure this out. So yeah, it's not the best term, we all agree on that.

This was just a tangential example, however. When I was saying "Resources are used without exporting them in scenes all the time." I meant that a lot of time you create resources not to be edited in the inspector, not to be stored as a part of the scene. And so that fact does become a dead weight. There are other considerations too. For example, you may also want to compute and store some properties, but don't make them easily editable by your artist, for example, so they don't mess it up by accident. Godot has a powerful property system that allows all that, with the `export` keyword being just the tip of an iceberg, that hides a lot of complexity (and yet, people ask for more anyway, like annotations for grouping, or contextual properties — all possible, just hidden).

I think we can make use of this situation and clarify what you can do with the properties, and possibly make it doable more easily. I would find it very annoying if we go through the trouble of modifying this core syntax for a small superficial change without actually making the feature richer and giving users more control that they often ask for.

> the thing with splitting into separate annotations? yea I recognize that, which is why I also mentioned it in the opening post, but it needs be fleshed out. sorry if I missed anything else.

In this particular thread I suggested a slightly different thing compared to the one you used in OP. I proposed we split the hint part and the export/expose part. Then we can indeed use different keywords for storage/editor individually, and keep some keyword for the unified storage + editor usage. Xrayez suggested that part as well, so there is some support to the idea, I think.

I think we should keep close to the terminology of the engine, because it would make learning about the extension of this feature easier. E.g. if you learn about some `@storage` annotation you would be able to map that knowledge when you start learning about `_get_property_list` and various amazing things you can do with that, but can't do with annotations (because there you'd use `PROPERTY_USAGE_STORAGE` instead). So we can easily borrow `@storage` (since `@store` is apparently reserved by Steam in collective mind) and `@editor` from `PROPERTY_USAGE_*` flags.

One problem is that the unified usage flag is called `PROPERTY_USAGE_DEFAULT`, and `@default` is hardly a good term. If we can find a good term here, we can change `PROPERTY_USAGE_DEFAULT` to use that term as well, allowing, once again, to learn about the advanced usages of the feature easier.

-----

Overall, I find that the main conflict here is that the discussion started kind of tunnel-vision-y with people saying how great `expose` is to reflect what they know about the feature, whereas what I want from this change is that we expand people's knowledge about the feature where it's lacking. Because frankly properties are freaking cool and powerful and worth to learn about.

**Comment by Scony** [comment]
What about introducing annotation aliases in project settings? OP would then create an alias:
```
expose=export
```
And use `@export` as well as `@expose` interchangeably.

The `@export` would remain default and everyone would be happy.

**Comment by Zireael07** [comment]
> everyone would be happy.

Not everyone - the people saying there are more complex things at work worth exposing to users explicitly still wouldn't be happy (unless we could do "export = storage+editor"?)

**Comment by aaronfranke** [comment]
@Scony Making the GDScript language change depending on project settings is a bad idea.

**Comment by TurtleKwitty** [comment]
Definitely very much like the idea of actually splitting the annotations so its accessible, but personally don't think we need an annotation for default even if internally it does use default to present the use case of both. 
@editor just to expose to the editor, and @editor_*() for all the magical madness possible, that way it always refers back to the fact that this annotation is for the editor and only the editor
If you want both then put both, it keeps things very simple, no need to add additional hint annotations on top of it all just 
@storage @editor to indicate that you want this property to interact with both the editor and the storage facilities.

**Comment by Mickeon** [comment]
I think that for the beginning user it is fairly expected to see a stored property in the Inspector. And, being such a common thing, splitting the functionalities up would feel redudant.

**Comment by pchasco** [comment]
The fact that exported variables are shown as "properties" in the editor obviates the choice: "@property"

**Comment by h0lley** [comment]
wouldn't that imply to new users that only variables exposed to the inspector are referred to as properties?

also I doubt it's much better of a keyword than "export" to search the docs by.

in my mind there's still nothing really competing with `@expose`.

**Comment by pchasco** [comment]
> wouldn't that imply to new users that only variables exposed to the inspector are referred to as properties?

I don't think so. I would think that the "filter properties" label under the search box would be giving new users that impression.
 
> also I doubt it's much better of a keyword than "export" to search the docs by.

I don't know if the goal of any keyword is to necessarily make it 100% unambiguous to search for. To me, the keyword should clearly communicate its meaning. It should be easy for new users to make the connection that when they see @property before a script variable that it would be visible in the properties window.

In the end, I'm not sure that the disruption to existing GDScript developers would worth the marginal benefit to changing this keyword.

**Comment by Mickeon** [comment]
>in the editor creates an obvious choice: @property

Let's see then:
```
@property_range(10, 50) var jump_height := 0.0
@property_flags("Fire", "Water", "Earth", "Wind") var elements := 0
@property(Array, PackedScenes) var stages := [] 
@property_file var file
@property_dir var directory
```

It doesn't sound too bad, but it's not exactly correct, per se. Any property defined in the script is... a property! Regardless of whether or not it's exposed to the editor.

**Comment by TurtleKwitty** [comment]
I still quite like the idea of splitting the options. editor would very much simplify making the connection that these are exposed to the editor in clear language for a new user, and storage for the same reasons for being exposed to the storage mechanisms

So, @Mickeon exmaples would become 
```
@editor_range(10, 50) var jump_height := 0.0
@editor_flags("Fire", "Water", "Earth", "Wind") var elements := 0
@editor(Array, PackedScenes) var stages := [] 
@editor_file var file
@editor_dir var directory
```

with possibilities for exposing things to either without forcing the other
```
@storage @editor var characterName := "Bob"
@storage @editor_flags("Knight", "Wizard") var characterClass
@storage var exp := 0
@editor_range(1.1, 2.5) expScaling
```
Showing exp in editor wouldn't be very useful, but neither do you need to save the expScaling factor per character its just a constant of the scene form the editor as examples

**Comment by Mickeon** [comment]
Problem with that is, when available in the editor, the storing behaviour is to be expected. If anything, **not** storing in that case may be the exception.

Suppose you're a beginner user that makes use of `@editor`. The property will display in the editor, so the user will modify the value, save, open the Scene again and discover that nothing has been saved. So they wonder what happened and...
Writing `@storage` for each one of them is a fair nuisance for such a common necessity, and it would, for example, be plastered on almost every property of a custom Resource. If only there was a single annotation that avoided repetition, which there is, and it's as of currently `@export`,

**Comment by Mickeon** [comment]
I want to try to find a name in the attempt to have a new name be more exhaustive and self-explanatory. It's true, `@export` doesn't just do one thing. It displays a property in the editor _and_ serialises it. It's very important and fairly powerful.

I looked around, these are closest words I can **personally** find to define it.
`@record`, or `@register`, too. According to most vocabularies:
> "set down in writing or some other permanent form for later reference."
> "[to keep information for the future, by writing it down or storing it on a computer](https://dictionary.cambridge.org/dictionary/english/record)"
> "[to show a measurement, an amount, etc.](https://dictionary.cambridge.org/dictionary/english/register)"

It seems like it is not just about storing, it's also about the need for it to be looked that by an user agent.

Putting it up to the now typical example, and more:
```
@record_range(10, 50, 0.2) var jump_height := 0.0
@record_flags("Fire", "Water", "Earth", "Wind") var elements := 0
@record(Array, PackedScenes) var stages := [] 
@record_file var file
@record_dir var directory
@record_enum("Rebecca", "Mary", "Leah") var character_name: String
@record_multiline var text
@record_exp_easing var transition_speed
@record_color_no_alpha var col: Color
@record_node_path(Button, TouchScreenButton) var some_button
```
Despite *perhaps* being more accurate, I'm terribly afraid this is not a term most people would be willing to adapt to, unless it got overwhelming support. Its meaning really closely intertwines with a theoretical `@store`.

**Comment by Mickeon** [comment]
Splitting my line of thought in half, any `@record` variation may come with the same, long aforementioned misleading issue of `@store` (how is the _enum_ of `@record_enum` being recorded, too?), which, personally, I believe `@export` is also guilty of. This is currently mitigated by proper documentation and proficiency for the language, so I'm not confident on how much of an issue this actually is.

**Comment by filipworksdev** [comment]
I like `@export` is just export is also used when exporting the project.  At first when I started using Godot I thought is something to do with exporting the project.

I actually vote for using `@property` which is actually what the controls in the Inspector are called in the source code.

**Comment by aaronfranke** [comment]
@filipworksdev The problem with `@property` is that properties are already a well-defined thing in programming languages like GDScript and C#, they just aren't exposed to the inspector by default unless we have this attribute.

**Comment by filipworksdev** [comment]
@aaronfranke In that I cast my vote for my second choice `@expose` which makes it different than export but with a better meaning since export means to transport, spread while expose to to reveal or show or make available. Properties are exposed to the inspector rather than exported.

**Comment by YuriSizov** [comment]
@filipworksdev It has been stated already that exposing the property to the inspector is only one of two things it does. The other thing it does is saving the property to a file. So by your own logic we'd be replacing a word that means half of its actual functionality with a word that means the other half. But neither is expressive enough to actually convey the functionality as a whole.

**Comment by h0lley** [comment]
I don't quite follow how export is more descriptive in the serialization aspect of the feature than expose.

but even if we grant that, `expose` still does clash less with other things commonly used in game development and therefore makes for better searchability, so in my mind it has at least one up on `export`.

the counter argument that remains is that `export` is the established term for existing users, and it may not be worth the trouble of amending the docs plus having people have to get used to typing a different keyword. personally I feel like that's moot though, looking at the amount of breaking changes Godot 4 is already sure to come with.

**Comment by YuriSizov** [comment]
No, my counter argument was that if we go through this trouble of changing one of the core terms, we must do it for more benefit than just having a maybe slightly better term.

**Comment by dalexeev** [comment]
As mentioned above, these are two different functions - displaying a property in the editor's inspector and saving the value in a file (and then getting it back, that's what was meant by "export").

The property can also be displayed in the editor but not saved to a file, and not displayed in the editor but saved to a file.

For `Resource` export properties are restored on `duplicate()`, while other script variables are not. Those there might be a case where I have to use `export` even if I don't have the goal of displaying the property in the inspector.

> The fact that the variable is saved to the file is incidental in order to have a way to restore the set value between project/scene reloads.


It sounds like "Wow, now you can change the value in the editor instead of in the script, how convenient!", and where it is stored is just a minor detail. However, the scope of `export` is wider. Where data is stored, where and when it arrives is a very important aspect in programming in general. By exporting variables, you mark that they are external variables, their initial values ​​come from outside, and are not part of the script.

But the arguments in this discussion are beginning to be repeated for the second time. Let's wait for the maintainers to get here, read them and make an informed decision.

**Comment by h0lley** [comment]
`@configurable` may be best in describing the full scope of the feature and its use-case, but to be honest if it takes that much then I'd rather concede and stick to `@export`. I just don't see us finding a term as concise as export that makes everybody happy.

... OP does have a decent amount of likes though... :P

so
> Let's wait for the maintainers to get here, read them and make an informed decision.

**Comment by filipworksdev** [comment]
Thank you @YuriSizov and @dalexeev for further explaining how export works. So based on the responses above I would like to suggest  `@external` as a new alernative since the value comes from an external source inspector/file/etc.

**Comment by golddotasksquestions** [comment]
I have recently seen many people recommend the serialization aspect of export variables using the resource workflow for saving project data.

However doing so is extremely risky endeavor as it opens up the user to loosing all their data when refactoring and renaming those variables. See https://github.com/godotengine/godot/issues/62643 for a detailed description.
There are other similar issues reported with export variable, for example values being lost periodically while the game is running when export variables and tool keyword is used (https://github.com/godotengine/godot/issues/43659#issuecomment-805015987), or values being lost when updating via Github (https://github.com/godotengine/godot/issues/60278).

My point is: using export variables for their serialization aspect is anything but save. Imho, it should be discouraged, not advertised!
Their best use until a stable reliable use can be guaranteed is purely for temporary convenience only, which "expose" is a perfect description.

**Comment by aaronfranke** [comment]
Thinking about it more, I think that `@expose` actually does imply that it's serialized/saved. Think about it... have you ever seen a single thing in the inspector that *isn't* saved? I think it's the user expectation that an exposed property is saved.

**Comment by YuriSizov** [comment]
> have you ever seen a single thing in the inspector that isn't saved? 

Yes, the new layout mode toggles are editor only.

**Comment by YuriSizov** [comment]
> My point is: using export variables for their serialization aspect is anything but save. Imho, it should be discouraged, not advertised!

Please, there is no need for fearmongering. Not only is it perfectly safe to export properties for serialization, it's also the only possible way to do it, now or in future.

**Comment by aaronfranke** [comment]
> Yes, the new layout mode toggles are editor only.

![Screenshot from 2022-07-02 15-20-49](https://user-images.githubusercontent.com/1646875/177015109-d148ecdb-5b6c-495e-b27c-46db60c49d63.png)

**Comment by YuriSizov** [comment]
> > Yes, the new layout mode toggles are editor only.
> 
> ![Screenshot from 2022-07-02 15-20-49](https://user-images.githubusercontent.com/1646875/177015109-d148ecdb-5b6c-495e-b27c-46db60c49d63.png)

Properties are editor only, meta is sometimes saved to help the editor, but is absolutely not necessary.

**Comment by aaronfranke** [comment]
@YuriSizov What's your point? I can easily make a property exposed to the inspector that isn't necessary for the script to function. That doesn't change the fact that it's saved to the file.

**Comment by YuriSizov** [comment]
@aaronfranke Well, you asked for an example of a property that is not saved. That property is not saved. Some meta _may be_ saved, sometimes, no guarantee, but that's editor metadata, not the property itself.

**Comment by aaronfranke** [comment]
@YuriSizov It is saved. I sent you a screenshot of it being saved.

**Comment by YuriSizov** [comment]
Either way, I propose we all take a break for a moment, unless there is some actual new information that we need to discuss. Arguments provided here have been circulating the discussion for months now, and this is getting too repetitive and a bit too heated for such a trivial issue.

I'll try to bring this proposal to a proper discussion with the rest of the maintainers so we can close it one way or another.

**Comment by univeous** [comment]
> Not only is it perfectly safe to export properties for serialization, it's also the only possible way to do it, now or in future.

I haven't read through the whole issue, and I don't object to the current export annotation, but are you saying that we can only make variables serializable via export annotation even in the future instead of having a separate serializable or something annotation? That sounds a bit bad to me.

**Comment by YuriSizov** [comment]
> are you saying that we can only make variables serializable via export annotation even in the future instead of having a separate serializable or something annotation? That sounds a bit bad to me.

There isn't much benefit in a dedicated annotation for serialization, so there hasn't been any plans for that. `@export` is already fine to cover both cases, even if you don't explicitly need the other half of it. If you want to edit the property in the inspector, serialization is still required but to the user it may be incidental. And if you want to serialize a property, then editing it in the editor is incidental.

You can have finer control using `_get_property_list()`, if you want to.

**Comment by univeous** [comment]
> There isn't much benefit in a dedicated annotation for serialization, so there hasn't been any plans for that. `@export` is already fine to cover both cases, even if you don't explicitly need the other half of it. If you want to edit the property in the inspector, serialization is still required but to the user it may be incidental. And if you want to serialize a property, then editing it in the editor is incidental, but also handy.
> 
> You can have finer control using `_get_property_list()`, if you want to.

A lot of properties need to be serialized without needing/having meaning to be displayed in the inspector.

Say I'm making an RPG game and my character_stat inherits from Resource and has properties like str and max_hp. The str property can be exported, but it doesn't make sense to export max_hp because that property is calculated from the str property, but it should be serialized as well.
This is a simple example and could probably be solved by calculating max_hp every time it is used, but in more complex examples it is absolutely essential that it can be serialized without being exported in the inspector.

I know I could use `_get_property_list()`, but that would produce a lot of boilerplate code, and that's the 'a bit bad' part I referred to.

**Comment by YuriSizov** [comment]
@univeous This isn't really related to this proposal, and merits of adding a storage-only annotation can be discussed in a dedicated proposal that provides concrete use cases.

**Comment by h0lley** [comment]
@reydelatorre entirely wrong place to comment on this.
what you are looking for is [this issue](https://github.com/godotengine/godot/issues/54828).
