### ISSUE TITLE
Add a method to create a new inherited scene from code

### ISSUE THREAD

**Issue by VanDeiMin** [godotengine/godot-proposals#3907]
### Describe the project you are working on

2D isometric car race game.  currently in Godot 3.4.2

### Describe the problem or limitation you are having in your project

In my game I will  have to add about 1000-2000 vehicles of 200-400 types (for now i have 256 in 42 types). Each vehicle must be unique beacuse only one instance can be in game scene at once. I have base CarTemplate scene. Then I create default CarType which inherits from CarTemplate. Then I make specific Car scenes (usualy 6- 10) which inherit from CarType and have its unique features. Making one CarType by hand takes me about half an hour. 

I designed EditorPlugin which helps with tedious process of making new Car scenes. It takes assets from named folders and creates nessesery Resources (e.g. SpriteFrames, simple scripts inherited from CarTemplate.gd script I have, etc.) and then ataches them to corresponding Car scenes. 

Unfortunately whole proccess can not be fully automatic. Car scenes must be made by hand if I want to use benefits of inheritance... It takes time and makes a risk of typing mistakes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With ability to create a new inherited scene directly from GDScript, it would be possible to fully automate process of creating inherited scenes inside editor and thus could save a lot of developer's time. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It could be a **new Method** added to **PackedScene**.

The code in GDScript should allow something like:
```gdscript 
var inheriting_scene : PackedScene = load("res://InheritingScene.tscn")
var inherited_scene : PackedScene = inheriting_scene.create_new_inherited_scene()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no code for this. Only tedious clicking and typing in the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

The proposal looks like core to me. Also I suppose change like that is imposible to do whitout changing base engine code and recompiling it.

**Comment by petterthowsen** [comment]
I also want this for a open world terrain addon. Need it for generating a bunch of scenes for each terrain tile (or "chunk").

For the time being, I assume it's possible to write the text for the .tscn file? I actually did something like that for a previous iteration of this project.

**Comment by nonunknown** [comment]
I could not understand the proposal, whats the difference from a instanced scene to a inherited one?

**Comment by nonunknown** [comment]
but in the end its the same thing, look:

```gdscript

var scene = load(existing_scene_path)
add_child(scene)
# do some code here to modify the scene
#save the scene somewhere in res://
```

Done you have a modified scene from the chosen one.

**Comment by Zireael07** [comment]
Aah, that is what you mean. Yes, that's a solution for the OP

**Comment by nonunknown** [comment]
its because, when you create a `new inherited scene` in the editor, in the backend you're just duplicating the scene, the fact that you cant modify the original nodes, its the editor (front-end) decision, but if you load this inherited scene via code and modify it, its ok. I'm not sure about this I've said, but @Calinou can confirm I think.

**Comment by lentsius-bark** [comment]
If the greyed out nodes behave the same in a scene duplicated that way the same way as they do in an inherited scene, this would indeed be a solution if not, and the inheritance is lost then it's not a functional workaround.

**Comment by VanDeiMin** [comment]
> but in the end its the same thing, look:
> 
> ```gdscript
> var scene = load(existing_scene_path)
> add_child(scene)
> # do some code here to modify the scene
> #save the scene somewhere in res://
> ```
> 
> Done you have a modified scene from the chosen one.

I think Your sollution brakes the inheritance . I made a simple scene :
https://drive.google.com/file/d/1G815McN3nKGK4QH5RwtQAkPaWRGjJFGB/view?usp=sharing
[InheritanceIssue.zip](https://github.com/godotengine/godot-proposals/files/8063177/InheritanceIssue.zip)

which tries to make new inherited scene from code. Without success.
Plugin makes new scene but with no inheritance.

Copy it and use "SaveScene" button in 2D editor, and analize results.

Here is the main part of code I used:

    	var _load_path: String = "res://Inheritance.tscn"
	var _loaded_scene: PackedScene = load(_load_path)
	var _root_node: Node2D = _loaded_scene.instance(1)
	var _new_node: Node2D = Node2D.new()
	_new_node.set_name("NewNode2D")
	_root_node.add_child(_new_node)
	_new_node.set_owner(_root_node)
	var _pck: int = _loaded_scene.pack(_root_node)
	var _save_path: String = "res://NewInherited.tscn"
	var _sv: int = ResourceSaver.save(_save_path, _loaded_scene)
	_root_node.free()


I still hope the problem is made only by my lack of knowledge.
I found that GEN_EDIT_STATE must be ("1") GEN_EDIT_STATE_INSTANCE if I want to make changes in instanced scene but I don't know why.

**Comment by nathanfranke** [comment]
```gdscript
func create_inherited_scene(inherits: PackedScene, root_name := "Scene") -> PackedScene:
	var scene := PackedScene.new()
	scene._bundled = {"base_scene": 0, "conn_count": 0, "conns": [], "editable_instances": [], "names": [root_name], "node_count": 1, "node_paths": [], "nodes": [-1, -1, 2147483647, 0, -1, 0, 0], "variants": [inherits], "version": 2}
	return scene
```

**Comment by Zireael07** [comment]
Nice trick, should be documented somewhere. Also what is that magic number in nodes?

**Comment by nathanfranke** [comment]
No idea- to get this dictionary I created an inherited scene in the editor and then `print(load("x.tscn")._bundled)`.

**Comment by Reneator** [comment]
I personally would be in need/want for this.

I have certain ingame-objects saved as scenes (Items, Equipment, Armor etc.) and i have hundreds of them. These are ordered in tiers. So when i now want to create a new tier, i have to manually duplicate those scenes of the previous tier and rename them. 

I tried to write a script that loads items/equipment of a certain tier, changes some values and saves them as a higher tier item, with a new file-name (sword_t1 -> sword_t2). It works at it's core, but i loose my connection to the core-scene its inheriting from, which defines certain defualt values i want to be able to easily change for all inheriting scenes, by just changing it in this parent scene. 

I found an idea of how to make it work, by using a different kind of instance, but this only works for tool scripts:

https://godotengine.org/qa/120127/how-to-edit-inherited-packed-scenes

The problem with this is that it requires to run scripts in tool, but that still doesnt work and creates a scene without the inheritance connection:

What i want:
(the .tscn file)
![image](https://user-images.githubusercontent.com/24807557/197844732-fa8ebe9d-e6b8-4123-91cc-bdd3811976bb.png)

what it does:

![image](https://user-images.githubusercontent.com/24807557/197844836-4dbe2da2-37d0-48e6-a288-d38f98ab1f43.png)

In the image all those ext_resource are created because it doesnt inherit anymore and  the `instance=ExtResource( %id )` is missing which signifies the inheritance


The initial proposal feels like it could help me make it possible for me to duplicate a scene and it's still an inherited scene. Even if i would have to do a workaround like:
- get the scene the node is inheriting from
- create a new inheriting scene
- copy all values from the original scene i want to duplicate into the new inheriting scene
- save to file-system

**Comment by VanDeiMin** [comment]
Hi! I've tried Your way and it works for me. I added  line for using root node name of inherited scene. It's useful if You don't want to change root node name in inheriting scene.
Anyway Big Thanks for the Solution!!!

> ```gdscript
>var _inherits: PackedScene = load("res://path");
>var _root_name: String = _inherits._bundled["names"][0];
>
> func create_inherited_scene(inherits: PackedScene, root_name : String = "Scene") -> PackedScene:
> 	var scene := PackedScene.new();
> 	scene._bundled = {"base_scene": 0, "conn_count": 0, "conns": [], "editable_instances": [], 
>					"names": [_root_name], "node_count": 1, "node_paths": [], 
>					"nodes": [-1, -1, 2147483647, 0, -1, 0, 0], 
>					"variants": [inherits], "version": 2};
> 	return scene;
> ```

**Comment by mrkdji** [comment]
I managed to find a workaround for this by creating an inherited scene from the editor,  then duplicating it from code and saving the duplicate as a new .tscn file. The duplicate scene maintains inheritance.

```gdscript
tool
extends EditorScript

const INHERITED_SCENE = preload("res://test/Inherited.tscn")

func _run():

	var new_scene = INHERITED_SCENE.duplicate();
	var instance = new_scene.instance(PackedScene.GEN_EDIT_STATE_INSTANCE);
	instance.name = "AnotherInherited";
	new_scene.pack(instance);
	
	ResourceSaver.save("test/AnotherInherited.tscn", new_scene);
```

Anyway I second the proposal for ease of use and moreover this workaround doesn't solve [this use case](https://www.reddit.com/r/godot/comments/qflbyl/create_a_new_inherited_scene_in_gdscript/)

**Comment by TheDoorworlds** [comment]
> I managed to find a workaround for this by creating an inherited scene from the editor, then duplicating it from code and saving the duplicate as a new .tscn file. The duplicate scene maintains inheritance.
> 
> ```gdscript
> tool
> extends EditorScript
> 
> const INHERITED_SCENE = preload("res://test/Inherited.tscn")
> 
> func _run():
> 
> 	var new_scene = INHERITED_SCENE.duplicate();
> 	var instance = new_scene.instance(PackedScene.GEN_EDIT_STATE_INSTANCE);
> 	instance.name = "AnotherInherited";
> 	new_scene.pack(instance);
> 	
> 	ResourceSaver.save("test/AnotherInherited.tscn", new_scene);
> ```
> 
> Anyway I second the proposal for ease of use and moreover this workaround doesn't solve [this use case](https://www.reddit.com/r/godot/comments/qflbyl/create_a_new_inherited_scene_in_gdscript/)

This is the same approach I take for an addon I've made, but it really is inelegant and comes with its own set of problems in my experience.  I've run into problems where making changes to the new .tscn file after it's been successfully created breaks the inheritance.  As it stands, I'm going to have to verify and/or edit the .tscn file's content directly to make this work, which I'd really rather not do because that's so error prone.

Here's hoping the pull request gets reviewed and approved soon!

**Comment by ryevdokimov** [comment]
I submitted a PR that should work: https://github.com/godotengine/godot/pull/90057

Would appreciate a review.

**Comment by Sythelux** [comment]
I had a similar Problem when writing a custom `EditorScenePostImportPlugin` so I made a workaround in C#.
Until the referenced pull request is merged  I'll put the code here for anyone, who might need more input solving it themselves. (works with Godot 4.3)

```csharp
    public override void _PostProcess(Node scene)
    {
        CreateNewInheritedScene(scene);
    }

    // scenePath is the path of the scene file (fbx, gltf, tscn) that is supposedly inherited into the scene test.tscn
    void CreateNewInheritedScene(Node sceneNode)
    {
        PackedScene scene = new PackedScene();
        scene._Bundled = new Dictionary
        {
            { "base_scene", 0 },
            { "conn_count", 0 },
            { "conns", new Array() },
            { "editable_instances", new Array() },
            { "names", new Array(new[] { sceneNode.Name }) },
            { "node_count", 1 }, { "node_paths", new Array() },
            { "nodes", new Array(new[] { -1, -1, 2147483647, 0, -1, 0, 0 }.Select(i => Variant.From(i))) },
            { "variants", new Array(new[] { ResourceLoader.Load<PackedScene>(scenePath) }) },
            { "version", 3 }
        };
        ResourceSaver.Save(scene, "res://test.tscn");
    }

```

**Comment by McZazz** [comment]
Last January/Feb I was able to get the equivalent of "right click > new inherited scene" on glb files by using the following:

```
EditorInterface.open_scene_from_path(path_to_glb)
EditorInterface.save_all_scenes()
```

I could run through an arbitrary folder structure with glbs, images, and json with the material info and was able to hack together the little text files Godot likes to use and it all worked.

But now, in 4.3, once it hits the first glb it finds, the editor stops executing the script (an anti pattern) and shows the popup you would get if you were doing this manually.

But when I was looking into this, I did stumble across the property that Sythelux mentioned, and skipped it because it looks too complicated. Probably will have to revisit it now.

**Comment by wgeraghty** [comment]
Some additional code to help see what's going on when using the _bundle override hack:

```gdscript
const NO_PARENT_SAVED = 0x7FFFFFFF
const NAME_INDEX_BITS = 18
const NAME_MASK = (1 << 18) - 1 

const FLAG_ID_IS_PATH = (1 << 30)
const TYPE_INSTANTIATED = 0x7FFFFFFF # 2147483647
const FLAG_INSTANCE_IS_PLACEHOLDER = (1 << 30)
const FLAG_PATH_PROPERTY_IS_NODE = (1 << 30)
const FLAG_PROP_NAME_MASK = FLAG_PATH_PROPERTY_IS_NODE - 1
const FLAG_MASK = (1 << 24) - 1

static func PARENT(id: int) -> int:
  return id

static func OWNER(id: int) -> int:
  return id

static func NAME_INDEX(index: int) -> int:
  return index << NAME_INDEX_BITS

static func INSTANCE(id: int) -> int:
  return id

static func PROPERTIES(count: int) -> int:
  return count

static func GROUPS(count: int) -> int:
  return count

static func IS_PATH(id: int) -> int:
  return id | FLAG_ID_IS_PATH

static func PROP_NAME(id: int) -> int:
  return id

static func PROP_VALUE(id: int) -> int:
  return id

static func to_inherited_scene(sceneName: String, scene: PackedScene) -> PackedScene:
  var _bundled = {
    "names": [sceneName],
    "variants": [scene],
    "node_count": 1,
    "nodes": [
      PARENT(-1),
      OWNER(-1),
      TYPE_INSTANTIATED,
      NAME_INDEX(0),
      INSTANCE(-1),
      PROPERTIES(0),
      GROUPS(0)
    ],
    "conn_count": 0,
    "conns": [],
    "node_paths": [],
    "editable_instances": [],
    "base_scene": 0,
    "version": 3,
  }
  scene = PackedScene.new()
  scene._bundled = _bundled
  return scene

static func to_inherited_scene_with_material(sceneName: String, scene: PackedScene, material: Material) -> PackedScene:
  var _bundled = {
    "names": [sceneName, sceneName, "material_override"],
    "variants": [scene, material],
    "node_count": 2, # size of "nodes" array
    "nodes": [
      #------------------------
      PARENT(-1),
      OWNER(-1),
      TYPE_INSTANTIATED,
      NAME_INDEX(0),
      INSTANCE(-1),
      PROPERTIES(0),
      GROUPS(0),
      #------------------------
      IS_PATH(PARENT(0)), # node_paths[0]
      OWNER(-1),
      TYPE_INSTANTIATED,
      NAME_INDEX(1),
      INSTANCE(-1),
      PROPERTIES(1),
      PROP_NAME(2), PROP_VALUE(1), # material_override = nodes[1]
      GROUPS(0)
      #------------------------
    ],
    "conn_count": 0,
    "conns": [],
    "node_paths": [^"."], # IS_PATH(PARENT(0))
    "editable_instances": [],
    "base_scene": 0,
    "version": 3,
  }
  scene = PackedScene.new()
  scene._bundled = _bundled
  return scene
```

This is based on `scene/resources/packed_scene.cpp` and `scene/resources/packed_scene.h`.

**Comment by dmlary** [comment]
I'm curious why this proposal was closed with [godot#90057](https://github.com/godotengine/godot/pull/90057).  That only adds an argument to `EditorInterface.open_scene_from_path()` to open a new inherited scene in the editor.  It doesn't provide any way to create and save a new inherited scene entirely in GDScript.  From reading the comments in the proposal, it seems like one of the key workflows here is to create inherited scenes without any user interaction from things like a `EditorScenePostImportPlugin`.

Should this proposal be reopened, or new one be opened that explicitly focuses on programmatic creation/save with no user interaction in the editor?

**Comment by ryevdokimov** [comment]
Isn't that possible by following up with `EditorInterface.save_scene_as()` and then `EditorInterface.close_scene()`?

**Comment by dmlary** [comment]
@ryevdokimov When you're doing an import of a bunch of assets, that's a lot of UI flipping for no purpose.

The workaround from @nathanfranke works, but the problem is how fragile it is due hard-coded values being set in the PackedScene._bundle.
