### ISSUE TITLE
Add an option to reset the transform of the root node when saving a branch as an instanced scene

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#3962]
### Describe the project you are working on

unrelated

### Describe the problem or limitation you are having in your project

When saving a branch as a scene, the transform of the root node in the new scene is the transform the node had originally:

https://user-images.githubusercontent.com/71937306/153724878-d2d198fe-025f-41df-a93b-ebe13b86e71a.mp4

However, when saving a branch as a scene the idea is in my experience almost always to "promote" a subtree and make it a component on its own, which has no reason not to be centered in its own scene.
What I have to do in the current state of things to achieve this is:
 1. save branch as scene
 2. reset the transform of the root in the newly created scene
 3. re-setup the instance that is not in the right position anymore

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Therefore imo it makes sense to add a checkbox somewhere in the "save branch as scene" dialog, titled "reset root transform" and checked by default that if checked does the following:
 1. reset the transform of the root node in the newly created scene so that the scene is at the origin of its "scene space",
 2. set the transform of the instance that replaces the branch to match the original state.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure wether this feature is used often at all. I do use it often. It can't be a script.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if it can.

**Comment by Mickeon** [comment]
I'm struggling to find a reason on why this **shouldn't** be the case by default. The current way leads to the `position` property to behave unintuitively  (on the Scene the operation starts from, `position` of the branch is **(0,0)** but the "Restore to Default" symbol shows up because in the newly created Scene, `position` is, say, **(40, 50)**  ).

**Comment by Calinou** [comment]
> I'm struggling to find a reason on why this **shouldn't** be the case by default. The current way leads to the `position` property to behave unintuitively (on the Scene the operation starts from, `position` of the branch is **(0,0)** but the "Restore to Default" symbol shows up because in the newly created Scene, `position` is, say, **(40, 50)** ).

I think having this "reset transform" behavior as the default is a good idea, but I don't know if some people will want the old behavior back.

**Comment by Mickeon** [comment]
I believe the current behaviour only makes sense if the parent Node isn't Node2D, since it would not be able to inherit the position from anything.

**Comment by HolonProduction** [comment]
I tried to implement this (without knowing about the proposal). During the process the following questions were brought up:
- Are there known workflows which rely on the new scene having a translated root?
- What about other transformations like rotation or scale?

Given that this proposal is here since more then a year and no usecase against it was brought up, I think that we can answer the first point with no.

However I would like to address the question about other transformations. Taking the idea of checkboxes from this proposal I could imagine having three checkboxes with only the translation checked by default. This would give users controll over the behaviour.

However I don't know where I would place such checkboxes and maybe the additional checkboxes would be distracting and confusing for most users. In that case I think it would be reasonable to just reset position right now.

**Comment by Bitlytic** [comment]
I personally don't believe having a checkbox in the editor settings would be a bad idea just for the freedom of having the option to disable the position change, but using this proposed solution by default sounds like the a good way to go.

As for things like rotation and scale, I think if someone has scaled and rotated something, that should be applied to the saved scene from the branch. Something like rotation and scale seems very deliberate and intentional, whereas I know a lot of people will position something in the level just to test that it works before saving off as a separate scene.

**Comment by HolonProduction** [comment]
I could imagine that scale and rotation would be interesting for saving decoration objects that might have been placed to fit with the rest of a level. But going ahead with translation should be fine. If issues are raised about other transforms, adding them later should be no problem

**Comment by wirelessfuture** [comment]
Did this go anywhere?

**Comment by Mickeon** [comment]
https://github.com/godotengine/godot/pull/80561 implements this, but it's not been merged yet. It also happens always rather than being an option.

**Comment by UrgUrgUrg** [comment]
Would love to see this get added!

**Comment by Zireael07** [comment]
You can see the related PR was merged and this is closed?
