### ISSUE TITLE
Console Support

### ISSUE THREAD

**Issue by DreamBoi8** [godotengine/godot-proposals#4109]
### Describe the project you are working on

Top down driving game

### Describe the problem or limitation you are having in your project

Can't export to console.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding console support would help in increasing the amount of people who could play your game

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add console export to export menu

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, its kinda self explanatory.

**Comment by ynot01** [comment]
https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html

**Comment by pycbouh** [comment]
Godot cannot offer first party console support, as is outlined in the article above. You can partner with third parties, and regardless you would need to get into an agreement with a console vendor.

I have to close this proposal, because it doesn’t qualify the proposal requirement. Please do read the documentation and get familiar with the engine before opening a proposal, and do read the requirements outlined in the readme file of this repository.

If you want to discuss a general idea of console support in Godot, feel free to open a discussion.
