### ISSUE TITLE
Fold down comments (like functions)

### ISSUE THREAD

**Issue by MrMrBlackDragon** [godotengine/godot-proposals#416]
**Describe the project you are working on:**
Nearly any project

**Describe the problem or limitation you are having in your project:**
When have a comment going over multiple lines it interrupts the code reading flow

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If it's possible to fold down like a comment like a function, it would be easier to scroll trough the code.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
So there is a comment to explain your function like this:
![grafik](https://user-images.githubusercontent.com/46326301/73397022-e594d580-42e2-11ea-80e8-76d772f4494b.png)
and fold it down like this:
![grafik](https://user-images.githubusercontent.com/46326301/73397394-bc287980-42e3-11ea-8089-a0d3b93a80fa.png)

**Describe implementation detail for your proposal (in code), if possible:**
n.a

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Something like this would be possible:
![grafik](https://user-images.githubusercontent.com/46326301/73397528-06115f80-42e4-11ea-92ba-1e6e71d00648.png)
resulting in:
![grafik](https://user-images.githubusercontent.com/46326301/73397557-16c1d580-42e4-11ea-97bd-bcfa21546df3.png)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Is see no way how this could be implemented as an asset. Furthermore it's usefull for every project

**Comment by Calinou** [comment]
See also #27488.

**Comment by Feniks-Gaming** [comment]
We could close my issue and stay with this one instead as is better presented. @Calinou  feel free to close the one I made. I agree folding comments would be great help for documenting inside the function. 

It can be somewhat faked by having multiplier strings instead of comments but it's not ideal. 

![1](https://user-images.githubusercontent.com/30668026/73500274-1eec4480-43ba-11ea-8684-bcfba7dc52ed.PNG)

![2](https://user-images.githubusercontent.com/30668026/73500278-21e73500-43ba-11ea-8d50-365c84e70429.PNG)
