### ISSUE TITLE
Rename project.godot to the name of the project

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot-proposals#4198]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Currently every project has ```project.godot```. The folder name is the only clue as to what's inside. Searching for project files on your computer is useless since they are all named ```project.godot```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest renaming them to the name you specify for the project + the extension ```.gdproj``` or ```.godotproj``` so you may have ```Tower Defense.gdproj```

This way you have a descriptive name, project files become searchable and you know what will they open.

The project file is pretty much unique, so finding your project even becomes easier when searching for files

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is a good moment to change this while Godot 4 is improving everything and is still in Alpha 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

We are used to naming files based on what they do, which helps identify them, rather than all project files having the same filename even though they are different projects and it's hard to differentiate them and search for them outside the engine

**Comment by Zireael07** [comment]
Can the people downvoting explain their reasoning? I fail to see any reason NOT to do this, except inertia...

**Comment by BeayemX** [comment]
Downvoter here, my reasoning:

It seems like an odd solution to a VERY specific problem. Why do you search for Godot project files this much? It seems like this should be solved on OP's side somehow else. Maybe a better folder structure?

This would mean that a file that is doing the **same thing** in every project (storing project specific data) would always have a **different name**. This is really bad if you want to have this file used in any sort of pipeline (not sure if anyone is doing this).
Also I can't recall any framework/engine that does this. e.g often you find `manifest.json` files in other software, where they never use the project name as a file name.

What happens if you rename your project? Does it rename your file? Probably. Is the project title still contained in the project file? If so, you (=Godot Devs) now have to keep track of two places for one thing. (Personal opinion: I rename projects FAR more often then I am looking for project.godot files, which I literally never have done)

And if for any reason I would like to manually edit the project file, I currently know which file to look for, because it is **always** the same name. If it would be the project's name, I would always have to look for a different file. If you have a project beginning with `a` it is maybe listed as the first file. If it starts with `z` you have to scroll to the bottom... and so on... Which in my opinion contradicts the initial intention of making it easier find.

**Comment by Zireael07** [comment]
Oh. That's actually a very good point, thanks.

**Comment by Mickeon** [comment]
Also the problem OP is describing doesn't look like that much of a problem, at least in Windows 10.
![image](https://user-images.githubusercontent.com/66727710/157661557-2740dbb9-129a-4076-9c2b-cdc9769ed0d9.png)

>  The folder name is the only clue as to what's inside

If that's not desirable, better organization of all Godot projects should be considered, so that there would not even be a need to look for them all over the hard drive.

> We are used to naming files based on what they do

Indeed, it's why the file is called `project.godot`. For instance, additional **git** files (`.gitignore`, `.gitattributes`...) aren't renamed on a project-by-project basis because they may differ between one another. They're just named after what information they store, and what actually makes them unique is their file path.

**Comment by lexum0** [comment]
> Also I can't recall any framework/engine that does this

Unreal does this 
<img width="701" alt="Unreal Engine 4" src="https://user-images.githubusercontent.com/2546522/157669553-d7335957-8c06-4db2-bb62-2189d8a6ba00.png">
Xcode does this
<img width="130" alt="Xcode" src="https://user-images.githubusercontent.com/2546522/157670255-9ff37b84-0c23-4bff-97c6-ca5c6a2ff8d5.png">
Even exporting the project from Godot does this
<img width="449" alt="Godot Exported Project" src="https://user-images.githubusercontent.com/2546522/157670262-ea34bd98-fcab-4c73-b709-e06d419cfe63.png">
Godot even adds the project name to files that are always kept the same in Xcode projects (```Info.plist``` is always the same, whereas the project file gets the name of the project like ```project_name.xcodeproj```)
<img width="363" alt="Godot Exported Project 2" src="https://user-images.githubusercontent.com/2546522/157670490-4908c6a8-213b-4c02-9831-367acce07d4c.png">



Here's another example where it's useful to have the name of the project
<img width="257" alt="Godot Projects" src="https://user-images.githubusercontent.com/2546522/157670807-5502af79-e227-4a6b-9bcd-73047748fb7a.png">




> Indeed, it's why the file is called `project.godot`. For instance, additional **git** files (`.gitignore`, `.gitattributes`...) aren't renamed on a project-by-project basis just because they may differ between one another. They're consistently named after what information they store, and what actually makes them unique is their file path.

The difference is we are talking about the project file, not the rest of the files under that file that have a specific function. This is the file you double click, your document so to speak, to keep working on your project. I can search for my project and launch it right away by having the project name in the file, rather than searching for a folder which will very likely return several results for the same name whereas searching for the project file with your name will return less


Here's another example where searching for them doesn't work
<img width="266" alt="Spotlight" src="https://user-images.githubusercontent.com/2546522/157672279-8e8bede8-8a32-4e8e-8a69-a7b24ab3689d.png">



> What happens if you rename your project? Does it rename your file? Probably.

You simply rename the file. Xcode does this. Xcode has an internal name like Godot which is the one that will be used and the filename. Most of the time they are the same, but they can be different

> Personal opinion: I rename projects FAR more often then I am looking for project.godot files, which I literally never have done

You can still rename your files all the time, and have the project file with a more familiar name than ```project.godot```. For the engine it should be no problem, it just opens the file that matches ```*.godotproj``` instead of ```project.godot```. The engine uses the file extension which belongs to it, we use the file name for us and everyone is happy

> And if for any reason I would like to manually edit the project file, I currently know which file to look for, because it is **always** the same name. If it would be the project's name, I would always have to look for a different file. If you have a project beginning with `a` it is maybe listed as the first file. If it starts with `z` you have to scroll to the bottom... and so on... Which in my opinion contradicts the initial intention of making it easier find.

It's still easy to find, it's the only file using the Godot "Project" icon, plus it has the name you assigned to it. Besides, I'd argue that's a less common scenario to have to edit the project file manually, and have to keep the name the same because of that

**Comment by lexum0** [comment]
Here's another example where having the same name doesn't help

<img width="364" alt="Recent Files" src="https://user-images.githubusercontent.com/2546522/157681381-f245a1b0-4b1f-4bcc-8f25-22f4ae173627.png">

**Comment by lexum0** [comment]
Another example

<img width="1022" alt="Search" src="https://user-images.githubusercontent.com/2546522/157691853-053b4c2b-554e-4267-afb4-7a5cdbec92b4.png">

**Comment by lexum0** [comment]
> Also the problem OP is describing doesn't look like that much of a problem, in my opinion, and at least in Windows 10. ![image](https://user-images.githubusercontent.com/66727710/157661557-2740dbb9-129a-4076-9c2b-cdc9769ed0d9.png)
> 
> > The folder name is the only clue as to what's inside
> 
> If that's not desirable, better organization of all Godot projects should be considered, so that there would not even be a need to look for them all over the hard drive.

In that screenshot search only works if the file you are looking for turns out to be in the top 10, or randomly shown in your results. If it's not, then search is useless in that case for Windows 10 too. The more projects you have, the more likely that will happen

**Comment by gustavi** [comment]
> Another example
> 
> <img alt="Search" width="1022" src="https://user-images.githubusercontent.com/2546522/157691853-053b4c2b-554e-4267-afb4-7a5cdbec92b4.png">

That's not an argument. I have dozens of `README.md` in my home directory and I'm not asking GitHub/GitLab to rename this file. Same for `requirements.txt`, `packages.json`, `.gitignore`, `Makefile` and so on. You may be search the wrong way.

**Comment by EricEzaM** [comment]
> Unreal does this

And yet it is notoriously difficult to rename unreal engine projects. There is a reason why 'Ark Survival Evolved' is still 'Shooter Game.exe'

**Comment by Mickeon** [comment]
> And yet it is notoriously difficult to rename unreal engine projects. There is a reason why 'Ark Survival Evolved' is still 'Shooter Game.exe'

I'm curious to see the general user complaints of this, maybe available on their forums.


Also, 
> I suggest renaming them to the name you specify for the project + the extension `.gdproj` or `.godotproj` so you may have `Tower Defense.gdproj`

Unlike as of currently, the new format would make it technically possible to store multiple projects on the same folder. Is that desirable or problematic?

**Comment by BeayemX** [comment]
> Unlike as of currently, the new format would make it technically possible to store multiple projects on the same folder. Is that desirable or problematic?

What would be the usecase for that?
You would still have the same scripts, scenes, resources...

To me this sounds like a good way to corrupt your project(s).

**Comment by Mickeon** [comment]
Indeed, but because the file would be named `project name.gdproject` instead of being the never changing project.godot, it technically makes it possible to have more than one `gdproject` file in the same folder. How should the engine behave in those use cases?

**Comment by stevecotton** [comment]
As there's already a project-browser built into Godot, what advantage is there to using other GUIs to search for the project files?

> I can search for my project and launch it right away by having the project name in the file, rather than searching for a folder which will very likely return several results for the same name whereas searching for the project file with your name will return less

The "likely return several results" part of that could be solved by adding an extension to your folder's name.

**Comment by stevecotton** [comment]
That filename is currently hardcoded into the engine's command-line parsing - it works out which argument is the filename by `} else if (I->get().ends_with("project.godot")) {`. I was looking to see if a directory-name could be detected and automatically treated as if the `--path` option had been given.

(posted as a separate comment because the previous one already has a reaction emoji).

**Comment by me2beats** [comment]
If I rename the_project in ProjectSetting, would the_project.godot be renamed too?

**Comment by Mickeon** [comment]
Surely yes.

**Comment by naturally-intelligent** [comment]
It would be nice to be able to have other names, as I can't store more than one project in a folder. In my case I would be using slightly altered projects for special builds, like "demo.project" etc but Godot refuses to open them so I have to do a renaming dance or symlink tricks when opening.

**Comment by Mickeon** [comment]
Have you considered [making use of `override.cfg`](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#:~:text=Any%20project%20setting%20can%20be%20overridden%20by%20creating%20a%20file%20named%20override.cfg%20in%20the%20project%27s%20root%20directory.%20This%20can%20also%20be%20used%20in%20exported%20projects%20by%20placing%20this%20file%20in%20the%20same%20directory%20as%20the%20project%20binary)?
