### ISSUE TITLE
Allow SceneTreeTimer to run in physics frame

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot-proposals#4319]
### Describe the project you are working on

A bullet hell game with a system to record player operations

### Describe the problem or limitation you are having in your project

In my project, I made a system to record player operations, but if I use the create_timer() directly, it will have inconsistent behaviors when playing/accelerating/decelerating the playback, and I have to implement a global timer that based on physics frames.
https://github.com/godotengine/godot/pull/63026

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This ensures that the timers in the script will not be affected by frame rate changes, thus ensuring that systems like described above (which you need to guarantee the same result every timing) will run smoothly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I already opened a PR to achieve this function, and to organize some SceneTreeTimer related code:

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible but less convenient, we will need to implement a global timer to do this, and the performance is not as good as the built-in in heavy usage.

### Is there a reason why this should be core and not an add-on in the asset library?

It integrates seamlessly with the existing SceneTree.create_timer() function without breaking any compatibility and has better performance.

**Comment by L4Vo5** [comment]
I often find myself unable to `get_tree().create_timer()` in gameplay code due to it not running on the physics frame. This would be a welcome change for me.
And indeed, for things like bullet hell where the code for patterns can get pretty complex, having a one-line way to wait for some amount of time is invaluable. `create_timer()` is supposed to be a convenience function, so why not let it run in deterministic portions of the code?

As a side note, it took me some time to realize `create_timer()` ran in the normal process instead of physics, since I hadn't even thought about how it worked when I first started using it. Having the optional argument right there would help make it immediately clear to the user how it works, which could save people some headaches as they may be expecting deterministic behaviour out of their gameplay code.

**Comment by enetheru** [comment]
isn't this resolved?
https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-create-timer
func signature for create timer allows specification of whether to process in the phsyics frame, am i Misunderstanding something?

**Comment by AThousandShips** [comment]
Indeed this has already been implemented, thank you for noticing!
