### ISSUE TITLE
Expose Animation Node inside an Animation tree to editable values

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#4381]
### Describe the project you are working on

working on an advanced movement system with multiple layers

### Describe the problem or limitation you are having in your project

I wanted instead of creating a lot of blend trees for different states (Rifle, Pistol,unarmed,etc)

to just edit AnimationNode and choose another animation 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

edit AnimationNode and choose another animation through inspector and code,

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it should work like setting AnimationTree parameters :

`anim_ref.set("parameters/"AnimTurnLeft"/animation" , "Falling")`
replace "AnimTurnLeft" with any AnimationNode name 

I also would like to have the same feature for the BlendSpace1D and BlendSpace2D.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it is an important feature for advanced animations, and to work around it I will need to add BlendSpace2D for each different state, which will make the tree unreadable for me.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by fire** [comment]
See also https://github.com/godotengine/godot/pull/54327

**Comment by ywmaa** [comment]
I want to be able to edit this node's anim not having "advance expressions" 
![Screenshot from 2022-04-11 12-59-50](https://user-images.githubusercontent.com/68971808/162726685-7dc6424e-4aaf-4f9c-9e7f-57cc334b77f7.png)

**Comment by Hiiamwilliam** [comment]
You can do that in Godot 3 already (assuming the root node of your `AnimationTree` is a `AnimationNodeBlendTree`:

- $AnimationTree.tree_root.get_node("AnimTurnLeft").animation = "name_of_new_animation"

Where "name_of_new_animation" is the name of an animation that exists in the associated `AnimationPlayer`.

I'm pretty sure this is not documented given I found out by trial and error.
Something that makes it even more difficult to discover is that `tree_root` is a very generic type (lots of inheritance), which means Godot doesn't know which documentation page to open when you Ctrl + Click.

**Comment by ywmaa** [comment]
Really that looks awesome, I will try it myself,
I didn't find it anywhere on the docs, 

It must be in the docs as it is very good feature


Once I try it, if it works I will close this issue and open an issue for the docs.

**Comment by ywmaa** [comment]
Does it also work for BlendSpaces ?

**Comment by Hiiamwilliam** [comment]
It should work, yeah. **I didn't test**, but again assuming the root node of your `AnimationTree` is `AnimationNodeBlendTree`:

- $AnimationTree.tree_root.get_node("name_of_BlendSpaceNode").get_blend_point_node(index).animation = "new_anim"

Where index is the index of the current animation inside the BlendSpace (I think it represents the order the animations were added into the BlendSpace) and "new_anim" is the name of another animation in the associated `AnimationPlayer`. 
  
> It must be in the docs as it is very good feature

The problem is that this information _is in the docs_ but getting what you wanted is not straightforward.

In this case, you wanted to change the animation of a node of your `AnimationTree`. So you go to the `AnimationTree` docs. 
It doesn't clearly say how to do what you want, so you don't know where to look next. People may get discouraged to continue looking.
You persist, checking the `tree_root`, which returns an `AnimationNode`. This class also doesn't say how to do what you want, which is another discouraging point. You would need to search through the 10 classes that inherit from it (or, simply print `tree_root`). Eventually you find that the actual root node is `AnimationNode > AnimationRootNode > AnimationNodeBlendTree`.

Again, this class doesn't show you the way (this is why I said it's trial and error, it's easier to print every possible step than to search the docs). You persist and look at its methods, finding `get_node`, which returns... `AnimationNode`, which you already know doesn't give you what you want. You may think it's impossible.

But, surprise, due to Godot being Object Oriented, when you return `AnimationNode` you may also return a class that inherits from it. Which means, if you tried `get_node` on your `AnimTurnLeft`, you would get `AnimationNode > AnimationRootNode > AnimationNodeAnimation`, which is the correct class that allows you to change animation through code. Using a similar thinking, you can get the animations inside a `BlendSpace` etc.

So yeah, the information is there. Finding it though...

**Comment by ywmaa** [comment]
I can confirm that this method works,

but for AnimationBlendSpace it is hard to know the index of the animation (I wanted at first to give each animation a name inside the BlendSpace, but I think it is just easier to show the index of the animation.

so should I close this issue and open a new one, or rename the issue ?

**Comment by ywmaa** [comment]
this is probably out of context but is there a way to use anim_player.get_animation_list() to make exported variable have a selectable list of animation names ?

something like an enum

this won't work, but is there something similar to it ?
`@export_enum(anim_player.get_animation_list()) var AnimationTurn = "name_of_one_of_the_animations"`

**Comment by Hiiamwilliam** [comment]
> but for AnimationBlendSpace it is hard to know the index of the animation

Yeah I think there's no way to know which index represents which animation. It seems you need to use a loop and print both to see their relations.

> so should I close this issue and open a new one, or rename the issue ?

Well, I had this problem, you had this problem, probably someone else will have this problem (even if it's somewhat specific). If you want to, I think you can close this issue and open a new issue on the documentation repository.

About your last comment, I don't know any way of doing that automatically.

**Comment by ywmaa** [comment]
I mean open another issue for showing the index of BlendSpaceAnimations.

**Comment by Hiiamwilliam** [comment]
Hmm, probably open a new one.

However, can you not print the index and the animation name in a loop, as I mentioned? Like:
```gdscript
var blendspace = $AnimationTree.root.get_node("your_blendspace")
for b in blendspace.get_blend_point_count():
   print("index %s, animation %s" % [b, blendspace.get_blend_point_node(b).animation])
```
Disclaimer: I didn't actually test this.

Remember that if you can workaround a problem in a few lines, the proposal has a higher chance to not be accepted (even if the proposal would be useful if accepted).

**Comment by ywmaa** [comment]
Ok, yeah this will be a work around,
 But overall this is a useful feature, maybe I should add it myself and make a pull request ?
Or is it going to be ignored ?

**Comment by Hiiamwilliam** [comment]
> But overall this is a useful feature, maybe I should add it myself and make a pull request ?

You're free to do so, if you wish. 
I'm not sure if this specific problem is so bad that a pull request is warranted. I honestly don't know if it will be ignored or not, that will depend on which contributor is free to review etc. 
Note that enhancements like these should aim `master` branch (Godot 4) with a different pull to Godot 3.

**Comment by ywmaa** [comment]
closing this issue, as I found the docs for animations node(though it needs somekind of digging, but not most people use it anyway so no need for another issue for the docs, 
for reference : 
https://docs.godotengine.org/en/latest/classes/class_animationnodeanimation.html?highlight=AnimationNodeAnimation


I will open another issue for showing AnimationBlendSpace point's index.
