### ISSUE TITLE
Implement an editor for quaternions that exist outside of the Node3D Transform

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot-proposals#4504]
### Describe the project you are working on

none

### Describe the problem or limitation you are having in your project

none

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This will get rid of gimbal lock and keep it simple for less mathematical savy person dealing with quaternions

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

values for rotation degrees in the inspector would be the same but rather than using those values for euler, Godot would calculate quaternion from these values. Simillar to how Unity handles it

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it is change in the Godot itself and couldn't be handled by plugin in any way

**Comment by Calinou** [comment]
This is already supported in 4.0alpha: 
![image](https://user-images.githubusercontent.com/180032/167231807-9fee23ce-a297-4d9c-93f6-de0e8dc1ebbc.png)


I don't think this can be backported to `3.x` though, since it relies on backwards-incompatible changes. (The same applies to the rotation order property).

**Comment by Lasuch69** [comment]
what i meant is using these rotation degrees to calculate quaternion inside of godot and then based on this quaternion rotate the object to get rid of gimbal lock on the surface this would behave like normal euler but when you rotate angles then they don't interfere each other (gimbal lock) this would be godsend for people not understanding quaternions and having trouble with 3d rotation

![image](https://user-images.githubusercontent.com/71460040/167251104-81192e2b-2816-4b10-ade8-babb4b826e0c.png)

as i stated in original comment this how Unity handles rotations by default

**Comment by Zireael07** [comment]
That explains why I never had gimbal locks issues in Unity even though I never consciously used quaternions

**Comment by fire** [comment]
As mentioned this is already implemented.

**Comment by TokageItLab** [comment]
At least in 4.0 Rotation3DTrack is recorded in Quaternion, but it is impossible to manually edit its values. See https://github.com/godotengine/godot/issues/39229 and https://github.com/godotengine/godot/pull/55899.

There are several issues compounding this problem. I think it will be solved if all three of the following are done:

1. reduz mentioned that they are planning an inspector to edit Quaternion
2. the ValueTrack in 3DTransform needs to be eliminated, because 3D rotation needs to be unified so that it is recorded in Quaternion
3. bezier tracks are no longer available in 3DTransform due to 2. we need to have some GUI in TRS3DTracks and BlendShapeTrack so that we can edit easing with bezier curves as well

**Comment by Zireael07** [comment]
Why close? @TokageItLab has clearly showed that it's an issue...

**Comment by TokageItLab** [comment]
In the meantime, I believe that we need to implement the editor inspector for quaternions that exists outside of Node3D.

**Comment by TokageItLab** [comment]
Superseded by #5021.
