### ISSUE TITLE
Implement Retarget feature in the importer

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#4510]
### Describe the project you are working on

Godot Animation System for 3D Model

### Describe the problem or limitation you are having in your project

It is difficult to share animations across multiple models.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It greatly improves the workflow of developing games with assets such as character models and animations.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Retargeting was discussed by #3379. As a result, I implemented https://github.com/godotengine/godot/pull/56902 as a prototype, but the discussion led to the decision that the importer should do the most of the work. Of course, I agree with that.

But, in that prototype, I had implemented Global/Local(RestRelative)/Absolute animations, each of which could be blended, but such real-time retargeting was rejected by @reduz as it being over-tech for most users. I did not agree with it, but as a compromise, I agreed with him that it could be easily implemented as a custom-module. This means that some APIs need to be modularized, exposed, or virtualized so that the animation applying process can be overridden.

Based on the above, I will add an implementation for retargeting in the importer as shown in the following mock-up image:

![ImporterRetargetMock](https://user-images.githubusercontent.com/61938263/167277906-346f2e81-38c8-49c0-971b-89e73a00f236.png)

First of all, prerequisite is the need to unify the roles of the bones. This is accomplished as a bone mapping.

The retargeting process must then be performed after that. It is important to understand that retargeting is just a name given to multiple processes as workflows. In other words, the processes within a retarget can be completely separated into several processes. And I believe that it makes sense to modularize them as plug-ins.

With modularization, when more advanced processing is needed, add-on features such as custom modules can allow it to be highly integrated with the built-in processes in the importer. This allows us to create plug-ins outside of core such as "do real-time retargeting", "reproduce RestRelative animations like Godot 3" and "import original bone information before renaming or re-resting as dictionary".

So this proposal can be separated into several PRs, as follows:

----

(Basic feature)
~1. Implement Bone Mapper~ Done in https://github.com/godotengine/godot/pull/61610
~2. Implement Bone Renamer~ Done in https://github.com/godotengine/godot/pull/61610
~3. Implement Rest Pose Fixer~ Done in https://github.com/godotengine/godot/pull/62939
~4. Implement Position Track Optimizer (Adjust for root motion)~ Done in https://github.com/godotengine/godot/pull/63138

----

(Advance feature)
~~5. Change Animation API to expose the processes for custom-modules (Make RealtimeRetarget Extention as custom-module)~~ API has been changed in https://github.com/godotengine/godot/pull/63138
6. Improve Mapping GUI ~~(Add Pulldown "Profile Bone" Selector & Highlight Bone Position In Scene)~~ Added BoneTreeDialog in https://github.com/godotengine/godot/pull/63854
7. Implement Mapping Estimation https://github.com/godotengine/godot/pull/63854

----

My plan is to try to implement 1 and 2 at the same time first, and if that goes well, we can work on the other PRs as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

A simple retargeting system is needed by most light users. It also needs to be changed to allow the Animation process API to be exposed for advanced users.

**Comment by SaracenOne** [comment]
I like this, it looks very sensible and should cover most of what people should need out of import-time retargeting.

**Comment by reduz** [comment]
This looks really good to me, I suppose there are a couple of things that come to mind:
* Option to keep some existing bones that are children of retargeted bones (like for tails, hair, etc).
* For T-Posing I think it should be selectable whether you want a standard T-Pose, or use one of the animations for it (or an external resource i guess?). At least I recall this was something you needed.

**Comment by TokageItLab** [comment]
> Option to keep some existing bones that are children of retargeted bones (like for tails, hair, etc).

It was planned that no processing would be done on unmapped bones, meaning that the animation would be imported as is. However indeed, it would be better to be able to choose whether they are imported or not, to reduce the size of the sharable animations.

BTW, since errors are always printed for tracks that are not currently found, it may be necessary to reduce the output warning.

> For T-Posing I think it should be selectable whether you want a standard T-Pose, or use one of the animations for it (or an external resource i guess?). At least I recall this was something you needed.

@reduz I was thinking that reference pose is a resource that can be output from SkeletonEditor, would it be better to use gltf?

**Comment by TokageItLab** [comment]
> I was thinking that reference pose is a resource that can be output from SkeletonEditor or anyway, would it be better to use gltf?

In that case, I think we need something to take out only the poses, since we need to avoid using an importer in the importer, so we will discuss this with @fire when we implement the T-poser.

**Comment by Ansraer** [comment]
Could you explain a bit how this proposal differs from #4296?

My naive understanding is that AnimationLibraries should do the trick as long as both the animation source and target use the exact same skeleton, while this proposal would be useful when one of the skeletons has additional bones or the target and source have different sizes.

Assuming my assumption is correct, would the animation retarget imported create a new AnimationLibrary I can simply apply to my target model?

**Comment by Zireael07** [comment]
> My naive understanding is that AnimationLibraries should do the trick as long as both the animation source and target use the exact same skeleton, while this proposal would be useful when one of the skeletons has additional bones or the target and source have different sizes.

Not just different sizes. I have several meshes from the same author that were in different packs, so the bones are differently named and this is enough to confuse Godot.

**Comment by WiredDreamcaster** [comment]
Is there a public repo available to follow?

**Comment by Zireael07** [comment]
@WiredDreamcaster: This is a proposal repo. The previous PR was linked in the OP. This proposal is yet to be implemented.

**Comment by WiredDreamcaster** [comment]
Assuming we have not approved this yet, I want to share my experiences in support of this proposal:

One of the biggest challenges and procrastinations for me leaving Unity for Godot was that Godot lacked a skeletal animation retargeting system. I still avoid it in Godot, and have been waiting for a proper skeletal retargeting system -- I have even regrettably considered using Unity again just to access this feature, as much as it pains me to admit...

This would be an invaluable utility for developers who make their own 3D characters and animations in house, and those  who want to use 3D characters with external animations for their games and vice versa. **Even Blender**, a very mature and versatile do-it-all software **does not** possess the capability to perform skeletal animation retargeting with any sense of ease or accuracy and requires 3rd party plugins to even attempt it. This is a feature Unity truly excels with in the industry, with Unreal taking note. I feel every game engine, in their own ways, do not understand all of their pain points, and how could they? This is a massive pain point for Godot IMHO. Having this feature added would be an **immense** punch up for Godot developers and _potential developers_ trying to get out of the Unity ecosystem and into a libre game development environment, where people can just make games. This is something I've discussed with colleagues in the professional game development field many times, and we all share the consensus that **it unfortunately holds Godot's potential back**.

I don't know how old the discussion for why it shouldn't be implemented in Godot was, but it seems pretty short sighted to say game devs should create their own animation blending/retargeting systems, instead of having an official utility that comes with Godot. This is a reoccurring barrier for game developers, if the Godot project is serious about making 3D games, we _need_ support for sharing animations between different 3D characters, formats, and skeletons. This is an absolute must. 

I'd love to help contribute to this effort if possible, even if I can only raise my voice in support right now, and I'm sure others have and will too.

**Comment by Calinou** [comment]
@WiredDreamcaster Animation retargeting is already being worked on for Godot 4.0.

**Comment by w548544375** [comment]
this is fucking awesome,i love it.
