### ISSUE TITLE
Nest shader inspector when shader editor is opened from another resource

### ISSUE THREAD

**Issue by Wolfe2x7** [godotengine/godot-proposals#4528]
### Describe the project you are working on

A 2D game utilizing shaders.

### Describe the problem or limitation you are having in your project

![Screenshot from 2022-05-11 03-36-45](https://user-images.githubusercontent.com/72348938/167809488-8559ac66-0a03-4f98-9706-90ba5b6467b3.png)

The inspector shown when the shader editor is open is not super useful. While editing a shader, referring to the last inspector you were on means closing the shader editor, and writing the shader means switching away from the other inspector. Having to go back and forth seems unnecessary.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice if the above inspector was nested inside the opened inspector like some other resources. This would solve having to switch back and forth between inspectors if you wish to refer to something else while editing a shader.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a shader is opened for editing from another resource, might it be possible to nest the shader inspector instead of changing the whole inspector? Then, the "Shader" option on the bottom panel may become unavailable when a different resource/node is selected, closing the shader editor in a similar way to the current behavior:

![Screenshot from 2022-05-11 03-58-02](https://user-images.githubusercontent.com/72348938/167815041-a1c2cc7c-1977-4c0a-bd4f-b7cddcc3dcb0.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it may be a worthy interface improvement for all users.

**Comment by YuriSizov** [comment]
It's a forced measure, unfortunately. I had to disable embedded sub-inspectors for resources with dedicated editors in 3.4 because they have too many issues. While they work in some cases just fine, in others they get completely broken and unusable.

I was actually working on making ShaderMaterial editable with the shader editor so that we can simply select it to edit the underlying shader text/graph, but my plans got halted by the war. It was tricky, but I think it might still work. If anyone wants to pick up that task for now, be my guest!

**Comment by Zireael07** [comment]
@YuriSizov: Stay safe <3

**Comment by Wolfe2x7** [comment]
I think I have nothing to suggest anymore by now, in Godot 4.1.
