### ISSUE TITLE
Add UIDs to script files

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4603]
### Describe the project you are working on

Big project in Godot

### Describe the problem or limitation you are having in your project

While I don't have this problem personally, it's recurring issue for many users that moving files outside Godot will break path references. This was mostly resolved in 4.0 with the introduction of Resource UIDs, but this feature exists only for tscn and tres files (and their binary equivalents) and imported files. It's lacking in Scripts, so when you e.g. move a script inside your IDE, everything breaks.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Scripts should have associated UIDs, so you can attach/load them without relying on rigid file paths.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are a couple of possible implementations. The one I have in mind is just adding a comment line at the beginning of each script.
The line would be simply `#UID: som3randomU1D`. This way when you want to get UID of a script, you just need to load the first line and avoid parsing it. If the line doesn't start with `#UID`, the file has no id. This could work for any scripting language and the `#` would just be replaced with its comment equivalent (not sure about VisualScript though, as it's binary).

Having an auto-generated line in each script that you can't touch is obviously problematic, so the line could be folded by default and the feature itself would be opt-out in Project Settings if someone doesn't want it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's not about lines. Well, technically it is, but not in that sense.

### Is there a reason why this should be core and not an add-on in the asset library?

Can't be an addon.

**Comment by Kopkako** [comment]
Thank you for opening this proposal, it is definitely my number 1 problem right now with scripting - having entire projects break because your IDE did some auto-refactoring/moving files around is not a good feeling.

I am not sure about the idea of adding text to scripts, but I also feel it might fit in with KISS.
Unity famously uses `.meta` files for everything and it's a complete pain to work with them. I also feel that it's a big part of what makes the Unity editor so unusably slow, so I would not advise for that.

I don't love the optics of having a GUID identifier in every script file, and I also feel like it might be an issue if files are created from outside the Godot editor: How do you add a GUID by hand?

**Comment by KoBeWi** [comment]
> I am not sure about the idea of adding text to scripts

It's a necessity. There is no other place to put them if we want UIDs to be handled transparently for the user (i.e. you just add/move files and the editor handles the rest); at least not without affecting performance too much.

> Unity famously uses .meta files for everything and it's a complete pain to work with them.

Agreed. The existence of `.import` files is already a pain for me, but luckily no other meta files are needed and will likely never be added.

> How do you add a GUID by hand?

You don't. Editor should auto-detect new scripts and add UID when necessary.

**Comment by Kopkako** [comment]
> You don't. Editor should auto-detect new scripts and add UID when necessary.

Ah, I did not realize this would be the method - well that seems great, then!

It looks like a really simple, robust solution that adds a microscopic amount of boilerplate while adding the enormous benefit of allowing real refactoring capabilities - I would love it!

The C# equivalent could maybe be:
```cs
// UID: som3randomU1D
```

**Comment by Calinou** [comment]
Shouldn't UIDs be written as annotations rather than as comments? They affect script behavior, and I think comments should not do that.

**Comment by KoBeWi** [comment]
It could be annotation, but we should avoid parsing the script, so the annotation would still be accessed as text and couldn't be moved to another line.

**Comment by YuriSizov** [comment]
> but luckily no other meta files are needed and will likely never be added.

Technically, global namespace that you fill with `class_name` is currently stored in a meta file, the main one, `project.godot`. I was about to suggest we maybe have a similar meta file for all scripts and their UIDs (in `.godot` folder), but then again, cache invalidation is a real problem all the time...

**Comment by Byteron** [comment]
> Shouldn't UIDs be written as annotations rather than as comments? They affect script behavior, and I think comments shouldn't do that. (In other words, a script should never break if you remove all comments from it.)

Not sure if annotations are a thing. I feel this feature is more important to the C# folks than it is to the GDScript folks since most GDScript folks don't use an external IDE and thus don't have this problem.

**Comment by KoBeWi** [comment]
C# does have annotations, but not all languages have them (while all have comments), so it's probably not perfect solution for extensions.

**Comment by Kopkako** [comment]
I couldn't find any resources on C# annotations, maybe you meant Attributes? Like this:

```cs
[GodotUID("Som3GU1D")]
public class SomeNode : Node
{
}
```
If so, I don't think using Attributes would be a good idea:
- It looks really verbose and ugly imho
- Sometimes you might add more attributes to the class, making it difficult to parse from the Godot side

I think simple comments, even if not strictly best practice, might work well.

**Comment by raulsntos** [comment]
In C#, attributes would be the perfect thing to use (that's what they are for, they add metadata).

> Sometimes you might add more attributes to the class, making it difficult to parse from the Godot side

I don't see how using attributes would make it more difficult to parse (we don't parse C# files by the way).

> It looks really verbose and ugly imho

You won't even see it, in `master` we are already using the attribute `ScriptPathAttribute` to keep track of the path of the file where C# classes are defined. We use source generators so the attribute is added to your classes, it's not in your actual files.

---

However, I'm not sure this would even be necessary in C#. In the future (Godot 4.x) the idea is for C# to behave more like C++ where there are no script files because it's a compiled language, your _scripts_ would behave like built-in Nodes[^1].

[^1]: https://github.com/godotengine/godot-proposals/issues/2333#issuecomment-857875677

**Comment by raulsntos** [comment]
We don't parse C# files, that's done by Mono/CLR, so as long as it's valid C# it will be parseable already and we don't have to implement it in Godot's side.

**Comment by Byteron** [comment]
> However, I'm not sure this would even be necessary in C#. In the future (Godot 4.x) the idea is for C# to behave more like C++ where there are no script files because it's a compiled language, your scripts would behave like built-in Nodes.

it would definitely be necessary. Just because your nodes show up as build-in nodes doesn't mean you won't move your csharp files around when refactoring.

**Comment by raulsntos** [comment]
So the problem is right now scenes store the path to the script file, if you move the file then the path is no longer valid and your scene breaks.

If you take a look at a scene file you'll notice that built-in nodes don't use a path. Nodes created by a GDExtension language will also not use a path, that's why it's a better fit for compiled languages. And since we don't use paths moving the files no longer breaks the scene, that's why I said I don't think this would be necessary for C#.

**Comment by KoBeWi** [comment]
UIDs are only for file paths, they don't map to class names.

**Comment by me2beats** [comment]
Is this something like class_name but without making it a "class"

**Comment by willnationsdev** [comment]
@me2beats No, not at all. They are merely trying to find a way to uniquely identify a class's *script file* in such a way that even if the file moves in an external IDE, the Godot Editor doesn't get confused about where the file is and all references to the file start throwing errors looking for it. Godot 4's Resource UIDs solve that issue for the most part, but they don't apply to scripts. While you can re-identify a script if it has a global script class, any script *lacking* that (e.g. C#, VisualScript) won't be able to use that. And even then, if the file is both moved AND has its global class name changed in a separate IDE, then Godot still won't be able to identify it and automatically resolve failed resource references when the Godot Editor regains focus.

**Comment by ashelleyPurdue** [comment]
Hard disagree with this.  UIDs run counter to Godot's philosophy of being version-control-friendly, because they're a non-deterministic, auto-generated value that has the potential to be accidentally _re_-generated at any point.  They're just like Unity's dreaded meta files, and frankly they shouldn't have been added to resources either.

**Comment by KoBeWi** [comment]
UID support for GDScript was added in https://github.com/godotengine/godot/pull/67132

**Comment by KoBeWi** [comment]
Implemented by #97352

**Comment by MikeSchulze** [comment]
Hello, I unfortunately only became aware of the introduction of UIDs through testing with Godot 4.4-dev5.
After expressing my dislike of this solution somewhat rudely on Discord, I had a day to think about it again.

And I must say, I think this is using a sledgehammer to crack a nut.
The main reason is to support users who deliberately or unknowingly destroy their projects by moving resources that are dependent on scenes.
I don't understand why there's a belief that the Godot Engine should be responsible for solving problems that were clearly caused by users?
If I move classes or dependencies externally in C++ or C#, the project breaks there too, and nobody asks if VS or Rider will magically fix it for you.

Moreover, introducing UIDs won't help when users improperly handle their project resources.
Here's a small example that reduces this solution to absurdity:
To hide the "annoying" UID files in VS or Rider as suggested above, moving individual resources would result in the UID files remaining in their old location.
This completely breaks this solution, and worse, when Godot restarts, a new UID is created while the original UID remains as a corpse in the filesystem.
Additionally, UIDs are being created for all resources and scripts regardless of whether they are referenced by a scene.

Therefore, I wonder how many users really have this problem and how often does it occur?
There's already help in Godot to fix broken scenes through a dialog that helps reassign orphaned references.
The argument about someone breaking many scenes - honestly, a) how often does that happen? And if someone is restructuring their entire project,
they should just use the Godot editor which ensures dependencies are automatically resolved.

To "punish" all other users for this and flood the filesystem with these UID files is, in my opinion, completely the wrong approach.
It would be more sensible to educate users about what it means to manage a scene and how resource dependencies work.

Even Unity or Unreal explicitly point out that externally moving resources breaks the project.
So what exactly bothers me about this solution:

* UID files are created for all scripts and resources regardless of whether they're used in a scene
* It basically doubles the file count and "pollutes" the filesystem
* We're supposed to include these files in the repository, NO
* Using file filters in external IDEs breaks this approach
* Users are still required to maintain discipline to move script+UID files to the same location
* Users are still required to maintain discipline to rename script+UID files to maintain the relationship

Currently, I see more negative impacts than positive ones, so please don't roll this change into the final Godot 4.4 version.

**Comment by KoBeWi** [comment]
One of the main complains users have about Godot is over-reliance on hard-coded paths. UIDs don't just allow to move files more easily, they also allow referring to them in path-agnostic way and without a risk of cyclic loading.

Los of users asked to have UIDs and we already had them since Godot 4.0. The recent change just made it consistently supported for all Resources. It's was not about adding UID support at all, but adding it where it's missing.

> nobody asks if VS or Rider will magically fix it for you.

Godot is not an IDE, but a game engine. It's used by a variety of people, not only programmers.

> Even Unity or Unreal explicitly point out that externally moving resources breaks the project.

If you move files in Unity together with them `.meta`, they won't break.

> It would be more sensible to educate users about what it means to manage a scene and how resource dependencies work.

No amount of education will unfortunately help in this case, otherwise the feature would've never been added. Even if we added super comprehensive docs on the topic, that requires reading them, which most people just don't do.

---

UID support seems to be hot topic among users, we might make a blog post about that eventually, to explain what are UIDs and why do they exist.

**Comment by MikeSchulze** [comment]
To perhaps clear up a misunderstanding here: I'm not against UIDs, they make perfect sense.
I'm just against the solution of saving this as an additional file, which floods the file system and doesn't guarantee that it will work reliably as mentioned in my post

**Comment by KoBeWi** [comment]
Feel free to propose a better way.
There is #99090, but a similar solution existed in the past and was reverted.
Extra files does not prevent us from implementing a better way of storing UIDs where needed, they were only supposed to provide a solution that can work for every Resource.

**Comment by MikeSchulze** [comment]
https://github.com/godotengine/godot-proposals/issues/11223

**Comment by ArchercatNEO** [comment]
Looking at the PR that implemented this it says that the .uid file must also be moved (which is the same for .import files) however it seems like these files could be used to allow moving files and letting godot move orphan uid files to "new" files.

First maintain a cache of uid -> file hash inside `.godot` that is hopefully maintained and invalidated enough.
When a "new" file is detected first  look for orphaned import/uid files and do a hash check to hopefully automatically move the import/uid instead of regenerating a file.
If a "new" file does not match an existing uid hash (it has been moved *and* edited) but there are still orphan uid files display a popup asking if you moved the file to resolve the conflict.
If there are no orphan uid files the file is simply new -> create a .uid/.import

Would this not resolve moving only the main file without it's partner file without messing further with version control?

**Comment by markdchurchill** [comment]
> Feel free to propose a better way. There is #99090, but a similar solution existed in the past and was reverted. Extra files does not prevent us from implementing a better way of storing UIDs where needed, they were only supposed to provide a solution that can work for every Resource.

This does seem like a solution that only really partly and tangentially solves an underlying issue, and brings in additional problems. (I also just became aware of this while trialling 4.4dev). A few points on where my head is at from scanning this thread:

* Many file formats do not and will not support an inbuilt canonical identity. While we can add metadata into script files, we can't stamp a (eg) PNG with a UID.
* Filesystem paths are *not* a "programmer specific" thing, these are generally the primary way that an asset is identified and organized. The relative path *is the identity*. This admittedly leads to problems when files are reorganized, as assets will lose their identity.
* Moving files when outside of the controlled environment of the Editor gives no guarantee that metadata files will also be moved. This leads me to think metadata files are a poor solution.
* The problem is really one of bridging the identity in the short term. The path will still be stable over the long term.

So to find an arbitrary missing file, in a working project directory (ie, no synthetic fresh checkout, the file used to exist on this machine) and update the identity to the new path - it seems something like centralized tracking of filenames/checksums for files would provide a short term identity that can help bridge issues when a known file disappears and a new one appears somewhere else.

None of this obviously is relevant for resources that can have a unique id baked into them.

**Comment by Calinou** [comment]
> Many file formats do not and will not support an inbuilt canonical identity. While we can add metadata into script files, we can't stamp a (eg) PNG with a UID.

The UID is contained in the `.import` file already.
