### ISSUE TITLE
Add shader recycling to have zero cost runtime shader compilation

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot-proposals#4754]
### Describe the project you are working on

This would be good for many kinds of games (action especially) which have a high complexity in regards to shaders. The problem described below happens at least in several released titles.

### Describe the problem or limitation you are having in your project

If the game has many combinations of shaders and shader conditions (lights present or not, shadows enabled or not, meshes compressed or not, etc.), asynchronous shader compilation may not be enough to prevent fps hiccups if not yet compiled variations of a shader appear at a fast pace and/or the target hardware is not powerful enough to handle both the game and background compilation smoothly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A new node type, `ShaderRecycler`, and a new resource type, `ShaderDepot`. (Not using the 'cache' word, because the engine already has the concept of shader cache used for a different purpose. Suggestions about naming welcome.)

While you are playing your game during development, a `ShaderRecycler` node watches for shader compilations and saves into a `ShaderDepot` resource some information about each of them: like shader source code (Godot sahder lang, not graphics API lang) and hash of the source code, plus maybe some other needed bookkeeping information.

While the game is being played, the `ShaderRecycler` loads the `ShaderDepot` and compiles all the shaders it captured (this may be synchronous or asynchronous so a loading screen can animate while this happens). Then, when a specific combination of shader code and shader conditions is needed during gameplay, the rendering infrastructure will notice it's already there and can just make use of it without the slightest hiccup.

---

It's up to the developer how to shape their shader recycling strategy. One can just have a single `ShaderRecycler` node in a singleton working against a single `ShaderDepot` resource; probably enough for a simple game. Another option would be to have a `ShaderRecycler` node on the base scene for a level of the game, with the relevant property overridden in each specific level so each one has its own `ShaderDepot`; this may work better in a game in that a high variability in shader usage is expected across levels. Or any other, as the developer sees fit.

---

Would it be better use `ShaderRecyclerDepot` or `ShaderRecyclingDepot` instead of `ShaderDepot` so they are intuitively identified as related?

---

P.S.: I've written this proposal thanks to the inspiration that @akien-mga provided about the possibility of having a feature like this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`ShaderRecycler` would have a single property:
- `shader_depot`: path to the `ShaderDepot` resource that it will load from and/or save to.

Whether the `ShaderRecycler` is in load only or load/save mode is controlled by the following:
- On a debug-enabled build, with the debugger attached (run from the editor), it's load/save, unless a new debug setting, say _Load-Only Shader Recycling_, is enabled.
- On a debug-enabled build, without the debugger attached (e.g., run from the command line via the editor binary), it's load-only, unless the `--shader-recycler-enable-capture` command line switch is passed (useful for automation of the capture of shaders).
- Pure release builds (export templates) can't capture; they're always load-only.

---

The developer may want to clear a shader depot if many changes have happened to the usage of shaders and they want to be sure not many stales entries are taking space. That's just as easy as removing the shader depot file. However, a new debug setting, _Reset Shader Recycling Depots_, and a new command line switch, `--shader-recycle-reset-depots`, will do it automatically whenever a `ShaderRecycler` is given a `ShaderDepot` path.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Impossible. The rendering code in the engine has to provide this feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Same as above.

**Comment by Janders1800** [comment]
> A new node type, ShaderRecycler, and a new resource type, ShaderDepot. (Not using the 'cache' word, because the engine already has the concept of shader cache used for a different purpose. Suggestions about naming welcome.)

ShaderLibrary, ShaderArchive, ShaderGroup, ShaderPoll. Those come to mind.

**Comment by CodeDoctorDE** [comment]
Unreal engine has something like "Material Instances". That would be really great to save performance!

**Comment by RedMser** [comment]
Just to confirm my understanding: Every time a shader is edited, the developer has to play through their entire game to update all of the depots (or write a script which automatically warps them through every level)?

There should probably be a configuration warning on the `ShaderRecycler` node to inform about its depot being outdated (can be detected via mismatching hashes or shader code). Maybe even a method that can be queried, so it can for example be detected by a plugin before the game export.

> Another option would be to have a `ShaderRecycler` node on the base scene for a level of the game, with the relevant property overridden in each specific level so each one has its own `ShaderDepot`

Depending on how large the `ShaderDepot`s can get, it might even make sense for them to be able to inherit from one another, to avoid storing redundant information.

So following your example, you could cache all core gameplay elements (but no level geometry) in one "base" depot. In each level's depot, you specify this "base depot" as a parent. Then during capture, only the level geometry's shaders would get added to the level depot, reducing the size.

**Comment by RandomShaper** [comment]
> Just to confirm my understanding: Every time a shader is edited, the developer has to play through their entire game to update all of the depots (or write a script which automatically warps them through every level)?

Good question. The sad answer is yes. And I can't think of any good way around it. Depots are not meant to contain the paths of the shaders, but just hashes of their code. That allows to have shaders generated on the fly, like `StandardMaterial3D` does, for instance. It would be technically possible to track the paths in some cases, but not in others and I'm not sure what an ergonomic way to handle that would be. I had written this to add to the PR description, until I realized that wouldn't work for non-trackable shaders, so the system would not be trustworthy:
> `ShaderRecycler` nodes will display a warning if some of the shaders its `ShaderDepot` resource contains data about has changed. There will be a one-click way to update the depot (it won't be necessary to run a session of the game because it already knows the usages). Alternatively, there would be one project-wide mechanism to make sure all the depots are up-to-date. The exporting flow will inform if some depot is outdated and will give the opportunity to have it fixed (or just do it routinely without asking; to be decided). It should also be possible via the new command-line argument `--shader-recycler-`. All that said, capture mode will update changed shaders, but

---

> Depending on how large the `ShaderDepot`s can get, it might even make sense for them to be able to inherit from one another, to avoid storing redundant information.

Maybe we want composition here rather than inheritance. Inheritance may get tricky due to potentially broken links, etc. With composition, with multiple `ShaderRecycler`s., As long as one `ShaderDepot` already contains data for a shader, it won't be captured in another one.

**Comment by realkotob** [comment]
@RandomShaper A slightly more user-friendly workflow would be to actually give the option to record the user input/world data during a playthrough and allow the developer to re-run that as a simulation to re-generate the recycled shaders.

Definitely a bit silly, but it would work and it's not as complicated as it sounds.

**Comment by RPicster** [comment]
Joining in because we talked about it at the GDC:
I think the general usefulness of the idea is great - my only concern is the same as @RedMser - Playing through the whole game to grab all shader variants can be a bit messy.

So let's get back to the reason why this is useful: To avoid stutters by shader compilations.

Almost all serious Godot games I know use some kind of shader pre-compilation. Either during the loading screen or somewhere in the background.

So developers are aware of the problem and how to fix it.
The frustration starts when you have all the shaders and materials saved and load them during your pre-compilation phase, but you still get stutters.

This is - by my knowledge - almost always caused by conditionals that cause a recompilation.

Eventually it would help to give developers better tools to easier catch and understand the different conditionals - and also educate about this topic.
If you think for example about the case in Beat Invaders where it was just contact shadow being enabled on one light. Neither did I know about the topic at all, nor did I know what and when the stutter was caused.

Just throwing around ideas here, I'm not against the concept, I just don't like that I basically have to play through all the game, use all the skills, show all meshes / items in all situations just to have a general "it should be fine" mindset without knowing why or what is going on in the background.

**Comment by clayjohn** [comment]
@RPicster That is helpful feedback. There is a long history behind shader compilation stutters, but in short, engine developers faced the same issues as you when using API's like OpenGL. Even we don't know exactly what combination of settings will trigger a shader recompilation when using OpenGL because drivers sometimes need to recompile shaders when changing related state (like blend modes for example). 

With Vulkan the situation is much better and we are better able to flag for users what settings will trigger new pipeline variants (with Vulkan the stutter is from compiling pipelines not just shaders). Since we compile pipelines up front (i.e. when a setting is changed) we are much better able to warn a user when they are triggering pipeline re-compiles. 

To me, the biggest question is how to communicate this effectively to the user?

**Comment by Calinou** [comment]
> To me, the biggest question is how to communicate this effectively to the user?

Could we add a new option to the Debug menu at the top of the editor called **Debug Shader Compilation** (plus a `--debug-shader-compilation` CLI argument) that prints a line every time a new shader is compiled, and what triggered this compilation?

**Comment by Jamsers** [comment]
Manually collecting PSO caches by playing though the game is tedious to the point of ridiculousness, but it's important to note that this is pretty much the best approach the industry as a whole has at this moment. Even Unreal's approach is like this: https://dev.epicgames.com/documentation/en-us/unreal-engine/manually-creating-bundled-pso-caches-in-unreal-engine#collectingrecordedpsocaches

Even all the in house engines that do shader precomp well, like Call of Duty's engine, or Horizon's Decima Engine, most likely uses this approach, backed by an army of QA playing through every nook and cranny of the game. So we're definitely on the right track.

Completely and utterly avoiding any and all shader stutter is pretty important for some types of games. If you're making a single player linear game for example, a player's first playthough is pretty much the *only* playthough that matters - so "don't worry, the game gets smoother the more you play it" doesn't fly in that case.

As long as there's a method to collect PSO cache, a way to explicitly detect any cache "misses" in dev builds, and a way to precomp the whole cache on the player's machine, game devs that have a special interest in completely squashing shader comp stutter should be OK, tedious as the whole process may be. For devs that don't wanna deal with this tediousness, or who don't need perfectly stutter free gameplay, there's always [asynchronous real time shader comp](https://github.com/godotengine/godot/pull/90400) that should alleviate stuttering significantly by default at least.

**Comment by clayjohn** [comment]
@Jamsers https://github.com/godotengine/godot/pull/90400 will make this proposal obsolete. With https://github.com/godotengine/godot/pull/90400 you can easily identify shader compiles in advance and avoid them. 

To reduce load times, we can easily add a way to pre-compile and ship SPIRV so compilation cost is reduced as much as possible

**Comment by KeyboardDanni** [comment]
On the subject of Unreal, Digital Foundry explored this with the Fortnite upgrade to Unreal Engine 5.1: https://www.youtube.com/watch?v=O6GC8TZbJmI&t=1580s

Basically:
- Shader stutter in Unreal Engine 5 is still not perfect, but is much improved with async compilation.
- Background compilation occurs while in the menu, so that your first game is at least a bit smoother.
- While in-game, the engine will try to background compile shaders ahead of time asynchronously, but it does not have a priority system, so if you move too quickly through the world you will outrun the background compilation and get some traversal stutter.
- In the video they mention that the devs are looking into improving this (for example, only showing the object when the material has been compiled). Unsure if some of these improvements have been added to the engine since then/

**Comment by RandomShaper** [comment]
I think this proposal is fairly outdated now. As mentioned, https://github.com/godotengine/godot/pull/90400 already does a great job in avoiding stutters. There may be future efforts to add some pre-compilation steps in addition to that, as far as platforms allow, but that's divergent with what was proposed here.

So, I'm closing this now. The discussion can continue in Godot chat or in subsequent, more focused proposals that already have the aforementioned PR as a starting point.
