### ISSUE TITLE
Build Godot Engine as a shared library

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#4773]
### Describe the project you are working on

Multiplayer Video game - https://github.com/V-Sekai

### Describe the problem or limitation you are having in your project

1. I want to have dynamic mesh plugins and Houdini and Houdini like effects from OpenMeshEffect.

2. @punto- Mentioned wanted to use Godot Engine from nodejs.

3. I want to call libgodot from elixir.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The standard architecture of Godot Engine is that we want things to be Godot Engine Extensions.

It should be possible to embed Godot Engine into a shared library for OpenMeshEffect standard and also as an Extension.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Build Godot Engine as a shared library.

Replace the entry points of main.

See pull request.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No! This is a buildsystem change to Godot Engine.

### Is there a reason why this should be core and not an add-on in the asset library?

Changing the build system of Godot Engine is difficult to most people.

**Comment by GeorgeS2019** [comment]
@fire How will this approach complement [the dotnet6 branch approach](https://github.com/godotengine/godot-proposals/issues/2333)?

> use Godot Engine from nodejs

The same could be from c# by interop with the exposed c++ functions.

**Comment by IlyaStuurFedorov** [comment]
I am probably missing something, but why would there be a need for a library version of Godot? Looking at the resulting implementation it essentially provides same functionality as if it was running as a standalone version, maybe I am not getting something.

**Comment by fire** [comment]
It exposes all the functions from godot engine on Linux .

So I can run:

### Setup

1. Main::setup
2. Main::start()
3. os.run()


### 

1. iterate()
1. call any exposed symbol

**Comment by IlyaStuurFedorov** [comment]
I get that, and that is what's bugging me about this. If this simply exposes main engine loop to be called manually from the outside code, why would you need something like this? This is not a critique btw, I simply dont understand a practical application of running an engine that enforces its way or running processing code, event dispatch/poll, function call order e.t.c., e.t.c, e.t.c., as an external lib.

**Comment by fire** [comment]
# Language integration

1. This is an alternative way to implement C# integration. Not my focus though.

## Calling as a process

1. OpenMeshEffect plugins are single shared library named .ofx
2. Usable from nodejs as a direct c code integration.
3. Call libgodot from elixir 

For example I want to call a process to resize a mesh and output a gltf as a batch job.

**Comment by Lucrecious** [comment]
I am interested in this as well for a separate reason.

I'm pretty ignorant on Godot's rendering pipeline and rendering in general, so what I'm talking about or proposing might not make any sense or might be impossible to do... but

I was thinking about Godot Engine as a static/dynamic library as a way of creating an agnostic 3D viewport renderer for embedding into applications. In Godot, you can save the contents of a viewport to an image, or capture the results on a `ViewportTexture`...

If there was a faster way of getting the image data from the viewport without encoding it as an image, would it be possible to embed a Godot Viewport in another applications?

Dear ImGUI is agnostic in the sense that you can hook it up to any rendering and input system - is something like this possible in Godot? Like Godot handles all the rendering using OpenGL/Vulkan, but since it'd be a library then we can take the image data and display it somewhere?

**Comment by techchol** [comment]
My interest is similar to @Lucrecious I want to use this in MAUI view so we can reuse as much backend code as possible on Multiplatform.
using the native UI as Menu (Both stylistic and UX reason).
Right now we kinda use frankenstein of BlazorWebView with Pixi.js as renderer then laying the Native menu on top.
If this is possible it would be way more efficient since we dont have to use WebGL and JSInterlop.

**Comment by GeorgeS2019** [comment]
Hosting Godot in MAUI as feedback from this [discussion](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview)

**Comment by ErivanDev** [comment]
I'm developing a prototype of an HTML multiplayer game that interacts with Colyseus.js on the client, on the server I want to use Godot as a Game Server running inside Node.js, so I removed the calls to WebGL (like the server version of Godot) and other things, and exported the template. I was thinking of opening a proposal for that, but maybe this proposal covers what I described. Am I right? Does this proposal cover that case?

**Comment by Calinou** [comment]
> on the server I want to use Godot as a Game Server running inside Node.js,

For Godot 3.x, this can be done by porting the `server` platform to be buildable for HTML5. This is a lot of work though.

For Godot 4.0, this can be done by running an HTML5 export template with the `--headless` command line argument. In fact, this is the only currently supported use of Godot 4.0 in HTML5 right now, as the WebGL renderer hasn't been reimplemented yet.

**Comment by fire** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/6267 The other proposal has an open pr

**Comment by Calinou** [comment]
Closing per the above comment.
