### ISSUE TITLE
Ray tracing support

### ISSUE THREAD

**Issue by GumaD3v** [godotengine/godot-proposals#4870]
### Describe the project you are working on

A realistic survival game

### Describe the problem or limitation you are having in your project

In my game lighting and reflections aren't as realistic as I wanted

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add ray tracing support

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an option to enable ray tracing, it could be done with the vulkan extension and enabled/disabled by a project option changeable at runtime

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can't be worked around without writing a ray tracer and displaying it's contents with a sprite

### Is there a reason why this should be core and not an add-on in the asset library?

It would be inefficient to make it run on the cpu

**Comment by Calinou** [comment]
> There may be already a proposal for this anyway.

I couldn't find a proposal about raytracing support, but the [Discussions](https://github.com/godotengine/godot-proposals/discussions) tab should be used anyway when you don't have a *concrete* implementation idea. Also, remember that raytracing-capable GPU adoption remains low as of 2022 due to the ongoing GPU shortage.

**Comment by mrjustaguy** [comment]
Currently there are no Proposals/Discussions regarding any form of Ray Tracing active.

However I do think we should be considering some RT effects in the near future that make the most sense even on low-end RT hardware, as adoption rates are increasing, and games generally tend to take a few years to make. Given the Community Data https://docs.google.com/forms/d/e/1FAIpQLSe-OIpxXqou9cDnPXEAjxzpICbf8_YZB3jUizdECXRydtB8cA/viewanalytics 20% of developers already have an RT capable GPU, and 75% of people got their GPUs in the last 5 years, and the fact that there's likely going to be a fresh influx of RT capable GPUs due to the Crypto Crash, the Interest in RT is likely only going to increase in the next few years.

Now that said, I think that at first RT support should be very limited to specific effects that are both relatively cheap, and are really difficult to get looking good with Raster.
The RT implementation Order should probably be:
1) Reflections - This should be the main focus of RT, this is the hardest to do with Raster, and has the biggest impact in RT on-vs-off in places where there is a fair bit of reflections around, and is relatively cheap
2) Shadows - Probably the Cheapest RT Effect, However it's also the one that gives the least visual quality improvements as you can get really good shadows, even the notoriously difficult to work with Directional Shadows can be made good with TAA+Shadowmap Rotation+16k Shadowmap for Kilometers of real time shadows cheaper then RT Shadows would be, and should thus be fairly low on the priority list
3) Full - Most Expensive, But a Fully ray traced essentially. Something like https://github.com/EmbarkStudios/kajiya/blob/main/docs/gi-overview.md which does GI, Reflections and shadows

Honestly I'd do 1 when 4.0 is out, and skip 2 to 3 when the hardware gets to the point that this makes sense, in a few GPU generations when you can get 200-300€ GPUs that can do 1080p@60 with such RT enabled.
