### ISSUE TITLE
Refactor of GraphEdit/GraphNode

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot-proposals#5271]
### Describe the project you are working on

Godot Engine

### Describe the problem or limitation you are having in your project

Compared to other software the current graph editor is rather limited in usability and flexibility (e.g. no subgraphing, comment nodes don't work well)
In addition to that the underlying code is quite convoluted and hard to maintain, making it difficult to extend the visual editors to cope with the demands/expectations of such a system.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The visual editor system including the GraphNode and GraphEdit nodes as well as the editor specific classes should be refactored and cleaned up to build a foundation for easy extensions and usability improvements.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This refactor may include:
- Split GraphNode into `GraphNodeBase`, `GraphNode` and `GraphNodeComment`(or `GraphFrame`) (open for naming suggestions) due to:
	-   Maintainability: The GraphNode class got really large and complex, so splitting it up improves code navigation and readability (removes some `is_comment()`-branching/ cleans up theme constants)
	-   Flexibility: Allows adding more features to the frame/comment graph node or extend GraphNodeBase for a completely custom node without most of the predefined connection functionality (reference image backdrops, etc.)
	-   Performance/implementation complexity: For example, a comment node does not need to keep track of any connections/slots/ports
- Improve the comment node system
	- Draw connection lines above comment nodes, but below normal graph nodes (would be easier with proper layers, but for now there is godotengine/godot#61783)
	- Nested comment nodes are automatically sorted
	- Consider automatically resizing comment nodes (similar to Blender)
- Allow for customizable title bars to include custom controls (e.g. buttons/icons)
    - This can be useful if we want to add a button to minimize a node (hiding all its properties/slots, just show the ports) or to enter a subgraph node
- Extract the menu from GraphEdit and make it its own control (if we don't want to expose this we can just do that internally as a improvement to code structure[GraphEdit is huge with around 2500 lines]) or at least add a toggle to turn it off so users can add their own
- [might require some discussion] Introduce GraphNode layers (e.g. as a new node) with layer specific properties as a structural improvement. This would flesh out the concept of layers - which is already (kind of) present internally - and improve it in terms of WYSIWYG. For example, here you have a backdrop layer for reference images, above that a comment node layer which keeps the nodes sorted based on their bounding boxes, then the layer containing normal/functional graph nodes (+ the connection lines) and on top of that you could add a layer which shows a subgraph dynamically. There are still many things to figure out and there may be some alternatives to this approach, but this is just what I currently have in mind.
- Modify GraphEdit to properly support subgraphs (maybe the layer introduction above plus a new GraphNode type is enough together with some additional tweaks or there is a need of a more fundamental modification)

Here's an example how some of the concepts are implemented in Blender:
![grafik](https://user-images.githubusercontent.com/50084500/187026093-3b01483d-7371-47ca-91b6-242cb764fa9c.png)

I already opened a demo PR, which partially implements this proposal for interested people to try out: godotengine/godot#67152
This proposal should create a common ground for discussion to decide which of the above points could improve the current situation with GraphEdit/GraphNode, so we can provide a more flexible graph editor system to build upon (for shaders/animation trees/audio etc.).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

The visual graph editors are a core part of the engine.

**Comment by halgriffiths** [comment]
Sadly I read recently that this feature is being discontinued in 4.0: 
https://godotengine.org/article/godot-4-will-discontinue-visual-scripting

Visual scripting is now part of a separate repo, so you could re-target this PR there instead:
https://github.com/godotengine/godot-visual-script

**Comment by coppolaemilio** [comment]
> Sadly I read recently that this feature is being discontinued in 4.0: https://godotengine.org/article/godot-4-will-discontinue-visual-scripting
> 
> Visual scripting is now part of a separate repo, so you could re-target this PR there instead: https://github.com/godotengine/godot-visual-script

The graph editor and graph nodes are not going away, they are still a part of the engine

**Comment by Zireael07** [comment]
Speaking of customizability, I made three discussions/proposals relating to that, based on old suggestions for VS.

https://github.com/godotengine/godot-proposals/discussions/5249 highlight ports

https://github.com/godotengine/godot-proposals/discussions/5250 separate snap and grid

https://github.com/godotengine/godot-proposals/discussions/5252 make easier to customize

**Comment by YuriSizov** [comment]
I think we can separate this body of work into several steps and start with GraphNode refactoring. It makes sense to me just from the health of the codebase standpoint. Plus, done right, it can allow to incorporate this idea, for example: https://github.com/godotengine/godot-proposals/issues/2212#issuecomment-1222231077

And it can be done relatively quickly, if you want to break compat before beta. It's niche enough to risk it, and important enough to try and improve, IMO.

The layering and other improvements can be done later. Like the menu thing is definitely minor and can be done at any point, since exposing it as a class is not necessary, exposing it as hbox is enough, probably.

**Comment by Geometror** [comment]
Update on the technical site, I managed to come up with some solutions to some of the proposed changes:

- Generic titlebar (only implemented for GraphNode, not GraphNodeBase/GraphFrame)
	- The titlebar will consist of one titlebar container/control (default will be HBoxContainer)
		- This container can hold e.g. the title label, a icon or a functional button(close/minimize/settings)
	- Remove the close button ("show close" property) from GraphNode since it is rather specific and it's possible to add it manually to the titlebar container with a few lines of code (Unreal, Unity and Blender don't have a close button on their nodes, only one to minimize)
- Remove the overlay property as it was specific to visual script, which was removed 
	- Add an overlay StyleBox as a replacement, but more flexible
- GraphEdit layers through layer index
	- Add a layer index property to BaseGraphNode, GraphEdit will keep its children sorted by that index
	- For example: GraphFrame nodes will have a default layer index of 0, normal GraphNodes 2, the connection layer as a special case has layer index 1 so that it is kept between them

Now regarding class names:
For now I settled with BaseGraphNode, GraphNode and GraphFrame, but I kind of dislike BaseGraphFrame.
I'm thinking about the most fitting name for the base class - BaseGraphNode feels a bit off since it only provides the basic functionality to be used together with GraphEdit - no slots, no ports, no connections. Should we go with GraphItem/GraphEditItem/{some other name you may suggest} or leave it?
While we're at it, would it make sense to rename GraphEdit to GraphEditor?

**Comment by YuriSizov** [comment]
> While we're at it, would it make sense to rename GraphEdit to GraphEditor?

No, for better or worse this is how we call a bunch of nodes, LineEdit, TextEdit, CodeEdit. Renaming GraphEdit would make it an outlier.

**Comment by aXu-AP** [comment]
I'm not sure where I should comment on these recent changes, but this thread seems like the best place to discuss.
I have been testing around the recently updated GraphEdit and here's some thoughts:
Generally, changes that were made are reasonable and welcome, nice job! 😄 👍 
Porting existing code was easy (disclaimer, I started using GraphEdit only this week as I needed it for my addon).
But here's few ideas:

- `snap_distance` was renamed to `snapping_distance`. However, with the addition of disabling snapping without hiding the grid, I think `grid_size` would make more sense.
- Since resizing is supported out of the box (thank you!), signal `resize_request` doesn't sound right - since the action happens no matter what, it isn't a mere request. I'm not sure what it should be renamed though, since Control already offers `resized` signal.
- Resizing should snap to grid.
- I'm not sure why `delete_nodes_request` was changed to `close_nodes_request`, seems like unnecessary change and deleting describes better to what is happening here. I mean, it's triggered by pressing the delete key.

This doesn't directly relate to this refactor, but since we are introducing API breaking changes, it seems to be good time to bring this up: I think GraphEdit should support following features from the get go: **deleting nodes, connecting and disconnecting ports**. I feel that more godoty way would be to have overrideable functions for these, than just raising signals and leaving the implementation to the user.
Preventing bad connections can already be done in `_is_node_hover_valid()`, so usually you don't need to add extra checks upon connecting. Similiar approach could be made for deleting: `_can_delete_node(node : StringName) -> bool` or something.

**Comment by YuriSizov** [comment]
> * I'm not sure why `delete_nodes_request` was changed to `close_nodes_request`, seems like unnecessary change and deleting describes better to what is happening here. I mean, it's triggered by pressing the delete key.

It was changed for consistency, because previously both "close" and "delete" (and their variations) were used for related things. I simply unified everything under one term. There has been a discussion on Rocket.Chat about this and suggestions to rename everything to delete. I don't mind, as long as it stays self-consistent.

My reasoning for picking closing over deleting is because deleting the node is an implementation detail and to be decided by the developer. From the POV of the graph itself we are only requesting to hide it. Maybe calling it hiding would've been better, but that wasn't one of the options used, so I picked closing as the closest alternative.

**Comment by aXu-AP** [comment]
Indeed, in ui related things closing is the more used term, sounds reasonable. Altough, at the same time I am suggesting having default implementation for deleting nodes as it seems to be the most usual thing to do. There might be exceptions but in practise I haven't seen a graph editor which hides or moves away the nodes instead of deleting them. Of course, undo/redo system needs to catch the changes but that could be implemented in virtual callback functions / signal handlers.
