### ISSUE TITLE
Visual Scripting Needs To Be In Godot

### ISSUE THREAD

**Issue by bbacle** [godotengine/godot-proposals#5307]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Visual scripting needs to be totally rewritten & definitely needs to be in Godot. I am NOT a programmer so gdscript is not my forte. The visual scripting that has been in Godot needs to be totally redone so that it will better serve users with a way to make games without having to type code.
In Godot 4, I understand that you are deprecating visual scripting. I think this is a mistake, because you have only gotten feedback from those in your inner circle & not from the vast community of Godot users.
If you want to make Godot better, then redo visual scripting so that it will be on a par with Unreal's blueprints or Unity's Bolt.
Don't just throw it out, as you have now done.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See previous post

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See previous post

### If this enhancement will not be used often, can it be worked around with a few lines of script?

See previous post

### Is there a reason why this should be core and not an add-on in the asset library?

See previous post

**Comment by Calinou** [comment]
Please do not create proposal issues if you don't have a concrete technical implementation for a feature. Besides, work is already being done on https://github.com/godotengine/godot-visual-script. As described in the [news post](https://godotengine.org/article/godot-4-will-discontinue-visual-scripting), the goal is to have visual scripting as an extension in future versions. This extension could be officially supported if it receives enough maintenance (but note that most core contributors already have their hands full – so additional help is needed here).

**Comment by bbacle** [comment]
Since you do not think that my issue did not contain a concrete solution, I was only voicing what many other users have said about this issue. And since I am not that familiar with github, I believed that this was the appropriate place to voice my concerns with Godot & the direction that it is taking.
You could have left off the first part of your reply & just told me that this was already being worked on. Your rudeness is showing, & I don't appreciate it.

**Comment by YuriSizov** [comment]
@bbacle I'm sorry that we offended you, but we have strict rules for submitting proposals. They need to be actionable. If you want to voice general concerns, you can open a proposal discussion instead of a proposal issue. See [Discussions](https://github.com/godotengine/godot-proposals/discussions).

I would also like to reiterate that the visual scripting system was removed not because we don't believe it, but because our attempt was a failure. We want to have VS, but we don't want to keep a very bad and barely supported tool as an official solution. We're looking forward to more interest and more contributions unbounded by our old design. Many users voiced their satisfaction with the removal specifically because it allows alternative solutions to rise.

**Comment by bbacle** [comment]
Thank you for the response. Since I am not familiar with github, I did not know about a discussion section. And I understand why the visual scripting was removed, as you stated, in order to allow alternative solutions. I do hope that the new visual scripting extension will be useful, since programming is not my forte.
