### ISSUE TITLE
Add a Angle type instead of using floats

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot-proposals#5397]
### Describe the project you are working on

Top-down game with aiming.

### Describe the problem or limitation you are having in your project

Angles are floats (own code and engine). But a float is alot more then an angle and has different behaviours and methods.
Methods may exspect angles in different ranges (-PI to +PI), (0 to TAU) or any value.
Internal all angles are stored in radians, but users/developers input is in degrees and must be converted.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Opaque type for angles.
- Explicit conversion from float (`Angle.from_radians(...), Angle.from_degrees(...), Angle.from_circle_percent(...)`)
- Explicit conversion to float (`angle.as_radians(), angle.as_degrees()`)
- Friendly as exported property (custom inspector)
- Limited Operators defined

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

All methods and members which represent angles should be converted to angles.
Custom Syntax for angles

```gdscript
func _process(delta: float) -> void:
    Rotation += delta * 15°

    var x := 10° + 15°
    var y := 10° * 15° # error
    var z := 10° + 0.3rad + PI + TAU

    var w := Rotation.sin()
    Rotation := asin(w)

    Rotation := 1.3 # error
```

### Problems

- Not sure how many conversions may be nessecary for existing code
- Keeping the backing data correct (normalized) may decrease performance

### Other

- The backing data type could be anything, but float is probatly the only viable
   - uint may be normalized with overflow, but trigonometric function are not supported

**Comment by Calinou** [comment]
Adding new Variant types should only be done when it's absolutely needed, as every new Variant type has a performance cost (even if you never use it in a project).

**Comment by antonWetzel** [comment]
> Adding new Variant types should only be done when it's absolutely needed, as every new Variant type has a performance cost (even if you never use it in a project).

Where does the cost come from? I can only think about the Variant-Type switch, but it should be compiled to a jump table.

**Comment by Mickeon** [comment]
I don't know about adding a whole new Variant type that stores a single float, since that already... exists, as TYPE_FLOAT.

**Comment by YuriSizov** [comment]
"Angle" doesn't imply any unit of measure, so that doesn't improve much in terms of clarity. Depending on your background and the work you do, you could still expect radians or at the very least be unsure which one of the two is expected by the engine. So I'm not convinced this is an improvement beyond what is already available with `deg2rad` and `rad2deg`.

The new syntax looks fun, and may be nice to have... but my keyboard layout doesn't have a dedicated degree key, so I would not be able to use it. And I'm sure this is true for many other mainstream layouts.

**Comment by antonWetzel** [comment]
@Mickeon 

> I don't know about adding a whole new Variant type that stores a single float, since that already... exists, as TYPE_FLOAT.

`Vector4`, `Quaternion` and `Color` exists, which all are just 4 floats

> Admittedly, the custom syntax is a cool idea, and has potential for making the code prettier and easier to understand. Only problem is that not every keyboard has °, not that it would be a very common (and mandatory) usage.

Maybe allow `15deg` and `0.3rad`

**Comment by antonWetzel** [comment]
@YuriSizov

> "Angle" doesn't imply any unit of measure, so that doesn't improve much in terms of clarity. Depending on your background and the work you do, you could still expect radians or at the very least be unsure which one of the two is expected by the engine. So I'm not convinced this is an improvement beyond what is already available with deg2rad and rad2deg.

The angle type would be opaque, all conversion to and from float would be named (to string and editor inspector would probatly use degrees) and the user can think in whatever unit they want.

> The new syntax looks fun, and may be nice to have... but my keyboard layout doesn't have a dedicated degree key, so I would not be able to use it. And I'm sure this is true for many other mainstream layouts.

Maybe allow `15deg` and `0.3rad`

**Comment by Mickeon** [comment]
But allowing `deg` and `rad` in a numerical context as if they were symbols... it's just too complicated, it doesn't add anything to the float value defining the angle, either, which for the engine is actually always expressed in **radians**, unless otherwise noted. Besides:
```GDScript
# I don't see how:
15deg
# is any better than:
rad_to_deg(15)
# Or, if something has to be proposed for visual sugar:
deg(15)
```

I do reiterate, that the **°** symbol is cool. Really cool. Albeit very, very rare in programming. To be fair, however, I can't access **~** and that too is an operator.
Perhaps **°** would implicitly multiply the number next to it by roughly _0.0174_? (this is how **degrees** to **radians** conversion is done).

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
