### ISSUE TITLE
include json module from docs

### ISSUE THREAD

**Issue by GoDino** [godotengine/godot-proposals#547]
**Describe the project you are working on:**
game machine with selection menu for selecting and playing multiple games

**Describe the problem or limitation you are having in your project:**
configurations such as versions are .json docs, those are not visible/editable in the editor

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
there is already a module in the docs that works well for us:
http://docs.godotengine.org/en/latest/development/cpp/custom_resource_format_loaders.html

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
json files are visible in the editor filesystem and can be viewed/modified in the inspector

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no

**Is there a reason why this should be core and not an add-on in the asset library?:**
for us it is a great enhancement and we believe it would be for others, too

**Comment by linkpy** [comment]
It is possible to make an add-on to show `*.json` files from the filesystem dock. 

Maybe making them editable in the editor could be useful too, but you have other ways to do that by making your data into classes extending `Resource`, which allows you to save your instances directly to `.tres`/`.res` files, which are editable from the inspector and shown in the filesystem dock. As for 3.2, this feature is kind of clunky to use but works pretty well.

**Comment by GoDino** [comment]
We looked into these possibilities, however writing out data to .res or .tres was not an option as the that format would be godot-only, and it would need another conversion step to get config data from godot and into godot. While this would be trivial to implement, it is a unnecessary extra step that could possibly introduce errors, so using .json straight seems more to the point. That way godot can interact more directly with external applications.

Like I said the resource format loader already exists and works (see documentation link), and that lets you do anything with json files as a resource. As godot already contains a json reader it seems indicated to have it as a resource as well. Makes scripting with json a lot easier too if it can be accessed as a resource.

**Comment by linkpy** [comment]
I think the issue will come from the ability to consider generic markup languages as ressources. In the link you sent, it is indeed a resource loader, but it doesn't load a resource (as in, the result isn't something that extends `Resource`). And making an in-engine "resource" loader for JSON would mean that it could be done for other (XML, YAML, INI, etc) which will bloat the engine on my opinion.

What i'm trying to say is that JSON is too generic to be considered as a `Resource`, just like XML or other MLs. If what you want is just being able to do `load("file.json")` you can still make a new resource class `JsonResource` which would load a JSON file at runtime throught a function : `var data = load("json_res.tres").json()`

Finally, to view them in the filesystem, a simple add-on can do the trick. Editing them is another issue tho. The simplest way i can think of is in pair with the add-on : when the user want to edit a json, just lunch an external editor. To edit them within Godot's editor, you need to edit the current implementation of the code editor to support the format, and make the syntax highlighter.

**Comment by GoDino** [comment]
I do not think the intent is to support multiple markup languages. Json is already supported in the engine and the docs include code for a loader. In godot, it is then used as a dictionary, so its content can be viewed in the Inspector and, if deemed necessary, edited and saved. Why edit a json file is another discussion, in my view it has not much use, but viewing it does have a use. And since a dictionary can be edited and saved, this comes as a "bonus". Removing the ResourceFormatSaver will make it read-only.

Editing json files themself in the text editor not at all intended or subject of this proposal. 

All I am saying is, since the code is in the docs already, maybe include it in the core as a convenience. I do not mind if it remains a custom module either. It is just an extra step compiling the engine with the custom module.

**Comment by linkpy** [comment]
The documentation shows an example of resource loader. It's just to show the process of implementing a `ResourceFormatReader` in the engine itself. This can be done with a simple addon by using [add_export_plugin](https://docs.godotengine.org/en/latest/classes/class_editorplugin.html#class-editorplugin-method-add-export-plugin) and [add_import_plugin](https://docs.godotengine.org/en/latest/classes/class_editorplugin.html#class-editorplugin-method-add-import-plugin). 

It still boils down to the same thing : a `ResourceFormatReader` should returns a `Resource` object, otherwise it doesn't make much sense. A JSON file isn't a resource : it's just data that needs futher processing to have meaning, as a `Resource` is meaningful on its own and once loaded, no more processing need to be done on it, like a texture or a packed scene.

> Is there a reason why this should be core and not an add-on in the asset library?:
for us it is a great enhancement and we believe it would be for others, too

Seeing the files in the filesystem dock can be done throught an addon, easily. Loading/saving a dictionary by using Godot's resource system can be implemented througth an addon. Editing a JSON file is the same. 

I dont think specific markup langages (any of them) should be considered as a resource, because they are just ways to format and structurate data, and always need something else to be interpreted by the game. Compared to all other resources, they are all directly understood by the engine itself as they are specific enough and always has specific usage. A texture will always be used in the same way, just like a tileset or audio file. A JSON file can be used in thousand of way.

But I'll do agree on something : Godot needs a way to define/format/structurate custom data from the editor/engine itself. In some cases, using a spreadsheet can be really useful and way faster than going to each scene and edit exported values manually. Same goes with a tree data structure, which can be done by using custom nodes in the scenetree, but this is very ineffective. Maybe adding general purpose resource formats is useful, with importers that converts ML into these resources (like converting a CSV file to `ResourceTable`) that can then be directly used and edited from the engine. This would allow way more flexibility, such as using Godot's type in them (PoolArrays, Resources, etc) than just using JSON or XML.

**Comment by GoDino** [comment]
yeah think you are right, thanks
