### ISSUE TITLE
Add an `utc` parameter to `Time.*_from_unix_time()` methods

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#5515]
### Describe the project you are working on

A game

### Describe the problem or limitation you are having in your project

![](https://user-images.githubusercontent.com/47700418/193082131-077bb9a8-d985-4751-ad9e-2f5d4a622afe.png)

Only the `Time.*_from_system` methods have the `utc = false` parameter, which means that by default they return the date/time in the local time zone. When I use a `Time.*_from_unix_time` method (for example, if I use a timestamp from a savefile), I get the date/time in UTC. I think in most cases the desired result is local time.

```gdscript
@tool
extends EditorScript

func _run() -> void:
    print(Time.get_date_string_from_system())
    print(Time.get_time_string_from_system())
	
    var t := int(Time.get_unix_time_from_system())
    print(Time.get_date_string_from_unix_time(t))
    print(Time.get_time_string_from_unix_time(t))
```

```
2022-09-29
19:13:27
2022-09-29
16:13:27
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the `utc = false` parameter to the rest of the methods for which this makes sense.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to add the timezone offset before the method call, but I don't think this is a good solution.

### Is there a reason why this should be core and not an add-on in the asset library?

This is the main use case for these methods in user code.

**Comment by dalexeev** [comment]
The title sounds like a bug report, which is almost true. This is a bug in API design.

**Comment by dalexeev** [comment]
Related:

* godotengine/godot#66695

**Comment by TokisanGames** [comment]
Yes, all functions that convert unix time to human readable formats should have a utc/local option. Alternatively, please give us functions to convert between local and utc. 

I'm having difficulty with this now. I'm fetching the last modified date of a file. When printing the result with `get_datetime_string_from_unix_time(FileAccess.get_modified_time(file_name))` it shows me UTC. Why would I want that? Looking at it in windows explorer it shows local time. Now I can't compare accuracy. The use cases for UTC are far fewer than local time.

This should be a bug report. Half of the Time functions are unusable for most cases without an easy way to convert between utc/local. Since I don't have a solution, I'm going to have to append UTC and the user will just have to look at it.

**Comment by dalexeev** [comment]
@aaronfranke Can you take a look please.

**Comment by aaronfranke** [comment]
With the from system methods, the heavy lifting is done by the OS.

For all of the other methods, the current logic is that all operations are done in "the same timezone". So if you give the Unix timestamp in local time, you get the String/Dictionary in local time. As such, what this is really asking for is a flag to do a conversion. So I would recommend this be false by default. Also keep in mind that when converting back into a Unix timestamp the conversion would be backwards (or, if not converted, you get the local time Unix timestamp).

Right now if you want to convert things to local time you can use `get_time_zone_from_system` to get the bias offset in minutes, then do `+= bias * 60` or `-= bias * 60`. Thankfully this means we can avoid [this](https://www.youtube.com/watch?v=-5wpm-gesOY) and it would be easy to implement this in the Time methods, we just need to decide what's the right API.

**Comment by aaronfranke** [comment]
The other catch is that using `get_time_zone_from_system` to determine what the offset should be will still not account for if the time is in a different timezone. Like if it's currently winter and you want to convert a timestamp from the summer. However it works if you're trying to convert the current time. So this is one argument in favor of not adding timezone adjustment into Time's conversion methods, it would make more sense for the user to adjust the timezone as needed with whatever level of complexity they need.

**Comment by dalexeev** [comment]
I solved the problem for myself:

```gdscript
static func get_local_datetime(unix_time: int) -> String:
    var bias: int = Time.get_time_zone_from_system().bias
    var t := unix_time + bias * 60
    return Time.get_datetime_string_from_unix_time(t, true)
```

But I still think that the `utc` parameter is needed, even if it does not take into account daylight saving time and historical facts. We can just mention these limitations in the docs, but free users from having to implement their own method.

**Comment by YuriSizov** [comment]
Seems to me that only one method is missing a utc flag, `get_unix_time_from_system()`. Though if by default it already does UTC, this will be a bit confusing now, since to preserve compat we would need to set it up with utc = true.

The rest of the methods that take a Unix timestamp work with an already fixed timestamp in whatever timezone and I agree that getting into conversion business is not worth it for us.

**Comment by joshmg** [comment]
There are already some valid workarounds here, but will just offer this one as well:

```
var utcTimestamp: int = ...
var localDateTime: Dictionary = Time.get_datetime_dict_from_system(false)
var offset: int = Time.get_unix_time_from_datetime_dict(localDateTime) - Time.get_unix_time_from_system()
var dateTime: Dictionary = Time.get_datetime_dict_from_unix_time(utcTimestamp + offset)
```

**Comment by aaronfranke** [comment]
I will close this issue, restating that this feature is too complex to implement and is out-of-scope. However, feel free to continue commenting with any solutions and workarounds, or if you implement a GDExtension and want to share it.

The Time class is intentionally simple, it explicitly does not deal with timezone conversions [because those are a massive pain](https://www.youtube.com/watch?v=-5wpm-gesOY). Implementing this would require Godot to bring in an entire timezone library, which will likely be massive, and is unnecessary for most games. If you need support for timezone conversions, you should use a time library via GDExtension.

**Comment by dalexeev** [comment]
That's ok, but we should properly document the reason, probably along with the above workaround and a note that it doesn't always work correctly.
