### ISSUE TITLE
Write metadata file with path to Godot executable

### ISSUE THREAD

**Issue by van800** [godotengine/godot-proposals#555]
**Describe the project you are working on:**
I am working on JetBrains IDE integration
https://github.com/JetBrains/godot-support
I think also https://github.com/exigow/intellij-gdscript would benefit from this proposal.
And all other external editors may use it.

**Describe the problem or limitation you are having in your project:**
I need to know Godot executable location on IDE side.
For now I use this metadata file inside the user project directory:
https://github.com/godotengine/godot/blob/5771f9959c5fe0d0a236f334a6211cbe20c8b293/modules/mono/editor/GodotTools/GodotTools/Ides/GodotIdeServer.cs#L52
But I need more solid approach, which show work also in Regular Godot version.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
On startup Godot Editor should write metadata file similar to described above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Every user would need to copy-paste path to executable in some setting on IDE side.

**Comment by van800** [comment]
@neikeq What do you think?
For sure I can make a PR with such tiny change, but I am asking first to avoid doing unneeded work.

**Comment by neikeq** [comment]
However, regular Godot version projects are not supposed to contain editor data (with C# we can get away with this because of the `.mono/` folder). 
The alternative is to put this in the project's editor settings directory, but it's more tricky to find:

- Windows: `%APPDATA%\Godot\projects\{PROJECT_NAME}_{MD5_OF_PROJECT_PATH}\`
- macOS: `$XDG_DATA_HOME/Godot/projects/{PROJECT_NAME}_{MD5_OF_PROJECT_PATH}/` or `$HOME/Library/Application Support/Godot/projects/{PROJECT_NAME}_{MD5_OF_PROJECT_PATH}/`
- Linux: `$XDG_DATA_HOME/godot/projects/{PROJECT_NAME}_{MD5_OF_PROJECT_PATH}/` or `$HOME/.local/share/godot/projects/{PROJECT_NAME}_{MD5_OF_PROJECT_PATH}/`

More problematic if the editor is self-contained (as is with the Steam version), as it's a sub-directory of the Godot executable itself.

cc @akien-mga who may know more about this.
