### ISSUE TITLE
In `Edit Animation Libraires` window rename `Add Library` to `Create New Library`

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#5565]
### Describe the project you are working on

CHecking godot 4 animation libraries.

### Describe the problem or limitation you are having in your project

If in AnimationPlayer click on Animation and Manage Animations at the top of the the window for animation libraries there are two buttons: `Add Library` and `Load Library`.
Labels are similar which creates confusion for anyone using the system (not just me, there are already youtube videos with people also mentioning this in their tutorials), if you press the Add Library button you get a pop up window which says `Global library will be created.` since it clearly creates a new library I believe it would be benificial to change the button's label to reflect that a bit better.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Renaming `Add Library` -> `Create New Library` defuses a situation when someone wants to add an existing library and clicks on `Add Library` button which creates a new library but does not add an already exiting one.
The second button `Load Library` serves for the purpose of adding existing libraries instead so the naming is a bit confusing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Renaming the Label for `Add Library` button.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's editor's core.

### Is there a reason why this should be core and not an add-on in the asset library?

It's editor's core.

**Comment by Illauriel** [comment]
Sounds reasonable, but maybe instead of writing Create we could use the same + icon like on the New Project button. On that note, Load Library button may benefit in readability from adding a folder icon to it.

**Comment by RobProductions** [comment]
@Illauriel any chance you could submit a PR with that update? It looks really clean that way!

This current wording actually tripped me up just yesterday even when I had read this proposal before if you can believe it lol. For some reason I thought that Add Library meant it would create a new library resource based on animations from the window itself rather than a local library managed by the anim player. Perhaps a further clarity improvement might be to let the "New Library" button sit in the list itself like underneath the existing libraries? But I can definitely see some downsides to that too so maybe your approach is best for now, and the rest might just be up to clarity in the tutorial resources on Godot's doc site.

**Comment by Illauriel** [comment]
> @Illauriel any chance you could submit a PR with that update? It looks really clean that way!

Thanks! Sure I can. The only problem I see with renaming the button is that I'm unsure if it will break localized versions. I might need to ask someone more knowledgeable in editor-fu first.

**Comment by RobProductions** [comment]
> The only problem I see with renaming the button is that I'm unsure if it will break localized versions.

From what I understand it will since it likely uses `TTR()`, however from what I've seen elsewhere in other PRs I think it's alright to push usability changes like that and let it break for now. After all, you can only [localize via Weblate](https://docs.godotengine.org/en/stable/contributing/documentation/editor_and_docs_localization.html) so you wouldn't be able to update the localization strings in the same commit. 

Hopefully before 4.3 (or whichever stable version it ends up in) is officially released the translation can be updated by other contributors :) though take all that with a grain of salt because I'm still relatively new to contributing haha, please feel free to correct if I'm mistaken!

**Comment by Illauriel** [comment]
Aaaand done
- godotengine/godot/pull/86736

> From what I understand it will since it likely uses `TTR()`, however from what I've seen elsewhere in other PRs I think it's alright to push usability changes like that and let it break for now. After all, you can only [localize via Weblate](https://docs.godotengine.org/en/stable/contributing/documentation/editor_and_docs_localization.html) so you wouldn't be able to update the localization strings in the same commit.

I asked in contributor chat and it's exactly as you say.

> I'm still relatively new to contributing haha

Lol, same^^
