### ISSUE TITLE
Could we replace Godot numerics types (vectors, planes, etc.) with System.Numerics from .NET?

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot-proposals#5580]
### Describe the project you are working on

C# project

### Describe the problem or limitation you are having in your project

There is ambiguity between [System.Numerics](https://learn.microsoft.com/en-us/dotnet/api/system.numerics?view=net-6.0) types and Godot types. Sometimes resulting in compiler error when you are not specifying namespace explicitly. Types like:
* Vector2, Vector3, Vector4 (but not integer variants)
* Quaternion,   
* Plane.

Also there's no explicit nor implicit conversion available between Godot and System.Numerics types. (You can't use System.Numerics.Vector2 as an replacement of Godot.Vector2 in methods or vice versa). Current way to convert is like so:
```c#
Godot.Vector2 godotVector = new(3, 4);
System.Numerics.Vector2 dotnetVector = new()
{
    X = godotVector.x,
    Y = godotVector.y
};
```

Could we simplify Godot C# implementation by reusing already existing .NET structs?

Also, Transform3D (and 2D) struct could be represented as an class that uses System.Numerics.Matrix4x4 (3x2) under the hood to store and manipulate data.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use of [System.Numerics](https://learn.microsoft.com/en-us/dotnet/api/system.numerics?view=net-6.0) 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We can either:
1. Add `public static implicit operator Vector2(System.Numerics.Vector2 from)` and `public static implicit operator System.Numerics.Vector2(Vector2 from)` to each struct Godot has.
2. Use System.Numerics types from get-go. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is used often and is difficult to replace with few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

It requires changes to the core.

**Comment by raulsntos** [comment]
We have no control over the `System.Numerics` types and we need the types to follow the same layout in memory as the one used by the C++ in order to marshal them which is how these types can go from C# to C++ and back. If we can't ensure the same layout is used, we'd need a conversion step every time we use any of the engine's APIs which would make them more costly to use.

Our vector types also use `real_t` so they match the precision used by the C++ vectors in the engine, this means if you build the engine with 64-bit precision your vectors will use `double`, otherwise they'll use `float`. The vectors in `System.Numerics` use `float` and therefore if you were to use an engine built with 64-bit precision you wouldn't be able to use them.

I'm not opposed to providing conversions between Godot types and `System.Numerics` types though, but it won't bring any benefits other than being able to use them seamlessly with third-party libraries that use `System.Numerics`.

**Comment by Mickeon** [comment]
> but it won't bring any benefits other than being able to use them seamlessly with third-party libraries that use `System.Numerics`.

That by itself sounds pretty huge to me, but I can't exactly say in what way, because my experience with C# in Godot is minimal.
