### ISSUE TITLE
Ask user on new project creation to create `.git/` folder and add first `Initial` commit

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot-proposals#5659]
### Describe the project you are working on

_not relevant_

### Describe the problem or limitation you are having in your project

_not relevant_

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

![image](https://user-images.githubusercontent.com/45442278/198048400-d8de5679-393e-4ef7-ba5e-217573b152ea.png)

- Add checkbox with option to create `.git/` folder
- Add checkbox with option to commit created project immediatelly, with text input of first commit name (default "Initial").

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

_see description above_

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Used on new project creation.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it could be part of the core.

**Comment by tvardero** [comment]
> I think this is better done by https://github.com/godotengine/godot-git-plugin (if not implemented already). You should only initialize the Git repository when you actually plan to use it.

This plugin is not required in cases if VSC is managed not inside of Godot editor. For example, "Source controll" tab in VS Code, GitHub Desktop, etc..

Having new project already commited is only a small QoL feature.

**Comment by Zireael07** [comment]
@tvardero: Not every Godot user uses Git at all though, why should Godot care about Git if it's not managing it tbh?

**Comment by TheDuriel** [comment]
If a user is an avid git user, they will be familiar with initializing a repo, and they will have preferences on how to do it. Like setting up their ignores, attributes, and subdirectories **before** initializing the Godot project.

If they aren't, then this isn't relevant to them.

I don't really see a case where this is going to be useful to someone who takes VCS serious.

Sidenote: Nor is the existing VCS integration tbh. (Which is a feature born out of popular request by people that did not end up using it, because other options are better, or they didn't actually care enough.) God I wish we had some usage statistics on engine features other than the poll. <.<
