### ISSUE TITLE
Add 'default scene path' to Project Settings

### ISSUE THREAD

**Issue by Dorifor** [godotengine/godot-proposals#576]
**Describe the project you are working on:**
1 bit course from HeartBeast
**Describe the problem or limitation you are having in your project:**
I created folders to organize my project (Scripts, Scenes, etc...) but when I create a new scene while I'm in the root folder or any other folder than Scenes, then it creates it outside of my custom folder.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A "Default Scene Creation Path" and a "Default Script Creation Path" option in the project settings would be awesome.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A new menu / option in the Project Settings where we can select default pathes for files we create (Scripts / Scenes / etc...)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it'd benefit a lot of people.

**Comment by KoBeWi** [comment]
You can right-click a directory in file system and select "New Scene". The scene will be created in that directory (after you save it).

**Comment by Calinou** [comment]
> I created folders to organize my project (Scripts, Scenes, etc...) but when I create a new scene while I'm in the root folder or any other folder than Scenes, then it creates it outside of my custom folder.

It's recommended to group resources by purpose or "component" rather than by type. See [Project organization](https://docs.godotengine.org/en/latest/getting_started/workflow/project_setup/project_organization.html) in the documentation for more information.

**Comment by Delpire** [comment]
As someone working with C#/Mono in Godot, it seems like this would be a nice addition, especially with respect to namespaces. In Visual Studio, when you create a new cs file in a folder, you automatically get a namespace that matches that name. Currently this is a pain though since Godot doesn't generate cs files with namespaces for some reason, I believe this issue has been talked in a Godot blog though.

I understand that you want people to follow your style guidelines, and while maybe that should be the default behavior, I don't think people should be forced into following a particular guideline. To me it makes sense to have my scripts together so that they appear together in Visual Studio. I don't want to have to dig through tons of folders. Generally I have Godot open with the scenes folder open so I can easily access the scene I want, and then all my scripting is done in Visual Studio. The two lists are separate, and therefore half as long, easier to find what I am looking for.

I guess an argument could be made that if your going to organize your code by a particular namespace, you would want to organize your scenes in that same way, but I don't know if that will universally be true.

Godot will never be a replacement for Visual Studio, VSCode, Blender, Aesprite, etc. Developers are often going to be using many programs together. Some people might want their scenes, scripts, and assets together, others might find other workflows more productive.

**Comment by Calinou** [comment]
Closing due to lack of support. If you really need to save your scenes/scripts in a specific folder, you can always use the approach described in [this comment](https://github.com/godotengine/godot-proposals/issues/576#issuecomment-597973940).

**Comment by Benpaste** [comment]
I appreciate this is archived, but I run into this problem a lot. What is the recommended course of action for somebody who has a lot of different scripts they don't necessarily want to dump in the main scene folder?
![image](https://github.com/godotengine/godot-proposals/assets/74246868/05222bef-ecf7-46f8-bd61-fb5333b724ca)
Take this example. All the children of BattleStateMachine need their own script, but I don't want to have to change the script directory to my "states" subfolder every time I create a new child.
What's expected of the user here? Should I just be using the method outlined in the comment @Calinou linked?

**Comment by Calinou** [comment]
To me, persisting the last folder you chose in the save dialog is the way to go, so you don't need to reconfigure it every time. This should be tracked in its own proposal.
