### ISSUE TITLE
Godot Engine API for Dart and Flutter using "dart:ffi"

### ISSUE THREAD

**Issue by iapicca** [godotengine/godot-proposals#58]
[As propsed to Dart](https://github.com/dart-lang/sdk/issues/38303)
[Dart 2.5](https://medium.com/dartlang/announcing-dart-2-5-super-charged-development-328822024970) is introducing "Foreign Function Interface" (dart:ffi) that allows Dart-C interop.
Quoting the article in the link above: 
"Dart enters the IEEE Spectrum programming language ratings as 16. It’s also 10 under trending, and 6 when filtering to languages for mobile (behind Java, C, C++, C#, and Swift).";
Flutter allows to build, with a single code base, mobile app for Android and iOS, PWA and soon desktop app for Windows, Linux and OSX.
Such an API would undoubtedly  widen Godot adoption.

[edit] filling in [template](https://github.com/godotengine/godot-proposals): 

_Describe the project you are working on:_ 
I'm a Flutter developer and I'm working on a 2D game using flare
taking [this ](https://play.google.com/store/apps/details?id=dev.flutter.devRpg) as example

_Describe how this feature / enhancement will help your project:_
this feature would allow my creativity to express to a whole new level enabling the possibility of 3d rendering

_Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:_
it a technical proposal that doesn't impact a single feature, but the whole game complexity,
on the technical side what I picture is:
Flutter App => plugin (Godot Engine + Dart:ffi interface) => Flutter Widget Tree => Godot rendering inside a widget

_Describe implementation detail for your proposal (in code), if possible:_
please see the original post above

_If this enhancement will not be used often, can it be worked around with a few lines of script?:_
no, when available this enhancement will be used often and isn't possible for my knowledge to shrink it in few lines

_Is there a reason why this should be core and not an add-on in the asset library?:_
yes, it's a fully fledged feature, not an add-on

**Comment by clayjohn** [comment]
Please update your post filling out the template properly or it will be closed in accordance with Rule 1. Rules can be found on the README on the main page of the repo https://github.com/godotengine/godot-proposals

**Comment by iapicca** [comment]
> Please update your post filling out the template properly or it will be closed in accordance with Rule 1. Rules can be found on the README on the main page of the repo https://github.com/godotengine/godot-proposals

I've update the original post, sorry I didn't read carefully the guidelines.

**Comment by groud** [comment]
This was already proposed, and I still don't see any reason to implement that. The only argument I can find here is that it may bring some Flutter users to Godot, but we don't really care that much.

> Flutter allows to build, with a single code base, mobile app for Android and iOS, PWA and soon desktop app for Windows, Linux and OSX.

Godot is already a multiplatform solution.

> Describe how this feature / enhancement will help your project:
this feature would allow my creativity to express to a whole new level enabling the possibility of 3d rendering

That quite a vague use case... I don't see why your creativity would be limited with Godot, and Godot is already capable of 3D rendering.

**Comment by LikeLakers2** [comment]
Hi, I read through your edit. I get the impression that you've not tried Godot before, not even on its own.

You seem to want to use Godot inside of a Flutter app, for 3D rendering from what I can gather? In that case, I want to point out that Godot is a maturing game engine all its own, and if you were to use Godot, there's a good chance you could achieve nearly the same results without the needed complexity of having to manage Flutter *and* Dart *and* Flare *and* Godot (not to mention any workarounds you'd be using to make everything work together).

That said, if you need Godot as just a renderer, and are intent on using Flutter for this, then you would still need to create bindings to Dart (as I suggested in this issue's counterpart on the `dart-lang/sdk` repo) so that you can control Godot's VisualServer or scene tree; alternatively, you would need to rip out Godot's renderer code and use that (under the MIT license that Godot has, of course).

If you need help with those sorts of things (creating bindings, or figuring out how Godot's renderer works so you can rip it out or create an equivalent in Dart, or anything Godot really), don't be afraid to ask for help on the [community channels](https://godotengine.org/community). But unfortunately, I don't think this is the sort of thing we could make happen for you.

**Comment by iapicca** [comment]
> This was already proposed, and I still don't see any reason to implement that. The only argument I can find here is that it may bring some Flutter users to Godot, but we don't really care that much.
> 
that's an honest answer, I respect that
too bad, I really feel that this could have been an opportunity for both

**Comment by girng** [comment]
Interesting, but why use Flare when you're already using Godot?

**Comment by iapicca** [comment]
> Interesting, but why use Flare when you're already using Godot?

flare is 2D there are no 3D engines for Dart that I'm aware of

**Comment by LikeLakers2** [comment]
@iapicca I think you misunderstood girng's question. Why are you using Flare, when Godot already provides its own facilities for game logic, rendering, and UI components?

**Comment by Sslaxx** [comment]
Would GDNative/NativeScript bindings for Dart be possible, or desirable?

**Comment by ElfEars** [comment]
Imo: This is very much a "maybe in a few years if" case. (My estimate is about 5 or 6)

I don't want to speak for OP but I assume this is mostly for future compatibility with Google's Fuchsia project (A possible future replacement for android). Fuchsia only accepts flutter executables, ergo all applications must use it. 

Opinions follow:
(I assume that dart is introducing C support because most people either use it or something that can be compiled to it, not dart itself. Gonna be honest in all my time as a developer I have only ever heard of it when researching the Fuchsia project. Several articles detail it's semi obscure history and are good reads for those interested.)

**Comment by iapicca** [comment]
@LikeLakers2 

the point is not to replace godot, 
if you want to go "full godot" you have no reason to use dart,
but...

Flutter gives an extremely good experience
in creating app for Android and iOS with a single code,
web and desktop (coming soon),
**what flutter doesn't have is a 3D engine**
(2D rendering is actually one of the selling point
of flutter, especially compared to React).

Imho the possibility to use Godot 's 3D engine in Flutter
would bring a lot of popularity to Godot itself
and since community is the flesh and blood of any
open source project I can only see this as a win win

**Comment by vnen** [comment]
I think the you are going the wrong way in this, honestly. You are saying "I'm using Flutter/Dart and want to bring in Godot 3D rendering". That is a task for Flutter, not for Godot. You can already do apps for Android, iOS, and desktop with Godot itself, bringing in Flutter is not a benefit in this regard.

For a proposal here, you should say "Bringing Flutter will make Godot better because it'll enable me to do X in my project, which wouldn't be possible without it". If you don't phrase it that way, it'll be hard for other people to see any benefit in this proposal.

**Comment by iapicca** [comment]
> I think the you are going the wrong way in this, honestly. You are saying "I'm using Flutter/Dart and want to bring in Godot 3D rendering". That is a task for Flutter, not for Godot. You can already do apps for Android, iOS, and desktop with Godot itself, bringing in Flutter is not a benefit in this regard.
> 
> For a proposal here, you should say "Bringing Flutter will make Godot better because it'll enable me to do X in my project, which wouldn't be possible without it". If you don't phrase it that way, it'll be hard for other people to see any benefit in this proposal.

it is possible, but I believe in open source
https://pub.dev/packages/flutter_unity_widget
also current solutions are based on "calling" the native code
which is greatly inefficient and now can be done differently
using dart:ffi

**Comment by aloisdeniel** [comment]
While using Flutter doesn't make sense to me for the same reasons already exposed, I would love using Dart as a script language. 

Simply because I use Dart on a day to day basis, and it is always simpler when you can keep your environment and tools (just like C# support).

**Comment by vnen** [comment]
Well, it's not feasible for Godot to support every possible programming language out there. We support a few officially (GDScript, C#, C/C++) and provide an interface for the community to add support for other languages (Rust, Nim, and Python are some examples available). If there's something missing in the interface that don't allow Dart to be done, we will highly consider adding that, but official support won't happen.

**Comment by mahdisml** [comment]
i started working on it :
https://github.com/mahdisml/DartGodot
