### ISSUE TITLE
Make C# signal connections straightforward like GDScript 2.0 is

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-proposals#5835]
### Describe the project you are working on

Kart Racing Game

### Describe the problem or limitation you are having in your project

Currently in order to connect to a signal you must do:

```csharp
        kart.Connect(nameof(SignalName),new Callable(this, nameof(functionName)));
```

which is cumbersome

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The solution is make it looks like gdscript2.0 which is quite simple:

`signal_name.connect(function_name)`
or
`signal_name.connect( func(): do_stuff_here.... )`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the solution is:

```csharp
 SignalName.Connect(FunctionName);
```
and lambda support

```
SignalName.Connect(  ()=>{GD.Print("This is awesome")} );
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

this requires changes on core

**Comment by KoBeWi** [comment]
Didn't C# support events? Something like `signal += method`.

**Comment by nonunknown** [comment]
LOL when creating this proposal I really forgot about this one! should I remove this proposal, or it makes sense to make connect that way, or at least then the COnnect function should be removed from C# then! because if its goin to remain then it should be improved!

**Comment by KoBeWi** [comment]
I don't think it can be removed easily. The API is auto-generated AFAIK.

**Comment by raulsntos** [comment]
I don't think it's a good idea to remove `Connect` because some users may still find it useful as a last resort when they are working with dynamic untyped code (same use case as `Get`, `Set`, ...). Also, internally we use it to connect the C# events, see the generated event for Node's ready:

```csharp
public event Action Ready
{
    add => Connect(SignalName.Ready, Callable.From(value));
    remove => Disconnect(SignalName.Ready, Callable.From(value));
}
```

> Also keep in mind that using event requires to manually disconnect it, or bugs can happen

Not if they are Godot signals, the events generated by our source generators are just wrappers around the `Connect` and `Disconnect` methods and we automatically disconnect signals when the object is disposed (see https://github.com/godotengine/godot/blob/f6f8a48459f9bbe97ee76a7186b9ae37e71e724b/modules/mono/csharp_script.cpp#L1743-L1745).

**Comment by nonunknown** [comment]
oh awesome, didnt know that! also I would like to know from you @raulsntos if this proposal makes sense or not!

**Comment by nonunknown** [comment]
ohh awesome, so my proposal became useless at all, because didnt know about `Callable.From()` which already make syntax sugary xD, thanks for the info!
