### ISSUE TITLE
Develop a high level API to use. (Godot is too low level and dificult to code)

### ISSUE THREAD

**Issue by ca3gamedev** [godotengine/godot-proposals#5894]
### Describe the project you are working on

a 3D jrpg.

### Describe the problem or limitation you are having in your project

I spend 2 days trying to code a basic 3D rigidbody npc that walks randomly in a single direction like a 2D jrpg character that can be hit by a ball and pushed around.
And I totally failed.

And I don't want to spend 5 years getting a CS degree to be able to read godot source code and documentation to be able to know how to do this.
Already spend 19 years learning to do art.

I'm too old and mentally exausted to attempt to get a CS degree to do this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make an easy to use event API like rpg maker where I can easily code my game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just an even higher API, maybe a secondary API on top of gdscript where I can easily simply call a single line of code and I get complex behaviour done.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is a core issue.

### Is there a reason why this should be core and not an add-on in the asset library?

No, this is a core issue.

**Comment by RedMser** [comment]
You might be looking for something like VisualScript? It's an alternative to GDScript where you program by using a visual node editor.

> No, this is a core issue.

This could definitely be done as an add-on, and I really feel like it should be as well.
This would be a too large maintenance burden. Also evidenced by VisualScript being taken out of Godot's core for 4.0.

**Comment by atirut-w** [comment]
> I spend 2 days trying to code a basic 3D rigidbody npc that walks randomly in a single direction like a 2D jrpg character that can be hit by a ball and pushed around.

I think that's more of a user problem. You can make something like that in less than an hour if you know what node to extend from and know how to read the *online* docs.

> And I don't want to spend 5 years getting a CS degree to be able to read godot source code and documentation to be able to know how to do this.
I got used to coding in GDScript in probably a few days of messing around with Godot.

**Comment by Mickeon** [comment]
> Godot is too low level and dificult to code

I do not agree with the main sentiment of this discussion at all.

Godot has always been described as a **high-level** engine. In fact, many of Godot's Objects are just accessible versions of internal objects present in one of the many servers. **Physics Node**s, **Node2D**, **AudioStreamPlayer**s, **Texture**s... These **Node**s/**Resource**s do all of the difficult work for you by communicating with their respective servers (such as **PhysicsServer2D**). You may even access these servers manually, for actual low-level, advanced purposes.

In my experience coming from basic object-oriented programming lessons, **Unity** and **Clickteam Fusion 2.5**, Godot Engine has been by far the most comfortable I've been using an engine. This is mainly because all of my knowledge in programming is simplified _(the engine does the hard work for me)_, while still letting me have the freedom to program something suitable for my needs, if I put thinking into it _(like some low-level languages out there)_.

By no means, this is not to say that Godot is super-simple. No one should say that. Simplicity is subjective, and there's a lot of things to learn if one wants to. But, I feel what you are looking for is some assistance, some instructions. If you do not believe Godot fits your needs because it is difficult to use, see if another engine does.

**Comment by KoBeWi** [comment]
> Make an easy to use event API like rpg maker where I can easily code my game.

RPG Maker is designed to create jRPG games and it has events specific for that use-case. Godot is general-purpose engine, so you'd need events for every type of game there is. This is just not feasible, hence it's better for an addon territory.
btw if you are looking for a 3D jRPG framework, you might be interested in RPG in a Box. It's free on Epic Store right now.

Closing, the proposal is out of scope of the engine.
