### ISSUE TITLE
Implement `AnimationPlayerBase` class to make the blending process shared between `AnimationPlayer` and `AnimationTree`

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#5972]
### Describe the project you are working on

Stabilization of Godot animation feature

### Describe the problem or limitation you are having in your project

Godot's AnimationPlayer blending is out dated and remains old duplicated

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Fixes:
- https://github.com/godotengine/godot/issues/70207

Supersedes:
- https://github.com/godotengine/godot-proposals/issues/5952
- https://github.com/godotengine/godot/pull/70241

Most of the bugs in AnimationTree have recently been removed, but the AnimationPlayer blending is still having old AnimationTree code, making it difficult to keep them in sync.

AnimationPlayer blending currently has the following bugs:
- Breaking AnimationPlayer playback process due to possibility of blending the same cache
- Incorrect blend weights when blending more than 3 animations
- Inconsistent blend results

After discussion with @reduz in reference to the [poll](https://twitter.com/reduzio/status/1605158737852870657), we agreed to make a compromise by implementing the AnimationPlayerBase. But please understand that until then, fixing bugs in AnimationPlayer's blending will have a much lower priority.

If possible, we would like to eliminate the extra AnimationPlayer from the scene by having the AnimationTree get the animation list from the AnimationBase instead of getting it from the AnimationPlayer, as mentioned in comment https://github.com/godotengine/godot/issues/28311#issuecomment-1175568055, but that is a future plan.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implement AnimationPlayerBase as the base class. It is implemented based on the new AnimationTree blending process. Then, AnimationPlayer and AnimationTree are reimplemented by extending AnimationPlayerBase.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Never

### Is there a reason why this should be core and not an add-on in the asset library?

Animation system is core

**Comment by jitspoe** [comment]
Just to clarify, what you're proposing is:
AnimationPlayerBase: This handles just the animations, no blending.
AnimationPlayer: Inherits AnimationPlayerBase and adds blending.  Effectively acting the way it does now.
AnimationTree: Uses animations from AnimationPlayerBase to avoid blend conflicts and handles its own blending internally.

If so, my first question is:
What's placed in the scene when importing a model with animation?  Is AnimationPlayerBase used directly, or does it use AnimationPlayer?  Would we need to manually add an AnimationPlayer to the scene?

Second question:
If the problem is keeping the blending logic in sync because there are 2 different classes to maintain, does this even address that issue?  Seems it just adds another class to maintain.

Finally:
Have you tested with PR https://github.com/godotengine/godot/pull/37001 ?  That fixes a bug with a blend time of 0, so maybe we can always use a blend time of 0 with AnimationTree and save a lot of work not implementing new classes?

**Comment by TokageItLab** [comment]
AnimationBase is implemented to cache each track, process their blends, and apply the blended values to each object. Currently, AnimationPlayer has duplicated code that is out of sync with AnimationTree for blending, so the main purpose is to get rid of it.

AnimationPlayer and AnimationTree calculate the weights and pass them to AnimationBase. Perhaps the playback process will have separate AnimationPlayer and AnimationTree, I don't know yet.

I can't guarantee that #37001 will work well with this AnimationBase implementation, but they are not in conflict. At least the current AnimationPlayer is incorrectly weighted for more than 3 animation blends, so if #37001 fixes that it is fine, but if AnimationBase does not work with #37001 then we will have to fix it again.

**Comment by TokageItLab** [comment]
I consider it impossible to keep the old blending logic. This is because the blending results depend on an iterative order which the user has no control over. For example, the old blending logic produced different blend results for AB * 0.5 + C * 0.5 and C * 0.5 + AB * 0.5, it's so wired.

Also, the new blending process correctly handles weights above 1.0 and negative weights, so it can correctly handle AddBlend, etc., whereas the old blending process does not. And I don't know if it makes sense to add features such as Xfade-AddBlend to AnimationPlayer.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/80813.
