### ISSUE TITLE
Add strict and safe equality operator `===` for comparing references and variants

### ISSUE THREAD

**Issue by vonagam** [godotengine/godot-proposals#6092]
### Describe the project you are working on

A library.

### Describe the problem or limitation you are having in your project

Arrays and Dictionaries are reference types unlike other core types. If you have two arrays with same content modifications to one might or might not be reflected on another, it depends on whenever they point to the same underlying vector of data or different. This fundamental distinction from value types is not reflected in behavior of equality operator.

A simple example of such drawback can be guards in setters:
```gdscript
var array: Array:
  get:
    return array
  set(value):
    if value == array: return # is it the same array or not?
    array = value
    handle_update()
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In Godot 3 dictionaries were compared by reference, while arrays by value. Godot 4 wanted to make things consistent (which is commendable) but instead of comparing both of them by reference it started to compare them by value. Which, in my opinion, is a shame.

Since the ship has sailed in opposite direction but we still do not have a way to compare references I propose that we add new operator for strict and safe compassion - `===`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
+------- left operand 
|  +---- operator     
|  |  +- right operand
v  v  v              
a === b
```

**Strict**: returns true only if both operands are of the same type (no implicit conversions) and of the same reference or value depending on their type. This will close #874.

**Safe**: simply returns false if operands are of different type. This will allow to compare arbitrary values without troubles. This will close #4571.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Will be used quite often. I guarantee.

### Is there a reason why this should be core and not an add-on in the asset library?

A basic fundamental feature.

**Comment by Calinou** [comment]
I would add a new method for this, rather than a `===` operator. `===` will remind people of PHP/JavaScript's weak typing – not necessarily in a good way :slightly_smiling_face:

**Comment by vonagam** [comment]
Yes, the situation does remind me of js, unfortunately.

But `===` is as short as you can get, does not require reserving any global names, familiar for many and because of that more intuitive than a function.

**Comment by aaronfranke** [comment]
Using a method would be familiar for C# developers, since C# has `Object.ReferenceEquals` https://learn.microsoft.com/en-us/dotnet/api/system.object.referenceequals?view=net-7.0

**Comment by adamscott** [comment]
I'm ok on my part for `===`. Better that than calling some global function, in my mind.

**Comment by vonagam** [comment]
It can be put to a vote or something, where people propose their names or operators.
```gdscript
a === b
# vs
reference_equals(a, b)
```
Personally I would prefer an operator more than a function (it should have been `==` and contents compassion as a function...) But a function is better than nothing too.

**Comment by anvilfolk** [comment]
I guess we've also left out the option of the compatibility breaking change of making default `==` be compare by reference, and then having another method, possibly `dict.equals(other_dict)` or something like that in a builtin type that does deep comparison.

It's a pretty big compat breaking change, but I wonder if that wouldn't put things more inline with how other programming languages handle equality - as long as you interpret arrays/dicts being reference types as them being pointers.

**Comment by dalexeev** [comment]
In #4571, I suggested making `==` more restrictive, but it was received negatively, many people think that comparisons like `1 == 1.0` or `"abc" == &"abc"` are useful. So I agree that `===` can be a good solution to these problems, even though it looks like JavaScript/PHP. We can explain all the nuances of comparisons (including `match`) in the documentation/tutorials. I think it's better than leaving things as they are now.

**Comment by RandomShaper** [comment]
1. I agree with those not fond of the `===` idea, since it already has a widespread meaning in other relevant languages, plus I think it's bad for readability.
2. As far as real-world usage has told, compare by value is what meets the less astonishing principle best, as well as what in most cases one wants.
3. I can still see the point in the ability to tell if two arrays or dictionares are the same (i.e., backed by the same memory so mirroring each other). Since the OP says to be working on a library, I'm starting to think that the needs there may diverge from those of a standard project.
4. I opened a PR to expose to scripting what I believe to be the simplest to remember and read way to compare by reference: `Array.id()` and `Dictionary.id()`, but I eventually closed it since we couldn't find any real use case: https://github.com/godotengine/godot/pull/54804. Maybe we could get more details on what this library is trying to achieve to assess the decision to resurrect the PR or suggesting a different approach. to the script writer

**Comment by vonagam** [comment]
> not fond of the === idea, since it already has a widespread meaning in other relevant languages

And that meaning matches the behavior proposed here, is there another? (I know of js, php and swift)

> I'm starting to think that the needs there may diverge from those of a standard project

Which relevant language **does not** have a way to check reference/identity/physical equality?

**Comment by RandomShaper** [comment]
As far as I know, `===` are a type strict comparison in those languages, not related to the uniqueness of the data.

In any case, it still would be helpful to know your thoughts about point 4.

**Comment by vonagam** [comment]
> not related to the uniqueness of the data

In js they compare all reference types by reference (which is consistent), so for them it is only about lack of conversions. 

For [php](https://www.php.net/manual/en/language.oop5.object-comparison.php) and [swift](https://developer.apple.com/documentation/swift/===(_:_:)) it is exactly about references equality because their `==` is for value compassions only (consistent). 

It raises the question then, if the move to compare arrays by value was done in consistency name, why objects are still compared by reference?

> thoughts about point 4

It will be slower. If the variable is a variant then there will have to be runtime resolution of the method. Theoretically such variant can hold class with `id` method, so will produce unexpected results. Variants are not advisable, but there are some weakness in type system so sometimes you have to use it. And in any case (even if it is a hard dictionary/array) there still will be a usual call and then return of the value and then another compassion, so it will not match specialized operator speed.

It is harder to implement. You had trouble exposing `id` because it is a pointer. So it is not trivial and might lead to bugs (if somebody saves the id and then later other instance gets the same one).

It is unsafe. Only dictionary/array will have it, so it will not solve ability to safely compare arbitrary values.

**Comment by RandomShaper** [comment]
Let's 

What concerns the most is me is the benefit-risk ratio of adding something of such big consequences as a new operator if yours is the only known use case.

So, while I acknowledge there's a feature gap, to avoid making things unnecessarily complicated for most users (and maintainers), I'd still want to explore approaches like maybe a top-level GDScript function like `is_same(a, b)` that works like you expect, is simple to implement and fast at runtime, doesn't hsve and is clearly meant to be used in those exceptional cases (and so it avoids the headaches of deciding which comparison operator is suited for each case). Otherwise, people would no longer be sure about what's the primary way of comparing variables and a mix of `==` and `===` would arise in projects, code samples, tutorials, etc.

P. S.: I guess objects, arrays and dictionaries are compared they way the are because that's the most useful scheme. Arrays and dictionaries didn't have a good reason for being compared differently.

**Comment by RandomShaper** [comment]
Sorry. My phone did weird scrolling for no reason and I closed without intending to hit that button. I've finished editing my reply above, which was sent before complete.

**Comment by adamscott** [comment]
I would be ok with a short top-level GDScript function like `is_same(a, b)`. It isn't `===` as it is strongly opposed by some, and it does what it says on the tin.

**Comment by vonagam** [comment]
> if yours is the only known use case

There are three reference types - arrays, dictionaries, objects. Before one of them was compared by value (initially it was compared by reference). Instead of making it behave like others, a breaking change was made (without proposal*) to make dictionaries be compared by value too.

(* - and during this time there was a proposal #874 to make `==` compare all reference types by references. It did not gather any negative feedback.)

All the way through you can see comments from people that say that they want a way to compare array/dictionaries by references somehow. After that how can I still be "the only known use case"?

**Comment by adamscott** [comment]
@vonagam I don't think the use case is the issue, here. @RandomShaper acknowledges the feature gap.

**Comment by vonagam** [comment]
This is about importance of that gap. In the message - I'm "the only known use case" and new solution "to be used in those exceptional cases".

For me it is clear that ability to check if you have the same value or not is a basic need as it gets. It is not exceptional.

And while function will be better than nothing, it will be a second class citizen compared to equality operator by design.

**Comment by adamscott** [comment]
I was reading [the wiki article about relational operators](https://en.wikipedia.org/wiki/Relational_operator) when I stumbled to this idea.

Why not imitate in Python and use the `is` operator to do the job? `a is b`

Like, if the identifier is not a constant, but a variable, treat `is` as the hypothetical `is_same(a, b)` or `ReferenceEquals`?

**Comment by vonagam** [comment]
Will not work. You still may want to compare to constant. Even metatypes.

**Comment by adamscott** [comment]
| Possible operator names |
| -- |
| `sameof` |
| `equals` |

**Comment by vonagam** [comment]
Well obvious one is `eq` actually, but it clearly should have been used for value compassion and not reference one:
```gdscript
a eq b
```

**Comment by RandomShaper** [comment]
The name of the operator would ideally not be a synonym of 'equals' because that could cause confusion, as in '`equals` is to `==` like `and` is to `&&`.

`is` looks fine to me.

**Comment by vonagam** [comment]
`is` is a type check already. Cannot be used.

**Comment by adamscott** [comment]
We could rename the current `is` to `instanceof`.

**Comment by RandomShaper** [comment]
> `is` is a type check already. Cannot be used.
Oh, right.

`is_same` then. And I'd still advise that it's a top-level function for the aforementioned reasons, despite it no longer being `===` reduces the risks to some extent, but I wouldn't oppose to it being an operator if there's enough consensus.

**Comment by vonagam** [comment]
As I said before, I think it makes sense to put it to a vote on which symbol/name to use.

**Comment by adamscott** [comment]
Let's vote here:

| `===` operator | `is_same` operator | `is_same(a, b)` | 
| ------ | --- | --- | 
| :+1: | :laughing: | :tada: |

**Comment by dalexeev** [comment]
Let's not repeat my mistake of combining different things in one proposal (#4571) and divide this proposal into 2 parts:

1. strict comparison, which does not produce errors, but returns `false` if the types are different;
2. value equality vs reference equality for reference types (`Array`, `Dictionary`, `Object`).

**Comment by adamscott** [comment]
What would be the behavior for types like `String` and `int`?

Does `"Godot" === "Godot"` equals `true` or `false`? Because it should be distinct references.

If the answer is `false`, I will remove my vote for `===`.

**Comment by RandomShaper** [comment]
I think a poll here will be biased. It's obvious that people favoring the introduction of `===` is around.

**Comment by vonagam** [comment]
Hah, when I said "decided by a poll" I didn't mean by a poll of emojis deep in comments of new proposal.

Though it is a small bonus validation for myself that I am not alone in thinking that `===` would be the best (or just more popular) option out of those given. (When I did put a thumb up there were some votes for other options, but none for `===`.)

Is there any way, @RandomShaper, to prove to you that the issue is important one and not some fringe use case?

**Comment by RandomShaper** [comment]
I already agreed the issue exists. I'm just trying to be cautious in assessing how it should be addressed, pointing out some of the many downsides I see to the specific solution of adding a whole new operator.

**Comment by vnen** [comment]
I personally don't like the addition of a new operator, in particular because the `===` has already some wonky meaning in other languages (for instance, in JS you pretty much never want the regular `==` because it has so many issues). The solution that worked for other languages is not necessarily applicable to GDScript. Note that adding `===` implies also adding `!==`.

The fact that the regular equality gives an error with incompatible types is actually a feature because it's very likely you're making a mistake if you're comparing different types, with the exception being similar types (e.g. number or string types) and have a debug break makes you are of the problem. I fear that introducing the `===` operator will make users behave like in JS (the most well known usage of this operator) and prefer using it over anything else and start facing some odd bugs. Those will probably argue then to change the meaning of `===`.

Of course, this is all speculation, but the reasons to add the new operators is also speculation.

I believe we still need the feature, as @RandomShaper said, it just doesn't need to be an operator (at least not yet). We need a way to compare values by reference and possibly also a shorthand for `typeof(x) == typeof(y) and x == y` for type-strict comparisons. IMO for now we can add a top-level function to do reference comparison, and decide later for a type-strict shorthand. At a later point this still may be promoted to an operator if it makes sense after we see how the function is being used.

Lastly, while voting can give us an idea on how people feel about the implementation, it's rarely the best option to use if we want a consistent language design (which I do). People voting will be biased by the languages they prefer and might not realize the implications of adding a new operator. It might not even behave like they expect in practice, even if they read the description. So I prefer we focus on the language design aspect first and try to reach a consensus. Voting should be the last resort.

I propose using `is_equal_ref(a, b)` as the name of the new function, being similar to the already existent `is_equal_approx(a, b)` utility function.

**Comment by vonagam** [comment]
It does sound like it what we will end up with.

To address the comment anyway:

> `===` has already some wonky meaning in other languages

There is no wonky meaning of `===` in other languages (for js, php and swift it is consistent). There is a wonky meaning of `==` in js, as you said, yes.

> making a mistake if you're comparing different types

What other languages error on comparison with their analog of Variant? (Not rhetorical question.) I don't mean when you compare variables typed as `int` and `Vector2` or two untyped variables. I mean this:
```gdscript
var x: Variant = ...
var y: Variant = ...
print(x == y)
```

> reasons to add the new operators is also speculation.

Why do almost all relevant languages support reference comparison as a first class operator, mostly as `==` or `===`, even if they have an operator or a function for value comparison? 

For example, C# mentioned here, compares references by references. `ReferenceEquals` (and `Equals`) are just to bypass overloads if you encounter them.

> Voting should be the last resort.

The problem is when you argue against arguments of "most users" and "usefulness". Polling user-base give some way to prove or disprove such statements.

I'm not saying that such polls should be binding. And it should be done in a way to minimize audience selection biases.

For example, argument against `===` is that it has bad reputation. How do you prove that?

**Comment by dalexeev** [comment]
> The fact that the regular equality gives an error with incompatible types is actually a feature because it's very likely you're making a mistake if you're comparing different types

I partly agree with this, in some cases it really is an indicator of user mistake. But IMO this is too strict behavior, a warning would be enough (in the editor, if it is known in advance that the values will never be equal, and at runtime in debug builds). Arguments:

1. Now it is not obvious to the user which types can be compared and which cannot. In some cases, this is allowed (comparisons with `null`) and may even give true (`1 == 1.0`), in others it causes an error (and only at runtime, as far as I remember).
2. This is required when you are working with `Variant` and values of different types is intended case (for example, when reading JSON data, `ConfigFile`). #737 indirectly confirms that people need a convenient way to compare values of different types.
3. The `===` operator is already indirectly present in the language, in the `match` construct. It is more type strict and does not cause an error when different types are compared. I can easily imagine a case where the user, for some reason, replaces `match` with `if` - `elif` - `else` and surprised by an error or incorrect behavior of the script.

**Comment by Av3r3tt** [comment]
In case this hasn't been pointed out yet: one of the strengths of GDscript is its eminent _readability_ of code. It is too easy for beginners and intermediate users to overlook, misread or misunderstand "==" vs "===". And since the use of true identity (pointer equality) is rather rare, it would be a safer bet to consciously put the distinction a true step away (i.e. either give it an operator that really looks different, or give it a self-explanatory name).
So I second _any_ other operator than "===" _precisely_ because it is similar to "==".

**Comment by touilleMan** [comment]
Since I've been summoned (and I'm the author of the PR that implemented the change in the `==` operator :smile: )

In Python the `==` operator has a behavior very similar to what is currently implemented in Godot: scalar (e.g. int, str) and container (e.g. list, dict tuple) are compared by value where user's class instances are compared by reference.
This is simply because equality can have multiple meanings for user class while it's obvious what it should be for scalar and container.

I'm against the `===` operator for the reason @vnen mentioned (since Javascript, everybody consider `===` to be the "non broken ==" so you can be sure there will be confusion and bad use if we introduce something like that in Godot)

> For example, argument against === is that it has bad reputation. How do you prove that?

- JS linter [considers using === instead of == a good practice](https://eslint.org/docs/latest/rules/eqeqeq)
- in PHP == does "type juggling", prior to PHP8 it leads to such craziness (e.g. `"10" == "1e1"` returns true) [that documentation warns about it](https://www.php.net/manual/en/language.operators.comparison.php)

On top of that, @dalexeev is right here: https://github.com/godotengine/godot-proposals/issues/6092#issuecomment-1382828041, there is two different topics here:
1) should comparison on different types be always considered an error ?
2) should there be a way to do reference comparison ?

Regarding 1), I'd say it's the static type-checking job to display this kind of codesmell (which give the benefit of giving a way for the user to silence this by using an any typing), so runtime shouldn't complain about this.
However this is not the point of this issue 😄 

Regarding 2), it is only a performance need (at least I've failed to see any other usecase so far).
However it seems weird to me to consider we want such performance with GDScript:
- per value comparison is efficient on most case (for instance is comparing to itself or to the wrong type, or to containres with different size)
- providing an `.id()` method for containers is a simple way to provide reference comparison if that's really needed. Of course this means the user code should do `typeof(a) == typeof(b) && a.id() == b.id()`. It's cumbersome to type and less efficient than a dedicated keyword. But it's also far simpler to implement and good enough.

Finally if performances are really needed, GDExtension is the way to go. So it seems very strange to me to introduce a keyword to do reference comparison for performance reason given a keyword is only usable from GDScript 🤔 
So if anything, it should be global method.

@vonagam Do you have some more example where reference comparison would have a benefit ? (ideally real-life example)
your [setter/getter example on the initial post](https://github.com/godotengine/godot-proposals/issues/6092#issue-1533016406) is not really convincing to me:
- using the setter with it own value is unlikely (the caller that have taken the value knows that it haven't modified it)
- using the setter with the copy of it own value is more likely. In this case should `handle_update` be called or not ? (I would guess no, but reference equal will trigger the comparison...) 
- what happen if the value is modified ? the setter is not called but the `handle_update` should be called in one way or another ?
So in the end this is the kind of code the caller must have a much better understanding of what is going on that the callee. So either the caller can be made responsible of calling `handle_update`, either a better interface to the callee is needed (typically passing the array to the `handle_update` method, or having setter/getter on the array items).

**Comment by vonagam** [comment]
I think there is a strong consensus about how this should be handled. I will close the proposal during the week since there is already original one for chosen solution. But to replay:

> In Python the `==` operator has a behavior 

In Python there is first class short operator `is` for reference comparison. Why do they have it for comparison that does not have use cases or benefit?

**Comment by touilleMan** [comment]
> In Python there is first class short operator is for reference comparison. Why do they have it for comparison that does not have use cases or benefit?

In Python everything is an object on the heap (variable all contains pointers). Hence implementing `is` was extremely simple (the C code of CPython just have to compare the value of the variables to do pointer comparison). So my guess is it was just too tempting not to provide it ^^

But may have been a curse: `is` operator is one of the most common source of error from beginners: for instance `a is b` returns True if `a = 256; b = 256` but False if `a = 257; b = 257`, and `257 is 257` still returns True.

Python have operator overloading. Hence `is` is a way to ensure no overloading is involved:
- when using an object as default value instead of `None` (useful in a function where passing `None` is a valid value)
- when comparing against an arbitrary object that may be [`unittest.mock.ANY`](https://docs.python.org/3/library/unittest.mock.html#any)

The funny thing is Python also have a `id()` global function that returns the pointer value of a variable, so `a is b` is equivalent to `id(a) == id(b)` [^1]

I think those few points help underline the differences between Godot/GDScript and Python:

GDScript is a language specialized in a narrow usecase.
GDScript don't have operator overloading.
Godot's Variant are passed by value, hence reference comparison has no sens on the variant types that don't internally contains a pointer (i.e. not Array/Dictionary/Object).
 

[^1] I'm omitting a little detail here: `id(a)` is guaranteed to return a number uniquely identifying `a` *as long as `a` still exists*, so in theory `id("foo") == id("bar")` can be True if "foo" get garbage collected right after id() is called and it memory location is reused to create "bar".

**Comment by vonagam** [comment]
Ok, seems like people are averted by `===` and there is no desire for an operator in general. Looks like `is_equal_ref` is the accepted solution. And there is old open proposal for a way to do reference equality comparison. No need to keep this open.

**Comment by akien-mga** [comment]
Implemented in https://github.com/godotengine/godot/pull/71758 via the `is_same(a, b)` method.
