### ISSUE TITLE
Add a function that returns a random point in the NavigationMesh

### ISSUE THREAD

**Issue by ismailgamedev** [godotengine/godot-proposals#6181]
### Describe the project you are working on

3D City Building Game

### Describe the problem or limitation you are having in your project

There is no function in NavigationMesh that gives a random point, which wastes time, and even if I do it myself, it will not be what I want.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a function that returns a random point in the NavigationMesh Unreal has this by default, it is a very useful function :D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When you call this function, it returns a position in the area baked by the NavigationRegion according to the radius we give around the origin.

```nav_agent.get_random_point_in_navigable_radius(origin : Vector3, radius : float) - return random location```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it's very difficult to do, but it's a very important and time-saving feature.

### Is there a reason why this should be core and not an add-on in the asset library?

It's simple and it's a function that should be default in NavigationAgent so it should be in the core.

**Comment by Calinou** [comment]
Out of curiosity, why do you need a random point in the NavigationMesh? What purpose does it serve (e.g. for implementing a gameplay feature)?

**Comment by ismailgamedev** [comment]
the easiest and shortest way to make the character walk randomly.

**Comment by smix8** [comment]
> I don't think it's very difficult to do, but it's a very important and time-saving feature.

I will more or less quote the ReCast Navigation dev (which Unreal Engine uses for navigation) on this:

> It is very non-trivial (and slow) to clip a navigation mesh to an input circle for fetching a random point from the navigation mesh triangle soup.

I will borrow a graphic that someone posted at ReCast Navigation to visualize what the common problem is with circles or spheres and why we prefer to not use them at all for such operations in navigation mesh context.


![navmesh_circle_issue](https://user-images.githubusercontent.com/52464204/215056192-a32015ad-0077-420d-a40d-a3b22ffe0085.jpg)

Depending on your navmesh layout even Unreal Engine only gives you a position that is "around" somewhere close to your circle because it only checks if the polygon is inside the circle not the position. If you would check if the actual position is inside the circle you could theoretically run the search forever.

We can add this "somewhere around" circle function same as Unreal Engine but it will also be polygon based so not be a 100% inside circle function.

That said we can also add random point queries for navigation maps and regions. Those can run very quick if you want just a random position in a region compared to a circle search.

Later after the planned NavigationServer internals rework we can add more accurate point queries constrained to predefined convex polygon shapes. Those can at least run semi-performant compared to the uncontrollable performance abomination of an actual "accurate" circle search.

**Comment by ismailgamedev** [comment]
Will this function be added and when.

**Comment by Calinou** [comment]
> Will this function be added and when.

As smix8 mentioned, it's not quite clear-cut. There needs to be community support and consensus before a proposal can be implemented.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/75098.

**Comment by MJBrune** [comment]
@akien-mga Perhaps I'm missing something but it seems like #75098 adds a function on the Navigation Server to get a random point on a specific navregion or navmap. It doesn't add a function to get a random point (potentially across navmap/navregion) within a radius.

**Comment by WesleySweazey** [comment]
It would be cool if there were min and max radius range arguments for the NavigationServer3D.map_get_random_point function!

**Comment by Calinou** [comment]
@WesleySweazey Please open a separate proposal for this, as this proposal is now closed.

**Comment by AleMarcati** [comment]
@WesleySweazey did you create a proposal for this feature request? If so, can you post a link to it? I would like to show support.

**Comment by WesleySweazey** [comment]
Hey @AleMarcati I did not sorry!
