### ISSUE TITLE
Add Vector4 to the engine

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#629]
**Describe the project you are working on:**

Many projects can benefit from this feature, this is mostly for discussion.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

A Vector4 class would be similar to Vector2 and Vector3, but with four components: X, Y, Z, and W.

Potential use cases for a Vector4 class that I can think of:

* Parameters for noise functions, simplex etc: https://github.com/godotengine/godot/issues/1268 and https://github.com/godotengine/godot/pull/21569

* For use with shaders: https://github.com/godotengine/godot/issues/9134, https://github.com/godotengine/godot/issues/2855#issuecomment-406846872, https://github.com/godotengine/godot/issues/28504, https://github.com/godotengine/godot-proposals/issues/258

* Representing an Axis-Angle 3D rotation (not the same as Quaternions, simpler, less capable, Godot's rotate function already does this with a Vector3 and a float)

* Represeting 3D vectors in Direction-Magnitude format (direction is normalized).

* Simply for allowing the user to store 4 values together with a built-in struct.

There's likely many more uses for Vector4 than I'm thinking of. I'm not desperate for it, but I would find a Vector4 class useful. What matters is what Godot users would need it to do. It would be engine bloat implementing Vector4 "just because". So I'm opening this discussion to ask around about if users would find Vector4 useful and what kind of things they would use it for.

If you can think of a use case for Vector4 that you'd use, feel free to post it here.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Yes-ish. I have a C# implementation [here](https://github.com/aaronfranke/GodotExtraMath/blob/master/ExtraMath/Vector4.cs). It's not really feasible to make within GDScript, but the real solution there would be to allow custom structs in GDScript: #279

**Is there a reason why this should be core and not an add-on in the asset library?:**

Having Vector4 in core would allow engine functions to use it as a built-in type whenever it's necessary to work with four numbers. An analysis of how many engine functions could benefit from this would be a good idea first. Again, this proposal is mostly for discussion.

It might indeed be a better idea for this to be an add-on, but [this isn't possible in GDScript](https://github.com/godotengine/godot-proposals/issues/279).

**Comment by fire** [comment]
Currently Godot Engine uses plane or color for vec4.

**Comment by aaronfranke** [comment]
When it comes to shoehorning existing types for usage as a Vector4, here's a quick overview:

* `Color`: This type is not ideal because it uses `float` rather than `real_t`, which would mean it has less precision than vector types when `real_t` is `double`. `Color` also generally expects its values to be on a range of 0 to 1, but it can go above 1.

* `Plane`: This type expects its `x`, `y`, and `z` values to form a normalized vector.

* `Quat`: This type expects its values to be on a range of -1 to 1, and form a valid rotation.

* `Rect2`: This type has no restrictions on its position, but expects the size to be non-negative. This might be the most annoying to use since it's built out of two `Vector2` values, but it also has the least restrictions on what kind of values produce a "valid" `Rect2`.

A `Vector4` type would have no expectations, and all numbers would make up valid `Vector4`s.

**Comment by bojidar-bg** [comment]
> `Rect2`: […] but expects the size to be non-negative.

I do not remember this being the case, especially since issues like [godotengine/godot#23711](https://github.com/godotengine/godot/issues/23711#issuecomment-439017673) are reproduced when using rect2 with negative size.

**Comment by seocwen** [comment]
As someone who's not a good programmer, I don't understand what's expected of me when I'm trying to get a Vector4 into a shader. If I'm supposed to use Plane, or Color, of Quat, or whatever, that's really something that needs to be documented. How do I know nothing's going to break when I'm passing one of these between the CPU and GPU using a value outside their normal range - say, due to normalization, or filtering? And how easy and intuitive can you explain to a shader newbie how and why these other types are to be used as a Vector4? Likewise, when someone goes looking for this information, finding it should be straightforward.

I'm not sure it makes life easier for those looking for standard functionality like this to be expected to look for something other than "Vector4" - seems like they're going to end up having to ask someone for help figuring out the expected workaround.

On the other hand, in shaders themselves, vectors and colors are the same datatype, which makes a lot of sense. If Color had the same functionality as a Vec4 (maybe with x, y, z, and w property aliases) and you explained up front it was for the sake of interoperability between the CPU and GPU, I think you could justify that to anyone who's learning about shaders anyway. Of course, some reassurance in the documentation that Color and Vec4 really will have the same value after being passed and operate the same way on either side would be helpful. There's a lot that's not obvious about shader programming and no one want's to "experiment" with what works right now and end up with inscrutable bugs later.

**Comment by lyuma** [comment]
I would argue against adding another type for a few reasons.
Yes, `Color`, `Rect2` and `Quat` all have drawbacks because of their intended usecases and what they enforce.

However, `Plane` already exists and is a reasonable choice as a standard `Vector4` type. It does not check for being unit length. As evidence of this, all `vec4` types currently declared in shaders (other than `:hint_color`) are already passed as Plane without any problem in both Godot 3 and Godot 4.

Furthermore, `Plane` already has `x`, `y` and `z`. Only `d` needs to be renamed to `w`, so it would be very easy to migrate code using `Plane`. `Plane`-specific operations can be kept on `Vector4` but prefixed with `plane_`

Therefore, rather than add yet another type, I would propose that either the status quo be kept, or `Plane` be renamed to `Vector4`. 

t might also be nice to add a `PackedVector4Array`, since the alternatives are `PackedFloat64Array` (or PackedFloat32Array presently used for passing data to shader arrays) and `PackedColorArray` neither of which are ideal.

As for native formats, we already have PackedByteArray and various packed types which can be made from this. But I agree, it's not all-encompassing and both misses many formats and requires copying between types. I really appreciate Javascript's TypedArray system, where there is an `ArrayBuffer` (like a PackedByteArray) which backs the data, and then any number of `Uint8Array` etc typed arrays can be created as *views* over the backing ArrayBuffer. Godot could also enforce alignment such that SIMD operations can always be safely used.

I tried writing conversion code in GDScript for various vertex buffer formats here: https://github.com/V-Sekai/Unidot-Importer/blob/main/aligned_byte_buffer.gd supporting various strides and types (i needed to pass these to mesh APIs, so I wanted to minimize overhead in GDScript). Some of the conversions were clean but others were extremely messy. 

I feel like the discussion about a generic type and/or SIMD / integer operations is interesting but might belong in its own proposal. I'm kind of scared about making things too generic just to solve the Vector4 problem because that creates complexity everywhere in the type system.

**Comment by Zireael07** [comment]
Plane -> Vector4 isn't a bad idea, and ditto for PackedVector4Array

**Comment by Listwon** [comment]
> Plane -> Vector4 isn't a bad idea,

It is a bad idea, because there's no reason for Vector4 to have methods specific to Plane (like `Vector3 project(const Vector3 &p_point)`, `bool is_point_over(const Vector3 &p_point)` etc.).

I really can't grasp what is the real problem of having such basic data type in 3D game engine core.

**Comment by Zireael07** [comment]
@Listwon: You have a point. Maybe have the Plane inherit from V4?

**Comment by aaronfranke** [comment]
@Zireael07 That wouldn't make much sense. There are also methods that would be on Vector4 that don't make sense on Plane, such as length and distance methods, actually I think most methods wouldn't make sense.

**Comment by Zireael07** [comment]
* scratches head kinda sheepishly* right...

**Comment by nathanfranke** [comment]
As mentioned in https://github.com/godotengine/godot/pull/59125#issuecomment-1155927738, `Vector4` can be used to link the values of sides/corners (e.g. stylebox borders top/bottom/left/right) using a property hint.

![image](https://user-images.githubusercontent.com/14253836/174803427-98de7d26-c4d1-4c9e-a4ce-cad5435fc0b5.png)

**Comment by philomelus** [comment]
This has been closed, even though Vector4 and Vector4i have not been implemented in the mono classes.  Isn't making the mono classes part of "implementing" the new feature?  If so, this is incomplete.

**Comment by aaronfranke** [comment]
@philomelus This is already being worked on. These new types not existing in the Mono module prevents compiling the Mono module, so it's not as if this could be forgotten.
