### ISSUE TITLE
Remove class_name and inner classes for just outer class

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#6313]
### Describe the project you are working on

None right now but I have been looking over the many proposals of replaces class_name with class and i think I have an idea

### Describe the problem or limitation you are having in your project

1. having unnamed classes that inherit from something
2. having named classes that inherit from something

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

get rid of inner classes and replace class_name with class

this does the following...

1. unifies and gets rid of confusion between class and class_name
2. forces developers to implement 1 to 1 file to class making code shorter and more readable
3. gets rid of the issue with what if we attach a script with two classes to a node?
4. ensures future class features don't need to be reimplemented for both class and class_name

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Node example...
```
class Entity extends CharacterBody2D
@export var config  EntityConfig

func PrintName():
    print(config.name)

```

Resource example...
```
class EntityConfig extends Resource
@export var name : String

```

Lightweight example...
```
class MyObject extends Object
# same thing
# class MyObject  

@export var my_variable : int
```

all classes can be nameless...
Lightweight nameless example...
```
extends Object 

@export var my_variable : int
```

but nameless classes become accessible without a script reference.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature would be used when creating scripts and is hardcoded into gdscript so there is no workaround

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by RedMser** [comment]
I could only see this working if `class_name` got a replacement, such as putting `@global` in front of the class definition. Just naming a class should *not* instantly make it automatically preload in every file, IMO.

**Comment by Shadowblitz16** [comment]
> I could only see this working if `class_name` got a replacement, such as putting `@global` in front of the class definition. Just naming a class should _not_ instantly make it automatically preload in every file, IMO.

that is literally what a class is.

if namespace pollution is the problem that's not a class issue that's a issue where we need some sort of module system where we can import only the types we are using.

This is actually a case I agree with because gdscripts are flooded with name pollution right now.

of course if I remember correctly reduz said he didn't want that so you would have to take it up with him in another issue.

a class is there to declare a object with a name so you can use it.
having to preload string names is honestly awful and in most situations would be considered a code smell so it should only be there if needed and classes should be the recommended thing to do

if this is a speed issue, there is talk about compiling gdscript to gdextension which if that becomes a thing, there shouldn't be a speed issue.

if you're implying we need inner classes for encapsulation to go with the access modifiers suggestion then we can wait to see if it's implemented and if it is then I can close this issue.

**Comment by RedMser** [comment]
> having to preload string names is honestly awful and in most situations would be considered a code smell so it should only be there if needed and classes should be the recommended thing to do

Every other programming language I know would disagree with you. Preloads are just the way you do imports as you know them from other programming languages, just with different syntax and slightly different behavior.

Tooling for it could be improved to make using preloads more comfy (e.g. autoimport if entering the class name in autocomplete, or via a shortcut), but some classes are just not intended for re-use.

I suppose namespaces would be an alternative way to fix the problems you listed, but I don't like the idea of having to assign a namespace or otherwise my inner class is automatically part of the global namespace...

Also I *really* don't like the idea of being limited to 1 class per file (I assumed you wanted classes to be blocks, not just a line in the header)... If enums and consts can be part of a class, why not other classes? I use inner classes for related data structures ("typed dictionaries" basically), which makes autocomplete in the same file better, but has no business outside of the file.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
