### ISSUE TITLE
Open the editor by default when running Godot without any arguments in a project folder

### ISSUE THREAD

**Issue by jjangga0214** [godotengine/godot-proposals#643]
**Describe the project you are working on:**  _

**Describe the problem or limitation you are having in your project:** 
In order to open the editor by CLI with pre-selecting a project, I need to provide a path of project.godot file, even though I am already in the same directory. 

```bash
godot project.godot
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** 

For convenience, I want it to load project.godot file from the current directory if it exists and no explicit argument is given.

```bash
godot
```

I personally feel this is sane default, and even popular GUI programs(e.g. IDEs) allow this behavior as well.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** _

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** _

**Is there a reason why this should be core and not an add-on in the asset library?:** _

**Comment by Xrayez** [comment]
From this I learnt that `godot godot.project` runs the editor for the project.

But there's currently a special option for that:
```bash
godot -e # short for --editor
```

Perhaps you also suggest that simply running `godot` should open the editor instead of running the game by default?

**Comment by jjangga0214** [comment]
@Xrayez Oh, I didn't know the `-e` option.
To my test, these two commands do the same(Opening the editor). 

```bash
$ godot path/to/project.godot
$ godot path/to/project.godot -e 
```

Thus I couldn't know how `-e` flag can be used for different behavior. Would be happy if you let me know :) .

P.S.
To be clear, what I want is making `godot ./project.godot` and `godot` same.

**Comment by Xrayez** [comment]
See [Command line tutorial](https://docs.godotengine.org/en/latest/getting_started/editor/command_line_tutorial.html).

If `godot` and `godot -e` (aka `godot project.godot`) are the same, then basically the `--editor` option is redundant. But that also means there would be no way to actually *run* the game with `godot` (no editor, and as long as the *main scene* is set), so another option would have to be introduced explicitly for this, something like `godot --run`, or `godot --play`.

Regarding my own opinion, I've never had to run a game with `godot` and always had to put that `-e` option everytime, so perhaps it does make sense to make this default behavior.

Did you know that you can copy the export template directly to where `project.godot` resides and have it run the game without even having to export the project? Just saying that the `-e` option wouldn't make sense for export templates anyway. I'd personally expect the binary with `tools=yes` (the way it's compiled) to open the editor by default (unless `godot --run` is specified), and the export template to actually run the game (because there's no other option really).

**Comment by Calinou** [comment]
I'm not sure if it's a good idea to make the "default" command line behavior depend on whether the Godot binary is an editor binary or export template binary. It introduces an inconsistency that can be confusing in the long run.

**Comment by Calinou** [comment]
Closing per the above comment – changing this behavior now would break compatibility with existing user-made automations.
