### ISSUE TITLE
Make Particles emit a signal when all particles finished

### ISSUE THREAD

**Issue by Anyeos** [godotengine/godot-proposals#649]
**Describe the project you are working on:**
A simple shoot em game with explosions.

**Describe the problem or limitation you are having in your project:**
It is unelegant when you make an explosion or some other effects write a lot of code to only call queue_free().

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If I have a signal for the Particles2D and Particles in general when it stop emitting, I can attach a function to it and call directly queue_free() when it finish. Or make more complex effects like spawning another particle.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```gdscript
func _on_Particles2D_finished():
  queue_free()
```
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
```gdscript
extends Node2D

var lifetime

func _ready():
	lifetime = $Explosion.lifetime
	$Explosion.emitting = true

func _process(delta):
	lifetime -= delta
	if lifetime < 0:
		queue_free()
```
**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is easy to implement signals like the ones of AnimatedSprite

**Comment by WippingPost** [comment]
Hello!
New to Godot, and I found this post since I too have been wondering how to remove my Particles2D object when the its emitting is done. When using "One Shot" the objects "emitting" property will automatically reset itself to "false", so checking for:
Prticles2d.get("emitting") = false in func _process(delta) would be better especially when using a randomness parameter for lifetime. That is what I found worked best for me.

**Comment by macmv** [comment]
Checking `particles.emitting` every frame is annoying and makes ugly code. The current solution I can think of is using a Timer, and connecting the finished signal of that. But this means that you would need to start a timer when you started the particle. This is annoying, but the cleanest solution I can think of. You could also add the particle to the parent scene, and then call `queue_free()` immediately. But this requires that you make sure to remove the particles after they are done playing, which brings us back to the initial problem.

**Comment by WippingPost** [comment]
Hello!
I agree that checking get("emitting") every frame is not optimal, but...
Using a timer is fine I guess, but when using random lifetime you're only
guessing when it's done. And if you change the setting of your particles2d
you have to change the timer too.
I guess you could set the timer to way off to be sure it's done and that
would be fine since the particles will be running on the gpu mostly.
Timer or not...in the background there still will be checking every frame
(we just don't see it in our code) so for me, the best option is to signal
when when the emitting is actually done.

Den ons 9 dec. 2020 21:39macmv <notifications@github.com> skrev:

**Comment by Xrayez** [comment]
See godotengine/godot#7887 where this feature was added, and https://github.com/godotengine/godot/commit/95560e02c5eed3561996ed2b1d1e47e26e8bb81c where this feature was removed.

It's seems trivial to re-add, but I'm concerned about the usefulness of the current GPU implementation. The problem with things like explosions is that you want *all* particles to be processed, and not just when particles stop *emitting*, as it takes remaining particles to fade out as well even if you set `emitting = false`, so it looks like it takes `lifetime * 2` seconds before the node can be freed without remaining particles to suddenly disappear, in fact...

See also my approach at [this Q&A answer](https://godotengine.org/qa/92493/gpu-particles-2d-emit-only-when-visible?show=92673#a92673):

```gdscript
extends Particles2D

func _ready():
	one_shot = true
	emitting = true
	var time = (lifetime * 2) / speed_scale
	get_tree().create_timer(time).connect("timeout", self, "queue_free")
```

[particles_emission_finished.zip](https://github.com/godotengine/godot-proposals/files/5837924/particles_emission_finished.zip)

**Comment by WippingPost** [comment]
I disagree, because "emitting" is only set to false when the last particle
is done. Meaning it has run it's course.
You can easily check this by tracking the "emitting" property by overriding
it's "_process" method.
Here's the code for the explosion (and a smoke) particles I use in a game.
Of course you can set a timer to que_free(), but when you are using
randomness for the particles lifetime, I have found this way  to work best.
Otherwise you would be guessing when it's done emitting.

extends Node2D

var fire
var smoke

*func _ready():*
    fire = get_node("Fire")
    fire.set("one_shot", true)
    fire.set("emitting", false)
    smoke = get_node("Smoke")
    smoke.set("one_shot", true)
    smoke.set("emitting", false)
    start()

*func start():*
    fire.set("emitting", true)
    smoke.set("emitting", true)

*func _physics_process(delta):*
    # Removing object from memory when particles emitting is finished
    if !fire.get("emitting") and !smoke.get("emitting"):
    queue_free()

Den tis 19 jan. 2021 kl 19:42 skrev Andrii Doroshenko <
notifications@github.com>:

**Comment by Xrayez** [comment]
> I disagree, because "emitting" is only set to false when the last particle is done. Meaning it has run it's course.

Well I think we certainly have a misunderstanding here... I think it depends on how fast your particles process, so you might not necessarily see the difference.

Here's what I mean by "not emitting", notice how particles still process.

https://user-images.githubusercontent.com/17108460/105087794-b4895400-5aa3-11eb-8826-ec4491284b4f.mp4

```gdscript
extends Particles2D

func _ready():
	one_shot = true
	emitting = true


func _physics_process(_delta):
	if not emitting:
		$debug.text = "Not emitting"
	else:
		$debug.text = "Emitting"
```

If you were to `queue_free()` the node whenever `emitting` property is set to `false`, then all those remaining particles will suddenly disappear, which is not desired. Therefore, I think using the `lifetime` (and checking `emitting` property), may produce the desired result. 

See test project:

[particles_emission_finished.zip](https://github.com/godotengine/godot-proposals/files/5838386/particles_emission_finished.zip)


> Of course you can set a timer to que_free(), but when you are using randomness for the particles lifetime, I have found this way to work best.

I think it's still possible to calculate the maximum lifetime regardless, but yeah as I said, both techniques can be used to workaround this in the best way possible.

**Comment by WippingPost** [comment]
Ok. I get your point, but that's wierd since I did the same test when
creating my particles, checking to see that they really are finished.
Are you using randomness of the lifetime of the particles.
Good presentation though! 👍

Den tis 19 jan. 2021 21:26Andrii Doroshenko <notifications@github.com>
skrev:

**Comment by Xrayez** [comment]
Apart from modifying gravity, direction, and velocity, no, I haven't touched random-related properties.

> that's wierd since I did the same test when creating my particles

May be due to different version of Godot (tested in 3.2.4), or perhaps you've used `CPUParticles2D` which are different in implementation.

**Comment by WippingPost** [comment]
I'm not using cpuParticles. I am however using version 3.2.3. Not sure if
that has something to do with it. I literally spent 3 knights trying to
figure out how to que_free() ONLY when the emitting was actually done. I
would like to believe I did not miss anything, but watching your video I
guess I must have...😂.
I am however using plenty of randomness in the lifetime of both my
particles. Maybe that has something to do with it...?
Who knows..maybe we're both right...
Cheers

Den tis 19 jan. 2021 21:43Andrii Doroshenko <notifications@github.com>
skrev:

**Comment by sairam4123** [comment]
I'm currently struggling with this, I find the mixture of checking the emitting as well as lifetime working a little worse for me, sometimes the particles just disappears. I got a slow PC, might be because of that?

**Comment by WippingPost** [comment]
Hello!
Hard to say what is causing your issue, but unless your computer is
ancient, I don't think that is the issue.
Is there a reason you have to check the emitting? I found that when using
randomness in the lifetime of the particles, the best way was to check for
"emitting" = true.
It's probably not the most efficient way to do it.

Den tis 27 apr. 2021 kl 12:32 skrev Sairam Kumar ***@***.***>:

**Comment by sairam4123** [comment]
It's same as what @Xrayez had, the particles just gets deleted even before it completes. I just have to put a 0.5 seconds delay, but I don't think that would be a great way, since my game could be played by anyone, so if they have ancient computers they may have the delay, and sometimes the 0.5 second delay doesn't work and particles get deleted before it completes. I haven't tried the lifetime method, I'd try and tell you.

**Comment by KoBeWi** [comment]
Since around 3.3, if you set particles to `one_shot` they will automatically disable `emitting` after *all* particles have finished processing. The signal could be emitted then. Unless there is a case when this doesn't work reliably?

**Comment by sairam4123** [comment]
As far as I know, it seems not that much reliable, I actually had to wait 5-6 seconds, still sometimes it doesn't reliably work.On 28-Jul-2021 4:22 PM, Tomek ***@***.***> wrote:
Since around 3.3, if you set particles to one_shot they will automatically disable emitting after all particles have finished processing. The signal could be emitted then. Unless there is a case when this doesn't work reliably?

**Comment by Xrayez** [comment]
My previous post pretty much sums it up: https://github.com/godotengine/godot-proposals/issues/649#issuecomment-763110270. I'd like to emphasize on "particles finished processing", rather than "particles finished emitting". Still relevant in 3.x.

**Comment by KoBeWi** [comment]
Ah, this only works when you have explosiveness set to 1. Nevermind.

**Comment by ryanscottcausecast** [comment]
FWIW a signal when the last particle is removed is obvious and would be extremely useful.  Guessing/timers doesn't feel like the Godot way.

**Comment by sairam4123** [comment]
> FWIW a signal when the last particle is removed is obvious and would be extremely useful. Guessing/timers doesn't feel like the Godot way.

Maybe the signal could be emitted around 0.1 seconds after the last particle is removed. To make sure that it gets necessary time to clean up.

**Comment by Anyeos** [comment]
> > FWIW a signal when the last particle is removed is obvious and would be extremely useful. Guessing/timers doesn't feel like the Godot way.
> 
> Maybe the signal could be emitted around 0.1 seconds after the last particle is removed. To make sure that it gets necessary time to clean up.

Not seconds but frames (or whate

**Comment by Anyeos** [comment]
Sorry I just read "close" and wanted to close the dialog not the issue.

**Comment by Anyeos** [comment]
I worked in the past on a developing of an "game engine" made in Pascal, and I implemented a particles system that just knew all about each particle it emitted. 
I don't know how Godot handle it but I think it must have some relationship system where the particles can have the refered emitter or some. So, I think with a counter it can add one if it emits a new particle and it can be decreased if a son particle died. 
With that, when the counter reachs 0, it can emit a signal like "particles_finished".

I think the problem is not only technical, but must be reviewed as a proposal for possible troubles or incompatibilities.

**Comment by KoBeWi** [comment]
Actually I wasn't that wrong in my [previous comment](https://github.com/godotengine/godot-proposals/issues/649#issuecomment-888213648).

The time formula until last particle dies is `lifetime * (2 - explosiveness)`. With explosiveness 1, all particles are emitted at start and they disappear exactly at `lifetime`. With explosiveness 0, the last particle is emitted at `lifetime` and lives another `lifetime`, thus time until all particles die is `lifetime * 2`.

You can get a perfectly accurate `finished` signal with this script:
```
extends Particles2D

signal finished

func start():
	if not emitting:
		emitting = true
		get_tree().create_timer(lifetime * (2 - explosiveness), false).connect("timeout", self, "emit_signal", ["finished"])
```

**Comment by elvisish** [comment]
> Actually I wasn't that wrong in my [previous comment](https://github.com/godotengine/godot-proposals/issues/649#issuecomment-888213648).
> 
> The time formula until last particle dies is `lifetime * (2 - explosiveness)`. With explosiveness 1, all particles are emitted at start and they disappear exactly at `lifetime`. With explosiveness 0, the last particle is emitted at `lifetime` and lives another `lifetime`, thus time until all particles die is `lifetime * 2`.
> 
> You can get a perfectly accurate `finished` signal with this script:
> 
> ```
> extends Particles2D
> 
> signal finished
> 
> func start():
> 	if not emitting:
> 		emitting = true
> 		get_tree().create_timer(lifetime * (2 - explosiveness), false).connect("timeout", self, "emit_signal", ["finished"])
> ```

Works very well! I wish particles also had an auto cleanup option when they’ve finished emitting by queue_freeing themselves, with a signal built in this would be slightly easier to do (but a toggle option would also be nice)

**Comment by qbitroot** [comment]
I do it like this:

```
extends Particles2D

func _physics_process(_d):
	if not emitting: queue_free()
```

Attach this script to all particles you want to autodelete.
