### ISSUE TITLE
Add seperate focus style to controls for keyboard/gamepad and mouse/touch

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#6577]
### Describe the project you are working on

Windows 95 Theme

### Describe the problem or limitation you are having in your project

Godot has a limitation where it treats both keyboard and mouse focus and the same thing
This makes it impossible to make a accurate windows 95 theme due to the fact win32 treated them separately 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Rename focus style to keyboard focus
- Add mouse focus
- Rename Control.grab_focus to Control.grab_keyboard_focus()
- Add Control.grab_mouse_focus()
- Add ablity to add shaders to focus styles (this is due to the fact that keyboard focus in win32 uses a negative filter)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is a picture of a windows95 button without any keyboard or mouse focus
![image](https://user-images.githubusercontent.com/2453707/227835624-528405cb-43ac-4620-95df-e6f32f0bb791.png)

Here is a picture of a windows95 button with both keyboard focus (dotted rectangle)  and mouse focus (black border)
![image](https://user-images.githubusercontent.com/2453707/227836098-d3857aac-055c-4c71-b7d6-b57111c4bd40.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It makes themes most customizable

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot-proposals/issues/2011.

**Comment by Shadowblitz16** [comment]
I do have an issue with calling it mouse and keyboard focus since mouse could be touch and keyboard could be gamepad.
Maybe someone else has a brighter idea for names

**Comment by ibe-denaux** [comment]
I was struggling with this since the current way focus works makes it very hard to make a GUI with both mouse and keyboard controls without mouse users having their UI cluttered with a noisy focus style.

For most apps, it would already be helpful for Control nodes to have a 'keyboard only' focus mode so that users don't see a focus when they don't need to. I agree that this proposal would be the best way to handle it though. 

A current workaround I thought of using is to have two separate themes that activate based on the input (mouse or keyboard), but this feels incredibly hacky, and doesn't work for the windows 95 theme example. Let me know if anyone has a better workaround though.

> I do have an issue with calling it mouse and keyboard focus since mouse could be touch and keyboard could be gamepad.
Maybe someone else has a brighter idea for names

I agree, maybe something like Keyboard -> Directional, and Mouse -> Screen?

**Comment by passivestar** [comment]
> (I have a WIP at https://github.com/Calinou/godot/tree/button-focus-visible)

@Calinou any plans on making a PR? also any plans on doing the same thing for all other ui elements that draw focus such as scrollboxes, trees, etc?

**Comment by Calinou** [comment]
> [@Calinou](https://github.com/Calinou) any plans on making a PR?

Unfortunately, I won't have time to work on it until 4.5 is released at least. Also, the branch is quite outdated and wasn't fully working, so I suggest starting from scratch at this point (but feel free to take a look for inspiration nonetheless).

> also any plans on doing the same thing for all other ui elements that draw focus such as scrollboxes, trees, etc?

I agree this should also be offered for in-control focus too, but I'm not sure what the API/exposed properties should look like.
