### ISSUE TITLE
Reimplement `String.erase()` as an immutable method

### ISSUE THREAD

**Issue by SilicDev** [godotengine/godot-proposals#6598]
### Describe the project you are working on

A String formatter for a chat bot with dynamic placeholders.

### Describe the problem or limitation you are having in your project

As I may have to evaluate every occurence sequentially (as they can differ or are nested) I can not use `String.replace` or `String.format`. With the removal of `String.erase` I have to manually construct the result. `String.erase` is also the only way to my knowledge to remove the first occurence of a String.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to see `String.erase` reimplemented, as an immutable function to fix why it was removed in the first place (see godotengine/godot#37918).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implement `erase` as in 3.x, but return a new String instead of modifying the String the method was called on.

Additionally my fork already has a working implementation that could be merged https://github.com/SilicDev/godot/tree/string_erase

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, however as a basic string operation this should really be in core.
```gdscript
func _str_erase(str: String, pos: int, len := 1) -> String:
	return str.left(max(pos, 1)) + str.substr(pos + len)
```
The alternative is writing equivalent expression everywhere it's needed.
The engine is also using this approach as seen in the changes in godotengine/godot#54869

### Is there a reason why this should be core and not an add-on in the asset library?

As a basic string operation this should really be in core.

**Comment by AThousandShips** [comment]
You edited the issue and broke the links that was previously corrected

**Comment by SilicDev** [comment]
Thank you, fixed

**Comment by DaGamingWolf** [comment]
I still don't know what could have led to the conclusion that this should have been removed. I get it, strings should be immutable. that's the convention chosen for gdscript. What I don't get is why string.erase() wasn't simply modified to return a new string, allowing the old one to be discarded. Was it causing problems or something? I'd understand if it was actually causing problems, but so far it just introduces a headache I have to work around in order to make a game with godot.

**Comment by AThousandShips** [comment]
Please, this is not constructive or helpful, please respect the [code of conduct](https://godotengine.org/code-of-conduct/)

It is being implemented again, so your complaints over it having been removed aren't helpful, this is a place to discuss implementations and improvements, not venting frustration or attack decisions being made years ago.

Removing it and then reimplementing it was discussed and decided in godotengine/godot#37918

**Comment by AThousandShips** [comment]
There doesn't seem to have been much of a reaction to it being removed, as it is easy to work around it, and the use of it isn't necessary that common, just because you need a feature doesn't mean that it's an unreasonable change to remove that feature, please consider that you are not the only one using Godot, you were also already told about this workaround but rejected it

That being said, this feature is coming back

**Comment by DaGamingWolf** [comment]
> There doesn't seem to have been much of a reaction to it being removed, as it is easy to work around it, and the use of it isn't necessary that common, just because you need a feature doesn't mean that it's an unreasonable change to remove that feature, please consider that you are not the only one using Godot, you were also already told about this workaround
> 
> It was removed not just vecause of the principle that strings should be immutable, but because of the bugs that caused

I think you misunderstood the intent behind my post. I'm not concerned about venting my frustration or lack thereof. I'm getting my position on the record so the level of support for the feature can be more accurately measured by those who are trying to gauge such things. Looking back, I understand the limited helpfulness of my post and I am willing to adapt my posts accordingly if expressing a position alone is not enough to justify. 

I am surprised, however, that my post was interpreted as an attack. I personally wouldn't consider expressing confusion about a decision and communicating the resulting experience due to the decision as such. I attempted to make it clear I didn't have an understanding of the decision, with the implication that because I don't I therefore can't conclude that the experience I had at the result of the decision was unreasonable. I don't know if it was reasonable or not.

 I apologize for my lack of tact, and I will endeavor to introduce more consideration and constructiveness into my posts.

**Comment by AThousandShips** [comment]
Thank you for clarifying, I misread your intention

**Comment by golddotasksquestions** [comment]
`erase()` imho is really basic String functionality and one should not have to search for a workaround or have to write custom utility to erase a number of characters from a string at a certain position in the string.

The 3.X method was fast and intuitive to use, even for beginners. The solution and workaround we have right now is not.
[
Two years ago](https://github.com/godotengine/godot/issues/37918#issuecomment-775226868) I was trying to test the RichTextLabel in early Godot4 builds because I knew I'm going to need this. Now I'm in the process of porting an existing Godot3 project to Godot4 and have to find `erase()` is still gone from Godot4.

This is again a massive usability regression in Godot4 making it less user friendly compared to Godot3. I really hope this is reimplemented soon.

**Comment by SilicDev** [comment]
Would it be worth it to have the project converter fix `erase` by assigning its result to the input variable (I'd think we can assume nobody passes a string literal to this)

**Comment by Calinou** [comment]
> Would it be worth it to have the project converter fix `erase` by assigning its result to the input variable? (I'd think we can assume nobody passes a string literal to this)

The project converter is regex-based, so it can't perform advanced conversions like that.
