### ISSUE TITLE
Add support for 3D Level of Detail

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot-proposals#692]
I'm going to ignore the issue template because this has been confirmed to be implemented in the future.

I'm opening this issue because the conversation arround LOD is scattered by multiple issues and I think it is important to have a common place to discuss the technical details of a feature (and move the discussion of the design to the proposals repository).

### Hierarchical level of detail
Another LOD approach (and not mutually exclusive with the previously mentioned) is the hierarchical level of detail. With this a single mesh can replace multiple smaller ones. It greatly helps reducing the mesh count for the areas far from the camera.
https://docs.unrealengine.com/en-US/Engine/HLOD/index.html

This will be implemented as stated here: https://twitter.com/reduzio/status/1340114705923379202

### Content streaming

Related issue: godotengine/godot#17556

As indicated by @Calinou : "Support for LOD and texture streaming is planned in Godot 4.0"

**Comment by Calinou** [comment]
Related to #657.

**Comment by SIsilicon** [comment]
I have a pitch for how this can work.
- A new node known as an `LODGroup` can be used to manage multiple LOD levels.
  - It can have 1-8 GeometryInstances as children. Their order determines what LOD level they represent.
  - Each of those children can have sub-children allowing for Hierarchical LOD.
- The LOD system will be screen coverage dependent like Unity. That way the LODs will work consistently with different Cameras and Viewports.
- A Viewport can have an LOD bias and a minimum base LOD, including the main game Viewport, allowing variations across platforms.
- In the VisualServer (RenderingServer in 4.0) the LODGroup will be used to determine what gets called from rendering per Viewport.
- Shadow maps, Reflection Probes, Baked Light, etc.. will all only use the minimum LOD level when doing their computations.

**Comment by fire** [comment]
I have done the lod generation portion of this, but it's lacking the engine implementation.

https://github.com/godotengine/godot-proposals/issues/657#issuecomment-640254293

1. It needs to use a screen space metric for the mesh.
1. A single mesh needs to share the same vertex array but have different indices rrays.
1. The above comment's lod grouping work

**Comment by fire** [comment]
Can someone review the proposal and remove items that have been implemented? This is why omnibus issues are hard to use.

**Comment by lupoDharkael** [comment]
I've removed all the features already implemented and referenced all the planned ones. The only one I don't know if there are any plans to implement is Per-Platform LOD configuration.

**Comment by Calinou** [comment]
>  The only one I don't know if there are any plans to implement is Per-Platform LOD configuration.

You can configure the currently available automatic LOD both on a per-node basis and using project settings. Project settings can be overridden using [feature tags](https://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html.

**Comment by lupoDharkael** [comment]
@Calinou  I've removed that item from the description, maybe I should open an issue in the documentation so that feature gets documented when the API is stable.

**Comment by Zylann** [comment]
I'm not sure if I should open another issue, but since LOD fading has been discussed here I'll post it:

I'm coming back to this every so often and I'm leaning towards the animated approach, rather than a purely distance-based per pixel approach, mostly because fading must not freeze in-between if the camera doesn't move. I need this for several things:

- My voxel terrain's octree LOD system, in which meshes are not available up-front, and I don't use nodes for procedural meshes so any setup requiring scenes or nodes is not possible
- Instancing on top of the terrain, which can use meshes, multimeshes, but also impostors, which use a different shader and aren't part of the LOD system of Godot 4 AFAIK

Still, even if the setup is different, the problem remains the same: I want fading between my LODs. I can figure out a system on my own but there are several things rendering-wise I'm still bumping into after all this time:

1) https://github.com/godotengine/godot/issues/34966 is still an issue in Godot 3.2.4 rc2, which makes it harder to use the dithering technique properly without fireflies popping up in trantitionning meshes. So far the only workaround that *appears* to work *on my computer* is to use `discard` at the very end of the fragment shader.

2) Not enough control on shadow mapping. When two mesh LODs are rendered at once, one fades in, the other fades out, and complementary pixels get discarded by dithering so it looks seamless. But there is no way to have that on the shadow, because one of the two meshes should not cast shadow on the other. I don't think that's possible currently. We could consider that only the fading-in mesh casts a shadow then, but it will make shadow pop. And even if we consider shadow popping as acceptable, the shadow map is still only picking up non-discarded pixels of the fading-in mesh, *which is not wanted in that fallback case*. So overall, if you have shadows, you just cant fade properly, AFAIK.

3) Will not work with multiple cameras. This is a more general issue I have with any LOD/Culling systems I'm making, because the scripting API has no way to tap into these rendering passes.

About re-usability:
The voxel module I'm making is not dedicated to one project, and may migrate to an addon in the future. If Godot opens up possibilities to solve these issues, it would preferably need to be easily integrable in different projects, so solutions involving a fork of the engine or a completely custom rendering architecture are not suitable for assetlib distribution.

Nevertheless, I put up a test project to try out the system:
[DiscardFading.zip](https://github.com/godotengine/godot-proposals/files/6012808/DiscardFading.zip)
