### ISSUE TITLE
Add a position scale factor to AnimationTree

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#7022]
### Describe the project you are working on

A 3D game with lots of user-generated content, including user-generated avatars of many sizes.

### Describe the problem or limitation you are having in your project

Currently it is not trivial to re-use the same set of animations for characters of different sizes.

One option is to duplicate all animations and perform retargeting or scale the position tracks manually, but this would be a very complicated solution with significant memory consequences since it involves duplicating all animations.

Another option would be to offset the skeleton vertically to make the character at the desired height, but this only works for characters with roughly the same heights (0.5x to 2x). With very small characters, this approach causes the position animation to hugely change the position relative to their size, violently shaking the poor small character.

I have also tried to see if it was possible to do this with AnimationNodes inside of an AnimationNodeBlendTree, but I think this is not possible, because AnimationNode does not distinguish between track types as far as I can tell.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose adding a position scale factor float value to AnimationTree. This can be set to control the position scale. The AnimationTree would apply this to 3D Position tracks to work with either Node3D nodes or Skeleton3D bones.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

PR: https://github.com/godotengine/godot/pull/77865

This PR adds the position scale factor, and applies it when setting a position track onto a node or skeleton bone.

Conceptually this would also make sense to put on AnimationPlayer in addition to AnimationTree, but I think this would primarily be used in more advanced cases where users have an AnimationTree anyway.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. At least, the work-arounds I know about are complicated, performance-intensive, or don't work well.

I don't know how often this will be used, I think it's not very common to want to use the same set of animations with differently sized characters, but it's quite useful for games that do need to have differently sized characters, especially games with user-generated content.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it can be done in an add-on, but I would be happy to be proven wrong.

**Comment by TokageItLab** [comment]
This proposal already exists in Retargeter as a `motion scale` property implemented in `Skeleton3D`.

https://github.com/godotengine/godot/pull/63138

If you want to use this in an environment that does not use Retargeter, perhaps it might be worthwhile to take only this setting out of Retargeter. Then, Retargeter will only set the motion scale property outside of Retargeter to the recommended value estimated from the model hips height, instead of having that property inside of Retargeter.

**Comment by aaronfranke** [comment]
@TokageItLab In my case, the animations are only created once in the editor, and shared for all characters imported at runtime. Will that solution work here? Would it require me to duplicate my animations for each character?

**Comment by TokageItLab** [comment]
Yes, it works as long as you use retarget (specifically `Normalize position tracks`) for all models (the actual model you use and the model you animate).

If that option is enabled, the Skeleton3D motion scale property will be imported with the hips height set.

When the animation is extracted from glTF, the position track values are normalized by dividing by the hips height of the model that has the animation. After that, when the animation is played back, it is multiplied by the motion scale.

Basically, the hips height is used because the position track is affected by the character's movement, i.e., the difference in stride length. There is a `Base height adjustment` option https://github.com/godotengine/godot/pull/64015 to manually adjust for high heels, bare feet, etc., but if you want to always use a base value other than hips height, you may need to add some additional functionality to the importer.

However, if you want to use this with the runtime loading, we will need to get PostImportPlugins to work at runtime in the first place.
