### ISSUE TITLE
Add Material/Material Override support for decals

### ISSUE THREAD

**Issue by MangoDragonHub** [godotengine/godot-proposals#7180]
### Describe the project you are working on

I'm working on a jet ski racing game that uses water and I want to make caustics to make it look nice.

### Describe the problem or limitation you are having in your project

I can inject my caustic texture as a emission texture and that's pretty much it. No UV scaling control, I can't dynamically distort the texture, and can't scroll uvs . It would be nice if I had the ability to make a material to allow it do so.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature is simple. While still having option of still having individual textures, right under the all of the normal options or under the textures option gives you the option to override all the settings using an assigned material. With this you are given more customization to decal materials.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I opened up Krita and added a basic Surface Override tab at the bottom.
![GodotDecalProposal](https://github.com/godotengine/godot-proposals/assets/7853845/65bea7cd-05e5-4ca9-a0d4-586b19f5ab11)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know. I'm not a strong programmer but this is an editor feature more than anything.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a small addition, but I think this will help out a lot people creating dynamic decal effects.

**Comment by AThousandShips** [comment]
* Related/duplicate: #4938

**Comment by yosoyfreeman** [comment]
I just would like to share a few thoughts here:

- I find myself explaining quite often to new and not so new Godot users that when they read that Godot now support decals, it does not mean what they probably are thinking about. People usually thought about decals from a level design perspective, which is what Godot have right now. The thing is that 3D artist nowadays mostly speak about decals to talk about it use in 3D asset creation.  Using decals to add detail on meshes is becoming more and more common, specially at an indie scale, because it allows to generate high quality content exponentially quicker. Therefore the confusion of lots of users trying to work with this kind of workflows and seeing they can not get it done.

- Calinou Kindly explained a lot of things in https://github.com/godotengine/godot-proposals/issues/4938. In that proposal, this is explained:

> In future 4.x releases, [there will be more low-level renderer access so you could replace this standard scene shader entirely](https://godotengine.org/article/vulkan-progress-report-7/#:~:text=low%20level%20access%20to%20renderingdevice) (without having to recompile the editor and export templates). This will remain something for advanced users only, though.

While i understand the point of trying to keep the solution clean and quick at the cost of flexibility, i think that, in this particular case, there is not a huge overlap between fully focused 3D artist who use decals on a daily basis and people with enough technical acknowledgement about rendering to implement them by themselfs.  With this i mean that while technically supported, migration from any other engine will be painful for artist if they lack the tools that can help then the most to do their job.

For example, we are having serious issues to replicate common workflows for sci-fi environments, which leads to a lot more time expend in achieving less quality results. Of course, there is always a way to get nice results. But maybe we are underestimating the importance of this artist pipeline.

Hope my thoughts were clear and organized and they can provide some kind of feedback, even if it is to clarify a little more the Godot intended use of this systems on the docs. 

Hope you all have a nice day.

**Comment by Calinou** [comment]
> The thing is that lots of 3D artist nowadays mostly speak about decals to talk about it's use in 3D asset creation. Using decals to add detail on meshes is becoming more and more common, specially at an indie scale, because it allows to generate high quality content exponentially quicker. Therefore the confusion of lots of users trying to work with this kind of workflows and seeing they can not get it done.

What prevents you from using Decal nodes as they are on 3D assets?
