### ISSUE TITLE
Automatically Set Main Scene

### ISSUE THREAD

**Issue by rontarrant** [godotengine/godot-proposals#720]
**Describe the project you are working on:**
I'm just starting out learning the Godot game engine. Each tutorial I've followed to far describes the process of setting the Main Scene, something that's done each and every time a new project is created.

**Describe the problem or limitation you are having in your project:**
When the first scene of a new project is created and then saved, the user has to open the Project menu, go to Project Settings, and drill down to where Main Scene is set so it can be configured. This is something that could be done automatically, saving the user time and effort. And because the first scene created usually (I'm assuming) ends up as the Main Scene, it's unnecessary effort that could easily be done by Godot.

Also, if the user knew in advance that the first scene created will automatically be set as Main Scene, they could shape their workflow to include this expectation.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
After the first scene is created in a new project, when the user saves that scene, if that scene is not just saved to disk, but the user-supplied name is also automatically used to set the Main Scene in Project Settings, it would (for the average user) speed up workflow.

For new users, it would give them one less thing they need to fiddle with before running their projects for the first time.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
- user selects Scene > Save in a new project
   - save dialog pops up,
   - user types name of scene,
   - user clicks "Save" button,
   - user-supplied name is stuffed into a string and...
   - used to set Project Settings > Application > Run > Main Scene.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't foresee any harm in this feature being executed every time the first scene of a new project is saved. Once it's set, if the user wants to change the Main Scene to something else, he/she would have to create the scene and then select it in Project Settings. But the way things work now, they have to do this anyway, so I don't think it will inconvenience anyone.

I see it as a way of speeding up development time and it would be especially useful if the user is creating a one-scene project.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Reasonable defaults will save the user time and (for new users) confusion.

**Comment by bojidar-bg** [comment]
While this would be a good way to streamline the experience, it might leave new users at a loss of how to change the main scene afterwards.

For example, one usually needs to change the main scene when adding a main menu, since most projects start with the game scene.

---

I think it might be better to inform the user that the main scene would be changed when setting it to the first saved scene. Even better, asking the user if they want to make it the main scene would allow power-users starting with the player scene to not have to open the project settings.

For example:
![image](https://user-images.githubusercontent.com/5276727/79574552-00e4d500-80c9-11ea-8cf0-0e0466e7cd18.png)

Or maybe:
![image](https://user-images.githubusercontent.com/5276727/79574949-a6984400-80c9-11ea-839b-c6bac2d30f0d.png)

Another way to streamline the current process would be to add an option to the dialog which pops up when playing the project for the first time, named "Make Current Scene Main" or "Set to Current Scene". This should help both power-users that create a bunch of scenes when starting the project and conventional users that create a single scene and play immediately afterwards.

For example:
![image](https://user-images.githubusercontent.com/5276727/79574322-a64b7900-80c8-11ea-979e-704cbf72522a.png)

**Comment by Jummit** [comment]
I like the "Select current" the best. It appears in a more logical place, saving scenes without a main scene set shouldn't always show a popup.

**Comment by rontarrant** [comment]
Yup, that's a better idea... that final dialog you mocked up. I'm assuming the "Select" button would pop up a list of scenes to pick from. That's an excellent idea, too. And the logic could be rounded off by having just "Cancel" and "Select Current" if there's only one scene available in the project.
