### ISSUE TITLE
Improve code readability when code is under the code editor minimap

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot-proposals#7215]
### Describe the project you are working on

A code heavy project were I spend most of my time in the code editor.

### Describe the problem or limitation you are having in your project

The minimap in the code editor has, depending on the scripts lenght, a lot of empty space under the part of the map that shows code. This is wasting space in the a bit crammed code editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the space of the minimap that is not showing actuall code fully transparent or make it a transparency slider.
Also, while we're at it: Maybe make the before mentioned options also affect the backround of the part of the map that shows code. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

_(The code used here is pseudo code generated by ChatGPT)_
One could argue that the user should keep the lines of their code shorter, but that is shoving the problem away to the user.

**BEFORE:**
Notice how the empty space under the minimap cuts of some of the code editor. This hinders readability of code sometimes, but also looks very ugly (but that is subjective)

![RAW Godot code editor minimap improvements](https://github.com/godotengine/godot-proposals/assets/111653551/c7933a64-a068-4c15-ab50-78a7706af9b5)

**AFTER:**
The red space is normally taken up by the minimap. 

Yes, its only a very small portion of the text that gets visible with this change.
But: I would have have to scroll a bit horizontally to read it otherwise. 

![Godot code editor minimap improvements](https://github.com/godotengine/godot-proposals/assets/111653551/33acd31b-8171-4714-882e-b6ebfdbd7f9e)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can not be worked around with a few lines of script. Though it can be worked around by scrolling the text horizontally.

### Is there a reason why this should be core and not an add-on in the asset library?

This affects the script editor and it is a core part of godot.

**Comment by Calinou** [comment]
For reference, Visual Studio Code doesn't do this. Instead, it makes the minimap narrower if the editor view is narrow.

**Comment by xxSeys1** [comment]
That would be a possible solution. Though I think the one proposed by me is better, because making the minimap narrower does not solve the problem, it only makes the impact of it smaller.

Though if there is a technical limitation with implementing the proposed transparency in the minimap, that would probably be the best solution.

**Comment by Download** [comment]
A do see a downside of making the minimap transparent. In the current situation it is annoying you cannot see the code, but that does make it perfectly clear that you cannot click there to get a cursor on that position. If the minimap were transparent in that area, you would click there expecting to get a cursor but you would instead be clicking on the (transparent part of the) minimap. We could get around that by making the minimap not fully transparent so you can see the code but also see that it is actually behind the minimap.

Maybe even better would be to adjust the height of the minimap so that the area below is simply not there and hence no need to make it transparent in the first place. Not sure if that solution would be more complex to implement though...
