### ISSUE TITLE
Option to export to Wii U

### ISSUE THREAD

**Issue by Moonlumen** [godotengine/godot-proposals#7216]
### Describe the project you are working on

Nothing specific

### Describe the problem or limitation you are having in your project

VERY unfortunately, I can't export my games to an 11 year old console

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for exporting to Wii U and/or other supported consoles, with open source SDKs/toolchains like devKitPro, which eliminate the need for an official SDK under a non-disclosure agreement or such.

Others have already made support for 3DS and Switch, so I don't see why Wii U shouldn't be able to get Godot support.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new export option is added for Wii U.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This isn't possible to implement with an addon afaik, but it could maybe be fit better as a fork of Godot instead of being built in.

**Comment by Calinou** [comment]
There are no plans to officially maintain console homebrew ports
, but third parties are free to create ports as was already done for the [3DS](https://github.com/SeleDreams/godot-3ds) and [Switch](https://github.com/faithvoid/GodotNXPorts).

**Comment by dsnopek** [comment]
> This isn't possible to implement with an addon afaik, but it could maybe be fit better as a fork of Godot instead of being built in.

It's possible that this could be implemented as a platform directory that can be copied into the Godot source code, rather than a full-on fork, similar to [FRT](https://github.com/efornara/frt). Although, maybe not, depending on how "non-standard" the toolchain and the Wii U platform is?

In any case, it seems unlikely that support for Wii U via devKitPro would be merged into Godot itself. It'd be really cool to see as a 3rd party project, though. :-)
