### ISSUE TITLE
Add property prediction and interpolation, and a way to capture MultiplayerSynchronization events

### ISSUE THREAD

**Issue by X64X32** [godotengine/godot-proposals#7280]
### Describe the project you are working on

A Fast-Paced MP FPS.

### Describe the problem or limitation you are having in your project

There's no easy way to interpolate multiplayer properties, as a workaround, I make a varible that contains current position and share it via MultiplayerSynchronizer node. The reason why i'm using custom varible for position is that MultiplayerSynchronizer automatically replaces the position value with the one it just got from the server.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to be able to write custom logic for these events. Maybe a way to get synchronized properties in a signal and do whatever I really want with them. Custom client logic seems safe as well, if the server is the main authority, position and such values will be correct despite anything that client does with them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/53514993/075606b4-eeb3-472d-822f-eecef085b079)

SceneReplicationConfig could have a property which would disable automatic property updates, and MultiplayerSynchronizer **synchronized** signal could pass a dictionary synchronized values.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it's easilly possible to modify signals of already existing classes.

### Is there a reason why this should be core and not an add-on in the asset library?

Same as above, I think, writing custom logic for synchronized varibles seems like a pretty good idea, which should be included in the engine itself.

**Comment by Calinou** [comment]
cc @Faless

**Comment by X64X32** [comment]
Having a way to at least capture these events might remove the need to add prediction/interpolation in the engine itself

**Comment by Faless** [comment]
We have been discussing this feature during a networking meeting, and we agree it would come really handy.

We can't change a signal signature, so we would need a new signal in case.

I don't particularly like having all the variables in a signal as that would negatively affect performance.

We could fire a dedicated signal for properties marked as "manually interpolated", but I'm leaning more towards letting the dev set a Callable, so the engine can check and warn when the callable is not set (we could do that check for signals too, but again, in a less performant way).

So something like:

![interpolate](https://github.com/godotengine/godot-proposals/assets/1687918/7d2eca59-50c7-4f88-8e4c-0d26652d5aa1)

```gdscript
func _ready():
    set_interpolate_method(my_interpolate)

func my_interpolate(dict: Dictionary):
    print(dict)  # Will print '{"position": THE_INCOMING_POSITION}' for the above example

```

**Comment by TheYellowArchitect** [comment]
I only want to mention that nearly all modern online realtime games use some form of snapshots and rollbacks, because interpolation of the last 2 snapshots isn't enough. While the above solution of a checkbox for interpolation is good, and better than no interpolation at all, I would suggest expanding it a bit further to have new functions inside MultiplayerSynchronizer where you set if the interpolation is to happen from previous snapshot to latest snapshot, or previous-1 snapshot to latest-1 snapshot, or something along those lines, probably bloated. Though adding an intentional delay on the latest snapshot (basically you want 3 snapshots in total to process at all times) as an option, so you interpolate not the latest snapshot but the 2 before it

Honestly the more I write this, the more I feel my suggestion^ is bloated and should be left to the developer. So if he wants advanced interpolation or snapshots or rollback, he can disable interpolation and synced properties' signals to do his own interpolations among the snapshots (synced properties in this case)

**Comment by X64X32** [comment]
> I only want to mention that nearly all modern online realtime games use some form of snapshots and rollbacks, because interpolation of the last 2 snapshots isn't enough. While the above solution of a checkbox for interpolation is good, and better than no interpolation at all, I would suggest expanding it a bit further to have new functions inside MultiplayerSynchronizer where you set if the interpolation is to happen from previous snapshot to latest snapshot, or previous-1 snapshot to latest-1 snapshot, or something along those lines, probably bloated. Though adding an intentional delay on the latest snapshot (basically you want 3 snapshots in total to process at all times) as an option, so you interpolate not the latest snapshot but the 2 before it
> 
> Honestly the more I write this, the more I feel my suggestion^ is bloated and should be left to the developer. So if he wants advanced interpolation or snapshots or rollback, he can disable interpolation and synced properties' signals to do his own interpolations among the snapshots (synced properties in this case)

MultiplayerSynchronizer could have new properties like buffer_size and interpolation_offset for such things for interpolation.
But I agree, having a way to get synchronized properties and writing custom logic is more than enough, so built-in interpolation is not necessary.

**Comment by X64X32** [comment]
oh, closed that accidentally

**Comment by nickpolet** [comment]
It would be great to see something like this implemented. It's really quite crucial for games that require smooth movement over a network (which seems to be most multiplayer games these days).

The MultiplayerSynchronizer node is amazing at the moment, but something like what is described above would really help take it to the next level. 

Would be good to see this proposal opened up again.

**Comment by cidwel** [comment]
Probably I'm out of touch here but I was looking for something specific. Not thinking on lag compensation, interpolation or a rollback system but more in some basic core functionality with the MultiplayerSyncroniser. 

I was expecting the component to have signals where you could hook when those variables are changed. As a basic example I could have some variables like `hp`, `defense`, `mp`, `experience` or whatever I would like to have synced in an arena and hook signals whenever those single variables change. So when the `on_change` of the variable `hp` is fired I could see the previous value, the new value and do any custom action intended, like updating the UI:
````
_on_change_hp(var previous, var new):
   update_hp_hud(new)
   print("HP changed from " + previous)
````

In other systems I've seen this called SyncVars, and they even have some interesting elements like knowing if the variable is changed or even if a collection has added, set, deleted  a new element or collection is cleared.

I found MultiplayerSyncronizer as the ideal component that would able to create a library of synced vars, where you could set also the refresh rate per variable individually.

**Comment by r4ven1245** [comment]
Is there any progress on this? Didn't see anything in the documentation, and was wondering if this proposal still being considered, or when is it planned to be implemented?

**Comment by Calinou** [comment]
The proposal is still being considered as per the above comments, but nobody has started an implementation yet so we can't give an ETA.

**Comment by 3da** [comment]
Godot would be the true God of game engines if it have native support of rollback and input prediction.
There is nice addon for this purpose https://godotengine.org/asset-library/asset/2450
Made by @dsnopek
Would be nice if someone could do something like that, but more integrated into engine and existing scene replication API.
I also found nice project for C# https://github.com/lucasteles/Backdash
But don't know yet how to integrate that with Godot.
I also know that https://teeworlds.com/ has good rollback\prediction system.

**Comment by ywmaa** [comment]
> Godot would be the true God of game engines if it has native support of rollback and input prediction.
> There is nice addon for this purpose https://godotengine.org/asset-library/asset/2450
> Made by @dsnopek
> Would be nice if someone could do something like that, but more integrated into engine and existing scene replication API.
> I also found nice project for C# https://github.com/lucasteles/Backdash
> But don't know yet how to integrate that with Godot.
> I also know that https://teeworlds.com/ has good rollback\prediction system.

Ok, I am coming from a background where I worked on and helped in developing a rollback netcode fighter game in Godot 3 with dsnopek's addon.

It isn't only about network replication and rollback, it also needs a predictable and deterministic physics engine for both 2D and  3D because we don't know if the game developer will make their fighter game 2D or 3D so before having a rollback netcode base, we will need to have jolt as the 3D engine, as I heard it is deterministic, and make the 2D engine deterministic too or probably use Box2D as I heard it is deterministic (not sure though).

And also rollback netcode in general isn't for all multiplayer games, some games just find normal lag compensation + Client side prediction enough, so rollback netcode is almost a game specific thing.


I would be happy to have all of these networking solutions built-in in the engine, but I am not sure if this is something that will happen for Godot Engine, since it is always said that it is a General Game Engine, and for a feature to be added, it must be beneficial to a majority of games that will be made by the engine.

**Comment by 3da** [comment]
>since it is always said that it is a General Game Engine

Yeah, I agree, that not every game requires these network techniques. Most games even don't have multiplayer. But we have really nice scene replication API.
So I believe these guys can do some nice improvements to high-level network API step by step, to provide even better developer experience for network games.

May be after some network\physics core improvements there will appear any epic addon for these purposes. It will be good as well.

**Comment by Calinou** [comment]
> we will need to have jolt as the 3D engine, as I heard it is deterministic

godot-jolt is currently not deterministic: https://github.com/godot-jolt/godot-jolt#what-about-determinism

Even if it was able to be deterministic, this is something you'd have to explicitly opt into, as making guarantees of determinism has several caveats (such as making multithreaded physics simulations impossible by design).

**Comment by ranger-x-dev** [comment]
> So something like:
> 
> ![interpolate](https://private-user-images.githubusercontent.com/1687918/256973651-7d2eca59-50c7-4f88-8e4c-0d26652d5aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODY4MDksIm5iZiI6MTcxMTk4NjUwOSwicGF0aCI6Ii8xNjg3OTE4LzI1Njk3MzY1MS03ZDJlY2E1OS01MGM3LTRmODgtOGU0Yy0wZDI2NjUyZDVhYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTU0ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcyY2NlZmM0ZjZmMjBlNmZhMWQ0ZTVhODZjMTZkNjE3OTdhZGU1NmUyMTI2YjNhMjZhNjkyNDYwZWVlMTgxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9ao720D5RNf_rF4YicxatAZqSjPbPvSwOSFTERUibSE)

I would love to see this feature implemented. In my server-client implementation, being able to reduce the "server tick rate" by setting the replication interval and delta interval on the MultiplayerSynchronizer node is a great feature to limit bandwidth. Of course that comes with the price of laggy/jerky motion on the client side. Being able to go down and select which properties you want interpolated client-side with a simple check box would be such a convenient solution for that.

**Comment by vassembly** [comment]
> > So something like:
> 
> > 
> 
> > ![interpolate](https://private-user-images.githubusercontent.com/1687918/256973651-7d2eca59-50c7-4f88-8e4c-0d26652d5aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODY4MDksIm5iZiI6MTcxMTk4NjUwOSwicGF0aCI6Ii8xNjg3OTE4LzI1Njk3MzY1MS03ZDJlY2E1OS01MGM3LTRmODgtOGU0Yy0wZDI2NjUyZDVhYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTU0ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcyY2NlZmM0ZjZmMjBlNmZhMWQ0ZTVhODZjMTZkNjE3OTdhZGU1NmUyMTI2YjNhMjZhNjkyNDYwZWVlMTgxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9ao720D5RNf_rF4YicxatAZqSjPbPvSwOSFTERUibSE)
> 
> 
> 
> I would love to see this feature implemented. In my server-client implementation, being able to reduce the "server tick rate" by setting the replication interval and delta interval on the MultiplayerSynchronizer node is a great feature to limit bandwidth. Of course that comes with the price of laggy/jerky motion on the client side. Being able to go down and select which properties you want interpolated client-side with a simple check box would be such a convenient solution for that.

as far as I know, MultiplayerSynchronizer uses delta compression algo, so by implementing interpolation, we will pretty much get a win scenario for multiplayer development.

**Comment by RexReposit** [comment]
I agree, this function may be extremely necessary.

**Comment by AThousandShips** [comment]
@RexReposit Please don't bump without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Rybiscom** [comment]
Hey guys 👋
I'm writing my multiplayer game on Godot. 
And since I haven't found a suitable solution for interpolating motion on the client side, I wrote my own script.
This script interpolates the position, rotation and scale of an object.
-
How to use it?
1) Add a new **Node3D** node to your character instead of the **MultiplayerSynchronizer** node.
2) Add my script to this node.

Since the script does not synchronize the spawning of the object, you need to add a **MultiplayerSpawner** node to the main scene and configure it to spawn your character.

Script variables:
**TrackThisObject** - Add the main node of the player or character whose parameters will be synchronized
**SyncPosition**, **SyncRotation**, **SyncScale** - Which parameters should be synchronized.
**InterpolationOffsetMin**, **InterpolationOffsetMax** - Since the script automatically adjusts the delay required for interpolation, these values allow you to set the maximum and minimum delay (you can leave them at default 1-500).

As I have already written the script automatically adjusts the delay on each object depending on the speed of your server and the latency of the Internet connection with the player.
This is necessary for smooth interpolation
Also the data is sent only if it has been changed, if the object does not move - the data is not updated.

The script is not perfect, for example in the current version the script tracks any change (position, rotation, scale) and at any change of even 1 parameter it synchronizes all other parameters too
If you want, you can finalize it yourself
But if you need a quick solution, I think this script will be perfect for you.

[https://github.com/Rybiscom/multiplayer_transform_synchronizer](url)

**Comment by pennyloafers** [comment]
> It would be great to see something like this implemented. It's really quite crucial for games that require smooth movement over a network (which seems to be most multiplayer games these days).
> 
> The MultiplayerSynchronizer node is amazing at the moment, but something like what is described above would really help take it to the next level.
> 
> Would be good to see this proposal opened up again.

I have a proto type here https://github.com/pennyloafers/godot-branched-multiplayer

**Comment by 2585455437** [comment]
Is there any progress? Will this be implemented in 4.x or 5.x?

**Comment by Calinou** [comment]
> Is there any progress? Will this be implemented in 4.x or 5.x?

To my knowledge, nobody is currently working on implementing this. Since this can be implemented without breaking compatibility, it doesn't necessarily need to be for 5.x.

**Comment by ThanhTuNguyen** [comment]
I hope they will implement this soon. I am currently developing a game that heavily depends on co-op and multiplayer. However, this lack of Synchronization functions could hinder my game's progress, and it is too far to achieve a solid gameplay experience. This gives me too much worry when I start this project with Godot, making me think a lot about my decision. I can implement my solutions, but it will have risks; if there is native support, this dilemma will somehow be resolved in my mind. For me, Synchronization is a big step to make Godot out of indie game territory

**Comment by pennyloafers** [comment]
> I hope they will implement this soon. I am currently developing a game that heavily depends on co-op and multiplayer. However, this lack of Synchronization functions could hinder my game's progress, and it is too far to achieve a solid gameplay experience. This gives me too much worry when I start this project with Godot, making me think a lot about my decision. I can implement my solutions, but it will have risks; if there is native support, this dilemma will somehow be resolved in my mind. For me, Synchronization is a big step to make Godot out of indie game territory

There are existing [solutions](https://github.com/foxssake/netfox) out there. The main hurdle i see is that this feature may not be flexible for all types of games and needs to be performant and customizable, Godot should remain a general purpose engine.

**Comment by Eaglenait** [comment]
While netfox is nice. A native implementation would mean official support and better usability outside of gdscript
