### ISSUE TITLE
GDScript - Allow deleting variables.

### ISSUE THREAD

**Issue by Peter-Crawley** [godotengine/godot-proposals#731]
**Describe the project you are working on:** My game

**Describe the problem or limitation you are having in your project:** I can't delete variables.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** I will be able to delete variables.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Add a way to delete variables.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Functions like free() don't work on integers, strings, etc.

**Is there a reason why this should be core and not an add-on in the asset library?:** Because I should be able to delete variables without downloading something.

**Comment by Peter-Crawley** [comment]
I know this seems like a low effort request... but this is something so simple, there is not much to say about it.

**Comment by Xrayez** [comment]
Actually I think there's a lot of ways to interpret your request.

Built-in datatypes are generally not something which can be freed in GDScript. Resetting the state of those is what I think you refer as "deleting". I guess it's safe to say that most built-in types can be initialized to "zero":

```gdscript
var i = 10
i = 0

var s = "text"
s = ""

var d = {"key" : "value"}
d.clear()
```

If you put "variables" into an array, you could probably expect that when the array goes out of scope, those values will be deleted, too:

```gdscript
func some_func():
    var a = [0, 1, 2]
    # `a` is not returned and never used, the array and all the data is freed (hopefully!)
```

I'm not sure about specific internals. Perhaps if you assign `null` to each variable, they might be able to be freed that way (especially when we talk about `Reference` objects which are automatically freed when nothing points to it).

When I look at the engine internals regarding `Variant` implementation (datatype used for transportation of data and for the purpose of scripting), there's a `clear` method which is defined for some datatypes:

https://github.com/godotengine/godot/blob/495b28765d03aa9459bc312ebba190ec208979e7/core/variant.cpp#L1431-L1547

As you see, some comments already suggest that clearing some datatypes is not needed because they don't allocate any memory. For the rest, there's a `zero` method:

https://github.com/godotengine/godot/blob/495b28765d03aa9459bc312ebba190ec208979e7/core/variant.cpp#L1412-L1429

Do you suggest that those should be exposed to script somehow?

If you talk about deleting variables on the level of script (like literally removing members from script), yeah I think it's not possible to do at run-time, but I'm not sure why would you want to do this in the first place.
