### ISSUE TITLE
Android Plugins With C#

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot-proposals#733]
**Describe the project you are working on:**
Working on  a mobile game , intended for android .
I like the way Android plugins system became until the last release version of godot 3.2.2beta1

**Describe the problem or limitation you are having in your project:**
Dealing with C# as a main scripting language and using plugins with Java language .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Since exporting project made by C# as a main script to android is possible , 
it would be great if creating C# android Plugins is possible too .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Creating C# android module and use the module `.dll` file in the game project .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
New plugin system with c#

**Is there a reason why this should be core and not an add-on in the asset library?:**
main idea is to be able to create C# android plugins

**Comment by m4gr3d** [comment]
@MrZak-dev Platform plugins need to be written in a language supported by the platform. Android doesn't natively support C#, hence an Android plugins written in C# is not possible at the moment.

For example, even Unity's Android plugins require at least the use of C/C++ or Java via jni in order to interact with the underlying Android platform's APIs.

@Calinou I don't have edit access, can you close this proposal based on my above description. Thanks!

**Comment by neikeq** [comment]
The only way to support this would be by using Xamarin.Android which Godot does not use right now. Let's wait for .NET 5.0 and see how things are with the new net-android target. If it still depends on Xamarin.Android we will have to reconsider whether we should use that instead.
