### ISSUE TITLE
Add "Copy Absolute Path" to filesystem folders

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#7521]
### Describe the project you are working on

A game using sprites.

### Describe the problem or limitation you are having in your project

I often need to use some path in an external tool, e.g. when saving a new image or copying multiple files. The only way to obtain such path is to open a folder in file manager and copy the path from address bar.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be convenient if we had an option to copy absolute path of a folder, so I can just paste it in GIMP or whatever program and instantly navigate where I want.
![image](https://github.com/godotengine/godot-proposals/assets/2223172/796ae785-c4a7-4e33-b853-39a95c2b0ead)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new option would be the same as Copy Path, but with `ProjectSettings.globalize_path()`. I think it should appear only for folders as that's where it's most useful (for my use-case at least).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really. It involves some hacking.

### Is there a reason why this should be core and not an add-on in the asset library?

It's difficult to make as an addon.

**Comment by Mickeon** [comment]
I don't necessarily disagree with the proposal, but the right-click menu is getting quite cluttered (again) with all of these options

**Comment by tokengamedev** [comment]
I disagree with this proposal as absolute path is not required in Godot. Moreover, this option is already available in most OS file managers.

**Comment by KoBeWi** [comment]
> I disagree with this proposal as absolute path is not required in Godot.

Within Godot, yes. But when making a game you need to use all sorts of third-party apps and they require absolute paths.

> Moreover, this option is already available in most OS file managers.

But you need to open folder in file manager first. Having it available directly in Godot saves time and some clicks.

**Comment by tokengamedev** [comment]
I understand what you are saying, I am not sure how many people directly edit assets from Godot project folder. I myself have a buffer folder to edit assets and then push/copy it to Godot project folder. I do not do it directly because of multiple reasons like accidental duplicate files, naming conventions and many more reasons.

**Comment by KoBeWi** [comment]
> There should probably be command menu with search

It already exists. Editor -> Command Palette...

**Comment by Krigu** [comment]
I mostly require the absolute path to export assets from third-party apps to the godot project. Right now i right-click on the folder in godot, open the folder in the file manager and copy the path from the status bar.  As this flow is a bit cumbersome, I would love to have this proposal implemented in the engine as described and could possible create a PR for it. 

According to the [proposal workflow](https://github.com/godotengine/godot-proposals) a core commiter must approve the feature before it is considered ready to implement. Since I'm not to familiar with the process and this proposal has been opened a couple months ago, what can I do to move this proposal along and start implementing it?

**Comment by KoBeWi** [comment]
So far the proposal has some support and not much opposition, so feel free to open a PR. The final decision is usually made when the PR is merged or rejected.
