### ISSUE TITLE
Add Mesh Space Rotation Blend to AnimationTree Blend2

### ISSUE THREAD

**Issue by eddieataberk** [godotengine/godot-proposals#7579]
### Describe the project you are working on

A game with complex animations

### Describe the problem or limitation you are having in your project

In our game, we use Blend2 to have different weapon animations for the upper body while using the same lower-body locomotion animations. But a big problem is currently Blend2 blending rotations based on parent bone space. This causes problems such as rotation of the pelvis affecting the rest of the body while moving, and causing aim offsets to swivel left and right. In Unreal Engine. There is a Mesh Space Rotation Blend checkbox on Layered Blend Per Bone. If checked bone location follows parent bone space but rotations will always be based on mesh space. A similar feature would greatly improve Godot's animation system.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It adds Mesh Space Rotation Blend to Blend2 node properties.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/48696693/a0ecf040-7fa1-4f46-9d00-356875cb284e)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is about the core animation system.

**Comment by fire** [comment]
@TokageItLab thoughts?

**Comment by TokageItLab** [comment]
I'm not sure what the mesh space indicates, but probably a combination of Add2 and Sub2 should be sufficient for what you want. See also https://github.com/godotengine/godot/pull/76616.

**Comment by TokageItLab** [comment]
If you simply want to override blend calculation to use the global rotation, you can use the virtual method `_post_process_key_value()` as a global retarget in https://github.com/TokageItLab/realtime_retarget.

**Comment by eddieataberk** [comment]
> If you simply want to override blend calculation to use the global rotation, you can use the virtual method `_post_process_key_value()` like a global retarget in https://github.com/TokageItLab/realtime_retarget as example.

Yea, it seems this module can be quite useful. I didn't even know it existed. Thank you!

**Comment by kstanki2** [comment]
> If you simply want to override blend calculation to use the global rotation, you can use the virtual method `_post_process_key_value()` like a global retarget in https://github.com/TokageItLab/realtime_retarget as example.

@TokageItLab @eddieataberk  can you guys go into a little more detail on how to achieve this with overriding _post_process_key_value()? There isn't much documentation for it and I'm not sure how to use it

I'm trying to solve the same problem described in OP- I have separate animations for legs vs. torso and I blend them using a blend2d, with filtering enabled for the corresponding bones so the torso animations only apply from the spine up, and the legs from the hips down. But it seems the rotation of the torso animations is always affected by the legs/hips, so if the current legs animation rotates the hips then the torso follows suit- my goal is to blend them in such a way that the torso anims play as if the hips are facing forward. Then for example a character can strafe around while swinging a sword, and the rotation of the swing animation is always the character's forward direction instead of being affected by the hips.

I tried solving this with the (deprecated) SkeletonIK3D system by forcing the spine to always face forward, hoping that the other torso bones on top of it would animate in that direction- but it seems the IK only affects the bones in the chain and not their children

**Comment by Riordan-DC** [comment]
> > If you simply want to override blend calculation to use the global rotation, you can use the virtual method `_post_process_key_value()` like a global retarget in https://github.com/TokageItLab/realtime_retarget as example.
> 
> [@TokageItLab](https://github.com/TokageItLab) [@eddieataberk](https://github.com/eddieataberk) can you guys go into a little more detail on how to achieve this with overriding _post_process_key_value()? There isn't much documentation for it and I'm not sure how to use it
> 
> I'm trying to solve the same problem described in OP- I have separate animations for legs vs. torso and I blend them using a blend2d, with filtering enabled for the corresponding bones so the torso animations only apply from the spine up, and the legs from the hips down. But it seems the rotation of the torso animations is always affected by the legs/hips, so if the current legs animation rotates the hips then the torso follows suit- my goal is to blend them in such a way that the torso anims play as if the hips are facing forward. Then for example a character can strafe around while swinging a sword, and the rotation of the swing animation is always the character's forward direction instead of being affected by the hips.
> 
> I tried solving this with the (deprecated) SkeletonIK3D system by forcing the spine to always face forward, hoping that the other torso bones on top of it would animate in that direction- but it seems the IK only affects the bones in the chain and not their children

I solved it like this but performance sucks because it runs for every single key frame. Thats a lot of number crunching.

```
@tool
extends AnimationTree

@export var worldspace_anims: PackedStringArray = []
@export var bone_name: String = "Spine"
@export var enabled: bool = true

# What does this do? 
# Any animation that ends with sweep will have its Spine rotation applied in global space
# Result: Upper body poses will remain valid despite low body rotation
# NOTE: For this to work there needs to be zero rotation on the Spine parent (Hips)

var skeleton: Skeleton3D = null
var bone_id: int = -1

func _post_process_key_value(animation: Animation, track: int, value: Variant, object_id: int, object_sub_idx: int) -> Variant:
	# NOTE: In the CPP this processing is always done so we also have to do it here
	match animation.track_get_type(track):
		Animation.TYPE_POSITION_3D:
			if object_sub_idx >= 0:
				if skeleton == null:
					var obj: Skeleton3D = instance_from_id(object_id) as Skeleton3D
					if obj:
						skeleton = obj
			
				if skeleton:
					return Vector3(value) * skeleton.get_motion_scale()
			return value
	
	if bone_id == -1:
		bone_id = skeleton.find_bone(bone_name)
	
	if object_sub_idx == bone_id:
		if enabled and animation.resource_name.ends_with("sweep") or worldspace_anims.has(animation.resource_name):
			var track_type: Animation.TrackType = animation.track_get_type(track)
			
			if track_type == Animation.TrackType.TYPE_ROTATION_3D:
				if skeleton == null:
					var obj: Skeleton3D = instance_from_id(object_id) as Skeleton3D
					if obj:
						skeleton = obj
					
					var parent_pose: Quaternion = skeleton.get_bone_pose(skeleton.get_bone_parent(object_sub_idx)).basis.get_rotation_quaternion()
					var curr_rot: Quaternion = value
					value = parent_pose.inverse() * curr_rot
			
	return value
```

In this example I am only making a single bone on a subset of animations ending with "sweep" (The single bone is the spine, I dont want the upper body inheriting the hips rotation).
