### ISSUE TITLE
Implement a trait/mixin system and combine it with groups

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [godotengine/godot-proposals#758]
**Describe the project you are working on:**

A landscape-visualization software: https://github.com/boku-ilen/landscapelab. It uses geo-data to dynamically create a world. Having the right geo-data every place on the world can be mimiced. There is also VR-features which in the near future will be extended.

**Describe the problem or limitation you are having in your project:**

As our project get's huger every week, sometimes it is really hard to keep an overview. Inheritance can cause head-aches with projects of this size, also (thankfully) inheritance is relatively limited in godot. A trait-system like the one in [rust](https://doc.rust-lang.org/reference/types/trait-object.html) could be the perfect workaround. 
Currently we have the problem that the whole visualization that is happening should get capsulated and work as a child-scene of something else to possible have more than one visualization at the same time, or for example render the world on a table. Sadly we used a lot of ``global_transform`` which limits or progress.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

As mentioned before, a trait system could be very helpful reducing inheritance head-aches and at the same time could help the programming paradigm of DRY (don't repeat yourself). [Rust](https://doc.rust-lang.org/reference/types/trait-object.html) offers a way to implement traits for a class, i think one could greatly combine a similar system with groups.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Being able to add nodes to a group in the editor helps reducing programming work and scripts. My idea would be to be able to create a new script and add it to a godot group. Every node that is added in this group will automatically implement this trait as well. As gdscript works duck typed and is not really compareable to rust, i would not recommend using it the way rust does but much rather simply attaching the script to this node. 
Alternatively if the idea with groups is not liked, i would recommend a system like the one in python: https://py3traits.readthedocs.io/en/latest/readme.html. Traits could then easily be added in the ready function in godot. 

For my stated problem i would imagine something like this:
```
extends Spatial


var relative_transform: Transform setget set_relative_transform, get_relative_transform
var relation_node: Spatial = null


func set_relative_transform(t):
	assert(relation_node != null)
	
	relative_transform = t
	global_transform = relation_node.transform * t


func get_relative_transform():
	assert(relation_node != null)
	
	var node = self
	var t = transform
	
	while node != relation_node:
		node = node.get_parent()
		t *= node.transform
	
	return t
```

It should be automatically added and i can simply call for ``node.relative_transform = x`` just the way i would do it with global_transform

The scripts would be attached somehow like this: 
![grafik](https://user-images.githubusercontent.com/33001106/80409487-44112600-88c9-11ea-8120-2752c2558757.png) 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Well kind of yes to be honest, probably the closest to this is inheritance. However, especially as multiple inheritance is not allowed, one is kind of limited in godot. Having a superclass you want many nodes to inherit, it could happen, that it already is an inheriting node. Also, when combining it with groups it could be really helpful with reducing scripts and other overhead.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I honestly think it would be really challenging to implement something like this. Having the insights from the core developers would probably be helpful when doing this.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/23101.

**Comment by willnationsdev** [comment]
Also related to godotengine/godot#24262.

**Comment by willnationsdev** [comment]
I'm not really sure if it even *is* possible to make scripted traits dependent on groups without breaking OOP best practices pretty horribly. To have a script support traits, you either need the scripting language to implement support for recognizing them, or you need the Object/Script system in core to handle the entire delegation. However, groups are a thing that only exist in Nodes whereas Scripts are things that all Objects, even non-Node ones, have. And it would be very strange to have the logic of a Node's script suddenly change from the way any other Object would respond to such a method call just because the Node is a member of a group. This would mean either overriding methods from Object inside Node to have custom behavior accommodating group-traits or modifying Object's internals to provide a hook for an inherited class to affect its existing method's behavior. Neither of these solutions sounds appealing to me.

If we avoided these problems by just defining new details in the Script interface and having each scripting language handle traits themselves, it would lead to a bunch of custom core code being written simply to accommodate traits *possibly* being added to *some* languages in the future. This is also something that doesn't appeal to Godot's development standards.

As such, the only way I can see to implement traits *at all* is to do it on a per-language basis, with no engine or editor awareness of traits existing.

@MathiasBaumgartinger What do you think? Would GDScript Trait support be enough to satisfy your needs?

**Comment by vnen** [comment]
It's not feasible to use groups for this, simply because a script cannot know (at compile time) that it belongs to a particular group, especially because a group is a property of an *instance* while the script is a *class*. Also, the same script can be attached to multiple nodes which in turn can have different groups, making all possibles paths very complex and prone to fail.

I do have an idea for a trait system, but it would be implemented only on the script side, not relying on the editor or groups in any way.

**Comment by betalars** [comment]
I'd like to express my support for this proposal, mention a new use-case and also propose a possible implementation, where we might get the benefits of a trait-system without loosing the general nature of dynamic script languages:

**The Use case**
I'm building a scientific Research application in Godot, that is supposed to be modular: I want researchers to easily implement their own variants of scripts I've implemented so they may tailor the behavior of my application to their individual needs.

 But it's not trivial, because I need to do tons of calls to different elements. So I'm constantly running into runtime-errors, because certain scripts don't have the functions I expect and this is becoming more and more of a hassle. Also it makes my documentation somewhat messy.

**How to implement it**
I actually would not implement traits in a manner, that'd prevent your code from being compiled (similar to, what rust is doing), because this kind of goes against the spirit of scripting languages. So this is my proposed implementation:

1. **Define Traits in Project Settings.**
I'd personally just add a new Tab for the Project settings window, where you have a list of all the traits, you've defined in your project as well as all the functions and variables, they "force"
2. **Templates**
Godot Script can generate from a template, when you make a new Script. So I'd like to see an option to choose inheriting traits so your new script file already comes with each needed empty function body or variable declaration.
The function body should contain a keyword similar to `pass`, that raises a missing-trait error when reached during runtime (see point 8)
3. **Compliance overview**
(I'd probably put it with the project settings) it's an overview of all the scripts, that use a trait and, how many of them seem to fully implement it.
4. **Editor Warnings**
Put some kind of Editor warning, that informs a developer, if a script is missing features of a certain trait...
5. **Export Hints**
When exporting a variable, developers should be able to force one or traits similar to, how you can force a file format using `export(String, FILE, "*.json") var config`
6. **Implement traits for function heads**
... so you can define a function is expecting/returning an object of a certain trait ...
7. **Implement trait-checks**
... so you can check, if an object is of a specific trait.
8. **Implement a runtime-error for not properly implemented traits**
Okay this is kind of the core idea of my "dynamic" trait system:
If some scripts in your projects don't fully implement all the traits, they declared to have, you can still run your project.
But as soon as one of these not properly implemented scripts get's called with a function they should have, but don't ... you get a special error informing you about, how you didn't properly implement that trait.
Same goes for invalid return types or missing attributes.

I think this way, you kind of get all the benefits of having a trait-system but without breaking the dynamic nature of godot-script:
It still runs, if you have not properly implemented your traits, but it will raise dedicated errors and it will also give you proper feedback on, how well you've implemented a trait in editor.

**Comment by patrick-motard** [comment]
> 
> 
> It's not feasible to use groups for this, simply because a script cannot know (at compile time) that it belongs to a particular group, especially because a group is a property of an _instance_ while the script is a _class_. Also, the same script can be attached to multiple nodes which in turn can have different groups, making all possibles paths very complex and prone to fail.
> 
> I do have an idea for a trait system, but it would be implemented only on the script side, not relying on the editor or groups in any way.

@vnen Is there a proposal for this that we can begin to chip away at?

**Comment by vnen** [comment]
> @vnen Is there a proposal for this that we can begin to chip away at? Possibly part of the 4.0 re-write?

No, there's not a proposal from my side (though I do have some ideas), much less atual implementation. I don't think it will be done for 4.0, only for 4.1 or later.

I do intend to open proposals for the planned GDScript features soon.

**Comment by Gnumaru** [comment]
I think some kind of trait/mixin system would be great. Please let me try to contribute something to the discussion.

The core problem solved with php traits/python mixins, with inheritance (and multiple inheritance), with 'include' preprocessor directives and so on is, in the more general sense possible, 'text reuse'. One just wants some way, and preferably a pretty way, of acting 'as if I have wrote that text in this place'. One could solve virtually any reuse problem by adopting a preprocessor workflow. Instead of writing gdscript directly, you write gnu m4 macros, or c preprocessor macros, or microsoft's t4 templates, jinja templates, anything, wich you routinely run and convert to actual gdscript files. It is a bit cumbersome, you lose the ability of writing code and seeing the changes at runtime, but it works around and solve virtually any code reuse and composition problem you might have.

Being the preprocess phase something separate from the 'compile phase', you do not have the problem you usually have in C of having to debug some code generated by a series o convoluted preprocessor macros, because godot will be debugging the preprocessor output, not the preprocessor input. And it would not need work hours from the godot team or the community at all, just your solo work.

That said, it is easier on the programmer to have a trait system and not have to come up with this kind of solutions yourself. I use myself a preprocess step to include templates inside gdscript and emulate traits, but I'm just getting tired of it by now =S.

To have code reuse alternatives to inheritance, traits is one answer (as well as preprocessor include steps). But there are other alternatives.

You could user for example C# style extension methods (as well as golang methods with receiver argument). Extension methods make very pretty code because you call them as if they where instance methods, just as you would with a trait. They are not able to 'inject fields/properties' in the class as a trait would but this can be partially (injecting fields only, not properties) worked around by implementing _get and _set and delegating accesses to undeclared fields to the object's meta dictionary. If we wanted to make things easier to extension methods, we could with two changes: the first would be defaulting to get/set in the metadict any attempt to access an undeclared field. The other would be to not raise any error when trying to get un-existing properties of a dictionary, but return null instead like in javascript (maybe print a warning in the console). With this the extension methods could try to get and set anything in any object an so the 'field injection' feature of traits would be unnecessary.

Extension methods could be implemented with a singleton (only one) defined in the project configuration, so this would be project dependent, would not work with standalone scripts. Since it would be only one singleton, there would be name conflicts only with the class instance and the singleton, but the class method would take priority.

Or it could be implemented with a new keyword like 'use' followed by a comma (or space) separated list of singleton names, class names or load('res://') calls (so this would be resolved at init time). This way you could write several utility libraries and use only the ones you want, but function name conflicts could occur. This could be resolved using the 'use' order, the engine would search the undefined method name in the objects mentioned in the use statement on the order they are written and would call the first it could find.

All that said, I still prefer a proper traits system over extension methods since it would be nicer for people wanting to make more strongly typed code and easier to associate a trait method with the data it operates on, since this info would be hidden in the extension methods, one would have to actually read the code to know what fields/properties are being accessed

**Comment by Gnumaru** [comment]
I got another alternative idea for a trait system. It would be entirely resolved at runtime.

The Object class (the c++ one, not the exposed gdscript API) would need to have a new field to store a list of objects. There would be three new methods exposed to gdscript named register_trait, unregister_trait and pop_trait. register_trait would take a single object as a parameter and would just append the object to the beggining (not the end) of the list if it is not already there. unregister_trait would take a single object as a parameter and would search for that object instance and remove it from the list. pop_trait would remove the most recently added object from the list, which is the first element of the list.

Upon registering one or more objects, you now have a resolution chain for resolving member accesses (property, method signal, const, anything). When trying to access a member using the self keyword (without self you would get parser errors for accessing undefined members) the engine would search for the member in the current object. If it cannot find it, it would search the first object in the resolution chain (which was explicitly added via register_trait). If not found, try the second and so on until you reach the end of the list. If the member cannot be found neither in the current object nor in any of the resolution chain objects, only then a runtime error for accesing an undefined member would be raised.

If More than one object in the chain have the desired property, than the objects in the beginning of the list will shadow/override the others. This is why register_trait would add to the beggining of the list, not the end, because anytime you can override the resolution behavior by adding a new object to the chain

Optionally (this would be a bigger change) 'self' itself would be at the end of the resolution chain, not the start. This ways you can always override the current objects behavior by registering new traits. To avoid confusion we could create a new keyword called 'chain' or 'us' ('us' would be funny) that would first try to resolve through the chain and, if it cant, try the current object at the end.

Another alternative would be to get rid of the chain array in the object class and use the direct children of the node for access resolution. I think this would be a worse solution. This would be simpler but would force you to use traits only with nodes, classes not inheriting from node would not have access to the feature.

Personally, I would prefer not having to use self, but make the trait chain be used for every access. This would be easier to use but would be the biggest change with most impact in current users codebases. Using self would not change current codebases, and using 'us' would need changes in the parser.

Please note that the behavior mentioned above can already be implemented by the user in gdscript alone, you can have a 'TraitsEnabled' super class, make all your classes inherit from it, you store your objects list in the super class, create the register and unregister methods there, create the 'us' property and resolve the chain access in the getter and setter methods for the us property. But having this in the core engine would allow users to have access to the feature without changing the inheritance hierarchy in their codebases, and making the access resolution in C++ land would probably be faster than in gdscript land. Also, being part of the core engine gives access to all users despite the scripting language they are using, be it c++, gdscript, clr languages(C# etc), or the python and javascript pluggins/modules I have seen out there.

**Comment by Gnumaru** [comment]
'we' would be an even funnier keyword.
var v = we.get_this()
we.set_that(null)
we.make_anything("!")

**Comment by Gnumaru** [comment]
Oh... right... About that "can be implemented in gdscript alone". I forgot that if you inherit from a base script you cannot anymore inherit from any other script or builtin type, like RigidBody2D. This should not be a problem for member access since 'self' is an actual RigidBody2D and member accesses attempts from self (or 'we') would succeed in finding the desired members at runtime (but access without self would result in parse errors just as usual). You can even override virtual methods present in the built-in node type, even if it is not in the inheritance chain, like _integrate_forces. I have just tested it out, a script inheriting from Node that implements a 'func _integrate_forces(state):' do have it called at runtime when attached to a RigidBody2D.

**Comment by cgbeutler** [comment]
Extension methods have been mentioned a few times here. Not sure they are really the same and belong as a part of this proposal. The nicest thing about extension methods is that they can be written for _anything_, even primitive types. It would be really nice to write and call my `vec2.clamp_to_rect( rect2 )` just so. Most of this discussion seems focused on Object-derived stuff and doing mixin stuffs or using meta or script objects to hold/do stuff, but that would leave out all the other variant tyeps.

So, to get to the point, I may open a proposal for https://github.com/godotengine/godot/issues/15586 (GDScript Extension Methods) unless someone feels strongly that it should be discussed here instead.

**Comment by willnationsdev** [comment]
@cgbeutler Opening a proposal for that sounds like a good idea to me. I should also mention that my recent proposal for Struct Variants #2816 incorporates the use of extension methods too, albeit in a different way.

**Comment by Xrayez** [comment]
> The Object class (the c++ one, not the exposed gdscript API) would need to have a new field to store a list of objects. There would be three new methods exposed to gdscript named register_trait, unregister_trait and pop_trait. register_trait would take a single object as a parameter and would just append the object to the beggining (not the end) of the list if it is not already there. unregister_trait would take a single object as a parameter and would search for that object instance and remove it from the list. pop_trait would remove the most recently added object from the list, which is the first element of the list.

This sounds like `MultiScript` support which was part of earlier versions of Godot, but then it was removed, then again added, then removed again: godotengine/godot#8718.

Now, I've recognized that `MultiScript` is actually sort of like cross-language mixins, and I did go as far as to resurrect the feature in [Goost](https://goostengine.github.io/) using Godot 3.3 again... See goostengine/goost#92.

> Oh... right... About that "can be implemented in gdscript alone". I forgot that if you inherit from a base script you cannot anymore inherit from any other script or builtin type, like RigidBody2D. This should not be a problem for member access since 'self' is an actual RigidBody2D and member accesses attempts from self (or 'we') would succeed in finding the desired members at runtime (but access without self would result in parse errors just as usual).

Indeed, if I understand correctly, the `self` you refer to is the `owner` property I've exposed in dummy `Mixin` classes which are basically instantiated per script, since Godot's `Object` can only have one script per node. If you attempt to use built-in methods, GDScript will yell at you at parse time saying the method does not exist. Yet if you call the same method from within `owner` property, this prevent the parse error.

Interestingly, if you try to call built-in errors in other languages like `VisualScript`, then you don't get parse errors, and that actually makes it possible to avoid the usage of `owner` property, just because `VisualScript` is not yet smart enough to yell at you like GDScript does. 😄

**Comment by ivalylo** [comment]
I was thinking about similar problem, and I fail to see, how this is better then using composition approach. Like this:
```
class_name RelativeComp extends Resource

var relative_transform: Transform setget set_relative_transform, get_relative_transform
var relation_node: Spatial = null
var owner: Spatial

func _init(p_owner)
	owner = p_owner


func set_relative_transform(t):
	assert(relation_node != null)
	
	relative_transform = t
	owner.global_transform = relation_node.transform * t


func get_relative_transform():
	assert(relation_node != null)
	
	var node = self
	var t = transform
	
	while node != relation_node:
		node = node.get_parent()
		t *= node.transform
	
	return t
```

```
extends Spatial

var relative_comp: RelativeComp

func _init(tm):
	relative_comp = RelativeComp.new(self)
	relative_comp.relative_transform = tm

```

Yes, you must manually access the component with _node.relative_comp.relative_transform_ (can rename it to _relative_comp.transfrom_), but it makes it more obvious how it is defined. If you write just _node.relative_transform_, you no longer have information where exactly _relative_transform_ is coming from. It's kind of cool to have it automatically attached to your script, but at the same time, it's also kind of hidden. If you want to check if the interface is supported, you can use standard naming convention:

```
if node.get("relative_comp"): 
```
That part is a bit iffy, since there isn't an interface to enforce it. But Godot is a dynamic language that uses duck typing, so it is what is...

The issue I have with inheritance (i.e. the need for the component to inherit from particular class) is two fold:
  * it will never use the whole class you pass. In a strongly typed languages, you will most likely create yet another minimal sub-interface to derive from. Otherwise, you are limited to where you can use this component.
  * in a dynamic language, you don't even define an interfaces, so what is the point of the component to know what kind of object to work on? In your example, it just needs to set property called _global_transform_. It doesn't matter at all if the class inherits from Spatial. Just need a property named that way. You can even make "global_transform" a string parameter, so it can be called in any way you like. This makes interacting with different objects so much easier. A component can know absolutely nothing about the base class, and just use duck typing as implicit interface.

**Comment by Zireael07** [comment]
Mixins ARE composition, not inheritance.

**Comment by ivalylo** [comment]
@Zireael07 Please read the topic...

The example in this issue is based on inheritance... The mixin in that case must have appropriate parent in order to be plugged into another source file. godotengine/godot#23101 was also very much based on inheritance. While mixins can be implemented in different ways, they very much act like inheritance. And are commonly used to implement multiple inheritance. Here is definition from Wikipedia:

"A mixin class acts as the parent class, containing the desired functionality. "

You can also read https://stackoverflow.com/questions/860245/mixin-vs-inheritance

When you have a dynamic language, you always can "override" the mixin methods, so again - a lot like of inheritance.

Composition:

"Object composition is about combining objects within compound objects, and at the same time, ensuring the encapsulation of each object by using their well-defined interface without visibility of their internals."

"Object composition may also be about a group of multiple related objects, such as a set or a sequence of objects"

I really mean just having container object that creates different independent sub-objects (similar to the Node tree). They do not need to know the base object or about each other (actually that is the idea - the less they know, the better). You don't alter the behavior of the main object in non obvious ways. In the given example:

`node.relative_transform = x` alters the behavior of the `node` object directly, by inserting `relative_transform` just like inheritance does. 

I was going to implement some sort of mixin system by myself. But after some consideration, IMO this whole line of thinking is bogus, and based on experience with static languages. People tend to create these huge self-contained classes. In a static language, this is really the easier way, otherwise you must write and manage a lot of interfaces. In Godot, the node based system works well since GDScript is dynamic. However, creating node for every script is bad, and this was fixed. So I think the workflow currently is most optimal. 

I looked at MultiScript also, and its appeal is a bit different - mixing code from different languages. In bigger teams, some may work in C++, others GDScript, designers - Visual Script... This feature can really be handy, if you find how to use it properly... It's not composition either, just breaking up single class into multiple source files. This allows you to combine them freely, but also creates a mess... There is no "main class", but at the same time there is single node. So which file handles the node methods? This is why it was removed. But in any case, just collecting random code to construct a class, can easily end up badly. There is no way to predict how the code will interact with each other when combined, and working on the same object. So, very powerful, but also potentially bad to use. It's good to have as a plugin though...

**Comment by willnationsdev** [comment]
> > Mixins ARE composition, not inheritance
> > 
> Please read the topic...
> 
> While mixins can be implemented in different ways, they very much act like inheritance. And are commonly used to implement multiple inheritance.

This seems to be getting into semantics too much. Just having a child node or reference var that you attach and use is not equivalent specifically because a Trait is capable of making references to data that exists outside of the class information available to the trait. That is a use case that cannot be replicated with traditional composition.

    # my_trait.gd
    func do_something():
        print(some_data)

If something *uses* `my_trait`, then any of them can call `do_something()`. But it is also required that they have a member variable `some_data` defined (via duck-typing), otherwise there would be a parse/compilation error in the script. If, say, you had 5 or 6 methods or variables of this nature, and you wanted to replicate the outer interface across many different types, then using traditional composition would you mean a boilerplate of 5 or 6 duplicated methods that make calls to the internal managed instance. That's the kind of thing you'd want to avoid by using a trait so that all of that boilerplate code can be automated with a one-liner in each class that needs to have the same outer interface and implementation.

There is a very specific use case where traits are *incredibly* useful, so I don't think the concept should be discarded out of hand.

**Comment by Zireael07** [comment]
Bump. Making a procedural geometry tool for myself and running into problems that some sort of a mixin system would solve.

Any progress on this considering we're getting closer to 4.0?

**Comment by me2beats** [comment]
I don't get traits in gdscript at all. Need more traits examples.
For now I still think `includes` would be a clearer approach to extend class functionality like

```gdscript
module Module1

var a= 1

func func2():
  func3(a)

func func3():
  pass
```

```gdscript
extends Something
include Module1

func _ready():
  func2()
```

for example Python has `import` and not going to give it up.

**Comment by KiwwiPity** [comment]
> composition also can't help when I want to have export vars for example.

could explain this plz?

**Comment by me2beats** [comment]
I mean for example I want to have several export vars in the node.
Now I only can create(declare) them in one script or use inheritance.
Being able for example to include another script would solve the problem: I don't need to use inheritance, but still can reuse some common behaviors having them as a separate scripts, which can be included in other scripts.

**Comment by KiwwiPity** [comment]
this would imply to override stuff that have both scripts, by the last one that gets applied to the node (or the like)
then only the stuff kin the first script that isn't override by the second script, would end up applying.

the only alternative can think right now is of an additional script type `ComplementaryScript` (or whatever) that allow to add additional secondary scripts that doesn't inherit any node, to extend the normal script.

however who knows which caveats it would have. 
(one concern would be get access to stuff of the script that it extends and its node type members, from the complementary script)

**Comment by me2beats** [comment]
I had a proposal about partial classes https://github.com/godotengine/godot-proposals/issues/2410

I had to name it partial scripts I guess.
They said traits or even `include` would be better

**Comment by Zireael07** [comment]
Whatever it ends up being, it's still badly needed.

**Comment by KiwwiPity** [comment]
have read #2410
quite interesting
it looks like traits/mixins would bring most of the functionality:

- interfaces (abstractions + design by contract)
- partial class
- composition over inheritance
- include/import/module/package stuff
etc

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/6416.

**Comment by nonchip** [comment]
@Calinou which then also subsequently got locked. is there anywhere that's still relevant to this conversation (especially now we got the relatively useless `abstract` which is just a fancy `func _init(): assert(false)`)
