### ISSUE TITLE
Add support for multiple audio inputs at once

### ISSUE THREAD

**Issue by Faolan-Rad** [godotengine/godot-proposals#7613]
### Describe the project you are working on

Co-op VR Editor

This would be nice for people to stream other audio that is not just there voice.
This also is helpful for audio editor programs

### Describe the problem or limitation you are having in your project

I would like to have the ability to have an arbitrary amount of different mic inputs in use at one time

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a name field to Microphone stream where if it is null it uses the global microphone and if it is not null it uses that device

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Added field to Microphone stream

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only way to workaround it would be including mini audio or something and handling mic input myself 

### Is there a reason why this should be core and not an add-on in the asset library?

It is a enhancement to the existing microphone system

**Comment by szezjo** [comment]
Oh, it would be really great to see. I plan making a game where having multiple mics could be useful for multiplayer, but I'm worried it won't be possible in Godot, so I hope we will see such a functionality sometime soon.

**Comment by Calinou** [comment]
> Add a name field to Microphone stream where if it is null it uses the global microphone and if it is not null it uses that device

What do you mean by "global microphone"? I don't think OSes have such a concept out of the box. You may be using an option or external software to create a virtual audio input that sums all input sources together (like you can do for audio outputs), but this is different from something the OS would actually provide unconditionally.

Also, this will require breaking compatibility if we change the property to allow using multiple audio inputs at once (but not *all* of them), since we'll have to change the string property for a PackedStringArray.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2915.
