### ISSUE TITLE
Rename 'Control' to 'NodeUI'/'NodeGUI'

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-proposals#763]
Recently, the `Spatial` node was renamed to `Node3D`, as to match `Node2D` as one of the base nodes. Considering that Control is also a base node, I think it makes sense for it to follow the `Node*` naming. Specially since the name "Control" is not that intuitive as to what it does.

I propose either `NodeUI` or `NodeGUI`, with me being personally inclined to the former. They immediately convey that the node's function is related to UI/GUI manipulation.

**Comment by Zylann** [comment]
`NodeUI` looks a bit weird. For `Node3D` and `Node2D` it's understandable because they can't start with a number (convention not just seen in Godot) but `NodeUI`... eeh.
Maybe `UINode` or `GuiNode` would be better?
If we are going down the hill for all GUI nodes then some of those would get a much needed rename IMO, like ` Tree -> TreeView/UITree` or `GraphNode -> GraphEditNode/UIGraphNode`

**Comment by YeldhamDev** [comment]
I know there's a special reason for the "Node" part on those being on the start that does not apply here. But because the other two are named like that, it looks weird for the third one not to.

Also, I don't really see the need for adding "UI" to the other nodes.

**Comment by EricEzaM** [comment]
I think adding UI to other nodes isn't needed. I don't mind NodeUI but also don't mind the sound of something like 'Widget' (UE4 uses this). But then if it's just a rename for the sake of renaming (Control -> Widget) rather than for consistency (Control -> NodeUI).

Maybe it's ok for UI related nodes to have a different convention?

**Comment by groud** [comment]
I am not for this change because:
- From what I know Control is quite common to name GUI elements,
- Unlike a Node3D or a Node2D, a Control is not really a very generic, multi-purpose node,
- The Node3D rename made sense as most of the 3D nodes had a 2D counterpart, which is not the case at all for UI nodes. So using the NodeUI name may lead to confusion, as it would make some nodes having similar names for no reason.

**Comment by RabbitB** [comment]
@groud 
> From what I know Control is quite common to name GUI elements,

This is first and foremost why I'm against moving away from the Control naming scheme. `Control[s]` is how many UI frameworks commonly refer to their UI elements, and I think we lose a legitimate case for familiarity that makes migration from other platforms to Godot, easier for UI devs.

**Comment by mhilbrunner** [comment]
Have to agree that both 'Control' and 'Widget' are very commonly used like this (and úsed synonymously). Vote for letting this stay as-is. :)

**Comment by aaronfranke** [comment]
For 3D, having everything be renamed to end in 3D helps with consistency due to all of the 2D nodes ending in 2D already, as most nodes having alternate versions between 2D and 3D.

For Control nodes, there is only one version of each, so there is no suffix needed anywhere. "NodeUI" or "NodeGUI" would imply the existence of other nodes ending in "UI", which would be misleading. I think the current name of "Control" is already great and should be kept.

**Comment by Zylann** [comment]
> For Control nodes, there is only one version of each, so there is no suffix needed anywhere. "NodeUI" or "NodeGUI" would imply the existence of other nodes ending in "UI", which would be misleading

While the first reason mentionned at the beginning of this thread may not be the best or explanatory ("i.e 2D and 3D suffixes exist, let's do the same for everything"), I believe a better motivation (which is my own opinion) is that GUI nodes are components of a *family of nodes*. That assumes a lot of context. This goes in pair with what I said that `UI` should be a prefix and not a suffix. Indeed, When you find a class named `Tree`, `TreeItem`,  `Range`, `GraphNode` or `TextureRect`, do you immediately think about UI? Or do you think about: a tree data structre/terrain tree and its nodes, an simple min/max value type, a graph data structure for doing pathfinding, a sub-rectangle of a texture? Just by name, it's not obvious that they are actually full blown UI controls instead. Btw, those names are taken so should you want to use them, you have to name yours differently.

I (and maybe you) know most Godot nodes very well already so I don't mind much if they keep these names, I can tell them apart quickly after years of experience (same for 3D nodes btw!). But I don't know about other people with less experience.

**Comment by Calinou** [comment]
Closing due to lack of support – see the above discussion and reactions on OP.
