### ISSUE TITLE
Add `Array.min` and `Array.max` variations that return not only the value, but also the index

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot-proposals#7633]
### Describe the project you are working on

A 3D game

### Describe the problem or limitation you are having in your project

I need to calculate the closest node of kind X to the player. To do that, I first get all X nodes in a list with `get_children`. Then I create a list with all distances and use `Array.min` to find the closest. But then I have to make `Array.find` to find the index of that node in the corresponding list with all X nodes.

Note that this works if X nodes list and distances list follow the same order (expected if you create one from another).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement `Array.min` and `Array.max` variations that return not only the value, but also the index.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implement two new functions. Modifying existing ones breaks compatibility.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It might be possible, but no so efficient.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure, but when `Array.min`/`Array.max` find the corresponding value, the value index has to be somewhere in the algorithm, it is better to also return it, instead of making `Array.find`.

**Comment by Mickeon** [comment]
> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
> It might be possible, but no so efficient.

The method should not return both values at once. GDScript has no concept of tuples, so the closest thing would be an array of two elements. Judging by the statement above, the concern is performance, and this would not be worth it.

Especially because there are a bunch of ways you could write the same function in GDScript or other language, without losing too much on performance.

**Comment by acgc99** [comment]
Another option would be to return the index of the value, not the value itself.

> Especially because there are a bunch of ways you could write the same function in GDScript or other language, without losing too much on performance.

I agree that you could write your own function, but I still think that this feature is something to consider. I'm using a workaround to get the closest node to the player, using `Array.min` and then `Array.find`. I would be nice to skip the second step. I don't know how other users find the closest node to the player, but that is the way I found.

**Comment by Mickeon** [comment]
> Another option would be to return the index of the value, not the value itself.

Yeah, pretty much. It would need a pretty good name for it, too...

Here's an mocked-up example on how you could write them in GDScript.

```gdscript
# Get the index to the greatest value in the array:
var max = 0.0
var max_index = 0
for index in array.size():
	var value = array[index]
	if value > max:
		max = value
		max_index = index

# Get the index to the lowest value in the array:
var min = INF # Assuming the array contains numbers.
var min_index = 0
for index in array.size():
	var value = array[index]
	if value < min:
		min = value
		min_index = index
```

**Comment by AThousandShips** [comment]
I don't see this being a common enough need to justify adding it to core, as it is trivial to work around, further there's the possible confusion of the meaning of the minimum *index* when there's more than one copy of the minimum value.

**Comment by acgc99** [comment]
> I don't see this being a common enough need to justify adding it to core, as it is trivial to work around,

I use it to find the closest enemy to the player, a task that I think is common.

Consider also a tower defense game, where towers would attack the closest enemy that have entered in an area.

> further there's the possible confusion of the meaning of the minimum *index* when there's more than one copy of the minimum value.

`Array.find` also returns one index when there are duplicates. 

> Further I don't see this need as really making much sense as something that needs to be performant, so a workaround should be sufficient for most, if not all, of the people who *do* need this.

I guess that would depend on how often you call the function... I don't came up with an example here.

> Also this can be easily provided as a plugin via `GDExtension`, a method that takes an `Array` and returns either just the index or an array with the value and the index.

True... although beginners like me doesn't know it. Homework for me.

> You can also do it reasonably fast with:
> ```gdscript
> func _cmp_ind(acc, cur) -> Array:
> 	if acc.is_empty():
> 		return [cur, 0]
> 	elif cur < acc[0]:
> 		return [cur, acc[1] + 1]
> 	else:
> 		return acc
> 
> func min_index(arg: Array) -> Array:
> 	return arg.reduce(_cmp_ind, [])
> ```
> 
> Which returns an array holding the minimum value and the minimum index.

Nice :)

**Comment by AThousandShips** [comment]
> I guess that would depend on how often you call the function

I mean, sure, that's what I mean, that's what performance critical means

What I'm saying is that the fact that an alternative solution isn't fast isn't an argument in itself for adding something to core unless you can show that people both need it, and it has to be fast, we generally avoid adding new features to core because it is very easy to get into feature creep and bloat, so to justify adding them there needs to be really good arguments why.

What is needed is:
* Many people would benefit from this
* Many people would be negatively affected by having to do this themselves through code

For many cases you would instead benefit from keeping a sorted data storage, and adding new values where they belong, or sorting the array, having to scan through the *entire* storage every time you need the data isn't going to be fast

Instead having the array be sorted by distance, for example, and then add new elements where they belong using `bsearch` would solve that problem, you just need to look at the last element. And I think you might actually need a better way to solve your example issue than this, rather than needing this specific method

**Comment by acgc99** [comment]
I understand... I will try to figure out better ways to solve the problem and learn from your proposals in the meanwhile.

**Comment by jotaf98** [comment]
Finding the closest object, lowest health actor, most powerful upgrade, etc are common enough in any game that I think this is warranted.

Right now we can easily use map and lambdas to turn any objects array into the quantity of interest (distance, damage, etc).

But getting the max/min element suddenly ties this sort of code into knots, with imperative-style loops, or less-readable comparison functions (like @AThousandShips suggested).

Since there are `min/max` methods for Array, it does not seem too much to also have `argmin/argmax` (or `amin/amax`), returning a single index (just like `find`). And this very common operation would become a one-liner, like many other common and repeated operations in Godot.
