### ISSUE TITLE
Emits a signal when a new node is added into a group

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot-proposals#766]
**Describe the problem or limitation you are having in your project:**
I need to be notified when a node is added into a group, so I can put the node in a specific state.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If the `SceneTree` would emit a signal when a node is added into a group, I could be able to catch it and perform some operations on the node.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Simply add a new signal on the `SceneTree` and emits it when a new node is added into a group.
The signal name could be:
- node_grouped(StringName p_group, Node p_node)
- node_ungrouped(StringName p_group, Node p_node)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Add group is an engine feature, using a script doesn't allow me to emit a signal and so catch a grouping when it's grouped in the Editor.

**Comment by RabbitB** [comment]
I agree with your proposal and believe it would make runtime use of groups much more versatile regarding game design, but this can be [cludgily] implemented with an autoload and some due diligence when working with groups.

> Caveat: Code is completely untested. I just wrote it quickly here as an example.

```gdscript
extends Reference
class_name GroupHelper

signal node_grouped(group, node)
signal node_ungrouped(group, node)

func add_node_to_group(node: Node, group: String, persistent: bool = false) -> void:
    node.add_to_group(group, persistent)
    emit_signal("node_grouped", group, node)

func remove_node_from_group(node: Node, group: String) -> void:
    node.remove_from_group(group)
    emit_signal("node_ungrouped", group, node)
```

**Comment by AndreaCatania** [comment]
I evaluated this solution, but in this way the groups created in the editor doesn't emits any signal.

Also, any node should be aware of that class, making the grouping useless becouse I could even directly change the node status or add it in the array i need.

**Comment by RabbitB** [comment]
As these things tend to go, I ended up needing this exact functionality in my project, and while the earlier workaround is functional, it showed me the value in implementing this proposal. Adding new signals isn't too difficult, but I would like some insight into how others would expect this to work.

I already have the signals for SceneTree implemented; they emit whenever a node that's in the tree, is added or removed from a group. It's possible to get a reference to the tree and emit the signals even if they aren't part of the tree, but that feels like it would be unexpected behavior.

Especially unexpected because I'm also considering putting in a set of signals on Node itself. These signals would only emit if that specific node was added or removed from a group and would emit regardless of whether the node is in the tree.

As for the signals themselves, the signals for SceneTree are:
`node_added_to_group(node: Node, group: StringName)` and `node_removed_from_group(node: Node, group: StringName)`

If I add the signals for Node, I'm thinking they would be:
`added_to_group(group: StringName)` and `removed_from_group(group: StringName)`

If I add those signals, should I pass just the group name, or should I still pass along the node as well? On the one hand, you would be connecting to a specific node, so you should know what node is emitting the signal. But on the other hand, including the node allows you to connect multiple nodes to the same callback. Without it, you would be required to use different methods if you needed to know which node was emitting.

**Comment by YuriSizov** [comment]
We've discussed this in a proposal review meeting, and didn't reach a consensus whether there is a good case for the core change. It seems that most cases where adding to a group happens is fully within the user's control, so they can react to this change.

**Comment by robbertzzz** [comment]
I'd love to see this get implemented, because it would be a fix for many issues like #627 and #5466, both of which just want something simple to happen in response to a node being added to a group. I'm in a similar boat right now, where I have a singleton that needs to keep track of all nodes in a specific group in the scene tree, regardless of the currently loaded scene. All these groups are set in the editor rather than in code, so it would require a rework and a less designer-friendly approach (writing code rather than changing a setting in the editor) to make this work.

**Comment by LO-0116** [comment]
please add the signal, without knowing when the group is updated I am forced to create my own implementation of groups that is just a list of nodes kept in an autoloaded object with signals.

**Comment by dannyking** [comment]
I agree this would be a useful feature.

**Comment by Calinou** [comment]
@dannyking Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
