### ISSUE TITLE
A general documentation how to port on consoles.

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot-proposals#767]
**Describe the problem or limitation you are having in your project:**
"no one" knows how even to start to bring a game on a console on their own. The documentation gives no Help to help yourself.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The reasons are some legal stuff, which is totally understandable. But, what would be great is a documentation what steps would be necessary to do such an export yourself. What do I have to do after I got an SDKconsole from Nintendo/Sony/MS? How do I have to connect the correct parts in general without using actual licensed code? So I think there is some general Stuff all have in common like "make a folder with a c++ file", "put this into Godot as an export template" and so on. 
Cause no one really knows if it will take 5h or 500h and that's a bummer^^

Thanks

**Comment by groud** [comment]
This is simply not possible, the console integration depends on the console you use. 
Most of the features are going to be different from one console to another, as they have different hardware, social services, authentication system, save system, etc... so there is no way we could provide a "generic" documentation on how to integrate to any console, because there is nothing like a "generic" integration.

Maybe we could specify that porting to a console will likely, at least, require to implement a class implementing the OS interface. We could also make a list of the common features needed to be integrated, but there is not much more about it we could provide, as no specific details about how each console SDK work can be provided for legal reason.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/2330 and https://github.com/godotengine/godot-docs/issues/3035, as documentation issues are better tracked in the godot-docs repository.
