### ISSUE TITLE
Add a "Children" and "child" properties to nodes.

### ISSUE THREAD

**Issue by mk56-spn** [godotengine/godot-proposals#7705]
### Describe the project you are working on

A game with lots of UI elements where the current add_child() system can become burdensome at times

### Describe the problem or limitation you are having in your project

Sometimes when create the node stack for a UI setup you have nodes whos only purpose is to add padding. or do other minimal things that dont require them to have a name declaration for usage later.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a properties for adding children that can be called during node construction to allow for nested node initialisation

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

here is an example showing how allowing setting children as a property can be helpful at times:

![Screenshot from 2023-09-17 13-22-44](https://github.com/godotengine/godot-proposals/assets/74463310/8592d489-dd15-44f6-b6e4-b4374a7c57de)

in this mock-up node with this new property it is much easier to see the node structure that is being created without creating 6 named nodes when they will never be used again 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, adding this to existing nodes would require a custom Godot build to my knowledge

### Is there a reason why this should be core and not an add-on in the asset library?

It does not introduce a lot of maintenance overhead most likely and is convenient to have

**Comment by mk56-spn** [comment]
Example done in c# because i do not have enough experience in gdscript to say whether this would be of use over there. but i think the same idea holds

**Comment by AThousandShips** [comment]
The process of adding and removing children is complex, I don't think it makes sense to do this as a property access, for many reasons

Please provide some basic idea for how this would be possible, some basic idea how it would handle adding and removing children, for example, what happens if you do:
```gdscript
var tmp = children
tmp.erase(3)
tmp.emplace(node)
children = tmp
```

How does it detect what nodes are added or removed?

**Comment by mk56-spn** [comment]
> The process of adding and removing children is complex, I don't think it makes sense to do this as a property access, for many reasons
> 
> Please provide some basic idea for how this would be possible, some basic idea how it would handle adding and removing children, for example, what happens if you do:
> 
> ```gdscript
> var tmp = children
> tmp.erase(3)
> tmp.emplace(node)
> children = tmp
> ```
> 
> How does it detect what nodes are added or removed?

i must admit i do not understand the underlying system in regards to adding children so if my  suggestion is unworkable i get that, i also did not find the emplace() method  looking through the docs so i can not directly respond to the issue you are bringing up.

regardless if i get the gist of it correctly its that you can create impossible situations if you allow direct access to children im guessing?

**Comment by AThousandShips** [comment]
Sorry should be `append` my bad

**Comment by AThousandShips** [comment]
What I'm asking is:
How should it react to, for example, taking the list of children, adding some, erasing some, rearranging some, and then assign the list of children?

How would it handle that, how would it detect that one child is no longer in the list, how would it detect ones added

Not necessarily a detailed idea of how the code works exactly, but for example how would it work with some GDScript or C# code as a mock-up?

**Comment by mk56-spn** [comment]
> What I'm asking is: How should it react to, for example, taking the list of children, adding some, erasing some, rearranging some, and then assign the list of children?
> 
> How would it handle that, how would it detect that one child is no longer in the list, how would it detect ones added
> 
> Not necessarily a detailed idea of how the code works exactly, but for example how would it work with some GDScript or C# code as a mock-up?
> 
> Also: What if you have a list of children, and do some tweaking with them, and in the meantime some other script removes a node, or a node removes itself, how should the property data react? What happens if you add it back?
> 
> One consideration: Given the list: `{ Child1, Child2, Child3 }` And you change it to: `{ Child1, Child3, Child4 }`
> 
> Should it:
> 
> 1. Just remove `Child2` and add `Child4`, leaving `Child1` and `Child3` unaffected?
> 2. Remove all children and add `Child1`, `Child3`, and `Child4`?
> 
> The behaviour is wildly different

right, now i understand what you're getting at, the way i had imagined the property is that it wipes all child nodes out and replaces them with what you give it, so substituting the entire child list with whatever you feed into it, its usage would therefore be more so oriented towards initialising/ cleaning out the children of a node more so than editing children in and out of a node for which add_child is more adequate.

I have no idea regarding which would be more costly performance wise but this is how i feel such a property would act to be as intuitive as possible

obviously this is probably a terrible implementation but conceptually something like this perhaps : 

![Screenshot from 2023-09-17 15-54-00](https://github.com/godotengine/godot-proposals/assets/74463310/5ba52bc2-8ff2-4e09-8dbc-489171133fbd)

if such a feature is not desirable i perfectly understand that, its hardly a blocker for anything more so quality of life

**Comment by AThousandShips** [comment]
The problem is that the behaviour will be highly unexpected by a part of the users regardless which way you pick, right?

**Comment by mk56-spn** [comment]
fair enough

**Comment by bluenote10** [comment]
> Also when you're just initializing there's no need for this kind of thing, you just add all the nodes, with an optional helper function [...]

This is probably the key question: How to come up with such convenience that allows to build nested node trees in a syntactical concise form?

Personally I also encountered the issue observed by @mk56-spn that procedural generation of node trees  -- especially for GUIs -- often requires "dummy" nodes like `MarginContainer`, `VBoxContainer`, `HBoxContainer`. Building deeply nested trees with just plain `add_child` calls can become syntactically verbose, and in terms of readability the "tree like structure" is not easily reflected in the syntax.

-----------------------

However I think solving this issue largely depends on the language we're using Godot with. To give an example: I'm using Godot via Rust, and I've solved this issue by a small `assemble_tree!` macro. It offers a small domain specific language for that job, and internally converts it all to the necessary `add_child` calls. For instance, this GUI here

![image](https://github.com/godotengine/godot-proposals/assets/3620703/2265b485-21dc-49d1-8aa9-1c298b3296e3)

corresponding to this node tree

![image](https://github.com/godotengine/godot-proposals/assets/3620703/236b995a-cfd5-4b7d-91a7-1e49134773f5)

was build using this syntax in Rust (full example [here](https://github.com/godot-rust/gdext/issues/368#issuecomment-1660960719)):

```rust
assemble_tree!(
    base => {
        MarginContainer::new_alloc().set_full_rect() => {
            VBoxContainer::new_alloc() => {
                PanelContainer::new_alloc() => {
                    MarginContainer::new_alloc() => {
                        HBoxContainer::new_alloc() => {
                            make_label("left"),
                            make_label("middle").add_h_size_flags(SizeFlags::SIZE_EXPAND),
                            make_label("right"),
                        }
                    }
                },
                PanelContainer::new_alloc() => {
                    MarginContainer::new_alloc() => {
                        VBoxContainer::new_alloc() => {
                            .. children,
                            button.share(),
                        }
                    }
                },
            },
        },
    }
);
```

I've migrated quite a bit of plain `add_child` GDScript code to Rust using this macro, and I've always been quite pleased by the result -- mainly because the code now makes it very obvious what kind of node structure is build.

So perhaps it is possible to implement similar syntactical sugar in GDScript / C# that also leverages `add_child` internally without the need for actual tree diffing etc.
