### ISSUE TITLE
create/fix offset_polygon_2d(), an offsetting function for PoolVector2Array by a single vector

### ISSUE THREAD

**Issue by AriWD40** [godotengine/godot-proposals#777]
**Describe the project you are working on:**

an acid node that eats up polygons2d/collisionpolygons2d, or a bomb that does the same. 

**Describe the problem or limitation you are having in your project:**

When creating a new polygon, correct positional placement is key.

creating FOR loops in GDscript that offset the polygons is extremely taxing on performance but wouldn't be in C++. There is no function in polygon2d/collisionpolygon2d nor PoolVector2Array nor Geometry that offsets polygons. The function Geometry.offset_polygon_2d() doesn't offset a polygon by a vector amount, but inflates or deflates them, which is pretty silly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Either using (Transform2D * PoolVector2DArray) or .translate(), create a function in PoolVector2Array, Polygon2D & CollisionPolygon2D or Geometry that would add an input vector to all vectors in a given PoolVector2Array 

I think the function should be called offset_polygon_2d, and the function that already has that name should be changed to inflate_polygon_2d. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

1. take input poolvector2array
2. take input vector
3. in a loop, add vector to array
4. return array

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It will be used often, by most developers that use polygons a lot

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is a very basic vector function that belongs at the core.

**Comment by Calinou** [comment]
Can you move a parent node of the Polygon2D/CollisionPolygon2D instead?

**Comment by AriWD40** [comment]
let me check

**Comment by AriWD40** [comment]
I am using Geometry.clip_polygons_2d(), which don't accept coordinates of polygons, only poolvector2array. So no

**Comment by AriWD40** [comment]
Perhaps another solution (for me) would be to add an offset vector argument to the clip_polygon_2d() function, but as a general solution, I think an offset function would be more practical.

**Comment by Xrayez** [comment]
I've chosen the `offset_polygon` name for inflating/deflating polygons because that's what the Clipper library uses internally, and creating a separate method just for inflating and deflating polygons might be redundant and not as flexible as simply providing either positive or negative `delta`. I'm not sure of a better name for this. Also with godotengine/godot#36369 this could potentially make the API more complex. Note that I'm not really against making dedicated methods for this, it's up for other core devs to decide.

For translating polygon's vertices specifically, I've added support in `Transform2D/3D` to transform any `Vector2/3Array`, see examples in godotengine/godot#31761. You can take the `Transform2D(rotation, offset).xform(polygon)` to translate polygon vertices like that, and any other transform operation of course.

So this is a documentation issue I guess. Adding a note to `offset_polygon` about the mentioned `Transform2D` feature may be enough, but the ability to transform a `PoolVector2/3Array` is already documented though.

**Comment by AriWD40** [comment]
That should do it, though I am surprised at how little performance boost this gave me.
   
Thank you Xrayez.

**Comment by Xrayez** [comment]
There are many places where you could have a performance bottleneck, the polygon clipping is quite an intensive operation in and of itself, so you'll likely want to come up with optimization techniques like splitting polygons into smaller chunks.

For translating polygons, see documentation changes in godotengine/godot#38390 which may be merged to 3.2/4.0 built-in docs.

**Comment by Xrayez** [comment]
Also, you might be surprised how this can be little to do with the polygon clipping, but rather the rendering of polygons, which might be quite the case for you (and myself): godotengine/godot#19943, especially with many vertices which might result from this operation (more vertices → more shapes decomposed into convex → the number triangles to draw → slowdown).
