### ISSUE TITLE
A button to ' compile ' into low-level code . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#787]
**Describe the project you are working on:**
Tomb Raider, style game . .

**Describe the problem or limitation you are having in your project:**
This might not be needed, but I read GDScript, and Visual Script are high-level code languages, that need to be translated, and this is done, at run-time . . . Could one add a button, like in ' Unreal ', where one presses compile, and this is done before launching the game, to increase performance, it seems pretty easy, as this must happen at run-time, anyway, why not just have all the scripts made into ' machine speak code ', beforehand, so all the scripts are low-level, anyway it would be a nice feature, for sure . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I worry about performance, and in Unreal, they compile the Visual scripts into ' C# ', before one runs the game, I was wondering if one could do that in Godot, to increase performance . . . Not to C#, but all the way to low-level code stuff . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Not really sure, maybe the ' Compile ' button, used for Blueprint in Unreal somehow, could be made in Godot, so one doesn't interpret the visual script every frame, but it gets translated, before the game is run, by pressing a button or, toggling a ' Toggle ', in the project settings <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure, I can't code, just want it to be as fast, as possible . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, if it would make Godot run faster, I think everyone would benefit from it, a sort of ' translate visual scripts to low-level code ' button, in the editor or, inspector . . . <3

**Comment by Xrayez** [comment]
In theory, its possible to transpile VisualScript to GDScript at least, but I'm not sure about performance issues/differences with VisualScript to begin with. One could then transpile GDScript to C++, which can then be compiled to machine code, none of this is trivial to do at the moment. See some related proposals and issues if you want to indulge in reading: #119, #573, godotengine/godot#11068, godotengine/godot#11080, godotengine/godot#28968. 🙂

**Comment by jasperbrooks79** [comment]
Okay, I thought it would be easy, as the CPU does it at run-time, would be nice to get that feature, with Vulkan :OO

**Comment by mhilbrunner** [comment]
>This might not be needed, but I read

Please submit proposals for concrete needs or issues you face in a project.

>it seems pretty easy

Why don't you do it then instead of this proposal? Why do you think nobody else did yet, if it was such a low hanging fruit? 
Reconsider your assumptions, maybe. :) 

>I worry about performance

As does every game dev. So surely you've done some benchmarks? Tried to build a prototype for your use case, measured and ran into some specific performance problems that caused these worries?

Don't get me wrong, Godot certainly could stand some improvements and optimizations when it comes to performance, and things like Ahead of Time compilation may be wortwhile to explore.

As is, however, this proposal lacks both a specific problem to solve as well as a way to achieve that (other than a vague "make it faster").

Thanks for using Godot, and thanks for taking the time to try and improve it. :)
