### ISSUE TITLE
Always display enum values first when autocompleting an enum

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7913]
### Describe the project you are working on

Multiple Projects

### Describe the problem or limitation you are having in your project

Currently during the autocomplete of an Enum type.
It is listed as given below:

```gdscript
enum STATUS { IDLE, RUNNING, ACTIVE}
```

![image](https://github.com/godotengine/godot-proposals/assets/84369217/d2b3b290-8fc0-40cf-9a5d-7d6900e8f280)

The values of the enum are sorted in alphabetical order with all other functions and parameters. It will be more convenient if the values are at the top.

  

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the auto-complete menu all the values of the enum to be at the top as shown below:

![enum_autocomplete](https://github.com/godotengine/godot-proposals/assets/84369217/6246f6a6-2348-4efa-be2b-e5002c9c7ae2)

**There are two things to it.**
1. all the Enum values are at the top.
2. It is ordered by the way it has been defined or in other words their values(integer)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

listed above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used always

### Is there a reason why this should be core and not an add-on in the asset library?

Autocomplete is part of core

**Comment by TheColorRed** [comment]
I feel this shouldn't only be true for enums but all types. It seems as if it shows irrelevant things first, even when alphabetical is disabled in the settings.

I feel it should order Auto completions with itself first followed by the parent then grandparent and so on...

**Comment by HolonProduction** [comment]
> I feel it should order Auto completions with itself first followed by the parent then grandparent and so on...

That's how it is supposed to work.

Given the following class structure:
```gdscript
class A:
    ...

class B extends A:
    ...

class C extends B:
    ...
```

The autocompletion for something of type `C` should have the following structure:

1. properties and methods of `C` in alphabetical order
2. properties and methods of `B` in alphabetical order
3. properties and methods of `A` in alphabetical order

If it doesn't work that way it is a bug and you should report it.

Regarding the proposal I like the idea, but implementing it could be hard. The sorting is done by the code edit, and is not tied to GDScript (it could also receive suggestions from another language) and so getting access to the declaration order is hard. We could abuse the `location` property to achieve it but that feels like a hack, and wouldn't work for unnamed enums (since it would interfere with the real use for `location` in that case).

**Comment by tokengamedev** [comment]
> Regarding the proposal I like the idea but implementing it could be hard. The sorting is done by the code edit, and is not tied to GDScript 

I kind of understand, but to make matter more complicated, another thought was to display the class name to which the item belongs. It would be a different proposal altogether, but it makes sense, where the function/property is coming from.
Now adding the two, will it not possible to pass the sort order along with item name and class name, which code edit can use to sort, and display based on context

> wouldn't work for unnamed enums (since it would interfere with the real use for location in that case).

I think unnamed Enums work as group of constants, so it should display as constants only, sorted alphabetically. It is not worth the effort to custom sort them though.
