### ISSUE TITLE
Add Save and Load ability to swatches

### ISSUE THREAD

**Issue by eddieataberk** [godotengine/godot-proposals#7946]
### Describe the project you are working on

Game with multiple color themes

### Describe the problem or limitation you are having in your project

Having to re-arrange swatches is time-consuming

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the ability to save and load swatch groups as tres files.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/48696693/d4b0a669-2b35-4c71-bdc3-4bea062631de)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

this is about improving the editor usability

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/6805.

**Comment by hsandt** [comment]
Maybe not for this proposal since PR is already in the work, but as a future improvement, a Quick Load similar to other resource Quick Load popup (list all assets with the correct type) would be a nice complement to the classic Load file popup, and would make the color palette picker as fast as Unity's swatch library dropdown.
