### ISSUE TITLE
Add support for .jxl, .flac .av1 encoding/decoding

### ISSUE THREAD

**Issue by RustoMCSpit** [godotengine/godot-proposals#8011]
### Describe the project you are working on

A game with images and sound

### Describe the problem or limitation you are having in your project

Lack of support for better file formats

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

They save space, are foss, etc..

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

decode formats?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

yes, file formats

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1190 and https://github.com/godotengine/godot-proposals/issues/2461. (While the latter is about AVIF, the same concerns about JPEG-XL apply, so consider it rejected until it gains greater adoption.)

**Comment by RustoMCSpit** [comment]
> it's considered rejected until the format gains greater adoption.

im a bit confused by this logic apologies, the only way to have more adoption is for apps to support it in the first place. it's a self-fulfilling prophecy. how do you think these stronger formats will grow otherwise?

**Comment by IcedQuinn** [comment]
> > it's considered rejected until the format gains greater adoption.
> 
> im a bit confused by this logic apologies, the only way to have more adoption is for apps to support it in the first place. it's a self-fulfilling prophecy. how do you think these stronger formats will grow otherwise?

JXL is supported by major photo editing software and Safari these days. It's really just Google sandbagging the format in Chrome at this point.

**Comment by aaronfranke** [comment]
Note that users are welcome and encouraged to implement support for these formats in GDExtension.

**Comment by myclay** [comment]
> it's considered rejected until the format gains greater adoption.

JpegXL integration has been reopened for Chrome.
Additionally JpegXL will be added to the File Format PDF.
https://issues.chromium.org/issues/40168998
https://www.phoronix.com/news/JPEG-XL-Possible-Chrome-Back

is that enough adoption for reopening this proposal?

**Comment by BryanHaley** [comment]
JPEG XL seems to have won the long fight and is here to stay for the future. It is also supported in many more apps and OS shells than it was in 2023 when this issue was first opened. And, for what it's worth, it's a much better format for distributing textures with; a lossless JPEG XL is much tinier than a lossless PNG and that matters when we're talking about 4k or 8k textures.

<img width="576" height="366" alt="Image" src="https://github.com/user-attachments/assets/fd5c58bf-9d8b-455d-b51d-829198a251d8" />

**Comment by nostalgia-korvektis** [comment]
I double that JXL does already have enough support, and should be implemented. ffmpeg, adobe, Facebook, a few shop websites, gimp, krita, ... those are only a few names that have implemented jxl support a few years ago. Now google also want to implement it in chrome, and firefox will be forced to follow.

I haven't looked much around, but it seems to be a great format that simplifies a lot of things and has a better and faster codec (according to ffmpeg devs in a google thread). From what i understand, and sorry for it becoming political, it seems that google had tried to kill jxl in favor of AVIF, which they put a lot of effort in, and now that CDN cost them a lot, implementing something like JXL might save them a lot of space due to the format being efficient at compressing data, even in lossless mode. My knowledge is probably biased since i've gotten that information from a video: https://www.youtube.com/watch?v=uDydCrCXHyU, but it seems well studied, and is a great reference to me. I could also have misunderstood the video content, which is why i left the link to ensure the context is correctly transmitted.

Waiting might be smart tho, as the support increases, the codec might be improved, and implementing it might become easier. I don't really know i'm not an expert in that area. All in all, i hope it'll be implemented as well.

**Comment by BryanHaley** [comment]
Decode routines are unlikely to be changed as that would break compatibility with everything currently using JXL; there shouldn't be any benefit to waiting longer.

**Comment by dyvoker** [comment]
Game engines are closed ecosystems in terms of format support. And it is a great opportunity to increase the adoption of this format.
As an indie dev, I look at game size and try to optimize it. For example, I converted all MP3s to OGG (Vorbis) using ffmpeg. And the problem was not even adoption, I just didn't know that OGG is better than MP3 in a lot of cases.
I think it is a great opportunity to implement support and to talk about this JPEG XL LOUDLY in release notes (it will also be great to mention OGG), so people will know that there are easy ways to make their game a bit better. It is good to mention that a simple script with ffmpeg can convert all existing images to JPEG XL.
Thanks for great engine! ❤️

**Comment by Calinou** [comment]
> For example, I converted all MP3s to OGG (Vorbis) using ffmpeg. And the problem was not even adoption, I just didn't know that OGG is better than MP3 in a lot of cases.

If you convert a lossy format to another, this reduces quality (even if you use the same bitrate or a higher bitrate in Ogg Vorbis). The same applies to any lossy-to-lossy format conversion (it's a form of [generation loss](https://en.wikipedia.org/wiki/Generation_loss)). If you want Ogg Vorbis to be actually a better format than MP3, you need to encode it from a lossless source (WAV or FLAC).

JPEG XL is a bit different in the sense that it supports lossless JPEG transcoding (the output is bit-for-bit identical), but this comes at the cost of slower decoding times. In Godot's context, this will not actually impact loading times of an exported project (since the PCK doesn't contain JPEG or any other standard image format, but Godot's own `.ctex` format[^1]). This will however slow down resource (re)importing in the editor a little, since Godot has to decode the image before it can be imported.

It's probably not a huge issue in this context, but it's worth keeping in mind that implementing JPEG XL in Godot will **not** impact the size or loading times of exported projects. It will only affect the file size of what you commit to version control (reducing it is always a good thing, provided it doesn't affect import times too much).

[^1]: A custom format is used because it allows for various compression schemes (including VRAM compression, which standard image formats don't support). It can also store metadata that can't be practically saved consistently in all source image formats, as well as mipmaps.

**Comment by dyvoker** [comment]
> If you convert a lossy format to another, this reduces quality

Yeah, it was 320kbps mp3 so it is fine to lose a bit of quality during conversion to get half of a size.
> since the PCK doesn't contain JPEG or any other standard image format, but Godot's own .ctex format

Thanks for clarification about `.ctex`! In this case image format not so important, I guess... WEBP is already working 🫡

**Comment by BryanHaley** [comment]
It still reduces your source project size, which saves you disk space locally and reduces the size of your version control repo (which can be especially important if you're hosting on free services like github).

It also makes distributing your textures **much** easier if you're making an asset pack (as in my case). What I'm doing at the moment to support Godot is distributing as JXL and including a batch file to convert to PNG, which is kind of annoying for users. If JXL is supported directly, everyone wins.

**Comment by Joy-less** [comment]
Another benefit to supporting JXL that I haven't seen mentioned yet is that it would be beneficial for Godot to be able to save an `Image` as JXL, which would be the best filesize/quality of any `save_*` function.

In my game, I have been saving images in the player's portable save file, which means any size saving is ideal.

There is no reliable cross-platform JXL library for GDScript or C# that I know of, so it's difficult to do this without official Godot / C++ support.

**Comment by BryanHaley** [comment]
@Calinou would it be possible to reopen this issue for further consideration?

**Comment by ghost** [comment]
There is [LibJXL](https://github.com/libjxl/libjxl) which we could use to implement support for JXL.

**Comment by aaronfranke** [comment]
Has anyone implemented these formats as a GDExtension plugin or a module? That would be a good way to gauge interest.

**Comment by ghost** [comment]
> Has anyone implemented these formats as a GDExtension plugin or a module? That would be a good way to gauge interest.

If I have free time, I'll try to implement it in the engine via LibJXL as a module though it will take some time.
