### ISSUE TITLE
Adding/Overloading Some Operators for Signal to Make GDScript's Signal Operations More Readable

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#8047]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

As is known to all, signals are now belong to a native class Signal, which allows us to directly connect them to methods (Callables).
However, most of times we are prefer to use a operator to connect signal, just like how it is done in C#. And sometimes methods' calling will make the code more difficult to read as the project grows

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My thought is to add/overload some operators to stands for some signal methods in a faster way.
A signal is places on the left while a callable is done on the right if it is related to connection
``` GDScript
signal my_signal
...
my_signal <connection_operator> my_func
```
Also, developers are still able to use methods to do so.

#### Deprecated Version
For example
```GDScript
signal my_signal
...
my_signal.connect(my_func)

# Replaced by operators
# Equals "my_signal.connect(my_func)"
my_signal += my_func 
#or
my_signal => my_func # Returns an int

# Disconnection
# Equals "my_signal.disconnect(my_func)"
my_signal =/=> my_func 
#or
my_signal -= my_func # Returns nothing

# Check
# Equals "my_signal.is_connected(my_func)"
print(my_signal =?=> my_func) 
#or
my_signal == my_func # Returns True/False, here it's obviously 'false'
```
If we need to pass in a flag, we can add a method `bind_flags()` for a Signal
```GDScript
# Equals "my_signal.connect(my_func, ...)"
my_signal.bind_flags(...) => my_func
```
When it comes to signal emission, we can use an operator `++` to mean "emit", and add a method `bind_params()` to make it emitted with parameters
```GDScript
# Equals "my_signal.emit(1, 2, 3)"
my_signal.bind_params(1, 2, 3) ++
```
#### Updated Version
Seems that those symbols above were not well-understanding, so maybe `+`(`connect()`) and `-`(`disconnect()`) would make sense:
```GDScript
# Connection
my_signal + my_func # Means the signal adds the callable into its "listeners list" (connect)

# Disconnection
my_signal - my_func # Means the signal removes the callable from the list (disconnect)
```
As for `emit()` and `is_connected()`, seems that only methods do the best...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is an optimized(maybe) way to do signal operations, and methods are still allowed. So this can still be operated with functions.

### Is there a reason why this should be core and not an add-on in the asset library?

Addons are not allowed to get access to GDScriptAnalyzer, nor can GDExtension.

**Comment by Mickeon** [comment]
Overall, this is not necessarily more "readable". 

> If we need to pass in a flag, we can add a method `bind_flags()` for a Signal
> 
> ```gdscript
> # Equals "my_signal.connect(my_func, ...)"
> my_signal.bind_flags(...) => my_func
> ```
> When it comes to signal emission, we can use an operator `++` to mean "emit", and add a method `bind_params()` to make it emitted with parameters
> 
> ```gdscript
> # Equals "my_signal.emit(1, 2, 3)"
> my_signal.bind_params(1, 2, 3) ++
> ```

These method break conventions. What `bind_flags()` and `bind_params()` would return is neither a **Signal** nor a **Callable**. It can't be either because the flags are bound to the **Connection**. Having this work would require either exposing **Connection** as a Variant type, or making a massive exception for GDScript's interpreter and not other languages (C#).

Additionally, adding new operators needs to be done very carefully, especially if they are a massive exception. If anything, `=>` and `++` are more confusing. They're more operators to learn, more combinations of somewhat arbitrary characters, that have a relatively niche use, compared to the appropriately called methods that do the same thing.

Namely, in the proposal `=?=>` is also suggested. This operator is just ridiculously lengthy and easy to forget.
In comparison, the equivalent `is_connected()` already exists. Most things with "_connect_" in their name are reserved for signals in Godot, so it's pretty easy to associate when reading code.

So that's why, in my eyes at least, these new operators would not even be recommended. GDScript is designed to be easy to read, and these are not it.

**Comment by Mickeon** [comment]
Although, interestingly, using `+` and `-` as equivalents of `connect` and `disconnect` does have merit. C# already allows its events to be connected and disconnected with `+=` and `-=`, respectively.

It does still go against GDScript's principles. For example, `a += b` literally means `a = a + b` and there are no exceptions. But this proposal would be the exception, because this time `+=` would have to behave differently from `+`. Otherwise, the variable would get overridden.
