### ISSUE TITLE
Change default collision shape type in imported 3D scenes away from "convex decomposition"

### ISSUE THREAD

**Issue by wareya** [godotengine/godot-proposals#8059]
### Describe the project you are working on

3d scene demo

### Describe the problem or limitation you are having in your project

Whenever I turn on "generate physics" in the import panel for my scene's model it locks up for several minutes as it churns through the math for approximating a convex decomposition of that part of the map. The collision shape type cannot be changed before enabling physics, the panel literally does not exist until you turn "generate physics" on, which triggers the generation process.

99% of the time, I don't want a convex decomposition, I want a full convex solid or a trimesh.

By the way, I wrote and proofread this proposal in easily far less than 20% of the time that it took for the convex decomposition of a metal gate to generate.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the default collision shape type in the advanced 3d model import dialogue to full convex solid or trimesh. This would avoid situations where people are forced to wait for the most expensive collision shape generator to finish before switching to a cheaper one.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Part of the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Part of the editor.

**Comment by Calinou** [comment]
I agree the default should be concave/trimesh, as it's what I'd use in 99% of cases. However, changing this will break compatibility with existing projects.

**Comment by wareya** [comment]
Compatibility could be retained by making the "physics/shape_type" key in model import files special and always written to disk even if it's the default value, and adding a special case to make the not-present case load as "convex decomposition" instead of the default value. Alternatively, the new default value could be an interface-only change.

**Comment by chrisl8** [comment]
I am here after waiting about an hour after clicking on Generate Physics with a silly .glb file.

Apparently it isn't slow simply due to the one mesh in the I am selecting, but the more meshes there are in the .glb the longer it takes.

I'm not even sure what it is doing as my CPU shows under 10% usage for Godot (the fans never kick in) although Godot eventually uses over a gigabyte of memory before giving me control again.

I think if I could just set **my** default to something else it would make the process usable for me. I don't need everyone's default to be changed, I just need to be able to change my project default so other people don't fall into this trap with me or at least my editor default.

I am only asking to change the default in the editor, not what is done if nothing is set in the .import file.

I agree though that going forward the editor should probably set the Shape Type in the import file always, so that there is no confusion.

If you want a silly example .glb that will bring the Godot import dialog to its knees download this and pull it into any empty project, double click it to open the import dialog and select Generate Physics on any mesh.

https://github.com/chrisl8/space-game/blob/main/things/vending_machine/vending_machine.glb

I realize this file may be a worse case scenario, but outside of the import dialog, this file is fully usable within Godot and I can even generate collision shapes on the meshes easily in the editor inside a scene, it is only in this import dialog that it is impossible due to locking up for ages.

**Comment by chrisl8** [comment]
FWIW: I hacked the Godot source to change the default to Trimesh and suddenly selecting Generate Physics doesn't make Godot skip a beat. It went from locking up for an hour to not taking any time at all and makes this feature usable again.

Unfortunately I'm not proficient at C++ so I won't be submitting a proper PR for this anytime soon. My experiment was just a hack.

**Comment by Calinou** [comment]
I've looked around in the [code](https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/editor/import/resource_importer_scene.cpp) and can't see an easy way to change the value automatically after enabling **Generate > Physics**. We essentially need to be able to compare the old value with the new one to change the value of **Physics > Shape Type** within the editor, and only if this value is currently set to its default (convex decompose). All I can find is a reference to whether the preview UI should be updated when the property is toggled: https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/editor/import/resource_importer_scene.cpp#L1884

The only backwards-compatible workaround I can see for now is to not hide the physics shape type property when **Generate > Physics** is disabled, but this would be inconsistent with the rest of the inspector UI and it wouldn't resolve the issue out of the box. Most users don't even know why the engine is locking up after enabling **Generate > Physics**.

Given this can be a dealbreaker, we should find a solution that can be cherry-picked in 4.2.x.

**Comment by chrisl8** [comment]
I would like to submit this project as an example for debugging and solving this issue along with demonstrating how the problem manifests.

[ImportTesting.zip](https://github.com/godotengine/godot-proposals/files/13269952/ImportTesting.zip)

There are three .glb files in it:

 - simple_box.glb - This one causes no problem.
 - one_button.glb - This one demonstrates a significant lock up when selecting Generate Physics.
 - many_buttons.glb - This one demonstrates an almost unusable lockup period.

It seems odd to me that the number of meshes within the file increases the duration of the lock-up. Why does the many_buttons.glb file lock up the interface for longer when selecting the same single button within it? This causes highly complex .glb files to be impossible to use this feature with. Shouldn't the operation only happen on the individual mesh, such that the number of meshes in the file doesn't matter?


I'm also attaching a video in case it isn't clear what I mean about lock-up or in case it isn't happening to everyone who tries this.
https://github.com/godotengine/godot-proposals/assets/6188278/e99b3974-3a44-4f29-86c5-a234051a6643


Interestingly, making this change to the code fixes the problem entirely for me, allowing me to use the Generate Physics feature with absolutely no delay after clicking the check-box
```
diff --git a/editor/import/resource_importer_scene.h b/editor/import/resource_importer_scene.h
index 17681387e6..a4ef079d0e 100644
--- a/editor/import/resource_importer_scene.h
+++ b/editor/import/resource_importer_scene.h
@@ -321,7 +321,7 @@ public:
 template <class M>
 Vector<Ref<Shape3D>> ResourceImporterScene::get_collision_shapes(const Ref<ImporterMesh> &p_mesh, const M &p_options, float p_applied_root_scale) {
        ERR_FAIL_COND_V(p_mesh.is_null(), Vector<Ref<Shape3D>>());
-       ShapeType generate_shape_type = SHAPE_TYPE_DECOMPOSE_CONVEX;
+       ShapeType generate_shape_type = SHAPE_TYPE_TRIMESH;
        if (p_options.has(SNAME("physics/shape_type"))) {
                generate_shape_type = (ShapeType)p_options[SNAME("physics/shape_type")].operator int();
        }
```

I'm not suggesting this is "the fix", just that it may help demonstrate the problem and point toward a solution.

I dislike the idea of a timeout, because it still means we will always have at least `timeout length` delay every time we select the check-box, even though we know that if the default was Trimesh, it would be instant on many systems.

My guess is that a lot of people are not using this feature at all because they think Godot is crashing or that their system just cannot handle the process.
The only way I can use it is to make a custom build of Godot with the above change, but that isn't a suitable change for everyone. 

In case it matters, the video was made using build from `master` this morning:
v4.2.beta.custom_build [4c96e9676]
On this system:
Godot v4.2.beta (4c96e9676) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4592) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

**Comment by chrisl8** [comment]
This causes such a burden to my development that I currently only edit with a custom built engine. Waiting 30 minutes every time I want to edit an import is not workable.

I didn't want to suggest this as a 4.2 goal, so I didn't bring it up again while the Beta/RC cycle for 4.2 was in play, but now that 4.2 is released, I have two questions:

1. Can this be flagged as a goal for 4.3? 
2. **I think** that this is really a bug. Would you like me to open an Issue on the godotengine repository with what I posted above, or is it fine/better as it is here?

**Comment by reduz** [comment]
One bit of information here. Godot saves all settings in the .import file, so changing this default should _not_ break compatibility. As such, feel free to make a pull request to change this, existing files will keep importing as they did before.
