### ISSUE TITLE
Use Vertex-Lighting for far objects

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#8128]
### Describe the project you are working on

Working on reimplementing vertex-lighting in Godot 4

### Describe the problem or limitation you are having in your project

Nothing really, but an idea.
As I understand vertex-lighting enhances performance, but it is kinda low quality lighting.

So why can't we use it for far objects, along with auto Lod ?

I am no expert so I don't know if the performance gains is worth it for PC platforms, but I guess it will be worth it for mobile games that target High-End so they can use pixel-lighting for near objects and vertex-lighting for far objects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add options for each mesh "Use Vertex-Lighting when far from camera, Far Distance Value for Vertex-Lighting"

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Engine will switch to vertex lighting if after the check the mesh distance to camera is bigger than "Far Distance Value for Vertex-Lighting"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You will have to do it for each mesh, and do distance calculation to camera.

I guess not convenient.

### Is there a reason why this should be core and not an add-on in the asset library?

Improving engine performance out of the box.

**Comment by Calinou** [comment]
This can already be achieved using visibility ranges and a custom material: https://docs.godotengine.org/en/latest/tutorials/3d/visibility_ranges.html#use-simpler-materials-at-a-distance-to-improve-performance

However, vertex shading needs to be reimplemented first.

Also, remember that performance won't improve much when doing this, as distant materials only occupy a small portion of the screen. The performance impact of per-pixel shading is more noticeable when the material takes up a lot of the screen (which is why it's a good idea to use vertex shading for lit particles).

**Comment by ywmaa** [comment]
For me this answer is what I needed so closing this issue.
