### ISSUE TITLE
Add elementary set operators for Arrays and Dictionaries

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot-proposals#821]
**Describe the project you are working on:**
Currently working on [tripthearkfantastic.com](url), a big 2D side-scrolling RPG made in Godot.

**Describe the problem or limitation you are having in your project:**
One of the mechanics of my game is collecting clues all-around the game world. Currently these clues are added in an array that will, over time, start to grow larger and larger.

For UI purposes, I would like to only update clues that are actually new, or remove clues that have been removed. Currently I do it like this:
```swift
static func compare_arrays(old_array, new_array) -> Dictionary:
    # Check which values are new and which ones got removed.
    var to_be_added := []
    var old_duplicate : Array = old_array.duplicate()
    for clue_id in new_array:
        if old_duplicate.has(clue_id):
            old_duplicate.erase(clue_id)
        else:
            to_be_added.append(clue_id)

    # The ones that didn't get erased are to be removed!
    var to_be_removed := old_duplicate
    
    return {"add": to_be_added, "remove": to_be_removed}
```
This does the job, but I would very much like to use set operators (written and optimized in C++) to make the code easier to read and increase performance.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would propose similar set operators such as in MATLAB:

- For getting the common elements (= union) of two arrays:

https://www.mathworks.com/help/matlab/ref/double.union.html

- For getting the intersected elements (= intersection) of two arrays:

https://www.mathworks.com/help/matlab/ref/double.intersect.html

- For getting the different elements that are in new_array, but not in old_array:

https://www.mathworks.com/help/matlab/ref/setdiff.html

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The same function as above would end up looking like this:
```swift
static func compare_arrays(old_array, new_array) -> Dictionary: 
    return {
        "add": new_array.set_difference(old_array), 
        "remove": old_array.set_difference(new_array)
    }
```

Other example:
```swift
var array1 := ["a", "b", "c", "d", "e"]
var array2 := ["d", "e", "f", "g", "h"]
var union_array = array1.union(array2) # Contains ["a", "b", "c", "d", "e", "f", "g", "h"]
var intersect_array = array1.intersect(array2) # Contains ["d", "e"]
var diff_array1 = array1.set_difference(array2) # Contains ["a", "b", "c"]
var diff_array2 = array2.set_difference(array1) # Contains ["f", "g", "h"]
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be by usage of for-loops, but I imagine that having large arrays will start to hog the system when running these loops.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Comparing arrays and being able to do elementary set operations is a feature that would benefit a lot of projects in my opinion as it gets rid of GDscript  for-loops which is always a nice things.

**Comment by RabbitB** [comment]
Overall I like the idea of this proposal, but I believe there needs to be more discussion over dictionaries. Array is pretty straightforward with these functions, because we largely don't care about array indices, we care about what they contain.

However, when we start talking about dictionaries, how do we handle something like intersect? Do we intersect based on keys or values? Or do we provide two sets of methods to work on either keys or on values?

My gut reaction is to work on keys only, and copy the values for the keys from the called dictionary (and not the one passed as an argument), but that may not be as equally intuitive to others.

**Comment by 2shady4u** [comment]
For dictionaries I would implement the same features as Rust implements regarding HashSets (Similar to Dictionaries):
https://doc.rust-lang.org/stable/rust-by-example/std/hash/hashset.html

Which would result (in Godot) into the following syntax:
```
var dict1 := {"goblin": {"HP": 2, "MP": 0}, "ogre": {"HP": 20, "MP": 2}, "dragon": {"HP": 20, "MP": 20}}
var dict2 := {"orc": {"HP": 2, "MP": 0}, "ogre": {"HP": 20, "MP": 2}, "dragon": {"HP": 15, "MP": 20}}
var union_dict = dict1.union(dict2) # Contains {"goblin": {"HP": 2, "MP": 0}, 
"orc": {"HP": 2, "MP": 0}, 
"ogre": {"HP": 20, "MP": 2}, 
"dragon": {"HP": 15, "MP": 20}
}
var intersect_dict = dict1.intersect(dict2) # {"goblin": {"HP": 2, "MP": 0}, "orc": {"HP": 2, "MP": 0}}
var diff_dict1 = dict1.set_difference(dict2) # {"goblin": {"HP": 2, "MP": 0}}
var diff_dict2 = dict2.set_difference(dict2) # {"orc": {"HP": 2, "MP": 0}}
```
So I my opinion I think only working on keys is the way to go.

**Comment by RabbitB** [comment]
Just to be clear, intersect works the same as union, and the values from the dictionary passed as an argument, overwrite the values from the dictionary the method was called on, correct? I would verify in the Rust docs, but I don't think they're rendering correctly. Their code examples show tons of html fragments and they simply don't render in a readable format.

Seems counterintuitive, but if that's how it's handled in other languages with such functionality, it's probably the way to go.

**Comment by 2shady4u** [comment]
Yes, that would be correct.

Now take into account that this is just a proposal, details of implementation have to be discussed in depth by people who have a better understanding of Rust and its implementation.
Having @Zylann here might be nice, cause he knows exactly how this works.

**Comment by RabbitB** [comment]
I also wanted to ask about duplicates in arrays. Do we only keep one value period, or do we return one value for every time both arrays have that value?

Essentially, do we treat duplicates as unwanted and discard them (treating them as if there's only a singular entry for that value), or do we treat them as their own discrete values?

.NET would handle duplicates as unwanted and simply discard them.

```C#
int[] array1 = { 1, 1, 2, 3 };
int[] array2 = { 0, 1, 1, 2 };
IEnumerable<int> array_intersect = array1.Intersect(array2); // This would produce [1, 2]
```

Sorry if these sound like dumb questions, but the std-lib of every language is going to handle certain things differently, and I really want to try nailing down exactly how we would like it to function.

**Comment by Zylann** [comment]
> Array is pretty straightforward with these functions, because we largely don't care about array indices, we care about what they contain.

Not entirely true. Arrays are the only container with explicit ordering, you can care about indices, and more specifically the order in which items come in. But that's a matter of how you use it of course.

> However, when we start talking about dictionaries, how do we handle something like intersect? Do we intersect based on keys or values?

Intersecting based on keys makes the most sense as default behavior, I think. If you wanted to intersect based on values, either provide another method, or use the array of values maybe. You could also provide a function to do the intersection test.

Generally speaking set operations sound useful, although I'm not using them that often, at least not as explicit functions like proposed here. The reason is often due to the fact that I design my data structures before choosing the operations to do on them, for best efficiency (real time games). If Array had all set intersections methods readily available but I need such algorithm to work on a wildly different structure for performance reason, they will still be useless to me^^ Data structure matters before thinking about the algorithm.
Although, they can come in handy for small arrays. Beware of bloat though, if it can be solved with a bit of code and different design choices, or even as a library, then it's not that needed to be in core (citing the doc).

**Comment by 2shady4u** [comment]
closing this in favor of #867
