### ISSUE TITLE
Animating points of 2D polygons

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#8250]
### Describe the project you are working on

Game has a lot of animations, the characters are cut into pieces and put together

### Describe the problem or limitation you are having in your project

Godot has an excellent animation system, but I always missed animations of 2D mesh points, in the style of spine or dragon bones

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the ability to animate points, this will open up completely new possibilities for godot animation

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This would be a very interesting feature for Godot, and it would also attract more artists and animators to Godot.

**Comment by AThousandShips** [comment]
This is possible, though currently affected by a bug:
* https://github.com/godotengine/godot/issues/83841

**Comment by vyshliy** [comment]
Hello. I'm currently working on Polygon2D Editor plugin that expands the standard functionality for editing a Polygon2D. I can release the first version after some improvements and fixing the bug mentioned above.

By the way, the ability to animate polygon points exists in Godot since version 4. This plugin will simply make creating animations easier. Right now you can use existing https://github.com/dweremeichik/godot_autopoly_plugin with the stable version of Godot, it works quite fine.

Polygon2D Editor preview:

https://github.com/godotengine/godot-proposals/assets/72736632/66ad4940-8944-4bf4-9f03-06138c0513fd

**Comment by Calinou** [comment]
Closing, as this is actually a bug: https://github.com/godotengine/godot/issues/83841
