### ISSUE TITLE
Add an editor setting to disable switching to script editor after connecting a signal

### ISSUE THREAD

**Issue by ershn** [godotengine/godot-proposals#8351]
### Describe the project you are working on

A 2D top-down colony survival game set in space

### Describe the problem or limitation you are having in your project

I'm programming my game in C# in VSCode.

When it comes to signals, my programming workflow is as follows:
1. In VSCode, create methods that will be triggered by signals (not just stubs but fully functional methods)
2. In Godot, double click a signal to open the signal connection dialog
3. Select the receiving node and pick the matching method using the method list window
4. Click the `Connect` button

Since my method is already implemented and I don't need to change it further, I don't need to switch to VSCode after connecting the signal.
However, clicking `Connect` in 4.1 will always switch me back to VSCode. I want to avoid that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want to add a new editor setting to disable the automatic switch to the text editor.
Using this setting I won't have to switch back to Godot every time I connect a signal.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a new editor setting to disable the automatic switch to the text editor when connecting a signal.

Ideally, you could also choose what to do directly in the signal connection dialog with a toggle. The toggle default would be equal to the editor setting value. I don't think this modification is strictly necessary though.

After looking through the existing categories, I think adding the new setting under `interface/editor` is the most appropriate (it kinda feel like a misc category right now though).

The setting itself would be called `Open text editor on signal connection` and would be true by default (to preserve the current behavior).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know of any way to work around this behavior.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it's doable without changing the editor code itself.

**Comment by passivestar** [comment]
I have the same problem, and I think it doesn't need an editor setting, it could just not open the script editor for _**existing**_ methods at all because realistically how often would you want that?

I did post a screenshot of an editor setting [here](https://github.com/godotengine/godot-proposals/discussions/8836) though in case we're missing some workflow where people want that by default. But I can't see why

**Comment by Calinou** [comment]
Like when you select nodes while in the script editor, this behavior could be changed to require holding down a modifier while clicking the Connect button in the signal connection dialog.

**Comment by theraot** [comment]
I'll throw in that it could also be solved with two buttons in the dialog: "Connect" and "Connect and open". *I'd argue for button button with a drop down, but I don't think Godot has a solution for that ready to use.*

**Comment by ershn** [comment]
> it could just not open the script editor for existing methods at all because realistically how often would you want that?

I think this scenario could happen in case the user first creates stub methods and then connect them to signals. In that case you might want to open the editor on connect. Not sure how common it is but we should probably take that into account.

> Like when you select nodes while in the script editor, this behavior could be changed to require holding down a modifier while clicking the Connect button in the signal connection dialog. This would be a good middleground that doesn't require adding an editor setting, while still making it possible to choose the desired behavior on the go.

I'm not sure how common it is to e.g. ctrl-click a button and get a different behavior than click. IMO it's rather uncommon for OS-like GUI buttons. I'm ok with it if there is a precedent in Godot though.

I like the 2 buttons idea ! I think it's a pretty common solution and it's simpler than adding a new setting.

**Comment by Calinou** [comment]
Note that the 2-buttons solution lacks an easy way to activate it with a keyboard, so I'd suggest using the modifier for that case (holding <kbd>Ctrl</kbd> when pressing <kbd>Enter</kbd> while on the LineEdit that contains the target function name).

**Comment by passivestar** [comment]
Looking at the source code for this

Adding connections is handled in `ConnectionsDock::_make_or_edit_connection()`, and the signal emission that causes the editor to open happens inside of the `if (add_script_function)` block.

`add_script_function` should be true only if the class or any of its parent classes doesn't have the method, comments make it clear:

```cpp
// Conditions to add function: must have a script and must not have the method already
// (in the class, the script itself, or inherited).
bool add_script_function = false;
Ref<Script> scr = target->get_script();
if (!scr.is_null() && !ClassDB::has_method(target->get_class(), cd.method)) {
	// There is a chance that the method is inherited from another script.
	bool found_inherited_function = false;
	Ref<Script> inherited_scr = scr->get_base_script();
	while (!inherited_scr.is_null()) {
		int line = inherited_scr->get_language()->find_function(cd.method, inherited_scr->get_source_code());
		if (line != -1) {
			found_inherited_function = true;
			break;
		}

		inherited_scr = inherited_scr->get_base_script();
	}

	add_script_function = !found_inherited_function;
}
```

Unfortunately there's a logic error, and it doesn't detect if the function is present on the class itself, only on its parents. So when we're trying to make a connection to an existing method, we're trying to add a new script function, which causes the editor to open.

We don't end up with another copy of the method because there's another check later in `GDScriptWorkspace::apply_new_signal` that prevents that:

```cpp
void GDScriptWorkspace::apply_new_signal(Object *obj, String function, PackedStringArray args) {
	Ref<Script> scr = obj->get_script();

	if (scr->get_language()->get_name() != "GDScript") {
		return;
	}

	String function_signature = "func " + function;
	String source = scr->get_source_code();

	if (source.contains(function_signature)) {
		return;
	}
```

So the original intent of `ConnectionsDock::_make_or_edit_connection()` was to only add a callback and open the script editor if the method doesn't exist. It works as initially intended for inherited methods. So there's currently a bug where connecting to an existing method on a child class opens the editor, but connecting to an existing method on a base class doesn't:

https://github.com/godotengine/godot-proposals/assets/60579014/5e581416-9023-42a1-99b8-ebd1091d1280

[ConnectionBug.zip](https://github.com/godotengine/godot-proposals/files/13952140/ConnectionBug.zip)

We can still keep the old behaviour where connecting to existing methods with no `Ctrl` pressed opens the editor since everybody is used to it, but the code and comments need to be modified to reflect that it's intended

And the bug could be fixed in the process too, same behaviour for both own class and parent classes 🙂
