### ISSUE TITLE
Extend Type Inference to Function Return Types in GDScript using ->:

### ISSUE THREAD

**Issue by sandygk** [godotengine/godot-proposals#8371]
### Describe the project you are working on

This applies for any project that enables the `Untyped Declaration` warning to keep the code strongly typed. Also users who want to get autocompletion and other perks of typed code without having to type it when it can be inferred.

This feature encourages the adoption of strong typing practices by reducing the effort required to maintain them, ultimately improving code quality without sacrificing developer productivity

### Describe the problem or limitation you are having in your project

The requirement for explicitly typing the return type of functions in GDScript with the `UNTYPED_DECLARATION` warning enabled, leads to increased verbosity. Developers may disable useful warnings to avoid excessive typing, potentially missing out on the benefits of strong typing.

Besides that, users need to explicitly type the return of the function to get autocompletion on `f().`, this wouldn't be necessary when the type can be inferred.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expand GDScript's type inference system to include automatic deduction of function return types, similar to the `:=` operator for variables. This could be explicitly requested using a special syntax to indicate the desire for type inference:

```gdscript
func f()->:
  pass
```
This syntax signals the compiler to infer the return type. This gives users all the perks of having the return of the function typed without having to explicitly type it like autocompletion, etc.

One concern might be that a function's return type could become ambiguous without explicit types, but this can be mitigated by using the `INFERRED_DECLARATION` warning to enforce type annotations where necessary. Moreover, using a specific syntax for requested inference (`->:`) provides a clear indication of the developer's intention, avoiding accidental omissions of return types.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

User would type:
``` gdscript
func f()->:
  pass

func sum(a: int, b: int)->:
   return a + b

func()->: do_something()
```
Instead of:

```gdscript
func f() -> void:
  pass

func sum(a: int, b: int) -> int:
   return a + b

func() -> void: do_something()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, yes, if the user types the return type it could be workaround, this is more of a life quality feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Type inference is deeply integrated into the language's core, affecting the parser, compiler, and possibly the IDE tools. It's not feasible as an add-on because it changes the fundamental way the language is written and understood by the engine.

**Comment by AThousandShips** [comment]
This isn't really comparable with type inference for variables IMO, I don't see the value of adding just the arrow and not a type when the type is known, and when not known it is unsafe and simply ignores the untyped warning which is valid

It feels like it just allows using untyped functions while having the warning, which just feels backward to me, IMO you should be explicit or not, not both

**Comment by sandygk** [comment]
Just trying to understand why do you think is not comparable with type inference for variables? you don't see the value of adding the arrow and not the type, but you see value in adding the `:` in `:=` but not the type, if you don't mind, help me understand why is it valuable in one place and not the other in your view? To me the value is less typing which applies in both cases, right?

Is it because `->` is two characters instead of just one as in the case of `:`, just guessing.

I get the request is not popular, and that's ok, I'm not even trying to persuade. But I would love to understand why, if possible. 

I know TypeScript has a similar function where they infer the return type, for instance in the following case, it would complain if the argument `a` is not typed, but it doesn't complain if the return of `f` is not typed since it can be inferred
```ts
function f(a: string) {
  return a;
}
```

I wonder why the feature is welcome in TS but not in GDScript, just genuinely curious.

**Comment by AThousandShips** [comment]
Because `:=` takes the *known* type of the right hand side and applies it to the left, the right hand side *must* be well defined

However with a method this isn't the same, it isn't something as trivial or irrelevant as the number of characters, but the direction of operations here

The `-> Type:` syntax makes the return type explicit, whereas the `->:` syntax just silences an error, nothing more

I don't know anything of TS so that doesn't remotely apply here, I'm talking about GDScript and how it works, not some other language

However the TS case provided *is* just like a GDScript function *without* the `->`

**Comment by AThousandShips** [comment]
Now one place where this could be useful would be if we had more complex type overloading support, like:
```gdscript
func add(lhs, rhs) ->:
    return lhs + rhs
```

And it returns `int` if the two types are `int`, etc.

But otherwise having the `->` arrow *in my opinion* means you make a strong statement on what the return type should be, and communicate this not just to the compiler but to the user (and yourself), it also ensures that the return type is *correct*, you lose all that with the `->:` syntax

If you have the `-> Type` syntax it will complain if you make some error in the code for example

**Comment by sandygk** [comment]
Thanks for helping me understand, let me give you my two cents:

I understand this is not TypeScript, I just mentioned it as a point of reference, in the same manner we may mention a feature Unity or Unreal may have, this is just to illustrate the point, and provide a real life example where the feature exists and how it works and it's reception.

I wanted to point out that:

```ts
function f(a: string) {
  return a;
}
```

is not the same as:

```gdscript
func f(a: string):
  return a
```

because in TS f would be typed `(a:string)->string` where in GDScript f is typed as `(a:string)->undefined`

Also, it would only infer if possible, if not possible we would get the same warning we get when inferring `:=` is not possible, basically saying that the type could not be inferred, and you have to type it. That's what would happen in both examples you asked about.

> Now one place where this could be useful would be if we had more complex type overloading support, like:
func add(lhs, rhs) ->:
    return lhs + rhs

That sounds good, but wouldn't this check has to happen in runtime as opposed to compilation time?

**Comment by AThousandShips** [comment]
> That sounds good, but wouldn't this check has to happen in runtime as opposed to compilation time?

No, as I was saying, *when static typing is available*, i.e.

```gdscript
add(1.0, 2.0)
```

That's the only time static typing works anyway, it is only available on compile time

**Comment by sandygk** [comment]
oh I see

**Comment by AThousandShips** [comment]
> keep in mind func add(lhs, rhs)->: will still complain because the arguments are not typed

Well it wouldn't if the support for type overloads was available, hence why I gave it as an example of what it *could* be used for if the system was different

It was an example to point out where I think it might be useful, but also to that it doesn't, in my opinion, have any real use in the current code, and that being explicit about what you return is the proper way

**Comment by sandygk** [comment]
One last thing, I know this is a lost case, but I still fail to see why is it undesirable to infer the return of a function but not the return of an expression in a variable declaration using `:=`

> Because := takes the known type of the right hand side and applies it to the left, the right hand side must be well defined

In this case it would be the same:  `->:` takes the known type of the return expression and applies it to the function, the return expression most be well defined.

> However with a method this isn't the same, it isn't something as trivial or irrelevant as the number of characters, but the direction of operations here

Not sure what you mean by the direction of operations

> The -> Type: syntax makes the return type explicit, whereas the ->: syntax just silences an error, nothing more

What error do you mean? it doesn't really silence any error, if it can be inferred it infers it, if it cannot, the error is not silenced we give the warning, same as `:=` take `var a := 1 if condition else "one"` it will not silence the error if the type cannot be inferred

**Comment by AThousandShips** [comment]
I'm sorry I wrote out what I meant by all that in my previous comments, and I don't know how to explain it any more clearly than I already have, all those questions are things I've already answered

But what I mean with direction is:
With `var x := y` you have `y` which has a *well defined* type, or it won't work, that type is derived from some *explicit* type source, such as `func foo() -> Type:` or `var y : int`, with this syntax you have a ill-defined or undeclared type being inferred rather than carried over

The `:=` syntax *copies* the type from the right to the left, where the right type is well defined and given by what ever is there, however with this suggested syntax it still isn't guaranteed to be clear, and it isn't as simple as "it will error if it isn't defined", it's about how you take a method with multiple paths and dependencies and just have inferrence on that

My point is that the `:=` syntax simply takes a well defined type on the right, and copies it over, where as this takes some unknown type from the body of a method and just implies it, it says "you're allowed to infer it", where `:=` is "you are supposed to copy this", that's why I think they are not comparable at all

> What error do you mean? It doesn't really silence any error, if it can be inferred it infers it, if it cannot, the error is not silenced

The `untyped declaration` error, that would fire if you have `func foo():` but not with `func foo() ->:`, I'm not talking about the error when not inferred, I'm talking about the `untyped declaration` error, that's all, nothing else

**Comment by sandygk** [comment]
> with this syntax you have a ill-defined or undeclared type being inferred rather than carried over

But why do you call it ill-defined or undeclared, it's well-defined by the return expression of the function.

take for example:

```gdscript
var a := 1
var b := a
```

one could argue that the type of `a` is ill-define or undeclared, and it's being carried over to the type of `b`, I don't see how that's different from:

```gdscript
func a()->:
  return 1

var b := a()
```

why you call it ill-defined or undeclared for the function but not for the variable declaration

> it's about how you take a method with multiple paths and dependencies and just have inferrence on that

well you check the type of every return expression, they have to be the same, and you use that, if they are different then it cannot be inferred or more technically is a Variant type which still triggers the warning

> it, it says "you're allowed to infer it", where := is "you are supposed to copy this", that's why I think they are not comparable at al

I can of get this point but not really, the right-hand expression could be a complex operation with multiple ternary expressions, is not as simple as just infer this really clearly defined type. But if the point is, generally speaking the right hand side expression is usually just there, while the return expressions you have to dig for them, I can see that

> I see no use of it other than "I can't be bothered to add a type here but I don't want it complaining over no type being specified"

I agree, but I think that's a good reason, it basically lets the devs have all the advantages of typed functions without having to do the typing themselves, and is an opt-in feature. It's not really about silence the warning, it is about getting autocompletion and the other perks of typing without actually typing

**Comment by AThousandShips** [comment]
> I agree, but I think that's a good reason, it basically lets the devs have all the advantages of typed functions without having to do the typing themselves, and is an opt-in feature.

The way yo handle that is by turning of the warning/not having it be an error, I'd say that adding this functionality to have a half in half out opting of this feature isn't worth it

I'm sorry but I don't have time to further explain my points, my points are all there

Have a nice day 🙂

**Comment by sandygk** [comment]
>Have a nice day 🙂
Same to you my friend, and thanks for taking the time

**Comment by sandygk** [comment]
> The way yo handle that is by turning of the warning/not having it be an error

Well, not really, you will lose autocompletion of `f().` if you do that

**Comment by AThousandShips** [comment]
Now I would *love* this syntax and feature if GDScript had an "argument based" inferred system, so that the return type can be made dependent on the arguments, even possibly the argument *values* if they can be guessed, that would be worth the extra code and risks of implementing something like this (the risk being that adding any complexity to the parser and analyzer and compiler adds further points of failure, which has to be taken into account and weighed against the value of the feature)

Where, assuming the type of the arguments are known at compile time, the return type is also knowable through analysis, this would allow a kind of type overload with static typing, like the example I gave above

Otherwise however the cost of adding this, and the new points of failure, doesn't seem worth it to me, when the simple solution is to just be explicit about the return type, doing a little extra work to benefit from the features essentially

**Comment by dalexeev** [comment]
I think #8369 (implicit `void` type inference) has a better chance of being implemented than this, since it's already partially done in the compiler and DocGen and the lack of a non-empty return is more obvious for multiple code paths in function body. Although #8369 still has some issues.

As for the implicit inference of the non-`void` return type of a function, it seems to me that this can work in an obvious way only for one-line functions or for functions that have a single `return` at the end of the body (not nested in a condition/loop). For one-line functions we could add special syntax (including option with implicit type inference) but I'm not sure that's a good idea.

**Comment by HolonProduction** [comment]
> Well, not really, you still don't get autocompletion for `f().` without typing the return of `f` which is really the point of the feature, that you get the perks of typed code without actually typing it.

Not sure what you are talking about. The following gives correct autocompletion:

![image](https://github.com/godotengine/godot-proposals/assets/99511741/3784be1d-8590-4b55-bdb7-590a83707600)

We always do interference for autocompletion. The difference is, that this is a best effort thing which isn't guaranteed to work for complex cases with code paths. So this syntax isn't needed for autocompletion at all. It would just allow to use these interfered return types as well defined later on. Which does not make much sense as stated before.

**Comment by sandygk** [comment]
Oh that's nice! I didn't know that. That's really great! I still think there is value in inferring the type instead of having to explicitly type it. Again, it gives the dev the advantages of typed code without the cost, which is a win-win on my book. Like it would error out if you try to set a variable of the wrong type for instance, regardless of whether it was inferred or explicitly typed.

I understand this should be an opt-in feature, but I see value in it, specially for new devs that are new to typing, this is a good way to introduce them to the concept. Again, this is how it works in languages like TypeScript, it's not something I came up with or anything like that, it's a proven concept.

I understand that nobody agrees with me here, and that's ok. Just sharing my view.

**Comment by Calinou** [comment]
Closing due to lack of support (see comments and reactions on OP).
