### ISSUE TITLE
Changing the default editor-viewport-camera to look backwards instead of forward

### ISSUE THREAD

**Issue by desperate-coder** [godotengine/godot-proposals#843]
**Describe the project you are working on:**
Working on a 3D-Topdown-Shooter game as a hobby.

**Describe the problem or limitation you are having in your project:**
More of an inconvenience: New Godot-users, especially coming from Unreal Engine 4, could be confused by the way how the default-camera orientation is to be interpreted, as in: The figure is looking at me, therefore it must look in the right direction.
This albeit is as often clarified wrong and the figure is supposed to look at one with its rear, so to speak.
In some cases this could break a workload of long and arduous implementations, just so to correct this little mishap.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Simple: Turn the default in-editor camera around, so that instead when opening the scene one will not be greeted by the figures rear ;)
An streamlined example could be taken as it is done in the Unreal Engine, whereas the models face their forward axis (+X) from the beginning and the camera is looking backward at the model.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The suggestion of making the camera by default look backwards could prevent the aforementioned kind of confusion, without changing any OpenGL-convention at all, by forcing, especially new users, to adapt their models to face the right direction right away.
Therefore it would ensure the right export-settings from the beginning, also adding to the user-friendliness for new users of the engine as a bonus.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Possible by creating additional bloat, but in general it appears code will not work properly at all (especially the "look_at"-method) and the proper solution seems to rotate the model itself mostly (causing the said confusion in the first place)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it would be a change affecting the already present editor-solution.

**Comment by Calinou** [comment]
The editor's camera orientation is preserved when you save the scene (or at least, it's supposed to). So, this would only apply when creating a new scene.

**Comment by desperate-coder** [comment]
Thank you for replying, and indeed it is only an issue if you open a new scene.

Of course, as hinted by @Calinou , in the end it becomes only an issue if you arent aware of the OpenGL-convention.
Just in my mind it makes the editor a little inconvenient in the role of a resource-viewer by always reminding that the initial view has to be considered the backview of a model, whereas the said orientations could be the default one and put away some confusions in beforehand.
This is additionally confusing with the labels on the corners, as in these examples, as a side-mention:

![worlds_turned_back](https://user-images.githubusercontent.com/65235946/82067699-5cf34700-96d1-11ea-86c2-8a07ae6d703c.png)
![worlds_turned_front](https://user-images.githubusercontent.com/65235946/82067703-5e247400-96d1-11ea-97a7-52fb8d5fa747.png)

Well i just thought it may be helping to make Godot more friendly to especially newish users.

**Comment by salahchafai** [comment]
i totally agree with this

**Comment by Calinou** [comment]
@salahchafai Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by aaronfranke** [comment]
I don't think this is a good idea, for many reasons. The default editor camera should point roughly forward (-Z or north), which is the default orientation for creating new cameras and other objects too. The default editor camera should keep the same default forward direction.

Aside from 3D characters facing -Z (north) by convention and you having a desire to have the default camera orientation set to view their front, many nodes are designed to be viewed *from* +Z (south) with a camera pointing forward. For example, a Quad mesh in the default orientation is only visible when the camera is +Z from it. This shouldn't be changed, since if you create a Quad mesh and a camera, the Quad mesh is visible from +Z (south) by objects looking -Z (north), and cameras point -Z (north) by default. So if Quad meshes shouldn't be changed, then this proposal would cause Quad meshes to become invisible to the default editor camera since the editor camera would be -Z (north) of the mesh, but the mesh is only visible from objects south of it. The same problem exists with Sprite3D, but in that case it becomes mirrored instead of invisible.

There is also the ease of use for transform gizmos to consider. If [#39372](https://github.com/godotengine/godot/pull/39372) is merged, then the default camera allows easily using the transform gizmos.

![](https://user-images.githubusercontent.com/1646875/83976145-3b4b4100-a8c6-11ea-909b-053dde2d4e45.png)

For all of the above reasons, I vote to close this proposal.

**Comment by aaronfranke** [comment]
This proposal is mutually incompatible with [#39372](https://github.com/godotengine/godot/pull/39372), so I'm closing this.
