### ISSUE TITLE
Add style inheritance for theme items

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-proposals#850]
**Describe the project you are working on:**
Basic project

**Describe the problem or limitation you are having in your project:**
I have styles for button normal, pressed, hover, etc. If I want to change 1 shared parameter (e.g. border color), I have to do it all manually on each of them. Kind of a problem if I decide I want a major UI style change for many controls.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Inheritable styles

Style A is the base style (StyleBoxFlat).
Style B (StyleBoxFlat) inherits Style A.
Changing a parameter on Style A also changes it on style B, unless it has been overriden.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I tried doing this with GD Script with a custom inspector and an exported property. I could get the base style to work, and the child style to 'inherit' it... but the issue was that I could not update the child when the base was updated. There was no easy signal to connect to when the base was changed. I didn't go very far with this trial... Maybe it needs a custom type for both 'base' and 'inheritable' classes, but at this stage I would say it could be easier to implement natively.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not sure - see above comments. Maybe it could... but useful to have it as native functionality.

**Is there a reason why this should be core and not an add-on in the asset library?:**
See comments above - this is debatable.

**Comment by bojidar-bg** [comment]
While it is possible to make different stylebox classes/resources have a "parent"/"base" property which is the same-typed stylebox they inherit, this might be a bit of a mess.

Maybe, a system similar to how scene inheritance works could be nice?

---

Details:

Resource would get a new property: `base` or `

**Comment by fire** [comment]
As far as I know the current theme system is through a cascading styles system. The parent-most node theme properties are overriden by children nodes.

**Comment by bojidar-bg** [comment]
@fire I was thinking of the same, but check the issue carefully: The proposal is not to inherit the whole styleboxes, but to be able to override only part of a stylebox in another.

**Comment by EricEzaM** [comment]
@fire Yes, you can place new themes on child nodes to change their styles. But still the problem that this proposal addresses is apparent.

Say you have 5 StyleBoxFlat's that you use for your buttons. You all have the same border width on them. Now, you want to change it. You have to go to all 5 resources and change it individually - which is annoying to find, and time consuming to do.

This proposal would address this by making the system similar to inheritable scenes.

All 5 StyleBoxFlats have a "Base" StyleBoxFlat. Now, if you want to change the border thickness, you can just go to the base style and set it there, and the children would update - just like scenes. You would of course be able to override properties in child styles.

**Comment by EricEzaM** [comment]
Proof of concept:

Changing the borders in 3 different styles with one change in the base style:
![inherit_styles_1](https://user-images.githubusercontent.com/41730826/91860729-610e9900-ecaf-11ea-8a18-58b2ba5da764.gif)

**Comment by EricEzaM** [comment]
In this case, the green box has overridden the border width to 50, and so changes to the base class do not change it:

![inherit_styles_2](https://user-images.githubusercontent.com/41730826/91861660-6ddfbc80-ecb0-11ea-9c1d-77a3bb678b99.gif)

**Comment by EricEzaM** [comment]
Further examples, show real use case. Here I have 4 buttons with their own style.
![image](https://user-images.githubusercontent.com/41730826/91978168-0afd2c80-ed67-11ea-9dd9-2683fbaca97b.png)

Currently, I have only edited their "Base" which they all share, `red_base.tres`.

I can edit each individual stylebox as needed. I will make hover lighter, pressed darker, and disabled very dark:
![image](https://user-images.githubusercontent.com/41730826/91978501-8a8afb80-ed67-11ea-9a79-a9d1a3b65f74.png)

Cool! However, later I come back and decide that I want the borders to be bigger. Jeez, what a pain! I need to go through each stylebox for `Disabled`, `Hover`, `Normal` and `Pressed` and change them all individually.

But thanks to the base style I don't have to!
![inhert_styles_example](https://user-images.githubusercontent.com/41730826/91978772-0dac5180-ed68-11ea-9af0-35afb1ce7d6f.gif)

**Comment by Zireael07** [comment]
Yeppers, I have something similar in one of my games, several styles that only differ in details.
Currently the workaround is to have several .tres files, and create any more via Save As... button. This is not real inheritance, because if I change something in the first ("base") file, it's not reflected in the others, obviously.

**Comment by pycbouh** [comment]
This is not true inheritance as this only allows to customize on top of the base class, but I think https://github.com/godotengine/godot/pull/47544 covers this proposal.

**Comment by pycbouh** [comment]
So, @EricEzaM, do you think that https://github.com/godotengine/godot/pull/47544 and https://github.com/godotengine/godot/pull/50169 reasonably cover this proposal or if something crucial is still missing?

Unfortunately, this is not portable to 3.x at the moment, so if you want to test it you need to build `master`.

**Comment by Calinou** [comment]
Closing, as the original concern should be reasonably well addressed by https://github.com/godotengine/godot/pull/47544 and https://github.com/godotengine/godot/pull/50169 now.

https://github.com/godotengine/godot/pull/57942 also backported type variations to Godot 3.5beta2 and later.

**Comment by Lamby777** [comment]
> Closing, as the original concern should be reasonably well addressed by [godotengine/godot#47544](https://github.com/godotengine/godot/pull/47544) and [godotengine/godot#50169](https://github.com/godotengine/godot/pull/50169) now.
> 
> [godotengine/godot#57942](https://github.com/godotengine/godot/pull/57942) also backported type variations to Godot 3.5beta2 and later. [godotengine/godot#49487](https://github.com/godotengine/godot/pull/49487) is a partial backport of [godotengine/godot#47544](https://github.com/godotengine/godot/pull/47544) with breaking changes omitted.

Unless I'm missing something, this doesn't solve it for styles because you can't actually inherit styles... You still need to make an entirely new variation with a duplicated style just to change 1 thing on the style, and then you get the same problem of it being annoying to edit 1 minor thing on all styles at once (in my case, trying to make a zero-margin version of a panel). Only marginally better than theme overrides since you can edit the style in one place, but that's not relevant to this specific issue of wanting to extend styles themselves. :/

**Comment by YuriSizov** [comment]
@Lamby777 Indeed, the problem of overriding parts of styleboxes is not resolved yet. It's now tracked in https://github.com/godotengine/godot-proposals/issues/8094 I guess. Although the problem at its core is lack of resource/data inheritance, see https://github.com/godotengine/godot-proposals/issues/4089.

**Comment by hsandt** [comment]
Yeah, I just wanted to override the font size for a certain sub-menu, and found no way to do so. I tried Theme > Settings button > Base Type but I get this for Button because it's a native type:

![image](https://github.com/godotengine/godot-proposals/assets/1067772/a35a750e-2286-4367-9315-5607f2e87089)

There is no Inherited Resource system, but I suppose we could still implement it specifically just for themes, having an (override) theme refer to some base theme as a hardcoded field?

Should we reopen an issue for the broader problem of inheriting theme properties (including the "meta properties" of font and font sizes)?

**Comment by Calinou** [comment]
> Should we reopen an issue for the broader problem of inheriting theme properties (including the "meta properties" of font and font sizes)?

Yes, I'd say this warrants a separate proposal.

**Comment by onesuchkeeper** [comment]
If theme items recieve inheritance, theme resources themselfs should also recieve it. If not in the resource files at least programatically. Currently in order to tweak a single value dynamically and apply that only to a particular scope, the entire theme would have to be coppied.

Instead you could make a local theme inheriting from the base theme and just set the property you want to tweak.

This connot be acheived with a simple addon becuase Theme's getters and setters can't be overridden.
