### ISSUE TITLE
Use AI language models to summarize error messages in the console to facilitate the resolution of bugs

### ISSUE THREAD

**Issue by BCG-Jackson** [godotengine/godot-proposals#8514]
### Describe the project you are working on

I'm making a 3D RTS.

### Describe the problem or limitation you are having in your project

I encounter errors in the debug console because I am new to godot and don't know what i'm doing and understanding the cause of the error takes considerable time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want a more concise understanding of console errors and tracebacks so that I don't have to spend as much time figuring out problems with simple solutions. If an AI language model could understand the context of the problem and offer simple solutions, it would dramatically increase my learning rate.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Look at this 

![image](https://github.com/godotengine/godot-proposals/assets/12786535/0be6ab05-9d5c-4312-bb34-5b6e045fd6f0)

this is very scary to people new to game development, and may be the biggest thing turning people away. My course of action to resolve one error is to click the dropdown and pray there is a line number hidden in this block of text to one of my files to give me a hint of where to look for what the actual problem is. When the error isn't in one of my files, my only course of action is to turn to the internet for help, hoping someone else knows what is going on. Many times the help I go to is ChatGPT. It does an alright job of helping me code, but does not offer a lot of help in regards to context dependent bugs in the editor. 

What if there was a button next to each error message that would use AI to help find a concise solution. Clicking it would do make some API calls, send some data about the context of my project and the error message, load for a while, then print natural language in place of the scary red stacktrace telling me about what might have went wrong, and how to fix it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used every time if it existed because it solves error messages.

### Is there a reason why this should be core and not an add-on in the asset library?

I suppose this feature wouldn't be too different from the OpenAI GPT Chat plugin already available as an add-on, but this feature would incorporate the context of the godot editor, which may require some core integration.

I know its a big ask, but I believe this feature would put godot ahead of every other game development engine alive today. Dealing with bugs and errors is the biggest force causing would-be developers to give up. If that was easy, it would clear the tightest bottleneck in the game development process.

**Comment by Zireael07** [comment]
ChatGPT and other tools like that are NOT meant to be used for coding.

Also, there is a phenomenon known as AI hallucinations, it's currently about as likely to help as to make things worse.

**Comment by TrebbleBiscuit** [comment]
> ChatGPT and other tools like that are NOT meant to be used for coding.

How do you figure? I just went to ChatGPT and one of the suggestions it gives me is "show me a code snippet". Hallucinations are definitely a problem, but I wonder if even so a response could provide more value to a newbie than a stack of inscrutable `NullReferenceException`s

**Comment by YuriSizov** [comment]
> but I wonder if even so a response could provide more value to a newbie

You wouldn't know. There is no guarantee and no way to debug. The LLMs are designed to construct the most likely sentence, not the most correct one. They will be happy to spread popular misconception on top of casual hallucinations.

Error messages are easily googlable. You can find other people who faced them by copying the text and going to a search engine. This is true for every programmer's tool, actually.

You can also drop the message to any of our help channels and get a response from someone who understands it or has prior experience with it. Talking to people can also broaden your understanding of the issue, because people can introduce extra context to it. LLMs cannot. 

It's way more reliable than asking a language model to guesstimate what the most probably collection of words should be sent in response to your query.

**Comment by BCG-Jackson** [comment]
Wow, didn't expect such a negative response. I really can't imagine a future where this feature never exists, but I guess Godot won't be first.

**Comment by AThousandShips** [comment]
AI might be the future, but it is far, *far*, from mature enough to actually be reliable for these things, and LMs might never be simply because of how they work, as pointed out above. And no, Godot won't be the first to grab a novel and fad idea that hasn't been proven, that on the contrary has been shown to be highly unreliable and harmful, which is at best unhelpful.

Let's not jump on the latest fad idea just because of how hyped they are

**Comment by markdibarry** [comment]
There's many reasons why this isn't a good solution that others have touched on, but a few more I'd like to cover:
1. It would require sharing information with a third party that many users may be uncomfortable with, but all users would have to opt into to use Godot.
2. It would require relying on a third party api that Godot would have to pay for.
3. It would invite an overwhelming amount of new issues akin to "the AI button gave me wrong/malicious info" that we would not be able to help with.
4. It would require real-time reliance on a third party (Godot has no part or control over), so there would be no guarantee of current or future availability, bug-fixes, or viability of the responses.
5. There is no guarantee that the LM are pulling from current data or what version you're using, so even if it happened to give advice that was related to programming, related to Godot, related to the specific language you're using with Godot, and even correct, it may be correct for the wrong version or horribly out of date, so it could lead you even further from your needs, and there'd be nothing we could do to help.

**Comment by Zireael07** [comment]
> How do you figure? I just went to ChatGPT and one of the suggestions it gives me is "show me a code snippet".

That's a really big surprise to me, as lots of people have discovered code snippets given by ChatGPT are balderdash to put it politely (it suggests functions that don't even exist in a given language). ChatGPT was created as a language model, not a code model. Many programming sites outright ban questions and answers using ChatGPT due to the amount of problems the output has.

(I mean ChatGPT in general - models trained specificially on code such as GH Copilot *may* be better but I would also be wary of the end results

**Comment by Calinou** [comment]
Closing due to lack of support. Also, note that such a feature wouldn't be able to work out of the box as you need an API key to contact any AI service out there (for resource usage reasons), and access through API key is rarely free.
