### ISSUE TITLE
Implement `deferred` block in GDScript (`(func() -> void: ... ).call_deferred()` syntactic sugar)

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#8551]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Since there has been a lot of functions needing calling with `call_deferred()`, we sometimes hope to see such a grammar chunk that quotes the whole area to be called the way as `call_deferred()`
### Why not `await get_tree().process_frame`?
Good question: think about this problem:
```GDScript
if <some conditions>:
    await get_tree().process_frame
    ...

if <some conditions 2>:
   ....
```
See the question? When we hope the two functions are to be called all, the first call will delay the rest part's calling, which is not what we hope to see in some situations. 
### How about lambda.`call_deferred()`?
So what about a lambda with `call_deferred()`?
```GDScript
(func() -> void:
    ....
).call_deferred()
```
Seems pretty good and this will not block the regular process of the rest ones; however, this is a bit type-costy as we prefer a more lazier and sweeter way to defer a chunk of codes.  

I mean, why not **find a shorter way for `(...).call_deferred()`**?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Thus, we expect to see a `deferred` chunk, to quote a chunk of codes that should be executed deferredly.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This key word works makes a chunk where the codes with the same tabs are called at the time the `call_deferred()` method is called by the engine. See:
```GDScript
func somefunc() -> void:
    ....
    deferred:
        .... # These codes will be called at the time the call_deferred() method gets called
    deferred:
        .... # These codes will be called after the previous chunk of deferred codes are done execution
    # This is equivalent to:
    (func() -> void:
        .... # Lambda mode
    ).call_deferred()
```
Not only multiple lines, but also single line of code is ok:
```GDScript
func somefunc() -> void:
    ....
    deferred: .... # Single-line mode
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, see the description

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, see the description

**Comment by adamscott** [comment]
The idea is interesting, but it's important to differentiate the two "types" of defer.

There's the `call_deferred()` way, that is called [at the end of the current frame](https://docs.godotengine.org/en/stable/classes/class_callable.html#class-callable-method-call-deferred). This is the "defer" that targets this proposal.

And there's the Go `defer`, which is to call a function at the end of the current function. This is NOT what this PR wants.

IMHO, if we implement a defer keyword someday, it should be related to the "Go" way instead of being related to the current frame.

@ Lazy-Rabbit-2001 Could you update your proposal to show us in what way this cannot do everything your `deferred` block would do?
```gdscript
(func ():
    print("hello")
).call_deferred()
```

The philosophy of Godot is to identify problems first, then think of a solution. Here, I don't really see an existing problem.

**Comment by adamscott** [comment]
> and potential and existing bugs with it

Like what?
