### ISSUE TITLE
Add set_bone_pose(bone_idx : int, t : Transform3D) to Skeleton3D

### ISSUE THREAD

**Issue by soppermann** [godotengine/godot-proposals#8869]
### Describe the project you are working on

A VR game that procedurally poses a Skeleton3D

### Describe the problem or limitation you are having in your project

There is no Skeleton3D function that accepts a Transform3D to get a bone's local transform. I currently set_bone_pose_position(), set_bone_pose_rotation() and set_bone_pose_scale(), which adds unnecessary lines of code, is less efficient, and I believe it can't be used to properly set all possible transforms (i.e. shears).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding set_bone_pose(t : Transform3D) to Skeleton3D turns three lines of code to set local transform into one and allows for any valid Transform3D.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Currently, I have:

```
func set_bone_local_transform(skeleton : Skeleton3D, bone_idx : int, t : Transform3D):
	skeleton.set_bone_pose_position(bone_idx, t.origin)
	skeleton.set_bone_pose_rotation(bone_idx, t.basis.get_rotation_quaternion())
	skeleton.set_bone_pose_scale(bone_idx, t.basis.get_scale())
```

With the change, it would be:

```
func set_bone_local_transform(skeleton : Skeleton3D, bone_idx : int, t : Transform3D):
        skeleton.set_bone_pose(bone_idx, t)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm unaware of a way to access and set the local transform of each bone directly, and using set_bone_pose_position(), set_bone_pose_rotation() and set_bone_pose_scale() is a workaround in most cases, I'm unsure if it will work as expected for every possible Transform3D.

### Is there a reason why this should be core and not an add-on in the asset library?

set_bone_rest() and set_bone_global_pose_override() already do this for rest poses and global poses. It makes sense to do the same for the bone pose.

**Comment by goatchurchprime** [comment]
It appears that this is now in 4.3, according to the docs https://docs.godotengine.org/en/latest/classes/class_skeleton3d.html#class-skeleton3d-method-set-bone-pose

It looks like it got in with this humongous Pull Request https://github.com/godotengine/godot/pull/87888 so it can probably be closed.

Just as an aside, another reason that we needed this is that it's sometimes necessary to apply non-orthogonal bone transforms in a skeleton that will compose into orthogonal transforms.  For example, if you want to undo a scaling in one axis on the previous bone, apply a rotation, and scale back in a different axis you need to multiply by a non-orthogonal basis.

**Comment by Calinou** [comment]
Closing per @goatchurchprime's comment.

**Comment by goatchurchprime** [comment]
I've hit a very big issue with the implementation and capabilities of [Skeleton3D::set_bone_pose()](https://github.com/godotengine/godot/blob/d2ada64a03d2abdb97cafe8f10623db8a2ce1d4c/scene/3d/skeleton_3d.cpp#L840), which is implemented thus:
```C++
bones[p_bone].pose_position = p_pose.origin;
bones[p_bone].pose_rotation = p_pose.basis.get_rotation_quaternion();
bones[p_bone].pose_scale = p_pose.basis.get_scale();
```

This does not actually set it to the value of the transform unless it is semi-conformal -- by which I mean that the scale can be different in each of the axis.  

We need non-semi-conformal transforms on bones if we want to stretch a bone along its conventional y-axis, since we have to invert the scale before the rotation of the next bone is applied.

This function name is extremely misleading, and the [Skeleton3D::set_bone_pose_scale(int p_bone, const Vector3 &p_scale)](https://github.com/godotengine/godot/blob/d2ada64a03d2abdb97cafe8f10623db8a2ce1d4c/scene/3d/skeleton_3d.cpp#L876) should actually be `Skeleton3D::set_bone_pose_scale(int p_bone, float p_scale)`.

I need to write up a proposal where the bone-scale is absolute instead of relative since the system does not let us set arbitrary transforms (possibly because they cannot be animated).

**Comment by Calinou** [comment]
@goatchurchprime Please open a new proposal for this.
