### ISSUE TITLE
Add "Search with Google" to the right click context menu when selecting text

### ISSUE THREAD

**Issue by ndriqa** [godotengine/godot-proposals#8933]
### Describe the project you are working on

I'm working on a 3D Pixel Art game. But this one was needed in any project I've worked on.

### Describe the problem or limitation you are having in your project

There are some keywords that I quickly need to know the meaning of or errors that I need to find the cause of as quickly as possible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way for me to quickly Google or Community Forum search the selected error, code, keyword, etc.,

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Whenever I select some text, and right-click on the selection, below the "Copy" option, add another context menu option to search the web quickly. When I click on it, open the default browser and search engine with the selected text as the query. I am also an Android developer, and the Android Studio IDE has this feature and it's super handy. Here's what it would look like:

![image](https://github.com/godotengine/godot-proposals/assets/32796182/7b8791dd-c23d-4478-8deb-fd45169da18e)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This definitely can be added as a plugin, but I know this would be used quite often for it not to be core.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the code editor and making it very convenient to use. This one should be core because it would be used so often by so many. We all know Google is our friend, for all of our programming journeys, and by Google, I also mean Bing or any other search engine you have set by default. It's just that there's an option to do research more conveniently.

Here are the steps ***without*** this feature:
1. Select a word you don't know what it does
2. Copy
3. if you don't have the browser open, open it
4. switch windows (open a new tab if you don't want to lose the current one)
5. paste it on the search bar
6. enter

Here are the steps ***with*** this feature:
1. Select a word you don't know what it does
2. right-click
3. Search with Google

**Comment by JoNax97** [comment]
This is a very useful feature to have.

I think it would be useful to combine this with the docs function. This way, if the selected token is a GDScript keyword or part of the Godot API, you go straight to the relevant docs page. Otherwise, a web search is opened. Also, bind this to a key (I'd like F1 to mimic the jetbrains IDEs, but this is minor since it can be configured).

Finally, in the spirit of Godot, I'd try not to tie it to any search engine. Call the option "Web search" or similar. And there should be a way to open the default browser with a search query that is then sent to the user's default search engine.  I'm not sure there's such a thing that works across OSs, though.

**Comment by ndriqa** [comment]
I agree. And I definitely didn't mean to tie it to a specific search engine, I only took "Search with Google" as an example since it's present on JetBrains IDEs.

**Comment by JoNax97** [comment]
I think that, sadly, the direct mention of google has caused a lot of negative sentiment. It might be worth reworking this into a new proposal, as I don't think many people would be against the core idea.

**Comment by AThousandShips** [comment]
Google isn't the reason I'm against it for one, it's the applicability of automatic searching, from the script editor, I don't consider it very useful and it just saves you a very little amount, and you might generally want to search for more than just the keyword or name

**Comment by ndriqa** [comment]
I respectfully disagree. I don't mean to search only the keyword, I mean the whole selected text. Eg. I sometimes use it to web search an error stack trace part, a debugged value, a keyword missing documentation, and not even just a code part, it could be any selectable text, eg. an Editor option that you don't know what it does or what it represents. 

But I agree that it could cause various problems if maliciously configured.

**Comment by AThousandShips** [comment]
Still just a tiny bit of extra work, are you going to type out the rest of your search term in the editor before searching? You can still select anything you want to search for, I didn't say just searching the keyword, but more than what you would ever have in the editor, unless again you want to type it out temporarily, in that case it doesn't really save you any work, in my opinion (and no need to respectfully disagree, I'm just presenting my opinion 🙂)

**Comment by Mickeon** [comment]
> There are some keywords that I quickly need to know the meaning of [...]

I feel like the need for this feature in the first place only highlights the current issues with built-in docs. It's like users wanting to disable autocompletion outright (back in early 4.0) because of how **bad** it was compared to 3.x.
The issue that some keywords just cannot have related documentation is fairly up there, in my opinion. That needs to be improved upon. I'm not just thinking "GDScript keywords", I also refer to just being able to quickly look up e.g. "Inspector dock", and either refer to built-in or online documentation. Rapidly googling these doesn't help, it's too broad.

> [...] or errors that I need to find the cause of as quickly as possible.

Not necessarily against this, actually. I get where it is coming from, but if it's explicitly about googling errors it really would be a few clicks away, and I have not personally been in the situation of getting so many errors I have to "rapidly" open new tabs to look them.
One may argue that if you explicitly have to do that, somewhere in there a bug in Godot's code needs to be fixed, because we would never want the developer to be in that situation of utter confusion.

**Comment by Calinou** [comment]
Closing due to lack of support (see comments and reactions on OP).
