### ISSUE TITLE
More configurable/custom colors for visible collision shapes debug option (already implemented in 2D)

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#906]
**Describe the project you are working on:**
N/A (generic issue)

**Describe the problem or limitation you are having in your project:**
Difficulty to pick out collision shapes, especially when they overlap (it's more pronounced in 2D than 3D)
Tangent: collision shapes and navmeshes/navpolys coexisting in the same project exacerbate the problem even further.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Different collision shape colors would help differentiate between shapes, esp. overlapping ones.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In the original issue, @Calinou suggested either randomly selecting colors or exposing a custom_color option.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not possible to work around AFAIK.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Can assets even touch debug collision shape setting in any meaningful way? IIRC no.

Original issue: https://github.com/godotengine/godot/issues/31283

**Comment by Calinou** [comment]
> Difficulty to pick out collision shapes, especially when they overlap (it's more pronounced in 2D than 3D)

The overlapping issue should be partially addressed by https://github.com/godotengine/godot/pull/34923.

**Comment by Coldragon** [comment]
I'll add here the info from my https://github.com/godotengine/godot-proposals/issues/1143 proposal wich focused only in the 3D part of the colision shape.

It propose to show faces with custom color **and/or texture** and also an "Editor Only" checkbox.

Describe the feature :
> - With color/texture customization it will help gamedesigner to see directly what is the purpose of each area and have a readability of the current scene (Differentiate for example "Ladder", "Spawn", "Damage", "Loose" etc...)
> - It help to set their size more precisly because you see where they ends when some of the edge are through a wall or something else.
> - The Editor Only will let you draw them at runtime without drawing all the other ColisionShape and let you read the screen precisly

Describe how your proposal will work : 
>- A Checkbox on the Shape (or the Area/Body, need to be questionned) to show the faces.
>- Editor standard Color/Shape faces in Editor Configuration. Shape custom Color/Texture to differentiate it.
>- "Editor Only" checkbox to see the shape at runtime without showing every shape with the "Visisble Collision Shape" config.
>![image](https://user-images.githubusercontent.com/471393/86121192-e15d2600-bad5-11ea-9af9-4aec91a63106.png)

**Comment by dalexeev** [comment]
@Calinou @Coldragon There is a similar PR for `CollisionShape2D` (https://github.com/godotengine/godot/pull/39072).
Do I need to rename `debug_color` to `custom_color` for consistency with https://github.com/godotengine/godot/pull/40123?

**Comment by Jummit** [comment]
debug_color is more descriptive and makes it clear this is for debugging purposes only.

**Comment by dalexeev** [comment]
@Jummit I just think whether it is necessary to implement the `editor_only` option.

**Comment by golddotasksquestions** [comment]
For quick and fast prototypes or testing mechanics, I often just use CollisionShapes without any graphics and run with "visible Collisionshapes". Unfortunately the only way to differentiate CollisionShapes is via modulation (color value multiplication), and this prevents colors like red to show up. Pretty much the only visually distinguishable choice is green and blue.

I would really really appreciate to be able to choose any color I want for my Collisionshape and also be able to adjust opacity to my liking. This would speed up prototyping by a lot, as in many cases it would make the use of graphics unnecessary while testing mechanics. Even full games could be made without graphics that way. Less nodes, faster production, easier workflow. Therefore I would not want this to be restricted to debug only @Jummit

**Comment by Xrayez** [comment]
Alternative proposal (likely the same motivation): #1126. Basically my idea is to not modify the `CollisionShape2D` at all and provide a separate node for this. See goostengine/goost#2 where I've already implemented such a node. The idea is that it could work for any node, as long as it has `shape` property in parent, and not only the `CollisionShape2D` (I mean, what about `CollisionPolygon2D`?).

Of course being able to override the color in `CollisionShape2D` would be faster for prototyping purposes in comparison. But you could also create your custom node with `CollisionShape2D/VisualShape2D` nodes already instantiated. I haven't considered this option before because you need to modify the built-in nodes to achieve this, and this can be already implemented via plugin/module as you see.

So, you can treat `VisualShape2D` to be a replacement for a `Sprite` for collision objects, and it would also (hopefully 😄) work once exported (it wouldn't be necessarily tied to `debug/editor` mode, but I've provided an option to emulate this behavior anyway).

**Comment by Mayt38** [comment]
I'll add a small thing : when a collisionpolygon2D (maybe 3D as well I don't know) is disabled it doesn't change visually, unlike a collisionshape2D (which turns gray). It could be nice if they could become grayish, more transparent or something!

**Comment by KoBeWi** [comment]
Why not just use `modulate` property? The default shape color can be changed in Project Settings, so just change it to white and use modulate (or self_modulate).

**Comment by dalexeev** [comment]
Then the default color of the collision shapes will also be white, which is inconvenient. `modulate` is somewhere at the bottom of the inspector, and `debug_color` is at the top.

**Comment by golddotasksquestions** [comment]
@KoBeWi 
The difference is having to change the color of every CollisionShape, only so you can change one, vs just changing it where and whenever you need. 
If a user wants to change the default for all shapes they can still do so in the project settings. If a user wants to change a color of a particular object's CollisionShape, they should do it in the settings of this particular object.

It's anything but obvious for a user to make a change in the project settings, if they don't want to make a project wide change but an object wide change.
Forcing users to go and find this route over the project settings is exactly the kind of mindset that creates so many of Godot's absurd and counter intuitive UI flows. Besides just not being the same.

**Comment by timothyqiu** [comment]
> Then the default color of the collision shapes will also be white, which is inconvenient. `modulate` is somewhere at the bottom of the inspector, and `debug_color` is at the top.

To have the best of both worlds, I think the default shape color in project settings can be changed to affect the default modulate color instead of base color.

**Comment by MickL** [comment]
There is an [open PR](https://github.com/godotengine/godot/pull/39072) for some time now. Is this targeted for any upcoming 3.x or 4.0 release?

Being able to set different colors is SUPER useful do differentiate between different collision-types, e.g. collision, hitbox, hurtbox:

<img width="582" alt="Bildschirmfoto 2021-12-16 um 16 25 55" src="https://user-images.githubusercontent.com/5103210/146399659-7d5e0be5-6639-4598-bc5d-5573f54f6815.png">

In addition I wondher why CollisionPolygon2D has a different default color than CollisionShape2D. Personally I would make them the same default color:

<img width="594" alt="Bildschirmfoto 2021-12-16 um 16 27 27" src="https://user-images.githubusercontent.com/5103210/146399822-614e0b5f-0741-4f6e-987d-9acda864042e.png">

**Comment by Zireael07** [comment]
Seconding the above question.

**Comment by Calinou** [comment]
> In addition I wonder why CollisionPolygon2D has a different default color than CollisionShape2D

Convex decomposition is used on CollisionPolygon2Ds, and the different color lets you notice where the decomposition is done. Having too many polygons can impact performance negatively, so it's important to keep this distinction within each CollisionPolygon2D.

Once we support custom colors, I guess we can distinguish individual convex polygons within a CollisionPolygon2D by using different HSV values for each polygon.

**Comment by MickL** [comment]
> Once we support custom colors, I guess we can distinguish individual convex polygons within a CollisionPolygon2D by using different HSV values for each polygon.

This sounds like a very good idea!

**Comment by KoBeWi** [comment]
Yeah, even the PR says that it closed the proposal only for 2D, but GitHub obviously did not recognize that xd

**Comment by cybernaut4** [comment]
I think debug custom coloring CollisionShape3D is paramount for a comprehensive reading of each level scene to identify:

- damaging areas (be it swimmable lava or walkable burning sand, Area3D and StaticBody3D respectively)
- instant game-over falls (Area3D)
- player's pickup area size (Area3D)
- chosen structures that will disappear if player hides from the camera (StaticBody3D)
- multi-purpose triggers

I would leave blue only for standard collision procedure (movable entities) but everything else has to use a different color, otherwise it can get chaotic. 

AFAIK in 4.0, there's no such thing as Modulate property for CollisionShape3D, only for CanvasItem nodes.

**Comment by golddotasksquestions** [comment]
> AFAIK in 4.0, there's no such thing as Modulate property for CollisionShape3D, only for CanvasItem nodes.

A modulate would not help. If set, the custom color needs to completely override (replace) the default one.

**Comment by SirPigeonz** [comment]
There was PR implementing this for 3D but was closed by authoer for some reason (he deleted his branch).
Code can be salvaged here https://github.com/godotengine/godot/pull/40123

**Comment by SirPigeonz** [comment]
This proposal is probably better fit: https://github.com/godotengine/godot-proposals/issues/5196

**Comment by Calinou** [comment]
> This proposal is probably a better fit: #5196

These have different use cases. This proposal is about customizing the debug gizmos created by collision shapes, which is important for level designers as you don't want them to require scripts to customize the color of a collision shape for a specific element.

**Comment by Calinou** [comment]
Regarding whether debug collision shapes should have a texture or not:

If you use a solid unshaded color, there is no way to know a shape's distance from the camera and rotation if it covers the entire screen. Example with a large floor plane:

![image](https://github.com/godotengine/godot-proposals/assets/180032/3821865e-9b2e-4a9e-ada9-c18d3963e830)

On the other hand, if you have any kind of texture on the shape, you have a way to distinguish its rotation and also get a general sense of scale:

![image](https://github.com/godotengine/godot-proposals/assets/180032/edc1407d-2705-49b3-a631-72400566d90a)

This would likely require the use of triplanar mapping for the debug gizmos, but it's likely worth doing for debug visuals.

**Comment by Arecher** [comment]
I think it would be helpful to be able to set a default color for every `Collision Layer` for the visible debug collision wireframes. Next to being able to set a name for every Layer in the `Project Settings`, at `layer_names/3d_physics/layer_n` setting a color (which could be overwritten on an individual level) would make it a lot easier to read scenes where multiple collisions are present, and make it easier to find wrongly set collision layers.

That would only bring the issue of what happens when a collision is active on multiple layers, in which case it could either automatically create a color inbetween the multiple assigned colors, or simply display the color for the lowest/highest Layer ID.

When not assigned, the default blue wireframe color can just be used.
