### ISSUE TITLE
Implement SailfishOS support

### ISSUE THREAD

**Issue by savegame** [godotengine/godot-proposals#914]
I am using sources from two pull request 
 - https://github.com/godotengine/godot/pull/16470
 - https://github.com/godotengine/godot/pull/9435  

Sources are here: 
https://github.com/savegame/godot/tree/3.2_sailfish_sdl2

PR [here](https://github.com/godotengine/godot/pull/38642)

**Describe the project you are working on:**
this need for any project, if developer want publish their app to SailfishOS platform

**Describe the problem or limitation you are having in your project:**
cant export my game as native for SailfishOS. Sailfish - it linux for mobile phones, its use **rpm** as application  package. Need ability to build godot game directly to Sailfish RPM file form godot editor ( like APK file for android ) 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In my [PR](https://github.com/godotengine/godot/pull/38642) i allready add all what need for exporting Godot games to SailfishOS

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**. 
this successfully new platfrom implementation for godot  
*What is done*  
- export from [Godot Editor](https://github.com/savegame/godot/releases/tag/v3.2.1-stable-sailfish) with SaiflishSDK to native for sailfish RPM package.
- touch screen input
- dynamic orientation events 
- dynamic orientation change
- normal application life cycle 
- sound initialization
- joypad (just compile already exists **libudev** implementation of LinuxJoypad, works nice )
 
*What is not done*  
- gyroscope/accelerometer events
- disable screen blanking when application is open ( just need use some dbus interfaces from mce)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
**Is there a reason why this should be core and not an add-on in the asset library?:**
because need fixes in rendering of godot engine  (Saiflish dont support rotation of clients EGL context, client should dot this by himself )

**Comment by ryliejamesthomas** [comment]
I believe flatpack is also an (new) option for Sailfish

**Comment by Calinou** [comment]
Closing, as SailfishOS won't be maintained in core. Nonetheless, you are welcome to submit fixes and improvements required to make third-party platform ports back to the main Godot repository. It's already possible to develop platform ports without modifying Godot's source code – see [FRT](https://github.com/efornara/frt) for an example of this.

Note that we used to have official HaikuOS support, but it was dropped due to lack of maintenance. It's still available as a [first-party repository](https://github.com/godotengine/godot-haiku-platform), but its development is still inactive. Therefore, I'm not sure if a SailfishOS platform port would be accepted as a first-party @godotengine repository either.

**Comment by savegame** [comment]
I do not has much time to maintenance port for AuroraOS/SailfishOS in Godot's main repo, that is why i was made this port in my own fork of Godot. And i maintenance it there ) 
Last release here:
https://github.com/savegame/godot/releases/tag/3.6-auroraos-1
