### ISSUE TITLE
Keep texture of previously emitted particles when changing the Texture property

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#9226]
### Describe the project you are working on

A 2D project where phantoms are generated by XXXParticles2D, XXX can be "CPU" or "GPU"

### Describe the problem or limitation you are having in your project

Continuation of #9225
Not only the transform should be detailized, but the default synchornization of all texture of particles emitted by a particle emitter should be able to be adjusted by adding a propoerty

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a property `particle_texture_shared`(or `sync_particle_textures`) for XXXParticles2D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When this property is enabled, the behavior is the same as how it was like. While this one is disabled, once the member `texture` gets changed when there has been particles shown on the canvas, the particles having been emitted won't get their texture changed, while from the next emission the particles will display with a new appearance.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, because this requires modification or overhaul on relevant in the source code.

### Is there a reason why this should be core and not an add-on in the asset library?

Same as the previous answer

**Comment by Calinou** [comment]
I'm afraid this isn't technically possible. Internally, the shader used to render particles doesn't keep track of multiple textures (and should avoid doing so without a good reason due to performance concerns). This means that as soon as you set the texture, previously emitted particles will also be affected.

Can you describe a concrete use case for this (i.e. the effect you want to achieve)? Perhaps you can find a workaround using multiple Particles nodes. Feel free to add images/videos to describe the desired effect.

**Comment by Calinou** [comment]
> Though instantiating Sprite2D is a workaround, I personally don't like this solution because of performance consumption of calling add_child() or add_sibling(), and the utilization of large amount of Nodes.

Are you sure this is a bottleneck in your project? I suggest using an implementation based on Sprite2D nodes, which might turn out to perform just fine (especially if you pool the nodes instead of creating and freeing them every frame).

If performance actually becomes a problem with this approach, look into [using servers](https://docs.godotengine.org/en/stable/tutorials/performance/using_servers.html) to draw sprites as opposed to nodes.
