### ISSUE TITLE
Display the godot version instead of a warning sign in the project manager

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#9384]
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/e9cabd26-f4cd-4c1c-8daf-e5e40ec7662c)

It's hiding information behind a mouse hover.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Just display the information instead, optionally keeping the warning sign and the tooltip.
   - this is the easy solution, and probably the best
- Possibly, use a tag managed by the editor for the version, that way you can sort projects per version.
   - this is an idea I like less, but put here just in case

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

| Just a text label                                                                                                     | a text label, and the warning sign                                                                                           | special tag (not user-managed) |
|---------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|----|
| ![image](https://github.com/godotengine/godot-proposals/assets/71937306/e352f7fc-e324-452e-8080-bc76b1dce980) | ![image](https://github.com/godotengine/godot-proposals/assets/71937306/3cffafbc-8a3b-4c3a-af0f-26e01b351819) | ![image](https://github.com/godotengine/godot-proposals/assets/71937306/9f7e686b-80ea-4a4b-9cb1-e80b1a63aa0e) 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often, can't be worked around

### Is there a reason why this should be core and not an add-on in the asset library?

core already

**Comment by Mickeon** [comment]
This warning used to be way more necessary because the only "different" version of Godot prior to this addition was any **3.x** version. Needless to say, projects made in **3.x** are not compatible with **4.x** right out of the box.

Projects made in _later_ versions of 4.x compared to the current one still need to show this warning, as they may use features that did not exist prior in a prior version.

To summarize my opinion, using **4.2** as an example for the "current editor build":

- For any project older than **4.0**, show the warning.
- For **4.0** to **4.2**, this is fine. Only show the project's version number.
    - _It's worth noting that even here there's a chance to break compatibility, as much as we avoid to. It has happened before for multiple minor things._
- For anything after **4.2**, show the warning.
    - This should include patches. Oftentimes the bugs they fix are rather noteworthy.

**Comment by kitbdev** [comment]
The last edited date would also be useful information to show.
