### ISSUE TITLE
Improve output log / enable filtering for warnings, errors and verbose messages

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#971]
**Describe the project you are working on:**
None

**Describe the problem or limitation you are having in your project:**
The output log gets spammed with messages that are irrelevant to regular users for certain interactions with the editor, but they prevent easily catching actual errors that get pushed out of sight this way.

![grafik](https://user-images.githubusercontent.com/8841352/83323405-da38c300-a25e-11ea-9cc0-d5c63d4bcf92.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding an option to the output panel or editor settings that allows controlling the log types would help, like filter type toggles/mask or a log-type level dropdown.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
For example as type toggles:
![V1](https://user-images.githubusercontent.com/8841352/83324683-520aeb80-a267-11ea-8021-191495bd6e5b.jpg)
or
![V2](https://user-images.githubusercontent.com/8841352/83324687-56370900-a267-11ea-9371-1a9b67566852.jpg)
where i'd personally prefer the latter

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think it can without diving deep.
**Is there a reason why this should be core and not an add-on in the asset library?:**
It's not a big change, but it improves working with the engine. It may be hackable with editorplugins but it's such a basic functionality that most users would not now exists if distributed via assetlibrary, as it's typically expected to be part of the editor (as in other engines)

**Comment by rileylyman** [comment]
I took a stab at this in the above PR. Let me know what you think.

**Comment by Flavelius** [comment]
It's somewhat related to log output, so i'll put it here:
in c# when the engine prints an error for [Tool] scripts to the output it only shows a single line pointing to some cpp file, which is not helpful at all. But all it takes is a little stacktrace after that to make it helpful. 
This can be achieved manually with GD.PrintStack().
But doing it manually means wrapping everything in try-catch clauses which is not feasible.
It would be nice if the engine did this for errors by itself (or via editor setting toggle)

**Comment by menip** [comment]
This doesn't reply to idea to filter, though I like filter too. I suggest being able to group messages:

### Describe the problem or limitation you are having in your project
Error, warning, and print output can quickly clutter up debugger output. We can have the same error get printed from different places, at different times. It can be hard to spot specific error in debugger output if you are getting spammed with another error.


### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Each message would be it's own group in debugger output. A group would get the same message appended to it, and the entire group should be collapsible. This way we can quickly see all outputs of message we are looking for, and collapse anything that is not currently important.

This would work very well for Godot errors/warning, and for some user prints. It would not work well for messages that tend to have unique content, for example, print mouse position every frame.

Ways to deal with this:
1. Only group Godot errors/warnings, don't group user prints.
2. Allow user to specify which prints should get grouped, for example `print("Test", group=True)`. I don't like this approach.
3. Have settings/debugger output option to group user prints or not.
4. Automatically group everything. Change so that when there is a single message in a group, it displays like it currently does, and cannot be collapsed.





### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Instead of ![image](https://user-images.githubusercontent.com/22862244/58187689-24f72680-7c6c-11e9-88a8-ec474798da97.png)
we can have
![tmp_delete_later](https://user-images.githubusercontent.com/22862244/110565883-0fcede80-8104-11eb-8dbc-b81345f8fe6b.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. To not get a specific error/warning printed you can disable in settings, but this is not what the problem in question is here. 
### Is there a reason why this should be core and not an add-on in the asset library?
This can't be done via add-on from what I know.
