### ISSUE TITLE
Make the `VERTEX` variable editable in spatial fragment shaders

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot-proposals#974]
**Describe the project you are working on:**
A Signed distance field sphere tracer.

**Describe the problem or limitation you are having in your project:**
The lighting of the fragments do not match their positions calculated in the fragment shader.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It's simple really. Just allow the `VERTEX` built-in variable to be written to. That way, the lighting can be altered to conform to the fragment's "virtual" position.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The vertex is accessed as a varying in the fragment shader, so an intermediate variable must be used instead to allow the `VERTEX` to be written to. Also, it can work just how `MODULATE` was [implemented](https://github.com/godotengine/godot/commit/d8be5a9986ab4125316f086a309374dd35a89744).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Absolutely not. This a visual server level change.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Same reason as above.

**Comment by Calinou** [comment]
I was told by clayjohn on IRC this is not technically feasible, not even with Vulkan :slightly_frowning_face:

**Comment by SIsilicon** [comment]
So it's not possible to just replace all instances of the vertex being used in the fragment shader with a fragment variable, and have that variable be initialized to the vertex varying.

**Comment by drcd1** [comment]
I was playing around with this a little bit and made a little prototype implementation over `3.2.3-stable`. Here you can see shadow maps being properly sampled according to the position.
The images shows a cube where the shader renders an SDF.

![imagem](https://user-images.githubusercontent.com/22733172/107850476-b1f7f100-6dfa-11eb-98e6-e9207f826285.png)



The actual change I did was just a couple of lines. I added the keyword "OUT_POS" to the shader language, and if the user uses it, I add "vertex.xyz = out_pos;" in the glsl shader, and, in `contact_shadow_compute()`, it assigns the correct value to `vec4 source`

There are, however, two problems with the use case described, and this proposal only solves one of them.

a) Lighting sample (including GI)
b) Depthmap generation

a) is solved by allowing the user to write to vertex, as explained by SIsilicon

b) Is more complicated. It's already partially solved by allowing the user to write to gl_DepthFrag, but there are problems with shadow bias, and when rendering Dual Paraboloid maps. I have some ideas on how to solve this (without changing anything if the user doesn't write to vertex), but they might be better suited for a different proposal.

Are there any more problems that I may not be anticipating?

Note: Since some lighting in godot 4 is computed with deferred shading (SDFGI), and there are plans for a deferred pipeline, it might be better to allow users to only write to vertex.z, or gl_FragDepth and compute the new vertex position from that.
This is less general, but I don't know any use cases that benefit from the generality.

**Comment by SIsilicon** [comment]
An example use case would be when you want to render a mesh's lighting to a texture.
The vertices would be transformed into UV space, but actual lighting position stays in view space.

**Comment by jitspoe** [comment]
I also need this for my project so I can do perfect per-texel lighting.  Fortunately it's simply a matter of changing `shader_modes[RS::SHADER_SPATIAL].functions["fragment"].built_ins["VERTEX"] = constt(ShaderLanguage::TYPE_VEC3);` to `shader_modes[RS::SHADER_SPATIAL].functions["fragment"].built_ins["VERTEX"] = ShaderLanguage::TYPE_VEC3;` in shader_types.cpp.

Here's what it looks like without setting the vertex to the nearest texel:
![image](https://github.com/godotengine/godot-proposals/assets/7751182/c4c51a14-359e-437b-8ddd-f88a7e8215cc)

vs with:
![image](https://github.com/godotengine/godot-proposals/assets/7751182/dec06b79-a6d1-4028-b61a-3dfaf1cca5ce)

**Comment by paperjack93** [comment]
I'd also like to have this, for the same reason as jitspoe

**Comment by Calinou** [comment]
@paperjack93 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
