### ISSUE TITLE
Add a method to set column title alignment in Tree (left/center/right)

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot-proposals#982]
**Describe the project you are working on:**
Here's a link to the repository:
~~https://github.com/Barugon/CotA~~
> NOTE: That project has since been rewritten to use egui.

**Describe the problem or limitation you are having in your project:**
I would like to have Tree control column titles visible but there's no way to control the justification of the column title text. Center is the only justification and it doesn't look right.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a method to set the column title justification.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
tree.set_column_title_align(0, ALIGN_LEFT)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No way to set it.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Is that possible?

**Comment by dreadpon** [comment]
A workaround I found (in case you need the same alignment for ALL title columns) is setting
`title_button_hover`, `title_button_normal`, `title_button_pressed` stylebox content margin to a max value (2048).

Set `content_margin_right = 2048` to get left alignment
Set `content_margin_left  = 2048` to get right alignment
Center alignment is the default one (after taking margins into account)

There are probably cases where this workaround can push `Tree` outside it's boundaries, but wrapping it in a container seems to work just fine

**Comment by dcrawl** [comment]
I was looking for this feature too.  I think it would be useful.

I'm using a Tree control as a Table and wanted to Left Align the Column Titles.  I used a different method than dreadpon but it is also a little slipshod.  I hid the Title font by reducing the Alpha to 0.  Then added a _notification() function to redraw the Titles myself.  But I'm just guessing at the positions since the rect_size / position returns for the TreeItem area and not the columns and I don't know how to calculate the Title Height.

Anyway, I'll try the margin workaround to see if that looks better.  Thanks.

**Comment by Barugon** [comment]
I have implemented this functionality on the `Tree` control as `set_column_title_alignment` and `get_column_title_alignment` but I have no idea how to expose it to GDScript. Is there any documentation on that?

**Comment by Barugon** [comment]
Never mind, I figured it out. I'll make a pull request for it.
