### ISSUE TITLE
Highlight the error line in the script editor minimap

### ISSUE THREAD

**Issue by bjr29** [godotengine/godot-proposals#987]
**Describe the project you are working on:**
Making a raymarcher for other projects.

**Describe the problem or limitation you are having in your project:**
Little hard/ awkward to find the error sometimes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Highlight the sidebar, showing all of the code in the code editor, red on the line the error occured.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Example](https://user-images.githubusercontent.com/26935086/83429227-a2cb4180-a42b-11ea-87c2-37d004825f16.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope

**Is there a reason why this should be core and not an add-on in the asset library?:**
Its a small feature and don't think someone would really bother to make an add-on but it is a small quality of life thing I'd like and a few others will I think.

**Comment by poohcom1** [comment]
I think this feature can still be improved from an accessibility standpoint. For me the highlight on the minimap is barely visible (I'm slightly colorblind and I can barely really tell it apart from the current line highlight). 

![image](https://user-images.githubusercontent.com/74857873/209288574-50c35cfb-3f17-434a-9d1c-3820d9453811.png)

A workaround is to change the error highlight color to a more opaque and saturated color, but because it's shared with the main editor error highlight, it makes it obnoxiously bright in the editor.

I think having a separate color options for minimap errors that's more visible by default could be the simple fix, or maybe having the highlight appear over the text in the minimap.

On a side note: Having warnings appear in the minimap would be nice too.
